; Ethernet/IPv4 ARP build, parse, next-hop selection and four-entry cache.
; Derived from BSD-licensed sprinter-rtl8019a ARP framing; rewritten around
; caller-owned buffers and NETDRV with no RTL symbols or direct ISA access.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_ARP_ASM
	DEFINE	_ARP_ASM

	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"
	IFDEF	UNET_DLL
	INCLUDE "coldctx.inc"
	ENDIF

	MODULE ARP

ARP_FRAME_LENGTH	EQU 60
ARP_BODY_LENGTH		EQU 28
ARP_OP_REQUEST		EQU 1
ARP_OP_REPLY		EQU 2
ARP_CACHE_LIFETIME	EQU 60

ARP_ENTRY_VALID		EQU 0
ARP_ENTRY_IP		EQU 1
ARP_ENTRY_MAC		EQU 5
ARP_ENTRY_TIME		EQU 11
ARP_ENTRY_ORDER		EQU 13

	IFDEF	UNET_DLL
; BUILD_REQUEST/BUILD_REPLY/PARSE read/write NET_LOCAL_IP, NET_TARGET_IP,
; NET_NEXT_HOP_IP, NET_RESULT_MAC and NETDRV_STATION_MAC directly -- all
; RUNTIME_BASE-relative addresses in THIS image, fine for a normal EXE but
; meaningless to the separately-assembled, non-relocated cold blob (see
; unet509b_cold.asm's header). Their bodies move there, rewritten to
; reach the same fields through the COLD_CTX pointer block (coldctx.inc)
; instead of a fixed address; what stays here is a trampoline with the
; SAME calling convention, plus IX = &COLD_CTX for the cold side to use.
; UNET_COLD_CTX is defined by memory_dll.inc once BSS_UNET is linked.
BUILD_REQUEST
	PUSH	IX
	LD	IX,UNET_COLD_CTX
	LD	A,CFN_ARP_BUILD_REQUEST
	CALL	@COLD.RUN
	POP	IX
	RET

BUILD_REPLY
	PUSH	IX
	LD	IX,UNET_COLD_CTX
	LD	A,CFN_ARP_BUILD_REPLY
	CALL	@COLD.RUN
	POP	IX
	RET

PARSE
	PUSH	IX
	LD	IX,UNET_COLD_CTX
	LD	A,CFN_ARP_PARSE
	CALL	@COLD.RUN
	POP	IX
	RET

	ELSE

; CLEAR_CACHE initializes all nonpersistent entries.
CLEAR_CACHE
	PUSH	IX,IY
	LD	HL,ARP_CACHE
	LD	BC,ARP_CACHE_ENTRY_SIZE * ARP_CACHE_COUNT
	XOR	A
.CLEAR
	XOR	A
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.CLEAR
	LD	HL,0
	LD	(ARP_CACHE_CLOCK),HL
	POP	IY,IX
	RET

; BUILD_REQUEST
; In: DE=60-byte output, HL=target IPv4. Uses NETDRV station MAC and local IP.
; Out: BC=60. Preserves IX/IY.
BUILD_REQUEST
	PUSH	IX,IY
	LD	(ARP_TARGET_PTR),HL
	LD	(ARP_OUTPUT_PTR),DE
	LD	A,0xFF
	LD	B,6
.RDST
	LD	(DE),A
	INC	DE
	DJNZ	.RDST
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	LD	A,0x06
	LD	(DE),A
	INC	DE
	CALL	WRITE_FIXED_REQUEST
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	HL,NET_LOCAL_IP
	LD	BC,4
	LDIR
	XOR	A
	LD	B,6
.RZERO
	LD	(DE),A
	INC	DE
	DJNZ	.RZERO
	LD	HL,(ARP_TARGET_PTR)
	LD	BC,4
	LDIR
	CALL	PAD_FRAME
	LD	BC,ARP_FRAME_LENGTH
	XOR	A
	POP	IY,IX
	RET

; BUILD_REPLY
; In: DE=output, HL=validated 60+ byte request. Out: BC=60.
BUILD_REPLY
	PUSH	IX,IY
	LD	(ARP_INPUT_PTR),HL
	LD	(ARP_OUTPUT_PTR),DE
	PUSH	HL
	LD	BC,22
	ADD	HL,BC			; requester SHA
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	LD	A,0x06
	LD	(DE),A
	INC	DE
	LD	HL,FIXED_REPLY
	LD	BC,8
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	HL,NET_LOCAL_IP
	LD	BC,4
	LDIR
	POP	HL
	LD	BC,22
	ADD	HL,BC
	LD	BC,6
	LDIR
	LD	HL,(ARP_INPUT_PTR)
	LD	BC,28
	ADD	HL,BC			; requester SPA
	LD	BC,4
	LDIR
	CALL	PAD_FRAME
	LD	BC,ARP_FRAME_LENGTH
	XOR	A
	POP	IY,IX
	RET

WRITE_FIXED_REQUEST
	LD	HL,FIXED_REQUEST
	LD	BC,8
	LDIR
	RET

PAD_FRAME
	XOR	A
	LD	B,18
.PAD
	LD	(DE),A
	INC	DE
	DJNZ	.PAD
	RET

; PARSE
; In: HL=frame, BC=received length. Out: A=1 matching reply for
; NET_TARGET_IP, A=2 request for NET_LOCAL_IP, CF=0; CF=1 otherwise.
; Matching reply MAC is copied to NET_RESULT_MAC. All bounds precede reads.
PARSE
	PUSH	IX,IY
	LD	(ARP_INPUT_PTR),HL
	LD	A,B
	OR	A
	JR	NZ,.LENGTH_OK
	LD	A,C
	CP	42
	JP	C,.NO
.LENGTH_OK
	LD	DE,12
	ADD	HL,DE
	LD	DE,FIXED_ETH_ARP
	LD	B,8
.FIXED
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.NO
	INC	DE
	INC	HL
	DJNZ	.FIXED
	; Ethernet source and ARP sender hardware address must identify one peer.
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,6
	ADD	HL,DE
	LD	DE,(ARP_INPUT_PTR)
	PUSH	HL
	EX	DE,HL
	LD	BC,22
	ADD	HL,BC
	EX	DE,HL
	POP	HL
	CALL	CMP6
	JR	NZ,.NO
	; Opcode is a complete network-order word, not only its low byte.
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,20
	ADD	HL,DE
	LD	A,(HL)
	OR	A
	JR	NZ,.NO
	INC	HL
	LD	A,(HL)
	CP	ARP_OP_REPLY
	JR	Z,.REPLY
	CP	ARP_OP_REQUEST
	JR	NZ,.NO
	CALL	DEST_FOR_US
	JR	NZ,.NO
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,38
	ADD	HL,DE			; TPA
	LD	DE,NET_LOCAL_IP
	CALL	CMP4
	JR	NZ,.NO
	LD	A,2
	OR	A
	JR	.RETURN
.REPLY
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,NETDRV_STATION_MAC
	CALL	CMP6
	JR	NZ,.NO
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,32
	ADD	HL,DE
	LD	DE,NETDRV_STATION_MAC
	CALL	CMP6
	JR	NZ,.NO
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,38
	ADD	HL,DE
	LD	DE,NET_LOCAL_IP
	CALL	CMP4
	JR	NZ,.NO
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,28
	ADD	HL,DE			; SPA
	LD	DE,NET_NEXT_HOP_IP
	CALL	CMP4
	JR	NZ,.NO
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,22
	ADD	HL,DE
	LD	DE,NET_RESULT_MAC
	LD	BC,6
	LDIR
	LD	A,1
	OR	A
	JR	.RETURN
.NO
	LD	A,NETDRV_ERR_PARAMETER
	SCF
.RETURN
	POP	IY,IX
	RET

CMP4
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP
	RET

CMP6
	LD	B,6
.CMP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP
	RET

; Valid ARP requests may be Ethernet broadcast or unicast to this station.
DEST_FOR_US
	LD	HL,(ARP_INPUT_PTR)
	LD	DE,NETDRV_STATION_MAC
	CALL	CMP6
	RET	Z
	LD	HL,(ARP_INPUT_PTR)
	LD	B,6
.BROADCAST
	LD	A,(HL)
	CP	0xFF
	RET	NZ
	INC	HL
	DJNZ	.BROADCAST
	RET

	ENDIF	; UNET_DLL (BUILD_REQUEST/BUILD_REPLY/PARSE trampolines above)

; SELECT_NEXT_HOP
; In: HL=target IP. Copies target to NET_TARGET_IP and chosen address to
; NET_NEXT_HOP_IP. Limited/subnet broadcast returns FF:FF:FF:FF:FF:FF in
; NET_RESULT_MAC with A=1; unicast returns A=0. Missing gateway is parameter.
SELECT_NEXT_HOP
	PUSH	IX,IY
	LD	DE,NET_TARGET_IP
	LD	BC,4
	LDIR
	LD	HL,NET_TARGET_IP
	LD	B,4
	LD	A,0xFF
.LIMITED
	CP	(HL)
	JR	NZ,.SUBNET
	INC	HL
	DJNZ	.LIMITED
	JR	.BROADCAST
.SUBNET
	XOR	A
	LD	(ARP_HOST_BITS),A
	LD	HL,NET_TARGET_IP
	LD	DE,NET_LOCAL_IP
	LD	IX,NET_NETMASK
	LD	B,4
	LD	C,1			; C remains broadcast candidate
.CLASSIFY
	LD	A,(IX+0)
	LD	(ARP_MASK_BYTE),A
	LD	A,(DE)
	XOR	(HL)
	LD	IY,ARP_MASK_BYTE
	AND	(IY+0)
	JR	NZ,.OFF_SUBNET
	LD	A,(IX+0)
	CPL
	LD	IY,ARP_HOST_BYTE
	LD	(IY+0),A
	LD	IY,ARP_HOST_BITS
	OR	(IY+0)
	LD	(IY+0),A
	LD	A,(HL)
	LD	IY,ARP_HOST_BYTE
	AND	(IY+0)
	CP	(IY+0)
	JR	Z,.HOST_ALL_ONE
	LD	C,0
.HOST_ALL_ONE
	INC	HL
	INC	DE
	INC	IX
	DJNZ	.CLASSIFY
	LD	A,(ARP_HOST_BITS)
	OR	A
	JR	Z,.UNICAST
	LD	A,C
	OR	A
	JR	NZ,.BROADCAST
.UNICAST
	LD	HL,NET_TARGET_IP
	JR	.COPY_HOP
.OFF_SUBNET
	LD	HL,NET_GATEWAY
	LD	A,(HL)
	INC	HL
	OR	(HL)
	INC	HL
	OR	(HL)
	INC	HL
	OR	(HL)
	JR	Z,.BAD
	LD	HL,NET_GATEWAY
.COPY_HOP
	LD	DE,NET_NEXT_HOP_IP
	LD	BC,4
	LDIR
	XOR	A
	JR	.RETURN
.BROADCAST
	LD	HL,NET_TARGET_IP
	LD	DE,NET_NEXT_HOP_IP
	LD	BC,4
	LDIR
	LD	HL,NET_RESULT_MAC
	LD	B,6
	LD	A,0xFF
.BMAC
	LD	(HL),A
	INC	HL
	DJNZ	.BMAC
	LD	A,1
	OR	A
	JR	.RETURN
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
.RETURN
	POP	IY,IX
	RET

	IFNDEF	UNET_DLL
; The DLL runs one ARP exchange per CONNECT/UDPOPEN/RESOLVE/PING and keeps
; no cache (decision recorded in the plan): CACHE_LOOKUP/CACHE_INSERT and
; the entry table they walk are never linked in, saving the whole
; ARP_CACHE_COUNT * ARP_CACHE_ENTRY_SIZE reservation plus this code.
; CACHE_LOOKUP
; In: HL=IP, BC=now seconds. Out: NET_RESULT_MAC and CF=0 on live hit.
CACHE_LOOKUP
	PUSH	IX,IY
	LD	(ARP_TARGET_PTR),HL
	LD	(ARP_CACHE_CLOCK),BC
	LD	IX,ARP_CACHE
	LD	B,ARP_CACHE_COUNT
.LOOK
	LD	A,(IX+ARP_ENTRY_VALID)
	OR	A
	JR	Z,.NEXT
	PUSH	BC,IX
	PUSH	IX
	POP	HL
	LD	DE,ARP_ENTRY_IP
	ADD	HL,DE
	LD	DE,(ARP_TARGET_PTR)
	EX	DE,HL
	CALL	CMP4
	POP	IX,BC
	JR	NZ,.NEXT
	LD	HL,(ARP_CACHE_CLOCK)
	LD	E,(IX+ARP_ENTRY_TIME)
	LD	D,(IX+ARP_ENTRY_TIME+1)
	OR	A
	SBC	HL,DE
	LD	DE,ARP_CACHE_LIFETIME+1
	OR	A
	SBC	HL,DE
	JR	NC,.EXPIRE
	PUSH	IX
	POP	HL
	LD	DE,ARP_ENTRY_MAC
	ADD	HL,DE
	LD	DE,NET_RESULT_MAC
	LD	BC,6
	LDIR
	XOR	A
	JR	.RETURN
.EXPIRE
	LD	(IX+ARP_ENTRY_VALID),0
.NEXT
	LD	DE,ARP_CACHE_ENTRY_SIZE
	ADD	IX,DE
	DJNZ	.LOOK
	SCF
.RETURN
	POP	IY,IX
	RET

; CACHE_INSERT
; In: HL=IP, DE=MAC, BC=now seconds. Empty entry wins; otherwise oldest age.
CACHE_INSERT
	PUSH	IX,IY
	LD	(ARP_TARGET_PTR),HL
	LD	(ARP_MAC_PTR),DE
	LD	(ARP_CACHE_CLOCK),BC
	LD	IX,ARP_CACHE
	LD	IY,ARP_CACHE
	LD	HL,0
	LD	(ARP_OLDEST_AGE),HL
	LD	B,ARP_CACHE_COUNT
.SCAN
	LD	A,(IX+ARP_ENTRY_VALID)
	OR	A
	JR	Z,.CHOSEN
	PUSH	BC,IX
	PUSH	IX
	POP	HL
	INC	HL
	LD	DE,(ARP_TARGET_PTR)
	EX	DE,HL
	CALL	CMP4
	POP	IX,BC
	JR	Z,.CHOSEN
	LD	HL,(ARP_CACHE_CLOCK)
	LD	E,(IX+ARP_ENTRY_TIME)
	LD	D,(IX+ARP_ENTRY_TIME+1)
	OR	A
	SBC	HL,DE
	LD	DE,(ARP_OLDEST_AGE)
	OR	A
	SBC	HL,DE
	JR	C,.SCAN_NEXT
	PUSH	IX
	POP	IY
	ADD	HL,DE
	LD	(ARP_OLDEST_AGE),HL
.SCAN_NEXT
	LD	DE,ARP_CACHE_ENTRY_SIZE
	ADD	IX,DE
	DJNZ	.SCAN
	PUSH	IY
	POP	IX
.CHOSEN
	LD	(IX+ARP_ENTRY_VALID),1
	PUSH	IX
	POP	DE
	INC	DE
	LD	HL,(ARP_TARGET_PTR)
	LD	BC,4
	LDIR
	LD	HL,(ARP_MAC_PTR)
	LD	BC,6
	LDIR
	LD	HL,(ARP_CACHE_CLOCK)
	LD	(IX+ARP_ENTRY_TIME),L
	LD	(IX+ARP_ENTRY_TIME+1),H
	XOR	A
	POP	IY,IX
	RET
	ENDIF	; UNET_DLL (CACHE_LOOKUP/CACHE_INSERT)

	IFNDEF	UNET_DLL
FIXED_REQUEST	DB 0,1,0x08,0,6,4,0,ARP_OP_REQUEST
FIXED_REPLY	DB 0,1,0x08,0,6,4,0,ARP_OP_REPLY
; EtherType + ARP htype/ptype/hlen/plen. Opcode is checked separately.
FIXED_ETH_ARP	DB 0x08,0x06,0,1,0x08,0,6,4
ARP_TARGET_PTR	DW 0
ARP_MAC_PTR	DW 0
ARP_INPUT_PTR	DW 0
ARP_OUTPUT_PTR	DW 0
ARP_OLDEST_AGE	DW 0
	ENDIF
ARP_MASK_BYTE	DB 0
ARP_HOST_BYTE	DB 0
ARP_HOST_BITS	DB 0

	ENDMODULE
	ENDIF
