; Reflected IEEE CRC-32 over an Ethernet frame without its FCS.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_CRC32_ASM
	DEFINE	_CRC32_ASM

	INCLUDE "memory.inc"

	MODULE CRC32

; COMPUTE
; In: HL=data, BC=length. Out: CRC32_VALUE little-endian.
; Clobbers AF, BC, DE and HL; preserves IX and IY.
COMPUTE
	PUSH	IX,IY
	LD	A,0xFF
	LD	(CRC32_VALUE+0),A
	LD	(CRC32_VALUE+1),A
	LD	(CRC32_VALUE+2),A
	LD	(CRC32_VALUE+3),A
	LD	(CRC32_REMAINING),BC
.BYTE_LOOP
	LD	BC,(CRC32_REMAINING)
	LD	A,B
	OR	C
	JR	Z,.FINAL
	LD	A,(HL)
	INC	HL
	LD	D,A
	LD	A,(CRC32_VALUE)
	XOR	D
	LD	(CRC32_VALUE),A
	LD	B,8
.BIT_LOOP
	LD	A,(CRC32_VALUE)
	AND	1
	LD	E,A
	LD	A,(CRC32_VALUE+3)
	SRL	A
	LD	(CRC32_VALUE+3),A
	LD	A,(CRC32_VALUE+2)
	RR	A
	LD	(CRC32_VALUE+2),A
	LD	A,(CRC32_VALUE+1)
	RR	A
	LD	(CRC32_VALUE+1),A
	LD	A,(CRC32_VALUE+0)
	RR	A
	LD	(CRC32_VALUE+0),A
	LD	A,E
	OR	A
	JR	Z,.NO_XOR
	LD	A,(CRC32_VALUE+0)
	XOR	0x20
	LD	(CRC32_VALUE+0),A
	LD	A,(CRC32_VALUE+1)
	XOR	0x83
	LD	(CRC32_VALUE+1),A
	LD	A,(CRC32_VALUE+2)
	XOR	0xB8
	LD	(CRC32_VALUE+2),A
	LD	A,(CRC32_VALUE+3)
	XOR	0xED
	LD	(CRC32_VALUE+3),A
.NO_XOR
	DJNZ	.BIT_LOOP
	LD	BC,(CRC32_REMAINING)
	DEC	BC
	LD	(CRC32_REMAINING),BC
	JR	.BYTE_LOOP
.FINAL
	LD	HL,CRC32_VALUE
	LD	B,4
.FINAL_LOOP
	LD	A,(HL)
	CPL
	LD	(HL),A
	INC	HL
	DJNZ	.FINAL_LOOP
	XOR	A
	POP	IY,IX
	RET

	ENDMODULE
	ENDIF
