; Bounded DHCP acquire codec for Ethernet/IPv4/UDP.
; The framing was informed by the BSD-3-Clause sprinter-rtl8019a DHCP client,
; then rewritten for NETDRV buffers, UDP checksums and strict receive bounds.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_DHCP_ASM
	DEFINE	_DHCP_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"

DHCP_CLIENT_PORT	EQU 68
DHCP_SERVER_PORT	EQU 67
DHCP_DISCOVER		EQU 1
DHCP_OFFER		EQU 2
DHCP_REQUEST		EQU 3
DHCP_ACK		EQU 5
DHCP_NAK		EQU 6
DHCP_IP_OFFSET		EQU 14
DHCP_UDP_OFFSET	EQU 34
DHCP_BOOTP_OFFSET	EQU 42
DHCP_OPTIONS_OFFSET	EQU 282
DHCP_MIN_REPLY		EQU 285
DHCP_MAGIC_0		EQU 0x63
DHCP_MAGIC_1		EQU 0x82
DHCP_MAGIC_2		EQU 0x53
DHCP_MAGIC_3		EQU 0x63
DHCP_SEEN_TYPE		EQU 0x01
DHCP_SEEN_MASK		EQU 0x02
DHCP_SEEN_ROUTER	EQU 0x04
DHCP_SEEN_DNS		EQU 0x08
DHCP_SEEN_LEASE	EQU 0x10
DHCP_SEEN_SERVER	EQU 0x20

	MODULE DHCP

; GEN_XID
; In: HL=MAC. Mixes the DSS clock, MAC, R and SP. Must be called with ISA
; closed. Out: DHCP_XID[4], A=0/CF=0. Preserves IX/IY.
GEN_XID
	PUSH	IX,IY
	LD	(DHCP_MAC_PTR),HL
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,H
	LD	(DHCP_XID+0),A
	LD	A,L
	LD	(DHCP_XID+1),A
	LD	A,B
	LD	(DHCP_XID+2),A
	LD	A,R
	LD	(DHCP_XID+3),A
	LD	DE,(DHCP_MAC_PTR)
	LD	HL,DHCP_XID
	LD	B,6
	LD	C,0
.MIX_MAC
	LD	A,(DE)
	XOR	(HL)
	LD	(HL),A
	INC	DE
	INC	HL
	INC	C
	LD	A,C
	AND	3
	JR	NZ,.MIX_NEXT
	LD	HL,DHCP_XID
.MIX_NEXT
	DJNZ	.MIX_MAC
	LD	A,R
	LD	C,A
	LD	HL,0
	ADD	HL,SP
	LD	A,(DHCP_XID+3)
	XOR	C
	XOR	L
	LD	(DHCP_XID+3),A
	XOR	A
	POP	IY,IX
	RET

; BUILD_DISCOVER / BUILD_REQUEST
; In: DE=caller TX buffer, HL=MAC. Out: BC=frame length. Preserves IX/IY.
BUILD_DISCOVER
	PUSH	IX,IY
	LD	A,DHCP_DISCOVER
	CALL	BUILD
	POP	IY,IX
	RET

BUILD_REQUEST
	PUSH	IX,IY
	LD	A,DHCP_REQUEST
	CALL	BUILD
	POP	IY,IX
	RET

BUILD
	LD	(DHCP_BUILD_TYPE),A
	LD	(DHCP_FRAME_PTR),DE
	LD	(DHCP_MAC_PTR),HL
	; Zero the largest emitted prefix so BOOTP fixed fields cannot leak BSS.
	PUSH	DE
	EX	DE,HL
	LD	BC,320
	XOR	A
.ZERO
	XOR	A
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.ZERO
	POP	DE
	; Ethernet broadcast destination and caller MAC source.
	LD	A,0xFF
	LD	B,6
.DST
	LD	(DE),A
	INC	DE
	DJNZ	.DST
	LD	HL,(DHCP_MAC_PTR)
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	; IPv4 fixed header.
	LD	A,0x45
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	INC	DE
	INC	DE			; total length patched later
	LD	A,(DHCP_XID+2)
	LD	(DE),A
	INC	DE
	LD	A,(DHCP_XID+3)
	LD	(DE),A
	INC	DE
	LD	A,0x40			; don't fragment
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,64
	LD	(DE),A
	INC	DE
	LD	A,17
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	B,4
.SRC_ZERO
	LD	(DE),A
	INC	DE
	DJNZ	.SRC_ZERO
	LD	A,0xFF
	LD	B,4
.IP_DST
	LD	(DE),A
	INC	DE
	DJNZ	.IP_DST
	; UDP 68 -> 67, length/checksum patched later.
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,DHCP_CLIENT_PORT
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,DHCP_SERVER_PORT
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	; BOOTP fixed header was zeroed.
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_BOOTP_OFFSET
	ADD	HL,BC
	LD	(HL),1			; BOOTREQUEST
	INC	HL
	LD	(HL),1			; Ethernet
	INC	HL
	LD	(HL),6
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_BOOTP_OFFSET+4
	ADD	HL,BC
	EX	DE,HL
	LD	HL,DHCP_XID
	LD	BC,4
	LDIR
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_BOOTP_OFFSET+10
	ADD	HL,BC
	LD	(HL),0x80		; broadcast flag, wire high byte
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_BOOTP_OFFSET+28
	ADD	HL,BC
	EX	DE,HL
	LD	HL,(DHCP_MAC_PTR)
	LD	BC,6
	LDIR
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_BOOTP_OFFSET+236
	ADD	HL,BC
	LD	(HL),DHCP_MAGIC_0
	INC	HL
	LD	(HL),DHCP_MAGIC_1
	INC	HL
	LD	(HL),DHCP_MAGIC_2
	INC	HL
	LD	(HL),DHCP_MAGIC_3
	INC	HL			; options cursor
	EX	DE,HL
	LD	A,53
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	LD	A,(DHCP_BUILD_TYPE)
	LD	(DE),A
	INC	DE
	CP	DHCP_REQUEST
	JR	NZ,.PARAMS
	LD	A,50
	CALL	APPEND_4_OPTION
	LD	HL,DHCP_OFFERED_IP
	CALL	COPY_OPTION_DATA4
	LD	A,54
	CALL	APPEND_4_OPTION
	LD	HL,DHCP_SERVER_ID
	CALL	COPY_OPTION_DATA4
.PARAMS
	LD	A,55
	LD	(DE),A
	INC	DE
	LD	A,4
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	LD	A,3
	LD	(DE),A
	INC	DE
	LD	A,6
	LD	(DE),A
	INC	DE
	LD	A,51
	LD	(DE),A
	INC	DE
	LD	A,255
	LD	(DE),A
	INC	DE
	CALL	FINISH
	RET

APPEND_4_OPTION
	LD	(DE),A
	INC	DE
	LD	A,4
	LD	(DE),A
	INC	DE
	RET

COPY_OPTION_DATA4
	LD	BC,4
	LDIR
	RET

; Patch lengths and both mandatory checksums.
FINISH
	LD	HL,(DHCP_FRAME_PTR)
	LD	A,E
	SUB	L
	LD	C,A
	LD	A,D
	SBC	A,H
	LD	B,A			; BC=frame length
	LD	(DHCP_FRAME_LENGTH),BC
	LD	HL,BC
	LD	DE,14
	OR	A
	SBC	HL,DE			; IP total length
	PUSH	HL
	LD	DE,(DHCP_FRAME_PTR)
	EX	DE,HL
	LD	BC,DHCP_IP_OFFSET+2
	ADD	HL,BC
	EX	DE,HL			; frame+16
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	POP	HL
	LD	DE,20
	OR	A
	SBC	HL,DE			; UDP length
	LD	(DHCP_UDP_LENGTH),HL
	LD	DE,(DHCP_FRAME_PTR)
	PUSH	DE
	LD	BC,DHCP_UDP_OFFSET+4
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	LD	HL,(DHCP_UDP_LENGTH)
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	POP	HL
	LD	BC,DHCP_IP_OFFSET
	ADD	HL,BC
	PUSH	HL
	LD	BC,20
	CALL	@ETHERNET.CHECKSUM
	EX	DE,HL
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_IP_OFFSET+10
	ADD	HL,BC
	LD	(HL),D
	INC	HL
	LD	(HL),E
	POP	HL			; IP pointer
	LD	BC,(DHCP_UDP_LENGTH)
	CALL	@ETHERNET.UDP_IPV4_CHECKSUM
	LD	A,H
	OR	L
	JR	NZ,.UDP_NONZERO
	LD	HL,0xFFFF		; RFC 768 zero result is transmitted as all ones
.UDP_NONZERO
	EX	DE,HL
	LD	HL,(DHCP_FRAME_PTR)
	LD	BC,DHCP_UDP_OFFSET+6
	ADD	HL,BC
	LD	(HL),D
	INC	HL
	LD	(HL),E
	LD	BC,(DHCP_FRAME_LENGTH)
	XOR	A
	RET

; PARSE_REPLY
; In: HL=Ethernet frame, BC=actual frame length. Out: parsed fields and
; DHCP_MSG_TYPE with CF=0, or parameter/malformed with CF=1. All option TLVs
; are bounded by UDP length; chaddr, XID, IP and UDP checksums are verified.
PARSE_REPLY
	PUSH	IX,IY
	LD	A,1
	LD	(DHCP_PARSE_STAGE),A
	LD	(DHCP_FRAME_PTR),HL
	LD	(DHCP_FRAME_LENGTH),BC
	LD	HL,(DHCP_FRAME_LENGTH)
	LD	DE,DHCP_MIN_REPLY
	OR	A
	SBC	HL,DE
	JP	C,.BAD
.MIN_OK
	LD	HL,(DHCP_FRAME_PTR)
	PUSH	HL
	POP	IX
	LD	DE,NETDRV_STATION_MAC
	CALL	CMP6_IX
	JR	Z,.ETH_DEST_OK
	LD	B,6
.ETH_BROADCAST
	LD	A,(IX+0)
	CP	0xFF
	JP	NZ,.BAD
	INC	IX
	DJNZ	.ETH_BROADCAST
	LD	HL,(DHCP_FRAME_PTR)
	PUSH	HL
	POP	IX
.ETH_DEST_OK
	LD	A,(IX+12)
	CP	0x08
	JP	NZ,.BAD
	LD	A,(IX+13)
	OR	A
	JP	NZ,.BAD
	LD	A,(IX+14)
	CP	0x45
	JP	NZ,.BAD
	LD	A,(IX+20)
	AND	0x3F
	JP	NZ,.BAD
	LD	A,(IX+21)
	OR	A
	JP	NZ,.BAD
	LD	A,(IX+23)
	CP	17
	JP	NZ,.BAD
	LD	H,(IX+16)
	LD	L,(IX+17)		; IP total
	LD	DE,20+8+240+3
	OR	A
	SBC	HL,DE
	JP	C,.BAD
	ADD	HL,DE
	LD	(DHCP_IP_LENGTH),HL
	LD	DE,14
	ADD	HL,DE
	LD	DE,(DHCP_FRAME_LENGTH)
	OR	A
	SBC	HL,DE
	JP	NC,.IP_MAY_EQUAL
	JR	.IP_LENGTH_OK
.IP_MAY_EQUAL
	LD	A,H
	OR	L
	JP	NZ,.BAD
.IP_LENGTH_OK
	LD	A,2
	LD	(DHCP_PARSE_STAGE),A
	LD	HL,(DHCP_FRAME_PTR)
	LD	DE,DHCP_IP_OFFSET
	ADD	HL,DE
	PUSH	HL
	LD	BC,20
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,.BAD_POP
	POP	HL
	PUSH	HL
	POP	IX
	LD	A,(IX+20)		; UDP source high via IP pointer +20
	OR	A
	JP	NZ,.BAD
	LD	A,(IX+21)
	CP	DHCP_SERVER_PORT
	JP	NZ,.BAD
	LD	A,(IX+22)
	OR	A
	JP	NZ,.BAD
	LD	A,(IX+23)
	CP	DHCP_CLIENT_PORT
	JP	NZ,.BAD
	LD	H,(IX+24)
	LD	L,(IX+25)
	LD	(DHCP_UDP_LENGTH),HL
	LD	DE,8+240+3
	OR	A
	SBC	HL,DE
	JP	C,.BAD
	ADD	HL,DE
	LD	DE,(DHCP_IP_LENGTH)
	LD	BC,20
	EX	DE,HL
	OR	A
	SBC	HL,BC			; IP payload
	EX	DE,HL
	OR	A
	SBC	HL,DE			; UDP - IP payload
	JP	NZ,.BAD
	; UDP checksum 0000 is legal in IPv4; otherwise verify pseudo-header.
	LD	A,(IX+26)
	OR	(IX+27)
	JR	Z,.UDP_OK
	PUSH	IX
	POP	HL
	LD	BC,(DHCP_UDP_LENGTH)
	CALL	@ETHERNET.UDP_IPV4_CHECKSUM
	LD	A,H
	OR	L
	JP	NZ,.BAD
.UDP_OK
	LD	A,3
	LD	(DHCP_PARSE_STAGE),A
	PUSH	IX
	POP	HL
	LD	DE,28			; BOOTP starts IP+28
	ADD	HL,DE
	PUSH	HL
	POP	IY
	LD	A,(IY+0)
	CP	2
	JP	NZ,.BAD
	LD	A,(IY+1)
	CP	1
	JP	NZ,.BAD
	LD	A,(IY+2)
	CP	6
	JP	NZ,.BAD
	LD	HL,DHCP_XID
	PUSH	IY
	POP	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	LD	B,4
.XID
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.BAD
	INC	DE
	INC	HL
	DJNZ	.XID
	LD	HL,(DHCP_MAC_PTR)
	PUSH	IY
	POP	DE
	LD	BC,28
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	LD	B,6
.CHADDR
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.BAD
	INC	DE
	INC	HL
	DJNZ	.CHADDR
	PUSH	IY
	POP	HL
	LD	DE,236
	ADD	HL,DE
	LD	A,(HL)
	CP	DHCP_MAGIC_0
	JP	NZ,.BAD
	INC	HL
	LD	A,(HL)
	CP	DHCP_MAGIC_1
	JP	NZ,.BAD
	INC	HL
	LD	A,(HL)
	CP	DHCP_MAGIC_2
	JP	NZ,.BAD
	INC	HL
	LD	A,(HL)
	CP	DHCP_MAGIC_3
	JP	NZ,.BAD
	LD	A,4
	LD	(DHCP_PARSE_STAGE),A
	; Reset candidates, then capture yiaddr and bounded options.
	CALL	CLEAR_FIELDS
	PUSH	IY
	POP	HL
	LD	DE,16
	ADD	HL,DE
	LD	DE,DHCP_OFFERED_IP
	LD	BC,4
	LDIR
	PUSH	IY
	POP	HL
	LD	DE,240
	ADD	HL,DE
	LD	DE,(DHCP_UDP_LENGTH)
	LD	BC,8+240
	EX	DE,HL
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L			; option bytes available
	EX	DE,HL			; DE count (unused), HL cursor lost! restore
	PUSH	IY
	POP	HL
	LD	DE,240
	ADD	HL,DE
	CALL	PARSE_OPTIONS
	JP	C,.BAD
	LD	A,5
	LD	(DHCP_PARSE_STAGE),A
	LD	A,(DHCP_MSG_TYPE)
	CP	DHCP_NAK
	JR	Z,.CHECK_SERVER
	CP	DHCP_OFFER
	JR	Z,.CHECK_OFFER
	CP	DHCP_ACK
	JP	NZ,.BAD
	LD	A,(DHCP_OPTION_SEEN)
	AND	DHCP_SEEN_MASK | DHCP_SEEN_LEASE
	CP	DHCP_SEEN_MASK | DHCP_SEEN_LEASE
	JP	NZ,.BAD
.CHECK_OFFER
	LD	HL,DHCP_OFFERED_IP
	LD	B,4
	XOR	A
.YIADDR
	OR	(HL)
	INC	HL
	DJNZ	.YIADDR
	JP	Z,.BAD
.CHECK_SERVER
	LD	A,(DHCP_OPTION_SEEN)
	AND	DHCP_SEEN_TYPE | DHCP_SEEN_SERVER
	CP	DHCP_SEEN_TYPE | DHCP_SEEN_SERVER
	JP	NZ,.BAD
	XOR	A
	POP	IY,IX
	RET
.BAD_POP
	POP	HL
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

CLEAR_FIELDS
	LD	HL,DHCP_MSG_TYPE
	LD	BC,1+4+4+4+4+4+4+4
	XOR	A
.CF
	XOR	A
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.CF
	LD	(DHCP_OPTION_SEEN),A
	RET

; HL=options, BC=exact bytes remaining. Requires END and validates each TLV.
PARSE_OPTIONS
.NEXT
	LD	A,B
	OR	C
	JP	Z,.MALFORMED
	LD	A,(HL)
	INC	HL
	DEC	BC
	CP	255
	JP	Z,.END
	OR	A
	JR	Z,.NEXT
	LD	(DHCP_OPTION_CODE),A
	LD	A,B
	OR	C
	JP	Z,.MALFORMED
	LD	A,(HL)
	INC	HL
	DEC	BC
	LD	(DHCP_OPTION_LENGTH),A
	LD	E,A
	LD	D,0
	PUSH	HL
	LD	HL,BC
	OR	A
	SBC	HL,DE
	POP	HL
	JP	C,.MALFORMED
	LD	A,(DHCP_OPTION_CODE)
	CP	53
	JR	Z,.TYPE
	CP	1
	JR	Z,.MASK
	CP	3
	JR	Z,.ROUTER
	CP	6
	JR	Z,.DNS
	CP	51
	JP	Z,.LEASE
	CP	54
	JP	Z,.SERVER
	JP	.SKIP
.TYPE
	LD	A,(DHCP_OPTION_LENGTH)
	CP	1
	JP	NZ,.MALFORMED
	LD	A,(HL)
	LD	(DHCP_MSG_TYPE),A
	LD	A,(DHCP_OPTION_SEEN)
	OR	DHCP_SEEN_TYPE
	LD	(DHCP_OPTION_SEEN),A
	JP	.SKIP
.MASK
	LD	A,(DHCP_OPTION_LENGTH)
	CP	4
	JP	NZ,.MALFORMED
	LD	DE,DHCP_MASK
	LD	A,DHCP_SEEN_MASK
	JR	.COPY4
.ROUTER
	LD	A,(DHCP_OPTION_LENGTH)
	CP	4
	JP	C,.MALFORMED
	AND	3
	JP	NZ,.MALFORMED
	LD	DE,DHCP_ROUTER
	LD	A,DHCP_SEEN_ROUTER
	JR	.COPY4
.SERVER
	LD	A,(DHCP_OPTION_LENGTH)
	CP	4
	JP	NZ,.MALFORMED
	LD	DE,DHCP_SERVER_ID
	LD	A,DHCP_SEEN_SERVER
.COPY4
	LD	(DHCP_OPTION_BIT),A
	PUSH	HL,BC
	LD	BC,4
	LDIR
	POP	BC,HL
	LD	A,(DHCP_OPTION_BIT)
	LD	E,A
	LD	A,(DHCP_OPTION_SEEN)
	OR	E
	LD	(DHCP_OPTION_SEEN),A
	JR	.SKIP
.DNS
	LD	A,(DHCP_OPTION_LENGTH)
	CP	4
	JR	C,.MALFORMED
	AND	3
	JR	NZ,.MALFORMED
	PUSH	HL,BC
	LD	DE,DHCP_DNS1
	LD	BC,4
	LDIR
	POP	BC,HL
	LD	A,(DHCP_OPTION_SEEN)
	OR	DHCP_SEEN_DNS
	LD	(DHCP_OPTION_SEEN),A
	LD	A,(DHCP_OPTION_LENGTH)
	CP	8
	JR	C,.SKIP
	PUSH	HL,BC
	LD	DE,4
	ADD	HL,DE
	LD	DE,DHCP_DNS2
	LD	BC,4
	LDIR
	POP	BC,HL
	JR	.SKIP
.LEASE
	LD	A,(DHCP_OPTION_LENGTH)
	CP	4
	JR	NZ,.MALFORMED
	LD	A,(HL)
	LD	(DHCP_LEASE_SECS+3),A
	INC	HL
	LD	A,(HL)
	LD	(DHCP_LEASE_SECS+2),A
	INC	HL
	LD	A,(HL)
	LD	(DHCP_LEASE_SECS+1),A
	INC	HL
	LD	A,(HL)
	LD	(DHCP_LEASE_SECS+0),A
	DEC	HL
	DEC	HL
	DEC	HL
	LD	A,(DHCP_OPTION_SEEN)
	OR	DHCP_SEEN_LEASE
	LD	(DHCP_OPTION_SEEN),A
.SKIP
	LD	A,(DHCP_OPTION_LENGTH)
	LD	E,A
	LD	D,0
	ADD	HL,DE
	PUSH	HL
	LD	HL,BC
	OR	A
	SBC	HL,DE
	LD	B,H
	LD	C,L
	POP	HL
	JP	.NEXT
.END
	XOR	A
	RET
.MALFORMED
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET

; Compare IX[0..5] with DE[0..5], preserving IX and returning Z on equality.
CMP6_IX
	PUSH	IX
	LD	B,6
.LOOP
	LD	A,(DE)
	CP	(IX+0)
	JR	NZ,.DONE
	INC	DE
	INC	IX
	DJNZ	.LOOP
.DONE
	POP	IX
	RET

DHCP_MAC_PTR		DW 0
DHCP_FRAME_PTR		DW 0
DHCP_FRAME_LENGTH	DW 0
DHCP_IP_LENGTH		DW 0
DHCP_UDP_LENGTH	DW 0
DHCP_BUILD_TYPE	DB 0
DHCP_OPTION_CODE	DB 0
DHCP_OPTION_LENGTH	DB 0
DHCP_OPTION_BIT	DB 0

	ENDMODULE
	ENDIF
