; Strict backend-neutral DNS A/IN codec with bounded compression parsing.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_DNS_ASM
	DEFINE	_DNS_ASM

	INCLUDE "dns_ntp.inc"
	INCLUDE "netdrv.inc"

	MODULE DNS

; VALIDATE_NAME
; In: HL=ASCIIZ ASCII hostname. Out: BC=wire-name length, CF=0. A trailing dot
; is accepted. Empty labels, labels over 63, non-ASCII/control bytes, a wire
; name over 255 bytes, wrap and reads at/above C000h are rejected. IX/IY kept.
VALIDATE_NAME
	PUSH	IX,IY
	LD	DE,0			; textual bytes
	LD	B,0			; current label bytes
	LD	C,0			; completed labels
.VN_NEXT
	LD	A,H
	CP	0xC0
	JP	NC,.VN_BAD
	LD	A,(HL)
	OR	A
	JR	Z,.VN_END
	INC	DE
	LD	A,D
	OR	A
	JP	NZ,.VN_BAD		; command/API names are at most 255 bytes
	LD	A,(HL)
	INC	HL
	CP	'.'
	JR	Z,.VN_DOT
	CP	0x21
	JP	C,.VN_BAD
	CP	0x7F
	JP	NC,.VN_BAD
	INC	B
	LD	A,B
	CP	64
	JP	NC,.VN_BAD
	JR	.VN_NEXT
.VN_DOT
	LD	A,B
	OR	A
	JP	Z,.VN_BAD
	LD	B,0
	INC	C
	JR	.VN_NEXT
.VN_END
	LD	A,B
	OR	A
	JR	NZ,.VN_FINAL_LABEL
	LD	A,C
	OR	A
	JP	Z,.VN_BAD
	; A trailing dot is already present in the textual byte count; only the
	; terminating root octet remains additional on the wire.
	EX	DE,HL
	INC	HL
	JR	.VN_LIMIT
.VN_FINAL_LABEL
	EX	DE,HL
	INC	HL			; first label length replaces no text byte
	INC	HL			; terminating root
.VN_LIMIT
	LD	DE,DNS_MAX_WIRE_NAME+1
	OR	A
	SBC	HL,DE
	JP	NC,.VN_BAD
	ADD	HL,DE
	LD	B,H
	LD	C,L
	XOR	A
	POP	IY,IX
	RET
.VN_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; BUILD_QUERY
; In HL=DNSQB descriptor. Out BC=payload length. Caller owns all storage.
; Preserves IX/IY.
BUILD_QUERY
	PUSH	IX,IY
	LD	BC,DNSQB_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BQ_BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+DNSQB_NAME)
	LD	H,(IX+DNSQB_NAME+1)
	CALL	VALIDATE_NAME
	JP	C,.BQ_BAD
	LD	H,B
	LD	L,C
	LD	DE,12+4
	ADD	HL,DE
	JP	C,.BQ_BAD
	LD	(DNS_QUERY_LENGTH),HL
	LD	E,(IX+DNSQB_CAPACITY)
	LD	D,(IX+DNSQB_CAPACITY+1)
	OR	A
	SBC	HL,DE
	JP	C,.BQ_CAP_OK
	JP	NZ,.BQ_BAD
.BQ_CAP_OK
	LD	L,(IX+DNSQB_BUFFER)
	LD	H,(IX+DNSQB_BUFFER+1)
	LD	BC,(DNS_QUERY_LENGTH)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BQ_BAD
	LD	E,(IX+DNSQB_BUFFER)
	LD	D,(IX+DNSQB_BUFFER+1)
	LD	A,(IX+DNSQB_XID+1)
	LD	(DE),A
	INC	DE
	LD	A,(IX+DNSQB_XID)
	LD	(DE),A
	INC	DE
	LD	A,1			; RD=1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	A,1			; QDCOUNT=1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	B,6
.BQ_ZERO_COUNTS
	LD	(DE),A
	INC	DE
	DJNZ	.BQ_ZERO_COUNTS
	LD	L,(IX+DNSQB_NAME)
	LD	H,(IX+DNSQB_NAME+1)
.BQ_LABEL
	PUSH	DE
	INC	DE			; reserve label length
	LD	B,0
.BQ_CHAR
	LD	A,(HL)
	OR	A
	JR	Z,.BQ_NAME_END
	INC	HL
	CP	'.'
	JR	Z,.BQ_LABEL_END
	LD	(DE),A
	INC	DE
	INC	B
	JR	.BQ_CHAR
.BQ_LABEL_END
	POP	IY
	LD	(IY+0),B
	LD	A,(HL)
	OR	A
	JR	NZ,.BQ_LABEL
	JR	.BQ_ROOT
.BQ_NAME_END
	POP	IY
	LD	(IY+0),B
.BQ_ROOT
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A			; QTYPE A
	INC	DE
	LD	A,DNS_TYPE_A
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A			; QCLASS IN
	INC	DE
	LD	A,DNS_CLASS_IN
	LD	(DE),A
	LD	HL,(DNS_QUERY_LENGTH)
	LD	(IX+DNSQB_LENGTH),L
	LD	(IX+DNSQB_LENGTH+1),H
	LD	B,H
	LD	C,L
	XOR	A
	POP	IY,IX
	RET
.BQ_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE_REPLY
; In HL=DNSP descriptor. Out RESULT receives the first A/IN address. A stale
; transaction returns PARAMETER; malformed data/temporary RCODE returns
; PROTOCOL; NXDOMAIN and NO_ANSWER are distinct stable statuses.
PARSE_REPLY
	PUSH	IX,IY
	LD	BC,DNSP_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PR_BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+DNSP_BUFFER)
	LD	H,(IX+DNSP_BUFFER+1)
	LD	C,(IX+DNSP_LENGTH)
	LD	B,(IX+DNSP_LENGTH+1)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PR_BAD
	LD	A,B
	OR	A
	JR	NZ,.PR_MIN_OK
	LD	A,C
	CP	12
	JP	C,.PR_BAD
.PR_MIN_OK
	LD	(DNS_PACKET_START),HL
	ADD	HL,BC
	LD	(DNS_PACKET_END),HL
	LD	HL,(DNS_PACKET_START)
	LD	A,(IX+DNSP_XID+1)
	CP	(HL)
	JP	NZ,.PR_STALE
	INC	HL
	LD	A,(IX+DNSP_XID)
	CP	(HL)
	JP	NZ,.PR_STALE
	INC	HL
	LD	A,(HL)
	AND	0xFA			; QR=1, opcode=0, TC=0
	CP	0x80
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	AND	0x0F
	LD	(IX+DNSP_RCODE),A
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	CP	1
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,.PR_BAD		; ANCOUNT is bounded to 64
	INC	HL
	LD	A,(HL)
	CP	65
	JP	NC,.PR_BAD
	LD	(DNS_ANSWERS_LEFT),A
	LD	HL,(DNS_PACKET_START)
	LD	DE,12
	ADD	HL,DE
	CALL	SKIP_NAME
	JP	C,.PR_BAD
	LD	BC,4
	CALL	REGION_TO_END
	JP	C,.PR_BAD
	LD	A,(DE)
	OR	A
	JP	NZ,.PR_BAD
	INC	DE
	LD	A,(DE)
	CP	DNS_TYPE_A
	JP	NZ,.PR_BAD
	INC	DE
	LD	A,(DE)
	OR	A
	JP	NZ,.PR_BAD
	INC	DE
	LD	A,(DE)
	CP	DNS_CLASS_IN
	JP	NZ,.PR_BAD
	INC	DE
	LD	A,(IX+DNSP_RCODE)
	CP	3
	JP	Z,.PR_NXDOMAIN
	OR	A
	JP	NZ,.PR_PROTOCOL
.PR_ANSWER
	LD	A,(DNS_ANSWERS_LEFT)
	OR	A
	JP	Z,.PR_NO_ANSWER
	DEC	A
	LD	(DNS_ANSWERS_LEFT),A
	EX	DE,HL
	CALL	SKIP_NAME
	JP	C,.PR_BAD
	LD	BC,10
	CALL	REGION_TO_END
	JP	C,.PR_BAD
	LD	A,(DE)
	LD	(DNS_RR_TYPE_HI),A
	INC	DE
	LD	A,(DE)
	LD	(DNS_RR_TYPE_LO),A
	INC	DE
	LD	A,(DE)
	LD	(DNS_RR_CLASS_HI),A
	INC	DE
	LD	A,(DE)
	LD	(DNS_RR_CLASS_LO),A
	LD	HL,5
	ADD	HL,DE			; from class low to RDLENGTH high
	LD	A,(HL)
	LD	B,A
	INC	HL
	LD	C,(HL)
	INC	HL			; HL=RDATA
	PUSH	HL
	EX	DE,HL
	LD	H,B
	LD	L,C
	LD	B,H
	LD	C,L
	CALL	REGION_TO_END
	POP	HL
	JP	C,.PR_BAD
	LD	A,(DNS_RR_TYPE_HI)
	OR	A
	JR	NZ,.PR_SKIP
	LD	A,(DNS_RR_TYPE_LO)
	CP	DNS_TYPE_A
	JR	NZ,.PR_SKIP
	LD	A,(DNS_RR_CLASS_HI)
	OR	A
	JR	NZ,.PR_SKIP
	LD	A,(DNS_RR_CLASS_LO)
	CP	DNS_CLASS_IN
	JR	NZ,.PR_SKIP
	LD	A,B
	OR	A
	JR	NZ,.PR_SKIP
	LD	A,C
	CP	4
	JR	NZ,.PR_SKIP
	LD	E,(IX+DNSP_RESULT)
	LD	D,(IX+DNSP_RESULT+1)
	PUSH	HL
	EX	DE,HL
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	EX	DE,HL
	POP	HL
	JP	C,.PR_BAD
	LDIR
	XOR	A
	POP	IY,IX
	RET
.PR_SKIP
	ADD	HL,BC
	EX	DE,HL
	JP	.PR_ANSWER
.PR_STALE
	LD	A,NETDRV_ERR_PARAMETER
	JR	.PR_ERROR
.PR_NXDOMAIN
	LD	A,NETDRV_ERR_DNS_NXDOMAIN
	JR	.PR_ERROR
.PR_NO_ANSWER
	LD	A,NETDRV_ERR_DNS_NO_ANSWER
	JR	.PR_ERROR
.PR_BAD
.PR_PROTOCOL
	LD	A,NETDRV_ERR_PROTOCOL
.PR_ERROR
	SCF
	POP	IY,IX
	RET

; SKIP_NAME validates a DNS name, including compression chains. HL is the
; encoded name; DE returns the cursor after its original representation.
SKIP_NAME
	LD	DE,0
	LD	A,DNS_MAX_POINTERS
	LD	(DNS_POINTERS_LEFT),A
	LD	A,DNS_MAX_WIRE_NAME
	LD	(DNS_NAME_LEFT),A
.SN_NEXT
	LD	BC,1
	EX	DE,HL
	CALL	REGION_TO_END
	EX	DE,HL
	JR	C,.SN_BAD
	LD	A,(HL)
	OR	A
	JR	Z,.SN_ZERO
	AND	0xC0
	CP	0xC0
	JR	Z,.SN_POINTER
	OR	A
	JR	NZ,.SN_BAD
	LD	A,(HL)
	CP	64
	JR	NC,.SN_BAD
	INC	HL
	LD	C,A
	LD	B,0
	PUSH	HL
	EX	DE,HL
	CALL	REGION_TO_END
	EX	DE,HL
	POP	HL
	JR	C,.SN_BAD
	LD	A,(DNS_NAME_LEFT)
	SUB	C
	JR	C,.SN_BAD
	DEC	A
	JR	C,.SN_BAD
	LD	(DNS_NAME_LEFT),A
	ADD	HL,BC
	JR	.SN_NEXT
.SN_POINTER
	LD	BC,2
	EX	DE,HL
	CALL	REGION_TO_END
	EX	DE,HL
	JR	C,.SN_BAD
	LD	A,(DNS_POINTERS_LEFT)
	DEC	A
	JR	Z,.SN_BAD
	LD	(DNS_POINTERS_LEFT),A
	LD	A,D
	OR	E
	JR	NZ,.SN_HAVE_RETURN
	PUSH	HL
	INC	HL
	INC	HL
	EX	DE,HL
	POP	HL
.SN_HAVE_RETURN
	LD	A,(HL)
	AND	0x3F
	LD	B,A
	INC	HL
	LD	C,(HL)
	LD	HL,(DNS_PACKET_START)
	ADD	HL,BC
	EX	DE,HL
	LD	BC,1
	CALL	REGION_TO_END
	EX	DE,HL
	JR	C,.SN_BAD
	JR	.SN_NEXT
.SN_ZERO
	LD	A,(DNS_NAME_LEFT)
	OR	A
	JR	Z,.SN_BAD
	INC	HL
	LD	A,D
	OR	E
	RET	NZ
	EX	DE,HL
	OR	A
	RET
.SN_BAD
	SCF
	RET

; DE=start, BC=length. CF=1 if the region exceeds the packet end or wraps.
REGION_TO_END
	PUSH	HL
	PUSH	DE
	PUSH	BC
	EX	DE,HL
	ADD	HL,BC
	JR	C,.RE_BAD
	LD	BC,(DNS_PACKET_END)
	OR	A
	SBC	HL,BC
	JR	C,.RE_OK
	JR	Z,.RE_OK
.RE_BAD
	SCF
	POP	BC
	POP	DE
	POP	HL
	RET
.RE_OK
	OR	A
	POP	BC
	POP	DE
	POP	HL
	RET

DNS_QUERY_LENGTH	DW 0
DNS_PACKET_START	DW 0
DNS_PACKET_END		DW 0
DNS_ANSWERS_LEFT	DB 0
DNS_POINTERS_LEFT	DB 0
DNS_NAME_LEFT		DB 0
DNS_RR_TYPE_HI		DB 0
DNS_RR_TYPE_LO		DB 0
DNS_RR_CLASS_HI	DB 0
DNS_RR_CLASS_LO	DB 0

	ENDMODULE
	ENDIF
