; Read-only 3C509B discovery, EEPROM and activation.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_EL3_ASM
	DEFINE	_EL3_ASM

	INCLUDE "sprinter.inc"
	INCLUDE "isa.inc"
	INCLUDE "el3.inc"
	INCLUDE "memory.inc"

	MODULE EL3

; CONFIGURE
; In: A=slot, HL=ID port. Out: EL3_OK/CF=0 or explicit error/CF=1.
; Preserves IX and IY.
CONFIGURE
	PUSH	IX,IY
	CP	2
	JR	NC,.BAD
	LD	(SLOT),A
	LD	A,H
	CP	0x01
	JR	NZ,.BAD
	LD	A,L
	AND	0x0F
	JR	NZ,.BAD
	LD	A,L
	CP	0xF1
	JR	NC,.BAD
	LD	(EL3_IDPORT),HL
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; DISCOVER
; Performs classic reset, reads all 64 EEPROM words through the ID port,
; and validates IDs, MAC, and checksums. It never activates or writes EEPROM.
; Out: EL3_OK/CF=0 or explicit error/CF=1. Preserves IX and IY.
DISCOVER
	PUSH	IX,IY
	LD	HL,0
	LD	(EL3_LAST_TICKS),HL
	LD	A,EL3_STAGE_RESET
	LD	(EL3_LAST_STAGE),A
	CALL	ID_SEQUENCE
	JR	C,.RETURN
	LD	A,EL3_ID_GLOBAL_RESET
	CALL	ID_WRITE
	JR	C,.RETURN
	CALL	WAIT_ONE_QUANTUM
	CALL	ID_SEQUENCE
	JR	C,.RETURN
	LD	A,EL3_ID_TAG_ZERO
	CALL	ID_WRITE
	JR	C,.RETURN
	LD	A,EL3_STAGE_EEPROM
	LD	(EL3_LAST_STAGE),A
	LD	HL,EEPROM_BUFFER
	XOR	A
.EEPROM_LOOP
	PUSH	AF,HL
	CALL	ID_READ_WORD
	JR	C,.READ_FAILED
	EX	DE,HL
	POP	HL,AF
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	INC	A
	CP	0x40
	JR	NZ,.EEPROM_LOOP
	LD	A,EL3_STAGE_VALIDATE
	LD	(EL3_LAST_STAGE),A
	CALL	@EL3ALG.VALIDATE
	JR	.RETURN
.READ_FAILED
	POP	HL
	INC	SP
	INC	SP
.RETURN
	POP	IY,IX
	RET

; ACTIVATE
; In: A=0 for EEPROM base, A=1 for explicit base in HL.
; Out: active base in HL and EL3_BASE, EL3_OK/CF=0 or error/CF=1.
; Preserves IX and IY.
ACTIVATE
	PUSH	IX,IY
	LD	D,A
	LD	A,EL3_STAGE_ACTIVATE
	LD	(EL3_LAST_STAGE),A
	LD	A,D
	OR	A
	JR	NZ,.EXPLICIT
	LD	A,(EEPROM_BUFFER + 0x08*2)
	AND	0x1F
	CALL	@EL3ALG.BASE_DECODE
	JR	C,.RETURN
	LD	(EL3_BASE),HL
	LD	A,EL3_ID_ACTIVATE_EEPROM
	JR	.WRITE_ACTIVATE
.EXPLICIT
	CALL	@EL3ALG.BASE_ENCODE
	JR	C,.RETURN
	LD	(EL3_BASE),HL
	OR	EL3_ID_ACTIVATE_BASE
.WRITE_ACTIVATE
	CALL	ID_WRITE
	JR	C,.RETURN
	CALL	VERIFY_ACTIVE
	JR	C,.RETURN
	LD	HL,(EL3_BASE)
	XOR	A
.RETURN
	POP	IY,IX
	RET

; VERIFY_ACTIVE
; Reads Window 0 manufacturer/product registers using adjacent low/high cycles.
; Preserves IX and IY.
VERIFY_ACTIVE
	PUSH	IX,IY
	LD	A,EL3_STAGE_VERIFY
	LD	(EL3_LAST_STAGE),A
	LD	E,EL3_REG_MFG_ID
	CALL	READ16
	JR	C,.RETURN
	LD	DE,EL3_MFG_3COM
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	LD	E,EL3_REG_PRODUCT_ID
	CALL	READ16
	JR	C,.RETURN
	LD	DE,EL3_PRODUCT_3C509B_TPO
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	XOR	A
.RETURN
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_VERIFY
	SCF
	JR	.RETURN

; ID_SEQUENCE
; Sends two zero selector bytes and exactly 255 LFSR bytes (FF through 98).
; Preserves IX and IY.
ID_SEQUENCE
	PUSH	IX,IY
	LD	A,(SLOT)
	CALL	@ISA.OPEN
	JR	C,.ISA_ERROR
	LD	BC,(EL3_IDPORT)
	CALL	@ISA.MAP_POINTER
	XOR	A
	LD	(HL),A
	LD	(HL),A
	LD	C,EL3_LFSR_SEED
	LD	B,0xFF
.LOOP
	LD	A,C
	LD	(HL),A
	CALL	@EL3ALG.LFSR_NEXT
	LD	C,A
	DJNZ	.LOOP
	CALL	@ISA.CLOSE
	JR	C,.ISA_ERROR
	LD	A,C
	CP	EL3_LFSR_SEED
	JR	NZ,.INTERNAL
	XOR	A
	POP	IY,IX
	RET
.ISA_ERROR
	LD	A,EL3_ERR_ISA_STATE
	SCF
	POP	IY,IX
	RET
.INTERNAL
	LD	A,EL3_ERR_VERIFY
	SCF
	POP	IY,IX
	RET

; ID_WRITE
; In: A=ID command. Out: explicit status. Preserves IX and IY.
ID_WRITE
	PUSH	IX,IY
	LD	(ID_COMMAND),A
	LD	BC,(EL3_IDPORT)
	LD	A,(SLOT)
	LD	D,A
	LD	A,(ID_COMMAND)
	CALL	@ISA.WRITE8
	JR	NC,.OK
	LD	A,EL3_ERR_ISA_STATE
	SCF
	POP	IY,IX
	RET
.OK
	XOR	A
	POP	IY,IX
	RET

; ID_READ_WORD
; In: A=EEPROM address 00..3F. Out: HL=word and CF=0, or error.
; The documented 162 us operation is followed by one CYCLES21 quantum;
; the ISA window is closed for the entire wait.
; Preserves IX and IY.
ID_READ_WORD
	PUSH	IX,IY
	CP	0x40
	JR	NC,.BAD_ADDRESS
	OR	EL3_ID_EEPROM_READ
	CALL	ID_WRITE
	JR	C,.RETURN
	CALL	WAIT_ONE_QUANTUM
	LD	A,(SLOT)
	CALL	@ISA.OPEN
	JR	C,.ISA_ERROR
	LD	BC,(EL3_IDPORT)
	CALL	@ISA.MAP_POINTER
	LD	DE,0
	LD	B,16
.BIT_LOOP
	SLA	E
	RL	D
	LD	A,(HL)
	AND	1
	OR	E
	LD	E,A
	DJNZ	.BIT_LOOP
	CALL	@ISA.CLOSE
	JR	C,.ISA_ERROR
	EX	DE,HL
	XOR	A
.RETURN
	POP	IY,IX
	RET
.BAD_ADDRESS
	LD	A,EL3_ERR_PARAMETER
	SCF
	JR	.RETURN
.ISA_ERROR
	LD	A,EL3_ERR_ISA_STATE
	SCF
	JR	.RETURN

; WINDOW_EEPROM_READ
; In: A=address 00..3F. Out: HL=word. READ opcode only; no write/erase API.
; Busy is checked before and after READ with finite CYCLES21 timing.
; Preserves IX and IY.
WINDOW_EEPROM_READ
	PUSH	IX,IY
	CP	0x40
	JR	NC,.BAD
	LD	(CURRENT_EEPROM_ADDRESS),A
	CALL	WAIT_EEPROM_READY
	JR	C,.RETURN
	LD	A,(CURRENT_EEPROM_ADDRESS)
	OR	EL3_ID_EEPROM_READ
	LD	L,A
	LD	H,0
	LD	E,EL3_REG_EEPROM_CMD
	CALL	WRITE16
	JR	C,.RETURN
	CALL	WAIT_ONE_QUANTUM
	CALL	WAIT_EEPROM_READY
	JR	C,.RETURN
	LD	E,EL3_REG_EEPROM_DATA
	CALL	READ16
.RETURN
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_PARAMETER
	SCF
	JR	.RETURN

; WAIT_EEPROM_READY
; Polls EBY with ISA closed and one CYCLES21 quantum between reads.
WAIT_EEPROM_READY
	LD	HL,0
	LD	(EL3_LAST_TICKS),HL
.POLL
	LD	E,EL3_REG_EEPROM_CMD
	CALL	READ16
	RET	C
	LD	(EL3_LAST_STATUS),HL
	BIT	7,H
	JR	Z,.READY
	LD	HL,(EL3_LAST_TICKS)
	LD	DE,EL3_WAIT_QUANTA
	OR	A
	SBC	HL,DE
	JR	NC,.TIMEOUT
	CALL	WAIT_QUANTUM
	LD	HL,(EL3_LAST_TICKS)
	INC	HL
	LD	(EL3_LAST_TICKS),HL
	JR	.POLL
.READY
	XOR	A
	RET

.TIMEOUT
	LD	HL,EL3_COUNT_TIMEOUT
	CALL	INC_WORD
	LD	A,EL3_ERR_TIMER
	SCF
	RET

; WAIT_ONE_QUANTUM
; Close-window cycle delay used after ID reset and EEPROM READ.
WAIT_ONE_QUANTUM
	CALL	WAIT_QUANTUM
	LD	HL,1
	LD	(EL3_LAST_TICKS),HL
	XOR	A
	RET

SLOT			DB ISA_SLOT_1
CURRENT_EEPROM_ADDRESS	DB 0
ID_COMMAND		DB 0

	ENDMODULE
	ENDIF
