; Read-only 3C509B discovery, EEPROM, activation, and bounded waits.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_EL3_ASM
	DEFINE	_EL3_ASM

	INCLUDE "sprinter.inc"
	INCLUDE "isa.inc"
	INCLUDE "el3.inc"
	INCLUDE "memory.inc"

	MODULE EL3

; CONFIGURE
; In: A=slot, HL=ID port. Out: EL3_OK/CF=0 or explicit error/CF=1.
; Preserves IX and IY.
CONFIGURE
	PUSH	IX,IY
	CP	2
	JR	NC,.BAD
	LD	(SLOT),A
	LD	A,H
	CP	0x01
	JR	NZ,.BAD
	LD	A,L
	AND	0x0F
	JR	NZ,.BAD
	LD	A,L
	CP	0xF1
	JR	NC,.BAD
	LD	(EL3_IDPORT),HL
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; DISCOVER
; Performs classic reset, reads all 64 EEPROM words through the ID port,
; and validates IDs, MAC, and checksums. It never activates or writes EEPROM.
; Out: EL3_OK/CF=0 or explicit error/CF=1. Preserves IX and IY.
DISCOVER
	PUSH	IX,IY
	LD	A,EL3_STAGE_RESET
	LD	(EL3_LAST_STAGE),A
	CALL	ID_SEQUENCE
	JR	C,.RETURN
	LD	A,EL3_ID_GLOBAL_RESET
	CALL	ID_WRITE
	JR	C,.RETURN
	LD	B,2
	CALL	WAIT_FRAME_TRANSITIONS
	JR	C,.RETURN
	CALL	ID_SEQUENCE
	JR	C,.RETURN
	LD	A,EL3_ID_TAG_ZERO
	CALL	ID_WRITE
	JR	C,.RETURN
	LD	A,EL3_STAGE_EEPROM
	LD	(EL3_LAST_STAGE),A
	LD	HL,EEPROM_BUFFER
	XOR	A
.EEPROM_LOOP
	PUSH	AF,HL
	CALL	ID_READ_WORD
	JR	C,.READ_FAILED
	EX	DE,HL
	POP	HL,AF
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	INC	A
	CP	0x40
	JR	NZ,.EEPROM_LOOP
	LD	A,EL3_STAGE_VALIDATE
	LD	(EL3_LAST_STAGE),A
	CALL	@EL3ALG.VALIDATE
	JR	.RETURN
.READ_FAILED
	POP	HL
	INC	SP
	INC	SP
.RETURN
	POP	IY,IX
	RET

; ACTIVATE
; In: A=0 for EEPROM base, A=1 for explicit base in HL.
; Out: active base in HL and EL3_BASE, EL3_OK/CF=0 or error/CF=1.
; Preserves IX and IY.
ACTIVATE
	PUSH	IX,IY
	LD	D,A
	LD	A,EL3_STAGE_ACTIVATE
	LD	(EL3_LAST_STAGE),A
	LD	A,D
	OR	A
	JR	NZ,.EXPLICIT
	LD	A,(EEPROM_BUFFER + 0x08*2)
	AND	0x1F
	CALL	@EL3ALG.BASE_DECODE
	JR	C,.RETURN
	LD	(EL3_BASE),HL
	LD	A,EL3_ID_ACTIVATE_EEPROM
	JR	.WRITE_ACTIVATE
.EXPLICIT
	CALL	@EL3ALG.BASE_ENCODE
	JR	C,.RETURN
	LD	(EL3_BASE),HL
	OR	EL3_ID_ACTIVATE_BASE
.WRITE_ACTIVATE
	CALL	ID_WRITE
	JR	C,.RETURN
	CALL	VERIFY_ACTIVE
	JR	C,.RETURN
	LD	HL,(EL3_BASE)
	XOR	A
.RETURN
	POP	IY,IX
	RET

; VERIFY_ACTIVE
; Reads Window 0 manufacturer/product registers using adjacent low/high cycles.
; Preserves IX and IY.
VERIFY_ACTIVE
	PUSH	IX,IY
	LD	A,EL3_STAGE_VERIFY
	LD	(EL3_LAST_STAGE),A
	LD	E,EL3_REG_MFG_ID
	CALL	READ16
	JR	C,.RETURN
	LD	DE,EL3_MFG_3COM
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	LD	E,EL3_REG_PRODUCT_ID
	CALL	READ16
	JR	C,.RETURN
	LD	DE,EL3_PRODUCT_3C509B_TPO
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	XOR	A
.RETURN
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_VERIFY
	SCF
	JR	.RETURN

; ID_SEQUENCE
; Sends two zero selector bytes and exactly 255 LFSR bytes (FF through 98).
; Preserves IX and IY.
ID_SEQUENCE
	PUSH	IX,IY
	LD	A,(SLOT)
	CALL	@ISA.OPEN
	JR	C,.ISA_ERROR
	LD	BC,(EL3_IDPORT)
	CALL	@ISA.MAP_POINTER
	XOR	A
	LD	(HL),A
	LD	(HL),A
	LD	C,EL3_LFSR_SEED
	LD	B,0xFF
.LOOP
	LD	A,C
	LD	(HL),A
	CALL	@EL3ALG.LFSR_NEXT
	LD	C,A
	DJNZ	.LOOP
	CALL	@ISA.CLOSE
	JR	C,.ISA_ERROR
	LD	A,C
	CP	EL3_LFSR_SEED
	JR	NZ,.INTERNAL
	XOR	A
	POP	IY,IX
	RET
.ISA_ERROR
	LD	A,EL3_ERR_ISA_STATE
	SCF
	POP	IY,IX
	RET
.INTERNAL
	LD	A,EL3_ERR_VERIFY
	SCF
	POP	IY,IX
	RET

; ID_WRITE
; In: A=ID command. Out: explicit status. Preserves IX and IY.
ID_WRITE
	PUSH	IX,IY
	LD	(ID_COMMAND),A
	LD	BC,(EL3_IDPORT)
	LD	A,(SLOT)
	LD	D,A
	LD	A,(ID_COMMAND)
	CALL	@ISA.WRITE8
	JR	NC,.OK
	LD	A,EL3_ERR_ISA_STATE
	SCF
	POP	IY,IX
	RET
.OK
	XOR	A
	POP	IY,IX
	RET

; ID_READ_WORD
; In: A=EEPROM address 00..3F. Out: HL=word and CF=0, or error.
; The documented 162 us operation is given more than 40 ms of CTC time;
; the ISA window is closed for the entire wait.
; Preserves IX and IY.
ID_READ_WORD
	PUSH	IX,IY
	CP	0x40
	JR	NC,.BAD_ADDRESS
	OR	EL3_ID_EEPROM_READ
	CALL	ID_WRITE
	JR	C,.RETURN
	LD	B,2
	CALL	WAIT_FRAME_TRANSITIONS
	JR	C,.RETURN
	LD	A,(SLOT)
	CALL	@ISA.OPEN
	JR	C,.ISA_ERROR
	LD	BC,(EL3_IDPORT)
	CALL	@ISA.MAP_POINTER
	LD	DE,0
	LD	B,16
.BIT_LOOP
	SLA	E
	RL	D
	LD	A,(HL)
	AND	1
	OR	E
	LD	E,A
	DJNZ	.BIT_LOOP
	CALL	@ISA.CLOSE
	JR	C,.ISA_ERROR
	EX	DE,HL
	XOR	A
.RETURN
	POP	IY,IX
	RET
.BAD_ADDRESS
	LD	A,EL3_ERR_PARAMETER
	SCF
	JR	.RETURN
.ISA_ERROR
	LD	A,EL3_ERR_ISA_STATE
	SCF
	JR	.RETURN

; READ16
; In: E=even register offset, base from EL3_BASE. Out: HL=word.
; Low byte is read immediately before high byte in one ISA critical section.
; Preserves IX and IY.
READ16
	PUSH	IX,IY
	LD	A,E
	AND	1
	JR	NZ,.BAD_OFFSET
	LD	A,(SLOT)
	CALL	@ISA.OPEN
	JR	C,.ISA_ERROR
	LD	BC,(EL3_BASE)
	LD	A,C
	ADD	A,E
	LD	C,A
	JR	NC,.NO_CARRY
	INC	B
.NO_CARRY
	CALL	@ISA.MAP_POINTER
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	CALL	@ISA.CLOSE
	JR	C,.ISA_ERROR
	EX	DE,HL
	LD	(EL3_LAST_STATUS),HL
	XOR	A
	POP	IY,IX
	RET
.BAD_OFFSET
	LD	A,EL3_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET
.ISA_ERROR
	LD	A,EL3_ERR_ISA_STATE
	SCF
	POP	IY,IX
	RET

; WINDOW_EEPROM_READ
; In: A=address 00..3F. Out: HL=word. READ opcode only; no write/erase API.
; Busy is checked before and after issuing READ, with finite timing.
; Preserves IX and IY.
WINDOW_EEPROM_READ
	PUSH	IX,IY
	CP	0x40
	JR	NC,.BAD
	LD	(CURRENT_EEPROM_ADDRESS),A
	CALL	WAIT_EEPROM_READY
	JR	C,.RETURN
	LD	A,(CURRENT_EEPROM_ADDRESS)
	OR	EL3_ID_EEPROM_READ
	LD	L,A
	LD	H,0
	LD	E,EL3_REG_EEPROM_CMD
	CALL	WRITE16
	JR	C,.RETURN
	LD	B,2
	CALL	WAIT_FRAME_TRANSITIONS
	JR	C,.RETURN
	CALL	WAIT_EEPROM_READY
	JR	C,.RETURN
	LD	E,EL3_REG_EEPROM_DATA
	CALL	READ16
.RETURN
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_PARAMETER
	SCF
	JR	.RETURN

; WRITE16 is private to read-only commands: currently only EEPROM READ command.
; In: HL=word, E=even offset. Out: status. Low then high without intervening I/O.
WRITE16
	LD	(WRITE_WORD),HL
	LD	A,(SLOT)
	CALL	@ISA.OPEN
	JR	C,.ERROR
	LD	BC,(EL3_BASE)
	LD	A,C
	ADD	A,E
	LD	C,A
	JR	NC,.NO_CARRY
	INC	B
.NO_CARRY
	CALL	@ISA.MAP_POINTER
	LD	DE,(WRITE_WORD)
	LD	(HL),E
	INC	HL
	LD	(HL),D
	CALL	@ISA.CLOSE
	RET	C
	XOR	A
	RET
.ERROR
	LD	A,EL3_ERR_ISA_STATE
	SCF
	RET

; WAIT_EEPROM_READY
; Polls EBY with ISA closed between reads. Deadline is at least 100 ms,
; plus a finite emergency loop for a stalled CTC source.
WAIT_EEPROM_READY
	LD	A,EL3_CTC_TIMEOUT_WRAPS
	CALL	CTC_DEADLINE_START
.POLL
	LD	E,EL3_REG_EEPROM_CMD
	CALL	READ16
	RET	C
	BIT	7,H
	JR	Z,.READY
	CALL	CTC_DEADLINE_UPDATE
	JR	NC,.POLL
	RET
.READY
	XOR	A
	RET

; WAIT_FRAME_TRANSITIONS
; In: B=2. Out: elapsed CTC wraps in EL3_LAST_TICKS (at least 40 ms).
; The ISA window remains closed and the DSS-owned CTC is never reprogrammed.
; Preserves IX and IY.
WAIT_FRAME_TRANSITIONS
	PUSH	IX,IY
	LD	A,B
	CP	2
	JR	NZ,.BAD_COUNT
	LD	A,EL3_CTC_SETTLE_WRAPS + 1
	CALL	CTC_DEADLINE_START
.WAIT
	CALL	CTC_DEADLINE_UPDATE
	JR	C,.RETURN
	LD	A,(EL3_LAST_TICKS)
	CP	EL3_CTC_SETTLE_WRAPS
	JR	C,.WAIT
	XOR	A
.RETURN
	POP	IY,IX
	RET
.BAD_COUNT
	LD	A,EL3_ERR_PARAMETER
	SCF
	JR	.RETURN

; CTC_DEADLINE_START
; In: A=wrap deadline. Starts a read-only CTC0 deadline and emergency guard.
CTC_DEADLINE_START
	LD	(CTC_WRAP_LIMIT),A
	IN	A,(CTC_CHANNEL0)
	LD	(CTC_MARK),A
	XOR	A
	LD	(EL3_LAST_TICKS),A
	LD	HL,0
	LD	(EMERGENCY_COUNT),HL
	RET

; CTC_DEADLINE_UPDATE
; Out: CF=0 while active; CF=1/A=EL3_ERR_TIMER at the wrap deadline or if
; the observed down-counter stops changing for 65536 consecutive samples.
CTC_DEADLINE_UPDATE
	IN	A,(CTC_CHANNEL0)
	LD	B,A
	LD	A,(CTC_MARK)
	CP	B
	JR	Z,.NO_MOVEMENT
	LD	D,0
	JR	NC,.STORE_SAMPLE
	INC	D
.STORE_SAMPLE
	LD	A,B
	LD	(CTC_MARK),A
	LD	HL,0
	LD	(EMERGENCY_COUNT),HL
	LD	A,D
	OR	A
	JR	Z,.ACTIVE
	LD	A,(EL3_LAST_TICKS)
	INC	A
	LD	(EL3_LAST_TICKS),A
	LD	D,A
	LD	A,(CTC_WRAP_LIMIT)
	CP	D
	JR	Z,.TIMEOUT
	JR	C,.TIMEOUT
.ACTIVE
	XOR	A
	RET
.NO_MOVEMENT
	LD	HL,(EMERGENCY_COUNT)
	DEC	HL
	LD	(EMERGENCY_COUNT),HL
	LD	A,H
	OR	L
	JR	NZ,.ACTIVE
.TIMEOUT
	LD	A,EL3_ERR_TIMER
	SCF
	RET

SLOT			DB ISA_SLOT_1
CTC_MARK		DB 0
CTC_WRAP_LIMIT		DB 0
CURRENT_EEPROM_ADDRESS	DB 0
ID_COMMAND		DB 0
WRITE_WORD		DW 0
EMERGENCY_COUNT	DW 0

	ENDMODULE
	ENDIF
