; Production-neutral 3C509B register core. All physical I/O goes through EL3IO.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_EL3_REGS_ASM
	DEFINE	_EL3_REGS_ASM

	INCLUDE "el3.inc"
	INCLUDE "memory.inc"

	MODULE EL3

; READ8 / WRITE8
; In: E=register offset; WRITE8 also takes A=value.
; READ8 returns L=value. Both return A=EL3_OK/CF=0 or explicit error/CF=1.
; Preserve IX and IY. The provider closes the ISA window before returning.
READ8
	PUSH	IX,IY
	CALL	@EL3IO.READ8
	JR	C,.READ8_RETURN
	LD	L,A
	XOR	A
.READ8_RETURN
	POP	IY,IX
	RET

WRITE8
	PUSH	IX,IY
	CALL	@EL3IO.WRITE8
	POP	IY,IX
	RET

; READ16 / WRITE16
; In: E=even register offset; WRITE16 also takes HL=value.
; READ16 returns HL=value. Low and high ISA8 cycles are provider-atomic.
; Preserve IX and IY and return a stable status in A/CF.
READ16
	PUSH	IX,IY
	CALL	@EL3IO.READ16
	POP	IY,IX
	RET

WRITE16
	PUSH	IX,IY
	CALL	@EL3IO.WRITE16
	POP	IY,IX
	RET

; CMD
; In: HL=documented 3C509B command word. Out: status in A/CF.
; Preserve IX and IY. Completion is intentionally handled by WAIT_CIP.
CMD
	PUSH	IX,IY
	LD	(EL3_LAST_COMMAND),HL
	LD	E,EL3_REG_COMMAND
	CALL	WRITE16
	POP	IY,IX
	RET

; WAIT_CIP
; Polls once immediately, then waits one CYCLES21 quantum between polls.
; At most 100 quanta are consumed. EL3_LAST_TICKS is a 16-bit waitq count.
; Preserve IX and IY.
WAIT_CIP
	PUSH	IX,IY
	LD	HL,0
	LD	(EL3_LAST_TICKS),HL
.POLL
	LD	E,EL3_REG_COMMAND
	CALL	READ16
	JR	C,.RETURN
	LD	(EL3_LAST_STATUS),HL
	BIT	4,H
	JR	Z,.READY
	LD	HL,(EL3_LAST_TICKS)
	LD	DE,EL3_WAIT_QUANTA
	OR	A
	SBC	HL,DE
	JR	NC,.TIMEOUT
	CALL	WAIT_QUANTUM
	LD	HL,(EL3_LAST_TICKS)
	INC	HL
	LD	(EL3_LAST_TICKS),HL
	JR	.POLL
.READY
	XOR	A
.RETURN
	POP	IY,IX
	RET
.TIMEOUT
	LD	HL,EL3_COUNT_TIMEOUT
	CALL	INC_WORD
	LD	A,EL3_ERR_CMD_TIMEOUT
	SCF
	JR	.RETURN

; WAIT_QUANTUM
; Exactly 21023 T-states from entry through RET: 10 + 807*26 + 21 + 10.
; A call therefore waits at least 1 ms at the supported maximum CPU 21 MHz.
WAIT_QUANTUM
	LD	BC,EL3_CYCLE_COUNT
.LOOP
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.LOOP
	RET

; LINK_STATE
; Out: A=0 when the TPO link beat is absent, A=1 when present, CF=0;
;      explicit register error with CF=1 otherwise.
; Clobbers AF, BC, DE and HL; preserves IX and IY. Window 1 is restored.
LINK_STATE
	PUSH	IX,IY
	LD	A,4
	CALL	SELECT_WINDOW
	JR	C,.LINK_RETURN
	LD	E,EL3_W4_MEDIA_STATUS
	CALL	READ16
	JR	C,.LINK_RESTORE_ERROR
	LD	A,H
	AND	HIGH EL3_MEDIA_LINK_DETECT
	JR	Z,.LINK_DOWN
	LD	A,1
	JR	.LINK_SAVE
.LINK_DOWN
	XOR	A
.LINK_SAVE
	LD	(LINK_RESULT),A
	XOR	A
	LD	(LINK_ERROR),A
	JR	.LINK_RESTORE
.LINK_RESTORE_ERROR
	LD	(LINK_ERROR),A
.LINK_RESTORE
	LD	A,1
	CALL	SELECT_WINDOW
	JR	C,.LINK_RETURN
	LD	A,(LINK_ERROR)
	OR	A
	JR	NZ,.LINK_ERROR_RETURN
	LD	A,(LINK_RESULT)
	OR	A
.LINK_RETURN
	POP	IY,IX
	RET
.LINK_ERROR_RETURN
	SCF
	JR	.LINK_RETURN

; WAIT_LINK_UP
; In: BC=maximum CYCLES21 wait quanta (1..10000).
; Out: A=EL3_OK/CF=0 when link is up; EL3_ERR_LINK_TIMEOUT/CF=1 on expiry.
; Clobbers AF, BC, DE and HL; preserves IX and IY. Every wait occurs with the
; Sprinter ISA window closed and Window 1 is restored on all returns.
WAIT_LINK_UP
	PUSH	IX,IY
	LD	A,EL3_STAGE_LINK
	LD	(EL3_LAST_STAGE),A
	LD	A,B
	OR	C
	JR	Z,.WAIT_LINK_BAD
	LD	(WAIT_LINK_LIMIT),BC
	LD	HL,0
	LD	(WAIT_LINK_ELAPSED),HL
	LD	(EL3_LAST_TICKS),HL
.WAIT_LINK_POLL
	CALL	LINK_STATE
	JR	C,.WAIT_LINK_RETURN
	OR	A
	JR	NZ,.WAIT_LINK_READY
	LD	HL,(WAIT_LINK_ELAPSED)
	LD	DE,(WAIT_LINK_LIMIT)
	OR	A
	SBC	HL,DE
	JR	NC,.WAIT_LINK_TIMEOUT
	CALL	WAIT_QUANTUM
	LD	HL,(WAIT_LINK_ELAPSED)
	INC	HL
	LD	(WAIT_LINK_ELAPSED),HL
	LD	(EL3_LAST_TICKS),HL
	JR	.WAIT_LINK_POLL
.WAIT_LINK_READY
	LD	HL,(WAIT_LINK_ELAPSED)
	LD	(EL3_LAST_TICKS),HL
	LD	A,EL3_STAGE_LINK
	LD	(EL3_LAST_STAGE),A
	XOR	A
	JR	.WAIT_LINK_RETURN
.WAIT_LINK_TIMEOUT
	LD	HL,(WAIT_LINK_ELAPSED)
	LD	(EL3_LAST_TICKS),HL
	LD	A,EL3_STAGE_LINK
	LD	(EL3_LAST_STAGE),A
	LD	HL,EL3_COUNT_TIMEOUT
	CALL	INC_WORD
	LD	A,EL3_ERR_LINK_TIMEOUT
	SCF
	JR	.WAIT_LINK_RETURN
.WAIT_LINK_BAD
	LD	A,EL3_ERR_PARAMETER
	SCF
.WAIT_LINK_RETURN
	POP	IY,IX
	RET

; SELECT_WINDOW
; In: A=window 0..6. Out: explicit status. Preserve IX and IY.
SELECT_WINDOW
	PUSH	IX,IY
	CP	7
	JR	NC,.BAD
	LD	L,A
	LD	H,0
	LD	DE,EL3_CMD_SELECT_WINDOW
	ADD	HL,DE
	CALL	CMD_SYNC
	POP	IY,IX
	RET
.BAD
	LD	A,EL3_ERR_BAD_WINDOW
	SCF
	POP	IY,IX
	RET

; RESET_GLOBAL / RESET_RX / RESET_TX
; Issue the documented reset and wait for finite CIP completion.
; Preserve IX and IY; increment the software reset counter per command.
RESET_GLOBAL
	PUSH	IX,IY
	LD	HL,EL3_CMD_GLOBAL_RESET
	CALL	RESET_COMMAND
	POP	IY,IX
	RET

RESET_RX
	PUSH	IX,IY
	LD	HL,EL3_CMD_RX_RESET
	CALL	RESET_COMMAND
	POP	IY,IX
	RET

RESET_TX
	PUSH	IX,IY
	LD	HL,EL3_CMD_TX_RESET
	CALL	RESET_COMMAND
	POP	IY,IX
	RET

RESET_COMMAND
	CALL	CMD_SYNC
	RET	C
	LD	HL,EL3_COUNT_RESET
	CALL	INC_WORD
	XOR	A
	RET

; INIT
; Prepare polling-only RX/TX state without IRQ routing or EEPROM writes.
; Out: EL3_OK/CF=0 or explicit error/CF=1. Preserve IX and IY.
INIT
	PUSH	IX,IY
	LD	A,EL3_STAGE_INIT
	LD	(EL3_LAST_STAGE),A
	XOR	A
	LD	(INIT_ACTIVE),A
	LD	(EL3_VERIFY_FIELD),A
	LD	H,A
	LD	L,A
	LD	(EL3_VERIFY_EXPECTED),HL
	LD	(EL3_VERIFY_ACTUAL),HL
	CALL	LOOPBACK_DISABLE
	JP	C,.RETURN
	LD	A,EL3_STAGE_INIT
	LD	(EL3_LAST_STAGE),A
	LD	HL,EL3_CMD_SET_INTR_MASK
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_SET_READ_ZERO | EL3_MASK_READ_ZERO
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_RX_DISABLE
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_TX_DISABLE
	CALL	CMD_SYNC
	JP	C,.RETURN
	CALL	RESET_RX
	JP	C,.RETURN
	CALL	RESET_TX
	JP	C,.RETURN

	LD	A,2
	CALL	SELECT_WINDOW
	JP	C,.RETURN
	LD	HL,EL3_MAC
	LD	E,EL3_W2_STATION
	LD	B,6
.MAC_WRITE
	LD	A,(HL)
	CALL	WRITE8
	JP	C,.RETURN
	INC	HL
	INC	E
	DJNZ	.MAC_WRITE

	LD	A,4
	CALL	SELECT_WINDOW
	JP	C,.RETURN
	LD	E,EL3_W4_MEDIA_STATUS
	CALL	READ16
	JP	C,.RETURN
	LD	A,L
	OR	LOW EL3_MEDIA_LINK_JABBER
	LD	L,A
	LD	A,H
	OR	HIGH EL3_MEDIA_LINK_JABBER
	LD	H,A
	LD	(EL3_EXPECT_MEDIA),HL
	LD	E,EL3_W4_MEDIA_STATUS
	CALL	WRITE16
	JP	C,.RETURN

	LD	HL,EL3_CMD_STATS_DISABLE
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	A,6
	CALL	SELECT_WINDOW
	JP	C,.RETURN
	LD	E,0
	LD	B,14
.CLEAR_STATS
	CALL	READ8
	JP	C,.RETURN
	INC	E
	DJNZ	.CLEAR_STATS

	LD	HL,EL3_CMD_SET_RX_FILTER | EL3_RX_FILTER_POLLING
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_SET_RX_EARLY | EL3_THRESHOLD_DISABLED
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_SET_TX_AVAIL | EL3_THRESHOLD_DISABLED
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_SET_TX_START | EL3_TX_START_VALUE
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_STATS_ENABLE
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_RX_ENABLE
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_TX_ENABLE
	CALL	CMD_SYNC
	JP	C,.RETURN
	LD	HL,EL3_CMD_ACK_INTR | EL3_ACK_POLLING
	CALL	CMD_SYNC
	JP	C,.RETURN
	CALL	VERIFY_INIT
	JP	C,.RETURN
	LD	A,1
	LD	(INIT_ACTIVE),A
	XOR	A
.RETURN
	POP	IY,IX
	RET

; DONE
; Disable polling operation, clear masks, acknowledge polling causes and leave
; Window 0 selected. It is safe to call after a partial INIT.
DONE
	PUSH	IX,IY
	LD	A,EL3_STAGE_DONE
	LD	(EL3_LAST_STAGE),A
	CALL	LOOPBACK_DISABLE
	JR	C,.RETURN
	LD	A,EL3_STAGE_DONE
	LD	(EL3_LAST_STAGE),A
	LD	HL,EL3_CMD_RX_DISABLE
	CALL	CMD_SYNC
	JR	C,.RETURN
	LD	HL,EL3_CMD_TX_DISABLE
	CALL	CMD_SYNC
	JR	C,.RETURN
	LD	HL,EL3_CMD_STATS_DISABLE
	CALL	CMD_SYNC
	JR	C,.RETURN
	LD	HL,EL3_CMD_SET_INTR_MASK
	CALL	CMD_SYNC
	JR	C,.RETURN
	LD	HL,EL3_CMD_SET_READ_ZERO
	CALL	CMD_SYNC
	JR	C,.RETURN
	LD	HL,EL3_CMD_ACK_INTR | EL3_ACK_POLLING
	CALL	CMD_SYNC
	JR	C,.RETURN
	XOR	A
	CALL	SELECT_WINDOW
	JR	C,.RETURN
	XOR	A
	LD	(INIT_ACTIVE),A
.RETURN
	POP	IY,IX
	RET

VERIFY_INIT
	LD	A,EL3_VERIFY_MAC
	LD	(EL3_VERIFY_FIELD),A
	LD	A,2
	CALL	SELECT_WINDOW
	RET	C
	LD	HL,EL3_MAC
	LD	E,EL3_W2_STATION
	LD	B,6
.MAC
	PUSH	HL
	CALL	READ8
	JR	C,.MAC_IO_ERROR
	LD	A,L
	POP	HL
	CP	(HL)
	JP	NZ,.BAD_MAC
	INC	HL
	INC	E
	DJNZ	.MAC
	JR	.MAC_DONE
.MAC_IO_ERROR
	POP	HL
	RET
.MAC_DONE
	LD	A,EL3_VERIFY_MEDIA
	LD	(EL3_VERIFY_FIELD),A
	LD	A,4
	CALL	SELECT_WINDOW
	RET	C
	LD	E,EL3_W4_MEDIA_STATUS
	LD	BC,(EL3_EXPECT_MEDIA)
	CALL	VERIFY_MEDIA
	JP	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_FILTER
	LD	(EL3_VERIFY_FIELD),A
	LD	A,5
	CALL	SELECT_WINDOW
	RET	C
	LD	E,EL3_W5_RX_FILTER
	LD	BC,EL3_RX_FILTER_POLLING
	CALL	VERIFY_WORD
	JP	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_INTR_MASK
	LD	(EL3_VERIFY_FIELD),A
	LD	E,EL3_W5_INTR_MASK
	LD	BC,0
	CALL	VERIFY_WORD
	JR	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_READ_ZERO
	LD	(EL3_VERIFY_FIELD),A
	LD	E,EL3_W5_READ_ZERO_MASK
	LD	BC,EL3_MASK_READ_ZERO
	CALL	VERIFY_WORD
	JR	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_RX_EARLY
	LD	(EL3_VERIFY_FIELD),A
	LD	E,EL3_W5_RX_EARLY
	LD	BC,EL3_THRESHOLD_READBACK
	CALL	VERIFY_WORD
	JR	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_TX_AVAILABLE
	LD	(EL3_VERIFY_FIELD),A
	LD	E,EL3_W5_TX_AVAILABLE
	LD	BC,EL3_THRESHOLD_READBACK
	CALL	VERIFY_WORD
	JR	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_TX_START
	LD	(EL3_VERIFY_FIELD),A
	LD	E,EL3_W5_TX_START
	LD	BC,EL3_TX_START_VALUE
	CALL	VERIFY_WORD
	JR	C,.BAD_OR_IO
	LD	A,EL3_VERIFY_WINDOW
	LD	(EL3_VERIFY_FIELD),A
	LD	A,1
	CALL	SELECT_WINDOW
	RET	C
	LD	E,EL3_REG_COMMAND
	CALL	READ16
	RET	C
	LD	(EL3_LAST_STATUS),HL
	XOR	A
	LD	(EL3_VERIFY_ACTUAL),A
	LD	A,H
	AND	0xE0
	LD	(EL3_VERIFY_ACTUAL + 1),A
	LD	HL,0x2000
	LD	(EL3_VERIFY_EXPECTED),HL
	LD	A,(EL3_VERIFY_ACTUAL + 1)
	CP	0x20
	JR	NZ,.BAD
	CALL	CLEAR_VERIFY_DIAGNOSTICS
	XOR	A
	RET
.BAD_MAC
	LD	(EL3_VERIFY_ACTUAL),A
	XOR	A
	LD	(EL3_VERIFY_ACTUAL + 1),A
	LD	A,(HL)
	LD	(EL3_VERIFY_EXPECTED),A
	XOR	A
	LD	(EL3_VERIFY_EXPECTED + 1),A
	JR	.BAD
.BAD_OR_IO
	CP	EL3_ERR_INIT_VERIFY
	RET	NZ
.BAD
	LD	A,EL3_ERR_INIT_VERIFY
	SCF
	RET

VERIFY_WORD
	CALL	READ16
	RET	C
	LD	(EL3_VERIFY_ACTUAL),HL
	LD	A,C
	LD	(EL3_VERIFY_EXPECTED),A
	LD	A,B
	LD	(EL3_VERIFY_EXPECTED + 1),A
	OR	A
	SBC	HL,BC
	RET	Z
	LD	A,EL3_ERR_INIT_VERIFY
	SCF
	RET

; VERIFY_MEDIA compares only static media bits. Link Detect (bit 11) can
; change as soon as Link Beat Enable is written during INIT.
VERIFY_MEDIA
	CALL	READ16
	RET	C
	LD	(EL3_VERIFY_ACTUAL),HL
	LD	A,H
	AND	EL3_MEDIA_STABLE_HIGH_MASK
	LD	H,A
	LD	A,B
	AND	EL3_MEDIA_STABLE_HIGH_MASK
	LD	B,A
	OR	A
	SBC	HL,BC
	RET	Z
	LD	A,EL3_ERR_INIT_VERIFY
	SCF
	RET

CLEAR_VERIFY_DIAGNOSTICS
	XOR	A
	LD	(EL3_VERIFY_FIELD),A
	LD	H,A
	LD	L,A
	LD	(EL3_VERIFY_EXPECTED),HL
	LD	(EL3_VERIFY_ACTUAL),HL
	RET

; SNAPSHOT
; In: HL=60-byte destination. Out: explicit status. Preserve IX and IY.
SNAPSHOT
	PUSH	IX,IY
	LD	A,EL3_STAGE_SNAPSHOT
	LD	(EL3_LAST_STAGE),A
	LD	A,0xFF
	LD	(SNAP_WINDOW),A
	LD	(SNAP_POINTER),HL
	LD	HL,(EL3_LAST_COMMAND)
	LD	(SNAP_LAST_COMMAND),HL
	LD	HL,(EL3_LAST_STATUS)
	LD	(SNAP_LAST_STATUS),HL
	LD	E,EL3_REG_COMMAND
	CALL	READ16
	JP	C,.FAIL
	LD	A,H
	AND	0xE0
	RRCA
	RRCA
	RRCA
	RRCA
	RRCA
	LD	(SNAP_WINDOW),A
	LD	HL,(SNAP_POINTER)
	LD	(HL),EL3_SNAPSHOT_VERSION
	INC	HL
	LD	(HL),EL3_SNAPSHOT_LENGTH
	INC	HL
	LD	A,(INIT_ACTIVE)
	LD	(HL),A
	INC	HL
	LD	(HL),0
	INC	HL
	LD	A,(SLOT)
	LD	(HL),A
	INC	HL
	LD	A,(SNAP_WINDOW)
	LD	(HL),A
	LD	DE,EL3_SNAP_IDPORT
	LD	HL,(EL3_IDPORT)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_BASE
	LD	HL,(EL3_BASE)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_LAST_COMMAND
	LD	HL,(SNAP_LAST_COMMAND)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_LAST_STATUS
	LD	HL,(SNAP_LAST_STATUS)
	CALL	SNAP_STORE_WORD
	LD	A,0
	CALL	SELECT_WINDOW
	JP	C,.FAIL
	LD	E,EL3_REG_PRODUCT_ID
	CALL	READ16
	JP	C,.FAIL
	LD	DE,EL3_SNAP_PRODUCT
	CALL	SNAP_STORE_WORD
	LD	A,2
	CALL	SELECT_WINDOW
	JP	C,.FAIL
	LD	DE,EL3_SNAP_MAC
	LD	E,EL3_W2_STATION
	LD	B,6
.SNAP_MAC
	CALL	READ8
	JP	C,.FAIL
	LD	C,L
	PUSH	DE
	LD	HL,(SNAP_POINTER)
	LD	D,0
	LD	A,EL3_SNAP_MAC
	ADD	A,6
	SUB	B
	LD	E,A
	ADD	HL,DE
	LD	(HL),C
	POP	DE
	INC	E
	DJNZ	.SNAP_MAC
	LD	A,1
	CALL	SELECT_WINDOW
	JP	C,.FAIL
	LD	E,EL3_W1_RX_STATUS
	CALL	READ16
	JP	C,.FAIL
	LD	DE,EL3_SNAP_RX_STATUS
	CALL	SNAP_STORE_WORD
	LD	E,EL3_W1_TX_STATUS
	CALL	READ8
	JP	C,.FAIL
	LD	H,0
	LD	DE,EL3_SNAP_TX_STATUS
	CALL	SNAP_STORE_WORD
	LD	A,4
	CALL	SELECT_WINDOW
	JP	C,.FAIL
	LD	E,EL3_W4_FIFO_DIAG
	LD	D,EL3_SNAP_FIFO_DIAG
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W4_NET_DIAG
	LD	D,EL3_SNAP_NET_DIAG
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W4_MEDIA_STATUS
	LD	D,EL3_SNAP_MEDIA_STATUS
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	A,5
	CALL	SELECT_WINDOW
	JP	C,.FAIL
	LD	E,EL3_W5_RX_FILTER
	LD	D,EL3_SNAP_RX_FILTER
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W5_INTR_MASK
	LD	D,EL3_SNAP_INTR_MASK
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W5_READ_ZERO_MASK
	LD	D,EL3_SNAP_READ_ZERO
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W5_RX_EARLY
	LD	D,EL3_SNAP_RX_EARLY
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W5_TX_AVAILABLE
	LD	D,EL3_SNAP_TX_AVAILABLE
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	E,EL3_W5_TX_START
	LD	D,EL3_SNAP_TX_START
	CALL	SNAP_READ_WORD
	JP	C,.FAIL
	LD	DE,EL3_SNAP_COUNT_RESET
	LD	HL,(EL3_COUNT_RESET)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_COUNT_TIMEOUT
	LD	HL,(EL3_COUNT_TIMEOUT)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_COUNT_RX
	LD	HL,(EL3_COUNT_RX)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_COUNT_TX
	LD	HL,(EL3_COUNT_TX)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_COUNT_DROP
	LD	HL,(EL3_COUNT_DROP)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_COUNT_FRAME
	LD	HL,(EL3_COUNT_FRAME)
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_RESERVED
	LD	HL,0
	CALL	SNAP_STORE_WORD
	LD	DE,EL3_SNAP_RESERVED+2
	CALL	SNAP_STORE_WORD
	LD	A,(SNAP_WINDOW)
	CALL	SELECT_WINDOW
	JR	C,.FAIL
	CALL	SNAP_RESTORE_DIAGNOSTICS
	XOR	A
	POP	IY,IX
	RET
.FAIL
	LD	(SNAP_ERROR),A
	LD	A,(SNAP_WINDOW)
	CP	7
	CALL	C,SELECT_WINDOW
	CALL	SNAP_RESTORE_DIAGNOSTICS
	LD	A,(SNAP_ERROR)
	SCF
	POP	IY,IX
	RET

SNAP_READ_WORD
	PUSH	DE
	CALL	READ16
	POP	DE
	RET	C
	LD	E,D
	LD	D,0
	JP	SNAP_STORE_WORD

SNAP_STORE_WORD
	PUSH	BC,DE,HL
	LD	BC,(SNAP_POINTER)
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	POP	HL
	LD	A,L
	LD	(DE),A
	INC	DE
	LD	A,H
	LD	(DE),A
	POP	DE,BC
	RET

SNAP_RESTORE_DIAGNOSTICS
	LD	HL,(SNAP_LAST_COMMAND)
	LD	(EL3_LAST_COMMAND),HL
	LD	HL,(SNAP_LAST_STATUS)
	LD	(EL3_LAST_STATUS),HL
	RET

CMD_SYNC
	CALL	CMD
	RET	C
	JP	WAIT_CIP

INC_WORD
	INC	(HL)
	RET	NZ
	INC	HL
	INC	(HL)
	RET

INIT_ACTIVE		DB 0
SNAP_POINTER		DW 0
SNAP_LAST_COMMAND	DW 0
SNAP_LAST_STATUS	DW 0
SNAP_WINDOW		DB 0xFF
SNAP_ERROR		DB 0
LINK_RESULT		DB 0
LINK_ERROR		DB 0
WAIT_LINK_LIMIT		DW 0
WAIT_LINK_ELAPSED	DW 0

	ENDMODULE
	ENDIF
