; Production-neutral 3C509B polling datapath.
; Register access is through EL3IO; FIFO streams are through the four burst
; provider calls. The core never owns the Sprinter ISA window directly.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_EL3_FIFO_ASM
	DEFINE	_EL3_FIFO_ASM

	INCLUDE "el3.inc"
	INCLUDE "memory.inc"

	MODULE EL3

; SEND_FRAME
; In: HL=frame, BC=input length 14..1514.
; Out: A=EL3_OK/CF=0 or stable error/CF=1.
; Clobbers AF, BC, DE and HL; preserves IX and IY.
; A timeout recovers TX but never resends an uncertain TX.
SEND_FRAME
	PUSH	IX,IY
	LD	A,EL3_STAGE_TX
	LD	(EL3_LAST_STAGE),A
	LD	(TX_SOURCE),HL
	LD	(TX_INPUT_LENGTH),BC
	CALL	TX_CALCULATE_LENGTHS
	JP	C,.SEND_RETURN
	LD	A,1
	CALL	SELECT_WINDOW
	JP	C,.SEND_RETURN
	LD	A,2
	LD	(TX_ATTEMPTS_LEFT),A
.SEND_ATTEMPT
	CALL	TX_CLEAR_STALE
	JP	C,.SEND_RETURN
	CALL	TX_WAIT_FREE
	JR	C,.SEND_TIMEOUT_OR_IO
	IFDEF	EL3_SESSION_RX
	; TX_BURST (el3_io.asm) writes preamble+frame+both pad regions in one ISA
	; session instead of TX_WRITE_PACKET's four separate FIFO_WRITE/FIFO_ZERO
	; opens; TX_WRITE_PACKET itself stays compiled (FTP does not define
	; EL3_SESSION_RX and still calls it here). Same completion wait as
	; before -- this only shrinks the write, not the TX_WAIT_COMPLETE below.
	CALL	@EL3IO.TX_BURST
	ELSE
	CALL	TX_WRITE_PACKET
	ENDIF
	JP	C,.SEND_RETURN
	CALL	TX_WAIT_COMPLETE
	JR	C,.SEND_TIMEOUT_OR_IO
	LD	A,(EL3_LAST_TX_STATUS)
	LD	D,A
	AND	EL3_TX_ERROR_MASK
	JR	NZ,.SEND_ERROR
	LD	A,D
	AND	EL3_TX_COMPLETE | EL3_TX_NOTIFY
	CP	EL3_TX_COMPLETE | EL3_TX_NOTIFY
	JR	NZ,.SEND_ERROR
	LD	HL,EL3_COUNT_FRAME
	CALL	INC_WORD
	XOR	A
	JR	.SEND_RETURN
.SEND_ERROR
	LD	HL,EL3_COUNT_TX
	CALL	INC_WORD
	LD	A,D
	AND	EL3_TX_OVERFLOW
	JR	NZ,.SEND_OVERFLOW
	LD	A,D
	AND	EL3_TX_JABBER | EL3_TX_UNDERRUN
	JR	NZ,.SEND_RESET_RETRY
	LD	A,D
	AND	EL3_TX_MAX_COLLISION
	JR	NZ,.SEND_ENABLE_RETRY
	JR	.SEND_TX_ERROR
.SEND_RESET_RETRY
	CALL	TX_RECOVER_RESET
	JR	C,.SEND_RETURN
	JR	.SEND_RETRY
.SEND_ENABLE_RETRY
	CALL	TX_RECOVER_ENABLE
	JR	C,.SEND_RETURN
.SEND_RETRY
	LD	A,(TX_ATTEMPTS_LEFT)
	DEC	A
	LD	(TX_ATTEMPTS_LEFT),A
	JR	NZ,.SEND_ATTEMPT
	JR	.SEND_TX_ERROR
.SEND_OVERFLOW
	CALL	TX_RECOVER_ENABLE
	JR	C,.SEND_RETURN
.SEND_TX_ERROR
	LD	A,EL3_ERR_TX_ERROR
	SCF
	JR	.SEND_RETURN
.SEND_TIMEOUT_OR_IO
	CP	EL3_ERR_TX_TIMEOUT
	JR	NZ,.SEND_RETURN
	LD	HL,(EL3_LAST_TICKS)
	LD	(TX_TIMEOUT_TICKS),HL
	LD	HL,(EL3_LAST_STATUS)
	LD	(TX_TIMEOUT_STATUS),HL
	CALL	TX_RECOVER_RESET
	LD	HL,(TX_TIMEOUT_TICKS)
	LD	(EL3_LAST_TICKS),HL
	LD	HL,(TX_TIMEOUT_STATUS)
	LD	(EL3_LAST_STATUS),HL
	LD	A,EL3_STAGE_TX
	LD	(EL3_LAST_STAGE),A
	LD	A,EL3_ERR_TX_TIMEOUT
	SCF
.SEND_RETURN
	POP	IY,IX
	RET

; RX_PENDING
; Out: A=0/1, CF=0; error/CF=1. Error-status complete entries are pending.
; Clobbers AF, BC, DE and HL; preserves IX and IY.
RX_PENDING
	PUSH	IX,IY
	LD	A,EL3_STAGE_RX
	LD	(EL3_LAST_STAGE),A
	LD	A,1
	CALL	SELECT_WINDOW
	JR	C,.PENDING_RETURN
	LD	E,EL3_W1_RX_STATUS
	CALL	READ16
	JR	C,.PENDING_RETURN
	LD	(EL3_LAST_RX_STATUS),HL
	LD	A,H
	AND	HIGH EL3_RX_INCOMPLETE
	JR	NZ,.PENDING_NONE
	LD	A,H
	OR	L
	JR	Z,.PENDING_NONE
	LD	A,1
	OR	A
	JR	.PENDING_RETURN
.PENDING_NONE
	XOR	A
.PENDING_RETURN
	POP	IY,IX
	RET

; READ_FRAME
; In: HL=destination, BC=capacity.
; Out: BC=actual/required length on success/FRAME_SIZE; explicit status/CF.
; Consumes the current complete entry with exactly one RX_DISCARD.
; Clobbers AF, BC, DE and HL; preserves IX and IY.
READ_FRAME
	PUSH	IX,IY
	LD	A,EL3_STAGE_RX
	LD	(EL3_LAST_STAGE),A
	LD	(RX_DESTINATION),HL
	LD	(RX_CAPACITY),BC
	LD	HL,0
	LD	(EL3_RX_REQUIRED),HL
	CALL	RX_PENDING
	JP	C,.READ_RETURN
	OR	A
	JP	Z,.READ_NO_FRAME
	LD	HL,(EL3_LAST_RX_STATUS)
	LD	A,H
	AND	0x07
	LD	H,A
	LD	(EL3_RX_REQUIRED),HL
	LD	HL,(EL3_LAST_RX_STATUS)
	BIT	6,H
	JR	NZ,.READ_BAD_STATUS
	LD	HL,(EL3_RX_REQUIRED)
	LD	DE,EL3_FRAME_WIRE_MIN
	OR	A
	SBC	HL,DE
	JR	C,.READ_BAD_LENGTH
	LD	HL,(EL3_RX_REQUIRED)
	LD	DE,EL3_FRAME_MAX+1
	OR	A
	SBC	HL,DE
	JR	NC,.READ_BAD_LENGTH
	LD	HL,(RX_CAPACITY)
	LD	DE,(EL3_RX_REQUIRED)
	OR	A
	SBC	HL,DE
	JR	C,.READ_SMALL
	LD	HL,(RX_DESTINATION)
	LD	BC,(EL3_RX_REQUIRED)
	CALL	@EL3IO.FIFO_READ
	JR	C,.READ_IO_FAILED
	LD	HL,(EL3_RX_REQUIRED)
	LD	A,L
	NEG
	AND	3
	LD	C,A
	LD	B,0
	CALL	@EL3IO.FIFO_SKIP
	JR	C,.READ_IO_FAILED
	CALL	RX_DISCARD_CURRENT
	JR	C,.READ_RETURN
	LD	HL,EL3_COUNT_FRAME
	CALL	INC_WORD
	LD	BC,(EL3_RX_REQUIRED)
	XOR	A
	JR	.READ_RETURN
.READ_SMALL
	CALL	RX_DROP_CURRENT
	LD	BC,(EL3_RX_REQUIRED)
	JR	C,.READ_RETURN
	LD	A,EL3_ERR_FRAME_SIZE
	SCF
	JR	.READ_RETURN
.READ_BAD_STATUS
.READ_BAD_LENGTH
	LD	HL,EL3_COUNT_RX
	CALL	INC_WORD
	CALL	RX_DROP_CURRENT
	JR	C,.READ_RETURN
	LD	A,EL3_ERR_RX_ERROR
	SCF
	JR	.READ_RETURN
.READ_IO_FAILED
	LD	(RX_SAVED_ERROR),A
	CALL	RX_DROP_CURRENT
	LD	A,(RX_SAVED_ERROR)
	SCF
	JR	.READ_RETURN
.READ_NO_FRAME
	LD	A,EL3_ERR_NO_FRAME
	SCF
.READ_RETURN
	POP	IY,IX
	RET

	IFNDEF STAGE12_LAYOUT
; DISCARD_FRAME
; Discards only the current complete packet. Empty/incomplete FIFO is NO_FRAME.
; Out: A=EL3_OK/CF=0 or explicit error/CF=1.
; Clobbers AF, BC, DE and HL; preserves IX and IY.
DISCARD_FRAME
	PUSH	IX,IY
	LD	A,EL3_STAGE_RX
	LD	(EL3_LAST_STAGE),A
	CALL	RX_PENDING
	JR	C,.DISCARD_RETURN
	OR	A
	JR	Z,.DISCARD_EMPTY
	CALL	RX_DROP_CURRENT
	JR	.DISCARD_RETURN
.DISCARD_EMPTY
	LD	A,EL3_ERR_NO_FRAME
	SCF
.DISCARD_RETURN
	POP	IY,IX
	RET
	ENDIF

; LOOPBACK_ENABLE / LOOPBACK_DISABLE
; Diagnostic-only RMW of Window 4 Net Diagnostic bit 13. Both verify the
; result and return to Window 1. Clobbers AF, BC, DE and HL; preserves IX/IY.
; Out: A=EL3_OK/CF=0 or explicit error/CF=1.
LOOPBACK_ENABLE
	IFNDEF STAGE12_LAYOUT
	PUSH	IX,IY
	LD	A,1
	CALL	LOOPBACK_SET
	POP	IY,IX
	RET
	ENDIF

	IFNDEF STAGE12_LAYOUT		; no caller in a STAGE12 image; see el3_regs.asm INIT
LOOPBACK_DISABLE
	PUSH	IX,IY
	XOR	A
	CALL	LOOPBACK_SET
	POP	IY,IX
	RET

LOOPBACK_SET
	LD	(LOOPBACK_REQUEST),A
	LD	A,EL3_STAGE_LOOPBACK
	LD	(EL3_LAST_STAGE),A
	LD	A,4
	CALL	SELECT_WINDOW
	RET	C
	LD	E,EL3_W4_NET_DIAG
	CALL	READ16
	JR	C,.LOOPBACK_RESTORE
	LD	A,(LOOPBACK_REQUEST)
	OR	A
	JR	Z,.LOOPBACK_CLEAR
	SET	5,H
	JR	.LOOPBACK_WRITE
.LOOPBACK_CLEAR
	RES	5,H
.LOOPBACK_WRITE
	LD	E,EL3_W4_NET_DIAG
	CALL	WRITE16
	JR	C,.LOOPBACK_RESTORE
	LD	E,EL3_W4_NET_DIAG
	CALL	READ16
	JR	C,.LOOPBACK_RESTORE
	LD	A,H
	AND	HIGH EL3_NET_DIAG_LOOPBACK
	LD	D,A
	LD	A,(LOOPBACK_REQUEST)
	OR	A
	JR	Z,.LOOPBACK_EXPECT_CLEAR
	LD	A,D
	CP	HIGH EL3_NET_DIAG_LOOPBACK
	JR	NZ,.LOOPBACK_BAD
	JR	.LOOPBACK_OK
.LOOPBACK_EXPECT_CLEAR
	LD	A,D
	OR	A
	JR	NZ,.LOOPBACK_BAD
.LOOPBACK_OK
	XOR	A
	LD	(LOOPBACK_SAVED_ERROR),A
	JR	.LOOPBACK_SELECT_ONE
.LOOPBACK_BAD
	LD	A,EL3_ERR_LOOPBACK_VERIFY
	LD	(LOOPBACK_SAVED_ERROR),A
	JR	.LOOPBACK_SELECT_ONE
.LOOPBACK_RESTORE
	LD	(LOOPBACK_SAVED_ERROR),A
.LOOPBACK_SELECT_ONE
	LD	A,1
	CALL	SELECT_WINDOW
	JR	C,.LOOPBACK_RETURN
	LD	A,(LOOPBACK_SAVED_ERROR)
	OR	A
	RET	Z
	SCF
.LOOPBACK_RETURN
	RET
	ENDIF

TX_CALCULATE_LENGTHS
	LD	HL,(TX_INPUT_LENGTH)
	LD	DE,EL3_FRAME_MIN
	OR	A
	SBC	HL,DE
	JR	C,.TX_SIZE_BAD
	LD	HL,(TX_INPUT_LENGTH)
	LD	DE,EL3_FRAME_MAX+1
	OR	A
	SBC	HL,DE
	JR	NC,.TX_SIZE_BAD
	LD	HL,(TX_INPUT_LENGTH)
	LD	DE,EL3_FRAME_WIRE_MIN
	OR	A
	SBC	HL,DE
	JR	NC,.TX_EFFECTIVE_INPUT
	LD	HL,EL3_FRAME_WIRE_MIN
	JR	.TX_EFFECTIVE_STORE
.TX_EFFECTIVE_INPUT
	LD	HL,(TX_INPUT_LENGTH)
.TX_EFFECTIVE_STORE
	LD	(TX_EFFECTIVE_LENGTH),HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,L
	AND	0xFC
	LD	L,A
	LD	DE,4
	ADD	HL,DE
	LD	(TX_REQUIRED_BYTES),HL
	XOR	A
	RET
.TX_SIZE_BAD
	LD	A,EL3_ERR_FRAME_SIZE
	SCF
	RET

TX_CLEAR_STALE
	LD	B,31
.TX_STALE_LOOP
	LD	E,EL3_W1_TX_STATUS
	CALL	READ8
	RET	C
	LD	A,L
	AND	EL3_TX_COMPLETE
	RET	Z
	XOR	A
	LD	E,EL3_W1_TX_STATUS
	CALL	WRITE8
	RET	C
	DJNZ	.TX_STALE_LOOP
	XOR	A
	RET

TX_WAIT_FREE
	LD	HL,0
	LD	(EL3_LAST_TICKS),HL
.TX_FREE_POLL
	LD	E,EL3_W1_TX_FREE
	CALL	READ16
	RET	C
	LD	(EL3_LAST_STATUS),HL
	LD	DE,(TX_REQUIRED_BYTES)
	OR	A
	SBC	HL,DE
	RET	NC
	CALL	FIFO_WAIT_NEXT
	JR	NC,.TX_FREE_POLL
	RET

; Compiled out under EL3_SESSION_RX: .SEND_ATTEMPT above calls
; @EL3IO.TX_BURST instead, which does the same work in one ISA session. The
; source stays here regardless -- check-stage5.pl anchors the preamble formula
; and the FIFO_WRITE/FIFO_ZERO calls on it.
	IFNDEF	EL3_SESSION_RX
TX_WRITE_PACKET
	LD	HL,(TX_EFFECTIVE_LENGTH)
	LD	A,L
	LD	(TX_PREAMBLE),A
	LD	A,H
	OR	0x80
	LD	(TX_PREAMBLE+1),A
	XOR	A
	LD	(TX_PREAMBLE+2),A
	LD	(TX_PREAMBLE+3),A
	LD	HL,TX_PREAMBLE
	LD	BC,4
	CALL	@EL3IO.FIFO_WRITE
	RET	C
	LD	HL,(TX_SOURCE)
	LD	BC,(TX_INPUT_LENGTH)
	CALL	@EL3IO.FIFO_WRITE
	RET	C
	LD	HL,(TX_EFFECTIVE_LENGTH)
	LD	BC,(TX_INPUT_LENGTH)
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L
	CALL	@EL3IO.FIFO_ZERO
	RET	C
	LD	HL,(TX_EFFECTIVE_LENGTH)
	LD	A,L
	NEG
	AND	3
	LD	C,A
	LD	B,0
	JP	@EL3IO.FIFO_ZERO
	ENDIF

TX_WAIT_COMPLETE
	LD	HL,0
	LD	(EL3_LAST_TICKS),HL
.TX_COMPLETE_POLL
	LD	E,EL3_W1_TX_STATUS
	CALL	READ8
	RET	C
	LD	A,L
	LD	(EL3_LAST_TX_STATUS),A
	AND	EL3_TX_COMPLETE
	JR	NZ,.TX_COMPLETE_POP
	CALL	FIFO_WAIT_NEXT
	JR	NC,.TX_COMPLETE_POLL
	RET
.TX_COMPLETE_POP
	XOR	A
	LD	E,EL3_W1_TX_STATUS
	JP	WRITE8

FIFO_WAIT_NEXT
	LD	HL,(EL3_LAST_TICKS)
	LD	DE,EL3_FIFO_WAIT_QUANTA
	OR	A
	SBC	HL,DE
	JR	NC,.FIFO_TIMEOUT
	CALL	WAIT_QUANTUM
	LD	HL,(EL3_LAST_TICKS)
	INC	HL
	LD	(EL3_LAST_TICKS),HL
	OR	A
	RET
.FIFO_TIMEOUT
	LD	HL,EL3_COUNT_TIMEOUT
	CALL	INC_WORD
	LD	A,EL3_ERR_TX_TIMEOUT
	SCF
	RET

TX_RECOVER_RESET
	CALL	RESET_TX
	JR	C,TX_RECOVER_RETURN
	LD	HL,EL3_CMD_SET_TX_AVAIL | EL3_THRESHOLD_DISABLED
	CALL	CMD_SYNC
	JR	C,TX_RECOVER_RETURN
	LD	HL,EL3_CMD_SET_TX_START | EL3_TX_START_VALUE
	CALL	CMD_SYNC
	JR	C,TX_RECOVER_RETURN
TX_RECOVER_ENABLE
	LD	HL,EL3_CMD_TX_ENABLE
	CALL	CMD_SYNC
	JR	C,TX_RECOVER_RETURN
	LD	A,1
	CALL	SELECT_WINDOW
TX_RECOVER_RETURN
	RET

RX_DROP_CURRENT
	LD	HL,EL3_COUNT_DROP
	CALL	INC_WORD
RX_DISCARD_CURRENT
	LD	HL,EL3_CMD_RX_DISCARD
	CALL	CMD_SYNC
	RET	NC
	CP	EL3_ERR_CMD_TIMEOUT
	RET	NZ
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET

TX_SOURCE		DW 0
TX_INPUT_LENGTH		DW 0
TX_EFFECTIVE_LENGTH	DW 0
TX_REQUIRED_BYTES	DW 0
TX_PREAMBLE		DS 4,0
TX_ATTEMPTS_LEFT	DB 0
TX_TIMEOUT_TICKS	DW 0
TX_TIMEOUT_STATUS	DW 0
RX_DESTINATION		DW 0
RX_CAPACITY		DW 0
RX_SAVED_ERROR		DB 0
LOOPBACK_REQUEST	DB 0
LOOPBACK_SAVED_ERROR	DB 0

	ENDMODULE
	ENDIF
