; Path-aware DSS file helpers for Stage 9 TFTP.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_FILE_ASM
	DEFINE	_FILE_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"

	MODULE FILE

	IFDEF STAGE13_LAYOUT
FILE_SAVED_CWD	EQU F13_SAVED_CWD
FILE_SAVED_CWD_CAPACITY EQU 256
FILE_DIR_BUFFER	EQU FILE_SAVED_CWD+FILE_SAVED_CWD_CAPACITY
	ELSE
	IFDEF STAGE12_LAYOUT
; A literal 0x7B00 used to sit below PAGE_BASE, inside the range WGET's own
; growing image occupies -- a bigger build would silently overlap live code
; with no assembler error. The gap between the pending region and the TCP
; context (memory.inc) is unused page space instead.
FILE_SAVED_CWD	EQU PAGE_BASE + 0x2A78
	ELSE
FILE_SAVED_CWD	EQU STAGE9_SCRATCH
	ENDIF
FILE_SAVED_CWD_CAPACITY EQU 256
FILE_DIR_BUFFER	EQU FILE_SAVED_CWD+FILE_SAVED_CWD_CAPACITY

	ASSERT FILE_DIR_BUFFER+96 <= STAGE9_SCRATCH+STAGE9_SCRATCH_CAPACITY
	IFDEF STAGE12_LAYOUT
	ASSERT FILE_DIR_BUFFER+96 <= S11_CONTEXT0
	ENDIF
	ENDIF

; OPEN_OUTPUT
; In: HL=ASCIIZ path, A=0 prompt or nonzero force overwrite.
; Out: A=handle/CF=0; code 23 for refusal, code 26 for I/O failure.
OPEN_OUTPUT
	LD	(S9_TFTP_FORCE),A
	CALL	SETUP_PATH
	JR	C,.IO_BAD
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	NC,.EXISTS
	CP	DSS_ERR_FILE_NOT_FOUND	; only "not found" authorizes creation
	JR	NZ,.IO_BAD
	JR	.CREATE
.EXISTS
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	C,.IO_BAD
	IFNDEF STAGE12_LAYOUT
	LD	A,(S9_TFTP_FORCE)
	OR	A
	JR	NZ,.DELETE
	LD	HL,MSG_EXISTS
	LD	C,DSS_PCHARS
	RST	DSS
	LD	HL,(S9_RX_PAYLOAD)
	LD	C,DSS_PCHARS
	RST	DSS
	LD	HL,MSG_PROMPT
	LD	C,DSS_PCHARS
	RST	DSS
	CALL	WAIT_YES_NO
	JR	C,.CANCEL
	ENDIF
.DELETE
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	C,DSS_DELETE
	RST	DSS
	JR	C,.IO_BAD
.CREATE
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	JR	C,.IO_BAD
	LD	(S9_TFTP_FILE_HANDLE),A
	CALL	RESTORE_CWD
	JR	C,.CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	RET
.CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	.IO_BAD_DIRECT
	IFNDEF STAGE12_LAYOUT
.CANCEL
	CALL	RESTORE_CWD
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
	ENDIF
.IO_BAD
	CALL	RESTORE_CWD
.IO_BAD_DIRECT
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

	IFDEF STAGE12_LAYOUT
; OPEN_OUTPUT_ORC implements the sibling WGET overwrite/resume contract.
; In: HL=path, A=0 prompt, 1 overwrite, 2 resume. Out: A=handle, B=1 only
; when append/resume was selected. All DSS calls occur with the ISA window
; closed because NETDRV maps it only for individual hardware transactions.
OPEN_OUTPUT_ORC
	PUSH	AF
	PUSH	HL
	LD	HL,0
	LD	(W12_RESUME_OFFSET),HL
	LD	(W12_RESUME_OFFSET+2),HL
	XOR	A
	LD	(W12_RESUME_SELECTED),A
	POP	HL
	POP	AF
	OR	A
	JR	Z,.ORC_ASK
	CP	2
	JP	Z,OPEN_APPEND
	LD	A,1
	CALL	OPEN_OUTPUT
	RET	C
	LD	B,0
	RET
.ORC_ASK
	PUSH	HL
	CALL	SETUP_PATH
	JR	C,.ORC_FAIL_POP
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.ORC_MISSING
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	C,.ORC_RESTORE_FAIL
	LD	HL,MSG_LOCAL_FILE
	LD	C,DSS_PCHARS
	RST	DSS
	LD	HL,(S9_RX_PAYLOAD)
	LD	C,DSS_PCHARS
	RST	DSS
	LD	HL,MSG_ORC_PROMPT
	LD	C,DSS_PCHARS
	RST	DSS
	CALL	WAIT_ORC
	PUSH	AF
	CALL	RESTORE_CWD
	POP	AF
	POP	HL
	CP	'R'
	JP	Z,OPEN_APPEND
	CP	'O'
	JR	NZ,.ORC_CANCEL
	LD	A,1
	CALL	OPEN_OUTPUT
	RET	C
	LD	B,0
	RET
.ORC_CANCEL
	LD	HL,MSG_ABORTED
	LD	C,DSS_PCHARS
	RST	DSS
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.ORC_MISSING
	CP	DSS_ERR_FILE_NOT_FOUND
	JR	NZ,.ORC_RESTORE_FAIL
	CALL	RESTORE_CWD
	POP	HL
	LD	A,1
	CALL	OPEN_OUTPUT
	RET	C
	LD	B,0
	RET
.ORC_RESTORE_FAIL
	CALL	RESTORE_CWD
.ORC_FAIL_POP
	POP	HL
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

; OPEN_APPEND opens read/write and seeks to EOF without modifying the file.
; DSS MOVE_FP uses HL:IX for the signed offset/result (high:low words).
OPEN_APPEND
	CALL	SETUP_PATH
	JR	C,.APPEND_BAD
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FM_READ_WRITE
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.APPEND_MISSING
	LD	(W12_FILE_HANDLE),A
	LD	B,SEEK_END
	LD	HL,0
	LD	IX,0
	LD	C,DSS_MOVE_FP
	RST	DSS
	JR	C,.APPEND_SEEK_BAD
	LD	(W12_RESUME_OFFSET),IX
	LD	(W12_RESUME_OFFSET+2),HL
	CALL	RESTORE_CWD
	JR	C,.APPEND_CLOSE_BAD
	LD	A,1
	LD	(W12_RESUME_SELECTED),A
	LD	B,A
	LD	A,(W12_FILE_HANDLE)
	OR	A
	RET
.APPEND_MISSING
	CP	DSS_ERR_FILE_NOT_FOUND
	JR	NZ,.APPEND_BAD
	CALL	RESTORE_CWD
	LD	HL,(S9_RX_PAYLOAD)
	LD	A,1
	CALL	OPEN_OUTPUT
	RET	C
	LD	C,A
	XOR	A			; a missing target is fresh, not a preserved resume file
	LD	(W12_RESUME_SELECTED),A
	LD	B,A
	LD	A,C
	OR	A
	RET
.APPEND_SEEK_BAD
	LD	A,(W12_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	.APPEND_BAD
.APPEND_CLOSE_BAD
	LD	A,(W12_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
.APPEND_BAD
	CALL	RESTORE_CWD
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

WAIT_ORC
	LD	B,DSS_WAITKEY
	LD	C,DSS_K_CLEAR
	RST	DSS
	PUSH	AF
	LD	C,DSS_PUTCHAR
	RST	DSS
	LD	A,13
	LD	C,DSS_PUTCHAR
	RST	DSS
	LD	A,10
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	AF
	CP	0x1B
	JR	Z,.ORC_CANCEL_KEY
	AND	0xDF
	CP	'R'
	RET	Z
	CP	'O'
	RET	Z
	CP	'Y'
	JR	Z,.ORC_OVERWRITE
	CP	'C'
	JR	Z,.ORC_CANCEL_KEY
	CP	'N'
	JR	NZ,WAIT_ORC
.ORC_CANCEL_KEY
	LD	A,'C'
	RET
.ORC_OVERWRITE
	LD	A,'O'
	RET

MSG_LOCAL_FILE	DB "Local file '",0
MSG_ORC_PROMPT	DB "' exists. Overwrite/Resume/Cancel [O/R/C]? ",0
MSG_ABORTED	DB "Aborted by user.",13,10,0
	ENDIF

; OPEN_INPUT is needed by any app that reads a local file: plain TFTP PUT,
; and FTP's STOR (STAGE13_LAYOUT). WGET and DLSPEED never read one and cannot
; spare the bytes, so it stays excluded for STAGE12_LAYOUT builds that are
; not also STAGE13_LAYOUT.
	IFDEF STAGE12_LAYOUT
	IFDEF STAGE13_LAYOUT
	DEFINE FILE_NEEDS_OPEN_INPUT
	ENDIF
	ELSE
	DEFINE FILE_NEEDS_OPEN_INPUT
	ENDIF
	IFDEF FILE_NEEDS_OPEN_INPUT
; OPEN_INPUT: path-aware read-only open.
OPEN_INPUT
	CALL	SETUP_PATH
	JR	C,.BAD
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.BAD
	LD	(S9_TFTP_FILE_HANDLE),A
	CALL	RESTORE_CWD
	JR	C,.INPUT_CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	RET
.INPUT_CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	.BAD_DIRECT
.BAD
	CALL	RESTORE_CWD
.BAD_DIRECT
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

; READ_CHUNK is a thin wrapper over DSS_READ_FILE for STOR's upload slices.
; In: A=handle, HL=buffer, DE=capacity. Out: DE=bytes actually read (0=EOF);
; CF/A set only on a genuine I/O error, never on a short final read.
READ_CHUNK
	LD	C,DSS_READ_FILE
	RST	DSS
	RET	C
	XOR	A
	RET
	ENDIF

; BASENAME returns the byte after the last slash/backslash, or the input.
BASENAME
	LD	DE,HL
.BASE_SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.BASE_DONE
	CP	'/'
	JR	Z,.BASE_HIT
	CP	0x5C
	JR	NZ,.BASE_NEXT
.BASE_HIT
	INC	HL
	LD	DE,HL
	DEC	HL
.BASE_NEXT
	INC	HL
	JR	.BASE_SCAN
.BASE_DONE
	EX	DE,HL
	RET

; SETUP_PATH saves CWD, isolates the basename, and temporarily changes into
; the directory component. All input/output strings are bounded to 95 bytes.
SETUP_PATH
	LD	(S9_RX_PAYLOAD),HL	; full original path
	LD	(S9_RX_SOURCE_PORT),HL	; basename unless a separator is found
	XOR	A
	LD	(S9_FLAGS),A		; CWD changed flag
	LD	HL,FILE_SAVED_CWD
	LD	C,DSS_CURDIR
	RST	DSS
	JR	C,.SETUP_BAD
	LD	HL,(S9_RX_PAYLOAD)
	LD	DE,0
	LD	B,0
.SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.SCAN_DONE
	INC	B
	LD	A,B
	CP	96
	JR	NC,.SETUP_BAD
	LD	A,(HL)
	CP	'/'
	JR	Z,.HIT
	CP	0x5C
	JR	NZ,.NEXT
.HIT
	LD	D,H
	LD	E,L
.NEXT
	INC	HL
	JR	.SCAN
.SCAN_DONE
	LD	A,D
	OR	E
	JR	Z,.NO_DIR
	PUSH	DE
	INC	DE
	LD	(S9_RX_SOURCE_PORT),DE
	POP	DE
	LD	HL,(S9_RX_PAYLOAD)
	LD	BC,FILE_DIR_BUFFER
	LD	A,H
	CP	D
	JR	NZ,.COPY_DIR
	LD	A,L
	CP	E
	JR	NZ,.COPY_DIR
	LD	A,0x5C			; absolute root path
	LD	(BC),A
	INC	BC
	JR	.DIR_TERM
.COPY_DIR
	LD	A,H
	CP	D
	JR	NZ,.COPY_BYTE
	LD	A,L
	CP	E
	JR	NZ,.COPY_BYTE
	; Preserve the final separator in a drive-qualified directory. In
	; particular, a bare "C:" selects that drive's current directory rather
	; than the root intended by "C:\\".
	LD	HL,(S9_RX_PAYLOAD)
	INC	HL
	LD	A,(HL)
	CP	':'
	JR	NZ,.DIR_TERM
	LD	A,(DE)
	LD	(BC),A
	INC	BC
	JR	.DIR_TERM
.COPY_BYTE
	LD	A,(HL)
	LD	(BC),A
	INC	HL
	INC	BC
	JR	.COPY_DIR
.DIR_TERM
	XOR	A
	LD	(BC),A
	LD	HL,FILE_DIR_BUFFER
	LD	C,DSS_CHDIR
	RST	DSS
	JR	C,.SETUP_BAD
	LD	A,1
	LD	(S9_FLAGS),A
.NO_DIR
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,(HL)
	OR	A
	JR	Z,.SETUP_BAD
	XOR	A
	RET
.SETUP_BAD
	SCF
	RET

RESTORE_CWD
	LD	A,(S9_FLAGS)
	OR	A
	RET	Z
	XOR	A
	LD	(S9_FLAGS),A
	LD	HL,FILE_SAVED_CWD
	LD	C,DSS_CHDIR
	RST	DSS
	RET

	IFNDEF STAGE12_LAYOUT
WAIT_YES_NO
	LD	B,DSS_WAITKEY
	LD	C,DSS_K_CLEAR
	RST	DSS
	CP	0x1B
	JR	Z,.NO
	AND	0xDF
	CP	'Y'
	JR	Z,.YES
	CP	'N'
	JR	NZ,WAIT_YES_NO
.NO
	SCF
	RET
.YES
	OR	A
	RET

MSG_EXISTS	DB "File '",0
MSG_PROMPT	DB "' exists. Overwrite [Y/N]? ",0
	ENDIF

	ENDMODULE
	ENDIF
