; Path-aware DSS file helpers for Stage 9 TFTP.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_FILE_ASM
	DEFINE	_FILE_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"

	MODULE FILE

FILE_SAVED_CWD	EQU STAGE9_SCRATCH
FILE_SAVED_CWD_CAPACITY EQU 256
FILE_DIR_BUFFER	EQU FILE_SAVED_CWD+FILE_SAVED_CWD_CAPACITY

	ASSERT FILE_DIR_BUFFER+96 <= STAGE9_SCRATCH+STAGE9_SCRATCH_CAPACITY

; OPEN_OUTPUT
; In: HL=ASCIIZ path, A=0 prompt or nonzero force overwrite.
; Out: A=handle/CF=0; code 23 for refusal, code 26 for I/O failure.
OPEN_OUTPUT
	LD	(S9_TFTP_FORCE),A
	CALL	SETUP_PATH
	JR	C,.IO_BAD
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	NC,.EXISTS
	CP	DSS_ERR_FILE_NOT_FOUND	; only "not found" authorizes creation
	JR	NZ,.IO_BAD
	JR	.CREATE
.EXISTS
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	C,.IO_BAD
	LD	A,(S9_TFTP_FORCE)
	OR	A
	JR	NZ,.DELETE
	LD	HL,MSG_EXISTS
	LD	C,DSS_PCHARS
	RST	DSS
	LD	HL,(S9_RX_PAYLOAD)
	LD	C,DSS_PCHARS
	RST	DSS
	LD	HL,MSG_PROMPT
	LD	C,DSS_PCHARS
	RST	DSS
	CALL	WAIT_YES_NO
	JR	C,.CANCEL
.DELETE
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	C,DSS_DELETE
	RST	DSS
	JR	C,.IO_BAD
.CREATE
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	JR	C,.IO_BAD
	LD	(S9_TFTP_FILE_HANDLE),A
	CALL	RESTORE_CWD
	JR	C,.CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	RET
.CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	.IO_BAD_DIRECT
.CANCEL
	CALL	RESTORE_CWD
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.IO_BAD
	CALL	RESTORE_CWD
.IO_BAD_DIRECT
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

; OPEN_INPUT: path-aware read-only open.
OPEN_INPUT
	CALL	SETUP_PATH
	JR	C,.BAD
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.BAD
	LD	(S9_TFTP_FILE_HANDLE),A
	CALL	RESTORE_CWD
	JR	C,.INPUT_CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	RET
.INPUT_CLOSE_BAD
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	.BAD_DIRECT
.BAD
	CALL	RESTORE_CWD
.BAD_DIRECT
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

; BASENAME returns the byte after the last slash/backslash, or the input.
BASENAME
	LD	DE,HL
.BASE_SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.BASE_DONE
	CP	'/'
	JR	Z,.BASE_HIT
	CP	0x5C
	JR	NZ,.BASE_NEXT
.BASE_HIT
	INC	HL
	LD	DE,HL
	DEC	HL
.BASE_NEXT
	INC	HL
	JR	.BASE_SCAN
.BASE_DONE
	EX	DE,HL
	RET

; SETUP_PATH saves CWD, isolates the basename, and temporarily changes into
; the directory component. All input/output strings are bounded to 95 bytes.
SETUP_PATH
	LD	(S9_RX_PAYLOAD),HL	; full original path
	LD	(S9_RX_SOURCE_PORT),HL	; basename unless a separator is found
	XOR	A
	LD	(S9_FLAGS),A		; CWD changed flag
	LD	HL,FILE_SAVED_CWD
	LD	C,DSS_CURDIR
	RST	DSS
	JR	C,.SETUP_BAD
	LD	HL,(S9_RX_PAYLOAD)
	LD	DE,0
	LD	B,0
.SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.SCAN_DONE
	INC	B
	LD	A,B
	CP	96
	JR	NC,.SETUP_BAD
	LD	A,(HL)
	CP	'/'
	JR	Z,.HIT
	CP	0x5C
	JR	NZ,.NEXT
.HIT
	LD	D,H
	LD	E,L
.NEXT
	INC	HL
	JR	.SCAN
.SCAN_DONE
	LD	A,D
	OR	E
	JR	Z,.NO_DIR
	PUSH	DE
	INC	DE
	LD	(S9_RX_SOURCE_PORT),DE
	POP	DE
	LD	HL,(S9_RX_PAYLOAD)
	LD	BC,FILE_DIR_BUFFER
	LD	A,H
	CP	D
	JR	NZ,.COPY_DIR
	LD	A,L
	CP	E
	JR	NZ,.COPY_DIR
	LD	A,0x5C			; absolute root path
	LD	(BC),A
	INC	BC
	JR	.DIR_TERM
.COPY_DIR
	LD	A,H
	CP	D
	JR	NZ,.COPY_BYTE
	LD	A,L
	CP	E
	JR	NZ,.COPY_BYTE
	; Preserve the final separator in a drive-qualified directory. In
	; particular, a bare "C:" selects that drive's current directory rather
	; than the root intended by "C:\\".
	LD	HL,(S9_RX_PAYLOAD)
	INC	HL
	LD	A,(HL)
	CP	':'
	JR	NZ,.DIR_TERM
	LD	A,(DE)
	LD	(BC),A
	INC	BC
	JR	.DIR_TERM
.COPY_BYTE
	LD	A,(HL)
	LD	(BC),A
	INC	HL
	INC	BC
	JR	.COPY_DIR
.DIR_TERM
	XOR	A
	LD	(BC),A
	LD	HL,FILE_DIR_BUFFER
	LD	C,DSS_CHDIR
	RST	DSS
	JR	C,.SETUP_BAD
	LD	A,1
	LD	(S9_FLAGS),A
.NO_DIR
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	A,(HL)
	OR	A
	JR	Z,.SETUP_BAD
	XOR	A
	RET
.SETUP_BAD
	SCF
	RET

RESTORE_CWD
	LD	A,(S9_FLAGS)
	OR	A
	RET	Z
	XOR	A
	LD	(S9_FLAGS),A
	LD	HL,FILE_SAVED_CWD
	LD	C,DSS_CHDIR
	RST	DSS
	RET

WAIT_YES_NO
	LD	B,DSS_WAITKEY
	LD	C,DSS_K_CLEAR
	RST	DSS
	CP	0x1B
	JR	Z,.NO
	AND	0xDF
	CP	'Y'
	JR	Z,.YES
	CP	'N'
	JR	NZ,WAIT_YES_NO
.NO
	SCF
	RET
.YES
	OR	A
	RET

MSG_EXISTS	DB "File '",0
MSG_PROMPT	DB "' exists. Overwrite [Y/N]? ",0

	ENDMODULE
	ENDIF
