; Streaming HTTP response parser shared by DLSPEED and DLDIRECT.
; SPDX-License-Identifier: BSD-3-Clause
;
; The including application supplies the HTTP_*_VAR addresses listed below.
; No application I/O is performed here, so the same parser can be used by a
; native TCPX client and a libman/UNET client.
;
; Public routines:
;   RESET          clears all parser state.
;   PROCESS        HL=bytes, BC=count; consumes an arbitrarily split stream.
;   BODY_COMPLETE CF=0 only after exactly Content-Length body bytes; CF=1 if
;                 more input (or a close delimiter) is still required.
; All routines may clobber AF/BC/DE/HL. HTTP_ERROR_VAR is a stable
; HTTP_ERR_* status and remains sticky once set.

	IFNDEF	_HTTP_STREAM_ASM
	DEFINE	_HTTP_STREAM_ASM

	MODULE HTTPSTREAM

RESET
	XOR	A
	LD	(HTTP_STATE_VAR),A
	LD	(HTTP_HEADER_LENGTH_VAR),A
	LD	(HTTP_CONTENT_KNOWN_VAR),A
	LD	(HTTP_ERROR_VAR),A
	LD	(HTTP_STATUS_SEEN_VAR),A
	LD	HL,0
	LD	(HTTP_STATUS_VAR),HL
	LD	(HTTP_CONTENT_LENGTH_VAR),HL
	LD	(HTTP_CONTENT_LENGTH_VAR+2),HL
	LD	(HTTP_BODY_RECEIVED_VAR),HL
	LD	(HTTP_BODY_RECEIVED_VAR+2),HL
	RET

PROCESS
	LD	A,B
	OR	C
	RET	Z
	LD	A,(HTTP_STATE_VAR)
	CP	4
	JR	Z,.BODY
.HEADER_LOOP
	LD	A,(HL)
	PUSH	HL,BC
	CALL	CAPTURE_HEADER_BYTE
	POP	BC,HL
	LD	A,(HL)
	CALL	HEADER_TRANSITION
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	RET	Z
	LD	A,(HTTP_STATE_VAR)
	CP	4
	JR	NZ,.HEADER_LOOP
.BODY
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	RET	NZ
	LD	A,(HTTP_CONTENT_KNOWN_VAR)
	OR	A
	JR	Z,.ADD_COUNT
	; Cap this chunk at the declared remainder. Bytes following the body are
	; not part of the measured entity, even if a peer pipelines them into the
	; same TCP delivery.
	PUSH	BC
	LD	HL,(HTTP_CONTENT_LENGTH_VAR)
	LD	DE,(HTTP_BODY_RECEIVED_VAR)
	OR	A
	SBC	HL,DE
	LD	(HTTP_WORK32_VAR),HL
	LD	HL,(HTTP_CONTENT_LENGTH_VAR+2)
	LD	DE,(HTTP_BODY_RECEIVED_VAR+2)
	SBC	HL,DE
	JR	C,.ZERO_COUNT
	LD	A,H
	OR	L
	JR	NZ,.FULL_COUNT
	LD	HL,(HTTP_WORK32_VAR)
	POP	BC
	PUSH	BC
	OR	A
	SBC	HL,BC
	JR	NC,.FULL_COUNT
	LD	BC,(HTTP_WORK32_VAR)
	POP	DE
	JR	.ADD_COUNT
.ZERO_COUNT
	POP	BC
	LD	BC,0
	JR	.ADD_COUNT
.FULL_COUNT
	POP	BC
.ADD_COUNT
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	ADD	HL,BC
	LD	(HTTP_BODY_RECEIVED_VAR),HL
	RET	NC
	LD	HL,(HTTP_BODY_RECEIVED_VAR+2)
	INC	HL
	LD	(HTTP_BODY_RECEIVED_VAR+2),HL
	RET

BODY_COMPLETE
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	JR	NZ,.MORE
	LD	A,(HTTP_STATE_VAR)
	CP	4
	JR	NZ,.MORE
	LD	A,(HTTP_CONTENT_KNOWN_VAR)
	OR	A
	JR	Z,.MORE
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	LD	DE,(HTTP_CONTENT_LENGTH_VAR)
	OR	A
	SBC	HL,DE
	LD	HL,(HTTP_BODY_RECEIVED_VAR+2)
	LD	DE,(HTTP_CONTENT_LENGTH_VAR+2)
	SBC	HL,DE
	RET
.MORE
	SCF
	RET

CAPTURE_HEADER_BYTE
	LD	(.BYTE),A
	CP	10
	RET	Z
	CP	13
	JR	Z,.EOL
	LD	A,(HTTP_HEADER_LENGTH_VAR)
	CP	255
	JR	NC,.OVERFLOW
	LD	E,A
	LD	D,0
	LD	HL,HTTP_HEADER_LINE_VAR
	ADD	HL,DE
	LD	A,(.BYTE)
	LD	(HL),A
	LD	HL,HTTP_HEADER_LENGTH_VAR
	INC	(HL)
	RET
.OVERFLOW
	LD	A,HTTP_ERR_HEADER
	CALL	SET_ERROR
	RET
.EOL
	LD	A,(HTTP_HEADER_LENGTH_VAR)
	LD	E,A
	LD	D,0
	LD	HL,HTTP_HEADER_LINE_VAR
	ADD	HL,DE
	LD	(HL),0
	LD	A,(HTTP_STATUS_SEEN_VAR)
	OR	A
	JR	NZ,.HEADER
	CALL	PARSE_STATUS_LINE
	LD	A,1
	LD	(HTTP_STATUS_SEEN_VAR),A
	JR	.RESET_LINE
.HEADER
	CALL	CHECK_HEADER
.RESET_LINE
	XOR	A
	LD	(HTTP_HEADER_LENGTH_VAR),A
	RET
.BYTE	DB 0

HEADER_TRANSITION
	LD	(.BYTE),A
	LD	A,(HTTP_STATE_VAR)
	OR	A
	JR	Z,.S0
	CP	1
	JR	Z,.S1
	CP	2
	JR	Z,.S2
	CP	3
	JR	Z,.S3
	RET
.S0
	LD	A,(.BYTE)
	CP	13
	RET	NZ
	LD	A,1
	JR	.STORE
.S1
	LD	A,(.BYTE)
	CP	10
	LD	A,2
	JR	Z,.STORE
	LD	A,(.BYTE)
	CP	13
	LD	A,1
	JR	Z,.STORE
	XOR	A
	JR	.STORE
.S2
	LD	A,(.BYTE)
	CP	13
	LD	A,3
	JR	Z,.STORE
	XOR	A
	JR	.STORE
.S3
	LD	A,(.BYTE)
	CP	10
	LD	A,4
	JR	Z,.STORE
	LD	A,(.BYTE)
	CP	13
	LD	A,1
	JR	Z,.STORE
	XOR	A
.STORE
	LD	(HTTP_STATE_VAR),A
	RET
.BYTE	DB 0

CHECK_HEADER
	LD	HL,HTTP_HEADER_LINE_VAR
	LD	DE,LIT_CONTENT_LENGTH
	CALL	MATCH_PREFIX
	JR	Z,PARSE_CONTENT_LENGTH
	LD	HL,HTTP_HEADER_LINE_VAR
	LD	DE,LIT_TRANSFER_ENCODING
	CALL	MATCH_PREFIX
	JR	Z,CHECK_ENCODING_VALUE
	LD	HL,HTTP_HEADER_LINE_VAR
	LD	DE,LIT_CONTENT_ENCODING
	CALL	MATCH_PREFIX
	RET	NZ
	; fall through: both encoding headers use the same identity-only rule.
CHECK_ENCODING_VALUE
	CALL	SKIP_OWS
	LD	A,(HL)
	OR	A
	JR	Z,.UNSUPPORTED
	LD	DE,LIT_IDENTITY
.IDENTITY
	LD	A,(DE)
	OR	A
	JR	Z,.TAIL
	LD	C,A
	LD	A,(HL)
	CALL	TOLOWER
	CP	C
	JR	NZ,.UNSUPPORTED
	INC	HL
	INC	DE
	JR	.IDENTITY
.TAIL
	CALL	SKIP_OWS
	LD	A,(HL)
	OR	A
	RET	Z
.UNSUPPORTED
	LD	A,HTTP_ERR_UNSUPPORTED
	JP	SET_ERROR

PARSE_CONTENT_LENGTH
	CALL	SKIP_OWS
	LD	DE,0
	LD	(HTTP_WORK32_VAR),DE
	LD	(HTTP_WORK32_VAR+2),DE
	LD	B,0
.NEXT
	LD	A,(HL)
	SUB	'0'
	JR	C,.END
	CP	10
	JR	NC,.END
	INC	B
	LD	C,A
	PUSH	HL
	CALL	CHECK_WORK32_DIGIT
	JR	C,.OVERFLOW
	CALL	MUL_WORK32_10
	LD	A,(HTTP_WORK32_VAR)
	ADD	A,C
	LD	(HTTP_WORK32_VAR),A
	JR	NC,.NO_CARRY
	LD	HL,HTTP_WORK32_VAR+1
	INC	(HL)
	JR	NZ,.NO_CARRY
	INC	HL
	INC	(HL)
	JR	NZ,.NO_CARRY
	INC	HL
	INC	(HL)
.NO_CARRY
	POP	HL
	INC	HL
	JR	.NEXT
.OVERFLOW
	POP	HL
	JR	.BAD
.END
	LD	A,B
	OR	A
	JR	Z,.BAD
	CALL	SKIP_OWS
	LD	A,(HL)
	OR	A
	JR	NZ,.BAD
	LD	A,(HTTP_CONTENT_KNOWN_VAR)
	OR	A
	JR	Z,.STORE
	LD	HL,(HTTP_CONTENT_LENGTH_VAR)
	LD	DE,(HTTP_WORK32_VAR)
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	LD	HL,(HTTP_CONTENT_LENGTH_VAR+2)
	LD	DE,(HTTP_WORK32_VAR+2)
	SBC	HL,DE
	JR	NZ,.BAD
	RET
.STORE
	LD	HL,(HTTP_WORK32_VAR)
	LD	(HTTP_CONTENT_LENGTH_VAR),HL
	LD	HL,(HTTP_WORK32_VAR+2)
	LD	(HTTP_CONTENT_LENGTH_VAR+2),HL
	LD	A,1
	LD	(HTTP_CONTENT_KNOWN_VAR),A
	RET
.BAD
	LD	A,HTTP_ERR_HEADER
	JP	SET_ERROR

; C=next decimal digit. 4294967295 is the largest representable length, so
; multiplication is safe only below 429496729, or at that value with C<=5.
CHECK_WORK32_DIGIT
	LD	HL,(HTTP_WORK32_VAR+2)
	LD	DE,0x1999
	OR	A
	SBC	HL,DE
	JR	C,.OK
	JR	NZ,.OVERFLOW
	LD	HL,(HTTP_WORK32_VAR)
	LD	DE,0x9999
	OR	A
	SBC	HL,DE
	JR	C,.OK
	JR	NZ,.OVERFLOW
	LD	A,C
	CP	6
	JR	C,.OK
.OVERFLOW
	SCF
	RET
.OK
	OR	A
	RET

MUL_WORK32_10
	CALL	SHIFT_WORK32
	LD	HL,(HTTP_WORK32_VAR)
	LD	DE,(HTTP_WORK32_VAR+2)
	LD	(TEMP32),HL
	LD	(TEMP32+2),DE
	CALL	SHIFT_WORK32
	CALL	SHIFT_WORK32
	LD	HL,(HTTP_WORK32_VAR)
	LD	DE,(TEMP32)
	ADD	HL,DE
	LD	(HTTP_WORK32_VAR),HL
	LD	HL,(HTTP_WORK32_VAR+2)
	LD	DE,(TEMP32+2)
	ADC	HL,DE
	LD	(HTTP_WORK32_VAR+2),HL
	RET

SHIFT_WORK32
	LD	HL,HTTP_WORK32_VAR
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	RET

PARSE_STATUS_LINE
	LD	HL,HTTP_HEADER_LINE_VAR
	LD	DE,LIT_HTTP_PREFIX
	CALL	MATCH_PREFIX
	JR	NZ,.BAD
	LD	A,(HL)
	SUB	'0'
	JR	C,.BAD
	CP	10
	JR	NC,.BAD
	INC	HL
	LD	A,(HL)
	CP	'.'
	JR	NZ,.BAD
	INC	HL
	LD	A,(HL)
	SUB	'0'
	JR	C,.BAD
	CP	10
	JR	NC,.BAD
	INC	HL
	LD	A,(HL)
	CP	' '
	JR	NZ,.BAD
	INC	HL
	LD	A,(HL)
	CP	'2'
	JR	NZ,.BAD
	INC	HL
	LD	A,(HL)
	SUB	'0'
	JR	C,.BAD
	CP	10
	JR	NC,.BAD
	LD	C,A
	INC	HL
	LD	A,(HL)
	SUB	'0'
	JR	C,.BAD
	CP	10
	JR	NC,.BAD
	LD	B,A
	INC	HL
	LD	A,(HL)
	OR	A
	JR	Z,.STORE
	CP	' '
	JR	NZ,.BAD
.STORE
	LD	A,C
	ADD	A,A
	LD	E,A
	ADD	A,A
	ADD	A,A
	ADD	A,E
	ADD	A,B
	LD	E,A
	LD	D,0
	LD	HL,200
	ADD	HL,DE
	LD	(HTTP_STATUS_VAR),HL
	RET
.BAD
	LD	A,HTTP_ERR_STATUS
	JP	SET_ERROR

MATCH_PREFIX
	LD	A,(DE)
	OR	A
	RET	Z
	LD	C,A
	LD	A,(HL)
	CALL	TOLOWER
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	JR	MATCH_PREFIX

SKIP_OWS
	LD	A,(HL)
	CP	' '
	JR	Z,.ONE
	CP	9
	RET	NZ
.ONE
	INC	HL
	JR	SKIP_OWS

TOLOWER
	CP	'A'
	RET	C
	CP	'Z'+1
	RET	NC
	ADD	A,'a'-'A'
	RET

SET_ERROR
	PUSH	AF
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	JR	NZ,.KEEP
	POP	AF
	LD	(HTTP_ERROR_VAR),A
	RET
.KEEP
	POP	AF
	RET

LIT_CONTENT_LENGTH	DB "content-length:",0
LIT_TRANSFER_ENCODING	DB "transfer-encoding:",0
LIT_CONTENT_ENCODING	DB "content-encoding:",0
LIT_IDENTITY		DB "identity",0
LIT_HTTP_PREFIX		DB "http/",0
TEMP32			DS 4

	ENDMODULE
	ENDIF
