; Backend-neutral ICMP Echo and Destination Unreachable codec.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_ICMP_ASM
	DEFINE	_ICMP_ASM

	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"

	MODULE ICMP

ICMP_HEADER_LENGTH	EQU 8
ICMP_ECHO_REPLY		EQU 0
ICMP_DEST_UNREACHABLE	EQU 3
ICMP_ECHO_REQUEST	EQU 8
ICMP_MAX_PAYLOAD	EQU 1472

; BUILD_ECHO
; In: HL -> ICMPB descriptor. Writes request/reply header and deterministic
; byte-index payload. Out: BC=8+payload length. Preserves IX/IY.
BUILD_ECHO
	PUSH	IX,IY
	LD	BC,ICMPB_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IY
	LD	L,(IY+ICMPB_PAYLOAD_LENGTH)
	LD	H,(IY+ICMPB_PAYLOAD_LENGTH+1)
	LD	DE,ICMP_MAX_PAYLOAD+1
	OR	A
	SBC	HL,DE
	JP	NC,.BAD
	LD	L,(IY+ICMPB_PAYLOAD_LENGTH)
	LD	H,(IY+ICMPB_PAYLOAD_LENGTH+1)
	LD	DE,ICMP_HEADER_LENGTH
	ADD	HL,DE
	JP	C,.BAD
	LD	(ICMP_TOTAL),HL
	LD	E,(IY+ICMPB_CAPACITY)
	LD	D,(IY+ICMPB_CAPACITY+1)
	OR	A
	SBC	HL,DE
	JR	C,.CAPACITY_OK
	JR	Z,.CAPACITY_OK
	JR	.BAD
.CAPACITY_OK
	LD	L,(IY+ICMPB_BUFFER)
	LD	H,(IY+ICMPB_BUFFER+1)
	LD	BC,(ICMP_TOTAL)
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.BAD
	LD	E,(IY+ICMPB_BUFFER)
	LD	D,(IY+ICMPB_BUFFER+1)
	LD	A,(IY+ICMPB_TYPE)
	CP	ICMP_ECHO_REQUEST
	JR	Z,.TYPE_OK
	CP	ICMP_ECHO_REPLY
	JR	NZ,.BAD
.TYPE_OK
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A			; code
	INC	DE
	LD	(DE),A			; checksum
	INC	DE
	LD	(DE),A
	INC	DE
	LD	H,(IY+ICMPB_IDENTIFIER+1)
	LD	L,(IY+ICMPB_IDENTIFIER)
	CALL	@ETHERNET.WRITE_BE16
	LD	H,(IY+ICMPB_SEQUENCE+1)
	LD	L,(IY+ICMPB_SEQUENCE)
	CALL	@ETHERNET.WRITE_BE16
	LD	C,(IY+ICMPB_PAYLOAD_LENGTH)
	LD	B,(IY+ICMPB_PAYLOAD_LENGTH+1)
	LD	H,0
.PATTERN
	LD	A,B
	OR	C
	JR	Z,.CHECKSUM
	LD	A,H
	LD	(DE),A
	INC	DE
	INC	H
	DEC	BC
	JR	.PATTERN
.CHECKSUM
	LD	L,(IY+ICMPB_BUFFER)
	LD	H,(IY+ICMPB_BUFFER+1)
	LD	BC,(ICMP_TOTAL)
	CALL	@ETHERNET.CHECKSUM
	LD	E,(IY+ICMPB_BUFFER)
	LD	D,(IY+ICMPB_BUFFER+1)
	INC	DE
	INC	DE
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	LD	BC,(ICMP_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE_ECHO_REPLY
; In: HL=ICMP bytes, BC=exact IPv4 payload length, DE -> ICMPR descriptor.
; Requires type/code/checksum, id, sequence, exact length and byte-index data.
PARSE_ECHO_REPLY
	PUSH	IX,IY
	LD	(ICMP_INPUT),HL
	LD	(ICMP_TOTAL),BC
	PUSH	DE
	POP	IY
	EX	DE,HL
	LD	BC,ICMPR_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.REPLY_BAD
	LD	HL,(ICMP_INPUT)
	LD	BC,(ICMP_TOTAL)
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.REPLY_BAD
	LD	HL,(ICMP_TOTAL)
	LD	E,(IY+ICMPR_PAYLOAD_LENGTH)
	LD	D,(IY+ICMPR_PAYLOAD_LENGTH+1)
	LD	BC,ICMP_HEADER_LENGTH
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	OR	A
	SBC	HL,DE
	JR	NZ,.REPLY_BAD
	LD	HL,(ICMP_INPUT)
	LD	A,(HL)
	CP	ICMP_ECHO_REPLY
	JR	NZ,.REPLY_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,.REPLY_BAD
	LD	HL,(ICMP_INPUT)
	LD	BC,(ICMP_TOTAL)
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JR	C,.REPLY_BAD
	LD	HL,(ICMP_INPUT)
	LD	BC,4
	ADD	HL,BC
	LD	A,(IY+ICMPR_IDENTIFIER+1)
	CP	(HL)
	JR	NZ,.REPLY_BAD
	INC	HL
	LD	A,(IY+ICMPR_IDENTIFIER)
	CP	(HL)
	JR	NZ,.REPLY_BAD
	INC	HL
	LD	A,(IY+ICMPR_SEQUENCE+1)
	CP	(HL)
	JR	NZ,.REPLY_BAD
	INC	HL
	LD	A,(IY+ICMPR_SEQUENCE)
	CP	(HL)
	JR	NZ,.REPLY_BAD
	INC	HL
	LD	C,(IY+ICMPR_PAYLOAD_LENGTH)
	LD	B,(IY+ICMPR_PAYLOAD_LENGTH+1)
	LD	D,0
.VERIFY_PATTERN
	LD	A,B
	OR	C
	JR	Z,.REPLY_OK
	LD	A,D
	CP	(HL)
	JR	NZ,.REPLY_BAD
	INC	D
	INC	HL
	DEC	BC
	JR	.VERIFY_PATTERN
.REPLY_OK
	XOR	A
	POP	IY,IX
	RET
.REPLY_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE_ECHO_REQUEST validates an arbitrary Echo Request. Its payload is not
; assumed to use our diagnostic pattern.
PARSE_ECHO_REQUEST
	PUSH	IX,IY
	LD	(ICMP_INPUT),HL
	LD	(ICMP_TOTAL),BC
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.REQUEST_BAD
	LD	HL,(ICMP_TOTAL)
	LD	DE,ICMP_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	JR	C,.REQUEST_BAD
	LD	HL,(ICMP_INPUT)
	LD	A,(HL)
	CP	ICMP_ECHO_REQUEST
	JR	NZ,.REQUEST_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,.REQUEST_BAD
	LD	HL,(ICMP_INPUT)
	LD	BC,(ICMP_TOTAL)
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JR	C,.REQUEST_BAD
	XOR	A
	POP	IY,IX
	RET
.REQUEST_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; BUILD_ECHO_REPLY
; In: HL -> ICMPC descriptor. The source request is verified, copied to the
; caller's destination and converted to an Echo Reply with a fresh checksum.
BUILD_ECHO_REPLY
	PUSH	IX,IY
	LD	BC,ICMPC_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.COPY_BAD
	PUSH	HL
	POP	IY
	LD	L,(IY+ICMPC_SOURCE)
	LD	H,(IY+ICMPC_SOURCE+1)
	LD	C,(IY+ICMPC_LENGTH)
	LD	B,(IY+ICMPC_LENGTH+1)
	CALL	PARSE_ECHO_REQUEST
	JR	C,.COPY_BAD
	LD	L,(IY+ICMPC_CAPACITY)
	LD	H,(IY+ICMPC_CAPACITY+1)
	LD	E,(IY+ICMPC_LENGTH)
	LD	D,(IY+ICMPC_LENGTH+1)
	OR	A
	SBC	HL,DE
	JR	C,.COPY_BAD
	LD	L,(IY+ICMPC_DESTINATION)
	LD	H,(IY+ICMPC_DESTINATION+1)
	LD	C,(IY+ICMPC_LENGTH)
	LD	B,(IY+ICMPC_LENGTH+1)
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.COPY_BAD
	LD	L,(IY+ICMPC_SOURCE)
	LD	H,(IY+ICMPC_SOURCE+1)
	LD	E,(IY+ICMPC_DESTINATION)
	LD	D,(IY+ICMPC_DESTINATION+1)
	LD	C,(IY+ICMPC_LENGTH)
	LD	B,(IY+ICMPC_LENGTH+1)
	LDIR
	LD	L,(IY+ICMPC_DESTINATION)
	LD	H,(IY+ICMPC_DESTINATION+1)
	LD	(HL),ICMP_ECHO_REPLY
	INC	HL
	INC	HL
	LD	(HL),0
	INC	HL
	LD	(HL),0
	LD	L,(IY+ICMPC_DESTINATION)
	LD	H,(IY+ICMPC_DESTINATION+1)
	LD	C,(IY+ICMPC_LENGTH)
	LD	B,(IY+ICMPC_LENGTH+1)
	CALL	@ETHERNET.CHECKSUM
	LD	E,(IY+ICMPC_DESTINATION)
	LD	D,(IY+ICMPC_DESTINATION+1)
	INC	DE
	INC	DE
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	LD	C,(IY+ICMPC_LENGTH)
	LD	B,(IY+ICMPC_LENGTH+1)
	XOR	A
	POP	IY,IX
	RET
.COPY_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE_UNREACHABLE
; In: HL=outer ICMP, BC=exact length, DE -> ICMPR descriptor. Validates the
; complete outer checksum and the quoted IPv4 header + Echo id/sequence.
PARSE_UNREACHABLE
	PUSH	IX,IY
	LD	(ICMP_INPUT),HL
	LD	(ICMP_TOTAL),BC
	PUSH	DE
	POP	IY
	EX	DE,HL
	LD	BC,ICMPR_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.UNREACH_BAD
	LD	L,(IY+ICMPR_EXPECT_SOURCE)
	LD	H,(IY+ICMPR_EXPECT_SOURCE+1)
	LD	A,H
	OR	L
	JP	Z,.UNREACH_BAD
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.UNREACH_BAD
	LD	L,(IY+ICMPR_EXPECT_DESTINATION)
	LD	H,(IY+ICMPR_EXPECT_DESTINATION+1)
	LD	A,H
	OR	L
	JP	Z,.UNREACH_BAD
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.UNREACH_BAD
	LD	HL,(ICMP_INPUT)
	LD	BC,(ICMP_TOTAL)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.UNREACH_BAD
	LD	HL,(ICMP_TOTAL)
	LD	DE,ICMP_HEADER_LENGTH+IPV4_HEADER_LENGTH+ICMP_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	JP	C,.UNREACH_BAD
	LD	HL,(ICMP_INPUT)
	LD	A,(HL)
	CP	ICMP_DEST_UNREACHABLE
	JP	NZ,.UNREACH_BAD
	INC	HL
	LD	A,(HL)
	CP	16
	JP	NC,.UNREACH_BAD
	LD	HL,(ICMP_INPUT)
	LD	BC,(ICMP_TOTAL)
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,.UNREACH_BAD
	LD	HL,(ICMP_INPUT)
	LD	DE,ICMP_HEADER_LENGTH
	ADD	HL,DE
	LD	(ICMP_QUOTED_IP),HL
	LD	A,(HL)
	CP	0x45
	JP	NZ,.UNREACH_BAD
	PUSH	HL
	INC	HL
	INC	HL
	CALL	@ETHERNET.READ_BE16
	LD	HL,DE
	LD	BC,IPV4_MAX_PACKET_LENGTH+1
	OR	A
	SBC	HL,BC
	JP	NC,.UNREACH_LENGTH_POP_BAD
	LD	A,D
	OR	A
	JR	NZ,.QUOTED_LENGTH_OK
	LD	A,E
	CP	IPV4_HEADER_LENGTH+ICMP_HEADER_LENGTH
	JP	C,.UNREACH_LENGTH_POP_BAD
.QUOTED_LENGTH_OK
	POP	HL
	PUSH	HL
	LD	DE,6
	ADD	HL,DE
	LD	A,(HL)
	AND	0xBF			; only a quoted DF flag is accepted
	JP	NZ,.UNREACH_POP_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,.UNREACH_POP_BAD
	INC	HL
	INC	HL
	LD	A,(HL)
	CP	IPV4_PROTOCOL_ICMP
	JP	NZ,.UNREACH_POP_BAD
	POP	HL
	PUSH	HL
	LD	BC,IPV4_HEADER_LENGTH
	CALL	@ETHERNET.VERIFY_CHECKSUM
	POP	HL
	JP	C,.UNREACH_BAD
	LD	DE,12
	ADD	HL,DE
	LD	E,(IY+ICMPR_EXPECT_SOURCE)
	LD	D,(IY+ICMPR_EXPECT_SOURCE+1)
	CALL	CMP4
	JP	NZ,.UNREACH_BAD
	LD	HL,(ICMP_QUOTED_IP)
	LD	DE,16
	ADD	HL,DE
	LD	E,(IY+ICMPR_EXPECT_DESTINATION)
	LD	D,(IY+ICMPR_EXPECT_DESTINATION+1)
	CALL	CMP4
	JP	NZ,.UNREACH_BAD
	LD	HL,(ICMP_QUOTED_IP)
	LD	DE,IPV4_HEADER_LENGTH
	ADD	HL,DE
	LD	A,(HL)
	CP	ICMP_ECHO_REQUEST
	JR	NZ,.UNREACH_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,.UNREACH_BAD
	INC	HL
	INC	HL
	INC	HL
	LD	A,(IY+ICMPR_IDENTIFIER+1)
	CP	(HL)
	JR	NZ,.UNREACH_BAD
	INC	HL
	LD	A,(IY+ICMPR_IDENTIFIER)
	CP	(HL)
	JR	NZ,.UNREACH_BAD
	INC	HL
	LD	A,(IY+ICMPR_SEQUENCE+1)
	CP	(HL)
	JR	NZ,.UNREACH_BAD
	INC	HL
	LD	A,(IY+ICMPR_SEQUENCE)
	CP	(HL)
	JR	NZ,.UNREACH_BAD
	XOR	A
	POP	IY,IX
	RET
.UNREACH_POP_BAD
	POP	HL
.UNREACH_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET
.UNREACH_LENGTH_POP_BAD
	POP	HL
	JR	.UNREACH_BAD

CMP4
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP
	RET

ICMP_INPUT	DW 0
ICMP_TOTAL	DW 0
ICMP_QUOTED_IP	DW 0

	ENDMODULE
	ENDIF
