; Strict backend-neutral IPv4 v4/IHL=5 codec.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_IPV4_ASM
	DEFINE	_IPV4_ASM

	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"

	MODULE IPV4

IPV4_MAX_PACKET	EQU IPV4_MAX_PACKET_LENGTH

; BUILD
; In: HL -> IP4B descriptor. Payload is already stored immediately after the
; 20-byte header. Out: BC=complete IPv4 length, A=0/CF=0. Invalid descriptor,
; pointer, capacity or size returns NETDRV_ERR_PARAMETER/CF=1.
; Clobbers AF/BC/DE/HL; preserves IX/IY.
BUILD
	PUSH	IX,IY
	LD	BC,IP4B_LENGTH
	CALL	VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+IP4B_DATA_LENGTH)
	LD	H,(IX+IP4B_DATA_LENGTH+1)
	LD	DE,IPV4_HEADER_LENGTH
	ADD	HL,DE
	JP	C,.BAD
	LD	(IPV4_TOTAL),HL
	LD	DE,IPV4_MAX_PACKET+1
	OR	A
	SBC	HL,DE
	JP	NC,.BAD
	LD	L,(IX+IP4B_CAPACITY)
	LD	H,(IX+IP4B_CAPACITY+1)
	LD	DE,(IPV4_TOTAL)
	OR	A
	SBC	HL,DE
	JP	C,.BAD
	LD	L,(IX+IP4B_BUFFER)
	LD	H,(IX+IP4B_BUFFER+1)
	LD	BC,(IPV4_TOTAL)
	CALL	VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+IP4B_SOURCE)
	LD	H,(IX+IP4B_SOURCE+1)
	LD	BC,4
	CALL	VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+IP4B_DESTINATION)
	LD	H,(IX+IP4B_DESTINATION+1)
	LD	BC,4
	CALL	VALIDATE_REGION
	JP	C,.BAD

	LD	E,(IX+IP4B_BUFFER)
	LD	D,(IX+IP4B_BUFFER+1)
	LD	A,0x45
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A			; DSCP/ECN
	INC	DE
	LD	HL,(IPV4_TOTAL)
	CALL	@ETHERNET.WRITE_BE16
	LD	H,(IX+IP4B_IDENTIFIER+1)
	LD	L,(IX+IP4B_IDENTIFIER)
	CALL	@ETHERNET.WRITE_BE16
	LD	HL,0x4000		; DF set; fragments are never produced
	CALL	@ETHERNET.WRITE_BE16
	LD	A,(IX+IP4B_TTL)
	OR	A
	JR	Z,.BAD
	LD	(DE),A
	INC	DE
	LD	A,(IX+IP4B_PROTOCOL)
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	L,(IX+IP4B_SOURCE)
	LD	H,(IX+IP4B_SOURCE+1)
	LD	BC,4
	LDIR
	LD	L,(IX+IP4B_DESTINATION)
	LD	H,(IX+IP4B_DESTINATION+1)
	LD	BC,4
	LDIR
	LD	L,(IX+IP4B_BUFFER)
	LD	H,(IX+IP4B_BUFFER+1)
	LD	BC,IPV4_HEADER_LENGTH
	CALL	@ETHERNET.CHECKSUM
	LD	E,(IX+IP4B_BUFFER)
	LD	D,(IX+IP4B_BUFFER+1)
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	LD	BC,(IPV4_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE
; In: HL -> IP4P descriptor. Ethernet padding after total-length is allowed.
; Only v4/IHL=5, an intact checksum and an unfragmented datagram are accepted.
; Expected source may be zero; destination and protocol are mandatory.
; Successful parsing fills DATA, DATA_LENGTH, IDENTIFIER, SOURCE and TTL.
; Clobbers AF/BC/DE/HL; preserves IX/IY.
PARSE
	PUSH	IX,IY
	LD	BC,IP4P_DESC_LENGTH
	CALL	VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+IP4P_EXPECT_DESTINATION)
	LD	H,(IX+IP4P_EXPECT_DESTINATION+1)
	LD	BC,4
	CALL	VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+IP4P_EXPECT_SOURCE)
	LD	H,(IX+IP4P_EXPECT_SOURCE+1)
	LD	A,H
	OR	L
	JR	Z,.EXPECTED_VALID
	LD	BC,4
	CALL	VALIDATE_REGION
	JP	C,.BAD
.EXPECTED_VALID
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	C,(IX+IP4P_LENGTH)
	LD	B,(IX+IP4P_LENGTH+1)
	CALL	VALIDATE_REGION
	JP	C,.BAD
	LD	HL,IPV4_HEADER_LENGTH
	LD	E,(IX+IP4P_LENGTH)
	LD	D,(IX+IP4P_LENGTH+1)
	OR	A
	SBC	HL,DE
	JR	NC,.MIN_CHECK
	JR	.LENGTH_OK
.MIN_CHECK
	JP	NZ,.BAD
.LENGTH_OK
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	A,(HL)
	CP	0x45
	JP	NZ,.BAD
	PUSH	HL
	INC	HL
	INC	HL
	CALL	@ETHERNET.READ_BE16
	LD	(IPV4_TOTAL),DE
	POP	HL
	LD	A,D
	OR	A
	JR	NZ,.TOTAL_AT_LEAST
	LD	A,E
	CP	IPV4_HEADER_LENGTH
	JP	C,.BAD
.TOTAL_AT_LEAST
	LD	HL,(IPV4_TOTAL)
	LD	DE,IPV4_MAX_PACKET+1
	OR	A
	SBC	HL,DE
	JP	NC,.BAD
	LD	C,(IX+IP4P_LENGTH)
	LD	B,(IX+IP4P_LENGTH+1)
	LD	DE,(IPV4_TOTAL)
	EX	DE,HL
	OR	A
	SBC	HL,BC
	JR	C,.TOTAL_FITS
	JR	Z,.TOTAL_FITS
	JP	.BAD
.TOTAL_FITS
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	DE,6
	ADD	HL,DE
	LD	A,(HL)
	AND	0xBF			; only DF may be set; reject reserved/MF/offset
	JP	NZ,.BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,.BAD
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	BC,IPV4_HEADER_LENGTH
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,.BAD
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	DE,9
	ADD	HL,DE
	LD	A,(IX+IP4P_EXPECT_PROTOCOL)
	CP	(HL)
	JP	NZ,.BAD
	INC	HL			; checksum then source
	INC	HL
	INC	HL
	LD	E,(IX+IP4P_EXPECT_SOURCE)
	LD	D,(IX+IP4P_EXPECT_SOURCE+1)
	LD	A,D
	OR	E
	JR	Z,.SOURCE_OK
	PUSH	HL
	CALL	CMP4
	POP	HL
	JP	NZ,.BAD
.SOURCE_OK
	LD	E,(IX+IP4P_EXPECT_DESTINATION)
	LD	D,(IX+IP4P_EXPECT_DESTINATION+1)
	LD	A,D
	OR	E
	JP	Z,.BAD
	PUSH	HL
	LD	BC,4
	ADD	HL,BC
	CALL	CMP4
	POP	HL
	JP	NZ,.BAD
	LD	(IX+IP4P_SOURCE),L
	LD	(IX+IP4P_SOURCE+1),H
	LD	E,(IX+IP4P_BUFFER)
	LD	D,(IX+IP4P_BUFFER+1)
	LD	HL,IPV4_HEADER_LENGTH
	ADD	HL,DE
	LD	(IX+IP4P_DATA),L
	LD	(IX+IP4P_DATA+1),H
	LD	HL,(IPV4_TOTAL)
	LD	DE,IPV4_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	LD	(IX+IP4P_DATA_LENGTH),L
	LD	(IX+IP4P_DATA_LENGTH+1),H
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	DE,4
	ADD	HL,DE
	LD	A,(HL)
	LD	(IX+IP4P_IDENTIFIER+1),A
	INC	HL
	LD	A,(HL)
	LD	(IX+IP4P_IDENTIFIER),A
	LD	L,(IX+IP4P_BUFFER)
	LD	H,(IX+IP4P_BUFFER+1)
	LD	DE,8
	ADD	HL,DE
	LD	A,(HL)
	LD	(IX+IP4P_TTL),A
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; In: HL=start, BC=nonzero length. End is exclusive and must be <= C000h.
VALIDATE_REGION
	PUSH	HL,BC
	LD	A,B
	OR	C
	JR	Z,.REGION_BAD
	ADD	HL,BC
	JR	C,.REGION_BAD
	LD	DE,0xC001
	OR	A
	SBC	HL,DE
	JR	NC,.REGION_BAD
	XOR	A
	POP	BC,HL
	RET
.REGION_BAD
	SCF
	POP	BC,HL
	RET

CMP4
	LD	B,4
.CMP_LOOP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP_LOOP
	RET

IPV4_TOTAL	DW 0

	ENDMODULE
	ENDIF
