; Interactive NET.CFG editor used only by NETCFG -W.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_NETCFG_WRITE_ASM
	DEFINE	_NETCFG_WRITE_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "netdrv.inc"

	MODULE NETCFGWRITE

FIELD_OPTIONAL	EQU 0x01
VALIDATE_NONE	EQU 0
VALIDATE_IDPORT	EQU 1
VALIDATE_HW	EQU 2
VALIDATE_MAC	EQU 3
VALIDATE_IP	EQU 4
VALIDATE_IPV4	EQU 5
VALIDATE_TZ	EQU 6

WRITE_NEW_FILE	EQU NETCFG_WRITE_NEW_FILE
WRITE_STATUS	EQU NETCFG_WRITE_STATUS
WRITE_PROMPT	EQU NETCFG_WRITE_PROMPT
WRITE_DEST	EQU NETCFG_WRITE_DEST
WRITE_CURSOR	EQU NETCFG_WRITE_CURSOR
WRITE_LENGTH	EQU NETCFG_WRITE_LENGTH
WRITE_CAPACITY	EQU NETCFG_WRITE_CAP_FIELD
WRITE_VALIDATOR	EQU NETCFG_WRITE_VALIDATOR
WRITE_FIELD_FLAGS EQU NETCFG_WRITE_FIELD_FLAGS
WRITE_INPUT_LENGTH EQU NETCFG_WRITE_INPUT_LENGTH
WRITE_CHAR	EQU NETCFG_WRITE_CHAR

; Maximum canonical size from the declared field capacities, including every
; key, '=' and CRLF. This makes the serializer's fixed page buffer auditable.
NETCFG_CANONICAL_MAX EQU 10 + 16 + 16 + 25 + 20 + 25 + 25 + 22 + 22 + 37 + 12
	ASSERT NETCFG_CANONICAL_MAX <= NETCFG_WRITE_CAPACITY

; RUN
; In: private Stage 7 page is mapped and S7APP state is clear.
; Out: A=0/CF=0 after saving; stable NETDRV error/CF=1 on cancel,
;      invalid/unreadable existing configuration, or file I/O failure.
; Clobbers AF/BC/DE/HL/IX/IY.
RUN
	CALL	@NETPARSE.LOAD
	JR	NC,.EXISTING
	CALL	@NETPARSE.LAST_ERROR
	CP	DSS_ERR_FILE_NOT_FOUND
	JP	NZ,.CONFIG_BAD
	CALL	NEW_DEFAULTS
	LD	A,1
	LD	(WRITE_NEW_FILE),A
	JR	.EDIT
.EXISTING
	XOR	A
	LD	(WRITE_NEW_FILE),A
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_WRITE
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.EDIT
	LD	HL,VALUE_DHCP_WRITE
	LD	DE,NCV_IP
	CALL	@NETPARSE.COPY_Z
.EDIT
	LD	HL,PROMPT_IDPORT
	LD	DE,NCV_IDPORT
	LD	B,NCV_IDPORT_CAP
	LD	C,VALIDATE_IDPORT
	XOR	A
	CALL	PROMPT_FIELD
	RET	C
	LD	A,(WRITE_NEW_FILE)
	OR	A
	CALL	NZ,ASK_AND_PROBE
	RET	C
	LD	HL,PROMPT_HW
	LD	DE,NCV_HW
	LD	B,NCV_HW_CAP
	LD	C,VALIDATE_HW
	XOR	A
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,PROMPT_MAC
	LD	DE,NCV_MAC
	LD	B,NCV_MAC_CAP
	LD	C,VALIDATE_MAC
	LD	A,FIELD_OPTIONAL
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,PROMPT_IP
	LD	DE,NCV_IP
	LD	B,NCV_IP_CAP
	LD	C,VALIDATE_IP
	XOR	A
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,NCV_IP
	LD	DE,VALUE_DHCP_WRITE
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.STATIC
	CALL	CLEAR_STATIC_FIELDS
	JR	.AFTER_ADDRESS
.STATIC
	LD	HL,PROMPT_MASK
	LD	DE,NCV_MASK
	LD	B,NCV_MASK_CAP
	LD	C,VALIDATE_IPV4
	XOR	A
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,PROMPT_GATEWAY
	LD	DE,NCV_GW
	LD	B,NCV_GW_CAP
	LD	C,VALIDATE_IPV4
	LD	A,FIELD_OPTIONAL
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,PROMPT_DNS1
	LD	DE,NCV_DNS1
	LD	B,NCV_DNS_CAP
	LD	C,VALIDATE_IPV4
	LD	A,FIELD_OPTIONAL
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,PROMPT_DNS2
	LD	DE,NCV_DNS2
	LD	B,NCV_DNS_CAP
	LD	C,VALIDATE_IPV4
	LD	A,FIELD_OPTIONAL
	CALL	PROMPT_FIELD
	RET	C
.AFTER_ADDRESS
	LD	HL,PROMPT_NTP
	LD	DE,NCV_NTP
	LD	B,NCV_NTP_CAP
	LD	C,VALIDATE_NONE
	LD	A,FIELD_OPTIONAL
	CALL	PROMPT_FIELD
	RET	C
	LD	HL,PROMPT_TZ
	LD	DE,NCV_TZ
	LD	B,NCV_TZ_CAP
	LD	C,VALIDATE_TZ
	LD	A,FIELD_OPTIONAL
	CALL	PROMPT_FIELD
	RET	C
	CALL	BUILD_AND_VALIDATE
	JR	C,.CONFIG_BAD
	CALL	SAVE
	RET	C
	LD	HL,MSG_SAVED
	CALL	@CONSOLE.LINE
	XOR	A
	RET
.CONFIG_BAD
	LD	A,NETDRV_ERR_CONFIG
	SCF
	RET

; Missing-file defaults are kept byte-for-byte in sync with NETSMPL.CFG's
; effective values (comments in the shipped template are intentionally absent).
NEW_DEFAULTS
	CALL	@NETPARSE.DEFAULTS
	LD	HL,VALUE_DHCP_WRITE
	LD	DE,NCV_IP
	CALL	@NETPARSE.COPY_Z
	LD	HL,VALUE_DHCP_WRITE
	LD	DE,NCV_IP_SRC
	CALL	@NETPARSE.COPY_Z
	LD	HL,DEFAULT_NTP
	LD	DE,NCV_NTP
	CALL	@NETPARSE.COPY_Z
	LD	HL,DEFAULT_TZ
	LD	DE,NCV_TZ
	JP	@NETPARSE.COPY_Z

CLEAR_STATIC_FIELDS
	XOR	A
	LD	(NCV_MASK),A
	LD	(NCV_GW),A
	LD	(NCV_DNS1),A
	LD	(NCV_DNS2),A
	RET

; Confirmation precedes every access to the adapter. A declined or failed
; bounded probe is diagnostic only: HW remains AUTO and editing continues.
ASK_AND_PROBE
.ASK
	LD	HL,MSG_PROBE_PRE
	CALL	@CONSOLE.STRING
	LD	HL,NCV_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,MSG_PROBE_POST
	CALL	@CONSOLE.STRING
	CALL	READ_KEY
	CP	0x1B
	JP	Z,.CANCEL
	PUSH	AF
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	POP	AF
	CP	13
	JR	Z,.PROBE
	CALL	@NETPARSE.UPPER_A
	CP	'Y'
	JR	Z,.PROBE
	CP	'N'
	JR	NZ,.ASK
	LD	HL,MSG_PROBE_SKIPPED
	CALL	@CONSOLE.LINE
	XOR	A
	RET
.PROBE
	CALL	@S7APP.INIT_DRIVER
	JR	C,.PROBE_FAILED
	CALL	@S7APP.RECORD_HW
	CALL	@NETDRV.DONE
	JR	C,.PROBE_FAILED_DONE
	LD	HL,MSG_PROBE_FOUND
	CALL	@CONSOLE.STRING
	LD	HL,NCV_HW
	CALL	@CONSOLE.LINE
	XOR	A
	RET
.PROBE_FAILED
	LD	(WRITE_STATUS),A
	CALL	@NETDRV.DONE
	LD	A,(WRITE_STATUS)
.PROBE_FAILED_DONE
	LD	(WRITE_STATUS),A
	LD	HL,MSG_PROBE_FAILED
	CALL	@CONSOLE.STRING
	LD	A,(WRITE_STATUS)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	XOR	A
	RET
.CANCEL
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

; PROMPT_FIELD
; In: HL=label, DE=current ASCIIZ, B=capacity including NUL, C=validator,
;     A flags (FIELD_OPTIONAL permits a single '-' to clear the value).
; Out: A=0/CF=0 after a valid edit or Enter; cancelled status/CF=1 on Esc.
; Overflow and invalid input are rejected in full and re-prompted.
PROMPT_FIELD
	LD	(WRITE_FIELD_FLAGS),A
	LD	(WRITE_PROMPT),HL
	LD	(WRITE_DEST),DE
	LD	A,B
	LD	(WRITE_CAPACITY),A
	LD	A,C
	LD	(WRITE_VALIDATOR),A
.RETRY
	LD	HL,(WRITE_PROMPT)
	CALL	@CONSOLE.STRING
	LD	HL,MSG_VALUE_OPEN
	CALL	@CONSOLE.STRING
	LD	HL,(WRITE_DEST)
	CALL	@CONSOLE.STRING
	LD	HL,MSG_VALUE_CLOSE
	CALL	@CONSOLE.STRING
	XOR	A
	LD	(WRITE_INPUT_LENGTH),A
.READ
	CALL	READ_KEY
	CP	0x1B
	JP	Z,.CANCEL
	CP	13
	JR	Z,.ENTER
	CP	10
	JR	Z,.ENTER
	CP	8
	JR	Z,.BACKSPACE
	CP	32
	JR	C,.READ
	CP	127
	JR	NC,.READ
	LD	(WRITE_CHAR),A
	LD	A,(WRITE_INPUT_LENGTH)
	LD	B,A
	LD	A,(WRITE_CAPACITY)
	DEC	A
	CP	B
	JR	Z,.OVERFLOW
	LD	C,B
	LD	B,0
	LD	HL,NETCFG_EDIT_BUFFER
	ADD	HL,BC
	LD	A,(WRITE_CHAR)
	LD	(HL),A
	LD	A,(WRITE_INPUT_LENGTH)
	INC	A
	LD	(WRITE_INPUT_LENGTH),A
	JR	.READ
.BACKSPACE
	LD	A,(WRITE_INPUT_LENGTH)
	OR	A
	JR	Z,.READ
	DEC	A
	LD	(WRITE_INPUT_LENGTH),A
	LD	HL,MSG_ERASE
	CALL	@CONSOLE.STRING
	JR	.READ
.OVERFLOW
	CALL	DRAIN_LINE
	RET	C
	LD	HL,MSG_TOO_LONG
	CALL	@CONSOLE.LINE
	JP	.RETRY
.ENTER
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(WRITE_INPUT_LENGTH)
	OR	A
	JR	NZ,.TERMINATE
	LD	HL,(WRITE_DEST)
	LD	DE,NETCFG_EDIT_BUFFER
	CALL	@NETPARSE.COPY_Z
	JR	.VALIDATE
.TERMINATE
	LD	C,A
	LD	B,0
	LD	HL,NETCFG_EDIT_BUFFER
	ADD	HL,BC
	LD	(HL),0
	LD	A,(WRITE_FIELD_FLAGS)
	AND	FIELD_OPTIONAL
	JR	Z,.VALIDATE
	LD	A,(WRITE_INPUT_LENGTH)
	CP	1
	JR	NZ,.VALIDATE
	LD	A,(NETCFG_EDIT_BUFFER)
	CP	'-'
	JR	NZ,.VALIDATE
	LD	HL,(WRITE_DEST)
	XOR	A
	LD	(HL),A
	RET
.VALIDATE
	CALL	VALIDATE_VALUE
	JR	C,.INVALID
	LD	HL,NETCFG_EDIT_BUFFER
	LD	DE,(WRITE_DEST)
	CALL	@NETPARSE.COPY_Z
	XOR	A
	RET
.INVALID
	LD	HL,MSG_INVALID
	CALL	@CONSOLE.LINE
	JP	.RETRY
.CANCEL
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

DRAIN_LINE
.LOOP
	CALL	READ_KEY
	CP	0x1B
	JR	Z,.CANCEL
	CP	13
	JR	Z,.DONE
	CP	10
	JR	NZ,.LOOP
.DONE
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	XOR	A
	RET
.CANCEL
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

VALIDATE_VALUE
	LD	A,(WRITE_VALIDATOR)
	OR	A
	RET	Z
	CP	VALIDATE_TZ
	JP	Z,.TZ
	LD	HL,NETCFG_EDIT_BUFFER
	LD	A,(HL)
	OR	A
	JR	NZ,.NONEMPTY
	LD	A,(WRITE_FIELD_FLAGS)
	AND	FIELD_OPTIONAL
	JP	NZ,.OK
	JP	.BAD
.NONEMPTY
	LD	A,(WRITE_VALIDATOR)
	CP	VALIDATE_IDPORT
	JR	Z,.IDPORT
	CP	VALIDATE_HW
	JR	Z,.HW
	CP	VALIDATE_MAC
	JR	Z,.MAC
	CP	VALIDATE_IP
	JR	Z,.IP
	; VALIDATE_IPV4
	LD	DE,NETCFG_SCRATCH
	CALL	@NETPARSE.PARSE_IPV4
	RET
.IDPORT
	CALL	UPPER_EDIT
	LD	HL,NETCFG_EDIT_BUFFER
	CALL	@NETPARSE.PARSE_HASH_WORD
	JR	C,.BAD
	LD	A,H
	CP	1
	JR	NZ,.BAD
	LD	A,L
	AND	0x0F
	JR	NZ,.BAD
	LD	(NETDRV_CONFIG+NETDRV_CFG_IDPORT),HL
	JR	.OK
.HW
	CALL	UPPER_EDIT
	LD	HL,NETCFG_EDIT_BUFFER
	LD	DE,@NETPARSE.DEFAULT_HW
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.HW_EXPLICIT
	XOR	A
	LD	(NETDRV_CONFIG+NETDRV_CFG_MODE),A
	JR	.OK
.HW_EXPLICIT
	LD	HL,NETCFG_EDIT_BUFFER
	CALL	@NETPARSE.PARSE_HW
	RET
.MAC
	CALL	UPPER_EDIT
	LD	HL,NETCFG_EDIT_BUFFER
	LD	DE,NETDRV_CONFIG+NETDRV_CFG_MAC
	CALL	@NETPARSE.PARSE_MAC
	RET
.IP
	LD	HL,NETCFG_EDIT_BUFFER
	LD	DE,VALUE_DHCP_WRITE
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.IP_STATIC
	LD	HL,VALUE_DHCP_WRITE
	LD	DE,NETCFG_EDIT_BUFFER
	CALL	@NETPARSE.COPY_Z
	JR	.OK
.IP_STATIC
	LD	HL,NETCFG_EDIT_BUFFER
	LD	DE,NETCFG_SCRATCH
	CALL	@NETPARSE.PARSE_IPV4
	RET
.TZ
	LD	HL,NETCFG_EDIT_BUFFER
	CALL	@NETPARSE.PARSE_TZ
	RET
.OK
	XOR	A
	RET
.BAD
	LD	A,NETDRV_ERR_CONFIG
	SCF
	RET

UPPER_EDIT
	LD	HL,NETCFG_EDIT_BUFFER
.LOOP
	LD	A,(HL)
	OR	A
	RET	Z
	CALL	@NETPARSE.UPPER_A
	LD	(HL),A
	INC	HL
	JR	.LOOP

; Blocking character input. DSS ECHOKEY returns the echoed ASCII byte in A.
READ_KEY
	LD	C,DSS_ECHOKEY
	RST	DSS
	RET

; BUILD_AND_VALIDATE serializes the editor state, validates that exact text
; through the normal NETPARSE path, then rebuilds the canonical CRLF form
; because the parser tokenizes its input in place.
BUILD_AND_VALIDATE
	CALL	SERIALIZE
	LD	HL,NETCFG_WRITE_BUFFER
	LD	BC,(WRITE_LENGTH)
	CALL	@NETPARSE.PARSE
	RET	C
	CALL	SERIALIZE
	XOR	A
	RET

SERIALIZE
	LD	HL,NETCFG_WRITE_BUFFER
	LD	(WRITE_CURSOR),HL
	LD	HL,0
	LD	(WRITE_LENGTH),HL
	LD	HL,KEY_NET
	LD	DE,@NETPARSE.DEFAULT_NET
	CALL	APPEND_PAIR
	LD	HL,KEY_HW
	LD	DE,NCV_HW
	CALL	APPEND_PAIR
	LD	HL,KEY_IDPORT
	LD	DE,NCV_IDPORT
	CALL	APPEND_PAIR
	LD	HL,KEY_MAC
	LD	DE,NCV_MAC
	CALL	APPEND_PAIR
	LD	HL,KEY_IP
	LD	DE,NCV_IP
	LD	A,(DE)
	OR	A
	JR	NZ,.IP_READY
	LD	DE,VALUE_DHCP_WRITE
.IP_READY
	CALL	APPEND_PAIR
	LD	HL,KEY_MASK
	LD	DE,NCV_MASK
	CALL	APPEND_PAIR
	LD	HL,KEY_GATEWAY
	LD	DE,NCV_GW
	CALL	APPEND_PAIR
	LD	HL,KEY_DNS1
	LD	DE,NCV_DNS1
	CALL	APPEND_PAIR
	LD	HL,KEY_DNS2
	LD	DE,NCV_DNS2
	CALL	APPEND_PAIR
	LD	HL,KEY_NTP
	LD	DE,NCV_NTP
	CALL	APPEND_PAIR
	LD	HL,KEY_TZ
	LD	DE,NCV_TZ
	JP	APPEND_PAIR

APPEND_PAIR
	PUSH	DE
	CALL	APPEND_Z
	POP	HL
	CALL	APPEND_Z
	LD	HL,CRLF_TEXT
	JP	APPEND_Z

APPEND_Z
	LD	DE,(WRITE_CURSOR)
.LOOP
	LD	A,(HL)
	OR	A
	JR	Z,.DONE
	LD	(DE),A
	INC	HL
	INC	DE
	LD	BC,(WRITE_LENGTH)
	INC	BC
	LD	(WRITE_LENGTH),BC
	JR	.LOOP
.DONE
	LD	(WRITE_CURSOR),DE
	RET

SAVE
	LD	HL,NETCFG_PATH
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	JR	C,.BAD
	LD	(NETCFG_FILE_HANDLE),A
	LD	HL,NETCFG_WRITE_BUFFER
	LD	DE,(WRITE_LENGTH)
	LD	C,DSS_WRITE
	RST	DSS
	JR	C,.WRITE_BAD
	LD	A,(NETCFG_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	NC,.OK
	LD	A,(NETCFG_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS			; close uncertainty remains an I/O failure
	JR	.BAD
.OK
	XOR	A
	RET
.WRITE_BAD
	LD	A,(NETCFG_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	NC,.BAD
	LD	A,(NETCFG_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS			; do not leak a handle after a write error
.BAD
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

PROMPT_IDPORT	DB "IDPORT",0
PROMPT_HW	DB "HW",0
PROMPT_MAC	DB "MAC",0
PROMPT_IP	DB "IP",0
PROMPT_MASK	DB "NETMASK",0
PROMPT_GATEWAY	DB "GATEWAY",0
PROMPT_DNS1	DB "DNS1",0
PROMPT_DNS2	DB "DNS2",0
PROMPT_NTP	DB "NTP",0
PROMPT_TZ	DB "TZ",0
MSG_VALUE_OPEN	DB " [",0
MSG_VALUE_CLOSE	DB "]: ",0
MSG_ERASE	DB " ",8,0
MSG_INVALID	DB "[E1] INVALID VALUE",0
MSG_TOO_LONG	DB "[E2] INPUT TOO LONG",0
MSG_PROBE_PRE	DB "Probe hardware at IDPORT ",0
MSG_PROBE_POST	DB "? [Y/n] ",0
MSG_PROBE_SKIPPED DB "[W0] PROBE SKIPPED code=23",0
MSG_PROBE_FAILED DB "[W1] PROBE FAIL code=",0
MSG_PROBE_FOUND DB "[W2] PROBE FOUND HW=",0
MSG_SAVED	DB "[C3] NET.CFG SAVED",0
DEFAULT_NTP	DB "pool.ntp.org",0
DEFAULT_TZ	DB "+3",0
VALUE_DHCP_WRITE DB "DHCP",0
CRLF_TEXT	DB 13,10,0
KEY_NET		DB "NET=",0
KEY_HW		DB "HW=",0
KEY_IDPORT	DB "IDPORT=",0
KEY_MAC		DB "MAC=",0
KEY_IP		DB "IP=",0
KEY_MASK	DB "NETMASK=",0
KEY_GATEWAY	DB "GATEWAY=",0
KEY_DNS1	DB "DNS1=",0
KEY_DNS2	DB "DNS2=",0
KEY_NTP		DB "NTP=",0
KEY_TZ		DB "TZ=",0

	ENDMODULE
	ENDIF
