; NET.CFG reader and tokenizer, split out of netparse.asm.
; Only NETCFG reads the file; every other app needs the value helpers
; (DEFAULTS/VALIDATE/PARSE_* etc.) alone, and sjasmplus has no dead-code
; elimination, so a shared module is paid for in full by every image that
; includes it -- see specs.md for the measured per-image savings.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_NETPARSE_FILE_ASM
	DEFINE	_NETPARSE_FILE_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"

	MODULE NETPARSE

; LOAD reads only <APPINFO home>\NET.CFG into the mapped Stage 7 TX region.
; Exact-capacity input is rejected as oversized. The handle closes on all paths.
LOAD
	PUSH	IX,IY
	LD	HL,NETCFG_PATH
	LD	B,APPINFO_EXE_HOMEDIR
	LD	C,DSS_APPINFO
	RST	DSS
	JR	C,.FILE_ERROR
	LD	HL,NETCFG_PATH
	CALL	APPEND_FILENAME
	JR	C,.FILE_ERROR
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	JR	C,.FILE_ERROR
	LD	(NETCFG_FILE_HANDLE),A
	LD	HL,STAGE7_TX_BUFFER
	LD	DE,STAGE7_TX_CAPACITY
	LD	C,DSS_READ_FILE
	RST	DSS
	JR	C,.READ_ERROR
	LD	(NETCFG_FILE_LENGTH),DE
	LD	A,(NETCFG_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	C,.FILE_ERROR
	LD	HL,(NETCFG_FILE_LENGTH)
	LD	DE,STAGE7_TX_CAPACITY
	OR	A
	SBC	HL,DE
	JR	NC,.OVERSIZED
	LD	HL,STAGE7_TX_BUFFER
	LD	DE,(NETCFG_FILE_LENGTH)
	ADD	HL,DE
	LD	(HL),0
	LD	HL,STAGE7_TX_BUFFER
	LD	BC,(NETCFG_FILE_LENGTH)
	CALL	PARSE
	POP	IY,IX
	RET
.READ_ERROR
	LD	(NETPARSE_SAVED_ERROR),A
	LD	A,(NETCFG_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,(NETPARSE_SAVED_ERROR)
.FILE_ERROR
	LD	A,NETDRV_ERR_CONFIG
	SCF
	POP	IY,IX
	RET
.OVERSIZED
	LD	A,NETDRV_ERR_CONFIG
	SCF
	POP	IY,IX
	RET

APPEND_FILENAME
	LD	B,0			; bounded 256-byte APPINFO result scan
.SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.END
	INC	HL
	DJNZ	.SCAN
	SCF
	RET
.END
	LD	A,L
	CP	LOW NETCFG_PATH
	JR	NZ,.HAVE_DIR
	LD	A,H
	CP	HIGH NETCFG_PATH
	JR	Z,.BAD
.HAVE_DIR
	DEC	HL
	LD	A,(HL)
	INC	HL
	CP	'\'
	JR	Z,.COPY
	CP	'/'
	JR	Z,.COPY
	LD	(HL),'\'
	INC	HL
.COPY
	LD	DE,CFG_FILENAME
	LD	B,8
.COPY_LOOP
	LD	A,(DE)
	LD	(HL),A
	INC	DE
	INC	HL
	DJNZ	.COPY_LOOP
	LD	HL,NETCFG_PATH
	OR	A
	RET
.BAD
	SCF
	RET

; PARSE operates over exactly BC bytes and supports LF, CRLF and CR. Unknown
; and duplicate keys increment NETCFG_WARNINGS; duplicate known keys use last.
PARSE
	PUSH	IX,IY
	LD	(NETPARSE_CURSOR),HL
	LD	(NETPARSE_REMAIN),BC
	CALL	DEFAULTS
.LINE
	LD	HL,(NETPARSE_REMAIN)
	LD	A,H
	OR	L
	JP	Z,.VALIDATE
	CALL	SKIP_EOL_SPACE
	LD	HL,(NETPARSE_REMAIN)
	LD	A,H
	OR	L
	JP	Z,.VALIDATE
	LD	HL,(NETPARSE_CURSOR)
	LD	A,(HL)
	CP	'#'
	JR	Z,.SKIP_LINE
	LD	(NETPARSE_KEY_START),HL
	XOR	A
	LD	(NETPARSE_KEY_LENGTH),A
.KEY
	CALL	GET_BYTE
	JR	C,.MALFORMED
	CP	'='
	JR	Z,.VALUE
	CP	13
	JR	Z,.MALFORMED
	CP	10
	JR	Z,.MALFORMED
	CP	' '
	JR	Z,.KEY_SPACE
	CP	9
	JR	Z,.KEY_SPACE
	CALL	UPPER_A
	LD	(HL),A			; GET_BYTE returned HL at consumed byte
	LD	A,(NETPARSE_KEY_LENGTH)
	INC	A
	LD	(NETPARSE_KEY_LENGTH),A
	CP	16
	JR	NC,.MALFORMED
	JR	.KEY
.KEY_SPACE
	CALL	SKIP_TO_EQUALS
	JR	C,.MALFORMED
.VALUE
	LD	HL,(NETPARSE_CURSOR)
	CALL	SKIP_INLINE_SPACE
	LD	(NETPARSE_VALUE_START),HL
	XOR	A
	LD	(NETPARSE_VALUE_LENGTH),A
.VALUE_SCAN
	LD	HL,(NETPARSE_REMAIN)
	LD	A,H
	OR	L
	JR	Z,.VALUE_END
	CALL	GET_BYTE
	CP	13
	JR	Z,.VALUE_END
	CP	10
	JR	Z,.VALUE_END
	LD	A,(NETPARSE_VALUE_LENGTH)
	INC	A
	LD	(NETPARSE_VALUE_LENGTH),A
	CP	64
	JR	NC,.MALFORMED
	JR	.VALUE_SCAN
.VALUE_END
	LD	HL,(NETPARSE_VALUE_START)
	LD	A,(NETPARSE_VALUE_LENGTH)
	LD	C,A
	CALL	TRIM_VALUE
	LD	(NETPARSE_VALUE_LENGTH),A
	CALL	DISPATCH_KEY
	JR	C,.MALFORMED
	JP	.LINE
.SKIP_LINE
	CALL	SKIP_TO_EOL
	JP	.LINE
.VALIDATE
	CALL	VALIDATE
	POP	IY,IX
	RET
.MALFORMED
	LD	A,NETDRV_ERR_CONFIG
	SCF
	POP	IY,IX
	RET



; GET_BYTE consumes one bounded byte, returning its address in HL and byte A.
GET_BYTE
	LD	BC,(NETPARSE_REMAIN)
	LD	A,B
	OR	C
	JR	Z,.EMPTY
	LD	HL,(NETPARSE_CURSOR)
	LD	A,(HL)
	INC	HL
	LD	(NETPARSE_CURSOR),HL
	DEC	BC
	LD	(NETPARSE_REMAIN),BC
	DEC	HL
	OR	A
	RET
.EMPTY
	SCF
	RET

SKIP_EOL_SPACE
.LOOP
	LD	BC,(NETPARSE_REMAIN)
	LD	A,B
	OR	C
	RET	Z
	LD	HL,(NETPARSE_CURSOR)
	LD	A,(HL)
	CP	13
	JR	Z,.ONE
	CP	10
	JR	Z,.ONE
	CP	' '
	JR	Z,.ONE
	CP	9
	RET	NZ
.ONE
	CALL	GET_BYTE
	JR	.LOOP

SKIP_INLINE_SPACE
.LOOP
	LD	A,(HL)
	CP	' '
	JR	Z,.ONE
	CP	9
	RET	NZ
.ONE
	INC	HL
	LD	(NETPARSE_CURSOR),HL
	LD	BC,(NETPARSE_REMAIN)
	DEC	BC
	LD	(NETPARSE_REMAIN),BC
	JR	.LOOP

SKIP_TO_EQUALS
.LOOP
	CALL	GET_BYTE
	RET	C
	CP	'='
	RET	Z
	CP	' '
	JR	Z,.LOOP
	CP	9
	JR	Z,.LOOP
	SCF
	RET

SKIP_TO_EOL
.LOOP
	CALL	GET_BYTE
	RET	C
	CP	13
	RET	Z
	CP	10
	RET	Z
	JR	.LOOP

; HL=start, C=raw length. Returns A=trimmed length and writes NUL terminator.
TRIM_VALUE
	LD	B,0
	ADD	HL,BC
.TRIM
	LD	A,C
	OR	A
	JR	Z,.DONE
	DEC	HL
	LD	A,(HL)
	CP	' '
	JR	Z,.REMOVE
	CP	9
	JR	NZ,.RESTORE
.REMOVE
	DEC	C
	JR	.TRIM
.RESTORE
	INC	HL
.DONE
	LD	(HL),0
	LD	A,C
	RET

DISPATCH_KEY
	LD	HL,KEY_TABLE
.NEXT
	LD	A,(HL)
	OR	A
	JR	Z,.UNKNOWN
	LD	(NETPARSE_MATCH_RECORD),HL
	PUSH	HL
	LD	DE,(NETPARSE_KEY_START)
	CALL	MATCH_NAME
	POP	HL
	JR	Z,.MATCH
	CALL	ADVANCE_RECORD
	JR	.NEXT
.MATCH
	CALL	ADVANCE_NAME
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	(NETPARSE_MATCH_BIT),DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,(HL)			; destination capacity
	LD	(NETPARSE_DESTINATION),DE
	LD	(NETPARSE_CAPACITY),A
	LD	DE,(NETPARSE_MATCH_BIT)
	CALL	MARK_SEEN
	LD	A,(NETPARSE_CAPACITY)
	LD	B,A
	LD	A,(NETPARSE_VALUE_LENGTH)
	CP	B
	JR	NC,.BAD
	LD	C,A
	LD	B,0
	LD	HL,(NETPARSE_VALUE_START)
	LD	DE,(NETPARSE_DESTINATION)
	LD	A,C
	OR	A
	JR	Z,.TERMINATE
	LDIR
.TERMINATE
	XOR	A
	LD	(DE),A
	RET
.UNKNOWN
	LD	A,(NETCFG_WARNINGS)
	INC	A
	LD	(NETCFG_WARNINGS),A
	OR	A
	RET
.BAD
	SCF
	RET

; MATCH_NAME compares ASCIIZ table name HL with key bytes DE/key length.
MATCH_NAME
	LD	A,(NETPARSE_KEY_LENGTH)
	LD	B,A
.LOOP
	LD	A,B
	OR	A
	JR	Z,.END
	LD	A,(HL)
	OR	A
	JR	Z,.NO
	LD	C,A
	LD	A,(DE)
	CP	C
	JR	NZ,.NO
	INC	HL
	INC	DE
	DJNZ	.LOOP
.END
	LD	A,(HL)
	OR	A
	RET
.NO
	OR	1
	RET

; Helpers for table records: name,0, bit word, destination word, capacity byte.
ADVANCE_NAME
.AN
	LD	A,(HL)
	INC	HL
	OR	A
	JR	NZ,.AN
	RET
ADVANCE_RECORD
	CALL	ADVANCE_NAME
	LD	DE,5
	ADD	HL,DE
	RET

MARK_SEEN
	; In DE=bit mask. Duplicate increments warning, then last value still wins.
	LD	HL,(NETCFG_SEEN)
	LD	A,L
	AND	E
	LD	C,A
	LD	A,H
	AND	D
	OR	C
	JR	Z,.NEW
	LD	A,(NETCFG_WARNINGS)
	INC	A
	LD	(NETCFG_WARNINGS),A
.NEW
	LD	A,L
	OR	E
	LD	L,A
	LD	A,H
	OR	D
	LD	H,A
	LD	(NETCFG_SEEN),HL
	RET

; Validate and normalize values into NETDRV_CONFIG plus IP source.

CFG_FILENAME	DB "NET.CFG",0


; name, bit, destination, capacity
KEY_TABLE
	DB "NET",0
	DW NC_SEEN_NET,NCV_NET
	DB 8
	DB "HW",0
	DW NC_SEEN_HW,NCV_HW
	DB 12
	DB "IDPORT",0
	DW NC_SEEN_IDPORT,NCV_IDPORT
	DB 8
	DB "MAC",0
	DW NC_SEEN_MAC,NCV_MAC
	DB 20
	DB "IP",0
	DW NC_SEEN_IP,NCV_IP
	DB 16
	DB "NETMASK",0
	DW NC_SEEN_MASK,NCV_MASK
	DB 16
	DB "GATEWAY",0
	DW NC_SEEN_GW,NCV_GW
	DB 16
	DB "DNS1",0
	DW NC_SEEN_DNS1,NCV_DNS1
	DB 16
	DB "DNS2",0
	DW NC_SEEN_DNS2,NCV_DNS2
	DB 16
	DB "NTP",0
	DW NC_SEEN_NTP,NCV_NTP
	DB 32
	DB "TZ",0
	DW NC_SEEN_TZ,NCV_TZ
	DB 8
	DB 0


NETPARSE_CURSOR	DW 0
NETPARSE_REMAIN	DW 0
NETPARSE_KEY_START	DW 0
NETPARSE_VALUE_START	DW 0
NETPARSE_MATCH_RECORD	DW 0
NETPARSE_MATCH_BIT	DW 0
NETPARSE_DESTINATION	DW 0
NETPARSE_VALUE_LENGTH	DB 0
NETPARSE_KEY_LENGTH	DB 0
NETPARSE_CAPACITY	DB 0
NETPARSE_SAVED_ERROR	DB 0

	ENDMODULE
	ENDIF
