; Clock-independent bounded polling timebase for Stage 8.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_NETTIME_ASM
	DEFINE	_NETTIME_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

	MODULE NETTIME

NETTIME_CAL_GUARD	EQU 4096
NETTIME_MAX_QPS		EQU 1000 ; CYCLES21 is at least one ms at 21 MHz

; CALIBRATE counts bounded CYCLES21 delays between two DSS_SYSTIME second
; boundaries. Both the alignment and measurement have finite guards.
CALIBRATE
	PUSH	IX,IY
	CALL	READ_SECOND
	LD	(NETTIME_CAL_SECOND),A
	LD	HL,NETTIME_CAL_GUARD
	LD	(NETTIME_CAL_COUNT),HL
.ALIGN
	CALL	@S7APP.WAIT_TICK
	CALL	READ_SECOND
	LD	B,A
	LD	A,(NETTIME_CAL_SECOND)
	CP	B
	JR	NZ,.ALIGNED
	LD	HL,(NETTIME_CAL_COUNT)
	DEC	HL
	LD	(NETTIME_CAL_COUNT),HL
	LD	A,H
	OR	L
	JR	NZ,.ALIGN
	JR	.FAIL
.ALIGNED
	LD	A,B
	LD	(NETTIME_CAL_SECOND),A
	LD	HL,0
	LD	(NETTIME_CAL_COUNT),HL
.MEASURE
	CALL	@S7APP.WAIT_TICK
	LD	HL,(NETTIME_CAL_COUNT)
	INC	HL
	LD	(NETTIME_CAL_COUNT),HL
	CALL	READ_SECOND
	LD	B,A
	LD	A,(NETTIME_CAL_SECOND)
	CP	B
	JR	NZ,.MEASURED
	LD	HL,(NETTIME_CAL_COUNT)
	LD	DE,NETTIME_CAL_GUARD
	OR	A
	SBC	HL,DE
	JR	C,.MEASURE
	JR	.FAIL
.MEASURED
	LD	HL,(NETTIME_CAL_COUNT)
	LD	A,H
	OR	L
	JR	Z,.FAIL
	LD	DE,NETTIME_MAX_QPS
	OR	A
	SBC	HL,DE
	JR	C,.USE_COUNT
	JR	Z,.USE_MAX
.USE_MAX
	LD	HL,NETTIME_MAX_QPS
	JR	.STORE
.USE_COUNT
	ADD	HL,DE
.STORE
	LD	(NETTIME_QPS),HL
	; ceil(1000/qps), used for approximate RTT output.
	LD	DE,0
	LD	BC,1000
.MS_DIVIDE
	LD	HL,BC
	LD	BC,(NETTIME_QPS)
	OR	A
	SBC	HL,BC
	JR	C,.MS_REMAINDER
	LD	B,H
	LD	C,L
	INC	DE
	JR	.MS_DIVIDE
.MS_REMAINDER
	ADD	HL,BC			; restore remainder before the failed subtract
	LD	A,H
	OR	L
	JR	Z,.MS_STORE
	INC	DE
.MS_STORE
	LD	(NETTIME_MS_PER_QUANTUM),DE
	XOR	A
	POP	IY,IX
	RET
.FAIL
	LD	A,EL3_ERR_TIMER
	SCF
	POP	IY,IX
	RET

; START
; In BC=timeout milliseconds 1..65535. Converts it to monotonic polling
; quanta using the measured rate and arms an additional coarse wall watchdog.
START
	PUSH	IX,IY
	LD	A,B
	OR	C
	JR	Z,.START_BAD
	LD	(NETTIME_TIMEOUT_MS),BC
	LD	HL,0
	LD	(NETTIME_QUANTA_LEFT),HL
	LD	(NETTIME_ELAPSED_MS),HL
	LD	DE,0			; fractional qps/1000 accumulator
.QUANTUM_MS
	LD	HL,(NETTIME_QPS)
	ADD	HL,DE
	EX	DE,HL
	LD	HL,DE
	LD	DE,1000
	OR	A
	SBC	HL,DE
	JR	C,.NO_WHOLE_QUANTUM
	EX	DE,HL			; DE=remainder
	LD	HL,(NETTIME_QUANTA_LEFT)
	INC	HL
	LD	(NETTIME_QUANTA_LEFT),HL
	JR	.NEXT_MS
.NO_WHOLE_QUANTUM
	ADD	HL,DE			; restore pre-subtraction accumulator
	EX	DE,HL
.NEXT_MS
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.QUANTUM_MS
	LD	A,D
	OR	E
	JR	Z,.QUANTA_READY
	LD	HL,(NETTIME_QUANTA_LEFT)
	INC	HL
	LD	(NETTIME_QUANTA_LEFT),HL
.QUANTA_READY
	LD	HL,(NETTIME_QUANTA_LEFT)
	LD	A,H
	OR	L
	JR	NZ,.HAVE_QUANTA
	INC	HL
	LD	(NETTIME_QUANTA_LEFT),HL
.HAVE_QUANTA
	LD	(NETTIME_QUANTA_TOTAL),HL
	; ceil(timeout_ms/1000)+2 seconds for a stopped/incorrect calibration.
	LD	HL,(NETTIME_TIMEOUT_MS)
	LD	BC,0
.WALL_DIVIDE
	LD	DE,1000
	OR	A
	SBC	HL,DE
	JR	C,.WALL_REMAINDER
	INC	BC
	JR	.WALL_DIVIDE
.WALL_REMAINDER
	ADD	HL,DE			; restore value before the failed subtraction
	LD	A,H
	OR	L
	JR	Z,.WALL_ADD_GUARD
	INC	BC
.WALL_ADD_GUARD
	INC	BC
	INC	BC
	LD	(NETTIME_WALL_LIMIT),BC
	CALL	READ_WALL
	LD	(NETTIME_START_WALL),HL
	XOR	A
	POP	IY,IX
	RET
.START_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; TICK performs one calibrated finite delay. Out: Z/CF clear while live;
; A=EL3_ERR_RX_TIMEOUT/CF set when either monotonic or wall limit expires.
TICK
	PUSH	IX,IY
	CALL	@S7APP.WAIT_TICK
	LD	HL,(NETTIME_ELAPSED_MS)
	LD	DE,(NETTIME_MS_PER_QUANTUM)
	ADD	HL,DE
	JR	C,.ELAPSED_SATURATE
	LD	DE,(NETTIME_TIMEOUT_MS)
	OR	A
	SBC	HL,DE
	JR	C,.ELAPSED_RESTORE
	JR	Z,.ELAPSED_LIMIT
.ELAPSED_SATURATE
	LD	HL,(NETTIME_TIMEOUT_MS)
	JR	.ELAPSED_STORE
.ELAPSED_RESTORE
	ADD	HL,DE
	JR	.ELAPSED_STORE
.ELAPSED_LIMIT
	ADD	HL,DE
.ELAPSED_STORE
	LD	(NETTIME_ELAPSED_MS),HL
	LD	HL,(NETTIME_QUANTA_LEFT)
	LD	A,H
	OR	L
	JR	Z,.EXPIRED
	DEC	HL
	LD	(NETTIME_QUANTA_LEFT),HL
	LD	A,H
	OR	L
	JR	Z,.EXPIRED
	CALL	READ_WALL
	LD	DE,(NETTIME_START_WALL)
	OR	A
	SBC	HL,DE
	JR	NC,.WALL_DELTA
	LD	DE,3600
	ADD	HL,DE
.WALL_DELTA
	LD	DE,(NETTIME_WALL_LIMIT)
	OR	A
	SBC	HL,DE
	JR	NC,.EXPIRED
	XOR	A
	POP	IY,IX
	RET
.EXPIRED
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	POP	IY,IX
	RET

; READ_WALL returns HL=second within the current hour (0..3599).
READ_WALL
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,B
	LD	(NETTIME_CAL_SECOND),A
	LD	A,L
	LD	HL,0
	LD	DE,60
	OR	A
	JR	Z,.ADD_SECONDS
	LD	B,A
.MINUTES
	ADD	HL,DE
	DJNZ	.MINUTES
.ADD_SECONDS
	LD	A,(NETTIME_CAL_SECOND)
	LD	E,A
	LD	D,0
	ADD	HL,DE
	RET

READ_SECOND
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,B
	RET

	ENDMODULE
	ENDIF
