; Backend-neutral SNTP framing, validation and 1970..2036 calendar conversion.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_NTP_ASM
	DEFINE	_NTP_ASM

	INCLUDE "dns_ntp.inc"
	INCLUDE "netdrv.inc"

	MODULE NTP

; BUILD_REQUEST: HL=NTPB descriptor, BC=48 on success. The caller's eight-byte
; cookie is copied to the transmit timestamp. IX/IY are preserved.
BUILD_REQUEST
	PUSH	IX,IY
	LD	BC,NTPB_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BR_BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+NTPB_COOKIE)
	LD	H,(IX+NTPB_COOKIE+1)
	LD	BC,8
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BR_BAD
	LD	L,(IX+NTPB_BUFFER)
	LD	H,(IX+NTPB_BUFFER+1)
	LD	BC,NTP_PACKET_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BR_BAD
	LD	L,(IX+NTPB_CAPACITY)
	LD	H,(IX+NTPB_CAPACITY+1)
	LD	DE,NTP_PACKET_LENGTH
	OR	A
	SBC	HL,DE
	JP	C,.BR_BAD
	LD	E,(IX+NTPB_BUFFER)
	LD	D,(IX+NTPB_BUFFER+1)
	PUSH	DE
	EX	DE,HL
	LD	BC,NTP_PACKET_LENGTH
	XOR	A
.BR_ZERO
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.BR_ZERO
	POP	DE
	LD	A,0x23			; LI=0, VN=4, client mode=3
	LD	(DE),A
	LD	HL,40
	ADD	HL,DE
	EX	DE,HL
	LD	L,(IX+NTPB_COOKIE)
	LD	H,(IX+NTPB_COOKIE+1)
	LD	BC,8
	LDIR
	LD	BC,NTP_PACKET_LENGTH
	XOR	A
	POP	IY,IX
	RET
.BR_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE_REPLY: validates endpoint-independent NTP fields. UDPX validates the
; IP/UDP endpoint and checksums. The transmit seconds are returned little
; endian through NTPP_SECONDS. Cookie mismatch is stale PARAMETER traffic.
PARSE_REPLY
	PUSH	IX,IY
	LD	BC,NTPP_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PR_BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+NTPP_COOKIE)
	LD	H,(IX+NTPP_COOKIE+1)
	LD	BC,8
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PR_BAD
	LD	L,(IX+NTPP_SECONDS)
	LD	H,(IX+NTPP_SECONDS+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PR_BAD
	LD	L,(IX+NTPP_BUFFER)
	LD	H,(IX+NTPP_BUFFER+1)
	LD	C,(IX+NTPP_LENGTH)
	LD	B,(IX+NTPP_LENGTH+1)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PR_BAD
	LD	L,(IX+NTPP_LENGTH)
	LD	H,(IX+NTPP_LENGTH+1)
	LD	DE,NTP_PACKET_LENGTH
	OR	A
	SBC	HL,DE
	JP	C,.PR_BAD
	LD	L,(IX+NTPP_BUFFER)
	LD	H,(IX+NTPP_BUFFER+1)
	LD	A,(HL)
	LD	B,A
	AND	0xC0
	CP	0xC0
	JP	Z,.PR_BAD		; LI=3 means unsynchronised
	LD	A,B
	RRCA
	RRCA
	RRCA
	AND	7
	CP	3
	JR	Z,.PR_VERSION_OK
	CP	4
	JP	NZ,.PR_BAD
.PR_VERSION_OK
	LD	A,B
	AND	7
	CP	4			; server mode
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JP	Z,.PR_BAD		; reject kiss-of-death/unspecified strata
	CP	16
	JP	NC,.PR_BAD
	LD	L,(IX+NTPP_BUFFER)
	LD	H,(IX+NTPP_BUFFER+1)
	LD	DE,24
	ADD	HL,DE
	LD	E,(IX+NTPP_COOKIE)
	LD	D,(IX+NTPP_COOKIE+1)
	LD	B,8
.PR_COOKIE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.PR_STALE
	INC	DE
	INC	HL
	DJNZ	.PR_COOKIE
	LD	L,(IX+NTPP_BUFFER)
	LD	H,(IX+NTPP_BUFFER+1)
	LD	DE,40
	ADD	HL,DE
	PUSH	HL
	LD	B,8
	XOR	A
.PR_NONZERO
	OR	(HL)
	INC	HL
	DJNZ	.PR_NONZERO
	POP	HL
	JP	Z,.PR_BAD
	; NTP seconds are big endian; store host little endian.
	LD	E,(IX+NTPP_SECONDS)
	LD	D,(IX+NTPP_SECONDS+1)
	PUSH	DE
	POP	IY
	LD	A,(HL)
	LD	(IY+3),A
	INC	HL
	LD	A,(HL)
	LD	(IY+2),A
	INC	HL
	LD	A,(HL)
	LD	(IY+1),A
	INC	HL
	LD	A,(HL)
	LD	(IY+0),A
	; Reject pre-1970 values (83AA7E80h). All larger era-zero values are
	; representable through 2036-02-07 06:28:15.
	LD	L,(IX+NTPP_SECONDS)
	LD	H,(IX+NTPP_SECONDS+1)
	LD	DE,3
	ADD	HL,DE
	LD	A,(HL)
	CP	0x83
	JR	C,.PR_BAD
	JR	NZ,.PR_OK
	DEC	HL
	LD	A,(HL)
	CP	0xAA
	JR	C,.PR_BAD
	JR	NZ,.PR_OK
	DEC	HL
	LD	A,(HL)
	CP	0x7E
	JR	C,.PR_BAD
	JR	NZ,.PR_OK
	DEC	HL
	LD	A,(HL)
	CP	0x80
	JR	C,.PR_BAD
.PR_OK
	XOR	A
	POP	IY,IX
	RET
.PR_STALE
	LD	A,NETDRV_ERR_PARAMETER
	JR	.PR_ERROR
.PR_BAD
	LD	A,NETDRV_ERR_PROTOCOL
.PR_ERROR
	SCF
	POP	IY,IX
	RET

; TO_CALENDAR converts NTP_SECONDS to UTC Gregorian fields. NTP_SECONDS is
; first changed to Unix seconds; bounded repeated subtraction is at most 24107
; day iterations for the supported era.
TO_CALENDAR
	PUSH	IX,IY
	LD	HL,(NTP_SECONDS+0)
	LD	DE,0x7E80
	OR	A
	SBC	HL,DE
	LD	(NTP_SECONDS+0),HL
	LD	HL,(NTP_SECONDS+2)
	LD	DE,0x83AA
	SBC	HL,DE
	LD	(NTP_SECONDS+2),HL
	LD	HL,0
	LD	(NTP_DAYS),HL
.TC_DAY_LOOP
	LD	HL,(NTP_SECONDS+2)
	LD	A,H
	OR	L
	JR	Z,.TC_TIME
	LD	A,H
	OR	A
	JR	NZ,.TC_SUB_DAY		; more than 0001FFFFh is certainly >= one day
	LD	A,L
	CP	2
	JR	NC,.TC_SUB_DAY
	OR	A
	JR	Z,.TC_TIME
	LD	HL,(NTP_SECONDS+0)
	LD	DE,0x5180
	OR	A
	SBC	HL,DE
	JR	C,.TC_TIME
.TC_SUB_DAY
	LD	HL,(NTP_SECONDS+0)
	LD	DE,0x5180
	OR	A
	SBC	HL,DE
	LD	(NTP_SECONDS+0),HL
	LD	HL,(NTP_SECONDS+2)
	LD	DE,1
	SBC	HL,DE
	LD	(NTP_SECONDS+2),HL
	LD	HL,(NTP_DAYS)
	INC	HL
	LD	(NTP_DAYS),HL
	JR	.TC_DAY_LOOP
.TC_TIME
	XOR	A
	LD	(NTP_HOUR),A
.TC_HOUR_LOOP
	LD	HL,(NTP_SECONDS+2)
	LD	A,H
	OR	L
	JR	NZ,.TC_SUB_HOUR
	LD	HL,(NTP_SECONDS+0)
	LD	DE,3600
	OR	A
	SBC	HL,DE
	JR	C,.TC_MINUTES
.TC_SUB_HOUR
	LD	HL,(NTP_SECONDS+0)
	LD	DE,3600
	OR	A
	SBC	HL,DE
	LD	(NTP_SECONDS+0),HL
	LD	HL,(NTP_SECONDS+2)
	LD	DE,0
	SBC	HL,DE
	LD	(NTP_SECONDS+2),HL
	LD	A,(NTP_HOUR)
	INC	A
	LD	(NTP_HOUR),A
	JR	.TC_HOUR_LOOP
.TC_MINUTES
	XOR	A
	LD	(NTP_MINUTE),A
	LD	HL,(NTP_SECONDS+0)
.TC_MINUTE_LOOP
	LD	DE,60
	OR	A
	SBC	HL,DE
	JR	C,.TC_SECONDS
	LD	A,(NTP_MINUTE)
	INC	A
	LD	(NTP_MINUTE),A
	JR	.TC_MINUTE_LOOP
.TC_SECONDS
	ADD	HL,DE
	LD	A,L
	LD	(NTP_SECOND),A
	LD	HL,1970
	LD	(NTP_YEAR),HL
.TC_YEAR_LOOP
	CALL	YEAR_DAYS
	LD	HL,(NTP_DAYS)
	OR	A
	SBC	HL,DE
	JR	C,.TC_MONTH_START
	LD	(NTP_DAYS),HL
	LD	HL,(NTP_YEAR)
	INC	HL
	LD	(NTP_YEAR),HL
	JR	.TC_YEAR_LOOP
.TC_MONTH_START
	LD	A,1
	LD	(NTP_MONTH),A
.TC_MONTH_LOOP
	CALL	DAYS_IN_MONTH
	LD	L,A
	LD	H,0
	LD	DE,(NTP_DAYS)
	EX	DE,HL
	OR	A
	SBC	HL,DE
	JR	C,.TC_DAY_READY
	LD	(NTP_DAYS),HL
	LD	A,(NTP_MONTH)
	INC	A
	LD	(NTP_MONTH),A
	JR	.TC_MONTH_LOOP
.TC_DAY_READY
	LD	HL,(NTP_DAYS)
	INC	L
	LD	A,L
	LD	(NTP_DAY),A
	XOR	A
	POP	IY,IX
	RET

; APPLY_TZ applies signed NTP_TZ_MINUTES and normalises through date edges.
APPLY_TZ
	PUSH	IX,IY
	LD	A,(NTP_HOUR)
	LD	B,A
	LD	HL,0
.AT_HOUR
	LD	A,B
	OR	A
	JR	Z,.AT_ADD_MINUTE
	LD	DE,60
	ADD	HL,DE
	DJNZ	.AT_HOUR
.AT_ADD_MINUTE
	LD	A,(NTP_MINUTE)
	LD	E,A
	LD	D,0
	ADD	HL,DE
	LD	DE,(NTP_TZ_MINUTES)
	ADD	HL,DE
	BIT	7,H
	JR	Z,.AT_HIGH
	LD	DE,1440
	ADD	HL,DE
	PUSH	HL
	CALL	DEC_DATE
	POP	HL
.AT_HIGH
	LD	DE,1440
	OR	A
	SBC	HL,DE
	JR	C,.AT_RESTORE
	PUSH	HL
	CALL	INC_DATE
	POP	HL
	JR	.AT_SPLIT
.AT_RESTORE
	ADD	HL,DE
.AT_SPLIT
	LD	B,0
	LD	DE,60
.AT_DIV60
	OR	A
	SBC	HL,DE
	JR	C,.AT_DIV_DONE
	INC	B
	JR	.AT_DIV60
.AT_DIV_DONE
	ADD	HL,DE
	LD	A,B
	LD	(NTP_HOUR),A
	LD	A,L
	LD	(NTP_MINUTE),A
	XOR	A
	POP	IY,IX
	RET

INC_DATE
	LD	A,(NTP_MONTH)
	CALL	DAYS_IN_MONTH
	LD	B,A
	LD	A,(NTP_DAY)
	CP	B
	JR	C,.ID_SIMPLE
	LD	A,1
	LD	(NTP_DAY),A
	LD	A,(NTP_MONTH)
	INC	A
	CP	13
	JR	C,.ID_MONTH
	LD	A,1
	LD	HL,(NTP_YEAR)
	INC	HL
	LD	(NTP_YEAR),HL
.ID_MONTH
	LD	(NTP_MONTH),A
	RET
.ID_SIMPLE
	INC	A
	LD	(NTP_DAY),A
	RET

DEC_DATE
	LD	A,(NTP_DAY)
	DEC	A
	JR	NZ,.DD_STORE
	LD	A,(NTP_MONTH)
	DEC	A
	JR	NZ,.DD_MONTH
	LD	A,12
	LD	HL,(NTP_YEAR)
	DEC	HL
	LD	(NTP_YEAR),HL
.DD_MONTH
	LD	(NTP_MONTH),A
	CALL	DAYS_IN_MONTH
.DD_STORE
	LD	(NTP_DAY),A
	RET

YEAR_DAYS
	CALL	IS_LEAP
	LD	DE,365
	RET	NZ
	INC	DE
	RET

IS_LEAP
	LD	HL,(NTP_YEAR)
	LD	A,L
	AND	3			; 1970..2036: the only century is leap year 2000
	RET

DAYS_IN_MONTH
	LD	A,(NTP_MONTH)
	CP	2
	JR	NZ,.DM_TABLE
	CALL	IS_LEAP
	LD	A,28
	RET	NZ
	INC	A
	RET
.DM_TABLE
	DEC	A
	LD	E,A
	LD	D,0
	LD	HL,MONTH_DAYS
	ADD	HL,DE
	LD	A,(HL)
	RET

MONTH_DAYS	DB 31,28,31,30,31,30,31,31,30,31,30,31

	ENDMODULE
	ENDIF
