; Shared lifecycle for EL3TX/EL3RX. All DSS calls occur with ISA closed.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_STAGE6_APP_ASM
	DEFINE	_STAGE6_APP_ASM

	INCLUDE "dss.inc"
	INCLUDE "el3.inc"
	INCLUDE "memory.inc"

	MODULE S6APP

; CLEAR resets the shared Stage 6 runtime and cleanup state.
CLEAR
	XOR	A
	LD	H,A
	LD	L,A
	LD	(EL3_LAST_TICKS),HL
	LD	(EL3_LAST_STATUS),HL
	LD	(EL3_LAST_RX_STATUS),HL
	LD	(EL3_RX_REQUIRED),HL
	LD	(EL3_COUNT_RESET),HL
	LD	(EL3_COUNT_TIMEOUT),HL
	LD	(EL3_COUNT_RX),HL
	LD	(EL3_COUNT_TX),HL
	LD	(EL3_COUNT_DROP),HL
	LD	(EL3_COUNT_FRAME),HL
	LD	(S6_WAIT_TICKS),HL
	LD	(S6_ACTUAL_LENGTH),HL
	LD	(S6_FAIL_CODE),A
	LD	(S6_SEQUENCE),A
	LD	(CARD_ACTIVE),A
	LD	(PAGE_ALLOCATED),A
	LD	(EL3_LAST_TX_STATUS),A
	LD	A,0xFF
	LD	(S6_MEMORY_BLOCK),A
	LD	A,EL3_STAGE_ARGS
	LD	(EL3_LAST_STAGE),A
	RET

; PREPARE discovers, activates and initializes the configured card, allocates
; one 16 KiB DSS block in WIN1, and waits for link for CLI_WAIT quanta.
; Out: A=EL3_OK/CF=0 or stable status/CF=1. Cleanup remains the caller's duty.
PREPARE
	LD	A,(CLI_SLOT)
	LD	HL,(CLI_IDPORT)
	CALL	@EL3.CONFIGURE
	RET	C
	CALL	@EL3.DISCOVER
	RET	C
	LD	A,(CLI_BASE_AUTO)
	OR	A
	JR	Z,.EXPLICIT_BASE
	XOR	A
	LD	HL,0
	JR	.ACTIVATE
.EXPLICIT_BASE
	LD	A,1
	LD	HL,(CLI_BASE)
.ACTIVATE
	CALL	@EL3.ACTIVATE
	RET	C
	LD	A,1
	LD	(CARD_ACTIVE),A
	LD	A,EL3_STAGE_MEMORY
	LD	(EL3_LAST_STAGE),A
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JR	C,.NO_MEMORY
	LD	(S6_MEMORY_BLOCK),A
	LD	A,1
	LD	(PAGE_ALLOCATED),A
	LD	A,(S6_MEMORY_BLOCK)
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	JR	C,.NO_MEMORY
	CALL	@EL3.INIT
	RET	C
	LD	BC,(CLI_WAIT)
	CALL	@EL3.WAIT_LINK_UP
	RET
.NO_MEMORY
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	RET

; WAIT_RX waits for a complete receive entry for CLI_WAIT CYCLES21 quanta.
WAIT_RX
	LD	A,EL3_STAGE_RX
	LD	(EL3_LAST_STAGE),A
	LD	HL,0
	LD	(S6_WAIT_TICKS),HL
	LD	(EL3_LAST_TICKS),HL
.POLL
	CALL	@EL3.RX_PENDING
	RET	C
	OR	A
	RET	NZ
	LD	HL,(S6_WAIT_TICKS)
	LD	DE,(CLI_WAIT)
	OR	A
	SBC	HL,DE
	JR	NC,.TIMEOUT
	CALL	@EL3.WAIT_QUANTUM
	LD	HL,(S6_WAIT_TICKS)
	INC	HL
	LD	(S6_WAIT_TICKS),HL
	LD	(EL3_LAST_TICKS),HL
	JR	.POLL
.TIMEOUT
	LD	HL,EL3_COUNT_TIMEOUT
	CALL	@EL3.INC_WORD
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET

; CLEANUP
; In: A=primary status (zero for successful work).
; Out: A=primary/first cleanup status; CF mirrors whether A is non-zero.
; DONE and FREEMEM are always attempted when applicable.
CLEANUP
	LD	(S6_FAIL_CODE),A
	OR	A
	CALL	NZ,SAVE_DIAGNOSTICS
	LD	A,(CARD_ACTIVE)
	OR	A
	JR	Z,.FREE
	CALL	@EL3.DONE
	JR	NC,.CARD_DONE
	CALL	RECORD_CLEANUP_ERROR
.CARD_DONE
	XOR	A
	LD	(CARD_ACTIVE),A
.FREE
	LD	A,(PAGE_ALLOCATED)
	OR	A
	JR	Z,.RETURN
	LD	A,EL3_STAGE_MEMORY
	LD	(EL3_LAST_STAGE),A
	LD	A,(S6_MEMORY_BLOCK)
	LD	C,DSS_FREEMEM
	RST	DSS
	JR	NC,.FREED
	LD	A,EL3_ERR_NO_MEMORY
	CALL	RECORD_CLEANUP_ERROR
.FREED
	XOR	A
	LD	(PAGE_ALLOCATED),A
	LD	A,0xFF
	LD	(S6_MEMORY_BLOCK),A
.RETURN
	LD	A,(S6_FAIL_CODE)
	OR	A
	RET	Z
	CALL	RESTORE_DIAGNOSTICS
	LD	A,(S6_FAIL_CODE)
	SCF
	RET

RECORD_CLEANUP_ERROR
	LD	(CLEANUP_STEP_ERROR),A
	LD	A,(S6_FAIL_CODE)
	OR	A
	RET	NZ
	LD	A,(CLEANUP_STEP_ERROR)
	LD	(S6_FAIL_CODE),A
	JP	SAVE_DIAGNOSTICS

SAVE_DIAGNOSTICS
	LD	A,(EL3_LAST_STAGE)
	LD	(S6_SAVED_STAGE),A
	LD	HL,(EL3_LAST_TICKS)
	LD	(S6_SAVED_TICKS),HL
	LD	HL,(EL3_LAST_STATUS)
	LD	(S6_SAVED_STATUS),HL
	LD	HL,(EL3_LAST_RX_STATUS)
	LD	(S6_SAVED_RX),HL
	LD	A,(EL3_LAST_TX_STATUS)
	LD	(S6_SAVED_TX),A
	LD	HL,(EL3_RX_REQUIRED)
	LD	(S6_SAVED_REQUIRED),HL
	RET

RESTORE_DIAGNOSTICS
	LD	A,(S6_SAVED_STAGE)
	LD	(EL3_LAST_STAGE),A
	LD	HL,(S6_SAVED_TICKS)
	LD	(EL3_LAST_TICKS),HL
	LD	HL,(S6_SAVED_STATUS)
	LD	(EL3_LAST_STATUS),HL
	LD	HL,(S6_SAVED_RX)
	LD	(EL3_LAST_RX_STATUS),HL
	LD	A,(S6_SAVED_TX)
	LD	(EL3_LAST_TX_STATUS),A
	LD	HL,(S6_SAVED_REQUIRED)
	LD	(EL3_RX_REQUIRED),HL
	RET

CARD_ACTIVE		DB 0
PAGE_ALLOCATED		DB 0
CLEANUP_STEP_ERROR	DB 0

	ENDMODULE
	ENDIF
