; Bounded Stage 9 command-line parsers. No DSS or ISA access.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_STAGE9_CLI_ASM
	DEFINE	_STAGE9_CLI_ASM

	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"

	MODULE S9CLI

SEEN_N		EQU 0x01
SEEN_L		EQU 0x02
SEEN_W		EQU 0x04
SEEN_TARGET	EQU 0x08
SEEN_PORT	EQU 0x10
SEEN_HELP	EQU 0x20

	IFNDEF STAGE12_LAYOUT
PARSE_UDP
	PUSH	IX,IY
	XOR	A
	LD	(S9_SEEN),A
	LD	HL,1
	LD	(S9_COUNT),HL
	IFDEF STAGE11_LAYOUT
	LD	HL,2048
	ELSE
	LD	HL,16
	ENDIF
	LD	(S9_SIZE),HL
	LD	HL,5000
	LD	(S9_TIMEOUT_MS),HL
	CALL	READER_INIT
.LOOP
	CALL	NEXT_TOKEN
	JP	C,.END
	LD	A,(HL)
	CP	'-'
	JR	Z,.FLAG
	CP	'/'
	JR	Z,.FLAG
	LD	A,(S9_SEEN)
	AND	SEEN_TARGET
	JR	NZ,.POSITIONAL_PORT
	LD	A,SEEN_TARGET
	CALL	MARK
	JP	C,.BAD
	LD	DE,S9_TARGET_TEXT
	IFDEF STAGE10_DNS
	LD	C,255
	ELSE
	LD	C,16
	ENDIF
	CALL	COPY_TOKEN
	JP	C,.BAD
	LD	HL,S9_TARGET_TEXT
	IFDEF STAGE10_DNS
	CALL	@DNS.VALIDATE_NAME
	ELSE
	LD	DE,NET_TARGET_IP
	CALL	@S9APP.PARSE_IPV4
	ENDIF
	JP	C,.BAD
	JP	.LOOP
.POSITIONAL_PORT
	LD	A,SEEN_PORT
	CALL	MARK
	JP	C,.BAD
	CALL	PARSE_U16
	JP	C,.BAD
	LD	A,B
	OR	C
	JP	Z,.BAD
	LD	(S9_REMOTE_PORT),BC
	JP	.LOOP
.FLAG
	LD	A,(CLI_TOKEN_LEN)
	CP	2
	JP	NZ,.BAD
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'H'
	JR	Z,.HELP
	CP	'?'
	JR	Z,.HELP
	CP	'N'
	JR	Z,.COUNT
	CP	'L'
	JR	Z,.SIZE
	CP	'W'
	JP	Z,.WAIT
	JP	.BAD
.HELP
	LD	A,SEEN_HELP
	CALL	MARK
	JP	C,.BAD
	JP	.LOOP
.COUNT
	LD	A,SEEN_N
	CALL	MARK
	JP	C,.BAD
	CALL	NEXT_TOKEN
	JP	C,.BAD
	CALL	PARSE_U16
	JP	C,.BAD
	LD	A,B
	OR	C
	JP	Z,.BAD
	LD	(S9_COUNT),BC
	JP	.LOOP
.SIZE
	LD	A,SEEN_L
	CALL	MARK
	JP	C,.BAD
	CALL	NEXT_TOKEN
	JP	C,.BAD
	CALL	PARSE_U16
	JP	C,.BAD
	IFDEF STAGE11_LAYOUT
	LD	HL,S11_APP_CAPACITY
	ELSE
	LD	HL,1472
	ENDIF
	OR	A
	SBC	HL,BC
	JP	C,.BAD
	LD	(S9_SIZE),BC
	JP	.LOOP
.WAIT
	LD	A,SEEN_W
	CALL	MARK
	JP	C,.BAD
	CALL	NEXT_TOKEN
	JP	C,.BAD
	CALL	PARSE_U16
	JP	C,.BAD
	LD	A,B
	OR	C
	JP	Z,.BAD
	LD	(S9_TIMEOUT_MS),BC
	JP	.LOOP
.END
	LD	A,(S9_SEEN)
	AND	SEEN_HELP
	JR	Z,.NOT_HELP
	LD	A,(S9_SEEN)
	CP	SEEN_HELP
	JR	NZ,.BAD
	LD	A,EL3_CLI_HELP
	SCF
	POP	IY,IX
	RET
.NOT_HELP
	LD	A,(S9_SEEN)
	AND	SEEN_TARGET | SEEN_PORT
	CP	SEEN_TARGET | SEEN_PORT
	JR	NZ,.BAD
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE_TFTP implements:
; TFTP host[:port] GET remote [-o local] [-y|-f]
; TFTP host[:port] PUT local [-o remote]
	IFDEF STAGE9_TFTP
PARSE_TFTP
	PUSH	IX,IY
	XOR	A
	LD	(S9_SEEN),A
	LD	(S9_TFTP_FORCE),A
	LD	HL,69
	LD	(S9_TFTP_REQUEST_PORT),HL
	CALL	READER_INIT
	CALL	NEXT_TOKEN
	JP	C,.T_BAD
	LD	A,(CLI_TOKEN_LEN)
	CP	2
	JR	NZ,.NOT_HELP
	LD	A,(HL)
	CP	'-'
	JR	Z,.HELP_PREFIX
	CP	'/'
	JR	NZ,.NOT_HELP
.HELP_PREFIX
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'H'
	JR	Z,.HELP_ONLY
	CP	'?'
	JR	NZ,.NOT_HELP
.HELP_ONLY
	CALL	NEXT_TOKEN
	JP	NC,.T_BAD
	LD	A,EL3_CLI_HELP
	SCF
	POP	IY,IX
	RET
.NOT_HELP
	LD	DE,S9_TFTP_HOST
	IFDEF STAGE10_DNS
	LD	C,255
	ELSE
	LD	C,22
	ENDIF
	CALL	COPY_TOKEN
	JP	C,.T_BAD
	LD	HL,S9_TFTP_HOST
.HOST_SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.HOST_READY
	CP	':'
	JR	Z,.HOST_PORT
	INC	HL
	JR	.HOST_SCAN
.HOST_PORT
	XOR	A
	LD	(HL),A
	INC	HL
	PUSH	HL
	LD	B,0
.PORT_LENGTH
	LD	A,(HL)
	OR	A
	JR	Z,.PORT_LENGTH_DONE
	INC	HL
	INC	B
	JR	.PORT_LENGTH
.PORT_LENGTH_DONE
	LD	A,B
	LD	(CLI_TOKEN_LEN),A
	POP	HL
	CALL	PARSE_U16
	JP	C,.T_BAD
	LD	A,B
	OR	C
	JP	Z,.T_BAD
	LD	(S9_TFTP_REQUEST_PORT),BC
.HOST_READY
	LD	HL,S9_TFTP_HOST
	IFDEF STAGE10_DNS
	CALL	@DNS.VALIDATE_NAME
	ELSE
	LD	DE,NET_TARGET_IP
	CALL	@S9APP.PARSE_IPV4
	ENDIF
	JP	C,.T_BAD
	CALL	NEXT_TOKEN
	JP	C,.T_BAD
	LD	DE,V_GET
	CALL	TOKEN_EQ
	JR	NZ,.CHECK_PUT
	XOR	A
	LD	(S9_TFTP_MODE),A
	JR	.MODE_READY
.CHECK_PUT
	LD	DE,V_PUT
	CALL	TOKEN_EQ
	JP	NZ,.T_BAD
	LD	A,1
	LD	(S9_TFTP_MODE),A
.MODE_READY
	CALL	NEXT_TOKEN
	JP	C,.T_BAD
	LD	A,(S9_TFTP_MODE)
	OR	A
	JR	NZ,.PUT_LOCAL
	LD	DE,S9_TFTP_REMOTE_NAME
	LD	C,80
	CALL	COPY_TOKEN
	JP	C,.T_BAD
	JR	.OPTIONS
.PUT_LOCAL
	LD	DE,S9_TFTP_LOCAL_NAME
	LD	C,96
	CALL	COPY_TOKEN
	JP	C,.T_BAD
.OPTIONS
	CALL	NEXT_TOKEN
	JR	C,.NAMES
	LD	A,(CLI_TOKEN_LEN)
	CP	2
	JP	NZ,.T_BAD
	LD	A,(HL)
	CP	'-'
	JR	Z,.OPTION_CHAR
	CP	'/'
	JP	NZ,.T_BAD
.OPTION_CHAR
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'O'
	JR	Z,.OVERRIDE
	CP	'Y'
	JR	Z,.FORCE
	CP	'F'
	JP	NZ,.T_BAD
.FORCE
	LD	A,(S9_TFTP_MODE)
	OR	A
	JP	NZ,.T_BAD
	LD	A,0x02
	CALL	MARK_TFTP
	JP	C,.T_BAD
	LD	A,1
	LD	(S9_TFTP_FORCE),A
	JR	.OPTIONS
.OVERRIDE
	LD	A,0x01
	CALL	MARK_TFTP
	JP	C,.T_BAD
	CALL	NEXT_TOKEN
	JP	C,.T_BAD
	LD	A,(S9_TFTP_MODE)
	OR	A
	JR	NZ,.OVERRIDE_REMOTE
	LD	DE,S9_TFTP_LOCAL_NAME
	LD	C,96
	JR	.OVERRIDE_COPY
.OVERRIDE_REMOTE
	LD	DE,S9_TFTP_REMOTE_NAME
	LD	C,80
.OVERRIDE_COPY
	CALL	COPY_TOKEN
	JP	C,.T_BAD
	JR	.OPTIONS
.NAMES
	LD	A,(S9_TFTP_MODE)
	OR	A
	JR	NZ,.PUT_NAMES
	LD	A,(S9_SEEN)
	AND	0x01
	JR	NZ,.T_OK
.GET_BASENAME
	LD	HL,S9_TFTP_REMOTE_NAME
	CALL	@FILE.BASENAME
.GET_COPY
	LD	DE,S9_TFTP_LOCAL_NAME
	LD	C,96
	CALL	COPY_Z
	JP	C,.T_BAD
	JR	.T_OK
.PUT_NAMES
	LD	A,(S9_SEEN)
	AND	0x01
	JR	NZ,.T_OK
.PUT_BASENAME
	LD	HL,S9_TFTP_LOCAL_NAME
	CALL	@FILE.BASENAME
.PUT_COPY
	LD	DE,S9_TFTP_REMOTE_NAME
	LD	C,80
	CALL	COPY_Z
	JP	C,.T_BAD
.T_OK
	XOR	A
	POP	IY,IX
	RET
.T_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

TOKEN_EQ
	LD	A,(CLI_TOKEN_LEN)
	LD	B,A
.TEQ
	LD	A,B
	OR	A
	JR	Z,.TEQ_END
	LD	A,(DE)
	CALL	UPPER
	LD	C,A
	LD	A,(HL)
	CALL	UPPER
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	DEC	B
	JR	.TEQ
.TEQ_END
	LD	A,(DE)
	OR	A
	RET

COPY_Z
	LD	B,0
.Z_COUNT
	LD	A,(HL)
	OR	A
	JR	Z,.Z_COPY
	INC	HL
	INC	B
	LD	A,B
	CP	C
	JR	NC,.Z_BAD
	JR	.Z_COUNT
.Z_COPY
	LD	A,B
	OR	A
	JR	Z,.Z_BAD
	LD	(CLI_TOKEN_LEN),A
	LD	A,L
	SUB	B
	LD	L,A
	JR	NC,COPY_TOKEN
	DEC	H
	JR	COPY_TOKEN
.Z_BAD
	SCF
	RET

MARK_TFTP
	LD	B,A
	LD	A,(S9_SEEN)
	AND	B
	JR	NZ,.T_DUP
	LD	A,(S9_SEEN)
	OR	B
	LD	(S9_SEEN),A
	OR	A
	RET
.T_DUP
	SCF
	RET

V_GET	DB "GET",0
V_PUT	DB "PUT",0
	ENDIF
	ENDIF	; !STAGE12_LAYOUT

	IFDEF STAGE12_LAYOUT
	IFNDEF STAGE13_LAYOUT
; PARSE_WGET implements:
; WGET url [-o output] [-y|-f] [-r] [-d]
; Options may precede or follow the URL.  W12_FLAGS: bit 0 force, bit 1 resume,
; bit 2 dot progress, bit 3 explicit output.  Resume deliberately coexists with
; force; the application gives it precedence, matching the sibling CLI.
PARSE_WGET
	PUSH	IX,IY
	XOR	A
	LD	(W12_FLAGS),A
	LD	(W12_STATUS_SEEN),A	; temporary: positional URL already copied
	CALL	READER_INIT
	JP	.W_NEXT
.W_LOOP
	LD	A,(CLI_TOKEN_LEN)
	CP	2
	JR	NZ,.W_URL
	LD	A,(HL)
	CP	'-'
	JR	Z,.W_OPTION_CHAR
	CP	'/'
	JR	NZ,.W_URL
.W_OPTION_CHAR
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'H'
	JR	Z,.W_HELP
	CP	'?'
	JR	Z,.W_HELP
	CP	'O'
	JR	Z,.W_OUTPUT
	CP	'Y'
	JR	Z,.W_FORCE
	CP	'F'
	JR	Z,.W_FORCE
	CP	'R'
	JR	Z,.W_RESUME
	CP	'D'
	JR	NZ,.W_BAD
	LD	B,0x04
	JR	.W_MARK
.W_FORCE
	LD	B,0x01
	JR	.W_MARK
.W_RESUME
	LD	B,0x02
.W_MARK
	LD	A,(W12_FLAGS)
	OR	B
	LD	(W12_FLAGS),A
	JR	.W_NEXT
.W_OUTPUT
	CALL	NEXT_TOKEN
	JR	C,.W_BAD
	LD	DE,W12_OUTPUT
	LD	C,96
	CALL	COPY_TOKEN
	JR	C,.W_BAD
	LD	A,(W12_FLAGS)
	OR	0x08
	LD	(W12_FLAGS),A
	JR	.W_NEXT
.W_HELP
	CALL	NEXT_TOKEN
	JR	NC,.W_BAD
	LD	A,(W12_STATUS_SEEN)
	OR	A
	JR	NZ,.W_BAD
	LD	A,(W12_FLAGS)
	OR	A
	JR	NZ,.W_BAD
	LD	A,EL3_CLI_HELP
	SCF
	POP	IY,IX
	RET
.W_URL
	LD	A,(W12_STATUS_SEEN)
	OR	A
	JR	NZ,.W_BAD
	LD	DE,W12_URL
	LD	C,255
	CALL	COPY_TOKEN
	JR	C,.W_BAD
	LD	A,1
	LD	(W12_STATUS_SEEN),A
.W_NEXT
	CALL	NEXT_TOKEN
	JP	NC,.W_LOOP
.W_DONE
	LD	A,(W12_STATUS_SEEN)
	OR	A
	JR	Z,.W_BAD
	XOR	A
	POP	IY,IX
	RET
.W_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET
	ENDIF
	ENDIF

	IFDEF STAGE13_LAYOUT
; PARSE_FTP implements:
;   FTP host[:port] path       [-l|-n] [-u user] [-p pass] [-o out] [-y|-f] [-r] [-d]
;   FTP host[:port] PUT local  [-u user] [-p pass] [-o remote-name]
;   FTP host[:port] [path] -l|-n ...
;   FTP /?
; F13_FLAGS bits: 0 force, 1 resume, 2 dots, 3 list, 4 request NLST (-n),
; 5 has -o, 6 has -u, 7 has -p.  The NLST bit is consumed by ftp.asm when a
; server rejects NLST with 5xx and it retries the already-open data channel
; with LIST.
; F13_MODE is left 0 (GET-or-LIST, resolved by the
; caller once parsing is done) or set to 1 the moment the "PUT" keyword is
; recognised. F13_POS_COUNT tracks which positional comes next: 0 host,
; 1 verb-or-path, 2 the local file after a recognised PUT, 3 done.
; A raw -o value is staged in F13_OUTPUT_OVERRIDE since whether it means the
; local or the remote name depends on the mode, decided only after every
; token is seen (and NOT in F13_REPLY_LINE: that gets overwritten by every
; control-channel reply, all of which happen before DERIVE_ARGS's pointer to
; it would ever be dereferenced).
PARSE_FTP
	PUSH	IX,IY
	XOR	A
	LD	(F13_FLAGS),A
	LD	(F13_POS_COUNT),A
	LD	(F13_MODE),A
	LD	HL,21
	LD	(F13_CTRL_PORT),HL
	CALL	READER_INIT
	JP	.F_NEXT
.F_LOOP
	LD	A,(CLI_TOKEN_LEN)
	CP	2
	JP	NZ,.F_POSITIONAL
	LD	A,(HL)
	CP	'-'
	JR	Z,.F_OPT
	CP	'/'
	JP	NZ,.F_POSITIONAL
.F_OPT
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'H'
	JP	Z,.F_HELP
	CP	'?'
	JP	Z,.F_HELP
	CP	'U'
	JP	Z,.F_USERFLAG
	CP	'P'
	JP	Z,.F_PASSFLAG
	CP	'O'
	JP	Z,.F_OUTPUTFLAG
	; L/N/Y/F/R/D just OR a bit mask into F13_FLAGS; a small table beats six
	; more CP/JR pairs. -n includes the list-mode bit and its own NLST selector.
	LD	C,A
	LD	HL,SIMPLE_FLAGS
.F_SCAN
	LD	A,(HL)
	OR	A
	JP	Z,.F_BAD
	INC	HL
	CP	C
	JR	Z,.F_HIT
	INC	HL
	JR	.F_SCAN
.F_HIT
	LD	A,(F13_FLAGS)
	OR	(HL)
	LD	(F13_FLAGS),A
	JP	.F_NEXT
.F_USERFLAG
	CALL	NEXT_TOKEN
	JP	C,.F_BAD
	LD	DE,F13_USER
	LD	C,31
	CALL	COPY_TOKEN
	JP	C,.F_BAD
	LD	A,(F13_FLAGS)
	OR	0x40
	LD	(F13_FLAGS),A
	JP	.F_NEXT
.F_PASSFLAG
	CALL	NEXT_TOKEN
	JP	C,.F_BAD
	LD	DE,F13_PASS
	LD	C,31
	CALL	COPY_TOKEN
	JP	C,.F_BAD
	LD	A,(F13_FLAGS)
	OR	0x80
	LD	(F13_FLAGS),A
	JP	.F_NEXT
.F_OUTPUTFLAG
	CALL	NEXT_TOKEN
	JP	C,.F_BAD
	LD	DE,F13_OUTPUT_OVERRIDE
	LD	C,95
	CALL	COPY_TOKEN
	JP	C,.F_BAD
	LD	A,(F13_FLAGS)
	OR	0x20
	LD	(F13_FLAGS),A
	JP	.F_NEXT
.F_HELP
	CALL	NEXT_TOKEN
	JP	NC,.F_BAD
	LD	A,(F13_POS_COUNT)
	OR	A
	JP	NZ,.F_BAD
	LD	A,(F13_FLAGS)
	OR	A
	JP	NZ,.F_BAD
	LD	A,EL3_CLI_HELP
	SCF
	POP	IY,IX
	RET
.F_POSITIONAL
	LD	A,(F13_POS_COUNT)
	OR	A
	JR	Z,.F_HOST
	CP	1
	JR	Z,.F_VERB
	CP	2
	JR	Z,.F_PUTFILE
	JP	.F_BAD
.F_HOST
	LD	DE,F13_HOST
	LD	C,63
	CALL	COPY_TOKEN
	JP	C,.F_BAD
	CALL	SPLIT_HOST_PORT
	JP	C,.F_BAD
	LD	A,1
	LD	(F13_POS_COUNT),A
	JP	.F_NEXT
.F_VERB
	LD	A,(CLI_TOKEN_LEN)
	CP	3
	JR	NZ,.F_PATH
	PUSH	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'P'
	JR	NZ,.F_NOTPUT
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'U'
	JR	NZ,.F_NOTPUT
	INC	HL
	LD	A,(HL)
	CALL	UPPER
	CP	'T'
	JR	NZ,.F_NOTPUT
	POP	HL
	LD	A,1
	LD	(F13_MODE),A
	LD	A,2
	LD	(F13_POS_COUNT),A
	JP	.F_NEXT
.F_NOTPUT
	POP	HL
.F_PATH
	LD	DE,F13_REMOTE_PATH
	LD	C,255
	CALL	COPY_TOKEN
	JP	C,.F_BAD
	LD	A,3
	LD	(F13_POS_COUNT),A
	JP	.F_NEXT
.F_PUTFILE
	LD	DE,F13_LOCAL_OUTPUT
	LD	C,95
	CALL	COPY_TOKEN
	JP	C,.F_BAD
	LD	A,3
	LD	(F13_POS_COUNT),A
.F_NEXT
	CALL	NEXT_TOKEN
	JP	NC,.F_LOOP
	LD	A,(F13_POS_COUNT)
	OR	A
	JP	Z,.F_BAD
	CP	2
	JP	Z,.F_BAD		; saw PUT but no local filename followed
	CP	1
	JR	NZ,.F_HAVE_PATH
	LD	A,(F13_FLAGS)
	AND	F13_FLAG_LIST_MASK
	JP	Z,.F_BAD		; bare host only valid with -l/-n
	XOR	A
	LD	(F13_REMOTE_PATH),A
.F_HAVE_PATH
	LD	A,(F13_FLAGS)
	BIT	6,A
	JR	NZ,.F_HAVE_U
	LD	HL,DEFAULT_FTP_USER
	LD	DE,F13_USER
	CALL	COPY_Z_NUL
.F_HAVE_U
	LD	A,(F13_FLAGS)
	BIT	7,A
	JR	NZ,.F_DONE
	BIT	6,A
	JR	NZ,.F_EMPTY_PASS
	LD	HL,DEFAULT_FTP_PASS
	LD	DE,F13_PASS
	CALL	COPY_Z_NUL
	JR	.F_DONE
.F_EMPTY_PASS
	XOR	A
	LD	(F13_PASS),A
.F_DONE
	XOR	A
	POP	IY,IX
	RET
.F_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; SPLIT_HOST_PORT scans the just-copied F13_HOST for ':'. Absent, the
; caller's default (21) stands. Present, it is replaced with a NUL and the
; digits after it become F13_CTRL_PORT; trailing garbage, no digits, or a
; literal 0 are rejected. More than 5 digits is rejected outright, but a
; 5-digit value between 65536 and 99999 wraps mod 65536 rather than being
; caught -- a malformed port sent to the wrong number fails to connect
; instead of failing to parse, which is a fine trade for a CLI argument
; nobody but the caller controls.
SPLIT_HOST_PORT
	LD	HL,F13_HOST
.SCAN
	LD	A,(HL)
	OR	A
	JR	Z,.DONE
	CP	':'
	JR	Z,.SPLIT
	INC	HL
	JR	.SCAN
.SPLIT
	XOR	A
	LD	(HL),A
	INC	HL
	LD	DE,0
	LD	B,0
.DIGIT
	LD	A,(HL)
	SUB	'0'
	JR	C,.PEND
	CP	10
	JR	NC,.PEND
	LD	C,A
	INC	B
	LD	A,B
	CP	6			; more than 5 digits is already > 65535
	JR	NC,.BAD
	PUSH	HL
	; DE = DE*10 + C, via HL = DE*2, *4 (=DE*8), plus the two DE's and C.
	LD	H,D
	LD	L,E
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	ADD	HL,DE
	LD	D,0
	LD	E,C
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	INC	HL
	JR	.DIGIT
.PEND
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	A,(HL)
	OR	A
	JR	NZ,.BAD
	LD	A,D
	OR	E
	JR	Z,.BAD
	LD	(F13_CTRL_PORT),DE
.DONE
	OR	A
	RET
.BAD
	SCF
	RET

COPY_Z_NUL
	LD	A,(HL)
	LD	(DE),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_Z_NUL

DEFAULT_FTP_USER DB "anonymous",0
DEFAULT_FTP_PASS DB "anonymous@",0
SIMPLE_FLAGS
	DB	'L',F13_FLAG_LIST_MASK
	DB	'N',F13_FLAG_LIST_MASK | F13_FLAG_NLST_MASK
	DB	'Y',0x01
	DB	'F',0x01
	DB	'R',0x02
	DB	'D',0x04
	DB	0
	ENDIF

READER_INIT
	LD	HL,(CMDLINE_SOURCE)
	LD	A,(HL)
	INC	HL
	LD	(CLI_READER_PTR),HL
	LD	(CLI_READER_REMAIN),A
	RET

NEXT_TOKEN
	LD	HL,(CLI_READER_PTR)
	LD	A,(CLI_READER_REMAIN)
	LD	B,A
.SKIP
	LD	A,B
	OR	A
	JR	Z,.NONE
	LD	A,(HL)
	CP	' '
	JR	Z,.SKIP_ONE
	CP	9
	JR	NZ,.START
.SKIP_ONE
	INC	HL
	DEC	B
	JR	.SKIP
.START
	PUSH	HL
	LD	C,0
.SCAN
	LD	A,B
	OR	A
	JR	Z,.DONE
	LD	A,(HL)
	CP	' '
	JR	Z,.DONE
	CP	9
	JR	Z,.DONE
	INC	HL
	INC	C
	DEC	B
	JR	.SCAN
.DONE
	LD	(CLI_READER_PTR),HL
	LD	A,B
	LD	(CLI_READER_REMAIN),A
	LD	A,C
	LD	(CLI_TOKEN_LEN),A
	POP	HL
	OR	A
	RET
.NONE
	SCF
	RET

COPY_TOKEN
	LD	A,(CLI_TOKEN_LEN)
	CP	C
	JR	NC,.COPY_BAD
	LD	B,A
.COPY
	LD	A,B
	OR	A
	JR	Z,.TERM
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	JR	.COPY
.TERM
	XOR	A
	LD	(DE),A
	RET
.COPY_BAD
	SCF
	RET

	IFNDEF STAGE12_LAYOUT
PARSE_U16
	LD	A,(CLI_TOKEN_LEN)
	OR	A
	JR	Z,.NUM_BAD
	CP	6
	JR	NC,.NUM_BAD
	LD	(S9_FLAGS),A
	LD	BC,0
.DIGIT
	LD	A,(HL)
	CP	'0'
	JR	C,.NUM_BAD
	CP	'9'+1
	JR	NC,.NUM_BAD
	SUB	'0'
	LD	(S9_PRIMARY_ERROR),A
	PUSH	HL
	LD	H,B
	LD	L,C
	ADD	HL,HL
	JR	C,.POP_BAD
	LD	D,H
	LD	E,L
	ADD	HL,HL
	JR	C,.POP_BAD
	ADD	HL,HL
	JR	C,.POP_BAD
	ADD	HL,DE
	JR	C,.POP_BAD
	LD	A,(S9_PRIMARY_ERROR)
	LD	E,A
	LD	D,0
	ADD	HL,DE
	JR	C,.POP_BAD
	LD	B,H
	LD	C,L
	POP	HL
	INC	HL
	LD	A,(S9_FLAGS)
	DEC	A
	LD	(S9_FLAGS),A
	JR	NZ,.DIGIT
	OR	A
	RET
.POP_BAD
	POP	HL
.NUM_BAD
	SCF
	RET

MARK
	LD	B,A
	LD	A,(S9_SEEN)
	AND	B
	JR	NZ,.DUP
	LD	A,(S9_SEEN)
	OR	B
	LD	(S9_SEEN),A
	OR	A
	RET
.DUP
	SCF
	RET
	ENDIF

UPPER
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	SUB	'a'-'A'
	RET

	ENDMODULE
	ENDIF
