; Stage 11 command-line bootstrap for one private DSS page.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_STAGE11_APP_ASM
	DEFINE	_STAGE11_APP_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"

	MODULE S11APP

; SAVE_COMMAND runs before WIN1 remapping and preserves the complete DSS record.
SAVE_COMMAND
	PUSH	IY
	PUSH	IX
	POP	HL
	LD	A,(HL)
	LD	C,A
	LD	B,0
	INC	BC
	LD	DE,S10_COMMAND_BUFFER
	LDIR
	LD	IX,S10_COMMAND_BUFFER
	POP	IY
	RET

; ALLOCATE_FRESH maps one page, then copies the saved command into that page.
ALLOCATE_FRESH
	PUSH	IY
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JP	C,.FAIL
	LD	E,A
	PUSH	DE
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	POP	DE
	JP	C,.SET_FAIL
	CALL	@S9APP.CLEAR
	LD	A,E
	LD	(NETDRV_MEMORY_BLOCK),A
	LD	A,1
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	HL,S10_COMMAND_BUFFER
	LD	A,(HL)
	LD	C,A
	LD	B,0
	INC	BC
	LD	DE,S10_PAGE_COMMAND_BUFFER
	LDIR
	LD	IX,S10_PAGE_COMMAND_BUFFER
	LD	HL,0
	LD	(S11_NEXT_LOCAL_PORT),HL
	XOR	A
	POP	IY
	RET
.SET_FAIL
	PUSH	AF
	LD	A,E
	LD	C,DSS_FREEMEM
	RST	DSS
	POP	AF
.FAIL
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	POP	IY
	RET

	ENDMODULE
	ENDIF
