; Shared page allocation, environment loading and fail-safe Stage 7 cleanup.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_STAGE7_APP_ASM
	DEFINE	_STAGE7_APP_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "netdrv.inc"

	MODULE S7APP

CLEAR
	XOR	A
	LD	(NETDRV_ACTIVE),A
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	(NETDRV_FAIL_CODE),A
	LD	(NETDRV_SELECTED_SLOT),A
	LD	HL,0
	LD	(NETDRV_SELECTED_BASE),HL
	LD	A,0xFF
	LD	(NETDRV_MEMORY_BLOCK),A
	RET

ALLOCATE
	PUSH	IX,IY
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JP	C,.FAIL
	LD	(NETDRV_MEMORY_BLOCK),A
	LD	A,1
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	A,(NETDRV_MEMORY_BLOCK)
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	JP	C,.FAIL
	XOR	A
	POP	IY,IX
	RET
.FAIL
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	POP	IY,IX
	RET

INIT_DRIVER
	PUSH	IX,IY
	LD	HL,NETDRV_CONFIG
	CALL	@NETDRV.INIT
	POP	IY,IX
	RET

; CLEANUP
; In A=primary status. DONE and FREEMEM are both attempted; the first error is
; returned. No DSS call occurs until NETDRV has closed the ISA window.
CLEANUP
	PUSH	IX,IY
	LD	(NETDRV_FAIL_CODE),A
	CALL	@NETDRV.DONE
	JR	NC,.FREE
	LD	B,A
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	NZ,.FREE
	LD	A,B
	LD	(NETDRV_FAIL_CODE),A
.FREE
	LD	A,(NETDRV_PAGE_ALLOCATED)
	OR	A
	JR	Z,.RETURN
	LD	A,(NETDRV_MEMORY_BLOCK)
	LD	C,DSS_FREEMEM
	RST	DSS
	JR	NC,.FREED
	LD	B,A
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	NZ,.FREED
	LD	A,EL3_ERR_NO_MEMORY
	LD	(NETDRV_FAIL_CODE),A
.FREED
	XOR	A
	LD	(NETDRV_PAGE_ALLOCATED),A
.RETURN
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	Z,.OK
	SCF
	POP	IY,IX
	RET
.OK
	XOR	A
	POP	IY,IX
	RET

; LOAD_ENV_CONFIG reconstructs NETDRV config and common IP fields exclusively
; from published environment. No application other than NETCFG reads NET.CFG.
LOAD_ENV_CONFIG
	PUSH	IX,IY
	CALL	@NETPARSE.DEFAULTS
	LD	HL,E_NET
	LD	DE,NCV_NET
	LD	B,NCV_NET_CAP
	CALL	GET_REQUIRED
	JP	C,.FAIL
	LD	HL,E_HW
	LD	DE,NCV_HW
	LD	B,NCV_HW_CAP
	CALL	GET_REQUIRED
	JP	C,.FAIL
	LD	HL,E_IDPORT
	LD	DE,NCV_IDPORT
	LD	B,NCV_IDPORT_CAP
	CALL	GET_REQUIRED
	JP	C,.FAIL
	LD	HL,E_MAC
	LD	DE,NCV_MAC
	LD	B,NCV_MAC_CAP
	CALL	GET_REQUIRED
	JP	C,.FAIL
	LD	HL,E_IP_SRC
	LD	DE,NCV_IP_SRC
	LD	B,NCV_IP_SRC_CAP
	CALL	GET_REQUIRED
	JP	C,.FAIL
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_LOCAL
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.STATIC
	LD	HL,VALUE_DHCP_LOCAL
	LD	DE,NCV_IP
	CALL	@NETPARSE.COPY_Z
	JR	.OPTIONAL
.STATIC
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_STATIC_LOCAL
	CALL	@NETPARSE.STR_EQ_CI
	JP	NZ,.FAIL
	LD	HL,E_IP
	LD	DE,NCV_IP
	LD	B,NCV_IP_CAP
	CALL	GET_REQUIRED
	JR	C,.FAIL
	LD	HL,E_MASK
	LD	DE,NCV_MASK
	LD	B,NCV_MASK_CAP
	CALL	GET_REQUIRED
	JR	C,.FAIL
	LD	HL,E_GW
	LD	DE,NCV_GW
	LD	B,NCV_GW_CAP
	CALL	GET_OPTIONAL
	JR	C,.FAIL
.OPTIONAL
	LD	HL,E_DNS1
	LD	DE,NCV_DNS1
	LD	B,NCV_DNS_CAP
	CALL	GET_OPTIONAL
	JR	C,.FAIL
	LD	HL,E_DNS2
	LD	DE,NCV_DNS2
	LD	B,NCV_DNS_CAP
	CALL	GET_OPTIONAL
	JR	C,.FAIL
	LD	HL,E_NTP
	LD	DE,NCV_NTP
	LD	B,NCV_NTP_CAP
	CALL	GET_OPTIONAL
	JR	C,.FAIL
	LD	HL,E_TZ
	LD	DE,NCV_TZ
	LD	B,NCV_TZ_CAP
	CALL	GET_OPTIONAL
	JR	C,.FAIL
	; Mark the two mandatory parser keys before common validation.
	LD	HL,NC_SEEN_NET | NC_SEEN_IP
	LD	(NETCFG_SEEN),HL
	CALL	@NETPARSE.VALIDATE
	JR	C,.FAIL
	XOR	A
	POP	IY,IX
	RET
.FAIL
	LD	A,NETDRV_ERR_CONFIG
	SCF
	POP	IY,IX
	RET

; LOAD_ACTIVE_CONFIG is for upper-layer clients after IFUP. Static settings
; already arrive parsed through LOAD_ENV_CONFIG. In DHCP mode it additionally
; requires the lease fields published by IFUP and parses those exact values.
; This keeps IFUP's pre-acquire path unchanged while allowing PING to use the
; same public NET_* environment in either mode.
LOAD_ACTIVE_CONFIG
	PUSH	IX,IY
	CALL	LOAD_ENV_CONFIG
	JR	C,.ACTIVE_FAIL
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_LOCAL
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.ACTIVE_OK
	LD	HL,E_IP
	LD	DE,NCV_IP
	LD	B,NCV_IP_CAP
	CALL	GET_REQUIRED
	JR	C,.ACTIVE_FAIL
	LD	HL,E_MASK
	LD	DE,NCV_MASK
	LD	B,NCV_MASK_CAP
	CALL	GET_REQUIRED
	JR	C,.ACTIVE_FAIL
	LD	HL,E_GW
	LD	DE,NCV_GW
	LD	B,NCV_GW_CAP
	CALL	GET_OPTIONAL
	JR	C,.ACTIVE_FAIL
	LD	HL,NCV_IP
	LD	DE,NET_LOCAL_IP
	CALL	@NETPARSE.PARSE_IPV4
	JR	C,.ACTIVE_FAIL
	LD	HL,NCV_MASK
	LD	DE,NET_NETMASK
	CALL	@NETPARSE.PARSE_IPV4
	JR	C,.ACTIVE_FAIL
	LD	HL,NCV_GW
	LD	A,(HL)
	OR	A
	JR	Z,.ZERO_GATEWAY
	LD	DE,NET_GATEWAY
	CALL	@NETPARSE.PARSE_IPV4
	JR	C,.ACTIVE_FAIL
	JR	.ACTIVE_OK
.ZERO_GATEWAY
	LD	HL,0
	LD	(NET_GATEWAY),HL
	LD	(NET_GATEWAY+2),HL
.ACTIVE_OK
	XOR	A
	POP	IY,IX
	RET
.ACTIVE_FAIL
	LD	A,NETDRV_ERR_CONFIG
	SCF
	POP	IY,IX
	RET
GET_REQUIRED
	LD	(S7APP_ENV_DEST),DE
	LD	A,B
	LD	(S7APP_ENV_CAPACITY),A
	PUSH	HL
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.GET
	POP	HL
	OR	A
	JR	Z,.BAD
	LD	A,(ENV_SET_BUFFER)
	OR	A
	JR	Z,.BAD
	JR	COPY_ENV_VALUE
.BAD
	SCF
	RET

GET_OPTIONAL
	LD	(S7APP_ENV_DEST),DE
	LD	A,B
	LD	(S7APP_ENV_CAPACITY),A
	PUSH	HL
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.GET
	POP	HL
	OR	A
	JR	NZ,COPY_ENV_VALUE
	LD	DE,(S7APP_ENV_DEST)
	XOR	A
	LD	(DE),A
	RET

; Copy one DSS environment value from the 300-byte shared scratch into its
; normalized field. Capacity includes the terminator; oversized values fail
; before touching the next field.
COPY_ENV_VALUE
	LD	HL,ENV_SET_BUFFER
	LD	DE,(S7APP_ENV_DEST)
	LD	A,(S7APP_ENV_CAPACITY)
	LD	B,A
.COPY
	LD	A,(HL)
	OR	A
	JR	Z,.TERM
	LD	C,A
	LD	A,B
	CP	2
	JR	C,.TOO_LONG
	LD	A,C
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	JR	.COPY
.TERM
	LD	(DE),A
	OR	A
	RET
.TOO_LONG
	LD	A,NETDRV_ERR_CONFIG
	SCF
	RET

; Returns B=current seconds 0..59; DSS_SYSTIME is called with ISA closed.
SECONDS
	PUSH	IX,IY
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,B
	POP	IY,IX
	RET

; WAIT_TICK is a short backend-independent polling yield. Wall-clock timeout
; decisions remain based on DSS SYSTIME; this loop only avoids hammering DSS.
; Out: A=0/CF=0. Clobbers BC; preserves IX/IY.
WAIT_TICK
	PUSH	IX,IY
	LD	BC,NETTIME_TICK_LOOP
.TICK_LOOP
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.TICK_LOOP
	XOR	A
	POP	IY,IX
	RET

; WAIT_SECOND_EDGE
; Align a wire timeout with the next DSS wall-clock second so an N-second
; comparison cannot lose the fractional first second. The alignment itself is
; bounded even if the RTC stops. ISA must be closed.
; Out: A=0/CF=0 at an edge; EL3_ERR_TIMER/CF=1 after the finite guard.
WAIT_SECOND_EDGE
	PUSH	IX,IY
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,B
	LD	(EDGE_SECOND),A
	LD	HL,2000
	LD	(EDGE_TICKS_LEFT),HL
.EDGE_POLL
	CALL	WAIT_TICK
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,(EDGE_SECOND)
	CP	B
	JR	NZ,.EDGE_OK
	LD	HL,(EDGE_TICKS_LEFT)
	DEC	HL
	LD	(EDGE_TICKS_LEFT),HL
	LD	A,H
	OR	L
	JR	NZ,.EDGE_POLL
	LD	A,EL3_ERR_TIMER
	SCF
	POP	IY,IX
	RET
.EDGE_OK
	XOR	A
	POP	IY,IX
	RET

EDGE_SECOND	DB 0
EDGE_TICKS_LEFT DW 0

E_NET		DB "NET",0
E_HW		DB "NET_HW",0
E_IDPORT	DB "NET_IDPORT",0
E_MAC		DB "NET_MAC",0
E_IP_SRC	DB "NET_IP_SRC",0
E_IP		DB "NET_IP",0
E_MASK		DB "NET_MASK",0
E_GW		DB "NET_GW",0
E_DNS1		DB "NET_DNS1",0
E_DNS2		DB "NET_DNS2",0
E_NTP		DB "NET_NTP",0
E_TZ		DB "NET_TZ",0
VALUE_DHCP_LOCAL DB "DHCP",0
VALUE_STATIC_LOCAL DB "STATIC",0
S7APP_ENV_DEST DW 0
S7APP_ENV_CAPACITY DB 0

	ENDMODULE
	ENDIF
