; Compact Stage 9 environment loader, allocation and fail-safe cleanup.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_STAGE9_APP_ASM
	DEFINE	_STAGE9_APP_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"
	IFDEF	UNET_DLL
	INCLUDE "coldctx.inc"
	ENDIF

	MODULE S9APP

CLEAR
	XOR	A
	LD	(NETDRV_ACTIVE),A
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	(NETDRV_FAIL_CODE),A
	LD	(NETDRV_SELECTED_SLOT),A
	LD	(S9_TFTP_FILE_OPEN),A
	LD	A,0xFF
	LD	(NETDRV_MEMORY_BLOCK),A
	LD	(S9_TFTP_FILE_HANDLE),A
	RET

	IFNDEF STAGE12_LAYOUT	; WGET uses S11APP.ALLOCATE_FRESH, which maps WIN2
ALLOCATE
	PUSH	IX,IY
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JR	C,.FAIL
	LD	(NETDRV_MEMORY_BLOCK),A
	LD	A,1
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	A,(NETDRV_MEMORY_BLOCK)
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	JR	C,.FAIL
	XOR	A
	POP	IY,IX
	RET
.FAIL
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	POP	IY,IX
	RET
	ENDIF

INIT_DRIVER
	LD	HL,NETDRV_CONFIG
	JP	@NETDRV.INIT

SECONDS
	PUSH	IX,IY
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,B
	POP	IY,IX
	RET

WAIT_TICK
	LD	BC,NETTIME_TICK_LOOP
.TICK
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.TICK
	XOR	A
	RET

; CLEANUP closes a TFTP file first, then NETDRV and the DSS page. In A is the
; primary status; a later cleanup error is used only when the primary is zero.
	IFNDEF STAGE12_LAYOUT
CLEANUP
	PUSH	IX,IY
	LD	(NETDRV_FAIL_CODE),A
	LD	A,(S9_TFTP_FILE_OPEN)
	OR	A
	JR	Z,.DRIVER
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	JR	NC,.FILE_CLOSED
	LD	B,A
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	NZ,.FILE_CLOSED
	LD	A,NETDRV_ERR_FILE_IO
	LD	(NETDRV_FAIL_CODE),A
.FILE_CLOSED
	XOR	A
	LD	(S9_TFTP_FILE_OPEN),A
.DRIVER
	CALL	@NETDRV.DONE
	JR	NC,.FREE
	LD	B,A
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	NZ,.FREE
	LD	A,B
	LD	(NETDRV_FAIL_CODE),A
.FREE
	LD	A,(NETDRV_PAGE_ALLOCATED)
	OR	A
	JR	Z,.RETURN
	LD	A,(NETDRV_MEMORY_BLOCK)
	LD	C,DSS_FREEMEM
	RST	DSS
	JR	NC,.FREED
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	NZ,.FREED
	LD	A,EL3_ERR_NO_MEMORY
	LD	(NETDRV_FAIL_CODE),A
.FREED
	XOR	A
	LD	(NETDRV_PAGE_ALLOCATED),A
.RETURN
	LD	A,(NETDRV_FAIL_CODE)
	OR	A
	JR	Z,.OK
	SCF
	POP	IY,IX
	RET
.OK
	XOR	A
	POP	IY,IX
	RET
	ENDIF

; LOAD_ACTIVE_CONFIG reads only the public NET_* environment. All parsing is
; bounded and no card/ISA access occurs here.
LOAD_ACTIVE_CONFIG
	PUSH	IX,IY
	LD	HL,NETDRV_CONFIG
	LD	B,NETDRV_CONFIG_LENGTH
	XOR	A
.ZERO_CFG
	LD	(HL),A
	INC	HL
	DJNZ	.ZERO_CFG
	LD	A,NETDRV_CONFIG_VERSION
	LD	(NETDRV_CONFIG+NETDRV_CFG_VERSION),A
	LD	A,NETDRV_CONFIG_LENGTH
	LD	(NETDRV_CONFIG+NETDRV_CFG_LENGTH),A
	LD	HL,E_NET
	CALL	GET_REQUIRED
	JP	C,.BAD
	LD	DE,V_509B
	CALL	STR_EQ_CI
	JP	NZ,.BAD
	LD	HL,E_HW
	CALL	GET_REQUIRED
	JP	C,.BAD
	LD	DE,V_AUTO
	CALL	STR_EQ_CI
	JR	NZ,.EXPLICIT_HW
	XOR	A
	LD	(NETDRV_CONFIG+NETDRV_CFG_MODE),A
	JR	.IDPORT
.EXPLICIT_HW
	CALL	PARSE_HW
	JP	C,.BAD
.IDPORT
	LD	HL,E_IDPORT
	CALL	GET_REQUIRED
	JP	C,.BAD
	CALL	PARSE_HASH
	JP	C,.BAD
	LD	A,H
	CP	1
	JP	NZ,.BAD
	LD	A,L
	AND	0x0F
	JP	NZ,.BAD
	LD	A,L
	CP	0xF1
	JP	NC,.BAD
	LD	(NETDRV_CONFIG+NETDRV_CFG_IDPORT),HL
	LD	HL,E_MAC
	CALL	GET_OPTIONAL
	JP	C,.BAD
	LD	A,(S9_ENV_BUFFER)
	OR	A
	JR	Z,.IP
	LD	HL,S9_ENV_BUFFER
	LD	DE,NETDRV_CONFIG+NETDRV_CFG_MAC
	CALL	PARSE_MAC
	JP	C,.BAD
	LD	A,NETDRV_MAC_OVERRIDE
	LD	(NETDRV_CONFIG+NETDRV_CFG_MAC_FLAGS),A
.IP
	LD	HL,E_IP
	CALL	GET_REQUIRED
	JP	C,.BAD
	LD	HL,S9_ENV_BUFFER
	LD	DE,NET_LOCAL_IP
	CALL	PARSE_IPV4
	JP	C,.BAD
	LD	HL,E_MASK
	CALL	GET_REQUIRED
	JP	C,.BAD
	LD	HL,S9_ENV_BUFFER
	LD	DE,NET_NETMASK
	CALL	PARSE_IPV4
	JP	C,.BAD
	LD	HL,E_GW
	CALL	GET_OPTIONAL
	JP	C,.BAD
	LD	A,(S9_ENV_BUFFER)
	OR	A
	JR	Z,.ZERO_GW
	LD	HL,S9_ENV_BUFFER
	LD	DE,NET_GATEWAY
	CALL	PARSE_IPV4
	JP	C,.BAD
	JR	.DNS
.ZERO_GW
	LD	HL,0
	LD	(NET_GATEWAY),HL
	LD	(NET_GATEWAY+2),HL
.DNS
	LD	HL,E_DNS1
	CALL	GET_OPTIONAL
	JP	C,.BAD
	LD	HL,S9_ENV_BUFFER
	LD	DE,NET_DNS1
	CALL	PARSE_OPTIONAL_ACTIVE_IP
	JP	C,.BAD
	LD	HL,E_DNS2
	CALL	GET_OPTIONAL
	JP	C,.BAD
	LD	HL,S9_ENV_BUFFER
	LD	DE,NET_DNS2
	CALL	PARSE_OPTIONAL_ACTIVE_IP
	JP	C,.BAD
.DONE
	XOR	A
	POP	IY,IX
	RET
	; Keep the LOAD_ACTIVE_CONFIG local error label before the next public
	; routine so sjasmplus local-label scoping remains explicit.
.BAD
	LD	A,NETDRV_ERR_CONFIG
	SCF
	POP	IY,IX
	RET

; HL=optional normalized text, DE=four-byte destination.
PARSE_OPTIONAL_ACTIVE_IP
	LD	A,(HL)
	OR	A
	JR	NZ,.PO_PARSE
	EX	DE,HL
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	RET
.PO_PARSE
	JP	PARSE_IPV4

GET_REQUIRED
	LD	DE,S9_ENV_BUFFER
	LD	B,ENV_GET
	LD	C,DSS_ENVIRON
	RST	DSS
	RET	C
	OR	A
	JR	Z,.GET_BAD
	LD	HL,S9_ENV_BUFFER
	LD	A,(HL)
	OR	A
	RET	NZ
.GET_BAD
	SCF
	RET

GET_OPTIONAL
	LD	DE,S9_ENV_BUFFER
	LD	B,ENV_GET
	LD	C,DSS_ENVIRON
	RST	DSS
	RET	C
	OR	A
	RET	NZ
	LD	(S9_ENV_BUFFER),A
	RET

; Case-insensitive ASCIIZ equality. HL/DE strings, Z on equal.
STR_EQ_CI
	LD	A,(DE)
	CALL	UPPER
	LD	B,A
	LD	A,(HL)
	CALL	UPPER
	CP	B
	RET	NZ
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	STR_EQ_CI

UPPER
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	SUB	'a'-'A'
	RET

PARSE_HW
	IFDEF	UNET_DLL
; Moved to the cold overlay (unet509b_cold.asm, CFN_PARSE_HW) along with
; its own copy of @EL3ALG.BASE_ENCODE (hot-only, so duplicated rather than
; called across the cold/hot boundary). This stub keeps the NETDRV_CONFIG
; writes, since those are fixed hot addresses cold code cannot reference.
	LD	HL,S9_ENV_BUFFER
	LD	A,CFN_PARSE_HW
	CALL	@COLD.RUN
	RET	C
	LD	(NETDRV_CONFIG+NETDRV_CFG_SLOT),A
	LD	(NETDRV_CONFIG+NETDRV_CFG_BASE),HL
	LD	A,NETDRV_MODE_EXPLICIT
	LD	(NETDRV_CONFIG+NETDRV_CFG_MODE),A
	OR	A
	RET
	ELSE
	LD	HL,S9_ENV_BUFFER
	LD	A,(HL)
	CP	'0'
	JR	Z,.SLOT0
	CP	'1'
	JR	NZ,.HW_BAD
	LD	A,1
	JR	.SLOT
.SLOT0
	XOR	A
.SLOT
	LD	(NETDRV_CONFIG+NETDRV_CFG_SLOT),A
	INC	HL
	LD	A,(HL)
	CP	'/'
	JR	NZ,.HW_BAD
	INC	HL
	CALL	PARSE_HASH_AT
	JR	C,.HW_BAD
	PUSH	HL
	CALL	@EL3ALG.BASE_ENCODE
	POP	HL
	JR	C,.HW_BAD
	LD	(NETDRV_CONFIG+NETDRV_CFG_BASE),HL
	LD	A,NETDRV_MODE_EXPLICIT
	LD	(NETDRV_CONFIG+NETDRV_CFG_MODE),A
	OR	A
	RET
.HW_BAD
	SCF
	RET
	ENDIF

PARSE_HASH
	LD	HL,S9_ENV_BUFFER
PARSE_HASH_AT
	IFDEF	UNET_DLL
; Moved to the cold overlay (unet509b_cold.asm's PARSE_U16, CFN_PARSE_U16)
; -- pure register logic, only S9_ENV_BUFFER's address (a plain literal,
; not a fixed-address dependency inside the parser itself) ties it to the
; hot image, and that lives in the PARSE_HASH stub above, not here.
	LD	A,CFN_PARSE_U16
	JP	@COLD.RUN
	ELSE
	LD	A,(HL)
	CP	'#'
	JR	NZ,.HASH_BAD
	INC	HL
	LD	DE,0
	LD	B,0
.HEX
	LD	A,(HL)
	OR	A
	JR	Z,.HEX_DONE
	CALL	HEX_NIBBLE
	JR	C,.HASH_BAD
	LD	C,A
	LD	A,D
	AND	0xF0
	JR	NZ,.HASH_BAD
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	LD	A,E
	OR	C
	LD	E,A
	INC	HL
	INC	B
	LD	A,B
	CP	5
	JR	C,.HEX
.HASH_BAD
	SCF
	RET
.HEX_DONE
	LD	A,B
	OR	A
	JR	Z,.HASH_BAD
	EX	DE,HL
	OR	A
	RET
	ENDIF

	IFNDEF	UNET_DLL
HEX_NIBBLE
	CP	'0'
	JR	C,.NIB_BAD
	CP	'9'+1
	JR	C,.NIB_DEC
	CALL	UPPER
	CP	'A'
	JR	C,.NIB_BAD
	CP	'F'+1
	JR	NC,.NIB_BAD
	SUB	'A'-10
	OR	A
	RET
.NIB_DEC
	SUB	'0'
	OR	A
	RET
.NIB_BAD
	SCF
	RET
	ENDIF

; PARSE_MAC: HL=hex string (colon-separated), DE=6-byte output.
PARSE_MAC
	IFDEF	UNET_DLL
; Moved to the cold overlay (unet509b_cold.asm, CFN_PARSE_MAC) -- pure
; register logic, no memory.inc dependency of its own.
	LD	A,CFN_PARSE_MAC
	JP	@COLD.RUN
	ELSE
	LD	B,6
.MAC_BYTE
	LD	A,(HL)
	CALL	HEX_NIBBLE
	RET	C
	RLCA
	RLCA
	RLCA
	RLCA
	LD	C,A
	INC	HL
	LD	A,(HL)
	CALL	HEX_NIBBLE
	RET	C
	OR	C
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	JR	Z,.MAC_END
	LD	A,(HL)
	CP	':'
	JR	NZ,.MAC_BAD
	INC	HL
	JR	.MAC_BYTE
.MAC_END
	LD	A,(HL)
	OR	A
	RET	Z
.MAC_BAD
	SCF
	RET
	ENDIF

; Strict dotted IPv4. Rejects missing fields, overflow and trailing bytes.
; HL=ASCIIZ text, DE=4-byte output.
PARSE_IPV4
	IFDEF	UNET_DLL
; Moved to the cold overlay (unet509b_cold.asm, CFN_PARSE_IPV4): the ORIGINAL
; body below uses S9_FLAGS/S9_PRIMARY_ERROR/S9_RX_LENGTH as scratch, all
; fixed hot addresses a cold function cannot reference, so the cold copy
; reworks that scratch onto IX/IY (see its own header comment) instead --
; same algorithm, byte-identical accept/reject behaviour.
	LD	A,CFN_PARSE_IPV4
	JP	@COLD.RUN
	ELSE
	LD	B,4
.IP_FIELD
	LD	C,0
	LD	A,0
	LD	(S9_PRIMARY_ERROR),A	; digit count scratch
.IP_DIGIT
	LD	A,(HL)
	CP	'0'
	JR	C,.IP_END_FIELD
	CP	'9'+1
	JR	NC,.IP_END_FIELD
	SUB	'0'
	LD	(S9_FLAGS),A
	LD	A,C
	CP	26
	JR	NC,.IP_BAD
	ADD	A,A
	LD	(S9_RX_LENGTH),A	; old value times two
	ADD	A,A
	ADD	A,A
	LD	C,A			; old value times eight
	LD	A,(S9_RX_LENGTH)
	ADD	A,C
	LD	C,A
	LD	A,(S9_FLAGS)
	ADD	A,C
	JR	C,.IP_BAD
	LD	C,A
	LD	A,(S9_PRIMARY_ERROR)
	INC	A
	LD	(S9_PRIMARY_ERROR),A
	CP	4
	JR	NC,.IP_BAD
	INC	HL
	JR	.IP_DIGIT
.IP_END_FIELD
	LD	A,(S9_PRIMARY_ERROR)
	OR	A
	JR	Z,.IP_BAD
	LD	A,C
	LD	(DE),A
	INC	DE
	DEC	B
	JR	Z,.IP_TERM
	LD	A,(HL)
	CP	'.'
	JR	NZ,.IP_BAD
	INC	HL
	JR	.IP_FIELD
.IP_TERM
	LD	A,(HL)
	OR	A
	RET	Z
.IP_BAD
	SCF
	RET
	ENDIF

E_NET		DB "NET",0
E_HW		DB "NET_HW",0
E_IDPORT	DB "NET_IDPORT",0
E_MAC		DB "NET_MAC",0
E_IP		DB "NET_IP",0
E_MASK		DB "NET_MASK",0
E_GW		DB "NET_GW",0
E_DNS1		DB "NET_DNS1",0
E_DNS2		DB "NET_DNS2",0
V_509B		DB "509B",0
V_AUTO		DB "AUTO",0

	ENDMODULE

; NETTIME predates Stage 9 and calls the Stage 7 wait-yield symbol. Stage 9
; provides the same bounded primitive without pulling in the larger S7 loader.
	MODULE S7APP
WAIT_TICK
	JP	@S9APP.WAIT_TICK
	ENDMODULE
	ENDIF
