; Stage 10 page bootstrap and bounded DNS resolver over UDPX.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_STAGE10_APP_ASM
	DEFINE	_STAGE10_APP_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "dns_ntp.inc"

	MODULE S10APP

; SAVE_COMMAND must run before WIN1 is remapped. It copies the DSS length byte
; and at most 255 command bytes into fixed ordinary RAM below C000h.
; In: IX=DSS command record. Out: IX=S10_COMMAND_BUFFER. Preserves IY.
SAVE_COMMAND
	PUSH	IY
	PUSH	IX
	POP	HL
	LD	A,(HL)
	LD	C,A
	LD	B,0
	INC	BC
	LD	DE,S10_COMMAND_BUFFER
	LDIR
	LD	IX,S10_COMMAND_BUFFER
	POP	IY
	RET

; ALLOCATE_FRESH allocates/maps the one DSS page before any page-backed state
; is touched. Out: IX=S10_PAGE_COMMAND_BUFFER. Preserves IY. A failed SETWIN1
; releases the just-allocated block.
ALLOCATE_FRESH
	PUSH	IY
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JR	C,.AF_FAIL
	LD	E,A
	PUSH	DE
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	POP	DE
	JR	C,.AF_SET_FAIL
	CALL	@S9APP.CLEAR
	LD	A,E
	LD	(NETDRV_MEMORY_BLOCK),A
	LD	A,1
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	HL,S10_COMMAND_BUFFER
	LD	A,(HL)
	LD	C,A
	LD	B,0
	INC	BC
	LD	DE,S10_PAGE_COMMAND_BUFFER
	LDIR
	LD	IX,S10_PAGE_COMMAND_BUFFER
	XOR	A
	POP	IY
	RET
.AF_SET_FAIL
	PUSH	AF
	LD	A,E
	LD	C,DSS_FREEMEM
	RST	DSS
	POP	AF
.AF_FAIL
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	POP	IY
	RET

	ENDMODULE

	MODULE DNSX

; RESOLVE_OR_LITERAL
; In HL=hostname or dotted IPv4. Out NET_TARGET_IP and CF/status. DNS_EXPLICIT
; selects the single caller-provided DNS_EXPLICIT_SERVER. IX/IY preserved.
RESOLVE_OR_LITERAL
	PUSH	IX,IY
	LD	(DNS_NAME_POINTER),HL
	LD	DE,DNS_RESULT_IP
	CALL	@S9APP.PARSE_IPV4
	JR	C,.ROL_DNS
	CALL	COPY_RESULT
	XOR	A
	POP	IY,IX
	RET
.ROL_DNS
	LD	HL,(DNS_NAME_POINTER)
	CALL	RESOLVE
	POP	IY,IX
	RET

; RESOLVE performs three 5000 ms attempts per configured server. Malformed,
; unreachable, timeout and temporary/no-answer results advance to DNS2;
; NXDOMAIN and cancellation are final. Stale IDs remain inside one deadline.
RESOLVE
	PUSH	IX,IY
	LD	(DNS_NAME_POINTER),HL
	CALL	@DNS.VALIDATE_NAME
	JP	C,.RX_RETURN
	LD	A,NETDRV_ERR_CONFIG
	LD	(DNS_LAST_ERROR),A
	CALL	GENERATE_ID
	LD	A,(DNS_EXPLICIT_FLAG)
	OR	A
	JR	Z,.RX_PRIMARY
	LD	HL,DNS_EXPLICIT_SERVER
	JR	.RX_SERVER
.RX_PRIMARY
	XOR	A
	LD	(DNS_SERVER_INDEX),A
	LD	HL,NET_DNS1
.RX_SERVER
	CALL	IP_NONZERO
	JR	NZ,.RX_HAVE_SERVER
	LD	A,(DNS_SERVER_INDEX)
	OR	A
	JP	NZ,.RX_LAST
	LD	A,NETDRV_ERR_CONFIG
	JP	.RX_FALLBACK
.RX_HAVE_SERVER
	LD	DE,DNS_USED_SERVER
	CALL	COPY4
	LD	HL,DNS_USED_SERVER
	LD	DE,NET_TARGET_IP
	CALL	COPY4
	LD	BC,DNS_PORT
	LD	HL,(DNS_TRANSACTION_ID)
	LD	A,H
	AND	0x0F
	OR	0xD0
	LD	D,A
	LD	E,L
	LD	HL,NET_TARGET_IP
	CALL	@UDPX.OPEN
	JR	C,.RX_SERVER_ERROR
	CALL	BUILD_QUERY
	JP	C,.RX_RETURN
	LD	A,3
	LD	(DNS_ATTEMPTS),A
.RX_TRY
	LD	BC,(DNS_QUERY_DESC+DNSQB_LENGTH)
	CALL	@UDPX.SEND
	JP	C,.RX_RETURN
	LD	BC,5000
	CALL	@UDPX.WAIT
.RX_REPLY
	JR	C,.RX_WAIT_ERROR
	LD	(DNS_PARSE_DESC+DNSP_BUFFER),HL
	LD	(DNS_PARSE_DESC+DNSP_LENGTH),BC
	LD	HL,(DNS_TRANSACTION_ID)
	LD	(DNS_PARSE_DESC+DNSP_XID),HL
	LD	HL,DNS_RESULT_IP
	LD	(DNS_PARSE_DESC+DNSP_RESULT),HL
	LD	HL,DNS_PARSE_DESC
	CALL	@DNS.PARSE_REPLY
	JR	NC,.RX_SUCCESS
	CP	NETDRV_ERR_PARAMETER
	JR	NZ,.RX_PARSED_ERROR
	CALL	@UDPX.WAIT_CONTINUE
	JR	.RX_REPLY
.RX_PARSED_ERROR
	CP	NETDRV_ERR_DNS_NXDOMAIN
	JP	Z,.RX_ERROR_RETURN
	JR	.RX_FALLBACK
.RX_WAIT_ERROR
	CP	NETDRV_ERR_CANCELLED
	JP	Z,.RX_ERROR_RETURN
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.RX_FALLBACK
	LD	A,(DNS_ATTEMPTS)
	DEC	A
	LD	(DNS_ATTEMPTS),A
	JR	NZ,.RX_TRY
	LD	A,EL3_ERR_RX_TIMEOUT
.RX_FALLBACK
	LD	(DNS_LAST_ERROR),A
	LD	A,(DNS_EXPLICIT_FLAG)
	OR	A
	JR	NZ,.RX_LAST
	LD	A,(DNS_SERVER_INDEX)
	OR	A
	JR	NZ,.RX_LAST
	INC	A
	LD	(DNS_SERVER_INDEX),A
	LD	HL,NET_DNS2
	JP	.RX_SERVER
.RX_SERVER_ERROR
	CP	NETDRV_ERR_CANCELLED
	JP	Z,.RX_ERROR_RETURN
	JR	.RX_FALLBACK
.RX_LAST
	LD	A,(DNS_LAST_ERROR)
	SCF
	JR	.RX_RETURN
.RX_SUCCESS
	CALL	COPY_RESULT
	XOR	A
	JR	.RX_RETURN
.RX_ERROR_RETURN
	SCF
.RX_RETURN
	POP	IY,IX
	RET

BUILD_QUERY
	LD	HL,STAGE9_TX_BUFFER+42
	LD	(DNS_QUERY_DESC+DNSQB_BUFFER),HL
	LD	HL,UDP_MAX_PAYLOAD
	LD	(DNS_QUERY_DESC+DNSQB_CAPACITY),HL
	LD	HL,(DNS_NAME_POINTER)
	LD	(DNS_QUERY_DESC+DNSQB_NAME),HL
	LD	HL,(DNS_TRANSACTION_ID)
	LD	(DNS_QUERY_DESC+DNSQB_XID),HL
	LD	HL,DNS_QUERY_DESC
	JP	@DNS.BUILD_QUERY

GENERATE_ID
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,H
	XOR	B
	LD	L,A
	LD	A,R
	XOR	L
	LD	H,A
	LD	A,H
	OR	L
	JR	NZ,.GI_OK
	INC	HL
.GI_OK
	LD	(DNS_TRANSACTION_ID),HL
	RET

COPY_RESULT
	LD	HL,DNS_RESULT_IP
	LD	DE,NET_TARGET_IP
COPY4
	LD	BC,4
	LDIR
	RET

IP_NONZERO
	PUSH	HL
	LD	B,4
	XOR	A
.IN_LOOP
	OR	(HL)
	INC	HL
	DJNZ	.IN_LOOP
	POP	HL
	RET

	ENDMODULE
	ENDIF
