; Compact bounded DNS A resolver for WGET. Reuses the Stage 10 DNS/UDP codecs
; and the Stage 11 ARP route machinery without linking the generic UDP client.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF _STAGE12_DNS_ASM
	DEFINE _STAGE12_DNS_ASM

	MODULE DNSX

DNS_LOCAL_PORT	EQU 0xD035
DNS_TIMEOUT_MS	EQU 5000

; The query frame is built before anything has been received this attempt
; (RX is idle at that point, same reasoning as UDPX_TX_BUFFER/TCPX_TX_BUFFER),
; so for UNET_DLL and DLDIRECT (TCPX_SHARED_TX) it reuses the RX buffer instead
; of a dedicated reservation.
	IFDEF	UNET_DLL
	IFNDEF	TCPX_SHARED_TX
	DEFINE	TCPX_SHARED_TX
	ENDIF
	ENDIF
	IFDEF	TCPX_SHARED_TX
DNSX_TX_BUFFER		EQU STAGE9_RX_BUFFER
DNSX_TX_CAPACITY	EQU STAGE9_RX_CAPACITY
	ELSE
DNSX_TX_BUFFER		EQU STAGE9_TX_BUFFER
DNSX_TX_CAPACITY	EQU STAGE9_TX_CAPACITY
	ENDIF

	IFDEF	UNET_DLL
; Shared tail for this module's cold trampolines below (BUILD_QUERY,
; PARSE_DNS_REPLY, BUILD_FRAME, PARSE_REPLY_FRAME): JP, not CALL, so the
; original caller's own return address (from its CALL BUILD_FRAME etc.)
; stays on the stack all the way through to COLD.RUN's RET.
DNS_COLD_CALL
	LD	IX,UNET_COLD_CTX
	JP	@COLD.RUN
	ENDIF

RESOLVE_OR_LITERAL
	PUSH	IX,IY
	LD	(DNS_NAME_POINTER),HL
	LD	DE,DNS_RESULT_IP
	CALL	@S9APP.PARSE_IPV4
	JP	NC,.SUCCESS
.NAME
	LD	HL,(DNS_NAME_POINTER)
	CALL	VALIDATE_NAME
	JP	C,.RETURN
	CALL	GENERATE_ID
	; Every .LAST exit reports DNS_LAST_ERROR; the "no server configured"
	; path reaches it without writing one first.
	LD	A,NETDRV_ERR_CONFIG
	LD	(DNS_LAST_ERROR),A
	XOR	A
	LD	(DNS_SERVER_INDEX),A
.SERVER
	LD	HL,NET_DNS1
	LD	A,(DNS_SERVER_INDEX)
	OR	A
	JR	Z,.SERVER_PTR
	LD	HL,NET_DNS2
.SERVER_PTR
	CALL	NONZERO_IP
	JP	Z,.NEXT_SERVER
	LD	DE,NET_TARGET_IP
	CALL	COPY4
	; RESOLVE_ROUTE operates on the context selected by IX.  A dedicated
	; scratch context keeps this route resolve from corrupting a live TCP
	; channel context -- UNET_DLL uses S11_CONTEXT_SCRATCH (channels 0/1
	; are real, in-use connections there); the standalone WGET client has
	; no such conflict and keeps using channel 0's own context, as before.
	IFDEF	UNET_DLL
	LD	IX,S11_CONTEXT_SCRATCH
	LD	HL,NET_TARGET_IP
	LD	DE,S11_CONTEXT_SCRATCH+1
	ELSE
	LD	IX,S11_CONTEXT0
	LD	HL,NET_TARGET_IP
	LD	DE,S11_CONTEXT0+1
	ENDIF
	CALL	COPY4
	IFDEF	UNET_DLL
	LD	IX,S11_CONTEXT_SCRATCH
	ELSE
	LD	IX,S11_CONTEXT0
	ENDIF
	CALL	@TCPX.RESOLVE_ROUTE
	JP	C,.SERVER_ERROR
	LD	A,3
	LD	(DNS_ATTEMPTS),A
.TRY
	CALL	BUILD_FRAME
	JP	C,.RETURN
	LD	HL,DNSX_TX_BUFFER
	LD	BC,(S9_RX_LENGTH)
	CALL	@NETDRV.SEND_FRAME
	JP	C,.RETURN
	LD	BC,DNS_TIMEOUT_MS
	CALL	@NETTIME.START
	JP	C,.RETURN
.WAIT
	CALL	@TCPX.CHECK_CANCEL
	JP	C,.RETURN
	CALL	@NETDRV.RX_PENDING
	JR	C,.RETURN
	OR	A
	JR	Z,.TICK
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,STAGE9_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	C,.READ_ERROR
	; PROCESS_ARP below reads the length from this cell, and a freshly
	; mapped DSS page leaves it holding arbitrary bytes. Nothing between
	; here and PARSE_REPLY_FRAME writes it, so one store serves both.
	LD	(S11_FRAME_LENGTH),BC
	LD	A,(STAGE9_RX_BUFFER+12)
	CP	0x08
	JR	NZ,.TICK
	LD	A,(STAGE9_RX_BUFFER+13)
	CP	0x06
	JR	NZ,.IPV4
	CALL	@TCPX.PROCESS_ARP
	JR	C,.RETURN
	JR	.TICK
.IPV4
	OR	A
	JR	NZ,.TICK
	CALL	PARSE_REPLY_FRAME
	JR	NC,.SUCCESS
	CP	NETDRV_ERR_PARAMETER	; stale XID/noise remains in this deadline
	JR	Z,.TICK
	CP	NETDRV_ERR_DNS_NXDOMAIN
	JR	Z,.RETURN
	LD	(DNS_LAST_ERROR),A
.TICK
	CALL	@NETTIME.TICK
	JR	NC,.WAIT
	LD	A,(DNS_ATTEMPTS)
	DEC	A
	LD	(DNS_ATTEMPTS),A
	JR	NZ,.TRY
	LD	A,EL3_ERR_RX_TIMEOUT
	LD	(DNS_LAST_ERROR),A
.NEXT_SERVER
	LD	A,(DNS_SERVER_INDEX)
	OR	A
	JR	NZ,.LAST
	INC	A
	LD	(DNS_SERVER_INDEX),A
	JP	.SERVER
.SERVER_ERROR
	CP	NETDRV_ERR_CANCELLED
	JR	Z,.RETURN
	LD	(DNS_LAST_ERROR),A
	JR	.NEXT_SERVER
.READ_ERROR
	CP	EL3_ERR_RX_ERROR
	JR	Z,.TICK
	CP	EL3_ERR_FRAME_SIZE
	JR	Z,.TICK
	CP	EL3_ERR_NO_FRAME
	JR	Z,.TICK
	JR	.RETURN
.LAST
	LD	A,(DNS_LAST_ERROR)	; primed with NETDRV_ERR_CONFIG before the loop
	SCF
.RETURN
	POP	IY,IX
	RET
.SUCCESS
	CALL	COPY_RESULT
	XOR	A
	POP	IY,IX
	RET

	IFDEF	UNET_DLL
; Cold: same wire format, reached via CFN_DNS_BUILD_FRAME (unet509b_cold.asm)
; -- every fixed hot address this touches (DNS_NAME_POINTER, NET_LOCAL_IP,
; NET_TARGET_IP, NETDRV_STATION_MAC, NET_RESULT_MAC, S9_IP_ID, S9_RX_LENGTH,
; S9_IPV4_BUILD_DESC) becomes a CCTX_DNS_* dereference instead. IX=&COLD_CTX.
BUILD_FRAME
	LD	A,CFN_DNS_BUILD_FRAME
	JP	DNS_COLD_CALL
	ELSE
BUILD_FRAME
	LD	HL,(DNS_NAME_POINTER)
	LD	DE,DNSX_TX_BUFFER+42
	CALL	BUILD_QUERY
	RET	C
	; Minimal UDP header. A zero checksum is valid for IPv4 and avoids retaining
	; a second packet-codec stack solely for DNS.
	LD	HL,DNSX_TX_BUFFER+34
	LD	(HL),HIGH DNS_LOCAL_PORT
	INC	HL
	LD	(HL),LOW DNS_LOCAL_PORT
	INC	HL
	LD	(HL),0
	INC	HL
	LD	(HL),DNS_PORT
	INC	HL
	PUSH	BC
	LD	DE,8
	LD	H,B
	LD	L,C
	ADD	HL,DE
	LD	D,H
	LD	E,L
	LD	HL,DNSX_TX_BUFFER+38
	LD	(HL),D
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),0
	INC	HL
	LD	(HL),0
	POP	BC
	LD	HL,8
	ADD	HL,BC
	LD	B,H
	LD	C,L
	LD	(S9_IPV4_BUILD_DESC+IP4B_DATA_LENGTH),BC
	LD	HL,DNSX_TX_BUFFER+14
	LD	(S9_IPV4_BUILD_DESC+IP4B_BUFFER),HL
	LD	HL,DNSX_TX_CAPACITY-14
	LD	(S9_IPV4_BUILD_DESC+IP4B_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_IPV4_BUILD_DESC+IP4B_SOURCE),HL
	LD	HL,NET_TARGET_IP
	LD	(S9_IPV4_BUILD_DESC+IP4B_DESTINATION),HL
	LD	HL,(S9_IP_ID)
	INC	HL
	LD	(S9_IP_ID),HL
	LD	(S9_IPV4_BUILD_DESC+IP4B_IDENTIFIER),HL
	LD	A,64
	LD	(S9_IPV4_BUILD_DESC+IP4B_TTL),A
	LD	A,17
	LD	(S9_IPV4_BUILD_DESC+IP4B_PROTOCOL),A
	LD	HL,S9_IPV4_BUILD_DESC
	CALL	@IPV4.BUILD
	RET	C
	; IPV4.BUILD returns the complete IP length in BC. Preserve it before the
	; Ethernet-address LDIR instructions consume BC.
	LD	HL,14
	ADD	HL,BC
	LD	(S9_RX_LENGTH),HL
	LD	HL,NET_RESULT_MAC
	LD	DE,DNSX_TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	XOR	A
	RET
	ENDIF	; UNET_DLL (BUILD_FRAME trampoline above)

	IFDEF	UNET_DLL
; Cold: same wire format, reached via CFN_DNS_PARSE_FRAME (unet509b_cold.asm)
; -- every fixed hot address this touches becomes a CCTX_DNS_* dereference
; instead (see BUILD_FRAME's own header comment). IX=&COLD_CTX.
PARSE_REPLY_FRAME
	LD	A,CFN_DNS_PARSE_FRAME
	JP	DNS_COLD_CALL
	ELSE
PARSE_REPLY_FRAME
	LD	HL,STAGE9_RX_BUFFER+14
	LD	(S9_IPV4_PARSE_DESC+IP4P_BUFFER),HL
	LD	HL,(S11_FRAME_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	LD	(S9_IPV4_PARSE_DESC+IP4P_LENGTH),HL
	LD	HL,NET_TARGET_IP
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_SOURCE),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_DESTINATION),HL
	LD	A,17
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_PROTOCOL),A
	LD	HL,S9_IPV4_PARSE_DESC
	CALL	@IPV4.PARSE
	JR	C,.NOISE
	LD	BC,(S9_IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	A,B
	OR	A
	JR	NZ,.UDP_SIZE
	LD	A,C
	CP	8
	JR	C,.NOISE
.UDP_SIZE
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_DATA)
	LD	A,(HL)
	OR	A
	JR	NZ,.NOISE
	INC	HL
	LD	A,(HL)
	CP	DNS_PORT
	JR	NZ,.NOISE
	INC	HL
	LD	A,(HL)
	CP	HIGH DNS_LOCAL_PORT
	JR	NZ,.NOISE
	INC	HL
	LD	A,(HL)
	CP	LOW DNS_LOCAL_PORT
	JR	NZ,.NOISE
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	A,D
	CP	B
	JR	NZ,.NOISE
	LD	A,E
	CP	C
	JR	NZ,.NOISE		; UDP length must match the parsed IPv4 payload
	LD	A,(HL)
	INC	HL
	OR	(HL)
	INC	HL
	JR	Z,.CHECKSUM_OK		; an omitted UDP checksum is valid for IPv4
	PUSH	BC,HL
	LD	HL,STAGE9_RX_BUFFER+14
	CALL	@ETHERNET.UDP_IPV4_CHECKSUM
	LD	A,H
	OR	L
	POP	HL,BC
	JR	NZ,.NOISE
.CHECKSUM_OK
	LD	A,C
	SUB	8
	LD	C,A
	JR	NC,.PAYLOAD_SIZE
	DEC	B
.PAYLOAD_SIZE
	JP	PARSE_DNS_REPLY
.NOISE
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET
	ENDIF	; UNET_DLL (PARSE_REPLY_FRAME trampoline above)

GENERATE_ID
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,H
	XOR	B
	LD	L,A
	LD	A,R
	XOR	L
	LD	H,A
	LD	A,H
	OR	L
	JR	NZ,.ID_OK
	INC	HL
.ID_OK
	LD	(DNS_TRANSACTION_ID),HL
	RET

	IFDEF	UNET_DLL
; Cold: same copy, reached via CFN_DNS_COPY_RESULT -- DNS_RESULT_IP and
; NET_TARGET_IP are fixed hot addresses, so this dereferences each via its
; own CCTX field instead (both already exist for other DNS/route uses).
COPY_RESULT
	LD	A,CFN_DNS_COPY_RESULT
	JP	DNS_COLD_CALL
	ELSE
COPY_RESULT
	LD	HL,DNS_RESULT_IP
	LD	DE,NET_TARGET_IP
	ENDIF
COPY4
	LD	BC,4
	LDIR
	RET

	IFDEF	UNET_DLL
; Cold: identical body (pure register logic), reached via
; CFN_DNS_NONZERO_IP. No CCTX pointer needed.
NONZERO_IP
	LD	A,CFN_DNS_NONZERO_IP
	JP	DNS_COLD_CALL
	ELSE
NONZERO_IP
	PUSH	HL
	LD	B,4
	XOR	A
.NZ_LOOP
	OR	(HL)
	INC	HL
	DJNZ	.NZ_LOOP
	POP	HL
	RET
	ENDIF

; HL=name. Reject empty/oversize labels and non-printable input.
	IFDEF	UNET_DLL
; Cold: identical body (pure register logic, no hot-address dependency at
; all), reached via CFN_DNS_VALIDATE_NAME. No CCTX pointer needed.
VALIDATE_NAME
	LD	A,CFN_DNS_VALIDATE_NAME
	JP	@COLD.RUN
	ELSE
VALIDATE_NAME
	LD	B,0
	LD	C,0
.VN
	LD	A,(HL)
	OR	A
	JR	Z,.VN_END
	CP	0x21
	JR	C,.VN_BAD
	CP	0x7F
	JR	NC,.VN_BAD
	INC	C
	JR	Z,.VN_BAD
	CP	'.'
	JR	Z,.VN_DOT
	INC	B
	LD	A,B
	CP	64
	JR	NC,.VN_BAD
	INC	HL
	JR	.VN
.VN_DOT
	LD	A,B
	OR	A
	JR	Z,.VN_BAD
	LD	B,0
	INC	C
	INC	HL
	JR	.VN
.VN_END
	LD	A,B
	OR	C			; a single trailing dot terminates a valid prior label
	JR	Z,.VN_BAD
	XOR	A
	RET
.VN_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET
	ENDIF	; UNET_DLL (VALIDATE_NAME trampoline above)

; HL=name, DE=destination. Returns BC=query length.
	IFDEF	UNET_DLL
; Cold: identical body, reached via CFN_DNS_BUILD_QUERY (unet509b_cold.asm)
; -- DNS_TRANSACTION_ID is a fixed hot address, unreachable from cold code
; directly, so the cold copy dereferences it through (IX+CCTX_DNS_XID)
; instead. IX=&COLD_CTX is set by this trampoline; HL/DE pass through.
BUILD_QUERY
	LD	A,CFN_DNS_BUILD_QUERY
	JP	DNS_COLD_CALL
	ELSE
BUILD_QUERY
	PUSH	DE
	LD	BC,(DNS_TRANSACTION_ID)
	LD	A,B
	LD	(DE),A
	INC	DE
	LD	A,C
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	B,6
.BQ_ZERO
	LD	(DE),A
	INC	DE
	DJNZ	.BQ_ZERO
.BQ_LABEL
	PUSH	DE
	INC	DE
	LD	B,0
.BQ_CHAR
	LD	A,(HL)
	OR	A
	JR	Z,.BQ_END
	INC	HL
	CP	'.'
	JR	Z,.BQ_LABEL_END
	LD	(DE),A
	INC	DE
	INC	B
	JR	.BQ_CHAR
.BQ_LABEL_END
	POP	IY
	LD	(IY+0),B
	LD	A,(HL)
	OR	A
	JR	NZ,.BQ_LABEL
	JR	.BQ_ROOT			; trailing dot already ended the final label
.BQ_END
	POP	IY
	LD	(IY+0),B
	XOR	A
.BQ_ROOT
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	POP	HL
	EX	DE,HL
	OR	A
	SBC	HL,DE
	INC	HL
	LD	B,H
	LD	C,L
	XOR	A
	RET
	ENDIF	; UNET_DLL (BUILD_QUERY trampoline above)

	IFNDEF	UNET_DLL
; HL=DNS payload, BC=length. Compressed owner names are skipped safely; the
; first A/IN answer is returned and CNAME/unknown RRs are bounded by RDLENGTH.
PARSE_DNS_REPLY
	LD	D,H
	LD	E,L
	ADD	HL,BC
	LD	(S9_RX_PAYLOAD),HL	; exclusive end
	EX	DE,HL
	LD	A,B
	OR	A
	JR	NZ,.PR_HAVE_HEADER
	LD	A,C
	CP	12
	JP	C,.PR_BAD
.PR_HAVE_HEADER
	LD	BC,(DNS_TRANSACTION_ID)
	LD	A,B
	CP	(HL)
	JP	NZ,.PR_STALE
	INC	HL
	LD	A,C
	CP	(HL)
	JP	NZ,.PR_STALE
	INC	HL
	LD	A,(HL)
	AND	0xFA
	CP	0x80
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	AND	0x0F
	JR	Z,.PR_COUNTS
	CP	3
	LD	A,NETDRV_ERR_DNS_NXDOMAIN
	JP	Z,.PR_ERROR
	JP	.PR_BAD
.PR_COUNTS
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	CP	1
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,.PR_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JR	Z,.PR_NO_ANSWER
	LD	(S9_DRAIN_LEFT),A
	LD	DE,5
	ADD	HL,DE			; skip remaining counts to question name
	CALL	SKIP_DNS_NAME
	JR	C,.PR_BAD
	LD	DE,4
	CALL	ADVANCE_BOUNDED
	JR	C,.PR_BAD
.PR_ANSWER
	CALL	SKIP_DNS_NAME
	JR	C,.PR_BAD
	LD	DE,10
	CALL	ADVANCE_BOUNDED
	JR	C,.PR_BAD
	PUSH	HL
	LD	DE,-10
	ADD	HL,DE
	LD	B,0
	LD	A,(HL)
	OR	A
	JR	NZ,.PR_META
	INC	HL
	LD	A,(HL)
	CP	1
	JR	NZ,.PR_META
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,.PR_META
	INC	HL
	LD	A,(HL)
	CP	1
	JR	NZ,.PR_META
	LD	B,1
.PR_META
	POP	HL			; RDLENGTH is the word immediately before RDATA
	DEC	HL
	LD	E,(HL)
	DEC	HL
	LD	D,(HL)
	INC	HL
	INC	HL
	LD	A,D
	OR	A
	JR	NZ,.PR_SKIP
	LD	A,B
	CP	1
	JR	NZ,.PR_SKIP
	LD	A,E
	CP	4
	JR	NZ,.PR_SKIP
	LD	DE,4
	CALL	ADVANCE_BOUNDED
	JR	C,.PR_BAD
	LD	DE,-4
	ADD	HL,DE
	LD	DE,DNS_RESULT_IP
	LD	BC,4
	LDIR
	XOR	A
	RET
.PR_SKIP
	CALL	ADVANCE_BOUNDED
	JR	C,.PR_BAD
	LD	A,(S9_DRAIN_LEFT)
	DEC	A
	LD	(S9_DRAIN_LEFT),A
	JR	NZ,.PR_ANSWER
.PR_NO_ANSWER
	LD	A,NETDRV_ERR_DNS_NO_ANSWER
	JR	.PR_ERROR
.PR_STALE
	LD	A,NETDRV_ERR_PARAMETER
	JR	.PR_ERROR
.PR_BAD
	LD	A,NETDRV_ERR_PROTOCOL
.PR_ERROR
	SCF
	RET

SKIP_DNS_NAME
	LD	B,64
.SN
	CALL	CHECK_ONE
	RET	C
	LD	A,(HL)
	OR	A
	JR	Z,.ROOT
	LD	C,A
	AND	0xC0
	CP	0xC0
	JR	Z,.POINTER
	LD	A,C
	CP	64
	JR	NC,.BAD_NAME
	LD	E,A
	LD	D,0
	INC	HL
	CALL	ADVANCE_BOUNDED
	RET	C
	DJNZ	.SN
.BAD_NAME
	SCF
	RET
.ROOT
	INC	HL
	OR	A
	RET
.POINTER
	INC	HL
	CALL	CHECK_ONE
	RET	C
	INC	HL
	OR	A
	RET

CHECK_ONE
	PUSH	HL
	LD	DE,(S9_RX_PAYLOAD)
	OR	A
	SBC	HL,DE
	POP	HL
	CCF
	RET

ADVANCE_BOUNDED
	ADD	HL,DE
	JR	C,.AB_BAD
	PUSH	HL
	LD	DE,(S9_RX_PAYLOAD)
	OR	A
	SBC	HL,DE
	POP	HL
	JR	C,.AB_OK
	JR	Z,.AB_OK
.AB_BAD
	SCF
	RET
.AB_OK
	OR	A
	RET
	ENDIF	; UNET_DLL (PARSE_DNS_REPLY/SKIP_DNS_NAME/CHECK_ONE/ADVANCE_BOUNDED above)

	IFDEF	UNET_DLL
; Cold: same body as the IFNDEF branch above, reached via CFN_DNS_PARSE_REPLY
; (unet509b_cold.asm) -- DNS_TRANSACTION_ID/DNS_RESULT_IP/S9_RX_PAYLOAD/
; S9_DRAIN_LEFT are fixed hot addresses, so the cold copy reaches each
; through its own CCTX_DNS_* pointer instead. HL=payload, BC=length pass
; through untouched; IX=&COLD_CTX is set here.
PARSE_DNS_REPLY
	LD	A,CFN_DNS_PARSE_REPLY
	JP	DNS_COLD_CALL
	ENDIF

	ENDMODULE
	ENDIF
