; Strict TCP header codec used by the Stage 11 polling transport.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_TCP_ASM
	DEFINE	_TCP_ASM

	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "tcp.inc"

	MODULE TCP

; BUILD
; In: HL -> TCPB descriptor. Out: BC=TCP segment length, CF/A status.
; The MSS field selects a 24-byte SYN header; otherwise the header is 20 bytes.
; Clobbers AF/BC/DE/HL; preserves IX/IY.
BUILD
	PUSH	IX,IY
	LD	BC,TCPB_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	CALL	VALIDATE_BUILD
	JP	C,.BAD
	LD	E,(IX+TCPB_BUFFER)
	LD	D,(IX+TCPB_BUFFER+1)
	LD	H,(IX+TCPB_SOURCE_PORT+1)
	LD	L,(IX+TCPB_SOURCE_PORT)
	CALL	@ETHERNET.WRITE_BE16
	LD	H,(IX+TCPB_DESTINATION_PORT+1)
	LD	L,(IX+TCPB_DESTINATION_PORT)
	CALL	@ETHERNET.WRITE_BE16
	LD	L,(IX+TCPB_SEQUENCE)
	LD	H,(IX+TCPB_SEQUENCE+1)
	LD	BC,4
	LDIR
	LD	L,(IX+TCPB_ACKNOWLEDGEMENT)
	LD	H,(IX+TCPB_ACKNOWLEDGEMENT+1)
	LD	BC,4
	LDIR
	LD	A,(TCP_HEADER_SIZE)
	SRL	A
	SRL	A
	RLCA
	RLCA
	RLCA
	RLCA
	LD	(DE),A
	INC	DE
	LD	A,(IX+TCPB_FLAGS)
	LD	(DE),A
	INC	DE
	LD	H,(IX+TCPB_WINDOW+1)
	LD	L,(IX+TCPB_WINDOW)
	CALL	@ETHERNET.WRITE_BE16
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	(DE),A			; urgent pointer
	INC	DE
	LD	(DE),A
	LD	HL,(TCP_HEADER_SIZE)
	LD	BC,TCP_SYN_HEADER_LENGTH
	OR	A
	SBC	HL,BC
	JR	NZ,.NO_MSS
	INC	DE
	LD	A,2
	LD	(DE),A
	INC	DE
	LD	A,4
	LD	(DE),A
	INC	DE
	LD	H,(IX+TCPB_MSS+1)
	LD	L,(IX+TCPB_MSS)
	CALL	@ETHERNET.WRITE_BE16
.NO_MSS
	CALL	CHECKSUM_BUILD
	LD	(TCP_CHECKSUM),HL
	LD	E,(IX+TCPB_BUFFER)
	LD	D,(IX+TCPB_BUFFER+1)
	LD	BC,16
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	LD	HL,(TCP_CHECKSUM)
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	LD	BC,(TCP_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

VALIDATE_BUILD
	LD	L,(IX+TCPB_MSS)
	LD	H,(IX+TCPB_MSS+1)
	LD	A,H
	OR	L
	LD	HL,TCP_HEADER_LENGTH
	JR	Z,.HEADER_READY
	LD	HL,TCP_SYN_HEADER_LENGTH
.HEADER_READY
	LD	(TCP_HEADER_SIZE),HL
	LD	E,(IX+TCPB_PAYLOAD_LENGTH)
	LD	D,(IX+TCPB_PAYLOAD_LENGTH+1)
	ADD	HL,DE
	RET	C
	LD	DE,IPV4_MAX_PACKET_LENGTH-IPV4_HEADER_LENGTH+1
	OR	A
	SBC	HL,DE
	JR	NC,.INVALID
	ADD	HL,DE
	LD	(TCP_TOTAL),HL
	LD	E,(IX+TCPB_CAPACITY)
	LD	D,(IX+TCPB_CAPACITY+1)
	OR	A
	SBC	HL,DE
	JR	C,.CAPACITY_OK
	JR	Z,.CAPACITY_OK
	JR	.INVALID
.CAPACITY_OK
	LD	L,(IX+TCPB_BUFFER)
	LD	H,(IX+TCPB_BUFFER+1)
	LD	BC,(TCP_TOTAL)
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPB_SOURCE_IP)
	LD	H,(IX+TCPB_SOURCE_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPB_DESTINATION_IP)
	LD	H,(IX+TCPB_DESTINATION_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPB_SEQUENCE)
	LD	H,(IX+TCPB_SEQUENCE+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPB_ACKNOWLEDGEMENT)
	LD	H,(IX+TCPB_ACKNOWLEDGEMENT+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	A,(IX+TCPB_SOURCE_PORT)
	OR	(IX+TCPB_SOURCE_PORT+1)
	JR	Z,.INVALID
	LD	A,(IX+TCPB_DESTINATION_PORT)
	OR	(IX+TCPB_DESTINATION_PORT+1)
	JR	Z,.INVALID
	OR	A
	RET
.INVALID
	SCF
	RET

; PARSE
; In: HL -> TCPP descriptor. Out: descriptor results, CF/A status.
; Clobbers AF/BC/DE/HL; preserves IX/IY.
PARSE
	PUSH	IX,IY
	LD	BC,TCPP_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	CALL	VALIDATE_PARSE
	JP	C,.BAD
	CALL	CHECKSUM_PARSE
	LD	A,H
	OR	L
	JP	NZ,.BAD
	LD	L,(IX+TCPP_BUFFER)
	LD	H,(IX+TCPP_BUFFER+1)
	CALL	@ETHERNET.READ_BE16
	LD	A,D
	OR	E
	JP	Z,.BAD
	LD	A,(IX+TCPP_EXPECT_SOURCE_PORT)
	LD	C,A
	LD	A,(IX+TCPP_EXPECT_SOURCE_PORT+1)
	OR	C
	JR	Z,.SOURCE_OK
	LD	A,(IX+TCPP_EXPECT_SOURCE_PORT)
	CP	E
	JP	NZ,.BAD
	LD	A,(IX+TCPP_EXPECT_SOURCE_PORT+1)
	CP	D
	JP	NZ,.BAD
.SOURCE_OK
	CALL	@ETHERNET.READ_BE16
	LD	A,(IX+TCPP_EXPECT_DEST_PORT)
	CP	E
	JP	NZ,.BAD
	LD	A,(IX+TCPP_EXPECT_DEST_PORT+1)
	CP	D
	JP	NZ,.BAD
	LD	E,(IX+TCPP_SEQUENCE)
	LD	D,(IX+TCPP_SEQUENCE+1)
	LD	BC,4
	LDIR
	LD	E,(IX+TCPP_ACKNOWLEDGEMENT)
	LD	D,(IX+TCPP_ACKNOWLEDGEMENT+1)
	LD	BC,4
	LDIR
	LD	A,(HL)
	AND	0x0F
	JP	NZ,.BAD
	LD	A,(HL)
	AND	0xF0
	RRCA
	RRCA
	RRCA
	RRCA
	ADD	A,A
	ADD	A,A
	LD	(IX+TCPP_HEADER_LENGTH),A
	INC	HL
	LD	A,(HL)
	LD	(IX+TCPP_FLAGS),A
	INC	HL
	CALL	@ETHERNET.READ_BE16
	LD	(IX+TCPP_WINDOW),E
	LD	(IX+TCPP_WINDOW+1),D
	XOR	A
	LD	(IX+TCPP_MSS),A
	LD	(IX+TCPP_MSS+1),A
	CALL	PARSE_OPTIONS
	JP	C,.BAD
	LD	L,(IX+TCPP_BUFFER)
	LD	H,(IX+TCPP_BUFFER+1)
	LD	E,(IX+TCPP_HEADER_LENGTH)
	LD	D,0
	ADD	HL,DE
	LD	(IX+TCPP_PAYLOAD),L
	LD	(IX+TCPP_PAYLOAD+1),H
	LD	L,(IX+TCPP_LENGTH)
	LD	H,(IX+TCPP_LENGTH+1)
	OR	A
	SBC	HL,DE
	LD	(IX+TCPP_PAYLOAD_LENGTH),L
	LD	(IX+TCPP_PAYLOAD_LENGTH+1),H
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

VALIDATE_PARSE
	LD	L,(IX+TCPP_LENGTH)
	LD	H,(IX+TCPP_LENGTH+1)
	LD	DE,TCP_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	JR	C,.INVALID
	LD	L,(IX+TCPP_BUFFER)
	LD	H,(IX+TCPP_BUFFER+1)
	LD	C,(IX+TCPP_LENGTH)
	LD	B,(IX+TCPP_LENGTH+1)
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPP_SOURCE_IP)
	LD	H,(IX+TCPP_SOURCE_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPP_DESTINATION_IP)
	LD	H,(IX+TCPP_DESTINATION_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPP_SEQUENCE)
	LD	H,(IX+TCPP_SEQUENCE+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+TCPP_ACKNOWLEDGEMENT)
	LD	H,(IX+TCPP_ACKNOWLEDGEMENT+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	A,(IX+TCPP_EXPECT_DEST_PORT)
	OR	(IX+TCPP_EXPECT_DEST_PORT+1)
	JR	Z,.INVALID
	LD	L,(IX+TCPP_BUFFER)
	LD	H,(IX+TCPP_BUFFER+1)
	LD	DE,12
	ADD	HL,DE
	LD	A,(HL)
	AND	0xF0
	CP	0x50
	JR	C,.INVALID
	RRCA
	RRCA
	RRCA
	RRCA
	ADD	A,A
	ADD	A,A
	LD	E,A
	LD	D,0
	LD	L,(IX+TCPP_LENGTH)
	LD	H,(IX+TCPP_LENGTH+1)
	OR	A
	SBC	HL,DE
	JR	C,.INVALID
	OR	A
	RET
.INVALID
	SCF
	RET

; Parse only EOL, NOP and MSS. Unknown well-formed options are skipped.
PARSE_OPTIONS
	LD	A,(IX+TCPP_HEADER_LENGTH)
	SUB	TCP_HEADER_LENGTH
	RET	Z
	LD	B,A
	LD	L,(IX+TCPP_BUFFER)
	LD	H,(IX+TCPP_BUFFER+1)
	LD	DE,TCP_HEADER_LENGTH
	ADD	HL,DE
.OPTION
	LD	A,(HL)
	OR	A
	RET	Z
	CP	1
	JR	NZ,.LENGTH
	INC	HL
	DJNZ	.OPTION
	OR	A
	RET
.LENGTH
	LD	C,A
	PUSH	HL
	LD	A,B
	CP	2
	JR	C,.BAD_OPTION_POP
	INC	HL
	LD	A,(HL)
	CP	2
	JR	C,.BAD_OPTION_POP
	CP	B
	JR	Z,.FITS
	JR	C,.FITS
	JR	.BAD_OPTION_POP
.FITS
	LD	E,A
	LD	D,0
	LD	A,C
	CP	2
	JR	NZ,.SKIP
	LD	A,E
	CP	4
	JR	NZ,.BAD_OPTION_POP
	INC	HL
	LD	A,(HL)
	LD	(IX+TCPP_MSS+1),A
	INC	HL
	LD	A,(HL)
	LD	(IX+TCPP_MSS),A
.SKIP
	POP	HL
	ADD	HL,DE
	LD	A,B
	SUB	E
	LD	B,A
	JR	NZ,.OPTION
	OR	A
	RET
.BAD_OPTION_POP
	POP	HL
.BAD_OPTION
	SCF
	RET

CHECKSUM_BUILD
	PUSH	IX
	LD	L,(IX+TCPB_SOURCE_IP)
	LD	H,(IX+TCPB_SOURCE_IP+1)
	LD	E,(IX+TCPB_DESTINATION_IP)
	LD	D,(IX+TCPB_DESTINATION_IP+1)
	LD	C,(IX+TCPB_BUFFER)
	LD	B,(IX+TCPB_BUFFER+1)
	CALL	CHECKSUM_COMMON
	POP	IX
	RET

CHECKSUM_PARSE
	PUSH	IX
	LD	L,(IX+TCPP_LENGTH)
	LD	H,(IX+TCPP_LENGTH+1)
	LD	(TCP_TOTAL),HL
	LD	L,(IX+TCPP_SOURCE_IP)
	LD	H,(IX+TCPP_SOURCE_IP+1)
	LD	E,(IX+TCPP_DESTINATION_IP)
	LD	D,(IX+TCPP_DESTINATION_IP+1)
	LD	C,(IX+TCPP_BUFFER)
	LD	B,(IX+TCPP_BUFFER+1)
	CALL	CHECKSUM_COMMON
	POP	IX
	RET

; HL=source IP, DE=destination IP, BC=segment pointer, TCP_TOTAL=length.
CHECKSUM_COMMON
	LD	(TCP_SOURCE_PTR),HL
	LD	(TCP_DEST_PTR),DE
	LD	(TCP_BUFFER_PTR),BC
	LD	DE,0
	LD	BC,4
	CALL	@ETHERNET.ACCUMULATE
	LD	HL,(TCP_DEST_PTR)
	LD	BC,4
	CALL	@ETHERNET.ACCUMULATE
	LD	HL,TCP_PROTOCOL
	CALL	ADD_ACCUMULATOR
	LD	HL,(TCP_TOTAL)
	CALL	ADD_ACCUMULATOR
	LD	HL,(TCP_BUFFER_PTR)
	LD	BC,(TCP_TOTAL)
	CALL	@ETHERNET.ACCUMULATE
	LD	A,D
	CPL
	LD	H,A
	LD	A,E
	CPL
	LD	L,A
	RET

ADD_ACCUMULATOR
	ADD	HL,DE
	EX	DE,HL
	RET	NC
	INC	DE
	RET

TCP_TOTAL	DW 0
TCP_HEADER_SIZE DW 0
TCP_SOURCE_PTR	DW 0
TCP_DEST_PTR	DW 0
TCP_BUFFER_PTR	DW 0
TCP_CHECKSUM	DW 0

	ENDMODULE
	ENDIF
