; Polling-only two-channel TCP/IPv4 client over NETDRV.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_TCP_TRANSPORT_ASM
	DEFINE	_TCP_TRANSPORT_ASM

	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "tcp.inc"

	MODULE TCPX

CTX_STATE		EQU 0
CTX_REMOTE_IP		EQU 1
CTX_REMOTE_MAC		EQU 5
CTX_REMOTE_PORT	EQU 11
CTX_LOCAL_PORT		EQU 13
CTX_SND_UNA		EQU 15
CTX_SND_NXT		EQU 19
CTX_RCV_NXT		EQU 23
CTX_PEER_MSS		EQU 27
CTX_PENDING_LEN	EQU 29
CTX_PENDING_OFF	EQU 31
CTX_LAST_STATUS	EQU 33
CTX_EVENT		EQU 34
CTX_REMOTE_FIN		EQU 35
CTX_REMOTE_WINDOW	EQU 36
CTX_RETRY_LEFT		EQU 38

EVENT_ACK		EQU 0x01
EVENT_DATA		EQU 0x02
EVENT_FIN		EQU 0x04
EVENT_RST		EQU 0x08
EVENT_SYN_ACK		EQU 0x10
EVENT_WINDOW		EQU 0x20

SYN_ATTEMPTS		EQU 3
SYN_TIMEOUT_MS		EQU 1700
DATA_ATTEMPTS		EQU 3
FIN_TIMEOUT_MS		EQU 5000
ARP_ATTEMPTS		EQU 3
ARP_TIMEOUT_MS		EQU 2000

; RESET clears both channel contexts. It does not touch NETDRV and preserves a
; valid ephemeral-port cursor so reconnect cannot immediately reuse its tuple.
; Out: A=0/CF=0. Clobbers AF/BC/HL; preserves IX/IY.
RESET
	PUSH	IX,IY
	LD	HL,S11_CONTEXT0
	LD	BC,S11_CONTEXT_SIZE
	CALL	ZERO_REGION
	LD	HL,S11_CONTEXT1
	LD	BC,S11_CONTEXT_SIZE
	CALL	ZERO_REGION
	LD	HL,(S11_NEXT_LOCAL_PORT)
	LD	A,H
	CP	0xC0
	JP	NC,.PORT_READY
	LD	A,(NET_LOCAL_IP+3)
	LD	B,A
	LD	A,R
	XOR	B
	LD	L,A
	LD	A,R
	AND	0x3F
	OR	0xC0
	LD	H,A
	LD	(S11_NEXT_LOCAL_PORT),HL
.PORT_READY
	LD	HL,1
	LD	(S11_IP_ID),HL
	XOR	A
	POP	IY,IX
	RET

; OPEN
; In: A=channel 0..1, HL=remote IPv4 pointer, BC=remote port.
; Out: CF/A status. Local port and ISN are generated per call.
; Clobbers AF/BC/DE/HL; preserves IX/IY.
OPEN
	LD	(S11_CHANNEL),A
	JP	OPEN_SAFE

OPEN_SAFE
	PUSH	IX,IY
	LD	(S11_SEND_POINTER),HL
	LD	(S11_SEND_REMAINING),BC
	LD	A,B
	OR	C
	JP	Z,.PARAMETER_SAFE
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PARAMETER_SAFE
	LD	A,(S11_CHANNEL)
	CALL	SELECT_CONTEXT
	JP	C,.RETURN_SAFE
	LD	A,(IX+CTX_STATE)
	OR	A
	JP	NZ,.STATE_SAFE
	CALL	CLEAR_CONTEXT
	LD	HL,(S11_SEND_POINTER)
	PUSH	IX
	POP	DE
	INC	DE
	LD	BC,4
	LDIR
	LD	HL,(S11_SEND_REMAINING)
	LD	(IX+CTX_REMOTE_PORT),L
	LD	(IX+CTX_REMOTE_PORT+1),H
	LD	HL,TCP_MSS
	LD	(IX+CTX_PEER_MSS),L
	LD	(IX+CTX_PEER_MSS+1),H
	LD	A,TCP_STAGE_ARP
	LD	(S11_DIAG_STAGE),A
	CALL	RESOLVE_ROUTE
	JP	C,.FAIL_OPEN
	LD	HL,NET_RESULT_MAC
	PUSH	IX
	POP	DE
	LD	BC,CTX_REMOTE_MAC
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	LD	HL,NET_RESULT_MAC
	LD	BC,6
	LDIR
	CALL	GENERATE_TUPLE
	LD	(IX+CTX_STATE),TCP_STATE_SYN_SENT
	LD	A,TCP_STAGE_SYN
	LD	(S11_DIAG_STAGE),A
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	CALL	INC32
	LD	(IX+CTX_RETRY_LEFT),SYN_ATTEMPTS
.SYN_TRY
	XOR	A
	LD	(IX+CTX_EVENT),A
	LD	A,TCP_FLAG_SYN
	LD	BC,0
	CALL	SEND_SEGMENT
	JP	C,.FAIL_OPEN
	LD	A,EVENT_SYN_ACK|EVENT_RST
	LD	BC,SYN_TIMEOUT_MS
	CALL	WAIT_FOR_EVENT
	JP	NC,.SYN_EVENT
	CP	TCP_ERR_TIMEOUT
	JP	NZ,.FAIL_OPEN
	LD	A,(IX+CTX_RETRY_LEFT)
	DEC	A
	LD	(IX+CTX_RETRY_LEFT),A
	JP	NZ,.SYN_TRY
	LD	A,TCP_ERR_TIMEOUT
	JP	.FAIL_OPEN
.SYN_EVENT
	BIT	3,A
	JP	NZ,.RESET_OPEN
	LD	A,(IX+CTX_STATE)
	CP	TCP_STATE_ESTABLISHED
	JP	NZ,.PROTOCOL_OPEN
	XOR	A
	POP	IY,IX
	RET
.RESET_OPEN
	LD	A,TCP_ERR_RESET
	JP	.FAIL_OPEN
.PROTOCOL_OPEN
	LD	A,NETDRV_ERR_PROTOCOL
.FAIL_OPEN
	CALL	FAIL_CONTEXT
.RETURN_SAFE
	POP	IY,IX
	RET
.STATE_SAFE
	LD	A,TCP_ERR_STATE
	SCF
	POP	IY,IX
	RET
.PARAMETER_SAFE
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; SEND
; In: A=channel, HL=buffer, BC=length. Out: DE=cumulatively ACKed bytes.
; Length zero is a successful no-op on an open channel; longer calls are
; segmented internally.
; Clobbers AF/BC/HL; preserves IX/IY.
SEND
	PUSH	IX,IY
	LD	(S11_CHANNEL),A
	LD	(S11_SEND_POINTER),HL
	LD	(S11_SEND_REMAINING),BC
	LD	HL,0
	LD	(S11_SEND_CONFIRMED),HL
	LD	A,(S11_CHANNEL)
	CALL	SELECT_CONTEXT
	JP	C,.SEND_RETURN
	LD	A,(IX+CTX_STATE)
	CP	TCP_STATE_ESTABLISHED
	JP	Z,.SEND_STATE_OK
	CP	TCP_STATE_CLOSE_WAIT
	JP	NZ,.SEND_CLOSED
.SEND_STATE_OK
	LD	HL,(S11_SEND_REMAINING)
	LD	A,H
	OR	L
	JP	Z,.SEND_OK_SELECTED
	LD	HL,(S11_SEND_POINTER)
	LD	BC,(S11_SEND_REMAINING)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.SEND_PARAMETER
.SEND_NEXT
	LD	HL,(S11_SEND_REMAINING)
	LD	A,H
	OR	L
	JP	Z,.SEND_OK_SELECTED
	CALL	WAIT_REMOTE_WINDOW
	JP	C,.SEND_FAIL
	LD	A,TCP_STAGE_DATA
	LD	(S11_DIAG_STAGE),A
	CALL	CHOOSE_SEGMENT_LENGTH
	LD	HL,(S11_SEGMENT_LENGTH)
	LD	(S11_ACTIVE_LENGTH),HL
	LD	HL,(S11_SEND_POINTER)
	LD	DE,STAGE9_TX_BUFFER+14+IPV4_HEADER_LENGTH+TCP_HEADER_LENGTH
	LD	BC,(S11_ACTIVE_LENGTH)
	LDIR
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	LD	DE,S11_TARGET_ACK
	CALL	COPY4
	LD	HL,S11_TARGET_ACK
	LD	DE,(S11_ACTIVE_LENGTH)
	CALL	ADD16_TO32
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	EX	DE,HL
	LD	HL,S11_TARGET_ACK
	CALL	COPY4
	LD	(IX+CTX_RETRY_LEFT),DATA_ATTEMPTS
.DATA_TRY
	LD	A,(IX+CTX_EVENT)
	AND	~(EVENT_ACK|EVENT_RST|EVENT_FIN)
	LD	(IX+CTX_EVENT),A
	LD	A,TCP_FLAG_PSH|TCP_FLAG_ACK
	LD	BC,(S11_ACTIVE_LENGTH)
	CALL	SEND_SEGMENT
	JP	C,.SEND_FAIL
	LD	A,(IX+CTX_RETRY_LEFT)
	CP	3
	LD	BC,1000
	JP	Z,.DATA_WAIT
	CP	2
	LD	BC,2000
	JP	Z,.DATA_WAIT
	LD	BC,4000
.DATA_WAIT
	LD	A,EVENT_ACK|EVENT_RST
	CALL	WAIT_FOR_EVENT
	JP	NC,.DATA_EVENT
	CP	TCP_ERR_TIMEOUT
	JP	NZ,.SEND_FAIL
	LD	A,(IX+CTX_RETRY_LEFT)
	DEC	A
	LD	(IX+CTX_RETRY_LEFT),A
	JP	NZ,.DATA_TRY
	LD	A,TCP_ERR_TIMEOUT
	JP	.SEND_FAIL
.DATA_EVENT
	BIT	3,A
	JP	NZ,.SEND_RESET
	PUSH	IX
	POP	DE
	LD	HL,CTX_SND_UNA
	ADD	HL,DE
	LD	DE,S11_TARGET_ACK
	CALL	CMP4
	LD	A,TCP_ERR_SEQUENCE
	JP	NZ,.SEND_FAIL
	LD	HL,(S11_SEND_POINTER)
	LD	DE,(S11_ACTIVE_LENGTH)
	ADD	HL,DE
	LD	(S11_SEND_POINTER),HL
	LD	HL,(S11_SEND_REMAINING)
	OR	A
	SBC	HL,DE
	LD	(S11_SEND_REMAINING),HL
	LD	HL,(S11_SEND_CONFIRMED)
	ADD	HL,DE
	LD	(S11_SEND_CONFIRMED),HL
	JP	.SEND_NEXT
.SEND_RESET
	LD	A,TCP_ERR_RESET
.SEND_FAIL
	PUSH	AF
	CALL	FAIL_CONTEXT
	POP	AF
	LD	DE,(S11_SEND_CONFIRMED)
	SCF
	JP	.SEND_RETURN
.SEND_CLOSED
	LD	A,TCP_ERR_CLOSED
	LD	DE,0
	SCF
	JP	.SEND_RETURN
.SEND_PARAMETER
	LD	A,NETDRV_ERR_PARAMETER
	LD	DE,0
	SCF
	JP	.SEND_RETURN
.SEND_OK_SELECTED
	LD	DE,(S11_SEND_CONFIRMED)
	XOR	A
.SEND_RETURN
	POP	IY,IX
	RET

; RECV
; In: A=channel, HL=destination, BC=capacity, DE=timeout milliseconds.
; Out: BC=bytes copied. Timeout, orderly close and reset are distinct statuses.
; Clobbers AF/DE/HL; preserves IX/IY.
RECV
	PUSH	IX,IY
	LD	(S11_CHANNEL),A
	LD	(S11_SEND_POINTER),HL
	LD	(S11_COPY_LENGTH),BC
	LD	(S11_TIMEOUT_MS),DE
	LD	A,B
	OR	C
	JP	Z,.RECV_PARAMETER
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.RECV_PARAMETER
	LD	A,(S11_CHANNEL)
	CALL	SELECT_CONTEXT
	JP	NC,.RECV_CHECK
	LD	BC,0
	JP	.RECV_RETURN
.RECV_CHECK
	LD	L,(IX+CTX_PENDING_LEN)
	LD	H,(IX+CTX_PENDING_LEN+1)
	LD	A,H
	OR	L
	JP	NZ,.RECV_COPY
	LD	A,(IX+CTX_REMOTE_FIN)
	OR	A
	JP	NZ,.RECV_CLOSED
	LD	A,(IX+CTX_STATE)
	OR	A
	JP	Z,.RECV_STATE_ERROR
	LD	A,(IX+CTX_EVENT)
	AND	~(EVENT_DATA|EVENT_FIN|EVENT_RST)
	LD	(IX+CTX_EVENT),A
	LD	A,EVENT_DATA|EVENT_FIN|EVENT_RST
	PUSH	AF
	LD	A,TCP_STAGE_RECV
	LD	(S11_DIAG_STAGE),A
	POP	AF
	LD	BC,(S11_TIMEOUT_MS)
	CALL	WAIT_FOR_EVENT
	JP	C,.RECV_RETURN
	BIT	3,A
	JP	NZ,.RECV_RESET
	JP	.RECV_CHECK
.RECV_COPY
	LD	DE,(S11_COPY_LENGTH)
	OR	A
	SBC	HL,DE
	JP	C,.CAPACITY_SMALLER
	JP	Z,.CAPACITY_SMALLER
	LD	HL,(S11_COPY_LENGTH)
	JP	.COPY_READY
.CAPACITY_SMALLER
	ADD	HL,DE
.COPY_READY
	LD	(S11_COPY_LENGTH),HL
	CALL	PENDING_BASE
	LD	L,(IX+CTX_PENDING_OFF)
	LD	H,(IX+CTX_PENDING_OFF+1)
	ADD	HL,DE
	LD	DE,(S11_SEND_POINTER)
	LD	BC,(S11_COPY_LENGTH)
	LDIR
	LD	HL,(S11_COPY_LENGTH)
	LD	E,(IX+CTX_PENDING_OFF)
	LD	D,(IX+CTX_PENDING_OFF+1)
	ADD	HL,DE
	LD	(IX+CTX_PENDING_OFF),L
	LD	(IX+CTX_PENDING_OFF+1),H
	LD	L,(IX+CTX_PENDING_LEN)
	LD	H,(IX+CTX_PENDING_LEN+1)
	LD	DE,(S11_COPY_LENGTH)
	OR	A
	SBC	HL,DE
	LD	(IX+CTX_PENDING_LEN),L
	LD	(IX+CTX_PENDING_LEN+1),H
	LD	A,H
	OR	L
	JP	NZ,.RECV_SUCCESS
	XOR	A
	LD	(IX+CTX_PENDING_OFF),A
	LD	(IX+CTX_PENDING_OFF+1),A
	LD	A,TCP_FLAG_ACK
	LD	BC,0
	CALL	SEND_SEGMENT		; best-effort window update
.RECV_SUCCESS
	LD	BC,(S11_COPY_LENGTH)
	XOR	A
	JP	.RECV_RETURN
.RECV_PARAMETER
	LD	A,NETDRV_ERR_PARAMETER
	LD	BC,0
	SCF
	JP	.RECV_RETURN
.RECV_CLOSED
.RECV_STATE_ERROR
	LD	A,TCP_ERR_CLOSED
	LD	BC,0
	SCF
	JP	.RECV_RETURN
.RECV_RESET
	LD	A,TCP_ERR_RESET
	LD	BC,0
	SCF
.RECV_RETURN
	POP	IY,IX
	RET

; CLOSE performs an active close with a finite five-second wait. It is
; idempotent for an already closed channel.
; In: A=channel. Out: CF/A status. Clobbers AF/BC/DE/HL; preserves IX/IY.
CLOSE
	PUSH	IX,IY
	CALL	SELECT_CONTEXT
	JP	C,.CLOSE_RETURN
	LD	A,(IX+CTX_STATE)
	OR	A
	JP	Z,.CLOSE_OK
	CP	TCP_STATE_SYN_SENT
	JP	Z,.CLOSE_ABORT
	LD	A,(IX+CTX_EVENT)
	AND	~(EVENT_ACK|EVENT_FIN|EVENT_RST)
	LD	(IX+CTX_EVENT),A
	LD	A,TCP_FLAG_FIN|TCP_FLAG_ACK
	PUSH	AF
	LD	A,TCP_STAGE_CLOSE
	LD	(S11_DIAG_STAGE),A
	POP	AF
	LD	BC,0
	CALL	SEND_SEGMENT
	JP	C,.CLOSE_FAIL
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	CALL	INC32
	LD	(IX+CTX_STATE),TCP_STATE_FIN_WAIT
	LD	A,(IX+CTX_REMOTE_FIN)
	OR	A
	JP	NZ,.CLOSE_WAIT_ACK
	LD	A,EVENT_ACK|EVENT_FIN|EVENT_RST
	LD	BC,FIN_TIMEOUT_MS
	CALL	WAIT_FOR_ALL_EVENTS
	JP	.CLOSE_WAIT_DONE
.CLOSE_WAIT_ACK
	LD	A,EVENT_ACK|EVENT_RST
	LD	BC,FIN_TIMEOUT_MS
	CALL	WAIT_FOR_EVENT
.CLOSE_WAIT_DONE
	JP	C,.CLOSE_FAIL
	BIT	3,A
	JP	NZ,.CLOSE_RESET
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_UNA
	ADD	HL,DE
	PUSH	IX
	POP	DE
	LD	BC,CTX_SND_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.CLOSE_FAIL_TIMEOUT
.CLOSE_OK
	CALL	CLEAR_CONTEXT
	XOR	A
	JP	.CLOSE_RETURN
.CLOSE_ABORT
	CALL	ABORT_CONTEXT
	XOR	A
	JP	.CLOSE_RETURN
.CLOSE_RESET
	LD	A,TCP_ERR_RESET
	JP	.CLOSE_FAIL
.CLOSE_FAIL_TIMEOUT
	LD	A,TCP_ERR_TIMEOUT
.CLOSE_FAIL
	PUSH	AF
	CALL	ABORT_CONTEXT
	POP	AF
	SCF
	JP	.CLOSE_RETURN
.CLOSE_RETURN
	POP	IY,IX
	RET

; ABORT emits a best-effort RST for an active channel and always releases it.
; In: A=channel. Out: CF/A status. Clobbers AF/BC/DE/HL; preserves IX/IY.
ABORT
	PUSH	IX,IY
	CALL	SELECT_CONTEXT
	JP	C,.ABORT_RETURN
	CALL	ABORT_CONTEXT
	XOR	A
.ABORT_RETURN
	POP	IY,IX
	RET

; STATUS: In A=channel. Out A=TCP_STATE_*, B=last status, CF clear.
; Invalid channel returns NETDRV_ERR_PARAMETER/CF set. Clobbers AF/B/HL;
; preserves C/DE/IX/IY.
STATUS
	PUSH	IX,IY
	CALL	SELECT_CONTEXT
	JP	C,.STATUS_RETURN
	LD	B,(IX+CTX_LAST_STATUS)
	LD	A,(IX+CTX_STATE)
	OR	A
.STATUS_RETURN
	POP	IY,IX
	RET

SELECT_CONTEXT
	CP	2
	JP	NC,.BAD
	LD	(S11_CHANNEL),A
	OR	A
	LD	IX,S11_CONTEXT0
	JP	Z,.STORE
	LD	IX,S11_CONTEXT1
.STORE
	PUSH	IX
	POP	HL
	LD	(S11_SELECTED_CONTEXT),HL
	XOR	A
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET

CLEAR_CONTEXT
	PUSH	IX
	POP	HL
	LD	BC,S11_CONTEXT_SIZE
	JP	ZERO_REGION

ZERO_REGION
	LD	A,B
	OR	C
	RET	Z
.ZERO
	XOR	A
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JP	NZ,.ZERO
	RET

GENERATE_TUPLE
	LD	HL,(S11_NEXT_LOCAL_PORT)
	LD	(IX+CTX_LOCAL_PORT),L
	LD	(IX+CTX_LOCAL_PORT+1),H
	INC	HL
	LD	A,H
	OR	L
	JP	NZ,.NEXT_PORT_READY
	LD	HL,0xC000
.NEXT_PORT_READY
	LD	(S11_NEXT_LOCAL_PORT),HL
	CALL	@S9APP.SECONDS
	LD	(IX+CTX_SND_UNA),A
	LD	A,R
	LD	(IX+CTX_SND_UNA+1),A
	XOR	(IX+CTX_REMOTE_IP+3)
	LD	(IX+CTX_SND_UNA+2),A
	LD	A,R
	XOR	(IX+CTX_LOCAL_PORT)
	LD	(IX+CTX_SND_UNA+3),A
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_UNA
	ADD	HL,DE
	PUSH	HL
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	CALL	COPY4
	RET

; Resolve the selected context's next hop with three finite ARP attempts.
RESOLVE_ROUTE
	PUSH	IX
	POP	HL
	LD	DE,CTX_REMOTE_IP
	ADD	HL,DE
	CALL	@ARP.SELECT_NEXT_HOP
	RET	C
	OR	A
	JP	NZ,.BAD_TARGET
	CALL	@S9APP.SECONDS
	LD	C,A
	LD	B,0
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.CACHE_LOOKUP
	RET	NC
	LD	(IX+CTX_RETRY_LEFT),ARP_ATTEMPTS
.ARP_TRY
	LD	DE,STAGE9_TX_BUFFER
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,STAGE9_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	LD	BC,ARP_TIMEOUT_MS
	CALL	@NETTIME.START
	RET	C
.ARP_POLL
	CALL	CHECK_CANCEL
	RET	C
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JP	Z,.ARP_TICK
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,STAGE9_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JP	C,.ARP_TICK
	LD	HL,STAGE9_RX_BUFFER
	CALL	@ARP.PARSE
	JP	C,.ARP_TICK
	CP	1
	JP	Z,.ARP_FOUND
	CP	2
	JP	NZ,.ARP_TICK
	LD	DE,STAGE9_TX_BUFFER
	LD	HL,STAGE9_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE9_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
.ARP_TICK
	CALL	@NETTIME.TICK
	JP	NC,.ARP_POLL
	LD	A,(IX+CTX_RETRY_LEFT)
	DEC	A
	LD	(IX+CTX_RETRY_LEFT),A
	JP	NZ,.ARP_TRY
	LD	A,TCP_ERR_TIMEOUT
	SCF
	RET
.ARP_FOUND
	CALL	@S9APP.SECONDS
	LD	C,A
	LD	B,0
	LD	HL,NET_NEXT_HOP_IP
	LD	DE,NET_RESULT_MAC
	CALL	@ARP.CACHE_INSERT
	RET
.BAD_TARGET
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET

CHOOSE_SEGMENT_LENGTH
	LD	HL,(S11_SEND_REMAINING)
	LD	E,(IX+CTX_PEER_MSS)
	LD	D,(IX+CTX_PEER_MSS+1)
	OR	A
	SBC	HL,DE
	JP	C,.REMAINING_SMALLER
	JP	Z,.REMAINING_SMALLER
	EX	DE,HL
	JP	.MSS_READY
.REMAINING_SMALLER
	ADD	HL,DE
.MSS_READY
	LD	E,(IX+CTX_REMOTE_WINDOW)
	LD	D,(IX+CTX_REMOTE_WINDOW+1)
	PUSH	HL
	OR	A
	SBC	HL,DE
	POP	HL
	JP	C,.CHOSEN
	JP	Z,.CHOSEN
	EX	DE,HL
.CHOSEN
	LD	(S11_SEGMENT_LENGTH),HL
	RET

WAIT_REMOTE_WINDOW
	LD	A,(IX+CTX_REMOTE_WINDOW)
	OR	(IX+CTX_REMOTE_WINDOW+1)
	RET	NZ
	LD	A,TCP_STAGE_WINDOW
	LD	(S11_DIAG_STAGE),A
	LD	(IX+CTX_RETRY_LEFT),3
.PROBE
	LD	A,(IX+CTX_EVENT)
	AND	~(EVENT_WINDOW|EVENT_RST|EVENT_FIN)
	LD	(IX+CTX_EVENT),A
	CALL	SEND_WINDOW_PROBE
	RET	C
	LD	A,(IX+CTX_RETRY_LEFT)
	CP	3
	LD	BC,1000
	JP	Z,.PROBE_WAIT
	CP	2
	LD	BC,2000
	JP	Z,.PROBE_WAIT
	LD	BC,4000
.PROBE_WAIT
	LD	A,EVENT_WINDOW|EVENT_RST|EVENT_FIN
	CALL	WAIT_FOR_EVENT
	JP	C,.PROBE_TIMEOUT
	BIT	3,A
	JP	NZ,.PROBE_RESET
	LD	A,(IX+CTX_REMOTE_WINDOW)
	OR	(IX+CTX_REMOTE_WINDOW+1)
	RET	NZ
.PROBE_TIMEOUT
	LD	A,(IX+CTX_RETRY_LEFT)
	DEC	A
	LD	(IX+CTX_RETRY_LEFT),A
	JP	NZ,.PROBE
	LD	A,TCP_ERR_WINDOW
	SCF
	RET
.PROBE_RESET
	LD	A,TCP_ERR_RESET
	SCF
	RET

; SEND_WINDOW_PROBE sends one already-acknowledged octet at SND.NXT-1. Unlike
; an empty ACK, this persist probe requires a conforming peer to answer without
; consuming the caller's first unsent byte.
SEND_WINDOW_PROBE
	LD	HL,(S11_SEND_POINTER)
	LD	A,(HL)
	LD	(STAGE9_TX_BUFFER+14+IPV4_HEADER_LENGTH+TCP_HEADER_LENGTH),A
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	LD	DE,S11_TARGET_ACK
	CALL	COPY4
	LD	HL,S11_TARGET_ACK
	CALL	DEC32
	LD	A,1
	LD	(S11_SEQUENCE_OVERRIDE),A
	LD	A,TCP_FLAG_ACK
	LD	BC,1
	JP	SEND_SEGMENT_COMMON

; SEND_SEGMENT builds Ethernet/IPv4/TCP contiguously and transmits it.
; In: IX=context, A=flags, BC=payload length already at TX+54.
SEND_SEGMENT
	PUSH	AF
	XOR	A
	LD	(S11_SEQUENCE_OVERRIDE),A
	POP	AF
SEND_SEGMENT_COMMON
	LD	(S11_BUILD_FLAGS),A
	LD	(S11_SEGMENT_LENGTH),BC
	LD	HL,STAGE9_TX_BUFFER+14+IPV4_HEADER_LENGTH
	LD	(S11_TCP_BUILD_DESC+TCPB_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-14-IPV4_HEADER_LENGTH
	LD	(S11_TCP_BUILD_DESC+TCPB_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(S11_TCP_BUILD_DESC+TCPB_SOURCE_IP),HL
	PUSH	IX
	POP	HL
	INC	HL
	LD	(S11_TCP_BUILD_DESC+TCPB_DESTINATION_IP),HL
	LD	L,(IX+CTX_LOCAL_PORT)
	LD	H,(IX+CTX_LOCAL_PORT+1)
	LD	(S11_TCP_BUILD_DESC+TCPB_SOURCE_PORT),HL
	LD	L,(IX+CTX_REMOTE_PORT)
	LD	H,(IX+CTX_REMOTE_PORT+1)
	LD	(S11_TCP_BUILD_DESC+TCPB_DESTINATION_PORT),HL
	PUSH	IX
	POP	HL
	LD	DE,CTX_SND_NXT
	ADD	HL,DE
	LD	A,(S11_SEQUENCE_OVERRIDE)
	OR	A
	JP	NZ,.USE_OVERRIDE
	LD	A,(S11_BUILD_FLAGS)
	AND	TCP_FLAG_SYN|TCP_FLAG_FIN
	JP	NZ,.USE_UNA
	LD	DE,(S11_SEGMENT_LENGTH)
	LD	A,D
	OR	E
	JP	Z,.SEQUENCE_READY
.USE_UNA
	LD	DE,CTX_SND_UNA-CTX_SND_NXT
	ADD	HL,DE
	JP	.SEQUENCE_READY
.USE_OVERRIDE
	LD	HL,S11_TARGET_ACK
.SEQUENCE_READY
	LD	(S11_TCP_BUILD_DESC+TCPB_SEQUENCE),HL
	PUSH	IX
	POP	HL
	LD	DE,CTX_RCV_NXT
	ADD	HL,DE
	LD	(S11_TCP_BUILD_DESC+TCPB_ACKNOWLEDGEMENT),HL
	LD	HL,(S11_SEGMENT_LENGTH)
	LD	(S11_TCP_BUILD_DESC+TCPB_PAYLOAD_LENGTH),HL
	LD	A,(S11_BUILD_FLAGS)
	LD	(S11_TCP_BUILD_DESC+TCPB_FLAGS),A
	LD	HL,TCP_MSS
	LD	A,(IX+CTX_PENDING_LEN)
	OR	(IX+CTX_PENDING_LEN+1)
	JP	Z,.WINDOW_READY
	LD	HL,0
.WINDOW_READY
	LD	(S11_TCP_BUILD_DESC+TCPB_WINDOW),HL
	LD	HL,0
	LD	A,(S11_BUILD_FLAGS)
	AND	TCP_FLAG_SYN
	JP	Z,.MSS_READY
	LD	HL,TCP_MSS
.MSS_READY
	LD	(S11_TCP_BUILD_DESC+TCPB_MSS),HL
	LD	HL,S11_TCP_BUILD_DESC
	CALL	@TCP.BUILD
	RET	C
	LD	(S11_TCP_LENGTH),BC
	LD	(S11_IPV4_BUILD_DESC+IP4B_DATA_LENGTH),BC
	LD	HL,STAGE9_TX_BUFFER+14
	LD	(S11_IPV4_BUILD_DESC+IP4B_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-14
	LD	(S11_IPV4_BUILD_DESC+IP4B_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(S11_IPV4_BUILD_DESC+IP4B_SOURCE),HL
	PUSH	IX
	POP	HL
	INC	HL
	LD	(S11_IPV4_BUILD_DESC+IP4B_DESTINATION),HL
	LD	HL,(S11_IP_ID)
	LD	(S11_IPV4_BUILD_DESC+IP4B_IDENTIFIER),HL
	INC	HL
	LD	(S11_IP_ID),HL
	LD	A,64
	LD	(S11_IPV4_BUILD_DESC+IP4B_TTL),A
	LD	A,TCP_PROTOCOL
	LD	(S11_IPV4_BUILD_DESC+IP4B_PROTOCOL),A
	LD	HL,S11_IPV4_BUILD_DESC
	CALL	@IPV4.BUILD
	RET	C
	LD	(S11_FRAME_LENGTH),BC
	PUSH	IX
	POP	HL
	LD	DE,CTX_REMOTE_MAC
	ADD	HL,DE
	LD	DE,STAGE9_TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	LD	HL,(S11_FRAME_LENGTH)
	LD	DE,14
	ADD	HL,DE
	LD	B,H
	LD	C,L
	LD	HL,STAGE9_TX_BUFFER
	JP	@NETDRV.SEND_FRAME

; WAIT_FOR_EVENT polls and dispatches all frames, including the other channel.
; In: A=event mask, BC=timeout ms. Out: A=event bits or explicit timeout.
WAIT_FOR_EVENT
	PUSH	AF
	XOR	A
	LD	(S11_WAIT_ALL),A
	POP	AF
	JP	WAIT_START

; WAIT_FOR_ALL_EVENTS uses the same single deadline but waits for every masked
; event. RST remains immediately terminal and does not wait for other bits.
WAIT_FOR_ALL_EVENTS
	PUSH	AF
	LD	A,1
	LD	(S11_WAIT_ALL),A
	POP	AF
WAIT_START
	LD	(S11_WAIT_MASK),A
	CALL	@NETTIME.START
	RET	C
.WAIT_LOOP
	LD	HL,(S11_SELECTED_CONTEXT)
	PUSH	HL
	POP	IX
	CALL	CHECK_WAIT_EVENTS
	JP	C,.EVENT_READY
	CALL	CHECK_CANCEL
	RET	C
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JP	Z,.WAIT_TICK
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,STAGE9_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JP	C,.READ_ERROR
	LD	(S11_FRAME_LENGTH),BC
	CALL	PROCESS_FRAME
	RET	C
	LD	HL,(S11_SELECTED_CONTEXT)
	PUSH	HL
	POP	IX
	CALL	CHECK_WAIT_EVENTS
	JP	C,.EVENT_READY
	JP	.WAIT_TICK
.READ_ERROR
	CP	EL3_ERR_RX_ERROR
	JP	Z,.WAIT_TICK
	CP	EL3_ERR_FRAME_SIZE
	JP	Z,.WAIT_TICK
	CP	EL3_ERR_NO_FRAME
	JP	Z,.WAIT_TICK
	RET
.WAIT_TICK
	CALL	@NETTIME.TICK
	JP	NC,.WAIT_LOOP
	LD	A,TCP_ERR_TIMEOUT
	SCF
	RET
.EVENT_READY
	LD	C,B
	LD	A,(S11_WAIT_MASK)
	CPL
	AND	C
	LD	(IX+CTX_EVENT),A
	LD	A,(S11_WAIT_MASK)
	AND	C
	OR	A
	RET

CHECK_WAIT_EVENTS
	LD	A,(IX+CTX_EVENT)
	LD	B,A
	LD	A,(S11_WAIT_MASK)
	AND	B
	JP	Z,.NOT_READY
	LD	C,A
	BIT	3,C
	JP	NZ,.READY
	LD	A,(S11_WAIT_ALL)
	OR	A
	JP	Z,.READY
	LD	A,(S11_WAIT_MASK)
	AND	~EVENT_RST
	CP	C
	JP	NZ,.NOT_READY
.READY
	SCF
	RET
.NOT_READY
	OR	A
	RET

PROCESS_FRAME
	LD	HL,(S11_FRAME_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	RET	C
	LD	A,(STAGE9_RX_BUFFER+12)
	CP	0x08
	JP	NZ,.IGNORE
	LD	A,(STAGE9_RX_BUFFER+13)
	CP	0x06
	JP	Z,PROCESS_ARP
	OR	A
	JP	NZ,.IGNORE
	LD	HL,(S11_FRAME_LENGTH)
	LD	DE,14+IPV4_HEADER_LENGTH+TCP_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	JP	C,.IGNORE
	LD	HL,STAGE9_RX_BUFFER+14
	LD	(S11_IPV4_PARSE_DESC+IP4P_BUFFER),HL
	LD	HL,(S11_FRAME_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	LD	(S11_IPV4_PARSE_DESC+IP4P_LENGTH),HL
	LD	HL,0
	LD	(S11_IPV4_PARSE_DESC+IP4P_EXPECT_SOURCE),HL
	LD	HL,NET_LOCAL_IP
	LD	(S11_IPV4_PARSE_DESC+IP4P_EXPECT_DESTINATION),HL
	LD	A,TCP_PROTOCOL
	LD	(S11_IPV4_PARSE_DESC+IP4P_EXPECT_PROTOCOL),A
	LD	HL,S11_IPV4_PARSE_DESC
	CALL	@IPV4.PARSE
	JP	C,.IGNORE
	LD	HL,(S11_IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	DE,TCP_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	JP	C,.IGNORE
	LD	IX,S11_CONTEXT0
	CALL	MATCH_CONTEXT
	JP	Z,.MATCHED
	LD	IX,S11_CONTEXT1
	CALL	MATCH_CONTEXT
	JP	NZ,.IGNORE
.MATCHED
	PUSH	IX
	POP	HL
	LD	(S11_MATCH_CONTEXT),HL
	LD	HL,(S11_IPV4_PARSE_DESC+IP4P_DATA)
	LD	(S11_TCP_PARSE_DESC+TCPP_BUFFER),HL
	LD	HL,(S11_IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	(S11_TCP_PARSE_DESC+TCPP_LENGTH),HL
	LD	HL,(S11_IPV4_PARSE_DESC+IP4P_SOURCE)
	LD	(S11_TCP_PARSE_DESC+TCPP_SOURCE_IP),HL
	LD	HL,NET_LOCAL_IP
	LD	(S11_TCP_PARSE_DESC+TCPP_DESTINATION_IP),HL
	LD	L,(IX+CTX_REMOTE_PORT)
	LD	H,(IX+CTX_REMOTE_PORT+1)
	LD	(S11_TCP_PARSE_DESC+TCPP_EXPECT_SOURCE_PORT),HL
	LD	L,(IX+CTX_LOCAL_PORT)
	LD	H,(IX+CTX_LOCAL_PORT+1)
	LD	(S11_TCP_PARSE_DESC+TCPP_EXPECT_DEST_PORT),HL
	LD	HL,S11_PARSE_SEQUENCE
	LD	(S11_TCP_PARSE_DESC+TCPP_SEQUENCE),HL
	LD	HL,S11_PARSE_ACK
	LD	(S11_TCP_PARSE_DESC+TCPP_ACKNOWLEDGEMENT),HL
	LD	HL,S11_TCP_PARSE_DESC
	CALL	@TCP.PARSE
	JP	C,.IGNORE
	JP	HANDLE_SEGMENT
.IGNORE
	XOR	A
	RET

PROCESS_ARP
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,(S11_FRAME_LENGTH)
	CALL	@ARP.PARSE
	JP	C,.ARP_IGNORE
	CP	2
	JP	NZ,.ARP_IGNORE
	LD	DE,STAGE9_TX_BUFFER
	LD	HL,STAGE9_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE9_TX_BUFFER
	JP	@NETDRV.SEND_FRAME
.ARP_IGNORE
	XOR	A
	RET

MATCH_CONTEXT
	LD	A,(IX+CTX_STATE)
	OR	A
	JP	Z,.NO_MATCH
	LD	HL,(S11_IPV4_PARSE_DESC+IP4P_SOURCE)
	PUSH	IX
	POP	DE
	INC	DE
	CALL	CMP4
	JP	NZ,.NO_MATCH
	LD	HL,(S11_IPV4_PARSE_DESC+IP4P_DATA)
	LD	A,(IX+CTX_REMOTE_PORT+1)
	CP	(HL)
	JP	NZ,.NO_MATCH
	INC	HL
	LD	A,(IX+CTX_REMOTE_PORT)
	CP	(HL)
	JP	NZ,.NO_MATCH
	INC	HL
	LD	A,(IX+CTX_LOCAL_PORT+1)
	CP	(HL)
	JP	NZ,.NO_MATCH
	INC	HL
	LD	A,(IX+CTX_LOCAL_PORT)
	CP	(HL)
	JP	NZ,.NO_MATCH
	XOR	A
	RET
.NO_MATCH
	LD	A,1
	OR	A
	RET

HANDLE_SEGMENT
	XOR	A
	LD	(S11_SEGMENT_ACCEPTED),A
	LD	A,(S11_TCP_PARSE_DESC+TCPP_FLAGS)
	BIT	2,A
	JP	Z,.NOT_RST
	LD	A,(IX+CTX_STATE)
	CP	TCP_STATE_SYN_SENT
	JP	Z,.RST_SYN_SENT
	LD	HL,S11_PARSE_SEQUENCE
	PUSH	IX
	POP	DE
	LD	BC,CTX_RCV_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.DONE
	JP	.ACCEPT_RST
.RST_SYN_SENT
	LD	A,(S11_TCP_PARSE_DESC+TCPP_FLAGS)
	AND	TCP_FLAG_ACK
	JP	Z,.DONE
	LD	HL,S11_PARSE_ACK
	PUSH	IX
	POP	DE
	LD	BC,CTX_SND_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.DONE
.ACCEPT_RST
	LD	A,TCP_ERR_RESET
	LD	(IX+CTX_LAST_STATUS),A
	LD	(IX+CTX_STATE),TCP_STATE_CLOSED
	LD	A,EVENT_RST
	CALL	SET_EVENT
	XOR	A
	RET
.NOT_RST
	LD	A,(IX+CTX_STATE)
	CP	TCP_STATE_SYN_SENT
	JP	Z,HANDLE_SYN_ACK
	LD	A,(S11_TCP_PARSE_DESC+TCPP_FLAGS)
	AND	TCP_FLAG_ACK
	JP	Z,.NO_ACK
	LD	HL,S11_PARSE_ACK
	PUSH	IX
	POP	DE
	LD	BC,CTX_SND_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.NO_ACK
	LD	HL,S11_PARSE_ACK
	PUSH	IX
	POP	DE
	LD	BC,CTX_SND_UNA
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	COPY4
	CALL	UPDATE_REMOTE_WINDOW
	LD	A,EVENT_ACK
	CALL	SET_EVENT
.NO_ACK
	LD	HL,(S11_TCP_PARSE_DESC+TCPP_PAYLOAD_LENGTH)
	LD	(S11_COPY_LENGTH),HL
	LD	A,H
	OR	L
	JP	Z,.CHECK_FIN
	LD	DE,TCP_MSS+1
	OR	A
	SBC	HL,DE
	JP	NC,.PROTOCOL
	LD	HL,S11_PARSE_SEQUENCE
	PUSH	IX
	POP	DE
	LD	BC,CTX_RCV_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.ACK_CURRENT
	LD	A,(IX+CTX_PENDING_LEN)
	OR	(IX+CTX_PENDING_LEN+1)
	JP	NZ,.ACK_CURRENT
	CALL	PENDING_BASE
	LD	HL,(S11_TCP_PARSE_DESC+TCPP_PAYLOAD)
	LD	BC,(S11_COPY_LENGTH)
	LDIR
	LD	HL,(S11_COPY_LENGTH)
	LD	(IX+CTX_PENDING_LEN),L
	LD	(IX+CTX_PENDING_LEN+1),H
	XOR	A
	LD	(IX+CTX_PENDING_OFF),A
	LD	(IX+CTX_PENDING_OFF+1),A
	PUSH	IX
	POP	HL
	LD	DE,CTX_RCV_NXT
	ADD	HL,DE
	LD	DE,(S11_COPY_LENGTH)
	CALL	ADD16_TO32
	LD	A,1
	LD	(S11_SEGMENT_ACCEPTED),A
	LD	A,EVENT_DATA
	CALL	SET_EVENT
.CHECK_FIN
	LD	A,(S11_TCP_PARSE_DESC+TCPP_FLAGS)
	AND	TCP_FLAG_FIN
	JP	Z,.ACK_IF_DATA
	LD	A,(S11_SEGMENT_ACCEPTED)
	OR	A
	JP	NZ,.ACCEPT_FIN
	LD	HL,S11_PARSE_SEQUENCE
	PUSH	IX
	POP	DE
	LD	BC,CTX_RCV_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.ACK_CURRENT
.ACCEPT_FIN
	PUSH	IX
	POP	HL
	LD	DE,CTX_RCV_NXT
	ADD	HL,DE
	CALL	INC32
	LD	(IX+CTX_REMOTE_FIN),1
	LD	A,(IX+CTX_STATE)
	CP	TCP_STATE_FIN_WAIT
	JP	Z,.FIN_STATE_READY
	LD	(IX+CTX_STATE),TCP_STATE_CLOSE_WAIT
.FIN_STATE_READY
	LD	A,EVENT_FIN
	CALL	SET_EVENT
	JP	.ACK_CURRENT
.ACK_IF_DATA
	LD	A,(S11_SEGMENT_ACCEPTED)
	OR	A
	JP	Z,.DONE
.ACK_CURRENT
	LD	A,TCP_FLAG_ACK
	LD	BC,0
	JP	SEND_SEGMENT
.PROTOCOL
	LD	A,NETDRV_ERR_PROTOCOL
	CALL	FAIL_CONTEXT
	RET
.DONE
	XOR	A
	RET

HANDLE_SYN_ACK
	LD	A,(S11_TCP_PARSE_DESC+TCPP_FLAGS)
	AND	TCP_FLAG_SYN|TCP_FLAG_ACK
	CP	TCP_FLAG_SYN|TCP_FLAG_ACK
	JP	NZ,.SYN_IGNORE
	LD	HL,(S11_TCP_PARSE_DESC+TCPP_PAYLOAD_LENGTH)
	LD	A,H
	OR	L
	JP	NZ,.SYN_IGNORE
	LD	HL,S11_PARSE_ACK
	PUSH	IX
	POP	DE
	LD	BC,CTX_SND_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	CMP4
	JP	NZ,.SYN_IGNORE
	CALL	UPDATE_REMOTE_WINDOW
	LD	HL,S11_PARSE_ACK
	PUSH	IX
	POP	DE
	LD	BC,CTX_SND_UNA
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	COPY4
	LD	HL,S11_PARSE_SEQUENCE
	PUSH	IX
	POP	DE
	LD	BC,CTX_RCV_NXT
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	CALL	COPY4
	PUSH	IX
	POP	HL
	LD	DE,CTX_RCV_NXT
	ADD	HL,DE
	CALL	INC32
	LD	HL,(S11_TCP_PARSE_DESC+TCPP_MSS)
	LD	A,H
	OR	L
	JP	Z,.DEFAULT_MSS
	LD	DE,TCP_MSS+1
	OR	A
	SBC	HL,DE
	JP	NC,.DEFAULT_MSS
	ADD	HL,DE			; restore the peer value after comparison
	JP	.STORE_MSS
.DEFAULT_MSS
	LD	HL,TCP_MSS
.STORE_MSS
	LD	(IX+CTX_PEER_MSS),L
	LD	(IX+CTX_PEER_MSS+1),H
	LD	(IX+CTX_STATE),TCP_STATE_ESTABLISHED
	LD	A,EVENT_SYN_ACK|EVENT_ACK
	CALL	SET_EVENT
	LD	A,TCP_FLAG_ACK
	LD	BC,0
	JP	SEND_SEGMENT
.SYN_IGNORE
	XOR	A
	RET

SET_EVENT
	OR	(IX+CTX_EVENT)
	LD	(IX+CTX_EVENT),A
	RET

UPDATE_REMOTE_WINDOW
	LD	HL,(S11_TCP_PARSE_DESC+TCPP_WINDOW)
	LD	(IX+CTX_REMOTE_WINDOW),L
	LD	(IX+CTX_REMOTE_WINDOW+1),H
	LD	A,H
	OR	L
	RET	Z
	LD	A,EVENT_WINDOW
	JP	SET_EVENT

PENDING_BASE
	PUSH	IX
	POP	HL
	LD	DE,S11_CONTEXT0
	OR	A
	SBC	HL,DE
	LD	DE,S11_PENDING0
	RET	Z
	LD	DE,S11_PENDING1
	RET

ABORT_CONTEXT
	LD	A,(IX+CTX_STATE)
	OR	A
	JP	Z,.CLEAR
	LD	A,TCP_FLAG_RST|TCP_FLAG_ACK
	LD	BC,0
	CALL	SEND_SEGMENT
.CLEAR
	JP	CLEAR_CONTEXT

FAIL_CONTEXT
	LD	(IX+CTX_LAST_STATUS),A
	LD	(IX+CTX_STATE),TCP_STATE_CLOSED
	SCF
	RET

CHECK_CANCEL
	LD	C,DSS_SCANKEY
	RST	DSS
	JP	Z,.NO_CANCEL
	LD	A,E
	CP	0x1B
	JP	Z,.CANCEL
	LD	A,B
	AND	KB_CTRL|KB_L_CTRL|KB_R_CTRL
	JP	Z,.NO_CANCEL
	LD	A,D
	CP	0xAC
	JP	Z,.CANCEL
	LD	A,E
	CP	0x03
	JP	Z,.CANCEL
.NO_CANCEL
	XOR	A
	RET
.CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

; Four-byte sequence helpers use network byte order.
COPY4
	LD	BC,4
	LDIR
	RET

CMP4
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP
	RET

INC32
	LD	DE,3
	ADD	HL,DE
	INC	(HL)
	RET	NZ
	DEC	HL
	INC	(HL)
	RET	NZ
	DEC	HL
	INC	(HL)
	RET	NZ
	DEC	HL
	INC	(HL)
	RET

DEC32
	LD	DE,3
	ADD	HL,DE
	DEC	(HL)
	RET	NZ
	DEC	HL
	DEC	(HL)
	RET	NZ
	DEC	HL
	DEC	(HL)
	RET	NZ
	DEC	HL
	DEC	(HL)
	RET

; HL -> network-order sequence, DE=16-bit addend.
ADD16_TO32
	PUSH	HL
	LD	BC,3
	ADD	HL,BC
	LD	A,(HL)
	ADD	A,E
	LD	(HL),A
	DEC	HL
	LD	A,(HL)
	ADC	A,D
	LD	(HL),A
	JP	NC,.ADD_DONE
	DEC	HL
	INC	(HL)
	JP	NZ,.ADD_DONE
	DEC	HL
	INC	(HL)
.ADD_DONE
	POP	HL
	RET

	ENDMODULE
	ENDIF
