; Fido Editor-style resident trampolines for a program that owns WIN0.
; Fixed addresses let the independently assembled WIN0 entry install vectors.
; SPDX-License-Identifier: BSD-3-Clause

	MACRO TELNET_SYSCALL_TRAMP RST_VECTOR
	DI
	PUSH AF
	LD A,(TELNET_SYS_DSS_PAGE)
	OUT (PAGE0),A
	POP AF
	EI
	RST RST_VECTOR
	DI
	PUSH AF
	LD A,(TELNET_SYS_P1_PAGE)
	OUT (PAGE1),A
	LD A,(TELNET_SYS_P0_PAGE)
	OUT (PAGE0),A
	POP AF
	EI
	RET
	ENDM

SYSTEM_BIOS_TRAMP
	TELNET_SYSCALL_TRAMP BIOS
	DS TELNET_SYS_DSS_TRAMP - $,0

SYSTEM_DSS_TRAMP
	TELNET_SYSCALL_TRAMP DSS
	DS TELNET_SYS_MOUSE_TRAMP - $,0

SYSTEM_MOUSE_TRAMP
	TELNET_SYSCALL_TRAMP 0x30
	DS TELNET_SYS_INT_TRAMP - $,0

SYSTEM_INT_TRAMP
	PUSH AF
	PUSH HL
	LD A,(TELNET_SYS_DSS_PAGE)
	OUT (PAGE0),A
	LD HL,.RESUME
	PUSH HL
	LD HL,0x0038
	JP (HL)
.RESUME
	DI
	LD A,(TELNET_SYS_P1_PAGE)
	OUT (PAGE1),A
	LD A,(TELNET_SYS_P0_PAGE)
	OUT (PAGE0),A
	POP HL
	POP AF
	EI
	RETI

	ASSERT SYSTEM_BIOS_TRAMP == TELNET_SYS_BIOS_TRAMP
	ASSERT SYSTEM_DSS_TRAMP == TELNET_SYS_DSS_TRAMP
	ASSERT SYSTEM_MOUSE_TRAMP == TELNET_SYS_MOUSE_TRAMP
	ASSERT SYSTEM_INT_TRAMP == TELNET_SYS_INT_TRAMP
