; Strict RFC 1350/RFC 2348 TFTP packet codec.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_TFTP_ASM
	DEFINE	_TFTP_ASM

	INCLUDE "netdrv.inc"
	INCLUDE "udp_tftp.inc"

	MODULE TFTP

; BUILD_REQUEST builds RRQ/WRQ in octet mode with exactly one blksize option.
; In: HL -> TFTPR descriptor. Out: BC=wire length. Preserves IX/IY.
BUILD_REQUEST
	PUSH	IX,IY
	LD	BC,TFTPR_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	LD	A,(IX+TFTPR_OPCODE+1)
	OR	A
	JP	NZ,.BAD
	LD	A,(IX+TFTPR_OPCODE)
	CP	TFTP_OPCODE_RRQ
	JR	Z,.OP_OK
	CP	TFTP_OPCODE_WRQ
	JP	NZ,.BAD
.OP_OK
	LD	A,(IX+TFTPR_NAME_LENGTH+1)
	OR	A
	JP	NZ,.BAD
	LD	A,(IX+TFTPR_NAME_LENGTH)
	OR	A
	JP	Z,.BAD
	CP	TFTP_MAX_WIRE_NAME+1
	JP	NC,.BAD
	LD	L,(IX+TFTPR_NAME)
	LD	H,(IX+TFTPR_NAME+1)
	LD	C,(IX+TFTPR_NAME_LENGTH)
	LD	B,0
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+TFTPR_BLOCK_SIZE)
	LD	H,(IX+TFTPR_BLOCK_SIZE+1)
	CALL	VALID_BLOCK_SIZE
	JP	C,.BAD
	CALL	DECIMAL_LENGTH
	LD	A,(IX+TFTPR_NAME_LENGTH)
	ADD	A,2+1+5+1+1		; opcode, name NUL, "octet" NUL, option NUL
	JP	C,.BAD
	ADD	A,7+1			; "blksize" and NUL before value
	JP	C,.BAD
	ADD	A,C			; decimal value plus terminating NUL
	JP	C,.BAD
	LD	C,A
	LD	B,0
	LD	(FTP_TOTAL),BC
	LD	L,(IX+TFTPR_CAPACITY)
	LD	H,(IX+TFTPR_CAPACITY+1)
	OR	A
	SBC	HL,BC
	JP	C,.BAD
	LD	L,(IX+TFTPR_BUFFER)
	LD	H,(IX+TFTPR_BUFFER+1)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	LD	E,(IX+TFTPR_BUFFER)
	LD	D,(IX+TFTPR_BUFFER+1)
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,(IX+TFTPR_OPCODE)
	LD	(DE),A
	INC	DE
	LD	L,(IX+TFTPR_NAME)
	LD	H,(IX+TFTPR_NAME+1)
	LD	C,(IX+TFTPR_NAME_LENGTH)
	LD	B,0
	LDIR
	XOR	A
	LD	(DE),A
	INC	DE
	LD	HL,MODE_OCTET
	LD	BC,6
	LDIR
	LD	HL,OPTION_BLKSIZE
	LD	BC,8
	LDIR
	LD	L,(IX+TFTPR_BLOCK_SIZE)
	LD	H,(IX+TFTPR_BLOCK_SIZE+1)
	CALL	WRITE_DECIMAL
	XOR	A
	LD	(DE),A
	LD	BC,(FTP_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; BUILD_DATA writes the opcode/block header before caller-owned data.
BUILD_DATA
	PUSH	IX,IY
	LD	BC,TFTPD_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.DATA_BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+TFTPD_DATA_LENGTH)
	LD	H,(IX+TFTPD_DATA_LENGTH+1)
	LD	DE,TFTP_MAX_BLOCK+1
	OR	A
	SBC	HL,DE
	JR	NC,.DATA_BAD
	LD	L,(IX+TFTPD_DATA_LENGTH)
	LD	H,(IX+TFTPD_DATA_LENGTH+1)
	LD	DE,4
	ADD	HL,DE
	JR	C,.DATA_BAD
	LD	(FTP_TOTAL),HL
	CALL	VALIDATE_OUTPUT
	JR	C,.DATA_BAD
	LD	E,(IX+TFTPD_BUFFER)
	LD	D,(IX+TFTPD_BUFFER+1)
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,TFTP_OPCODE_DATA
	LD	(DE),A
	INC	DE
	LD	H,(IX+TFTPD_BLOCK+1)
	LD	L,(IX+TFTPD_BLOCK)
	CALL	@ETHERNET.WRITE_BE16
	LD	BC,(FTP_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.DATA_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; BUILD_ACK writes a four-byte ACK.
BUILD_ACK
	PUSH	IX,IY
	LD	BC,TFTPA_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JR	C,.ACK_BAD
	PUSH	HL
	POP	IX
	LD	HL,4
	LD	(FTP_TOTAL),HL
	CALL	VALIDATE_OUTPUT
	JR	C,.ACK_BAD
	LD	E,(IX+TFTPA_BUFFER)
	LD	D,(IX+TFTPA_BUFFER+1)
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,TFTP_OPCODE_ACK
	LD	(DE),A
	INC	DE
	LD	H,(IX+TFTPA_BLOCK+1)
	LD	L,(IX+TFTPA_BLOCK)
	CALL	@ETHERNET.WRITE_BE16
	LD	BC,4
	XOR	A
	POP	IY,IX
	RET
.ACK_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; BUILD_ERROR builds a bounded, zero-terminated ERROR packet.
BUILD_ERROR
	PUSH	IX,IY
	LD	BC,TFTPE_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+TFTPE_MESSAGE_LENGTH)
	LD	H,(IX+TFTPE_MESSAGE_LENGTH+1)
	LD	A,H
	OR	A
	JP	NZ,.BAD
	LD	A,L
	CP	80
	JP	NC,.BAD
	INC	HL
	LD	DE,4
	ADD	HL,DE
	LD	(FTP_TOTAL),HL
	LD	L,(IX+TFTPE_MESSAGE)
	LD	H,(IX+TFTPE_MESSAGE+1)
	LD	C,(IX+TFTPE_MESSAGE_LENGTH)
	LD	B,0
	LD	A,B
	OR	C
	JR	Z,.MESSAGE_OK
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
.MESSAGE_OK
	CALL	VALIDATE_OUTPUT
	JP	C,.BAD
	LD	E,(IX+TFTPE_BUFFER)
	LD	D,(IX+TFTPE_BUFFER+1)
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,TFTP_OPCODE_ERROR
	LD	(DE),A
	INC	DE
	LD	H,(IX+TFTPE_CODE+1)
	LD	L,(IX+TFTPE_CODE)
	CALL	@ETHERNET.WRITE_BE16
	LD	L,(IX+TFTPE_MESSAGE)
	LD	H,(IX+TFTPE_MESSAGE+1)
	LD	C,(IX+TFTPE_MESSAGE_LENGTH)
	LD	B,0
	LD	A,B
	OR	C
	JR	Z,.TERM
	LDIR
.TERM
	XOR	A
	LD	(DE),A
	LD	BC,(FTP_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

; PARSE accepts only complete, well-formed TFTP messages. OACK is restricted
; to the single requested blksize option and values 8..1428.
PARSE
	PUSH	IX,IY
	LD	BC,TFTPP_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PARSE_BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+TFTPP_BUFFER)
	LD	H,(IX+TFTPP_BUFFER+1)
	LD	C,(IX+TFTPP_LENGTH)
	LD	B,(IX+TFTPP_LENGTH+1)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.PARSE_BAD
	LD	A,B
	OR	A
	JP	NZ,.PARSE_LENGTH_OK
	LD	A,C
	CP	2
	JP	C,.PARSE_BAD
.PARSE_LENGTH_OK
	LD	L,(IX+TFTPP_BUFFER)
	LD	H,(IX+TFTPP_BUFFER+1)
	LD	A,(HL)
	OR	A
	JP	NZ,.PARSE_BAD
	INC	HL
	LD	A,(HL)
	LD	(IX+TFTPP_OPCODE),A
	XOR	A
	LD	(IX+TFTPP_OPCODE+1),A
	LD	(IX+TFTPP_DATA_LENGTH),A
	LD	(IX+TFTPP_DATA_LENGTH+1),A
	LD	(IX+TFTPP_ERROR_CODE),A
	LD	(IX+TFTPP_ERROR_CODE+1),A
	LD	(IX+TFTPP_BLOCK_SIZE),A
	LD	(IX+TFTPP_BLOCK_SIZE+1),A
	LD	A,(IX+TFTPP_OPCODE)
	CP	TFTP_OPCODE_DATA
	JR	Z,.PARSE_DATA
	CP	TFTP_OPCODE_ACK
	JR	Z,.PARSE_ACK
	CP	TFTP_OPCODE_ERROR
	JR	Z,.PARSE_ERROR
	CP	TFTP_OPCODE_OACK
	JP	Z,.PARSE_OACK
	JP	.PARSE_BAD
.PARSE_DATA
	CALL	REQUIRE_AT_LEAST_FOUR
	JP	C,.PARSE_BAD
	CALL	READ_BLOCK
	LD	L,(IX+TFTPP_BUFFER)
	LD	H,(IX+TFTPP_BUFFER+1)
	LD	DE,4
	ADD	HL,DE
	LD	(IX+TFTPP_DATA),L
	LD	(IX+TFTPP_DATA+1),H
	LD	L,(IX+TFTPP_LENGTH)
	LD	H,(IX+TFTPP_LENGTH+1)
	OR	A
	SBC	HL,DE
	LD	DE,TFTP_MAX_BLOCK+1
	PUSH	HL
	OR	A
	SBC	HL,DE
	POP	HL
	JP	NC,.PARSE_BAD
	LD	(IX+TFTPP_DATA_LENGTH),L
	LD	(IX+TFTPP_DATA_LENGTH+1),H
	JP	.PARSE_OK
.PARSE_ACK
	CALL	REQUIRE_FOUR
	JP	C,.PARSE_BAD
	CALL	READ_BLOCK
	JP	.PARSE_OK
.PARSE_ERROR
	LD	L,(IX+TFTPP_LENGTH)
	LD	H,(IX+TFTPP_LENGTH+1)
	LD	DE,5
	OR	A
	SBC	HL,DE
	JP	C,.PARSE_BAD
	CALL	READ_BLOCK
	LD	A,(IX+TFTPP_BLOCK)
	LD	(IX+TFTPP_ERROR_CODE),A
	LD	A,(IX+TFTPP_BLOCK+1)
	LD	(IX+TFTPP_ERROR_CODE+1),A
	LD	L,(IX+TFTPP_BUFFER)
	LD	H,(IX+TFTPP_BUFFER+1)
	LD	DE,4
	ADD	HL,DE
	LD	(IX+TFTPP_DATA),L
	LD	(IX+TFTPP_DATA+1),H
	LD	C,(IX+TFTPP_LENGTH)
	LD	B,(IX+TFTPP_LENGTH+1)
	DEC	BC
	DEC	BC
	DEC	BC
	DEC	BC
	CALL	FIND_FINAL_ZERO
	JP	C,.PARSE_BAD
	LD	(IX+TFTPP_DATA_LENGTH),E
	LD	(IX+TFTPP_DATA_LENGTH+1),D
	JR	.PARSE_OK
.PARSE_OACK
	LD	L,(IX+TFTPP_LENGTH)
	LD	H,(IX+TFTPP_LENGTH+1)
	LD	DE,12			; 2 + "blksize" NUL + digit NUL minimum
	OR	A
	SBC	HL,DE
	JP	C,.PARSE_BAD
	LD	L,(IX+TFTPP_BUFFER)
	LD	H,(IX+TFTPP_BUFFER+1)
	INC	HL
	INC	HL
	LD	DE,OPTION_BLKSIZE
	LD	B,7
.OPTION_COMPARE
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	OR	0x20			; RFC option names are case-insensitive ASCII
	CP	C
	JP	NZ,.PARSE_BAD
	INC	DE
	INC	HL
	DJNZ	.OPTION_COMPARE
	LD	A,(HL)
	OR	A
	JP	NZ,.PARSE_BAD
	INC	HL
	LD	C,(IX+TFTPP_LENGTH)
	LD	B,(IX+TFTPP_LENGTH+1)
	LD	DE,10
	LD	A,C
	SUB	E
	LD	C,A
	LD	A,B
	SBC	A,D
	LD	B,A
	CALL	PARSE_DECIMAL_Z
	JP	C,.PARSE_BAD
	CALL	VALID_BLOCK_SIZE
	JP	C,.PARSE_BAD
	LD	(IX+TFTPP_BLOCK_SIZE),L
	LD	(IX+TFTPP_BLOCK_SIZE+1),H
.PARSE_OK
	XOR	A
	POP	IY,IX
	RET
.PARSE_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

REQUIRE_FOUR
	LD	A,(IX+TFTPP_LENGTH+1)
	OR	A
	JR	NZ,.FOUR_BAD
	LD	A,(IX+TFTPP_LENGTH)
	CP	4
	JR	NZ,.FOUR_BAD
	OR	A
	RET
.FOUR_BAD
	SCF
	RET

REQUIRE_AT_LEAST_FOUR
	LD	L,(IX+TFTPP_LENGTH)
	LD	H,(IX+TFTPP_LENGTH+1)
	LD	DE,4
	OR	A
	SBC	HL,DE
	RET

READ_BLOCK
	LD	L,(IX+TFTPP_BUFFER)
	LD	H,(IX+TFTPP_BUFFER+1)
	INC	HL
	INC	HL
	CALL	@ETHERNET.READ_BE16
	LD	(IX+TFTPP_BLOCK),E
	LD	(IX+TFTPP_BLOCK+1),D
	RET

; HL=message, BC=available including terminator. Out DE=message length.
FIND_FINAL_ZERO
	LD	DE,0
.ZERO_SCAN
	LD	A,B
	OR	C
	JR	Z,.ZERO_BAD
	LD	A,(HL)
	INC	HL
	DEC	BC
	OR	A
	JR	Z,.ZERO_FOUND
	INC	DE
	JR	.ZERO_SCAN
.ZERO_FOUND
	LD	A,B
	OR	C			; ERROR must end at its first zero
	JR	NZ,.ZERO_BAD
	OR	A
	RET
.ZERO_BAD
	SCF
	RET

; HL=value. CF=0 only for 8..1428.
VALID_BLOCK_SIZE
	LD	DE,TFTP_MIN_BLOCK
	OR	A
	SBC	HL,DE
	JR	C,.BLOCK_BAD
	ADD	HL,DE
	LD	DE,TFTP_MAX_BLOCK+1
	OR	A
	SBC	HL,DE
	JR	NC,.BLOCK_BAD
	ADD	HL,DE
	OR	A
	RET
.BLOCK_BAD
	SCF
	RET

; IX descriptor begins with BUFFER/CAPACITY; FTP_TOTAL is exact output length.
VALIDATE_OUTPUT
	LD	L,(IX+0)
	LD	H,(IX+1)
	LD	BC,(FTP_TOTAL)
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+2)
	LD	H,(IX+3)
	OR	A
	SBC	HL,BC
	RET

; In HL=value. Out C=decimal digits (1..5).
DECIMAL_LENGTH
	LD	C,1
	LD	DE,10
	OR	A
	SBC	HL,DE
	RET	C
	INC	C
	LD	DE,90
	OR	A
	SBC	HL,DE
	RET	C
	INC	C
	LD	DE,900
	OR	A
	SBC	HL,DE
	RET	C
	INC	C
	LD	DE,9000
	OR	A
	SBC	HL,DE
	RET	C
	INC	C
	RET

; In HL=value, DE=destination. Writes unsigned decimal without terminator.
WRITE_DECIMAL
	XOR	A
	LD	(FTP_DEC_STARTED),A
	LD	BC,-1000
	CALL	.WRITE_DIGIT
	LD	BC,-100
	CALL	.WRITE_DIGIT
	LD	BC,-10
	CALL	.WRITE_DIGIT
	LD	A,L
	ADD	A,'0'
	LD	(DE),A
	INC	DE
	RET
.WRITE_DIGIT
	LD	A,'0'-1
.DIGIT_LOOP
	INC	A
	ADD	HL,BC
	JR	C,.DIGIT_LOOP
	SBC	HL,BC
	CP	'0'
	JR	NZ,.DIGIT_WRITE
	LD	A,(FTP_DEC_STARTED)
	OR	A
	RET	Z			; suppress leading zero
	LD	A,'0'
.DIGIT_WRITE
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(FTP_DEC_STARTED),A
	RET

; HL=first digit, BC=bytes through final packet byte. Requires exactly one
; nonempty decimal string followed by the packet's final zero. Out HL=value.
PARSE_DECIMAL_Z
	LD	DE,0
	LD	A,0
	LD	(FTP_DIGITS),A
.DEC_LOOP
	LD	A,B
	OR	C
	JR	Z,.DEC_BAD
	LD	A,(HL)
	INC	HL
	DEC	BC
	OR	A
	JR	Z,.DEC_END
	CP	'0'
	JR	C,.DEC_BAD
	CP	'9'+1
	JR	NC,.DEC_BAD
	SUB	'0'
	LD	(FTP_DIGIT),A
	LD	A,(FTP_DIGITS)
	INC	A
	LD	(FTP_DIGITS),A
	CP	6
	JR	NC,.DEC_BAD
	PUSH	HL,BC
	LD	H,D
	LD	L,E
	ADD	HL,HL
	JR	C,.DEC_POP_BAD
	LD	B,H
	LD	C,L
	ADD	HL,HL
	JR	C,.DEC_POP_BAD
	ADD	HL,HL
	JR	C,.DEC_POP_BAD
	ADD	HL,BC
	JR	C,.DEC_POP_BAD
	LD	A,(FTP_DIGIT)
	LD	C,A
	LD	B,0
	ADD	HL,BC
	JR	C,.DEC_POP_BAD
	EX	DE,HL
	POP	BC,HL
	JR	.DEC_LOOP
.DEC_END
	LD	A,(FTP_DIGITS)
	OR	A
	JR	Z,.DEC_BAD
	LD	A,B
	OR	C
	JR	NZ,.DEC_BAD
	EX	DE,HL
	OR	A
	RET
.DEC_POP_BAD
	POP	BC,HL
.DEC_BAD
	SCF
	RET

MODE_OCTET	DB "octet",0
OPTION_BLKSIZE	DB "blksize",0
FTP_TOTAL	DW 0
FTP_DIGITS	DB 0
FTP_DIGIT	DB 0
FTP_DEC_STARTED DB 0

	ENDMODULE
	ENDIF
