; Strict RFC 768 UDP codec with caller-owned buffers.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_UDP_ASM
	DEFINE	_UDP_ASM

	INCLUDE "netdrv.inc"
	INCLUDE "udp_tftp.inc"

	MODULE UDP

; BUILD
; In: HL -> UDPB descriptor; payload is already at BUFFER+8.
; Out: BC=UDP length, A=0/CF=0. The transmitted checksum is never zero.
; Clobbers AF/BC/DE/HL; preserves IX/IY.
BUILD
	PUSH	IX,IY
	LD	BC,UDPB_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	CALL	VALIDATE_BUILD
	JP	C,.BAD
	LD	E,(IX+UDPB_BUFFER)
	LD	D,(IX+UDPB_BUFFER+1)
	LD	H,(IX+UDPB_SOURCE_PORT+1)
	LD	L,(IX+UDPB_SOURCE_PORT)
	CALL	@ETHERNET.WRITE_BE16
	LD	H,(IX+UDPB_DESTINATION_PORT+1)
	LD	L,(IX+UDPB_DESTINATION_PORT)
	CALL	@ETHERNET.WRITE_BE16
	LD	HL,(UDP_TOTAL)
	CALL	@ETHERNET.WRITE_BE16
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	CALL	CHECKSUM_DESC
	LD	A,H
	OR	L
	JR	NZ,.CHECKSUM_READY
	LD	HL,0xFFFF		; RFC 768 encodes a computed zero as all ones
.CHECKSUM_READY
	LD	E,(IX+UDPB_BUFFER)
	LD	D,(IX+UDPB_BUFFER+1)
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	INC	DE
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	LD	BC,(UDP_TOTAL)
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

VALIDATE_BUILD
	LD	L,(IX+UDPB_PAYLOAD_LENGTH)
	LD	H,(IX+UDPB_PAYLOAD_LENGTH+1)
	LD	DE,UDP_MAX_PAYLOAD+1
	OR	A
	SBC	HL,DE
	JR	C,.PAYLOAD_OK
	SCF
	RET
.PAYLOAD_OK
	LD	L,(IX+UDPB_PAYLOAD_LENGTH)
	LD	H,(IX+UDPB_PAYLOAD_LENGTH+1)
	LD	DE,UDP_HEADER_LENGTH
	ADD	HL,DE
	RET	C
	LD	(UDP_TOTAL),HL
	LD	E,(IX+UDPB_CAPACITY)
	LD	D,(IX+UDPB_CAPACITY+1)
	OR	A
	SBC	HL,DE
	JR	C,.CAPACITY_OK
	JR	Z,.CAPACITY_OK
	SCF
	RET
	; Exact capacity is also valid.
.CAPACITY_OK
	LD	L,(IX+UDPB_BUFFER)
	LD	H,(IX+UDPB_BUFFER+1)
	LD	BC,(UDP_TOTAL)
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+UDPB_SOURCE_IP)
	LD	H,(IX+UDPB_SOURCE_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+UDPB_DESTINATION_IP)
	LD	H,(IX+UDPB_DESTINATION_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	RET	C
	LD	L,(IX+UDPB_DESTINATION_PORT)
	LD	H,(IX+UDPB_DESTINATION_PORT+1)
	LD	A,H
	OR	L
	JR	Z,.INVALID
	OR	A
	RET
.INVALID
	SCF
	RET

; PARSE
; In: HL -> UDPP descriptor. LENGTH must equal the UDP length field exactly.
; UDP checksum 0000 is accepted for IPv4; any nonzero checksum must verify.
; Out: payload pointer/length and both ports in the descriptor. Preserves IX/IY.
PARSE
	PUSH	IX,IY
	LD	BC,UDPP_DESC_LENGTH
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	PUSH	HL
	POP	IX
	LD	L,(IX+UDPP_BUFFER)
	LD	H,(IX+UDPP_BUFFER+1)
	LD	C,(IX+UDPP_LENGTH)
	LD	B,(IX+UDPP_LENGTH+1)
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+UDPP_SOURCE_IP)
	LD	H,(IX+UDPP_SOURCE_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+UDPP_DESTINATION_IP)
	LD	H,(IX+UDPP_DESTINATION_IP+1)
	LD	BC,4
	CALL	@IPV4.VALIDATE_REGION
	JP	C,.BAD
	LD	L,(IX+UDPP_LENGTH)
	LD	H,(IX+UDPP_LENGTH+1)
	LD	DE,UDP_HEADER_LENGTH
	OR	A
	SBC	HL,DE
	JP	C,.BAD
	LD	DE,UDP_MAX_PAYLOAD+1
	OR	A
	SBC	HL,DE
	JP	NC,.BAD
	LD	L,(IX+UDPP_BUFFER)
	LD	H,(IX+UDPP_BUFFER+1)
	LD	DE,4
	ADD	HL,DE
	CALL	@ETHERNET.READ_BE16
	LD	L,(IX+UDPP_LENGTH)
	LD	H,(IX+UDPP_LENGTH+1)
	OR	A
	SBC	HL,DE
	JP	NZ,.BAD
	LD	(UDP_TOTAL),DE
	LD	L,(IX+UDPP_BUFFER)
	LD	H,(IX+UDPP_BUFFER+1)
	CALL	@ETHERNET.READ_BE16
	LD	(IX+UDPP_SOURCE_PORT),E
	LD	(IX+UDPP_SOURCE_PORT+1),D
	LD	A,(IX+UDPP_EXPECT_SOURCE_PORT)
	LD	C,A
	LD	A,(IX+UDPP_EXPECT_SOURCE_PORT+1)
	OR	C
	JR	Z,.SOURCE_PORT_OK
	LD	A,(IX+UDPP_EXPECT_SOURCE_PORT)
	CP	E
	JP	NZ,.BAD
	LD	A,(IX+UDPP_EXPECT_SOURCE_PORT+1)
	CP	D
	JP	NZ,.BAD
.SOURCE_PORT_OK
	CALL	@ETHERNET.READ_BE16
	LD	(IX+UDPP_DESTINATION_PORT),E
	LD	(IX+UDPP_DESTINATION_PORT+1),D
	LD	A,(IX+UDPP_EXPECT_DEST_PORT)
	CP	E
	JP	NZ,.BAD
	LD	A,(IX+UDPP_EXPECT_DEST_PORT+1)
	CP	D
	JP	NZ,.BAD
	INC	HL
	INC	HL			; length -> checksum
	LD	A,(HL)
	INC	HL
	OR	(HL)
	JR	Z,.CHECKSUM_OK
	CALL	CHECKSUM_PARSE_DESC
	LD	A,H
	OR	L
	JP	NZ,.BAD
.CHECKSUM_OK
	LD	L,(IX+UDPP_BUFFER)
	LD	H,(IX+UDPP_BUFFER+1)
	LD	DE,UDP_HEADER_LENGTH
	ADD	HL,DE
	LD	(IX+UDPP_PAYLOAD),L
	LD	(IX+UDPP_PAYLOAD+1),H
	LD	HL,(UDP_TOTAL)
	OR	A
	SBC	HL,DE
	LD	(IX+UDPP_PAYLOAD_LENGTH),L
	LD	(IX+UDPP_PAYLOAD_LENGTH+1),H
	XOR	A
	POP	IY,IX
	RET
.BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	POP	IY,IX
	RET

CHECKSUM_DESC
	PUSH	IX
	LD	L,(IX+UDPB_SOURCE_IP)
	LD	H,(IX+UDPB_SOURCE_IP+1)
	LD	E,(IX+UDPB_DESTINATION_IP)
	LD	D,(IX+UDPB_DESTINATION_IP+1)
	LD	C,(IX+UDPB_BUFFER)
	LD	B,(IX+UDPB_BUFFER+1)
	CALL	CHECKSUM_COMMON
	POP	IX
	RET

CHECKSUM_PARSE_DESC
	PUSH	IX
	LD	L,(IX+UDPP_SOURCE_IP)
	LD	H,(IX+UDPP_SOURCE_IP+1)
	LD	E,(IX+UDPP_DESTINATION_IP)
	LD	D,(IX+UDPP_DESTINATION_IP+1)
	LD	C,(IX+UDPP_BUFFER)
	LD	B,(IX+UDPP_BUFFER+1)
	CALL	CHECKSUM_COMMON
	POP	IX
	RET

; HL=source IP, DE=destination IP, BC=UDP pointer, UDP_TOTAL=length.
CHECKSUM_COMMON
	LD	(UDP_SOURCE_PTR),HL
	LD	(UDP_DEST_PTR),DE
	LD	(UDP_BUFFER_PTR),BC
	LD	DE,0
	LD	BC,4
	CALL	@ETHERNET.ACCUMULATE
	LD	HL,(UDP_DEST_PTR)
	LD	BC,4
	CALL	@ETHERNET.ACCUMULATE
	LD	HL,IPV4_PROTOCOL_UDP
	CALL	ADD_ACCUMULATOR
	LD	HL,(UDP_TOTAL)
	CALL	ADD_ACCUMULATOR
	LD	HL,(UDP_BUFFER_PTR)
	LD	BC,(UDP_TOTAL)
	CALL	@ETHERNET.ACCUMULATE
	LD	A,D
	CPL
	LD	H,A
	LD	A,E
	CPL
	LD	L,A
	RET

ADD_ACCUMULATOR
	ADD	HL,DE
	EX	DE,HL
	RET	NC
	INC	DE
	RET

UDP_TOTAL	DW 0
UDP_SOURCE_PTR	DW 0
UDP_DEST_PTR	DW 0
UDP_BUFFER_PTR	DW 0

	ENDMODULE
	ENDIF
