; Polling-only Ethernet/IPv4/UDP transport shared by UDPTEST and TFTP.
; SPDX-License-Identifier: BSD-3-Clause

	IFNDEF	_UDP_TRANSPORT_ASM
	DEFINE	_UDP_TRANSPORT_ASM

	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"

	MODULE UDPX

ICMP_PROTOCOL		EQU 1
ICMP_UNREACHABLE	EQU 3
ICMP_ECHO_REQUEST_TYPE	EQU 8

; OPEN
; In: HL=target IPv4, BC=remote port, DE=local port. Resolves the route/cache
; with three bounded ARP requests. Out: stable status, IX/IY preserved.
OPEN
	PUSH	IX,IY
	LD	(S9_REMOTE_PORT),BC
	LD	(S9_EXPECT_REMOTE_PORT),BC
	LD	(S9_LOCAL_PORT),DE
	CALL	@ARP.SELECT_NEXT_HOP
	JP	C,.RETURN
	OR	A
	JR	NZ,.OK			; broadcast MAC already selected
	CALL	@S9APP.SECONDS
	LD	C,A
	LD	B,0
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.CACHE_LOOKUP
	JR	NC,.OK
	LD	A,3
	LD	(ARP_RETRY_LEFT),A
.ARP_TRY
	LD	DE,STAGE9_TX_BUFFER
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,STAGE9_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	JR	C,.RETURN
	CALL	WAIT_ARP
	JR	NC,.CACHE
	CP	NETDRV_ERR_CANCELLED
	JR	NZ,.ARP_RETRY
	SCF
	JR	.RETURN
.ARP_RETRY
	LD	A,(ARP_RETRY_LEFT)
	DEC	A
	LD	(ARP_RETRY_LEFT),A
	JR	NZ,.ARP_TRY
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	JR	.RETURN
.CACHE
	CALL	@S9APP.SECONDS
	LD	C,A
	LD	B,0
	LD	HL,NET_NEXT_HOP_IP
	LD	DE,NET_RESULT_MAC
	CALL	@ARP.CACHE_INSERT
.OK
	XOR	A
.RETURN
	POP	IY,IX
	RET

WAIT_ARP
	LD	BC,2000
	CALL	@NETTIME.START
	RET	C
.POLL
	CALL	CHECK_CANCEL
	JR	C,.CANCEL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.TICK
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,STAGE9_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	C,.READ_ERROR
	LD	(S9_RX_LENGTH),BC
	LD	HL,STAGE9_RX_BUFFER
	CALL	@ARP.PARSE
	JR	C,.TICK
	CP	1
	JR	Z,.FOUND
	CP	2
	JR	NZ,.TICK
	LD	DE,STAGE9_TX_BUFFER
	LD	HL,STAGE9_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE9_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
.TICK
	CALL	@NETTIME.TICK
	JR	NC,.POLL
	RET
.READ_ERROR
	CP	EL3_ERR_RX_ERROR
	JR	Z,.TICK
	CP	EL3_ERR_FRAME_SIZE
	JR	Z,.TICK
	CP	EL3_ERR_NO_FRAME
	JR	Z,.TICK
	RET
.FOUND
	XOR	A
	RET
.CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

; SET_REMOTE_PORT changes the connected peer port after a TFTP server TID is
; latched. In HL=port; zero is rejected.
SET_REMOTE_PORT
	LD	A,H
	OR	L
	JR	Z,.PORT_BAD
	LD	(S9_REMOTE_PORT),HL
	XOR	A
	RET
.PORT_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET

SET_EXPECT_PORT
	LD	(S9_EXPECT_REMOTE_PORT),HL
	XOR	A
	RET

; SEND transmits payload already at STAGE9_TX_BUFFER+42. In BC=0..1472.
SEND
	PUSH	IX,IY
	LD	(S9_RX_PAYLOAD_LENGTH),BC
	CALL	BUILD_ETHERNET
	LD	HL,STAGE9_TX_BUFFER+34
	LD	(S9_UDP_BUILD_DESC+UDPB_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-34
	LD	(S9_UDP_BUILD_DESC+UDPB_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_UDP_BUILD_DESC+UDPB_SOURCE_IP),HL
	LD	HL,NET_TARGET_IP
	LD	(S9_UDP_BUILD_DESC+UDPB_DESTINATION_IP),HL
	LD	HL,(S9_RX_PAYLOAD_LENGTH)
	LD	(S9_UDP_BUILD_DESC+UDPB_PAYLOAD_LENGTH),HL
	LD	HL,(S9_LOCAL_PORT)
	LD	(S9_UDP_BUILD_DESC+UDPB_SOURCE_PORT),HL
	LD	HL,(S9_REMOTE_PORT)
	LD	(S9_UDP_BUILD_DESC+UDPB_DESTINATION_PORT),HL
	LD	HL,S9_UDP_BUILD_DESC
	CALL	@UDP.BUILD
	JR	C,.RETURN
	LD	(S9_IPV4_BUILD_DESC+IP4B_DATA_LENGTH),BC
	LD	HL,STAGE9_TX_BUFFER+14
	LD	(S9_IPV4_BUILD_DESC+IP4B_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-14
	LD	(S9_IPV4_BUILD_DESC+IP4B_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_IPV4_BUILD_DESC+IP4B_SOURCE),HL
	LD	HL,NET_TARGET_IP
	LD	(S9_IPV4_BUILD_DESC+IP4B_DESTINATION),HL
	LD	HL,(S9_IP_ID)
	LD	(S9_IPV4_BUILD_DESC+IP4B_IDENTIFIER),HL
	INC	HL
	LD	(S9_IP_ID),HL
	LD	A,64
	LD	(S9_IPV4_BUILD_DESC+IP4B_TTL),A
	LD	A,IPV4_PROTOCOL_UDP
	LD	(S9_IPV4_BUILD_DESC+IP4B_PROTOCOL),A
	LD	HL,S9_IPV4_BUILD_DESC
	CALL	@IPV4.BUILD
	JR	C,.RETURN
	LD	HL,14
	ADD	HL,BC
	LD	B,H
	LD	C,L
	LD	HL,STAGE9_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
.RETURN
	POP	IY,IX
	RET

BUILD_ETHERNET
	LD	HL,NET_RESULT_MAC
	LD	DE,STAGE9_TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	RET

; WAIT receives one matched datagram within BC milliseconds. Every RX entry is
; consumed once; up to four are drained per time quantum. Out: HL=payload,
; BC=length, DE=source port, S9_REPLY_TTL set. Stale/noise never extends time.
WAIT
	PUSH	IX,IY
	CALL	@NETTIME.START
	JR	C,WAIT_RETURN
	JR	WAIT_LIVE
WAIT_CONTINUE
	PUSH	IX,IY
WAIT_LIVE
.POLL
	CALL	CHECK_CANCEL
	JR	C,WAIT_CANCEL
	LD	A,4
	LD	(S9_DRAIN_LEFT),A
.DRAIN
	CALL	@NETDRV.RX_PENDING
	JR	C,WAIT_RETURN
	OR	A
	JR	Z,.TICK
	CALL	READ_PROCESS
	JR	C,WAIT_RETURN
	CP	1
	JR	Z,.MATCH
	LD	A,(S9_DRAIN_LEFT)
	DEC	A
	LD	(S9_DRAIN_LEFT),A
	JR	NZ,.DRAIN
.TICK
	CALL	@NETTIME.TICK
	JR	NC,.POLL
	JR	WAIT_RETURN
.MATCH
	LD	HL,(S9_RX_PAYLOAD)
	LD	BC,(S9_RX_PAYLOAD_LENGTH)
	LD	DE,(S9_RX_SOURCE_PORT)
	XOR	A
WAIT_CANCEL_CHECK
	JR	WAIT_RETURN
WAIT_CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
WAIT_RETURN
	POP	IY,IX
	RET

READ_PROCESS
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,STAGE9_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	NC,.READ_OK
	CP	EL3_ERR_RX_ERROR
	JR	Z,.IGNORE
	CP	EL3_ERR_FRAME_SIZE
	JR	Z,.IGNORE
	CP	EL3_ERR_NO_FRAME
	JR	Z,.IGNORE
	RET
.READ_OK
	LD	(S9_RX_LENGTH),BC
	JP	PROCESS_FRAME
.IGNORE
	XOR	A
	RET

PROCESS_FRAME
	LD	HL,(S9_RX_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	JP	C,.IGNORE
	LD	A,(STAGE9_RX_BUFFER+12)
	CP	0x08
	JP	NZ,.IGNORE
	LD	A,(STAGE9_RX_BUFFER+13)
	CP	0x06
	JP	Z,.ARP
	OR	A
	JP	NZ,.IGNORE
	LD	A,(STAGE9_RX_BUFFER+23)
	CP	IPV4_PROTOCOL_UDP
	JR	Z,.UDP
	CP	ICMP_PROTOCOL
	JP	NZ,.IGNORE
	LD	HL,0
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_SOURCE),HL
	LD	A,ICMP_PROTOCOL
	CALL	PARSE_IP
	JP	C,.IGNORE
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_DATA)
	LD	A,(HL)
	CP	ICMP_ECHO_REQUEST_TYPE
	JP	Z,.ECHO_REQUEST
	CP	ICMP_UNREACHABLE
	JP	NZ,.IGNORE
	LD	BC,(S9_IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	CALL	PARSE_UDP_UNREACHABLE
	JP	C,.IGNORE
	LD	A,NETDRV_ERR_UNREACHABLE
	SCF
	RET
.UDP
	LD	HL,NET_TARGET_IP
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_SOURCE),HL
	LD	A,IPV4_PROTOCOL_UDP
	CALL	PARSE_IP
	JP	C,.IGNORE
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_DATA)
	LD	(S9_UDP_PARSE_DESC+UDPP_BUFFER),HL
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	(S9_UDP_PARSE_DESC+UDPP_LENGTH),HL
	LD	HL,NET_TARGET_IP
	LD	(S9_UDP_PARSE_DESC+UDPP_SOURCE_IP),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_UDP_PARSE_DESC+UDPP_DESTINATION_IP),HL
	LD	HL,(S9_EXPECT_REMOTE_PORT)
	LD	(S9_UDP_PARSE_DESC+UDPP_EXPECT_SOURCE_PORT),HL
	LD	HL,(S9_LOCAL_PORT)
	LD	(S9_UDP_PARSE_DESC+UDPP_EXPECT_DEST_PORT),HL
	LD	HL,S9_UDP_PARSE_DESC
	CALL	@UDP.PARSE
	JP	C,.IGNORE
	LD	HL,(S9_UDP_PARSE_DESC+UDPP_PAYLOAD)
	LD	(S9_RX_PAYLOAD),HL
	LD	HL,(S9_UDP_PARSE_DESC+UDPP_PAYLOAD_LENGTH)
	LD	(S9_RX_PAYLOAD_LENGTH),HL
	LD	HL,(S9_UDP_PARSE_DESC+UDPP_SOURCE_PORT)
	LD	(S9_RX_SOURCE_PORT),HL
	LD	A,(S9_IPV4_PARSE_DESC+IP4P_TTL)
	LD	(S9_REPLY_TTL),A
	LD	A,1
	OR	A
	RET
.ARP
	LD	HL,STAGE9_RX_BUFFER
	LD	BC,(S9_RX_LENGTH)
	CALL	@ARP.PARSE
	JR	C,.IGNORE
	CP	2
	JR	NZ,.IGNORE
	LD	DE,STAGE9_TX_BUFFER
	LD	HL,STAGE9_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE9_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	JR	.IGNORE
.ECHO_REQUEST
	CALL	ANSWER_ECHO
	JR	NC,.IGNORE
	CP	NETDRV_ERR_PARAMETER
	JR	Z,.IGNORE
	RET
.IGNORE
	XOR	A
	RET

; In A=protocol. Parses the Ethernet payload with exact local destination.
PARSE_IP
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_PROTOCOL),A
	LD	HL,STAGE9_RX_BUFFER+14
	LD	(S9_IPV4_PARSE_DESC+IP4P_BUFFER),HL
	LD	HL,(S9_RX_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	LD	(S9_IPV4_PARSE_DESC+IP4P_LENGTH),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_IPV4_PARSE_DESC+IP4P_EXPECT_DESTINATION),HL
	LD	HL,S9_IPV4_PARSE_DESC
	JP	@IPV4.PARSE

ANSWER_ECHO
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_SOURCE)
	LD	DE,S9_INCOMING_IP
	LD	BC,4
	LDIR
	LD	HL,STAGE9_RX_BUFFER+6
	LD	DE,STAGE9_TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_DATA)
	LD	(S9_ICMP_COPY_DESC+ICMPC_SOURCE),HL
	LD	HL,(S9_IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	(S9_ICMP_COPY_DESC+ICMPC_LENGTH),HL
	LD	HL,STAGE9_TX_BUFFER+34
	LD	(S9_ICMP_COPY_DESC+ICMPC_DESTINATION),HL
	LD	HL,STAGE9_TX_CAPACITY-34
	LD	(S9_ICMP_COPY_DESC+ICMPC_CAPACITY),HL
	LD	HL,S9_ICMP_COPY_DESC
	CALL	@ICMP.BUILD_ECHO_REPLY
	RET	C
	LD	(S9_IPV4_BUILD_DESC+IP4B_DATA_LENGTH),BC
	LD	HL,STAGE9_TX_BUFFER+14
	LD	(S9_IPV4_BUILD_DESC+IP4B_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-14
	LD	(S9_IPV4_BUILD_DESC+IP4B_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(S9_IPV4_BUILD_DESC+IP4B_SOURCE),HL
	LD	HL,S9_INCOMING_IP
	LD	(S9_IPV4_BUILD_DESC+IP4B_DESTINATION),HL
	LD	HL,(S9_IP_ID)
	INC	HL
	LD	(S9_IP_ID),HL
	LD	(S9_IPV4_BUILD_DESC+IP4B_IDENTIFIER),HL
	LD	A,64
	LD	(S9_IPV4_BUILD_DESC+IP4B_TTL),A
	LD	A,ICMP_PROTOCOL
	LD	(S9_IPV4_BUILD_DESC+IP4B_PROTOCOL),A
	LD	HL,S9_IPV4_BUILD_DESC
	CALL	@IPV4.BUILD
	RET	C
	LD	HL,14
	ADD	HL,BC
	LD	B,H
	LD	C,L
	LD	HL,STAGE9_TX_BUFFER
	JP	@NETDRV.SEND_FRAME

; Match ICMP Destination Unreachable quoting our current UDP tuple.
PARSE_UDP_UNREACHABLE
	LD	(S9_RX_PAYLOAD),HL
	LD	HL,36
	OR	A
	SBC	HL,BC
	JR	C,.LEN_OK
	JR	Z,.LEN_OK
	SCF
	RET
.LEN_OK
	LD	HL,(S9_RX_PAYLOAD)
	LD	A,(HL)
	CP	ICMP_UNREACHABLE
	JP	NZ,.BAD
	INC	HL
	LD	A,(HL)
	CP	16
	JP	NC,.BAD
	LD	HL,(S9_RX_PAYLOAD)
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JR	C,.BAD
	LD	HL,(S9_RX_PAYLOAD)
	LD	DE,8
	ADD	HL,DE
	LD	A,(HL)
	CP	0x45
	JR	NZ,.BAD
	PUSH	HL
	LD	DE,6
	ADD	HL,DE
	LD	A,(HL)
	AND	0xBF
	JR	NZ,.POP_BAD
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,.POP_BAD
	INC	HL
	INC	HL
	LD	A,(HL)
	CP	IPV4_PROTOCOL_UDP
	JR	NZ,.POP_BAD
	POP	HL
	PUSH	HL
	LD	BC,20
	CALL	@ETHERNET.VERIFY_CHECKSUM
	POP	HL
	JR	C,.BAD
	LD	DE,12
	ADD	HL,DE
	LD	DE,NET_LOCAL_IP
	CALL	CMP4
	JR	NZ,.BAD
	LD	HL,(S9_RX_PAYLOAD)
	LD	DE,8+16
	ADD	HL,DE
	LD	DE,NET_TARGET_IP
	CALL	CMP4
	JR	NZ,.BAD
	LD	HL,(S9_RX_PAYLOAD)
	LD	DE,8+20
	ADD	HL,DE
	CALL	@ETHERNET.READ_BE16
	LD	(S9_RX_SOURCE_PORT),DE
	CALL	@ETHERNET.READ_BE16
	LD	(S9_RX_PAYLOAD_LENGTH),DE
	LD	DE,(S9_RX_SOURCE_PORT)
	LD	HL,(S9_LOCAL_PORT)
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	LD	DE,(S9_RX_PAYLOAD_LENGTH)
	LD	HL,(S9_REMOTE_PORT)
	OR	A
	SBC	HL,DE
	JR	NZ,.BAD
	XOR	A
	RET
.POP_BAD
	POP	HL
.BAD
	SCF
	RET

CMP4
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP
	RET

CHECK_CANCEL
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.NO
	LD	A,E
	CP	0x1B
	JR	Z,.YES
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.NO
	LD	A,D
	CP	0xAC
	JR	Z,.YES
.NO
	XOR	A
	RET
.YES
	SCF
	RET

	ENDMODULE
	ENDIF
