; ARP.EXE - bounded ARP resolver/cache diagnostic (IMG only).
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	@S7APP.CLEAR
	CALL	@ARP.CLEAR_CACHE
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	PARSE_ARGS
	JP	C,USAGE
	LD	A,(ARP_HELP)
	OR	A
	JP	NZ,HELP_ONLY
	CALL	@S7APP.ALLOCATE
	JP	C,LOCAL_FAIL
	CALL	@S7APP.LOAD_ENV_CONFIG
	JP	C,CONFIG_FAIL
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_STATIC
	CALL	@NETPARSE.STR_EQ_CI
	JP	NZ,CONFIG_FAIL
	CALL	@S7APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JR	NC,.LINK_OK
	LD	(NETDRV_FAIL_CODE),A
	CP	EL3_ERR_LINK_TIMEOUT
	CALL	Z,PRINT_LINK_TIMEOUT
	LD	A,(NETDRV_FAIL_CODE)
	JP	NETWORK_FAIL
.LINK_OK
	LD	HL,NET_TARGET_IP
	CALL	@ARP.SELECT_NEXT_HOP
	JP	C,CONFIG_FAIL
	OR	A
	JP	NZ,BROADCAST_OK
	LD	HL,NET_NEXT_HOP_IP
	LD	BC,0
	CALL	@ARP.CACHE_LOOKUP
	JR	NC,RESOLVED
	LD	A,3
	LD	(ARP_RETRY_LEFT),A
	CALL	@S7APP.WAIT_SECOND_EDGE
	JP	C,NETWORK_FAIL
.ATTEMPT
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	JP	C,NETWORK_FAIL
	CALL	WAIT_ARP
	JR	NC,.CACHE
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	LD	A,(ARP_RETRY_LEFT)
	DEC	A
	LD	(ARP_RETRY_LEFT),A
	JR	NZ,.ATTEMPT
	CALL	PRINT_ARP_TIMEOUT
	LD	A,EL3_ERR_RX_TIMEOUT
	JP	NETWORK_FAIL
.CACHE
	LD	HL,NET_NEXT_HOP_IP
	LD	DE,NET_RESULT_MAC
	LD	BC,0
	CALL	@ARP.CACHE_INSERT
RESOLVED
	LD	HL,MSG_REPLY
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IP
	LD	HL,MSG_VIA
	CALL	@CONSOLE.STRING
	LD	HL,NET_NEXT_HOP_IP
	CALL	PRINT_IP
	LD	HL,MSG_MAC
	CALL	@CONSOLE.STRING
	LD	HL,NET_RESULT_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

BROADCAST_OK
	LD	HL,MSG_BROADCAST
	CALL	@CONSOLE.STRING
	LD	HL,NET_RESULT_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

; Wait two aligned wall-clock seconds. Requests for our IP are answered and the
; original RX entry is already consumed before the reply is transmitted.
WAIT_ARP
	CALL	@S7APP.SECONDS
	LD	(ARP_START_SECOND),A
.POLL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.TICK
	LD	HL,STAGE7_RX_BUFFER
	LD	BC,STAGE7_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	C,.TICK
	LD	(ARP_RX_LENGTH),BC
	LD	HL,STAGE7_RX_BUFFER
	CALL	@ARP.PARSE
	JR	C,.TICK
	CP	1
	JR	Z,.FOUND
	CP	2
	JR	NZ,.TICK
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,STAGE7_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	JR	.TICK
.FOUND
	XOR	A
	RET
.TICK
	CALL	@S7APP.WAIT_TICK
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.TIME
	LD	A,E
	CP	0x1B
	JR	Z,.CANCEL
	LD	A,B
	AND	3
	JR	Z,.TIME
	LD	A,D
	CP	0x2E
	JR	Z,.CANCEL
.TIME
	CALL	@S7APP.SECONDS
	LD	B,A
	LD	A,(ARP_START_SECOND)
	LD	C,A
	LD	A,B
	SUB	C
	JR	NC,.ELAPSED
	ADD	A,60
.ELAPSED
	LD	(ARP_LAST_ELAPSED),A
	CP	2
	JR	C,.POLL
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

; One positional IPv4 plus optional -v. The target is copied and NUL-terminated
; before the common bounded parser is called.
PARSE_ARGS
	LD	HL,(CMDLINE_SOURCE)
	LD	B,(HL)
	INC	HL
	LD	DE,NETCFG_SCRATCH
	LD	C,0
.SKIP
	LD	A,B
	OR	A
	JP	Z,.BAD
	LD	A,(HL)
	CP	' '
	JR	Z,.SKIP_ONE
	CP	9
	JR	NZ,.TOKEN
.SKIP_ONE
	INC	HL
	DEC	B
	JR	.SKIP
.TOKEN
	CP	'-'
	JR	Z,.FLAG_FIRST
	CP	'/'
	JR	Z,.FLAG_FIRST
.COPY
	LD	A,B
	OR	A
	JR	Z,.TERM
	LD	A,(HL)
	CP	' '
	JR	Z,.TERM
	CP	9
	JR	Z,.TERM
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	INC	C
	LD	A,C
	CP	16
	JR	NC,.BAD
	JR	.COPY
.TERM
	XOR	A
	LD	(DE),A
	LD	HL,NETCFG_SCRATCH
	LD	DE,NET_TARGET_IP
	CALL	@NETPARSE.PARSE_IPV4
	RET	C
	; Remaining non-space token, if any, must be -v.
.REST
	LD	A,B
	OR	A
	JR	Z,.OK
	LD	A,(HL)
	INC	HL
	DEC	B
	CP	' '
	JR	Z,.REST
	CP	9
	JR	Z,.REST
	CP	'-'
	JR	Z,.FLAG
	CP	'/'
	JR	NZ,.BAD
.FLAG
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	A,(HL)
	CALL	@NETPARSE.UPPER_A
	CP	'V'
	JR	NZ,.BAD
	INC	HL
	DEC	B
	JR	.REST
.FLAG_FIRST
	INC	HL
	DEC	B
	LD	A,(HL)
	CP	'?'
	JR	Z,.HELP
	CALL	@NETPARSE.UPPER_A
	CP	'H'
	JR	Z,.HELP
	CP	'V'
	JR	NZ,.BAD
	INC	HL
	DEC	B
	LD	A,1
	LD	(ARP_VERBOSE),A
	JP	.SKIP
.HELP
	LD	A,1
	LD	(ARP_HELP),A
.OK
	XOR	A
	RET
.BAD
	SCF
	RET

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(ARP_EXIT_CODE),A
	XOR	A
	CALL	@S7APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
HELP_ONLY
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
USAGE
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	A,NETDRV_ERR_CONFIG
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(ARP_EXIT_CODE),A
	LD	A,C
	CALL	@S7APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(ARP_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

PRINT_IP
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,ENV_SET_BUFFER
	JP	@CONSOLE.STRING

PRINT_LINK_TIMEOUT
	LD	HL,MSG_LINK_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	CALL	PRINT_DEVICE_STATUS
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_ARP_TIMEOUT
	LD	HL,MSG_ARP_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	A,(ARP_LAST_ELAPSED)
	CALL	@CONSOLE.DEC8
	CALL	PRINT_DEVICE_STATUS
	LD	HL,MSG_TARGET
	CALL	@CONSOLE.STRING
	LD	HL,NET_NEXT_HOP_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_DEVICE_STATUS
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	JP	@CONSOLE.HEX16

MSG_BANNER	DB "3C509B ARP v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: ARP [-v] target",0
MSG_REPLY	DB "[A2] REPLY target=",0
MSG_VIA		DB " via=",0
MSG_MAC		DB " MAC=",0
MSG_BROADCAST	DB "[A1] BROADCAST MAC=",0
MSG_LINK_TIMEOUT DB "[A0] TIMEOUT stage=LINK elapsed_waitq=#",0
MSG_ARP_TIMEOUT DB "[A1] TIMEOUT stage=ARP elapsed_sec=",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=#",0
MSG_TARGET	DB " target=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
VALUE_STATIC	DB "STATIC",0
ARP_START_SECOND DB 0
ARP_LAST_ELAPSED DB 0
ARP_EXIT_CODE	DB DSS_EXIT_NETWORK
ARP_HELP	DB 0
ARP_VERBOSE	DB 0

	ENDMODULE

	ASSERT $ < 0xC000

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "netparse.asm"
	INCLUDE "netenv.asm"
	INCLUDE "stage7_app.asm"
