; DLSPEED.EXE - HTTP download throughput through UNET509B.DLL/libman.
; Development/measurement tool only: diagnostic IMG, never the release ZIP.
; SPDX-License-Identifier: BSD-3-Clause
;
; Timing begins immediately before SEND after the connection is established
; and ends on the last response-body byte, before CLOSE/NETDONE/l_free. The
; body is discarded from a 6 KiB receive buffer and is never written to disk.

EXE_VERSION	EQU 1
	DEFINE LIBMAN_EXTERNAL_TABLE

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "unet.inc"
	INCLUDE "http_stream.inc"

; Fixed runtime layout. None of it is emitted into the EXE image.
RX_BUFFER		EQU 0xA000
RX_BUFFER_SIZE		EQU 0x1800
HTTP_STATE_VAR		EQU 0xB800
HTTP_STATUS_VAR		EQU 0xB801
HTTP_HEADER_LENGTH_VAR	EQU 0xB803
HTTP_CONTENT_KNOWN_VAR	EQU 0xB804
HTTP_CONTENT_LENGTH_VAR	EQU 0xB805
HTTP_BODY_RECEIVED_VAR	EQU 0xB809
HTTP_WORK32_VAR		EQU 0xB80D
HTTP_ERROR_VAR		EQU 0xB811
HTTP_STATUS_SEEN_VAR	EQU 0xB812
HTTP_HEADER_LINE_VAR	EQU 0xB820
URL_BUFFER		EQU 0xB920
HOST_BUFFER		EQU 0xBA20
PATH_BUFFER		EQU 0xBA60
PORT_BUFFER		EQU 0xBB60
REQUEST_BUFFER		EQU 0xBB70
DLL_PATH		EQU 0xBCF0
LIBMAN_TABLE_BASE	EQU 0xBE00
NUMBER_BUFFER		EQU 0xBF00
STATE_BASE		EQU 0xBF10
HANDLE			EQU STATE_BASE + 0
FLAGS			EQU STATE_BASE + 2
REQUEST_LENGTH		EQU STATE_BASE + 3
START_TIME		EQU STATE_BASE + 5
STOP_TIME		EQU STATE_BASE + 8
RTC_LAST_SECOND		EQU STATE_BASE + 11
RTC_TICKS_LEFT		EQU STATE_BASE + 12
API_STATUS		EQU STATE_BASE + 14
EXIT_CODE		EQU STATE_BASE + 15
; UNET's public ABI requires roughly 256 bytes of caller stack headroom. Keep
; that stack in the otherwise unused gap between the EXE image and RX_BUFFER,
; away from both libman's table at BE00h and the parser/request state at BFxx.
STACK_BOTTOM		EQU 0x9EF0
STACK_TOP		EQU 0x9FF0

FLAG_HANDLE	EQU 0x01
FLAG_NETINIT	EQU 0x02
FLAG_CHANNEL	EQU 0x04
HTTP_IDLE_MS	EQU 15000
RTC_ALIGN_TICKS EQU 2500

	MODULE MAIN

	ORG 0x8080
EXE_HEADER
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	LD	(CMDLINE_PTR),IX
	CALL	CLEAR_RUNTIME
	LD	HL,MSG_BANNER
	CALL	PUTS_LN
	CALL	PARSE_COMMAND
	JR	NC,.ARGS_OK
	CP	1
	JP	Z,SHOW_HELP
	LD	HL,MSG_USAGE_ERROR
	CALL	PUTS_LN
	LD	B,DSS_EXIT_ARGUMENT
	JP	FINISH
.ARGS_OK
	LD	HL,URL_BUFFER
	CALL	PARSE_URL
	JP	C,USAGE_FAIL
	CALL	BUILD_REQUEST

	CALL	RESOLVE_DLL_PATH
	LD	A,1
	CALL	LIBMAN.l_load
	JR	NC,.LOADED
	LD	A,(USED_EXEDIR)
	OR	A
	JP	Z,LOAD_FAIL
	LD	A,(LIBMAN.l_reason)
	CP	LIBMAN.LR_OPEN
	JP	NZ,LOAD_FAIL
	LD	HL,DLL_NAME
	LD	A,1
	CALL	LIBMAN.l_load
	JP	C,LOAD_FAIL
.LOADED
	LD	(HANDLE),HL
	LD	A,FLAG_HANDLE
	LD	(FLAGS),A

	LD	B,UNET_FN_GETCAPS
	CALL	CALL_API
	JP	C,CALL_FAIL
	OR	A
	JP	NZ,BAD_ABI
	LD	A,IXH
	CP	HIGH UNET_ABI_VERSION
	JP	NZ,BAD_ABI
	LD	A,E
	AND	UNET_CAP_TCP
	JP	Z,BAD_ABI

	LD	A,UNET_OPT_CANCELKEYS
	LD	DE,1
	LD	B,UNET_FN_SETOPT
	CALL	CALL_API
	JP	C,CALL_FAIL
	OR	A
	JP	NZ,API_FAIL

	LD	B,UNET_FN_NETINIT
	CALL	CALL_API
	JP	C,CALL_FAIL
	OR	A
	JP	NZ,NETINIT_FAIL
	LD	A,(FLAGS)
	OR	FLAG_NETINIT
	LD	(FLAGS),A

	XOR	A
	LD	DE,HOST_BUFFER
	LD	IX,PORT_BUFFER
	LD	B,UNET_FN_CONNECT
	CALL	CALL_API
	JP	C,CALL_FAIL
	OR	A
	JP	NZ,CONNECT_FAIL
	LD	A,(FLAGS)
	OR	FLAG_CHANNEL
	LD	(FLAGS),A
	LD	HL,MSG_CONNECTED
	CALL	PUTS_LN

	LD	HL,MSG_WAIT_EDGE
	CALL	PUTS_LN
	CALL	WAIT_RTC_EDGE
	JP	C,RTC_FAIL
	CALL	TIME_NOW
	LD	(START_TIME),HL
	LD	A,B
	LD	(START_TIME+2),A

	XOR	A
	LD	DE,REQUEST_BUFFER
	LD	IX,(REQUEST_LENGTH)
	LD	B,UNET_FN_SEND
	CALL	CALL_API
	JP	C,CALL_FAIL
	OR	A
	JP	NZ,SEND_FAIL
	LD	HL,(REQUEST_LENGTH)
	OR	A
	SBC	HL,DE
	JR	Z,.SEND_COMPLETE
	LD	A,NERR_SEND
	JP	SEND_FAIL
.SEND_COMPLETE
	CALL	@HTTPSTREAM.RESET

.RECV_LOOP
	XOR	A
	LD	DE,RX_BUFFER
	LD	IX,RX_BUFFER_SIZE
	LD	IY,HTTP_IDLE_MS
	LD	B,UNET_FN_RECV
	CALL	CALL_API
	JP	C,CALL_FAIL
	LD	(API_STATUS),A
	LD	A,D
	OR	E
	JR	Z,.NO_DATA
	LD	H,D
	LD	L,E
	LD	B,H
	LD	C,L
	LD	HL,RX_BUFFER
	CALL	@HTTPSTREAM.PROCESS
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	JP	NZ,HTTP_FAIL
	CALL	@HTTPSTREAM.BODY_COMPLETE
	JR	NC,.COMPLETE
	LD	A,(API_STATUS)
	CP	NERR_OK
	JR	Z,.RECV_LOOP
	JR	.STATUS
.NO_DATA
	LD	A,(API_STATUS)
	CP	NERR_OK
	JP	Z,RECV_IDLE_FAIL		; blocking RECV returned zero: final timeout
.STATUS
	CP	NERR_CLOSED
	JR	Z,.PEER_CLOSED
	CP	NERR_CANCEL
	JP	Z,USER_ABORT
	JP	RECV_FAIL
.PEER_CLOSED
	LD	A,(HTTP_STATUS_SEEN_VAR)
	OR	A
	JP	Z,HTTP_FAIL
	LD	A,(HTTP_STATE_VAR)
	CP	4
	JP	NZ,HTTP_FAIL
	LD	A,(HTTP_CONTENT_KNOWN_VAR)
	OR	A
	JR	Z,.COMPLETE		; legal HTTP/1.0 close-delimited body
	CALL	@HTTPSTREAM.BODY_COMPLETE
	JP	C,TRUNCATED_FAIL
.COMPLETE
	CALL	TIME_NOW
	LD	(STOP_TIME),HL
	LD	A,B
	LD	(STOP_TIME+2),A
	CALL	CLEANUP
	LD	HL,MSG_RECEIVED
	CALL	PUTS
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	LD	DE,(HTTP_BODY_RECEIVED_VAR+2)
	CALL	PRINT_DEC32
	LD	HL,MSG_BYTES
	CALL	PUTS_LN
	CALL	TIME_REPORT
	JP	C,SAMPLE_TOO_SHORT
	LD	B,DSS_EXIT_OK
	JP	FINISH_NO_CLEANUP

; Clear only caller-owned runtime. The 6 KiB receive buffer does not need
; clearing; libman's external table does, because DSS RAM is arbitrary.
CLEAR_RUNTIME
	XOR	A
	LD	(FLAGS),A
	LD	HL,LIBMAN_TABLE_BASE
	LD	DE,LIBMAN_TABLE_BASE+1
	LD	BC,255
	LD	(HL),A
	LDIR
	RET

; Exactly one URL token, or a help token. Out CF=1/A=1 help, CF=1/A=0 bad.
PARSE_COMMAND
	LD	HL,(CMDLINE_PTR)
	LD	B,(HL)
	INC	HL
.SKIP
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	A,(HL)
	CP	0x21
	JR	NC,.TOKEN
	INC	HL
	DEC	B
	JR	.SKIP
.TOKEN
	LD	DE,URL_BUFFER
	LD	C,0
.COPY
	LD	A,B
	OR	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.TRAIL
	INC	C
	JR	Z,.BAD
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	JR	.COPY
.TRAIL
	INC	HL
	DEC	B
	LD	A,B
	OR	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.TRAIL
	JR	.BAD
.END
	XOR	A
	LD	(DE),A
	CALL	IS_HELP
	JR	NZ,.NOT_HELP
	LD	A,1
	SCF
	RET
.NOT_HELP
	OR	A
	RET
.BAD
	XOR	A
	SCF
	RET

IS_HELP
	LD	HL,URL_BUFFER
	LD	DE,HELP_SLASH
	CALL	STREQ_CI
	RET	Z
	LD	HL,URL_BUFFER
	LD	DE,HELP_DASH_H
	CALL	STREQ_CI
	RET	Z
	LD	HL,URL_BUFFER
	LD	DE,HELP_DASH_Q
	CALL	STREQ_CI
	RET

; Absolute http:// URL. Host and port are ASCIIZ strings for UNET CONNECT.
PARSE_URL
	LD	DE,URL_PREFIX
	LD	B,7
.PREFIX
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	CALL	TOLOWER
	CP	C
	JP	NZ,.BAD
	INC	HL
	INC	DE
	DJNZ	.PREFIX
	LD	DE,HOST_BUFFER
	LD	B,63
.HOST
	LD	A,(HL)
	OR	A
	JR	Z,.HOST_END
	CP	':'
	JR	Z,.HOST_END
	CP	'/'
	JR	Z,.HOST_END
	LD	C,A
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	A,C
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	JR	.HOST
.HOST_END
	LD	A,63
	SUB	B
	JR	Z,.BAD
	XOR	A
	LD	(DE),A
	LD	DE,PORT_BUFFER
	LD	A,'8'
	LD	(DE),A
	INC	DE
	LD	A,'0'
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	LD	A,(HL)
	OR	A
	JR	Z,.DEFAULT_PATH
	CP	'/'
	JR	Z,.COPY_PATH
	CP	':'
	JR	NZ,.BAD
	INC	HL
	LD	DE,PORT_BUFFER
	LD	B,5
	LD	C,0
.PORT
	LD	A,(HL)
	SUB	'0'
	JR	C,.PORT_END
	CP	10
	JR	NC,.PORT_END
	INC	C
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	JR	.PORT
.PORT_END
	LD	A,C
	OR	A
	JR	Z,.BAD
	XOR	A
	LD	(DE),A
	PUSH	HL
	CALL	VALIDATE_PORT
	POP	HL
	JR	C,.BAD
	LD	A,(HL)
	OR	A
	JR	Z,.DEFAULT_PATH
	CP	'/'
	JR	NZ,.BAD
.COPY_PATH
	LD	DE,PATH_BUFFER
	LD	B,255
.PATH
	LD	A,(HL)
	OR	A
	JR	Z,.PATH_END
	LD	C,A
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	A,C
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	JR	.PATH
.PATH_END
	XOR	A
	LD	(DE),A
	JR	.OK
.DEFAULT_PATH
	LD	HL,DEFAULT_PATH
	LD	DE,PATH_BUFFER
	LD	BC,2
	LDIR
.OK
	OR	A
	RET
.BAD
	SCF
	RET

; C=decimal digit count (1..5), PORT_BUFFER is ASCIIZ. Reject port zero and
; the five-digit range above 65535 before handing the string to UNET.
VALIDATE_PORT
	LD	A,C
	CP	5
	JR	C,.NONZERO
	PUSH	BC
	LD	HL,PORT_BUFFER
	LD	DE,PORT_MAX_TEXT
	LD	B,5
.COMPARE
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	CP	C
	JR	C,.IN_RANGE
	JR	NZ,.TOO_LARGE
	INC	HL
	INC	DE
	DJNZ	.COMPARE
.IN_RANGE
	POP	BC
.NONZERO
	LD	HL,PORT_BUFFER
	LD	B,C
.SCAN
	LD	A,(HL)
	CP	'0'
	JR	NZ,.VALID
	INC	HL
	DJNZ	.SCAN
	SCF
	RET
.TOO_LARGE
	POP	BC
	SCF
	RET
.VALID
	OR	A
	RET

BUILD_REQUEST
	LD	HL,REQUEST_BUFFER
	LD	DE,LIT_GET
	CALL	APPEND
	LD	DE,PATH_BUFFER
	CALL	APPEND
	LD	DE,LIT_HOST
	CALL	APPEND
	LD	DE,HOST_BUFFER
	CALL	APPEND
	LD	DE,LIT_REQUEST_END
	CALL	APPEND
	LD	DE,REQUEST_BUFFER
	OR	A
	SBC	HL,DE
	LD	(REQUEST_LENGTH),HL
	RET

APPEND
	LD	A,(DE)
	OR	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	DE
	JR	APPEND

; Prefer the DLL beside the executable; l_load retries DLL_NAME from cwd only
; when that first candidate could not be opened.
RESOLVE_DLL_PATH
	XOR	A
	LD	(USED_EXEDIR),A
	LD	HL,DLL_PATH
	LD	B,APPINFO_EXE_HOMEDIR
	LD	C,DSS_APPINFO
	RST	DSS
	JR	C,.BARE
	LD	HL,DLL_PATH
	LD	BC,0x00F0
.END
	LD	A,(HL)
	OR	A
	JR	Z,.FOUND
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.END
	JR	.BARE
.FOUND
	LD	A,(DLL_PATH)
	OR	A
	JR	Z,.BARE
	DEC	HL
	LD	A,(HL)
	INC	HL
	CP	92
	JR	Z,.APPEND
	CP	'/'
	JR	Z,.APPEND
	LD	(HL),92
	INC	HL
.APPEND
	EX	DE,HL
	LD	HL,DLL_NAME
	CALL	STRCPY
	LD	A,1
	LD	(USED_EXEDIR),A
	LD	HL,DLL_PATH
	RET
.BARE
	LD	HL,DLL_NAME
	RET

; B=function, arguments already in A/DE/IX/IY. CF reports libman dispatch
; failure; API status remains in A and must be checked separately.
CALL_API
	LD	HL,(HANDLE)
	CALL	LIBMAN.l_call
	RET

WAIT_RTC_EDGE
	CALL	READ_SECOND
	LD	(RTC_LAST_SECOND),A
	LD	HL,RTC_ALIGN_TICKS
	LD	(RTC_TICKS_LEFT),HL
.LOOP
	CALL	WAIT_1MS
	CALL	READ_SECOND
	LD	B,A
	LD	A,(RTC_LAST_SECOND)
	CP	B
	JR	NZ,.OK
	LD	HL,(RTC_TICKS_LEFT)
	DEC	HL
	LD	(RTC_TICKS_LEFT),HL
	LD	A,H
	OR	L
	JR	NZ,.LOOP
	SCF
	RET
.OK
	OR	A
	RET

WAIT_1MS
	LD	BC,NETTIME_TICK_LOOP
.LOOP
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.LOOP
	RET

READ_SECOND
	PUSH	IX,IY
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	A,B
	POP	IY,IX
	RET

; TIME_NOW -> B:HL, 24-bit seconds since midnight.
TIME_NOW
	PUSH	IX,IY
	LD	C,DSS_SYSTIME
	RST	DSS
	PUSH	BC,HL
	LD	HL,0
	LD	(HTTP_WORK32_VAR),HL
	LD	(HTTP_WORK32_VAR+2),HL
	POP	DE
	PUSH	DE
	LD	A,D
	OR	A
	JR	Z,.MINUTES
	LD	B,A
.HOURS
	LD	HL,(HTTP_WORK32_VAR)
	LD	DE,3600
	ADD	HL,DE
	LD	(HTTP_WORK32_VAR),HL
	JR	NC,.HOUR_NEXT
	LD	HL,HTTP_WORK32_VAR+2
	INC	(HL)
.HOUR_NEXT
	DJNZ	.HOURS
.MINUTES
	POP	DE
	LD	A,E
	OR	A
	JR	Z,.SECONDS
	LD	B,A
.MINS
	LD	HL,(HTTP_WORK32_VAR)
	LD	DE,60
	ADD	HL,DE
	LD	(HTTP_WORK32_VAR),HL
	JR	NC,.MIN_NEXT
	LD	HL,HTTP_WORK32_VAR+2
	INC	(HL)
.MIN_NEXT
	DJNZ	.MINS
.SECONDS
	POP	BC
	LD	HL,(HTTP_WORK32_VAR)
	LD	D,0
	LD	E,B
	ADD	HL,DE
	LD	A,(HTTP_WORK32_VAR+2)
	LD	B,A
	JR	NC,.DONE
	INC	B
.DONE
	POP	IY,IX
	RET

TIME_REPORT
	LD	HL,(STOP_TIME)
	LD	DE,(START_TIME)
	OR	A
	SBC	HL,DE
	LD	A,(START_TIME+2)
	LD	E,A
	LD	A,(STOP_TIME+2)
	SBC	A,E
	LD	B,A
	JR	NC,.NO_WRAP
	LD	DE,0x5180
	ADD	HL,DE
	LD	A,B
	ADC	A,1
	LD	B,A
.NO_WRAP
	LD	(STOP_TIME),HL
	LD	A,B
	LD	(STOP_TIME+2),A
	OR	H
	OR	L
	JR	Z,.SHORT
	LD	HL,MSG_SUMMARY_PREFIX
	CALL	PUTS
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	LD	DE,(HTTP_BODY_RECEIVED_VAR+2)
	CALL	PRINT_DEC32
	LD	HL,MSG_SUMMARY_BYTES
	CALL	PUTS
	LD	HL,(STOP_TIME)
	LD	A,(STOP_TIME+2)
	LD	E,A
	LD	D,0
	CALL	PRINT_DEC32
	LD	HL,MSG_SUMMARY_SEC
	CALL	PUTS
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	LD	(HTTP_WORK32_VAR),HL
	LD	HL,(HTTP_BODY_RECEIVED_VAR+2)
	LD	(HTTP_WORK32_VAR+2),HL
	LD	DE,(STOP_TIME)
	CALL	DIV32_BY_DE
	LD	HL,HTTP_WORK32_VAR
	CALL	SHIFT_RIGHT_10
	CALL	PRINT_DEC32
	LD	HL,MSG_KBPS
	CALL	PUTS_LN
	OR	A
	RET
.SHORT
	SCF
	RET

PRINT_DEC32
	LD	IX,NUMBER_BUFFER
	CALL	FORMAT_DEC32
	LD	(IX+0),0
	LD	HL,NUMBER_BUFFER
	JP	PUTS

FORMAT_DEC32
	LD	(HTTP_WORK32_VAR),HL
	LD	(HTTP_WORK32_VAR+2),DE
	LD	A,H
	OR	L
	OR	D
	OR	E
	JR	NZ,.NONZERO
	LD	(IX+0),'0'
	INC	IX
	RET
.NONZERO
	LD	B,0
.DIVIDE
	PUSH	BC
	CALL	DIV32_10
	POP	BC
	ADD	A,'0'
	PUSH	AF
	INC	B
	LD	HL,(HTTP_WORK32_VAR)
	LD	A,H
	OR	L
	LD	HL,(HTTP_WORK32_VAR+2)
	OR	H
	OR	L
	JR	NZ,.DIVIDE
.WRITE
	POP	AF
	LD	(IX+0),A
	INC	IX
	DJNZ	.WRITE
	RET

DIV32_10
	LD	HL,0
	LD	B,32
.BIT
	PUSH	HL
	LD	HL,HTTP_WORK32_VAR
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	POP	HL
	ADC	HL,HL
	LD	A,L
	CP	10
	JR	C,.NEXT
	SUB	10
	LD	L,A
	PUSH	HL
	LD	HL,HTTP_WORK32_VAR
	SET	0,(HL)
	POP	HL
.NEXT
	DJNZ	.BIT
	LD	A,L
	RET

DIV32_BY_DE
	LD	HL,0
	LD	B,32
.LOOP
	PUSH	HL
	LD	HL,HTTP_WORK32_VAR
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	POP	HL
	ADC	HL,HL
	JR	C,.SUB
	OR	A
	SBC	HL,DE
	JR	C,.RESTORE
	JR	.SET
.SUB
	OR	A
	SBC	HL,DE
.SET
	PUSH	HL
	LD	HL,HTTP_WORK32_VAR
	SET	0,(HL)
	POP	HL
	JR	.NEXT
.RESTORE
	ADD	HL,DE
.NEXT
	DJNZ	.LOOP
	RET

SHIFT_RIGHT_10
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,(HL)
	EX	DE,HL
	LD	E,A
	SRL	E
	RR	H
	RR	L
	SRL	E
	RR	H
	RR	L
	LD	D,0
	RET

; Idempotent cleanup. Preserve the primary exit class across best-effort API
; calls, then release the libman handle on every path that acquired it.
CLEANUP
	PUSH	BC
	LD	A,(FLAGS)
	AND	FLAG_CHANNEL
	JR	Z,.NETDONE
	XOR	A
	LD	B,UNET_FN_CLOSE
	CALL	CALL_API
	LD	A,(FLAGS)
	AND	0xFF-FLAG_CHANNEL
	LD	(FLAGS),A
.NETDONE
	LD	A,(FLAGS)
	AND	FLAG_NETINIT
	JR	Z,.FREE
	LD	B,UNET_FN_NETDONE
	CALL	CALL_API
	LD	A,(FLAGS)
	AND	0xFF-FLAG_NETINIT
	LD	(FLAGS),A
.FREE
	LD	A,(FLAGS)
	AND	FLAG_HANDLE
	JR	Z,.DONE
	LD	HL,(HANDLE)
	CALL	LIBMAN.l_free
	LD	A,(FLAGS)
	AND	0xFF-FLAG_HANDLE
	LD	(FLAGS),A
.DONE
	POP	BC
	RET

LOAD_FAIL
	LD	HL,MSG_LOAD_FAIL
	CALL	PUTS_LN
	LD	B,DSS_EXIT_HARDWARE
	JP	FINISH_NO_CLEANUP
BAD_ABI
	LD	HL,MSG_BAD_ABI
	CALL	PUTS_LN
	LD	B,DSS_EXIT_HARDWARE
	JP	FINISH
NETINIT_FAIL
	LD	(API_STATUS),A
	CP	NERR_CANCEL
	JP	Z,USER_ABORT
	LD	HL,MSG_NETINIT_FAIL
	CALL	PUTS_LN
	CALL	PRINT_API_DETAIL
	LD	B,DSS_EXIT_CONFIG
	JP	FINISH
CONNECT_FAIL
	LD	(API_STATUS),A
	CP	NERR_CANCEL
	JP	Z,USER_ABORT
	LD	HL,MSG_CONNECT_FAIL
	CALL	PUTS_LN
	CALL	PRINT_API_DETAIL
	LD	B,DSS_EXIT_NETWORK
	JP	FINISH
SEND_FAIL
	LD	(API_STATUS),A
	CP	NERR_CANCEL
	JP	Z,USER_ABORT
	LD	HL,MSG_SEND_FAIL
	CALL	PUTS_LN
	CALL	PRINT_API_DETAIL
	LD	B,DSS_EXIT_NETWORK
	JP	FINISH
RECV_IDLE_FAIL
	LD	A,NERR_RECV_TIMEOUT
	LD	(API_STATUS),A
	LD	HL,MSG_IDLE_FAIL
	CALL	PUTS_LN
	CALL	PRINT_API_DETAIL
	LD	B,DSS_EXIT_NETWORK
	JP	FINISH
RECV_FAIL
	LD	(API_STATUS),A
	LD	HL,MSG_RECV_FAIL
	CALL	PUTS_LN
	CALL	PRINT_API_DETAIL
	LD	B,DSS_EXIT_NETWORK
	JP	FINISH
TRUNCATED_FAIL
	LD	HL,MSG_TRUNCATED
	CALL	PUTS_LN
	LD	B,DSS_EXIT_NETWORK
	JP	FINISH
HTTP_FAIL
	LD	HL,MSG_HTTP_FAIL
	CALL	PUTS_LN
	LD	B,DSS_EXIT_REMOTE
	JP	FINISH
RTC_FAIL
	LD	HL,MSG_RTC_FAIL
	CALL	PUTS_LN
	LD	B,DSS_EXIT_HARDWARE
	JP	FINISH
SAMPLE_TOO_SHORT
	LD	HL,MSG_SAMPLE_SHORT
	CALL	PUTS_LN
	LD	B,DSS_EXIT_REMOTE
	JP	FINISH_NO_CLEANUP
USER_ABORT
	LD	HL,MSG_ABORT
	CALL	PUTS_LN
	LD	B,DSS_EXIT_CANCELLED
	JP	FINISH
API_FAIL
	LD	(API_STATUS),A
	LD	HL,MSG_API_FAIL
	CALL	PUTS_LN
	CALL	PRINT_API_DETAIL
	LD	B,DSS_EXIT_NETWORK
	JP	FINISH
CALL_FAIL
	LD	HL,MSG_CALL_FAIL
	CALL	PUTS_LN
	LD	B,DSS_EXIT_HARDWARE
	JP	FINISH
USAGE_FAIL
	LD	HL,MSG_USAGE_ERROR
	CALL	PUTS_LN
	LD	HL,MSG_HELP
	CALL	PUTS
	LD	B,DSS_EXIT_ARGUMENT
	JP	FINISH_NO_CLEANUP
SHOW_HELP
	LD	HL,MSG_HELP
	CALL	PUTS
	LD	B,DSS_EXIT_OK
	JP	FINISH_NO_CLEANUP

FINISH
	CALL	CLEANUP
FINISH_NO_CLEANUP
	LD	A,B
	LD	(EXIT_CODE),A
	OR	A
	LD	HL,MSG_RESULT_OK
	JR	Z,.PRINT
	LD	HL,MSG_RESULT_FAIL
.PRINT
	CALL	PUTS_LN
	LD	A,(EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

PUTS
	PUSH	AF,BC,DE,HL
	LD	C,DSS_PCHARS
	RST	DSS
	POP	HL,DE,BC,AF
	RET
PUTS_LN
	CALL	PUTS
	LD	HL,CRLF_TEXT
	JR	PUTS

PRINT_API_DETAIL
	LD	HL,MSG_API_CODE
	CALL	PUTS
	LD	A,(API_STATUS)
	CALL	PUT_HEX8
	LD	HL,MSG_TARGET
	CALL	PUTS
	LD	HL,HOST_BUFFER
	CALL	PUTS
	LD	HL,MSG_COLON
	CALL	PUTS
	LD	HL,PORT_BUFFER
	JP	PUTS_LN

PUT_HEX8
	PUSH	AF
	RRA
	RRA
	RRA
	RRA
	CALL	HEX_NIBBLE
	LD	(NUMBER_BUFFER),A
	POP	AF
	CALL	HEX_NIBBLE
	LD	(NUMBER_BUFFER+1),A
	XOR	A
	LD	(NUMBER_BUFFER+2),A
	LD	HL,NUMBER_BUFFER
	JP	PUTS

HEX_NIBBLE
	AND	0x0F
	ADD	A,0x90
	DAA
	ADC	A,0x40
	DAA
	RET

STRCPY
	LD	A,(HL)
	LD	(DE),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	STRCPY

STREQ_CI
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	CALL	TOLOWER
	CP	C
	RET	NZ
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	STREQ_CI

TOLOWER
	CP	'A'
	RET	C
	CP	'Z'+1
	RET	NC
	ADD	A,'a'-'A'
	RET

CMDLINE_PTR	DW 0
USED_EXEDIR	DB 0
DLL_NAME	DB "UNET509B.DLL",0
URL_PREFIX	DB "http://"
DEFAULT_PATH	DB "/",0
HELP_SLASH	DB "/?",0
HELP_DASH_H	DB "-h",0
HELP_DASH_Q	DB "-?",0
LIT_GET		DB "GET ",0
LIT_HOST	DB " HTTP/1.0",13,10,"Host: ",0
LIT_REQUEST_END DB 13,10,"Connection: close",13,10,13,10,0
PORT_MAX_TEXT	DB "65535"
CRLF_TEXT	DB 13,10,0
MSG_BANNER	DB "3C509B DLSPEED v",PACKAGE_VERSION,0
MSG_CONNECTED	DB "ESTABLISHED via UNET509B.DLL.",0
MSG_WAIT_EDGE	DB "Waiting for RTC edge; transfer is silent until done...",0
MSG_RECEIVED	DB "Received: ",0
MSG_BYTES	DB " bytes",0
MSG_SUMMARY_PREFIX DB "  ",0
MSG_SUMMARY_BYTES DB " bytes in ",0
MSG_SUMMARY_SEC DB " sec, ",0
MSG_KBPS	DB " KB/s",0
MSG_LOAD_FAIL	DB "[E0] could not load UNET509B.DLL.",0
MSG_BAD_ABI	DB "[E1] DLL requires compatible UNET ABI 1.x with TCP.",0
MSG_NETINIT_FAIL DB "[E2] NETINIT failed.",0
MSG_CONNECT_FAIL DB "[E3] CONNECT failed.",0
MSG_SEND_FAIL	DB "[E4] SEND failed or returned a short count.",0
MSG_IDLE_FAIL	DB "[E5] RECV idle timeout after 15000 ms.",0
MSG_RECV_FAIL	DB "[E6] RECV failed.",0
MSG_TRUNCATED	DB "[E7] response closed before Content-Length bytes arrived.",0
MSG_HTTP_FAIL	DB "[E8] invalid status, framing, chunked or compressed response.",0
MSG_RTC_FAIL	DB "[E9] RTC second did not advance within 2500 ms.",0
MSG_SAMPLE_SHORT DB "[EA] sample too short (under one RTC second).",0
MSG_ABORT	DB "[EB] Aborted by user (Esc/Ctrl+Z).",0
MSG_API_FAIL	DB "[EC] UNET call returned an error.",0
MSG_CALL_FAIL	DB "[ED] libman dispatch failed.",0
MSG_USAGE_ERROR DB "[EE] usage: missing or invalid URL",0
MSG_API_CODE	DB "  code 0x",0
MSG_TARGET	DB ", target ",0
MSG_COLON	DB ":",0
MSG_HELP
	DB "Usage:",13,10
	DB "  DLSPEED http://host[:port]/path",13,10
	DB "  DLSPEED /?",13,10,13,10
	DB "  Measures the public UNET509B.DLL download path; body is discarded.",13,10,0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL",0

	ENDMODULE

	INCLUDE "http_stream.asm"
	INCLUDE "libman13.asm"

	ASSERT $ <= STACK_BOTTOM
	ASSERT RX_BUFFER + RX_BUFFER_SIZE <= HTTP_STATE_VAR
	ASSERT STACK_BOTTOM < STACK_TOP
	ASSERT STACK_TOP < 0xC000

	END MAIN.START
