; EL3INFO.EXE - safe 3C509B discovery and activation diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

	MODULE MAIN

	ORG 0x8080
EXE_HEADER
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	LD	A,EL3_STAGE_ARGS
	LD	(EL3_LAST_STAGE),A
	XOR	A
	LD	H,A
	LD	L,A
	LD	(EL3_LAST_TICKS),HL
	LD	(EL3_LAST_STATUS),HL
	LD	(EL3_BASE),HL
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@CLI.PARSE_INFO
	JR	C,PARSE_RESULT
	LD	A,(CLI_SLOT)
	LD	HL,(CLI_IDPORT)
	CALL	@EL3.CONFIGURE
	JP	C,FAIL
	CALL	PRINT_STAGE_E0
	CALL	@EL3.DISCOVER
	JP	C,FAIL
	LD	A,(CLI_BASE_AUTO)
	OR	A
	JR	Z,.EXPLICIT_BASE
	XOR	A
	LD	HL,0
	JR	.ACTIVATE
.EXPLICIT_BASE
	LD	A,1
	LD	HL,(CLI_BASE)
.ACTIVATE
	CALL	@EL3.ACTIVATE
	JP	C,FAIL
	CALL	PRINT_CARD
	LD	A,(CLI_VERBOSE)
	OR	A
	CALL	NZ,PRINT_VERBOSE
	JP	SUCCESS

PARSE_RESULT
	CP	EL3_CLI_HELP
	JR	NZ,.BAD
	CALL	PRINT_HELP
	JP	SUCCESS
.BAD
	LD	(FAIL_CODE),A
	CALL	PRINT_HELP
	LD	A,(FAIL_CODE)
	JP	FAIL

PRINT_STAGE_E0
	LD	HL,MSG_E0_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_CARD
	LD	HL,MSG_E1_PRODUCT
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x03*2)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_IO
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_E2_MAC
	CALL	@CONSOLE.STRING
	LD	HL,EL3_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_E3_IRQ
	CALL	@CONSOLE.STRING
	LD	A,(EEPROM_BUFFER + 0x09*2 + 1)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	0x0F
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_IRQ_UNUSED
	JP	@CONSOLE.LINE

PRINT_VERBOSE
	LD	HL,MSG_EV_MFG
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x07*2)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ADDR
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x08*2)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_RESOURCE
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x09*2)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_EV_CSUM
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x0F*2)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_SECONDARY
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x17*2)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_HELP
	LD	HL,MSG_HELP_1
	CALL	@CONSOLE.LINE
	LD	HL,MSG_HELP_2
	JP	@CONSOLE.LINE

FAIL
	LD	(FAIL_CODE),A
	LD	HL,MSG_ERROR_STAGE
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_STAGE)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_ERROR_CODE
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_ERROR_TICKS
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_TICKS)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_ERROR_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_ERROR_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ERROR_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ERROR_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

SUCCESS
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN 0

MSG_BANNER	DB "3C509B EL3INFO v",PACKAGE_VERSION,0
MSG_E0_SLOT	DB "[E0] SLOT=",0
MSG_IDPORT	DB " IDPORT=",0
MSG_E1_PRODUCT	DB "[E1] PRODUCT=",0
MSG_IO		DB " IO=",0
MSG_E2_MAC	DB "[E2] MAC=",0
MSG_E3_IRQ	DB "[E3] IRQ=",0
MSG_IRQ_UNUSED	DB " (not used by Sprinter)",0
MSG_EV_MFG	DB "[E4] MFG=",0
MSG_ADDR	DB " ADDR=",0
MSG_RESOURCE	DB " RESOURCE=",0
MSG_EV_CSUM	DB "[E5] CHECKSUM=",0
MSG_SECONDARY	DB " SECONDARY=",0
MSG_HELP_1	DB "Usage: EL3INFO [-v] [-s 0|1] [-p #100..#1F0]",0
MSG_HELP_2	DB "               [-b AUTO|#200..#3E0]",0
MSG_ERROR_STAGE	DB "ERROR stage=",0
MSG_ERROR_CODE	DB " code=",0
MSG_ERROR_TICKS	DB " waitq=",0
MSG_ERROR_SLOT	DB " slot=",0
MSG_ERROR_IDPORT DB " idport=",0
MSG_ERROR_BASE	DB " base=",0
MSG_ERROR_STATUS DB " status=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL	DB "RESULT FAIL code=",0
FAIL_CODE	DB 0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
