; EL3LB.EXE - bounded 3C509B controller-loopback FIFO diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
TX_BUFFER	EQU 0x4000
RX_BUFFER	EQU 0x4800
TEST_ETHERTYPE	EQU 0x88B5

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	CLEAR_RUNTIME
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@CLI.PARSE_LB
	JP	C,PARSE_RESULT
	CALL	PRINT_L0
	LD	A,(CLI_SLOT)
	LD	HL,(CLI_IDPORT)
	CALL	@EL3.CONFIGURE
	JP	C,FAIL_DIRECT
	CALL	@EL3.DISCOVER
	JP	C,FAIL_DIRECT
	LD	A,(CLI_BASE_AUTO)
	OR	A
	JR	Z,.EXPLICIT_BASE
	XOR	A
	LD	HL,0
	JR	.ACTIVATE
.EXPLICIT_BASE
	LD	A,1
	LD	HL,(CLI_BASE)
.ACTIVATE
	CALL	@EL3.ACTIVATE
	JP	C,FAIL_DIRECT
	LD	A,1
	LD	(CARD_ACTIVE),A
	CALL	PRINT_L1
	LD	A,EL3_STAGE_MEMORY
	LD	(EL3_LAST_STAGE),A
	CALL	ALLOCATE_BUFFERS
	JP	C,CLEANUP_FAIL
	CALL	PRINT_L2
	CALL	@EL3.INIT
	JP	C,CLEANUP_FAIL
	CALL	@EL3.LOOPBACK_ENABLE
	JP	C,CLEANUP_FAIL
	LD	HL,MSG_L3
	CALL	@CONSOLE.LINE

	LD	A,(CLI_COUNT)
	LD	(EL3LB_REMAINING),A
.RUN_LOOP
	CALL	RUN_MATRIX
	JP	C,CLEANUP_FAIL
	CALL	RUN_BURSTS
	JP	C,CLEANUP_FAIL
	LD	A,(EL3LB_RUN_OK)
	INC	A
	LD	(EL3LB_RUN_OK),A
	LD	A,(EL3LB_REMAINING)
	DEC	A
	LD	(EL3LB_REMAINING),A
	JR	NZ,.RUN_LOOP
	CALL	PRINT_RESULTS
	CALL	CLEANUP_SUCCESS
	JP	C,FAIL_DIRECT
	JP	SUCCESS

PARSE_RESULT
	CP	EL3_CLI_HELP
	JR	NZ,.PARSE_BAD
	CALL	PRINT_HELP
	JP	SUCCESS
.PARSE_BAD
	LD	(EL3LB_FAIL_CODE),A
	CALL	PRINT_HELP
	LD	A,(EL3LB_FAIL_CODE)
	JP	FAIL_DIRECT

; One run: eight lengths by five patterns = 40 verified packets.
RUN_MATRIX
	LD	HL,LENGTH_TABLE
	LD	B,8
.MATRIX_LENGTH
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	BC,HL
	LD	A,0
.MATRIX_PATTERN
	PUSH	AF,DE
	LD	(EL3LB_INPUT_LENGTH),DE
	LD	(EL3LB_PATTERN),A
	CALL	TEST_ONE
	JR	C,.MATRIX_FAIL
	LD	HL,EL3LB_MATRIX_OK
	CALL	@EL3.INC_WORD
	POP	DE,AF
	INC	A
	CP	5
	JR	NZ,.MATRIX_PATTERN
	POP	HL,BC
	DJNZ	.MATRIX_LENGTH
	XOR	A
	RET
.MATRIX_FAIL
	LD	(MATRIX_SAVED_ERROR),A
	POP	DE,AF
	POP	HL,BC
	LD	A,(MATRIX_SAVED_ERROR)
	SCF
	RET

; Additional back-to-back queues: two then ten packets, with no RX read until
; the complete queue has been transmitted. Byte 14 carries a per-queue sequence
; so a duplicate cannot stand in for the next packet.
RUN_BURSTS
	LD	B,2
	CALL	RUN_BURST
	RET	C
	LD	B,10
	JP	RUN_BURST

RUN_BURST
	LD	A,B
	LD	(BURST_SIZE),A
	LD	(BURST_REMAIN),A
	XOR	A
	LD	(BURST_SEQUENCE),A
.BURST_SEND
	LD	HL,60
	LD	(EL3LB_INPUT_LENGTH),HL
	LD	A,4
	LD	(EL3LB_PATTERN),A
	CALL	BUILD_FRAME
	LD	A,(BURST_SEQUENCE)
	LD	(TX_BUFFER+14),A
	INC	A
	LD	(BURST_SEQUENCE),A
	LD	HL,TX_BUFFER
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	RET	C
	LD	A,(BURST_REMAIN)
	DEC	A
	LD	(BURST_REMAIN),A
	JR	NZ,.BURST_SEND
	LD	A,(BURST_SIZE)
	LD	(BURST_REMAIN),A
	XOR	A
	LD	(BURST_SEQUENCE),A
.BURST_READ
	CALL	WAIT_RX
	RET	C
	LD	HL,RX_BUFFER
	LD	BC,0x0800
	CALL	@EL3.READ_FRAME
	LD	(EL3LB_ACTUAL_LENGTH),BC
	RET	C
	LD	A,(BURST_SEQUENCE)
	LD	(TX_BUFFER+14),A
	INC	A
	LD	(BURST_SEQUENCE),A
	CALL	VERIFY_FRAME
	RET	C
	LD	HL,EL3LB_BURST_OK
	CALL	@EL3.INC_WORD
	LD	A,(BURST_REMAIN)
	DEC	A
	LD	(BURST_REMAIN),A
	JR	NZ,.BURST_READ
	CALL	@EL3.RX_PENDING
	RET	C
	OR	A
	JR	NZ,.BURST_EXTRA
	XOR	A
	RET
.BURST_EXTRA
	LD	A,EL3_ERR_LOOPBACK_VERIFY
	SCF
	RET

TEST_ONE
	CALL	BUILD_FRAME
	LD	HL,TX_BUFFER
	LD	BC,(EL3LB_INPUT_LENGTH)
	CALL	@EL3.SEND_FRAME
	RET	C
	CALL	WAIT_RX
	RET	C
	LD	HL,RX_BUFFER
	LD	BC,0x0800
	CALL	@EL3.READ_FRAME
	LD	(EL3LB_ACTUAL_LENGTH),BC
	RET	C
	JP	VERIFY_FRAME

WAIT_RX
	LD	A,EL3_STAGE_RX
	LD	(EL3_LAST_STAGE),A
	LD	HL,0
	LD	(EL3LB_WAIT_TICKS),HL
	LD	(EL3_LAST_TICKS),HL
.WAIT_RX_POLL
	CALL	@EL3.RX_PENDING
	JR	C,.WAIT_RX_RETURN
	OR	A
	JR	NZ,.WAIT_RX_RETURN
	LD	HL,(EL3LB_WAIT_TICKS)
	LD	DE,EL3_FIFO_WAIT_QUANTA
	OR	A
	SBC	HL,DE
	JR	NC,.WAIT_RX_TIMEOUT
	CALL	@EL3.WAIT_QUANTUM
	LD	HL,(EL3LB_WAIT_TICKS)
	INC	HL
	LD	(EL3LB_WAIT_TICKS),HL
	LD	(EL3_LAST_TICKS),HL
	JR	.WAIT_RX_POLL
.WAIT_RX_RETURN
	LD	HL,(EL3LB_WAIT_TICKS)
	LD	(EL3_LAST_TICKS),HL
	RET
.WAIT_RX_TIMEOUT
	LD	HL,(EL3LB_WAIT_TICKS)
	LD	(EL3_LAST_TICKS),HL
	LD	HL,EL3_COUNT_TIMEOUT
	CALL	@EL3.INC_WORD
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET

; Destination and source are the card MAC. Pattern applies after EtherType.
BUILD_FRAME
	LD	HL,EL3_MAC
	LD	DE,TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,EL3_MAC
	LD	BC,6
	LDIR
	LD	A,HIGH TEST_ETHERTYPE
	LD	(DE),A
	INC	DE
	LD	A,LOW TEST_ETHERTYPE
	LD	(DE),A
	INC	DE
	LD	HL,(EL3LB_INPUT_LENGTH)
	LD	BC,14
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L
	XOR	A
	LD	(PATTERN_INDEX),A
.BUILD_PAYLOAD
	LD	A,B
	OR	C
	RET	Z
	CALL	PATTERN_BYTE
	LD	(DE),A
	INC	DE
	DEC	BC
	JR	.BUILD_PAYLOAD

PATTERN_BYTE
	LD	A,(EL3LB_PATTERN)
	OR	A
	RET	Z
	CP	1
	JR	NZ,.PATTERN_55
	LD	A,0xFF
	RET
.PATTERN_55
	CP	2
	JR	NZ,.PATTERN_AA
	LD	A,0x55
	RET
.PATTERN_AA
	CP	3
	JR	NZ,.PATTERN_INCREMENT
	LD	A,0xAA
	RET
.PATTERN_INCREMENT
	LD	A,(PATTERN_INDEX)
	INC	A
	LD	(PATTERN_INDEX),A
	DEC	A
	RET

VERIFY_FRAME
	LD	HL,(EL3LB_INPUT_LENGTH)
	LD	DE,EL3_FRAME_WIRE_MIN
	OR	A
	SBC	HL,DE
	JR	NC,.EXPECT_INPUT
	LD	HL,EL3_FRAME_WIRE_MIN
	JR	.EXPECT_STORE
.EXPECT_INPUT
	LD	HL,(EL3LB_INPUT_LENGTH)
.EXPECT_STORE
	LD	(EL3LB_EXPECT_LENGTH),HL
	LD	DE,(EL3LB_ACTUAL_LENGTH)
	OR	A
	SBC	HL,DE
	JR	NZ,.VERIFY_FAIL
	LD	HL,TX_BUFFER
	LD	DE,RX_BUFFER
	LD	BC,(EL3LB_INPUT_LENGTH)
.VERIFY_DATA
	LD	A,B
	OR	C
	JR	Z,.VERIFY_PADDING
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.VERIFY_FAIL
	INC	HL
	INC	DE
	DEC	BC
	JR	.VERIFY_DATA
.VERIFY_PADDING
	LD	HL,(EL3LB_EXPECT_LENGTH)
	LD	BC,(EL3LB_INPUT_LENGTH)
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L
.VERIFY_ZERO
	LD	A,B
	OR	C
	JR	Z,.VERIFY_OK
	LD	A,(DE)
	OR	A
	JR	NZ,.VERIFY_FAIL
	INC	DE
	DEC	BC
	JR	.VERIFY_ZERO
.VERIFY_OK
	XOR	A
	RET
.VERIFY_FAIL
	LD	A,EL3_ERR_LOOPBACK_VERIFY
	SCF
	RET

ALLOCATE_BUFFERS
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JR	C,.ALLOC_FAIL
	LD	(EL3LB_MEMORY_BLOCK),A
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	JR	C,.MAP_FAIL
	XOR	A
	RET
.MAP_FAIL
	CALL	FREE_BUFFERS
.ALLOC_FAIL
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	RET

CLEANUP_SUCCESS
	XOR	A
	LD	(CLEANUP_FAILED),A
	CALL	@EL3.LOOPBACK_DISABLE
	JR	NC,.SUCCESS_DONE
	CALL	SAVE_CLEANUP_ERROR
.SUCCESS_DONE
	CALL	@EL3.DONE
	JR	NC,.SUCCESS_FREE
	LD	(CLEANUP_STEP_ERROR),A
	LD	A,(CLEANUP_FAILED)
	OR	A
	JR	NZ,.SUCCESS_FREE
	LD	A,(CLEANUP_STEP_ERROR)
	CALL	SAVE_CLEANUP_ERROR
.SUCCESS_FREE
	CALL	FREE_BUFFERS
	JR	NC,.SUCCESS_CHECK
	LD	A,(CLEANUP_FAILED)
	OR	A
	JR	NZ,.SUCCESS_CHECK
	LD	A,EL3_ERR_NO_MEMORY
	CALL	SAVE_CLEANUP_ERROR
.SUCCESS_CHECK
	LD	A,(CLEANUP_FAILED)
	OR	A
	RET	Z
	CALL	RESTORE_DIAGNOSTICS
	LD	A,(EL3LB_FAIL_CODE)
	SCF
	RET

SAVE_CLEANUP_ERROR
	LD	(EL3LB_FAIL_CODE),A
	CALL	SAVE_DIAGNOSTICS
	LD	A,1
	LD	(CLEANUP_FAILED),A
	RET

CLEANUP_FAIL
	LD	(EL3LB_FAIL_CODE),A
	CALL	SAVE_DIAGNOSTICS
	LD	A,(CARD_ACTIVE)
	OR	A
	JR	Z,.FAIL_NO_DONE
	CALL	@EL3.LOOPBACK_DISABLE
	CALL	@EL3.DONE
.FAIL_NO_DONE
	CALL	FREE_BUFFERS
	CALL	RESTORE_DIAGNOSTICS
	LD	A,(EL3LB_FAIL_CODE)
	JP	FAIL_DIRECT

FREE_BUFFERS
	LD	A,(EL3LB_MEMORY_BLOCK)
	CP	0xFF
	JR	Z,.FREE_OK
	LD	A,EL3_STAGE_MEMORY
	LD	(EL3_LAST_STAGE),A
	LD	A,(EL3LB_MEMORY_BLOCK)
	LD	C,DSS_FREEMEM
	RST	DSS
	JR	C,.FREE_FAILED
	LD	A,0xFF
	LD	(EL3LB_MEMORY_BLOCK),A
.FREE_OK
	XOR	A
	RET
.FREE_FAILED
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	RET

SAVE_DIAGNOSTICS
	LD	A,(EL3_LAST_STAGE)
	LD	(EL3LB_SAVED_STAGE),A
	LD	HL,(EL3_LAST_TICKS)
	LD	(EL3LB_SAVED_TICKS),HL
	LD	HL,(EL3_LAST_STATUS)
	LD	(EL3LB_SAVED_STATUS),HL
	LD	HL,(EL3_LAST_RX_STATUS)
	LD	(EL3LB_SAVED_RX),HL
	LD	A,(EL3_LAST_TX_STATUS)
	LD	(EL3LB_SAVED_TX),A
	LD	HL,(EL3_RX_REQUIRED)
	LD	(EL3LB_SAVED_REQUIRED),HL
	RET

RESTORE_DIAGNOSTICS
	LD	A,(EL3LB_SAVED_STAGE)
	LD	(EL3_LAST_STAGE),A
	LD	HL,(EL3LB_SAVED_TICKS)
	LD	(EL3_LAST_TICKS),HL
	LD	HL,(EL3LB_SAVED_STATUS)
	LD	(EL3_LAST_STATUS),HL
	LD	HL,(EL3LB_SAVED_RX)
	LD	(EL3_LAST_RX_STATUS),HL
	LD	A,(EL3LB_SAVED_TX)
	LD	(EL3_LAST_TX_STATUS),A
	LD	HL,(EL3LB_SAVED_REQUIRED)
	LD	(EL3_RX_REQUIRED),HL
	RET

CLEAR_RUNTIME
	XOR	A
	LD	H,A
	LD	L,A
	LD	(EL3_LAST_TICKS),HL
	LD	(EL3_LAST_STATUS),HL
	LD	(EL3_LAST_RX_STATUS),HL
	LD	(EL3_RX_REQUIRED),HL
	LD	(EL3_COUNT_RESET),HL
	LD	(EL3_COUNT_TIMEOUT),HL
	LD	(EL3_COUNT_RX),HL
	LD	(EL3_COUNT_TX),HL
	LD	(EL3_COUNT_DROP),HL
	LD	(EL3_COUNT_FRAME),HL
	LD	(EL3LB_MATRIX_OK),HL
	LD	(EL3LB_BURST_OK),HL
	LD	(EL3_LAST_TX_STATUS),A
	LD	(EL3LB_RUN_OK),A
	LD	(CARD_ACTIVE),A
	LD	A,0xFF
	LD	(EL3LB_MEMORY_BLOCK),A
	LD	A,EL3_STAGE_ARGS
	LD	(EL3_LAST_STAGE),A
	RET

PRINT_L0
	LD	HL,MSG_L0
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_RUNS
	CALL	@CONSOLE.STRING
	LD	A,(CLI_COUNT)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_L1
	LD	HL,MSG_L1
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x03*2)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_MAC
	CALL	@CONSOLE.STRING
	LD	HL,EL3_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_L2
	LD	HL,MSG_L2
	CALL	@CONSOLE.STRING
	LD	A,(EL3LB_MEMORY_BLOCK)
	CALL	@CONSOLE.HEX8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_RESULTS
	LD	HL,MSG_L4
	CALL	@CONSOLE.STRING
	LD	HL,(EL3LB_MATRIX_OK)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_L5
	CALL	@CONSOLE.STRING
	LD	HL,(EL3LB_BURST_OK)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_RUN_OK
	CALL	@CONSOLE.STRING
	LD	A,(EL3LB_RUN_OK)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_L6
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_COUNT_RESET)
	CALL	PRINT_COUNTER
	LD	HL,(EL3_COUNT_TIMEOUT)
	CALL	PRINT_COUNTER
	LD	HL,(EL3_COUNT_RX)
	CALL	PRINT_COUNTER
	LD	HL,(EL3_COUNT_TX)
	CALL	PRINT_COUNTER
	LD	HL,(EL3_COUNT_DROP)
	CALL	PRINT_COUNTER
	LD	HL,(EL3_COUNT_FRAME)
	CALL	PRINT_COUNTER
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_COUNTER
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	JP	@CONSOLE.CHAR

PRINT_HELP
	LD	HL,MSG_HELP
	JP	@CONSOLE.LINE

FAIL_DIRECT
	LD	(EL3LB_FAIL_CODE),A
	LD	HL,MSG_ERROR
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_STAGE)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_CODE
	CALL	@CONSOLE.STRING
	LD	A,(EL3LB_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_WAITQ
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_RX
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_RX_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_TX
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_TX_STATUS)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_REQUIRED
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_RX_REQUIRED)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ACTUAL
	CALL	@CONSOLE.STRING
	LD	HL,(EL3LB_ACTUAL_LENGTH)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(EL3LB_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(EL3LB_FAIL_CODE)
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	C,DSS_EXIT
	RST	DSS

SUCCESS
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN 0

MSG_BANNER	DB "3C509B EL3LB v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: EL3LB [-v] [-s 0|1] [-p #100..#1F0] [-b AUTO|#200..#3E0] [-n 1..100]",0
MSG_L0		DB "[L0] TIMER=CYCLES21 SLOT=",0
MSG_IDPORT	DB " IDPORT=",0
MSG_RUNS	DB " RUNS=",0
MSG_L1		DB "[L1] PRODUCT=",0
MSG_BASE	DB " BASE=",0
MSG_MAC		DB " MAC=",0
MSG_L2		DB "[L2] DSS PAGE=16K BLOCK=",0
MSG_L3		DB "[L3] CONTROLLER LOOPBACK=#2000",0
MSG_L4		DB "[L4] MATRIX OK=#",0
MSG_L5		DB "[L5] BURST OK=#",0
MSG_RUN_OK	DB " RUN OK=",0
MSG_L6		DB "[L6] COUNTERS reset/timeout/rxerr/txerr/drop/complete=",0
MSG_ERROR	DB "ERROR stage=",0
MSG_CODE	DB " code=",0
MSG_WAITQ	DB " waitq=#",0
MSG_SLOT	DB " target=CYCLES21 slot=",0
MSG_STATUS	DB " status=",0
MSG_RX		DB " rx=",0
MSG_TX		DB " tx=",0
MSG_REQUIRED	DB " required=",0
MSG_ACTUAL	DB " actual=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0

LENGTH_TABLE	DW 14,42,59,60,61,62,63,1514
CARD_ACTIVE	DB 0
BURST_SIZE	DB 0
BURST_REMAIN	DB 0
BURST_SEQUENCE	DB 0
PATTERN_INDEX	DB 0
MATRIX_SAVED_ERROR DB 0
CLEANUP_FAILED	DB 0
CLEANUP_STEP_ERROR DB 0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
