; EL3REG.EXE - bounded 3C509B INIT/DONE register diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	CLEAR_RUNTIME
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@CLI.PARSE_REG
	JR	C,PARSE_RESULT
	LD	A,(CLI_SLOT)
	LD	HL,(CLI_IDPORT)
	CALL	@EL3.CONFIGURE
	JP	C,FAIL
	CALL	PRINT_E0
	CALL	@EL3.DISCOVER
	JP	C,FAIL
	LD	A,(CLI_BASE_AUTO)
	OR	A
	JR	Z,.EXPLICIT
	XOR	A
	LD	HL,0
	JR	.ACTIVATE
.EXPLICIT
	LD	A,1
	LD	HL,(CLI_BASE)
.ACTIVATE
	CALL	@EL3.ACTIVATE
	JP	C,FAIL
	CALL	PRINT_E1
	LD	A,(CLI_COUNT)
	LD	(REMAINING),A
.CYCLE
	CALL	@EL3.INIT
	JR	C,CLEANUP_FAIL
	LD	HL,EL3_SNAPSHOT_BUFFER
	CALL	@EL3.SNAPSHOT
	JR	C,CLEANUP_FAIL
	CALL	@EL3.DONE
	JP	C,FAIL
	LD	A,(SUCCESS_COUNT)
	INC	A
	LD	(SUCCESS_COUNT),A
	LD	A,(REMAINING)
	DEC	A
	LD	(REMAINING),A
	JR	NZ,.CYCLE
	CALL	PRINT_SNAPSHOT
	CALL	PRINT_E5
	JP	SUCCESS

PARSE_RESULT
	CP	EL3_CLI_HELP
	JR	NZ,.BAD
	CALL	PRINT_HELP
	JP	SUCCESS
.BAD
	LD	(FAIL_CODE),A
	CALL	PRINT_HELP
	LD	A,(FAIL_CODE)
	JP	FAIL

CLEANUP_FAIL
	LD	(FAIL_CODE),A
	CALL	SAVE_DIAGNOSTICS
	CALL	@EL3.DONE
	CALL	RESTORE_DIAGNOSTICS
	LD	A,(FAIL_CODE)
	JP	FAIL

SAVE_DIAGNOSTICS
	LD	A,(EL3_LAST_STAGE)
	LD	(SAVED_STAGE),A
	LD	HL,(EL3_LAST_TICKS)
	LD	(SAVED_TICKS),HL
	LD	HL,(EL3_LAST_STATUS)
	LD	(SAVED_STATUS),HL
	LD	HL,(EL3_LAST_COMMAND)
	LD	(SAVED_COMMAND),HL
	RET

RESTORE_DIAGNOSTICS
	LD	A,(SAVED_STAGE)
	LD	(EL3_LAST_STAGE),A
	LD	HL,(SAVED_TICKS)
	LD	(EL3_LAST_TICKS),HL
	LD	HL,(SAVED_STATUS)
	LD	(EL3_LAST_STATUS),HL
	LD	HL,(SAVED_COMMAND)
	LD	(EL3_LAST_COMMAND),HL
	RET

CLEAR_RUNTIME
	LD	A,EL3_STAGE_ARGS
	LD	(EL3_LAST_STAGE),A
	XOR	A
	LD	H,A
	LD	L,A
	LD	(EL3_LAST_TICKS),HL
	LD	(EL3_LAST_STATUS),HL
	LD	(EL3_LAST_COMMAND),HL
	LD	(EL3_BASE),HL
	LD	(EL3_COUNT_RESET),HL
	LD	(EL3_COUNT_TIMEOUT),HL
	LD	(EL3_COUNT_RX),HL
	LD	(EL3_COUNT_TX),HL
	LD	(EL3_COUNT_DROP),HL
	LD	(EL3_COUNT_FRAME),HL
	LD	(EL3_LAST_RX_STATUS),HL
	LD	(EL3_RX_REQUIRED),HL
	LD	(EL3_VERIFY_FIELD),A
	LD	(EL3_VERIFY_EXPECTED),HL
	LD	(EL3_VERIFY_ACTUAL),HL
	LD	(EL3_LAST_TX_STATUS),A
	LD	(SUCCESS_COUNT),A
	RET

PRINT_E0
	LD	HL,MSG_E0
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_COUNT
	CALL	@CONSOLE.STRING
	LD	A,(CLI_COUNT)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_E1
	LD	HL,MSG_E1
	CALL	@CONSOLE.STRING
	LD	HL,(EEPROM_BUFFER + 0x03*2)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_MAC
	CALL	@CONSOLE.STRING
	LD	HL,EL3_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_SNAPSHOT
	LD	HL,MSG_E2
	CALL	@CONSOLE.STRING
	LD	A,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_VERSION)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_LENGTH
	CALL	@CONSOLE.STRING
	LD	A,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_LENGTH)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_WINDOW
	CALL	@CONSOLE.STRING
	LD	A,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_WINDOW)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_E3
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_RX_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_TX
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_TX_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_FIFO
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_FIFO_DIAG)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_NET
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_NET_DIAG)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_MEDIA
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_MEDIA_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_FILTER
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_RX_FILTER)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_MASKS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_INTR_MASK)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_READ_ZERO)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_E4
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_RX_EARLY)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_TX_AVAILABLE)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_TX_START)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_RESETS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_COUNT_RESET)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_COUNT_TIMEOUT)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_COUNT_RX)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_COUNT_TX)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_COUNT_DROP)
	CALL	@CONSOLE.HEX16
	LD	A,'/'
	CALL	@CONSOLE.CHAR
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_COUNT_FRAME)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(CLI_VERBOSE)
	OR	A
	RET	Z
	LD	HL,MSG_EV
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_LAST_COMMAND)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_SNAPSHOT_BUFFER + EL3_SNAP_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_MAC
	CALL	@CONSOLE.STRING
	LD	HL,EL3_SNAPSHOT_BUFFER + EL3_SNAP_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_E5
	LD	HL,MSG_E5
	CALL	@CONSOLE.STRING
	LD	A,(SUCCESS_COUNT)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_HELP
	LD	HL,MSG_HELP
	JP	@CONSOLE.LINE

FAIL
	LD	(FAIL_CODE),A
	LD	HL,MSG_ERROR_STAGE
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_STAGE)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_ERROR_CODE
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_WAITQ
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_TICKS)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_ERROR_TARGET
	CALL	@CONSOLE.STRING
	LD	HL,MSG_ERROR_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_ERROR_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ERROR_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ERROR_COMMAND
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_COMMAND)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_ERROR_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	CP	EL3_ERR_INIT_VERIFY
	JR	NZ,.NO_VERIFY_DETAIL
	LD	HL,MSG_VERIFY_FIELD
	CALL	@CONSOLE.STRING
	LD	A,(EL3_VERIFY_FIELD)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_VERIFY_ACTUAL
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_VERIFY_ACTUAL)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_VERIFY_EXPECTED
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_VERIFY_EXPECTED)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
.NO_VERIFY_DETAIL
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(FAIL_CODE)
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	C,DSS_EXIT
	RST	DSS

SUCCESS
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN 0

MSG_BANNER	DB "3C509B EL3REG v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: EL3REG [-v] [-s 0|1] [-p #100..#1F0] [-b AUTO|#200..#3E0] [-n 1..100]",0
MSG_E0		DB "[E0] TIMER=CYCLES21 SLOT=",0
MSG_IDPORT	DB " IDPORT=",0
MSG_COUNT	DB " CYCLES=",0
MSG_E1		DB "[E1] PRODUCT=",0
MSG_BASE	DB " BASE=",0
MSG_MAC		DB " MAC=",0
MSG_E2		DB "[E2] SNAPSHOT v=",0
MSG_LENGTH	DB " len=",0
MSG_WINDOW	DB " window=",0
MSG_STATUS	DB " status=",0
MSG_E3		DB "[E3] RX=",0
MSG_TX		DB " TX=",0
MSG_FIFO	DB " FIFO=",0
MSG_NET		DB " NET=",0
MSG_MEDIA	DB " MEDIA=",0
MSG_FILTER	DB " FILTER=",0
MSG_MASKS	DB " MASKS=",0
MSG_E4		DB "[E4] THRESH=",0
MSG_RESETS	DB " RESETS=",0
MSG_EV		DB "[EV] CMD=",0
MSG_E5		DB "[E5] CYCLES OK=",0
MSG_ERROR_STAGE DB "ERROR stage=",0
MSG_ERROR_CODE	DB " code=",0
MSG_WAITQ	DB " waitq=",0
MSG_ERROR_TARGET DB " target=CYCLES21",0
MSG_ERROR_SLOT	DB " slot=",0
MSG_ERROR_IDPORT DB " idport=",0
MSG_ERROR_BASE	DB " base=",0
MSG_ERROR_COMMAND DB " command=",0
MSG_ERROR_STATUS DB " status=",0
MSG_VERIFY_FIELD DB "[EV] VERIFY field=",0
MSG_VERIFY_ACTUAL DB " actual=",0
MSG_VERIFY_EXPECTED DB " expected=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
REMAINING	DB 0
SUCCESS_COUNT	DB 0
FAIL_CODE	DB 0
SAVED_STAGE	DB 0
SAVED_TICKS	DW 0
SAVED_STATUS	DW 0
SAVED_COMMAND	DW 0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
