; EL3RX.EXE - bounded physical Ethernet II receiver diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
RX_BUFFER	EQU 0x4800

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	@S6APP.CLEAR
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@CLI6.PARSE_RX
	JR	C,PARSE_RESULT
	CALL	PRINT_CONFIG
	CALL	@S6APP.PREPARE
	JR	C,FAIL_CLEANUP
	CALL	PRINT_CARD
	LD	HL,(CLI_COUNT)
	LD	(S6_REMAINING),HL
.RECEIVE_LOOP
	CALL	@S6APP.WAIT_RX
	JR	C,FAIL_CLEANUP
	LD	HL,RX_BUFFER
	LD	BC,EL3_FRAME_MAX
	CALL	@EL3.READ_FRAME
	LD	(S6_ACTUAL_LENGTH),BC
	JR	C,FAIL_CLEANUP
	LD	HL,RX_BUFFER
	CALL	@CRC32.COMPUTE
	CALL	PRINT_FRAME
	LD	A,(CLI_HEXDUMP)
	OR	A
	CALL	NZ,PRINT_DUMP
	LD	HL,(S6_REMAINING)
	DEC	HL
	LD	(S6_REMAINING),HL
	LD	A,H
	OR	L
	JR	NZ,.RECEIVE_LOOP
	XOR	A
	CALL	@S6APP.CLEANUP
	JR	C,FAIL_DIRECT
	JP	SUCCESS

PARSE_RESULT
	CP	EL3_CLI_HELP
	JR	NZ,.BAD
	CALL	PRINT_HELP
	JP	SUCCESS
.BAD
	LD	(S6_FAIL_CODE),A
	CALL	PRINT_HELP
	LD	A,(S6_FAIL_CODE)
	JP	FAIL_DIRECT

FAIL_CLEANUP
	CALL	@S6APP.CLEANUP
FAIL_DIRECT
	LD	(S6_FAIL_CODE),A
	CALL	PRINT_ERROR
	LD	A,(S6_FAIL_CODE)
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	C,DSS_EXIT
	RST	DSS

SUCCESS
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN 0

PRINT_CONFIG
	LD	HL,MSG_R0
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_COUNT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_COUNT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_WAIT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_WAIT)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_CARD
	LD	HL,MSG_R1
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_MAC
	CALL	@CONSOLE.STRING
	LD	HL,EL3_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_FRAME
	LD	HL,MSG_R2
	CALL	@CONSOLE.STRING
	LD	HL,RX_BUFFER+6
	CALL	@CONSOLE.MAC
	LD	HL,MSG_DEST
	CALL	@CONSOLE.STRING
	LD	HL,RX_BUFFER
	CALL	@CONSOLE.MAC
	LD	HL,MSG_TYPE
	CALL	@CONSOLE.STRING
	LD	A,(RX_BUFFER+12)
	LD	H,A
	LD	A,(RX_BUFFER+13)
	LD	L,A
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_LENGTH
	CALL	@CONSOLE.STRING
	LD	HL,(S6_ACTUAL_LENGTH)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_CRC
	CALL	@CONSOLE.STRING
	LD	A,(CRC32_VALUE+3)
	CALL	@CONSOLE.HEX8
	LD	A,(CRC32_VALUE+2)
	CALL	@CONSOLE.HEX8
	LD	A,(CRC32_VALUE+1)
	CALL	@CONSOLE.HEX8
	LD	A,(CRC32_VALUE+0)
	CALL	@CONSOLE.HEX8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

; Full 16-byte hex/ASCII lines. No packet bytes are treated as FCS.
PRINT_DUMP
	LD	HL,RX_BUFFER
	LD	(DUMP_POINTER),HL
	LD	HL,(S6_ACTUAL_LENGTH)
	LD	(DUMP_REMAIN),HL
.LINE
	LD	HL,(DUMP_REMAIN)
	LD	A,H
	OR	L
	RET	Z
	LD	HL,(DUMP_POINTER)
	LD	DE,RX_BUFFER
	OR	A
	SBC	HL,DE
	CALL	@CONSOLE.HEX16
	LD	A,':'
	CALL	@CONSOLE.CHAR
	LD	HL,(DUMP_REMAIN)
	LD	A,H
	OR	A
	JR	NZ,.FULL_LINE
	LD	A,L
	CP	16
	JR	C,.SHORT_LINE
.FULL_LINE
	LD	A,16
.SHORT_LINE
	LD	(DUMP_LINE_COUNT),A
	LD	B,A
	LD	HL,(DUMP_POINTER)
.HEX_LOOP
	LD	A,' '
	CALL	@CONSOLE.CHAR
	LD	A,(HL)
	CALL	@CONSOLE.HEX8
	INC	HL
	DJNZ	.HEX_LOOP
	LD	A,(DUMP_LINE_COUNT)
	LD	B,A
.HEX_PAD
	LD	A,B
	CP	16
	JR	Z,.ASCII_START
	LD	A,' '
	CALL	@CONSOLE.CHAR
	CALL	@CONSOLE.CHAR
	CALL	@CONSOLE.CHAR
	INC	B
	JR	.HEX_PAD
.ASCII_START
	LD	A,' '
	CALL	@CONSOLE.CHAR
	LD	A,'|'
	CALL	@CONSOLE.CHAR
	LD	HL,(DUMP_POINTER)
	LD	A,(DUMP_LINE_COUNT)
	LD	B,A
.ASCII_LOOP
	LD	A,(HL)
	CP	32
	JR	C,.DOT
	CP	127
	JR	C,.ASCII_PUT
.DOT
	LD	A,'.'
.ASCII_PUT
	CALL	@CONSOLE.CHAR
	INC	HL
	DJNZ	.ASCII_LOOP
	LD	A,'|'
	CALL	@CONSOLE.CHAR
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(DUMP_LINE_COUNT)
	LD	E,A
	LD	D,0
	LD	HL,(DUMP_POINTER)
	ADD	HL,DE
	LD	(DUMP_POINTER),HL
	LD	HL,(DUMP_REMAIN)
	OR	A
	SBC	HL,DE
	LD	(DUMP_REMAIN),HL
	JP	.LINE

PRINT_HELP
	LD	HL,MSG_HELP
	JP	@CONSOLE.LINE

PRINT_ERROR
	LD	HL,MSG_ERROR
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_STAGE)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_CODE
	CALL	@CONSOLE.STRING
	LD	A,(S6_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_WAITQ
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_RX
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_RX_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(S6_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

MSG_BANNER	DB "3C509B EL3RX v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: EL3RX [-v] [-x] [-s 0|1] [-p #100..#1F0] [-b AUTO|#200..#3E0] [-n 1..100] [-w 1..10000]",0
MSG_R0		DB "[R0] SLOT=",0
MSG_IDPORT	DB " IDPORT=",0
MSG_COUNT	DB " COUNT=#",0
MSG_WAIT	DB " WAITQ=#",0
MSG_R1		DB "[R1] LINK=UP BASE=",0
MSG_MAC		DB " MAC=",0
MSG_R2		DB "[R2] SOURCE=",0
MSG_DEST	DB " DEST=",0
MSG_TYPE	DB " TYPE=#",0
MSG_LENGTH	DB " LENGTH=#",0
MSG_CRC		DB " CRC32=#",0
MSG_ERROR	DB "ERROR stage=",0
MSG_CODE	DB " code=",0
MSG_WAITQ	DB " waitq=#",0
MSG_BASE	DB " target=CYCLES21 base=",0
MSG_STATUS	DB " status=",0
MSG_RX		DB " rx=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
DUMP_POINTER	DW 0
DUMP_REMAIN	DW 0
DUMP_LINE_COUNT DB 0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli_stage6.asm"
	INCLUDE "console.asm"
	INCLUDE "crc32.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "stage6_app.asm"
