; EL3TX.EXE - bounded physical Ethernet II transmitter diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
TX_BUFFER	EQU 0x4000

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	@S6APP.CLEAR
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@CLI6.PARSE_TX
	JR	C,PARSE_RESULT
	CALL	PRINT_CONFIG
	CALL	@S6APP.PREPARE
	JR	C,FAIL_CLEANUP
	CALL	PRINT_CARD
	LD	HL,(CLI_COUNT)
	LD	(S6_REMAINING),HL
	XOR	A
	LD	(S6_SEQUENCE),A
.SEND_LOOP
	CALL	BUILD_FRAME
	LD	HL,TX_BUFFER
	LD	BC,(CLI_LENGTH)
	CALL	@EL3.SEND_FRAME
	JR	C,FAIL_CLEANUP
	LD	A,(S6_SEQUENCE)
	INC	A
	LD	(S6_SEQUENCE),A
	LD	HL,(S6_REMAINING)
	DEC	HL
	LD	(S6_REMAINING),HL
	LD	A,H
	OR	L
	JR	NZ,.SEND_LOOP
	XOR	A
	CALL	@S6APP.CLEANUP
	JR	C,FAIL_DIRECT
	LD	HL,MSG_SENT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_COUNT)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

PARSE_RESULT
	CP	EL3_CLI_HELP
	JR	NZ,.BAD
	CALL	PRINT_HELP
	JP	SUCCESS
.BAD
	LD	(S6_FAIL_CODE),A
	CALL	PRINT_HELP
	LD	A,(S6_FAIL_CODE)
	JP	FAIL_DIRECT

FAIL_CLEANUP
	CALL	@S6APP.CLEANUP
FAIL_DIRECT
	LD	(S6_FAIL_CODE),A
	CALL	PRINT_ERROR
	LD	A,(S6_FAIL_CODE)
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	C,DSS_EXIT
	RST	DSS

SUCCESS
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN 0

; Ethernet II header uses the requested destination and factory source.
; INC starts at the zero-based burst sequence, making ordering observable.
BUILD_FRAME
	LD	HL,CLI_DEST_MAC
	LD	DE,TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,EL3_MAC
	LD	BC,6
	LDIR
	LD	HL,(CLI_ETHERTYPE)
	LD	A,H
	LD	(DE),A
	INC	DE
	LD	A,L
	LD	(DE),A
	INC	DE
	LD	HL,(CLI_LENGTH)
	LD	BC,14
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L
	LD	A,(S6_SEQUENCE)
	LD	(PATTERN_INDEX),A
.PAYLOAD
	LD	A,B
	OR	C
	RET	Z
	CALL	PATTERN_BYTE
	LD	(DE),A
	INC	DE
	DEC	BC
	JR	.PAYLOAD

PATTERN_BYTE
	LD	A,(CLI_PATTERN)
	OR	A
	RET	Z
	CP	1
	JR	NZ,.CHECK_55
	LD	A,0xFF
	RET
.CHECK_55
	CP	2
	JR	NZ,.CHECK_AA
	LD	A,0x55
	RET
.CHECK_AA
	CP	3
	JR	NZ,.INCREMENT
	LD	A,0xAA
	RET
.INCREMENT
	LD	A,(PATTERN_INDEX)
	INC	A
	LD	(PATTERN_INDEX),A
	DEC	A
	RET

PRINT_CONFIG
	LD	HL,MSG_T0
	CALL	@CONSOLE.STRING
	LD	A,(CLI_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_IDPORT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_IDPORT)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_DEST
	CALL	@CONSOLE.STRING
	LD	HL,CLI_DEST_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_CARD
	LD	HL,MSG_T1
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_SOURCE
	CALL	@CONSOLE.STRING
	LD	HL,EL3_MAC
	CALL	@CONSOLE.MAC
	LD	HL,MSG_TYPE
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_ETHERTYPE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_LENGTH
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_LENGTH)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_WAIT
	CALL	@CONSOLE.STRING
	LD	HL,(CLI_WAIT)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_HELP
	LD	HL,MSG_HELP
	JP	@CONSOLE.LINE

PRINT_ERROR
	LD	HL,MSG_ERROR
	CALL	@CONSOLE.STRING
	LD	A,(EL3_LAST_STAGE)
	CALL	@CONSOLE.HEX8
	LD	HL,MSG_CODE
	CALL	@CONSOLE.STRING
	LD	A,(S6_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_WAITQ
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(S6_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

MSG_BANNER	DB "3C509B EL3TX v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: EL3TX [-v] [-s 0|1] [-p #100..#1F0] [-b AUTO|#200..#3E0] -d MAC "
		DB "[-t #0600..#FFFF] [-l 14..1514] [-f 00|FF|55|AA|INC] [-n 1..100] [-w 1..10000]",0
MSG_T0		DB "[T0] SLOT=",0
MSG_IDPORT	DB " IDPORT=",0
MSG_DEST	DB " DEST=",0
MSG_T1		DB "[T1] LINK=UP BASE=",0
MSG_SOURCE	DB " SOURCE=",0
MSG_TYPE	DB " TYPE=#",0
MSG_LENGTH	DB " LENGTH=#",0
MSG_WAIT	DB " WAITQ=#",0
MSG_SENT	DB "[T2] SENT=#",0
MSG_ERROR	DB "ERROR stage=",0
MSG_CODE	DB " code=",0
MSG_WAITQ	DB " waitq=#",0
MSG_BASE	DB " target=CYCLES21 base=",0
MSG_STATUS	DB " status=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
PATTERN_INDEX	DB 0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli_stage6.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "stage6_app.asm"
