; IFUP.EXE - static link validation or fresh DHCP acquire.
; Stage 7 intentionally has no renewal, RELEASE, -r, -d or persistent state.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
SCAN_C		EQU 0xAC		; DSS positional scancode for C with bit 7 set
DHCP_SERVER_TEXT EQU 0x6100
DHCP_LEASE_TEXT EQU 0x6120

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	@S7APP.CLEAR
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	CHECK_ARGS
	JP	C,USAGE
	LD	A,(IFUP_HELP)
	OR	A
	JP	NZ,HELP_ONLY
	CALL	@S7APP.ALLOCATE
	JP	C,LOCAL_FAIL
	CALL	@S7APP.LOAD_ENV_CONFIG
	JP	C,CONFIG_FAIL
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_APP
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.INIT
	CALL	PREPARE_EMPTY_DESIRED
	LD	HL,DESIRED_TABLE
	CALL	@NETENV.PUBLISH		; stale lease is gone before any wire attempt
	JP	C,LOCAL_FAIL
.INIT
	CALL	@S7APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JR	NC,.LINK_OK
	LD	(NETDRV_FAIL_CODE),A
	CP	EL3_ERR_LINK_TIMEOUT
	CALL	Z,PRINT_LINK_TIMEOUT
	LD	A,(NETDRV_FAIL_CODE)
	JP	NETWORK_FAIL
.LINK_OK
	LD	HL,MSG_LINK
	CALL	@CONSOLE.LINE
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_APP
	CALL	@NETPARSE.STR_EQ_CI
	JP	NZ,STATIC_OK
	CALL	DHCP_ACQUIRE
	JR	NC,.LEASE
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.LEASE
	CALL	PUBLISH_LEASE
	JP	C,LOCAL_FAIL
	LD	HL,MSG_DHCP_OK
	CALL	@CONSOLE.STRING
	LD	HL,DHCP_OFFERED_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

STATIC_OK
	LD	HL,MSG_STATIC
	CALL	@CONSOLE.STRING
	LD	HL,NET_LOCAL_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

DHCP_ACQUIRE
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.GEN_XID
	LD	HL,RETRY_SECONDS
	LD	(DHCP_RETRY_PTR),HL
	LD	A,4
	LD	(DHCP_RETRIES_LEFT),A
	CALL	@S7APP.WAIT_SECOND_EDGE
	RET	C
.DISCOVER
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.BUILD_DISCOVER
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	LD	A,DHCP_OFFER
	CALL	WAIT_REPLY
	JR	NC,.OFFERED
	CP	NETDRV_ERR_CANCELLED
	JR	NZ,.DISCOVER_NOT_CANCELLED
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.DISCOVER_NOT_CANCELLED
	CP	DHCP_NAK
	JR	Z,.NAK
	CALL	NEXT_RETRY
	JR	NC,.DISCOVER
	JR	.TIMEOUT
.OFFERED
	LD	HL,MSG_OFFER
	CALL	@CONSOLE.LINE
	LD	HL,RETRY_SECONDS
	LD	(DHCP_RETRY_PTR),HL
	LD	A,4
	LD	(DHCP_RETRIES_LEFT),A
	CALL	@S7APP.WAIT_SECOND_EDGE
	RET	C
.REQUEST
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.BUILD_REQUEST
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	LD	A,DHCP_ACK
	CALL	WAIT_REPLY
	RET	NC
	CP	NETDRV_ERR_CANCELLED
	JR	NZ,.REQUEST_NOT_CANCELLED
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.REQUEST_NOT_CANCELLED
	CP	DHCP_NAK
	JR	Z,.NAK
	CALL	NEXT_RETRY
	JR	NC,.REQUEST
.TIMEOUT
	CALL	PRINT_DHCP_TIMEOUT
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.NAK
	LD	HL,MSG_NAK
	CALL	@CONSOLE.LINE
	LD	A,DHCP_NAK
	SCF
	RET

NEXT_RETRY
	LD	A,(DHCP_RETRIES_LEFT)
	DEC	A
	LD	(DHCP_RETRIES_LEFT),A
	JR	Z,.DONE
	LD	HL,(DHCP_RETRY_PTR)
	INC	HL
	LD	(DHCP_RETRY_PTR),HL
	OR	A
	RET
.DONE
	SCF
	RET

; WAIT_REPLY: A=expected DHCP type. Uses the current retry interval. Every
; complete RX frame is read exactly once; malformed/foreign traffic is ignored.
WAIT_REPLY
	LD	(DHCP_EXPECTED),A
	CALL	@S7APP.SECONDS
	LD	(DHCP_START_SECOND),A
.POLL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.TICK
	LD	HL,STAGE7_RX_BUFFER
	LD	BC,STAGE7_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	C,.TICK			; EL3 already consumed malformed/oversize
	LD	HL,STAGE7_RX_BUFFER
	CALL	@DHCP.PARSE_REPLY
	JR	C,.TICK
	LD	A,(DHCP_MSG_TYPE)
	CP	DHCP_NAK
	JR	Z,.NAK
	LD	B,A
	LD	A,(DHCP_EXPECTED)
	CP	B
	JR	NZ,.TICK
	XOR	A
	RET
.NAK
	LD	A,DHCP_NAK
	SCF
	RET
.TICK
	CALL	@S7APP.WAIT_TICK
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.TIME
	LD	A,E
	CP	0x1B
	JR	Z,.CANCEL
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.TIME
	LD	A,D
	CP	SCAN_C
	JR	Z,.CANCEL
.TIME
	CALL	@S7APP.SECONDS
	LD	B,A
	LD	A,(DHCP_START_SECOND)
	LD	C,A
	LD	A,B
	SUB	C
	JR	NC,.ELAPSED
	ADD	A,60
.ELAPSED
	LD	(DHCP_LAST_ELAPSED),A
	LD	HL,(DHCP_RETRY_PTR)
	CP	(HL)
	JR	C,.POLL
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

PREPARE_EMPTY_DESIRED
	LD	HL,DESIRED_BASE
	LD	DE,DESIRED_TABLE
	LD	BC,ENV_VAR_COUNT*2
	LDIR
	RET

PUBLISH_LEASE
	LD	HL,DHCP_OFFERED_IP
	LD	DE,NCV_IP
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,DHCP_MASK
	LD	DE,NCV_MASK
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+6*2),HL
	LD	HL,DHCP_ROUTER
	LD	DE,NCV_GW
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+7*2),HL
	LD	HL,DHCP_DNS1
	LD	DE,NCV_DNS1
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+8*2),HL
	LD	HL,DHCP_DNS2
	LD	DE,NCV_DNS2
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+9*2),HL
	LD	HL,DHCP_SERVER_ID
	LD	DE,DHCP_SERVER_TEXT
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+12*2),HL
	LD	HL,DHCP_LEASE_SECS
	LD	DE,DHCP_LEASE_TEXT
	CALL	@NETENV.FORMAT_U32
	LD	HL,DHCP_LEASE_TEXT
	LD	(DESIRED_TABLE+13*2),HL
	LD	HL,NCV_IP
	LD	(DESIRED_TABLE+5*2),HL
	LD	HL,DESIRED_TABLE
	JP	@NETENV.PUBLISH

; Formats nonzero IP and returns HL=destination start, or HL=0 for absent.
FORMAT_OPTION_IP
	LD	(FORMAT_DEST),DE
	PUSH	HL
	LD	B,4
	XOR	A
.OR
	OR	(HL)
	INC	HL
	DJNZ	.OR
	POP	HL
	JR	Z,.EMPTY
	LD	DE,(FORMAT_DEST)
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,(FORMAT_DEST)
	RET
.EMPTY
	LD	HL,0
	RET

CHECK_ARGS
	LD	HL,(CMDLINE_SOURCE)
	LD	B,(HL)
	LD	A,B
	OR	A
	RET	Z
	INC	HL
.SPACE
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	' '
	JR	Z,.NEXT
	CP	9
	JR	Z,.NEXT
	CP	'-'
	JR	Z,.PREFIX
	CP	'/'
	JR	NZ,.BAD
.PREFIX
	INC	HL
	DEC	B
	JR	Z,.BAD
	LD	A,(HL)
	CP	'?'
	JR	Z,.HELP
	CALL	@NETPARSE.UPPER_A
	CP	'H'
	JR	NZ,.BAD
.HELP
	INC	HL
	DEC	B
	CALL	ONLY_SPACES
	RET	C
	LD	A,1
	LD	(IFUP_HELP),A
	OR	A
	RET
.NEXT
	INC	HL
	DEC	B
	JR	.SPACE
.BAD
	SCF
	RET

ONLY_SPACES
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	' '
	JR	Z,.NEXT
	CP	9
	JR	NZ,.BAD
.NEXT
	INC	HL
	DEC	B
	JR	ONLY_SPACES
.BAD
	SCF
	RET

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(IFUP_EXIT_CODE),A
	XOR	A
	CALL	@S7APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
HELP_ONLY
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
USAGE
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(IFUP_EXIT_CODE),A
	LD	A,C
	CALL	@S7APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(IFUP_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

PRINT_IP
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,ENV_SET_BUFFER
	JP	@CONSOLE.STRING

PRINT_LINK_TIMEOUT
	LD	HL,MSG_LINK_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	CALL	PRINT_DEVICE_STATUS
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_DHCP_TIMEOUT
	LD	HL,MSG_DHCP_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	A,(DHCP_EXPECTED)
	CP	DHCP_OFFER
	LD	HL,MSG_DHCP_ACK_STAGE
	JR	NZ,.STAGE
	LD	HL,MSG_DHCP_OFFER_STAGE
.STAGE
	CALL	@CONSOLE.STRING
	LD	HL,MSG_ELAPSED
	CALL	@CONSOLE.STRING
	LD	A,(DHCP_LAST_ELAPSED)
	CALL	@CONSOLE.DEC8
	CALL	PRINT_DEVICE_STATUS
	LD	HL,MSG_DHCP_TARGET
	CALL	@CONSOLE.LINE
	RET

PRINT_DEVICE_STATUS
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	JP	@CONSOLE.HEX16

MSG_BANNER	DB "3C509B IFUP v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: IFUP",0
MSG_LINK	DB "[I0] LINK UP",0
MSG_STATIC	DB "[I1] STATIC IP=",0
MSG_OFFER	DB "[I1] DHCP OFFER",0
MSG_DHCP_OK	DB "[I2] DHCP ACK IP=",0
MSG_NAK		DB "[I2] DHCP NAK",0
MSG_LINK_TIMEOUT DB "[I0] TIMEOUT stage=LINK elapsed_waitq=#",0
MSG_DHCP_TIMEOUT DB "[I2] TIMEOUT stage=",0
MSG_DHCP_OFFER_STAGE DB "DHCP_OFFER",0
MSG_DHCP_ACK_STAGE DB "DHCP_ACK",0
MSG_ELAPSED	DB " elapsed_sec=",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=#",0
MSG_DHCP_TARGET DB " target=255.255.255.255:67",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
VALUE_DHCP_APP	DB "DHCP",0
RETRY_SECONDS	DB 4,8,16,16

DESIRED_BASE
	DW NCV_NET,NCV_HW,NCV_IDPORT,NCV_MAC,NCV_IP_SRC
	DW 0,0,0,0,0,NCV_NTP,NCV_TZ,0,0
DESIRED_TABLE	DS ENV_VAR_COUNT*2,0
DHCP_RETRY_PTR	DW 0
FORMAT_DEST	DW 0
DHCP_RETRIES_LEFT DB 0
DHCP_EXPECTED	DB 0
DHCP_START_SECOND DB 0
DHCP_LAST_ELAPSED DB 0
IFUP_EXIT_CODE	DB DSS_EXIT_NETWORK
IFUP_HELP	DB 0

	ENDMODULE

	ASSERT $ < 0xC000

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "dhcp.asm"
	INCLUDE "netparse.asm"
	INCLUDE "netenv.asm"
	INCLUDE "stage7_app.asm"
