; IFUP.EXE - static validation, DHCP acquire/renew and best-effort RELEASE.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
SCAN_C		EQU 0xAC		; DSS positional scancode for C with bit 7 set
DHCP_SERVER_TEXT EQU 0x6100
DHCP_LEASE_TEXT EQU 0x6120
DHCP_OLD_IP	EQU 0x6200
DHCP_OLD_MASK	EQU 0x6204
DHCP_OLD_ROUTER EQU 0x6208
DHCP_OLD_DNS1	EQU 0x620C
DHCP_OLD_DNS2	EQU 0x6210
DHCP_OLD_LEASE	EQU 0x6214
IFUP_MODE_NORMAL EQU 0
IFUP_MODE_RENEW EQU 1
IFUP_MODE_RELEASE EQU 2
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	SAVE_COMMAND
	CALL	ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	CHECK_ARGS
	JP	C,USAGE
	LD	A,(IFUP_HELP)
	OR	A
	JP	NZ,HELP_ONLY
	CALL	@S7APP.LOAD_ENV_CONFIG
	JP	C,CONFIG_FAIL
	LD	A,(IFUP_MODE)
	CP	IFUP_MODE_RENEW
	JR	Z,.PREPARE_RENEW
	CP	IFUP_MODE_RELEASE
	JR	Z,.PREPARE_RELEASE
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_APP
	CALL	@NETPARSE.STR_EQ_CI
	JR	NZ,.INIT
	CALL	PREPARE_EMPTY_DESIRED
	LD	HL,DESIRED_TABLE
	CALL	@NETENV.PUBLISH		; stale lease is gone before any wire attempt
	JP	C,LOCAL_FAIL
	JR	.INIT
.PREPARE_RENEW
	CALL	LOAD_ACTIVE_LEASE
	JP	C,CONFIG_FAIL
	OR	A
	JP	Z,CONFIG_FAIL
	CALL	PREPARE_EMPTY_DESIRED
	JR	.INIT
.PREPARE_RELEASE
	CALL	LOAD_ACTIVE_LEASE
	JP	C,CONFIG_FAIL
	OR	A
	JP	Z,SUCCESS		; idempotent: no lease and no wire traffic
.INIT
	CALL	@S7APP.INIT_DRIVER
	JR	NC,.DRIVER_OK
	LD	B,A
	LD	A,(IFUP_MODE)
	CP	IFUP_MODE_RELEASE
	LD	A,B
	JP	NZ,HARDWARE_FAIL
	JP	RELEASE_CLEAR		; lease removal does not depend on the card
.DRIVER_OK
	CALL	@S7APP.RECORD_HW
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JR	NC,.LINK_OK
	LD	(NETDRV_FAIL_CODE),A
	LD	B,A
	LD	A,(IFUP_MODE)
	CP	IFUP_MODE_RELEASE
	LD	A,B
	JP	Z,RELEASE_CLEAR
	CP	EL3_ERR_LINK_TIMEOUT
	CALL	Z,PRINT_LINK_TIMEOUT
	LD	A,(NETDRV_FAIL_CODE)
	JP	NETWORK_FAIL
.LINK_OK
	LD	HL,MSG_LINK
	CALL	@CONSOLE.LINE
	LD	A,(IFUP_MODE)
	CP	IFUP_MODE_RENEW
	JP	Z,RENEW_LEASE
	CP	IFUP_MODE_RELEASE
	JP	Z,RELEASE_LEASE
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_APP
	CALL	@NETPARSE.STR_EQ_CI
	JP	NZ,STATIC_OK
	CALL	DHCP_ACQUIRE
	JR	NC,.LEASE
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.LEASE
	CALL	PUBLISH_LEASE
	JP	C,LOCAL_FAIL
	LD	HL,MSG_DHCP_OK
	CALL	@CONSOLE.STRING
	LD	HL,DHCP_OFFERED_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

STATIC_OK
	LD	HL,MSG_STATIC
	CALL	@CONSOLE.STRING
	LD	HL,NET_LOCAL_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	CALL	PREPARE_STATIC_DESIRED
	LD	HL,DESIRED_TABLE
	CALL	@NETENV.PUBLISH		; best effort, see below
	JP	SUCCESS

; PREPARE_STATIC_DESIRED extends the shared base table with the static
; address fields LOAD_ENV_CONFIG already loaded into NCV_* (NCV_IP_SRC=STATIC
; is guaranteed whenever this is called), exactly as NETCFG's own
; PREPARE_DESIRED does for a non-DHCP file. The base table already carries
; NET/HW/IDPORT/MAC/IP_SRC/NTP/TZ and clears the two lease variables, which
; is what a static run wants: no lease exists to keep. Republishing it is
; how a successful static IFUP records the driver's true slot/base, the same
; way DHCP's PUBLISH_LEASE already does.
;
; The publish is deliberately best effort: it refreshes values the
; environment already holds, and the only new one, NET_HW, is a probe hint
; that NETDRV.INIT recovers from on its own. PUBLISH restores every variable
; on failure, so a full or failing environment leaves the previous, complete
; configuration in place -- failing an interface that is genuinely up would
; be the worse answer, and would abort CONNECT.BAT for nothing.
PREPARE_STATIC_DESIRED
	CALL	PREPARE_EMPTY_DESIRED
	LD	HL,NCV_IP
	LD	(DESIRED_TABLE+5*2),HL
	LD	HL,NCV_MASK
	LD	(DESIRED_TABLE+6*2),HL
	LD	HL,NCV_GW
	LD	DE,DESIRED_TABLE+7*2
	CALL	STORE_TEXT_OPTIONAL
	LD	HL,NCV_DNS1
	LD	DE,DESIRED_TABLE+8*2
	CALL	STORE_TEXT_OPTIONAL
	LD	HL,NCV_DNS2
	LD	DE,DESIRED_TABLE+9*2
	JR	STORE_TEXT_OPTIONAL	; tail call: its RET ends this routine

; STORE_TEXT_OPTIONAL: HL -> field, DE -> table slot. An empty field stores a
; zero pointer, which PUBLISH turns into a deletion.
STORE_TEXT_OPTIONAL
	LD	A,(HL)
	OR	A
	JR	NZ,.STORE
	LD	HL,0
.STORE
	EX	DE,HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	RET

; LOAD_ACTIVE_LEASE uses only the public environment. It returns A=1 for the
; exact active-lease contract (DHCP source plus nonzero IP/server/lease), A=0
; when all dynamic identity fields are absent, or CONFIG/CF for static/partial
; state. Optional route/DNS values are parsed for ACK inheritance.
LOAD_ACTIVE_LEASE
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_APP
	CALL	@NETPARSE.STR_EQ_CI
	JP	NZ,.LAL_BAD
	LD	HL,E_LEASE_IP
	LD	DE,NCV_IP
	LD	B,NCV_IP_CAP
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	HL,E_LEASE_SERVER
	LD	DE,DHCP_SERVER_TEXT
	LD	B,NCV_IP_CAP
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	HL,E_LEASE_SECONDS
	LD	DE,DHCP_LEASE_TEXT
	LD	B,11
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	A,(NCV_IP)
	OR	A
	JR	NZ,.LAL_HAVE_IP
	LD	A,(DHCP_SERVER_TEXT)
	LD	B,A
	LD	A,(DHCP_LEASE_TEXT)
	OR	B
	JP	NZ,.LAL_BAD
	XOR	A
	RET
.LAL_HAVE_IP
	LD	A,(DHCP_SERVER_TEXT)
	OR	A
	JP	Z,.LAL_BAD
	LD	A,(DHCP_LEASE_TEXT)
	OR	A
	JP	Z,.LAL_BAD
	LD	HL,E_LEASE_MASK
	LD	DE,NCV_MASK
	LD	B,NCV_MASK_CAP
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	HL,E_LEASE_GW
	LD	DE,NCV_GW
	LD	B,NCV_GW_CAP
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	HL,E_LEASE_DNS1
	LD	DE,NCV_DNS1
	LD	B,NCV_DNS_CAP
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	HL,E_LEASE_DNS2
	LD	DE,NCV_DNS2
	LD	B,NCV_DNS_CAP
	CALL	@S7APP.GET_OPTIONAL
	JP	C,.LAL_BAD
	LD	HL,NCV_IP
	LD	DE,DHCP_OFFERED_IP
	CALL	@NETPARSE.PARSE_IPV4
	JP	C,.LAL_BAD
	LD	HL,DHCP_OFFERED_IP
	LD	DE,NET_LOCAL_IP
	CALL	COPY4
	LD	HL,NCV_MASK
	LD	DE,DHCP_MASK
	CALL	PARSE_OPTIONAL_IP
	JP	C,.LAL_BAD
	LD	HL,DHCP_MASK
	LD	DE,NET_NETMASK
	CALL	COPY4
	LD	HL,NCV_GW
	LD	DE,DHCP_ROUTER
	CALL	PARSE_OPTIONAL_IP
	JP	C,.LAL_BAD
	LD	HL,DHCP_ROUTER
	LD	DE,NET_GATEWAY
	CALL	COPY4
	LD	HL,NCV_DNS1
	LD	DE,DHCP_DNS1
	CALL	PARSE_OPTIONAL_IP
	JP	C,.LAL_BAD
	LD	HL,NCV_DNS2
	LD	DE,DHCP_DNS2
	CALL	PARSE_OPTIONAL_IP
	JP	C,.LAL_BAD
	LD	HL,DHCP_SERVER_TEXT
	LD	DE,DHCP_SERVER_ID
	CALL	@NETPARSE.PARSE_IPV4
	JP	C,.LAL_BAD
	LD	HL,DHCP_LEASE_TEXT
	LD	DE,DHCP_LEASE_SECS
	CALL	@NETPARSE.PARSE_U32
	JP	C,.LAL_BAD
	LD	HL,DHCP_LEASE_SECS
	LD	B,4
	XOR	A
.LAL_LEASE_NONZERO
	OR	(HL)
	INC	HL
	DJNZ	.LAL_LEASE_NONZERO
	JP	Z,.LAL_BAD
	CALL	SAVE_OLD_LEASE
	LD	A,1
	OR	A
	RET
.LAL_BAD
	LD	A,NETDRV_ERR_CONFIG
	SCF
	RET

PARSE_OPTIONAL_IP
	LD	A,(HL)
	OR	A
	JR	NZ,.POI_PARSE
	EX	DE,HL
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	RET
.POI_PARSE
	JP	@NETPARSE.PARSE_IPV4

SAVE_OLD_LEASE
	LD	HL,DHCP_OFFERED_IP
	LD	DE,DHCP_OLD_IP
	CALL	COPY4
	LD	HL,DHCP_MASK
	LD	DE,DHCP_OLD_MASK
	CALL	COPY4
	LD	HL,DHCP_ROUTER
	LD	DE,DHCP_OLD_ROUTER
	CALL	COPY4
	LD	HL,DHCP_DNS1
	LD	DE,DHCP_OLD_DNS1
	CALL	COPY4
	LD	HL,DHCP_DNS2
	LD	DE,DHCP_OLD_DNS2
	CALL	COPY4
	LD	HL,DHCP_LEASE_SECS
	LD	DE,DHCP_OLD_LEASE
COPY4
	LD	BC,4
	LDIR
	RET

; Renewal: three RFC DHCPREQUEST attempts with ciaddr and a fixed 5000 ms
; deadline. Only a valid ACK publishes; timeout/malformed/cancel keep the old
; environment. NAK transactionally removes dynamic fields.
RENEW_LEASE
	CALL	RESOLVE_DHCP_SERVER
	JP	C,NETWORK_FAIL
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.GEN_XID
	LD	HL,RENEW_SECONDS
	LD	(DHCP_RETRY_PTR),HL
	LD	A,3
	LD	(DHCP_RETRIES_LEFT),A
.RL_TRY
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.BUILD_RENEW
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	JP	C,NETWORK_FAIL
	LD	A,DHCP_ACK
	CALL	WAIT_REPLY
	JR	NC,.RL_ACK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	DHCP_NAK
	JR	Z,.RL_NAK
	LD	A,(DHCP_RETRIES_LEFT)
	DEC	A
	LD	(DHCP_RETRIES_LEFT),A
	JR	NZ,.RL_TRY
	LD	A,EL3_ERR_RX_TIMEOUT
	JP	NETWORK_FAIL
.RL_NAK
	CALL	CLEAR_DYNAMIC_LEASE
	JP	C,LOCAL_FAIL
	LD	HL,MSG_NAK
	CALL	@CONSOLE.LINE
	LD	A,DHCP_NAK
	JP	NETWORK_FAIL
.RL_ACK
	CALL	INHERIT_RENEW_FIELDS
	CALL	PUBLISH_LEASE
	JP	C,LOCAL_FAIL
	LD	HL,MSG_RENEW_OK
	CALL	@CONSOLE.STRING
	LD	HL,DHCP_OFFERED_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

INHERIT_RENEW_FIELDS
	LD	HL,DHCP_OFFERED_IP
	CALL	IP_NONZERO
	JR	NZ,.IR_MASK
	LD	HL,DHCP_OLD_IP
	LD	DE,DHCP_OFFERED_IP
	CALL	COPY4
.IR_MASK
	LD	A,(DHCP_OPTION_SEEN)
	AND	DHCP_SEEN_MASK
	JR	NZ,.IR_ROUTER
	LD	HL,DHCP_OLD_MASK
	LD	DE,DHCP_MASK
	CALL	COPY4
.IR_ROUTER
	LD	A,(DHCP_OPTION_SEEN)
	AND	DHCP_SEEN_ROUTER
	JR	NZ,.IR_DNS
	LD	HL,DHCP_OLD_ROUTER
	LD	DE,DHCP_ROUTER
	CALL	COPY4
.IR_DNS
	LD	A,(DHCP_OPTION_SEEN)
	AND	DHCP_SEEN_DNS
	RET	NZ
	LD	HL,DHCP_OLD_DNS1
	LD	DE,DHCP_DNS1
	CALL	COPY4
	LD	HL,DHCP_OLD_DNS2
	LD	DE,DHCP_DNS2
	JP	COPY4

RELEASE_LEASE
	CALL	RESOLVE_DHCP_SERVER
	JR	C,RELEASE_CLEAR		; best effort: state removal still proceeds
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.GEN_XID
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.BUILD_RELEASE
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME	; send failure is deliberately non-fatal
RELEASE_CLEAR
	CALL	CLEAR_DYNAMIC_LEASE
	JP	C,LOCAL_FAIL
	LD	HL,MSG_RELEASED
	CALL	@CONSOLE.LINE
	JP	SUCCESS

CLEAR_DYNAMIC_LEASE
	CALL	PREPARE_EMPTY_DESIRED
	LD	HL,DESIRED_TABLE
	JP	@NETENV.PUBLISH

IP_NONZERO
	LD	B,4
	XOR	A
.IPNZ_LOOP
	OR	(HL)
	INC	HL
	DJNZ	.IPNZ_LOOP
	RET

; Resolve the saved DHCP server for unicast renew/release. Three bounded ARP
; attempts are used; no DSS call occurs while NETDRV has the ISA window open.
RESOLVE_DHCP_SERVER
	LD	HL,DHCP_SERVER_ID
	LD	DE,NET_TARGET_IP
	CALL	COPY4
	LD	HL,NET_TARGET_IP
	CALL	@ARP.SELECT_NEXT_HOP
	RET	C
	OR	A
	RET	NZ
	LD	A,3
	LD	(DHCP_ARP_ATTEMPTS),A
.RDS_TRY
	CALL	@S7APP.WAIT_SECOND_EDGE
	RET	C
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	CALL	WAIT_SERVER_ARP
	RET	NC
	CP	NETDRV_ERR_CANCELLED
	RET	Z
	LD	A,(DHCP_ARP_ATTEMPTS)
	DEC	A
	LD	(DHCP_ARP_ATTEMPTS),A
	JR	NZ,.RDS_TRY
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET

WAIT_SERVER_ARP
	CALL	@S7APP.SECONDS
	LD	(DHCP_START_SECOND),A
.WSA_POLL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.WSA_TICK
	LD	HL,STAGE7_RX_BUFFER
	LD	BC,STAGE7_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	C,.WSA_TICK
	LD	HL,STAGE7_RX_BUFFER
	CALL	@ARP.PARSE
	JR	C,.WSA_TICK
	CP	1
	JR	Z,.WSA_OK
.WSA_TICK
	CALL	@S7APP.WAIT_TICK
	CALL	CHECK_CANCEL_KEY
	JR	C,.WSA_CANCEL
	CALL	@S7APP.SECONDS
	LD	B,A
	LD	A,(DHCP_START_SECOND)
	LD	C,A
	LD	A,B
	SUB	C
	JR	NC,.WSA_ELAPSED
	ADD	A,60
.WSA_ELAPSED
	CP	2
	JR	C,.WSA_POLL
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.WSA_OK
	XOR	A
	RET
.WSA_CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

CHECK_CANCEL_KEY
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.CCK_NO
	LD	A,E
	CP	0x1B
	JR	Z,.CCK_YES
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.CCK_NO
	LD	A,D
	CP	SCAN_C
	JR	Z,.CCK_YES
.CCK_NO
	XOR	A
	RET
.CCK_YES
	SCF
	RET

SAVE_COMMAND
	PUSH	IX
	POP	HL
	LD	A,(HL)
	LD	C,A
	LD	B,0
	INC	BC
	LD	DE,S10_COMMAND_BUFFER
	LDIR
	LD	IX,S10_COMMAND_BUFFER
	RET

ALLOCATE_FRESH
	LD	B,1
	LD	C,DSS_GETMEM
	RST	DSS
	JR	C,.AF_FAIL
	LD	E,A
	PUSH	DE
	LD	B,0
	LD	C,DSS_SETWIN1
	RST	DSS
	POP	DE
	JR	C,.AF_SET_FAIL
	CALL	@S7APP.CLEAR
	LD	A,E
	LD	(NETDRV_MEMORY_BLOCK),A
	LD	A,1
	LD	(NETDRV_PAGE_ALLOCATED),A
	LD	HL,S10_COMMAND_BUFFER
	LD	A,(HL)
	LD	C,A
	LD	B,0
	INC	BC
	LD	DE,S10_PAGE_COMMAND_BUFFER
	LDIR
	LD	IX,S10_PAGE_COMMAND_BUFFER
	XOR	A
	RET
.AF_SET_FAIL
	PUSH	AF
	LD	A,E
	LD	C,DSS_FREEMEM
	RST	DSS
	POP	AF
.AF_FAIL
	LD	A,EL3_ERR_NO_MEMORY
	SCF
	RET

DHCP_ACQUIRE
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.GEN_XID
	LD	HL,RETRY_SECONDS
	LD	(DHCP_RETRY_PTR),HL
	LD	A,4
	LD	(DHCP_RETRIES_LEFT),A
	CALL	@S7APP.WAIT_SECOND_EDGE
	RET	C
.DISCOVER
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.BUILD_DISCOVER
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	LD	A,DHCP_OFFER
	CALL	WAIT_REPLY
	JR	NC,.OFFERED
	CP	NETDRV_ERR_CANCELLED
	JR	NZ,.DISCOVER_NOT_CANCELLED
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.DISCOVER_NOT_CANCELLED
	CP	DHCP_NAK
	JR	Z,.NAK
	CALL	NEXT_RETRY
	JR	NC,.DISCOVER
	JR	.TIMEOUT
.OFFERED
	LD	HL,MSG_OFFER
	CALL	@CONSOLE.LINE
	LD	HL,RETRY_SECONDS
	LD	(DHCP_RETRY_PTR),HL
	LD	A,4
	LD	(DHCP_RETRIES_LEFT),A
	CALL	@S7APP.WAIT_SECOND_EDGE
	RET	C
.REQUEST
	LD	DE,STAGE7_TX_BUFFER
	LD	HL,NETDRV_STATION_MAC
	CALL	@DHCP.BUILD_REQUEST
	LD	HL,STAGE7_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	LD	A,DHCP_ACK
	CALL	WAIT_REPLY
	RET	NC
	CP	NETDRV_ERR_CANCELLED
	JR	NZ,.REQUEST_NOT_CANCELLED
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.REQUEST_NOT_CANCELLED
	CP	DHCP_NAK
	JR	Z,.NAK
	CALL	NEXT_RETRY
	JR	NC,.REQUEST
.TIMEOUT
	CALL	PRINT_DHCP_TIMEOUT
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.NAK
	LD	HL,MSG_NAK
	CALL	@CONSOLE.LINE
	LD	A,DHCP_NAK
	SCF
	RET

NEXT_RETRY
	LD	A,(DHCP_RETRIES_LEFT)
	DEC	A
	LD	(DHCP_RETRIES_LEFT),A
	JR	Z,.DONE
	LD	HL,(DHCP_RETRY_PTR)
	INC	HL
	LD	(DHCP_RETRY_PTR),HL
	OR	A
	RET
.DONE
	SCF
	RET

; WAIT_REPLY: A=expected DHCP type. Uses the current retry interval. Every
; complete RX frame is read exactly once; malformed/foreign traffic is ignored.
WAIT_REPLY
	LD	(DHCP_EXPECTED),A
	CALL	@S7APP.SECONDS
	LD	(DHCP_START_SECOND),A
.POLL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.TICK
	LD	HL,STAGE7_RX_BUFFER
	LD	BC,STAGE7_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	C,.TICK			; EL3 already consumed malformed/oversize
	LD	HL,STAGE7_RX_BUFFER
	LD	A,(IFUP_MODE)
	CP	IFUP_MODE_RENEW
	JR	NZ,.WR_ACQUIRE_PARSE
	CALL	@DHCP.PARSE_RENEW_REPLY
	JR	.WR_PARSED
.WR_ACQUIRE_PARSE
	CALL	@DHCP.PARSE_REPLY
.WR_PARSED
	JR	C,.TICK
	LD	A,(DHCP_MSG_TYPE)
	CP	DHCP_NAK
	JR	Z,.NAK
	LD	B,A
	LD	A,(DHCP_EXPECTED)
	CP	B
	JR	NZ,.TICK
	XOR	A
	RET
.NAK
	LD	A,DHCP_NAK
	SCF
	RET
.TICK
	CALL	@S7APP.WAIT_TICK
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.TIME
	LD	A,E
	CP	0x1B
	JR	Z,.CANCEL
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.TIME
	LD	A,D
	CP	SCAN_C
	JR	Z,.CANCEL
.TIME
	CALL	@S7APP.SECONDS
	LD	B,A
	LD	A,(DHCP_START_SECOND)
	LD	C,A
	LD	A,B
	SUB	C
	JR	NC,.ELAPSED
	ADD	A,60
.ELAPSED
	LD	(DHCP_LAST_ELAPSED),A
	LD	HL,(DHCP_RETRY_PTR)
	CP	(HL)
	JR	C,.POLL
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

PREPARE_EMPTY_DESIRED
	LD	HL,DESIRED_BASE
	LD	DE,DESIRED_TABLE
	LD	BC,ENV_VAR_COUNT*2
	LDIR
	RET

PUBLISH_LEASE
	LD	HL,DHCP_OFFERED_IP
	LD	DE,NCV_IP
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,DHCP_MASK
	LD	DE,NCV_MASK
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+6*2),HL
	LD	HL,DHCP_ROUTER
	LD	DE,NCV_GW
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+7*2),HL
	LD	HL,DHCP_DNS1
	LD	DE,NCV_DNS1
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+8*2),HL
	LD	HL,DHCP_DNS2
	LD	DE,NCV_DNS2
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+9*2),HL
	LD	HL,DHCP_SERVER_ID
	LD	DE,DHCP_SERVER_TEXT
	CALL	FORMAT_OPTION_IP
	LD	(DESIRED_TABLE+12*2),HL
	LD	HL,DHCP_LEASE_SECS
	LD	DE,DHCP_LEASE_TEXT
	CALL	@NETENV.FORMAT_U32
	LD	HL,DHCP_LEASE_TEXT
	LD	(DESIRED_TABLE+13*2),HL
	LD	HL,NCV_IP
	LD	(DESIRED_TABLE+5*2),HL
	LD	HL,DESIRED_TABLE
	JP	@NETENV.PUBLISH

; Formats nonzero IP and returns HL=destination start, or HL=0 for absent.
FORMAT_OPTION_IP
	LD	(FORMAT_DEST),DE
	PUSH	HL
	LD	B,4
	XOR	A
.OR
	OR	(HL)
	INC	HL
	DJNZ	.OR
	POP	HL
	JR	Z,.EMPTY
	LD	DE,(FORMAT_DEST)
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,(FORMAT_DEST)
	RET
.EMPTY
	LD	HL,0
	RET

CHECK_ARGS
	XOR	A
	LD	(IFUP_HELP),A
	LD	(IFUP_MODE),A
	LD	HL,(CMDLINE_SOURCE)
	LD	B,(HL)
	LD	A,B
	OR	A
	RET	Z
	INC	HL
.SPACE
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	' '
	JR	Z,.NEXT
	CP	9
	JR	Z,.NEXT
	CP	'-'
	JR	Z,.PREFIX
	CP	'/'
	JR	NZ,.BAD
.PREFIX
	INC	HL
	DEC	B
	JR	Z,.BAD
	LD	A,(HL)
	CP	'?'
	JR	Z,.HELP
	CALL	@NETPARSE.UPPER_A
	CP	'H'
	JR	Z,.HELP
	CP	'R'
	JR	Z,.RENEW
	CP	'D'
	JR	Z,.RELEASE
	JR	.BAD
.HELP
	INC	HL
	DEC	B
	CALL	ONLY_SPACES
	RET	C
	LD	A,1
	LD	(IFUP_HELP),A
	OR	A
	RET
.RENEW
	LD	A,IFUP_MODE_RENEW
	JR	.SET_MODE
.RELEASE
	LD	A,IFUP_MODE_RELEASE
.SET_MODE
	LD	(IFUP_MODE),A
	INC	HL
	DEC	B
	CALL	ONLY_SPACES
	RET
.NEXT
	INC	HL
	DEC	B
	JR	.SPACE
.BAD
	SCF
	RET

ONLY_SPACES
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	' '
	JR	Z,.NEXT
	CP	9
	JR	NZ,.BAD
.NEXT
	INC	HL
	DEC	B
	JR	ONLY_SPACES
.BAD
	SCF
	RET

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(IFUP_EXIT_CODE),A
	XOR	A
	CALL	@S7APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
HELP_ONLY
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
USAGE
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(IFUP_EXIT_CODE),A
	LD	A,C
	CALL	@S7APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(IFUP_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

PRINT_IP
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,ENV_SET_BUFFER
	JP	@CONSOLE.STRING

PRINT_LINK_TIMEOUT
	LD	HL,MSG_LINK_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	CALL	PRINT_DEVICE_STATUS
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_DHCP_TIMEOUT
	LD	HL,MSG_DHCP_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	A,(DHCP_EXPECTED)
	CP	DHCP_OFFER
	LD	HL,MSG_DHCP_ACK_STAGE
	JR	NZ,.STAGE
	LD	HL,MSG_DHCP_OFFER_STAGE
.STAGE
	CALL	@CONSOLE.STRING
	LD	HL,MSG_ELAPSED
	CALL	@CONSOLE.STRING
	LD	A,(DHCP_LAST_ELAPSED)
	CALL	@CONSOLE.DEC8
	CALL	PRINT_DEVICE_STATUS
	LD	HL,MSG_DHCP_TARGET
	CALL	@CONSOLE.LINE
	RET

PRINT_DEVICE_STATUS
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	JP	@CONSOLE.HEX16

MSG_BANNER	DB "3C509B IFUP v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: IFUP [-r|-d]",0
MSG_LINK	DB "[I0] LINK UP",0
MSG_STATIC	DB "[I1] STATIC IP=",0
MSG_OFFER	DB "[I1] DHCP OFFER",0
MSG_DHCP_OK	DB "[I2] DHCP ACK IP=",0
MSG_RENEW_OK	DB "[I2] DHCP RENEW ACK IP=",0
MSG_RELEASED	DB "[I2] DHCP RELEASED",0
MSG_NAK		DB "[I2] DHCP NAK",0
MSG_LINK_TIMEOUT DB "[I0] TIMEOUT stage=LINK elapsed_waitq=#",0
MSG_DHCP_TIMEOUT DB "[I2] TIMEOUT stage=",0
MSG_DHCP_OFFER_STAGE DB "DHCP_OFFER",0
MSG_DHCP_ACK_STAGE DB "DHCP_ACK",0
MSG_ELAPSED	DB " elapsed_sec=",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=#",0
MSG_DHCP_TARGET DB " target=255.255.255.255:67",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
VALUE_DHCP_APP	DB "DHCP",0
RETRY_SECONDS	DB 4,8,16,16
RENEW_SECONDS	DB 5

E_LEASE_IP	DB "NET_IP",0
E_LEASE_MASK	DB "NET_MASK",0
E_LEASE_GW	DB "NET_GW",0
E_LEASE_DNS1	DB "NET_DNS1",0
E_LEASE_DNS2	DB "NET_DNS2",0
E_LEASE_SERVER	DB "NET_DHCP_SRV",0
E_LEASE_SECONDS DB "NET_LEASE_SEC",0

DESIRED_BASE
	DW NCV_NET,NCV_HW,NCV_IDPORT,NCV_MAC,NCV_IP_SRC
	DW 0,0,0,0,0,NCV_NTP,NCV_TZ,0,0
DESIRED_TABLE	DS ENV_VAR_COUNT*2,0
DHCP_RETRY_PTR	DW 0
FORMAT_DEST	DW 0
DHCP_RETRIES_LEFT DB 0
DHCP_EXPECTED	DB 0
DHCP_START_SECOND DB 0
DHCP_LAST_ELAPSED DB 0
IFUP_EXIT_CODE	DB DSS_EXIT_NETWORK
IFUP_HELP	DB 0
IFUP_MODE	DB IFUP_MODE_NORMAL
DHCP_ARP_ATTEMPTS DB 0

	ENDMODULE

	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "dhcp.asm"
	INCLUDE "netparse.asm"
	INCLUDE "netenv.asm"
	INCLUDE "stage7_app.asm"
