; NETCFG.EXE - transactional NET.CFG reader and NET_* publisher.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	(CMDLINE_SOURCE),IX
	LD	SP,STACK_TOP
	CALL	@S7APP.CLEAR
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	PARSE_ARGS
	JP	C,USAGE
	CALL	@S7APP.ALLOCATE
	JP	C,LOCAL_FAIL
	LD	A,(NETCFG_FLAGS)
	CP	NETCFG_ACTION_SHOW
	JP	Z,SHOW
	CP	NETCFG_ACTION_DELETE
	JP	Z,DELETE
	CP	NETCFG_ACTION_HELP
	JP	Z,HELP
	CP	NETCFG_ACTION_WRITE
	JP	Z,WRITE_CONFIG
	CALL	@NETPARSE.LOAD
	JP	C,CONFIG_FAIL
	LD	A,(NETCFG_FLAGS+1)
	OR	A
	CALL	NZ,PRINT_PARSED
	LD	A,(NETCFG_FLAGS)
	CP	NETCFG_ACTION_CHECK
	JR	NZ,.VERIFY_CARD
	LD	A,(NETCFG_FLAGS+1)
	OR	A
	JP	Z,SUCCESS
.VERIFY_CARD
	CALL	@S7APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	CALL	@S7APP.RECORD_HW
	LD	HL,NETDRV_STATION_MAC
	LD	DE,NCV_MAC
	CALL	@NETENV.FORMAT_MAC
	LD	A,(NETCFG_FLAGS)
	CP	NETCFG_ACTION_INIT
	JP	NZ,SUCCESS
	CALL	PREPARE_DESIRED
	LD	HL,DESIRED_TABLE
	CALL	@NETENV.PUBLISH
	JP	C,LOCAL_FAIL
	LD	HL,MSG_PUBLISHED
	CALL	@CONSOLE.LINE
	JR	SUCCESS

SHOW
	LD	HL,MSG_CURRENT
	CALL	@CONSOLE.LINE
	LD	IX,@NETENV.ENV_NAMES
	LD	B,ENV_VAR_COUNT
.LOOP
	PUSH	BC,IX
	LD	HL,MSG_INDENT
	CALL	@CONSOLE.STRING
	PUSH	IX
	POP	HL
	CALL	@CONSOLE.STRING
	LD	HL,MSG_EQUALS
	CALL	@CONSOLE.STRING
	PUSH	IX
	POP	HL
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.GET
	OR	A
	JR	Z,.UNSET
	LD	HL,ENV_SET_BUFFER
	CALL	@CONSOLE.LINE
	JR	.NEXT
.UNSET
	LD	HL,MSG_UNSET
	CALL	@CONSOLE.LINE
.NEXT
	POP	IX,BC
	CALL	NEXT_NAME
	DJNZ	.LOOP
	JR	SUCCESS

DELETE
	CALL	@NETENV.DELETE_ALL
	JP	C,LOCAL_FAIL
	LD	HL,MSG_DELETED
	CALL	@CONSOLE.LINE
	JR	SUCCESS

HELP
	CALL	PRINT_HELP
	JR	SUCCESS

WRITE_CONFIG
	CALL	@NETCFGWRITE.RUN
	JR	NC,SUCCESS
	CP	NETDRV_ERR_CANCELLED
	LD	B,DSS_EXIT_CANCELLED
	JR	Z,FAIL_WITH_EXIT
	CP	NETDRV_ERR_CONFIG
	LD	B,DSS_EXIT_CONFIG
	JR	Z,FAIL_WITH_EXIT
	LD	B,DSS_EXIT_LOCAL
	JR	FAIL_WITH_EXIT

SUCCESS
	XOR	A
	CALL	@S7APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK

USAGE
	CALL	PRINT_HELP
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL_WITH_EXIT
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL_WITH_EXIT
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL_WITH_EXIT
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL_WITH_EXIT
	LD	C,A
	LD	A,B
	LD	(NETCFG_EXIT_CODE),A
	LD	A,C
	CALL	@S7APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(NETCFG_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

PRINT_HELP
	LD	HL,MSG_HELP
	JP	@CONSOLE.STRING

PRINT_PARSED
	LD	HL,MSG_VERIFIED
	CALL	@CONSOLE.STRING
	LD	A,(NETCFG_WARNINGS)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_HW
	CALL	@CONSOLE.STRING
	LD	HL,NCV_HW
	CALL	@CONSOLE.STRING
	LD	HL,MSG_IPSRC
	CALL	@CONSOLE.STRING
	LD	HL,NCV_IP_SRC
	CALL	@CONSOLE.LINE
	RET

PREPARE_DESIRED
	LD	HL,DESIRED_DEFAULTS
	LD	DE,DESIRED_TABLE
	LD	BC,ENV_VAR_COUNT*2
	LDIR
	LD	HL,NCV_IP_SRC
	LD	DE,VALUE_DHCP_APP
	CALL	@NETPARSE.STR_EQ_CI
	RET	Z
	LD	HL,NCV_IP
	LD	(DESIRED_TABLE+5*2),HL
	LD	HL,NCV_MASK
	LD	(DESIRED_TABLE+6*2),HL
	LD	HL,NCV_GW
	CALL	STORE_OPTIONAL_7
	LD	HL,NCV_DNS1
	CALL	STORE_OPTIONAL_8
	LD	HL,NCV_DNS2
	CALL	STORE_OPTIONAL_9
	RET

STORE_OPTIONAL_7
	LD	DE,DESIRED_TABLE+7*2
	JR	STORE_OPTIONAL
STORE_OPTIONAL_8
	LD	DE,DESIRED_TABLE+8*2
	JR	STORE_OPTIONAL
STORE_OPTIONAL_9
	LD	DE,DESIRED_TABLE+9*2
STORE_OPTIONAL
	LD	A,(HL)
	OR	A
	JR	NZ,.STORE
	LD	HL,0
.STORE
	LD	A,L
	LD	(DE),A
	INC	DE
	LD	A,H
	LD	(DE),A
	RET

; Parses zero or one action and an optional -v modifier. -v alone is verify.
PARSE_ARGS
	XOR	A
	LD	(NETCFG_FLAGS),A
	LD	(NETCFG_FLAGS+1),A
	LD	HL,(CMDLINE_SOURCE)
	LD	B,(HL)
	INC	HL
.SCAN
	LD	A,B
	OR	A
	JR	Z,.DONE
	LD	A,(HL)
	CP	' '
	JR	Z,.SPACE
	CP	9
	JR	Z,.SPACE
	CP	'-'
	JR	Z,.PREFIX
	CP	'/'
	JR	NZ,.BAD
.PREFIX
	INC	HL
	DEC	B
	JR	Z,.BAD
	LD	A,(HL)
	CALL	@NETPARSE.UPPER_A
	INC	HL
	DEC	B
	LD	C,A
	LD	A,B
	OR	A
	JR	Z,.TOKEN
	LD	A,(HL)
	CP	' '
	JR	Z,.TOKEN
	CP	9
	JR	NZ,.BAD
.TOKEN
	LD	A,C
	CP	'?'
	JR	Z,.HELP
	CP	'H'
	JR	Z,.HELP
	CP	'V'
	JR	Z,.VERBOSE
	CP	'I'
	LD	C,NETCFG_ACTION_INIT
	JR	Z,.ACTION
	CP	'C'
	LD	C,NETCFG_ACTION_CHECK
	JR	Z,.ACTION
	CP	'D'
	LD	C,NETCFG_ACTION_DELETE
	JR	Z,.ACTION
	CP	'W'
	LD	C,NETCFG_ACTION_WRITE
	JR	NZ,.BAD
.ACTION
	LD	A,(NETCFG_FLAGS)
	OR	A
	JR	NZ,.BAD
	LD	A,C
	LD	(NETCFG_FLAGS),A
	JR	.SCAN
.VERBOSE
	LD	A,(NETCFG_FLAGS+1)
	OR	A
	JR	NZ,.BAD
	LD	A,1
	LD	(NETCFG_FLAGS+1),A
	JR	.SCAN
.HELP
	LD	A,NETCFG_ACTION_HELP
	LD	(NETCFG_FLAGS),A
	JR	.SCAN
.SPACE
	INC	HL
	DEC	B
	JR	.SCAN
.DONE
	LD	A,(NETCFG_FLAGS+1)
	OR	A
	JR	Z,.OK
	LD	A,(NETCFG_FLAGS)
	OR	A
	JR	NZ,.CHECK_COMBO
	LD	A,NETCFG_ACTION_VERIFY
	LD	(NETCFG_FLAGS),A
	JR	.OK
.CHECK_COMBO
	CP	NETCFG_ACTION_INIT
	JR	Z,.OK
	CP	NETCFG_ACTION_CHECK
	JR	NZ,.BAD
.OK
	XOR	A
	RET
.BAD
	SCF
	RET

NEXT_NAME
.LOOP
	LD	A,(IX+0)
	INC	IX
	OR	A
	JR	NZ,.LOOP
	RET

MSG_BANNER	DB "3C509B NETCFG v",PACKAGE_VERSION,0
MSG_HELP
	DB	"Usage:",13,10
	DB	"  NETCFG           show published NET_* values",13,10
	DB	"  NETCFG -i [-v]   read NET.CFG, check card, publish NET_*",13,10
	DB	"  NETCFG -c [-v]   check NET.CFG; -v also checks card",13,10
	DB	"  NETCFG -d        delete published NET_* values",13,10
	DB	"  NETCFG -v        detailed file/card check; do not publish",13,10
	DB	"  NETCFG -W        interactively create or edit NET.CFG",13,10
	DB	"  NETCFG /?        help (-? and -h are also accepted)",13,10
	DB	"Flags accept - or / and are case-insensitive.",13,10
	DB	"-W cannot combine with -i, -c, -d, or -v.",13,10
	DB	"-W never publishes NET_*; run NETCFG -i and IFUP to apply.",13,10
	DB	"New file: confirm probe of slots 0/1 at the selected IDPORT.",13,10
	DB	"The probe may reset the adapter; EEPROM remains read-only.",13,10
	DB	"A valid existing file loads without a hardware probe.",13,10
	DB	"Exit: 0 OK, 1 arguments, 2 hardware, 4 config,",13,10
	DB	"      5 local error, 7 cancelled.",13,10,0
MSG_CURRENT	DB "[C0] Published environment",0
MSG_INDENT	DB "  ",0
MSG_EQUALS	DB "=",0
MSG_UNSET	DB "<not set>",0
MSG_VERIFIED	DB "[C1] VERIFIED warnings=",0
MSG_HW		DB " HW=",0
MSG_IPSRC	DB " IP_SRC=",0
MSG_PUBLISHED	DB "[C2] ENV COMMIT",0
MSG_DELETED	DB "[C2] ENV DELETE",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0
VALUE_DHCP_APP	DB "DHCP",0

; NET, HW, IDPORT, MAC, IP_SRC, IP, MASK, GW, DNS1, DNS2, NTP, TZ,
; DHCP server and lease. Dynamic fields default to deletion.
DESIRED_DEFAULTS
	DW NCV_NET,NCV_HW,NCV_IDPORT,NCV_MAC,NCV_IP_SRC
	DW 0,0,0,0,0,NCV_NTP,NCV_TZ,0,0
DESIRED_TABLE	DS ENV_VAR_COUNT*2,0
NETCFG_EXIT_CODE DB DSS_EXIT_LOCAL

	ENDMODULE

	ASSERT $ < 0xC000

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "netparse.asm"
	INCLUDE "netparse_file.asm"
	INCLUDE "netcfg_write.asm"
	INCLUDE "netenv.asm"
	INCLUDE "stage7_app.asm"

	ASSERT $ <= RUNTIME_BASE
