; NSLOOKUP.EXE - bounded DNS A/IN resolver over polling-only NETDRV.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE10_DNS

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"
	INCLUDE "dns_ntp.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	@S10APP.SAVE_COMMAND
	CALL	@S10APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	CALL	PARSE_ARGS
	JP	C,USAGE_FAIL
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JP	C,NETWORK_FAIL
	LD	HL,S9_TARGET_TEXT
	CALL	@DNSX.RESOLVE
	JR	NC,.RESOLVED
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	NETDRV_ERR_DNS_NXDOMAIN
	JP	Z,REMOTE_FAIL
	JP	NETWORK_FAIL
.RESOLVED
	LD	HL,MSG_NAME
	CALL	@CONSOLE.STRING
	LD	HL,S9_TARGET_TEXT
	CALL	@CONSOLE.LINE
	LD	HL,MSG_DNS
	CALL	@CONSOLE.STRING
	LD	HL,DNS_USED_SERVER
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_ADDRESS
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	JP	SUCCESS

; One required hostname and one optional dotted DNS server. All syntax is
; rejected before NETDRV/ISA access.
PARSE_ARGS
	XOR	A
	LD	(DNS_EXPLICIT_FLAG),A
	LD	HL,(CMDLINE_SOURCE)
	LD	A,(HL)
	INC	HL
	LD	(CLI_READER_PTR),HL
	LD	(CLI_READER_REMAIN),A
	CALL	NEXT_TOKEN
	JR	C,.PA_BAD
	LD	A,C
	CP	2
	JR	NZ,.PA_NAME
	LD	A,(HL)
	CP	'-'
	JR	Z,.PA_HELP_PREFIX
	CP	'/'
	JR	NZ,.PA_NAME
.PA_HELP_PREFIX
	INC	HL
	LD	A,(HL)
	AND	0xDF
	CP	'H'
	JR	Z,.PA_HELP
	CP	'?'
	JR	NZ,.PA_BAD
.PA_HELP
	CALL	NEXT_TOKEN
	JR	NC,.PA_BAD
	LD	A,EL3_CLI_HELP
	SCF
	RET
.PA_NAME
	LD	DE,S9_TARGET_TEXT
	CALL	COPY_TOKEN
	JR	C,.PA_BAD
	LD	HL,S9_TARGET_TEXT
	CALL	@DNS.VALIDATE_NAME
	JR	C,.PA_BAD
	CALL	NEXT_TOKEN
	JR	C,.PA_DONE
	LD	DE,S9_ENV_BUFFER
	CALL	COPY_TOKEN
	JR	C,.PA_BAD
	LD	HL,S9_ENV_BUFFER
	LD	DE,DNS_EXPLICIT_SERVER
	CALL	@S9APP.PARSE_IPV4
	JR	C,.PA_BAD
	LD	A,1
	LD	(DNS_EXPLICIT_FLAG),A
	CALL	NEXT_TOKEN
	JR	NC,.PA_BAD
.PA_DONE
	XOR	A
	RET
.PA_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET

; HL/B reader state, C=token length. Whitespace is ASCII space or tab.
NEXT_TOKEN
	LD	HL,(CLI_READER_PTR)
	LD	A,(CLI_READER_REMAIN)
	LD	B,A
.NT_SKIP
	LD	A,B
	OR	A
	JR	Z,.NT_NONE
	LD	A,(HL)
	CP	' '
	JR	Z,.NT_SKIP_ONE
	CP	9
	JR	NZ,.NT_START
.NT_SKIP_ONE
	INC	HL
	DEC	B
	JR	.NT_SKIP
.NT_START
	PUSH	HL
	LD	C,0
.NT_SCAN
	LD	A,B
	OR	A
	JR	Z,.NT_READY
	LD	A,(HL)
	CP	' '
	JR	Z,.NT_READY
	CP	9
	JR	Z,.NT_READY
	INC	HL
	INC	C
	DEC	B
	JR	.NT_SCAN
.NT_READY
	LD	(CLI_READER_PTR),HL
	LD	A,B
	LD	(CLI_READER_REMAIN),A
	POP	HL
	OR	A
	RET
.NT_NONE
	LD	(CLI_READER_PTR),HL
	XOR	A
	LD	(CLI_READER_REMAIN),A
	SCF
	RET

; HL token, C length, DE destination. Capacity is 255 including NUL.
COPY_TOKEN
	LD	A,C
	OR	A
	JR	Z,.CT_BAD
	CP	255
	JR	NC,.CT_BAD
	PUSH	BC
	LD	B,0
	LDIR
	XOR	A
	LD	(DE),A
	POP	BC
	RET
.CT_BAD
	SCF
	RET

PRINT_IP
	LD	B,4
.PI_NEXT
	LD	A,(HL)
	INC	HL
	PUSH	HL,BC
	CALL	@CONSOLE.DEC8
	POP	BC,HL
	DEC	B
	RET	Z
	LD	A,'.'
	CALL	@CONSOLE.CHAR
	JR	.PI_NEXT

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(S9_EXIT_CODE),A
	XOR	A
	CALL	@S9APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
USAGE_FAIL
	CP	EL3_CLI_HELP
	JR	NZ,.UF_ERROR
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
.UF_ERROR
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
REMOTE_FAIL
	LD	B,DSS_EXIT_REMOTE
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(S9_EXIT_CODE),A
	LD	A,C
	CALL	@S9APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(S9_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS
BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

MSG_BANNER	DB "3C509B NSLOOKUP v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: NSLOOKUP name [dns-server]",0
MSG_NAME	DB "Name: ",0
MSG_DNS		DB "DNS: ",0
MSG_ADDRESS	DB "Address: ",0
MSG_OK		DB "RESULT OK",0
MSG_FAIL	DB "RESULT FAIL code=",0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "icmp.asm"
	INCLUDE "udp.asm"
	INCLUDE "dns.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "udp_transport.asm"
	INCLUDE "stage10_app.asm"

	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP
