; NTP.EXE - polling-only SNTP clock client with quarter-hour time zones.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE10_DNS

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"
	INCLUDE "dns_ntp.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	@S10APP.SAVE_COMMAND
	CALL	@S10APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	CALL	PARSE_ARGS
	JP	C,USAGE_FAIL
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	LOAD_NTP_SETTINGS
	JP	C,CONFIG_FAIL
	CALL	VALIDATE_TARGET
	JP	C,USAGE_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JP	C,NETWORK_FAIL
	LD	HL,S9_TARGET_TEXT
	CALL	@DNSX.RESOLVE_OR_LITERAL
	JR	NC,.RESOLVED
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	NETDRV_ERR_DNS_NXDOMAIN
	JP	Z,REMOTE_FAIL
	JP	NETWORK_FAIL
.RESOLVED
	LD	HL,NET_TARGET_IP
	LD	BC,NTP_PORT
	LD	DE,0xC17B		; private source port, independent of DNS
	CALL	@UDPX.OPEN
	JP	C,NETWORK_FAIL
	CALL	BUILD_REQUEST
	JP	C,NETWORK_FAIL
	LD	A,3
	LD	(NTP_ATTEMPTS),A
.TRY
	LD	BC,NTP_PACKET_LENGTH
	CALL	@UDPX.SEND
	JP	C,NETWORK_FAIL
	LD	BC,5000
	CALL	@UDPX.WAIT
.REPLY
	JR	C,.WAIT_ERROR
	LD	(NTP_PARSE_DESC+NTPP_BUFFER),HL
	LD	(NTP_PARSE_DESC+NTPP_LENGTH),BC
	LD	HL,NTP_COOKIE
	LD	(NTP_PARSE_DESC+NTPP_COOKIE),HL
	LD	HL,NTP_SECONDS
	LD	(NTP_PARSE_DESC+NTPP_SECONDS),HL
	LD	HL,NTP_PARSE_DESC
	CALL	@NTP.PARSE_REPLY
	JR	NC,.HAVE_TIME
	CP	NETDRV_ERR_PARAMETER
	JR	NZ,.RETRY_PROTOCOL
	CALL	@UDPX.WAIT_CONTINUE
	JR	.REPLY
.WAIT_ERROR
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.RETRY_PROTOCOL
.RETRY_PROTOCOL
	LD	(NETDRV_FAIL_CODE),A
	LD	A,(NTP_ATTEMPTS)
	DEC	A
	LD	(NTP_ATTEMPTS),A
	JR	NZ,.TRY
	LD	A,(NETDRV_FAIL_CODE)
	JP	NETWORK_FAIL
.HAVE_TIME
	CALL	@NTP.TO_CALENDAR
	JP	C,NETWORK_FAIL
	CALL	@NTP.APPLY_TZ
	JP	C,NETWORK_FAIL
	; DSS must never be entered while the Sprinter ISA window is mapped.
	CALL	@NETDRV.DONE
	JP	C,HARDWARE_FAIL
	LD	A,(NTP_DAY)
	LD	D,A
	LD	A,(NTP_MONTH)
	LD	E,A
	LD	IX,(NTP_YEAR)
	LD	A,(NTP_HOUR)
	LD	H,A
	LD	A,(NTP_MINUTE)
	LD	L,A
	LD	A,(NTP_SECOND)
	LD	B,A
	LD	C,DSS_SETTIME
	RST	DSS
	JR	NC,.CLOCK_SET
	LD	A,NETDRV_ERR_CLOCK
	JP	LOCAL_FAIL
.CLOCK_SET
	CALL	PRINT_TIME
	JP	SUCCESS

; Zero or one server argument. Syntax is complete before NETDRV/ISA access.
PARSE_ARGS
	XOR	A
	LD	(NTP_TARGET_DEFAULT),A
	LD	(DNS_EXPLICIT_FLAG),A
	LD	HL,(CMDLINE_SOURCE)
	LD	A,(HL)
	INC	HL
	LD	(CLI_READER_PTR),HL
	LD	(CLI_READER_REMAIN),A
	CALL	NEXT_TOKEN
	JR	C,.PA_DEFAULT
	LD	A,C
	CP	2
	JR	NZ,.PA_SERVER
	LD	A,(HL)
	CP	'-'
	JR	Z,.PA_HELP_PREFIX
	CP	'/'
	JR	NZ,.PA_SERVER
.PA_HELP_PREFIX
	INC	HL
	LD	A,(HL)
	AND	0xDF
	CP	'H'
	JR	Z,.PA_HELP
	CP	'?'
	JR	NZ,.PA_BAD
.PA_HELP
	CALL	NEXT_TOKEN
	JR	NC,.PA_BAD
	LD	A,EL3_CLI_HELP
	SCF
	RET
.PA_SERVER
	LD	DE,S9_TARGET_TEXT
	CALL	COPY_TOKEN
	JR	C,.PA_BAD
	CALL	NEXT_TOKEN
	JR	NC,.PA_BAD
	XOR	A
	RET
.PA_DEFAULT
	LD	A,1
	LD	(NTP_TARGET_DEFAULT),A
	XOR	A
	RET
.PA_BAD
	LD	A,NETDRV_ERR_PARAMETER
	SCF
	RET

; NET_NTP is required only when no explicit server was supplied. NET_TZ is
; optional and empty means UTC. Both are read and validated before INIT_DRIVER.
LOAD_NTP_SETTINGS
	LD	A,(NTP_TARGET_DEFAULT)
	OR	A
	JR	Z,.LNS_TZ
	LD	HL,E_NTP
	CALL	GET_OPTIONAL
	RET	C
	LD	A,(S9_ENV_BUFFER)
	OR	A
	JR	Z,.LNS_BAD
	LD	HL,S9_ENV_BUFFER
	LD	DE,S9_TARGET_TEXT
	CALL	COPY_Z_255
	JR	C,.LNS_BAD
.LNS_TZ
	LD	HL,E_TZ
	CALL	GET_OPTIONAL
	RET	C
	LD	HL,S9_ENV_BUFFER
	CALL	@NETPARSE.PARSE_TZ
	JR	C,.LNS_BAD
	LD	(NTP_TZ_MINUTES),DE
	XOR	A
	RET
.LNS_BAD
	LD	A,NETDRV_ERR_CONFIG
	SCF
	RET

VALIDATE_TARGET
	LD	HL,S9_TARGET_TEXT
	LD	DE,DNS_RESULT_IP
	CALL	@S9APP.PARSE_IPV4
	RET	NC
	LD	HL,S9_TARGET_TEXT
	JP	@DNS.VALIDATE_NAME

GET_OPTIONAL
	LD	DE,S9_ENV_BUFFER
	LD	B,ENV_GET
	LD	C,DSS_ENVIRON
	RST	DSS
	RET	C
	OR	A
	RET	NZ
	LD	(S9_ENV_BUFFER),A
	RET

COPY_Z_255
	LD	B,0
.CZ_NEXT
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	OR	A
	RET	Z
	DJNZ	.CZ_NEXT
	SCF
	RET

BUILD_REQUEST
	CALL	MAKE_COOKIE
	LD	HL,STAGE9_TX_BUFFER+42
	LD	(NTP_BUILD_DESC+NTPB_BUFFER),HL
	LD	HL,UDP_MAX_PAYLOAD
	LD	(NTP_BUILD_DESC+NTPB_CAPACITY),HL
	LD	HL,NTP_COOKIE
	LD	(NTP_BUILD_DESC+NTPB_COOKIE),HL
	LD	HL,NTP_BUILD_DESC
	JP	@NTP.BUILD_REQUEST

MAKE_COOKIE
	LD	C,DSS_SYSTIME
	RST	DSS
	LD	D,H
	LD	E,L
	LD	HL,NTP_COOKIE
	LD	(HL),0x53
	INC	HL
	LD	(HL),0x31
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),B
	INC	HL
	LD	A,R
	LD	(HL),A
	INC	HL
	XOR	B
	LD	(HL),A
	INC	HL
	LD	(HL),0xA5
	RET

NEXT_TOKEN
	LD	HL,(CLI_READER_PTR)
	LD	A,(CLI_READER_REMAIN)
	LD	B,A
.NT_SKIP
	LD	A,B
	OR	A
	JR	Z,.NT_NONE
	LD	A,(HL)
	CP	' '
	JR	Z,.NT_SKIP_ONE
	CP	9
	JR	NZ,.NT_START
.NT_SKIP_ONE
	INC	HL
	DEC	B
	JR	.NT_SKIP
.NT_START
	PUSH	HL
	LD	C,0
.NT_SCAN
	LD	A,B
	OR	A
	JR	Z,.NT_READY
	LD	A,(HL)
	CP	' '
	JR	Z,.NT_READY
	CP	9
	JR	Z,.NT_READY
	INC	HL
	INC	C
	DEC	B
	JR	.NT_SCAN
.NT_READY
	LD	(CLI_READER_PTR),HL
	LD	A,B
	LD	(CLI_READER_REMAIN),A
	POP	HL
	OR	A
	RET
.NT_NONE
	LD	(CLI_READER_PTR),HL
	XOR	A
	LD	(CLI_READER_REMAIN),A
	SCF
	RET

COPY_TOKEN
	LD	A,C
	OR	A
	JR	Z,.CT_BAD
	CP	255
	JR	NC,.CT_BAD
	PUSH	BC
	LD	B,0
	LDIR
	XOR	A
	LD	(DE),A
	POP	BC
	RET
.CT_BAD
	SCF
	RET

PRINT_TIME
	LD	HL,MSG_TIME
	CALL	@CONSOLE.STRING
	LD	HL,(NTP_YEAR)
	CALL	@CONSOLE.DEC16
	LD	A,'-'
	CALL	@CONSOLE.CHAR
	LD	A,(NTP_MONTH)
	CALL	PRINT_2
	LD	A,'-'
	CALL	@CONSOLE.CHAR
	LD	A,(NTP_DAY)
	CALL	PRINT_2
	LD	A,' '
	CALL	@CONSOLE.CHAR
	LD	A,(NTP_HOUR)
	CALL	PRINT_2
	LD	A,':'
	CALL	@CONSOLE.CHAR
	LD	A,(NTP_MINUTE)
	CALL	PRINT_2
	LD	A,':'
	CALL	@CONSOLE.CHAR
	LD	A,(NTP_SECOND)
	CALL	PRINT_2
	LD	A,' '
	CALL	@CONSOLE.CHAR
	LD	A,'U'
	CALL	@CONSOLE.CHAR
	LD	A,'T'
	CALL	@CONSOLE.CHAR
	LD	A,'C'
	CALL	@CONSOLE.CHAR
	LD	HL,(NTP_TZ_MINUTES)
	BIT	7,H
	JR	Z,.PT_POSITIVE
	LD	A,'-'
	CALL	@CONSOLE.CHAR
	LD	DE,0
	EX	DE,HL
	OR	A
	SBC	HL,DE
	JR	.PT_MAGNITUDE
.PT_POSITIVE
	LD	A,'+'
	CALL	@CONSOLE.CHAR
.PT_MAGNITUDE
	LD	B,0
	LD	DE,60
.PT_DIV60
	OR	A
	SBC	HL,DE
	JR	C,.PT_DIV_DONE
	INC	B
	JR	.PT_DIV60
.PT_DIV_DONE
	ADD	HL,DE
	LD	A,B
	CALL	PRINT_2
	LD	A,':'
	CALL	@CONSOLE.CHAR
	LD	A,L
	CALL	PRINT_2
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_2
	CP	10
	JR	NC,.P2_VALUE
	PUSH	AF
	LD	A,'0'
	CALL	@CONSOLE.CHAR
	POP	AF
.P2_VALUE
	JP	@CONSOLE.DEC8

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(S9_EXIT_CODE),A
	XOR	A
	CALL	@S9APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
USAGE_FAIL
	CP	EL3_CLI_HELP
	JR	NZ,.UF_ERROR
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
.UF_ERROR
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
REMOTE_FAIL
	LD	B,DSS_EXIT_REMOTE
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(S9_EXIT_CODE),A
	LD	A,C
	CALL	@S9APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(S9_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS
BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

E_NTP		DB "NET_NTP",0
E_TZ		DB "NET_TZ",0
MSG_BANNER	DB "3C509B NTP v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: NTP [server]",0
MSG_TIME	DB "Local time: ",0
MSG_OK		DB "RESULT OK",0
MSG_FAIL	DB "RESULT FAIL code=",0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "icmp.asm"
	INCLUDE "udp.asm"
	INCLUDE "dns.asm"
	INCLUDE "../lib/ntp.asm"
	INCLUDE "netparse.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "udp_transport.asm"
	INCLUDE "stage10_app.asm"

	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP
