; PING.EXE / PINGALT.EXE - polling-only IPv4 ICMP diagnostics.
; Define PING_ALT_BUILD before including this file for the independent
; one-frame-per-poll PINGALT loop.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
; DSS_SCANKEY reports Ctrl+letter as a positional scancode with bit 7 set
; (the C key is 0xAC) and the Ctrl modifier in B.  It does not return the
; ready-made ASCII control byte used by the old host harness.
SCAN_C		EQU 0xAC
; PING is larger than the earlier diagnostics. Move only its resident state
; above the loaded image while retaining ample stack below C000h.
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE10_DNS

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"
	INCLUDE "dns_ntp.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	@S10APP.SAVE_COMMAND
	CALL	@S10APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	CALL	CLEAR_STATE
	CALL	@CMDLINE.PARSE_PING
	JR	NC,.ARGS_OK
	CP	EL3_CLI_HELP
	JP	NZ,USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.STRING		; MSG_HELP already ends in one CRLF
	JP	SUCCESS
.ARGS_OK
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JP	C,NETWORK_FAIL
	XOR	A
	LD	(DNS_EXPLICIT_FLAG),A
	LD	HL,PING_TARGET_TEXT
	CALL	@DNSX.RESOLVE_OR_LITERAL
	JR	NC,.NAME_OK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.NAME_OK
	CALL	PRINT_HEADER
	CALL	RESOLVE_TARGET
	JR	NC,.RESOLVED
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.RESOLVED
	CALL	PRINT_NEXT_HOP
	CALL	PING_LOOP
	PUSH	AF			; the statistics block closes every run
	CALL	PRINT_STATISTICS
	POP	AF
	JP	NC,SUCCESS
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	NETDRV_ERR_UNREACHABLE
	JP	Z,REMOTE_FAIL
	JP	NETWORK_FAIL

CLEAR_STATE
	XOR	A
	LD	(PING_RECEIVED),A
	LD	(PING_RECEIVED+1),A
	LD	(PING_SENT),A
	LD	(PING_SENT+1),A
	LD	(PING_UNREACHABLE),A
	LD	HL,0x509B
	LD	(PING_IDENTIFIER),HL
	LD	HL,0
	LD	(PING_SEQUENCE),HL
	LD	HL,1
	LD	(PING_IP_ID),HL
	RET

; Resolve the direct peer or configured gateway with three bounded requests.
RESOLVE_TARGET
	LD	HL,NET_TARGET_IP
	CALL	@ARP.SELECT_NEXT_HOP
	RET	C
	OR	A
	RET	NZ			; IPv4 broadcast already has FF MAC
	CALL	@S9APP.SECONDS
	LD	C,A
	LD	B,0
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.CACHE_LOOKUP
	RET	NC
	LD	A,ARP_ATTEMPTS_MAX
	LD	(ARP_RETRY_LEFT),A
.TRY
	LD	DE,STAGE8_TX_BUFFER
	LD	HL,NET_NEXT_HOP_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,STAGE8_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
	CALL	WAIT_ARP
	JR	NC,.CACHE
	CP	NETDRV_ERR_CANCELLED
	RET	Z
	LD	A,(ARP_RETRY_LEFT)
	DEC	A
	LD	(ARP_RETRY_LEFT),A
	JR	NZ,.TRY
	CALL	PRINT_ARP_TIMEOUT
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.CACHE
	CALL	@S9APP.SECONDS
	LD	C,A
	LD	B,0
	LD	HL,NET_NEXT_HOP_IP
	LD	DE,NET_RESULT_MAC
	CALL	@ARP.CACHE_INSERT
	XOR	A
	RET

; Same shared schedule as tcp_transport.asm RESOLVE_ROUTE: the opening attempts
; ask again quickly instead of waiting out the documented deadline, which is
; what put a pause in front of the first reply. See netdrv.inc.
WAIT_ARP
	LD	A,(ARP_RETRY_LEFT)
	CP	ARP_FAST_LEFT
	LD	BC,ARP_FIRST_MS
	JR	NC,.ARM
	LD	BC,ARP_RETRY_MS
.ARM
	CALL	@NETTIME.START
	RET	C
.ARP_POLL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.ARP_TICK
	LD	HL,STAGE8_RX_BUFFER
	LD	BC,STAGE8_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	NC,.ARP_FRAME
	CP	EL3_ERR_RX_ERROR
	JR	Z,.ARP_TICK
	CP	EL3_ERR_FRAME_SIZE
	JR	Z,.ARP_TICK
	CP	EL3_ERR_NO_FRAME
	JR	Z,.ARP_TICK
	RET				; preserve a real NETDRV/ISA failure
.ARP_FRAME
	LD	(PING_RX_LENGTH),BC
	LD	HL,STAGE8_RX_BUFFER
	CALL	@ARP.PARSE
	JR	C,.ARP_TICK
	CP	1
	JR	Z,.ARP_FOUND
	CP	2
	JR	NZ,.ARP_TICK
	LD	DE,STAGE8_TX_BUFFER
	LD	HL,STAGE8_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE8_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
.ARP_TICK
	CALL	CHECK_CANCEL
	JR	C,.ARP_CANCEL
	CALL	@NETTIME.TICK
	JR	NC,.ARP_POLL
	RET
.ARP_FOUND
	XOR	A
	RET
.ARP_CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

PING_LOOP
.REQUEST
	CALL	SEND_REQUEST
	RET	C
	LD	HL,(PING_SENT)
	INC	HL
	LD	(PING_SENT),HL
	CALL	WAIT_RESPONSE
	JR	C,.NO_REPLY
	LD	HL,(PING_RECEIVED)
	INC	HL
	LD	(PING_RECEIVED),HL
	CALL	PRINT_REPLY
	JR	.ADVANCE
.NO_REPLY
	LD	(PING_PRIMARY_ERROR),A
	CP	NETDRV_ERR_CANCELLED
	JR	NZ,.NOT_CANCELLED
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET
.NOT_CANCELLED
	CP	NETDRV_ERR_UNREACHABLE
	JR	NZ,.TIMEOUT
	LD	A,1
	LD	(PING_UNREACHABLE),A
	CALL	PRINT_UNREACHABLE
	JR	.ADVANCE
.TIMEOUT
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.OTHER_ERROR
	CALL	PRINT_ICMP_TIMEOUT
.ADVANCE
	LD	HL,(PING_SEQUENCE)
	INC	HL			; modulo 65536
	LD	(PING_SEQUENCE),HL
	LD	HL,(PING_IP_ID)
	INC	HL			; modulo 65536
	LD	(PING_IP_ID),HL
.FINISH_CHECK
	LD	A,(PING_FLAGS)
	AND	PING_FLAG_INFINITE
	JR	NZ,.MORE
	LD	HL,(PING_SENT)
	LD	DE,(PING_COUNT)
	OR	A
	SBC	HL,DE
	JR	NC,.DONE
.MORE
	CALL	WAIT_INTERVAL
	RET	C
	JR	.REQUEST
.OTHER_ERROR
	LD	A,(PING_PRIMARY_ERROR)
	SCF
	RET
.DONE
	LD	HL,(PING_RECEIVED)
	LD	A,H
	OR	L
	JR	NZ,.OK
	LD	A,(PING_UNREACHABLE)
	OR	A
	JR	Z,.ALL_TIMEOUT
	LD	A,NETDRV_ERR_UNREACHABLE
	SCF
	RET
.ALL_TIMEOUT
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.OK
	XOR	A
	RET

SEND_REQUEST
	CALL	BUILD_ETH_HEADER
	LD	HL,STAGE8_TX_BUFFER+34
	LD	(ICMP_BUILD_DESC+ICMPB_BUFFER),HL
	LD	HL,STAGE8_TX_CAPACITY-34
	LD	(ICMP_BUILD_DESC+ICMPB_CAPACITY),HL
	LD	HL,(PING_SIZE)
	LD	(ICMP_BUILD_DESC+ICMPB_PAYLOAD_LENGTH),HL
	LD	HL,(PING_IDENTIFIER)
	LD	(ICMP_BUILD_DESC+ICMPB_IDENTIFIER),HL
	LD	HL,(PING_SEQUENCE)
	LD	(ICMP_BUILD_DESC+ICMPB_SEQUENCE),HL
	LD	A,8
	LD	(ICMP_BUILD_DESC+ICMPB_TYPE),A
	LD	HL,ICMP_BUILD_DESC
	CALL	@ICMP.BUILD_ECHO
	RET	C
	LD	(IPV4_BUILD_DESC+IP4B_DATA_LENGTH),BC
	LD	HL,STAGE8_TX_BUFFER+14
	LD	(IPV4_BUILD_DESC+IP4B_BUFFER),HL
	LD	HL,STAGE8_TX_CAPACITY-14
	LD	(IPV4_BUILD_DESC+IP4B_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(IPV4_BUILD_DESC+IP4B_SOURCE),HL
	LD	HL,NET_TARGET_IP
	LD	(IPV4_BUILD_DESC+IP4B_DESTINATION),HL
	LD	HL,(PING_IP_ID)
	LD	(IPV4_BUILD_DESC+IP4B_IDENTIFIER),HL
	LD	A,(PING_TTL)
	LD	(IPV4_BUILD_DESC+IP4B_TTL),A
	LD	A,IPV4_PROTOCOL_ICMP
	LD	(IPV4_BUILD_DESC+IP4B_PROTOCOL),A
	LD	HL,IPV4_BUILD_DESC
	CALL	@IPV4.BUILD
	RET	C
	LD	HL,14
	ADD	HL,BC
	LD	B,H
	LD	C,L
	LD	HL,STAGE8_TX_BUFFER
	JP	@NETDRV.SEND_FRAME

BUILD_ETH_HEADER
	LD	HL,NET_RESULT_MAC
	LD	DE,STAGE8_TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	RET

; Main PING drains at most four complete frames per poll. PINGALT is assembled
; without this dispatcher and reads at most one frame before advancing time.
WAIT_RESPONSE
	LD	BC,(PING_TIMEOUT_MS)
	CALL	@NETTIME.START
	RET	C
.POLL
	CALL	CHECK_CANCEL
	JR	C,.CANCEL
	IFNDEF PING_ALT_BUILD
	LD	A,4
	LD	(PING_DRAIN_LEFT),A
.DRAIN
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.TICK
	CALL	READ_AND_PROCESS
	RET	C
	CP	1
	JR	Z,.REPLY
	LD	A,(PING_DRAIN_LEFT)
	DEC	A
	LD	(PING_DRAIN_LEFT),A
	JR	NZ,.DRAIN
	ELSE
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.TICK
	CALL	READ_AND_PROCESS
	RET	C
	CP	1
	JR	Z,.REPLY
	ENDIF
.TICK
	CALL	@NETTIME.TICK
	JR	NC,.POLL
	RET
.REPLY
	XOR	A
	RET
.CANCEL
	LD	A,NETDRV_ERR_CANCELLED
	SCF
	RET

READ_AND_PROCESS
	LD	HL,STAGE8_RX_BUFFER
	LD	BC,STAGE8_RX_CAPACITY
	CALL	@NETDRV.READ_FRAME
	JR	NC,.READ_OK
	; A bad RX status, runt/oversize entry, or an empty race is consumed and
	; ignored. ISA/FIFO/discard failures remain explicit operational errors.
	CP	EL3_ERR_RX_ERROR
	JR	Z,.READ_IGNORED
	CP	EL3_ERR_FRAME_SIZE
	JR	Z,.READ_IGNORED
	CP	EL3_ERR_NO_FRAME
	JR	Z,.READ_IGNORED
	RET
.READ_OK
	LD	(PING_RX_LENGTH),BC
	JP	PROCESS_FRAME
.READ_IGNORED
	XOR	A
	RET

; Out A=0 ignored/answered, A=1 matched reply; matching unreachable returns
; NETDRV_ERR_UNREACHABLE/CF=1. Malformed and foreign frames are ignored.
PROCESS_FRAME
	LD	HL,(PING_RX_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	JP	C,.IGNORED
	LD	A,(STAGE8_RX_BUFFER+12)
	CP	0x08
	JP	NZ,.IGNORED
	LD	A,(STAGE8_RX_BUFFER+13)
	CP	0x06
	JP	Z,.ARP_FRAME
	OR	A
	JP	NZ,.IGNORED
	LD	HL,STAGE8_RX_BUFFER+14
	LD	(IPV4_PARSE_DESC+IP4P_BUFFER),HL
	LD	HL,(PING_RX_LENGTH)
	LD	DE,14
	OR	A
	SBC	HL,DE
	LD	(IPV4_PARSE_DESC+IP4P_LENGTH),HL
	LD	HL,0
	LD	(IPV4_PARSE_DESC+IP4P_EXPECT_SOURCE),HL
	LD	HL,NET_LOCAL_IP
	LD	(IPV4_PARSE_DESC+IP4P_EXPECT_DESTINATION),HL
	LD	A,IPV4_PROTOCOL_ICMP
	LD	(IPV4_PARSE_DESC+IP4P_EXPECT_PROTOCOL),A
	LD	HL,IPV4_PARSE_DESC
	CALL	@IPV4.PARSE
	JP	C,.IGNORED
	LD	HL,(IPV4_PARSE_DESC+IP4P_DATA)
	LD	A,(HL)
	CP	0
	JR	Z,.ECHO_REPLY
	CP	3
	JR	Z,.UNREACHABLE
	CP	8
	JR	Z,.ECHO_REQUEST
	JP	.IGNORED
.ECHO_REPLY
	LD	HL,(IPV4_PARSE_DESC+IP4P_SOURCE)
	LD	DE,NET_TARGET_IP
	CALL	CMP4
	JR	NZ,.IGNORED
	CALL	PREPARE_REPLY_DESC
	LD	HL,(IPV4_PARSE_DESC+IP4P_DATA)
	LD	BC,(IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	DE,ICMP_REPLY_DESC
	CALL	@ICMP.PARSE_ECHO_REPLY
	JR	C,.IGNORED
	LD	A,1
	OR	A
	RET
.UNREACHABLE
	CALL	PREPARE_REPLY_DESC
	LD	HL,(IPV4_PARSE_DESC+IP4P_DATA)
	LD	BC,(IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	DE,ICMP_REPLY_DESC
	CALL	@ICMP.PARSE_UNREACHABLE
	JR	C,.IGNORED
	LD	A,NETDRV_ERR_UNREACHABLE
	SCF
	RET
.ECHO_REQUEST
	CALL	ANSWER_ECHO_REQUEST
	JR	NC,.IGNORED
	CP	NETDRV_ERR_PARAMETER	; malformed request/checksum is nonfatal noise
	JR	Z,.IGNORED
	RET				; preserve a real transmit/driver failure
.ARP_FRAME
	LD	HL,STAGE8_RX_BUFFER
	LD	BC,(PING_RX_LENGTH)
	CALL	@ARP.PARSE
	JR	C,.IGNORED
	CP	2
	JR	NZ,.IGNORED
	LD	DE,STAGE8_TX_BUFFER
	LD	HL,STAGE8_RX_BUFFER
	CALL	@ARP.BUILD_REPLY
	LD	HL,STAGE8_TX_BUFFER
	CALL	@NETDRV.SEND_FRAME
	RET	C
.IGNORED
	XOR	A
	RET

PREPARE_REPLY_DESC
	LD	HL,(PING_IDENTIFIER)
	LD	(ICMP_REPLY_DESC+ICMPR_IDENTIFIER),HL
	LD	HL,(PING_SEQUENCE)
	LD	(ICMP_REPLY_DESC+ICMPR_SEQUENCE),HL
	LD	HL,(PING_SIZE)
	LD	(ICMP_REPLY_DESC+ICMPR_PAYLOAD_LENGTH),HL
	LD	HL,NET_LOCAL_IP
	LD	(ICMP_REPLY_DESC+ICMPR_EXPECT_SOURCE),HL
	LD	HL,NET_TARGET_IP
	LD	(ICMP_REPLY_DESC+ICMPR_EXPECT_DESTINATION),HL
	RET

ANSWER_ECHO_REQUEST
	LD	HL,(IPV4_PARSE_DESC+IP4P_SOURCE)
	LD	DE,PING_INCOMING_IP
	LD	BC,4
	LDIR
	LD	HL,STAGE8_RX_BUFFER+6
	LD	DE,STAGE8_TX_BUFFER
	LD	BC,6
	LDIR
	LD	HL,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	A,0x08
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	LD	HL,(IPV4_PARSE_DESC+IP4P_DATA)
	LD	(ICMP_COPY_DESC+ICMPC_SOURCE),HL
	LD	HL,(IPV4_PARSE_DESC+IP4P_DATA_LENGTH)
	LD	(ICMP_COPY_DESC+ICMPC_LENGTH),HL
	LD	HL,STAGE8_TX_BUFFER+34
	LD	(ICMP_COPY_DESC+ICMPC_DESTINATION),HL
	LD	HL,STAGE8_TX_CAPACITY-34
	LD	(ICMP_COPY_DESC+ICMPC_CAPACITY),HL
	LD	HL,ICMP_COPY_DESC
	CALL	@ICMP.BUILD_ECHO_REPLY
	RET	C
	LD	(IPV4_BUILD_DESC+IP4B_DATA_LENGTH),BC
	LD	HL,STAGE8_TX_BUFFER+14
	LD	(IPV4_BUILD_DESC+IP4B_BUFFER),HL
	LD	HL,STAGE8_TX_CAPACITY-14
	LD	(IPV4_BUILD_DESC+IP4B_CAPACITY),HL
	LD	HL,NET_LOCAL_IP
	LD	(IPV4_BUILD_DESC+IP4B_SOURCE),HL
	LD	HL,PING_INCOMING_IP
	LD	(IPV4_BUILD_DESC+IP4B_DESTINATION),HL
	LD	HL,(PING_IP_ID)
	INC	HL
	LD	(PING_IP_ID),HL
	LD	(IPV4_BUILD_DESC+IP4B_IDENTIFIER),HL
	LD	A,64
	LD	(IPV4_BUILD_DESC+IP4B_TTL),A
	LD	A,IPV4_PROTOCOL_ICMP
	LD	(IPV4_BUILD_DESC+IP4B_PROTOCOL),A
	LD	HL,IPV4_BUILD_DESC
	CALL	@IPV4.BUILD
	RET	C
	LD	HL,14
	ADD	HL,BC
	LD	B,H
	LD	C,L
	LD	HL,STAGE8_TX_BUFFER
	JP	@NETDRV.SEND_FRAME

; One-second gap. Frames are consumed once and service traffic is answered,
; but replies outside the request deadline do not affect success counters.
WAIT_INTERVAL
	LD	BC,1000
	CALL	@NETTIME.START
	RET	C
.INTERVAL_LOOP
	CALL	CHECK_CANCEL
	JR	C,.INTERVAL_CANCEL
	CALL	@NETDRV.RX_PENDING
	RET	C
	OR	A
	JR	Z,.INTERVAL_TICK
	CALL	READ_AND_PROCESS
	JR	NC,.INTERVAL_TICK
	CP	NETDRV_ERR_UNREACHABLE
	JR	NZ,.INTERVAL_ERROR
	; A response outside the request deadline is stale even if its tuple matches
	; the next sequence value. Consume it, but never change this run's result.
.INTERVAL_TICK
	CALL	@NETTIME.TICK
	JR	NC,.INTERVAL_LOOP
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.INTERVAL_ERROR
	XOR	A
	RET
.INTERVAL_CANCEL
	LD	A,NETDRV_ERR_CANCELLED
.INTERVAL_ERROR
	SCF
	RET

CHECK_CANCEL
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.NO_CANCEL
	LD	A,E
	CP	0x1B
	JR	Z,.YES_CANCEL
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.NO_CANCEL
	LD	A,D
	CP	SCAN_C
	JR	Z,.YES_CANCEL
.NO_CANCEL
	XOR	A
	RET
.YES_CANCEL
	SCF
	RET

CMP4
	LD	B,4
.CMP_LOOP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.CMP_LOOP
	RET

; "Pinging <target> with <n> bytes of data:" and the local address, printed
; once the target is known and before the next hop is resolved.
PRINT_HEADER
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_PINGING
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IP
	LD	HL,MSG_WITH
	CALL	@CONSOLE.STRING
	LD	HL,(PING_SIZE)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_BYTES_DATA
	CALL	@CONSOLE.LINE
	LD	HL,MSG_OUR_IP
	CALL	@CONSOLE.STRING
	LD	HL,NET_LOCAL_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

; NET_RESULT_MAC is the address every request is actually addressed to, so
; printing it separates a routing mistake from an unanswered echo.
PRINT_NEXT_HOP
	LD	HL,MSG_NEXT_HOP
	CALL	@CONSOLE.STRING
	LD	HL,NET_RESULT_MAC
	CALL	@CONSOLE.MAC
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

; The reply line keeps the column order of the sibling kits:
; "Reply from A.B.C.D: bytes=N time=Nms TTL=N". The time is the elapsed
; millisecond count of the poll loop, so it is an approximation that errs
; high under broadcast traffic rather than hiding a slow reply; TTL is the
; one carried by the reply, not the requested -i value.
PRINT_REPLY
	LD	HL,MSG_REPLY
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IP
	LD	HL,MSG_BYTES
	CALL	@CONSOLE.STRING
	LD	HL,(PING_SIZE)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_TIME
	CALL	@CONSOLE.STRING
	LD	HL,(NETTIME_ELAPSED_MS)
	LD	A,H
	OR	L
	JR	NZ,.TIME_EXACT
	LD	A,'<'			; the reply beat the first quantum
	CALL	@CONSOLE.CHAR
	INC	HL			; HL=1 -> "time<1ms"
	JR	.TIME_VALUE
.TIME_EXACT
	LD	A,'='
	CALL	@CONSOLE.CHAR
.TIME_VALUE
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_MS_TTL
	CALL	@CONSOLE.STRING
	LD	A,(IPV4_PARSE_DESC+IP4P_TTL)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

; Sent/received/lost for the whole run, printed for success, timeout and
; cancellation alike so an interrupted -t run still reports its totals.
PRINT_STATISTICS
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_STATS
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IP
	LD	HL,MSG_COLON
	CALL	@CONSOLE.LINE
	LD	HL,MSG_PACKETS
	CALL	@CONSOLE.STRING
	LD	HL,(PING_SENT)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_RECEIVED
	CALL	@CONSOLE.STRING
	LD	HL,(PING_RECEIVED)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_LOST
	CALL	@CONSOLE.STRING
	LD	HL,(PING_SENT)
	LD	DE,(PING_RECEIVED)
	OR	A
	SBC	HL,DE
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_PERIOD
	JP	@CONSOLE.LINE

PRINT_ARP_TIMEOUT
	LD	HL,MSG_ARP_TIMEOUT
	CALL	@CONSOLE.STRING
	JP	PRINT_DIAG_TAIL

PRINT_ICMP_TIMEOUT
	LD	HL,MSG_ICMP_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	HL,(NETTIME_ELAPSED_MS)
	CALL	@CONSOLE.DEC16
	JP	PRINT_DIAG_TAIL

PRINT_UNREACHABLE
	LD	HL,MSG_UNREACHABLE
	CALL	@CONSOLE.STRING
	JP	PRINT_DIAG_TAIL

PRINT_DIAG_TAIL
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_STATUS)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_TARGET
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IP
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

PRINT_IP
	LD	DE,ENV_SET_BUFFER
	CALL	@NETENV.FORMAT_IPV4
	LD	HL,ENV_SET_BUFFER
	JP	@CONSOLE.STRING

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(PING_EXIT_CODE),A
	XOR	A
	CALL	@S9APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_RESULT_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.STRING		; MSG_HELP already ends in one CRLF
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
REMOTE_FAIL
	LD	B,DSS_EXIT_REMOTE
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(PING_EXIT_CODE),A
	LD	A,C
	CALL	@S9APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(PING_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_RESULT_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

	IFDEF PING_ALT_BUILD
MSG_BANNER	DB "3C509B PINGALT v",PACKAGE_VERSION,0
MSG_HELP
	DB "Usage:",13,10
	DB "  PINGALT [-t] [-n count] [-l size] [-i TTL] [-w ms] target",13,10
	DB "  PINGALT /?",13,10,13,10
	DB "  -t        ping until interrupted (Esc/Ctrl+C).",13,10
	DB "  -n count  number of echo requests (default 4, max 65535).",13,10
	DB "  -l size   payload size in bytes (default 32, max 1472).",13,10
	DB "  -i TTL    IP TTL on outgoing requests (default 64).",13,10
	DB "  -w ms     per-reply wait timeout (default 1000 ms).",13,10
	DB "  target    destination IPv4 or hostname (e.g. 192.168.7.1).",13,10,0
	ELSE
MSG_BANNER	DB "3C509B PING v",PACKAGE_VERSION,0
MSG_HELP
	DB "Usage:",13,10
	DB "  PING [-t] [-n count] [-l size] [-i TTL] [-w ms] target",13,10
	DB "  PING /?",13,10,13,10
	DB "  -t        ping until interrupted (Esc/Ctrl+C).",13,10
	DB "  -n count  number of echo requests (default 4, max 65535).",13,10
	DB "  -l size   payload size in bytes (default 32, max 1472).",13,10
	DB "  -i TTL    IP TTL on outgoing requests (default 64).",13,10
	DB "  -w ms     per-reply wait timeout (default 1000 ms).",13,10
	DB "  target    destination IPv4 or hostname (e.g. 192.168.7.1).",13,10,0
	ENDIF
MSG_PINGING	DB "Pinging ",0
MSG_WITH	DB " with ",0
MSG_BYTES_DATA	DB " bytes of data:",0
MSG_OUR_IP	DB "Our IP=",0
MSG_NEXT_HOP	DB "Next-hop MAC=",0
MSG_REPLY	DB "Reply from ",0
MSG_BYTES	DB ": bytes=",0
MSG_TIME	DB " time",0
MSG_MS_TTL	DB "ms TTL=",0
MSG_STATS	DB "Ping statistics for ",0
MSG_COLON	DB ":",0
MSG_PACKETS	DB "    Packets: Sent = ",0
MSG_RECEIVED	DB ", Received = ",0
MSG_LOST	DB ", Lost = ",0
MSG_PERIOD	DB ".",0
MSG_ARP_TIMEOUT DB "[E1] TIMEOUT stage=ARP elapsed_ms=2000",0
MSG_ICMP_TIMEOUT DB "[E2] TIMEOUT stage=ICMP elapsed_ms=",0
MSG_UNREACHABLE DB "[E3] UNREACHABLE code=24",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=#",0
MSG_TARGET	DB " target=",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL DB "RESULT FAIL code=",0

	ENDMODULE

	ASSERT $ < 0xC000

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "icmp.asm"
	INCLUDE "udp.asm"
	INCLUDE "dns.asm"
	INCLUDE "netenv.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "cmdline_lib.asm"
	INCLUDE "udp_transport.asm"
	INCLUDE "stage10_app.asm"

	; The complete linked image, not only MAIN, must stay below resident state.
	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP
