; TCPTEST.EXE - bounded two-channel TCP echo diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE11_LAYOUT

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "tcp.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	@S11APP.SAVE_COMMAND
	CALL	@S11APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	CALL	@S9CLI.PARSE_UDP
	JR	NC,.ARGS_OK
	CP	EL3_CLI_HELP
	JP	NZ,USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
.ARGS_OK
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	A,TCP_STAGE_LINK
	LD	(S11_DIAG_STAGE),A
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JP	C,NETWORK_FAIL
	CALL	@TCPX.RESET
	LD	HL,0
	LD	(S9_TFTP_BLOCK),HL
.CYCLE
	CALL	RUN_CYCLE
	JR	NC,.CYCLE_OK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	TCP_ERR_RESET
	JP	NZ,NETWORK_FAIL
	CALL	@TCPX.RESET		; prove a fresh tuple works after a remote reset
	CALL	RUN_CYCLE
	JR	NC,.CYCLE_OK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.CYCLE_OK
	LD	HL,(S9_TFTP_BLOCK)
	INC	HL
	LD	(S9_TFTP_BLOCK),HL
	LD	DE,(S9_COUNT)
	OR	A
	SBC	HL,DE
	JR	C,.CYCLE
	JP	SUCCESS

RUN_CYCLE
	LD	A,0
	LD	HL,NET_TARGET_IP
	LD	BC,(S9_REMOTE_PORT)
	CALL	@TCPX.OPEN
	RET	C
	LD	A,1
	LD	HL,NET_TARGET_IP
	LD	BC,(S9_REMOTE_PORT)
	CALL	@TCPX.OPEN
	JR	C,.ABORT0
	XOR	A
	CALL	SEND_CHANNEL
	JR	C,.ABORT_BOTH
	LD	A,1
	CALL	SEND_CHANNEL
	JR	C,.ABORT_BOTH
	XOR	A
	CALL	RECEIVE_CHANNEL
	JR	C,.ABORT_BOTH
	LD	A,1
	CALL	RECEIVE_CHANNEL
	JR	C,.ABORT_BOTH
	XOR	A
	CALL	@TCPX.CLOSE
	JR	C,.ABORT1
	LD	A,1
	CALL	@TCPX.CLOSE
	RET
.ABORT_BOTH
	PUSH	AF
	XOR	A
	CALL	@TCPX.ABORT
	LD	A,1
	CALL	@TCPX.ABORT
	POP	AF
	SCF
	RET
.ABORT1
	PUSH	AF
	LD	A,1
	CALL	@TCPX.ABORT
	POP	AF
	SCF
	RET
.ABORT0
	PUSH	AF
	XOR	A
	CALL	@TCPX.ABORT
	POP	AF
	SCF
	RET

SEND_CHANNEL
	LD	(S11_CHANNEL),A
	CALL	FILL_PATTERN
	LD	A,(S11_CHANNEL)
	LD	HL,S11_APP_BUFFER
	LD	BC,(S9_SIZE)
	CALL	@TCPX.SEND
	RET	C
	LD	HL,(S9_SIZE)
	OR	A
	SBC	HL,DE
	JR	NZ,.SHORT
	XOR	A
	RET
.SHORT
	LD	A,NETDRV_ERR_PROTOCOL
	SCF
	RET

FILL_PATTERN
	LD	HL,S11_APP_BUFFER
	LD	BC,(S9_SIZE)
	LD	E,0
	LD	A,(S11_CHANNEL)
	OR	A
	LD	D,0x31
	JR	Z,.FILL
	LD	D,0xA7
.FILL
	LD	A,B
	OR	C
	RET	Z
	LD	A,E
	XOR	D
	LD	(HL),A
	INC	HL
	INC	E
	DEC	BC
	JR	.FILL

RECEIVE_CHANNEL
	LD	(S11_CHANNEL),A
	LD	HL,0
	LD	(S9_SEQUENCE),HL
	LD	HL,(S9_SIZE)
	LD	A,H
	OR	L
	JR	Z,.RECV_DONE
.RECV_NEXT
	LD	A,(S11_CHANNEL)
	LD	HL,S11_APP_BUFFER
	LD	BC,TCP_MSS
	LD	DE,(S9_TIMEOUT_MS)
	CALL	@TCPX.RECV
	RET	C
	PUSH	BC
	CALL	VERIFY_PATTERN
	POP	BC
	JR	C,.BAD_DATA
	LD	HL,(S9_SEQUENCE)
	ADD	HL,BC
	LD	(S9_SEQUENCE),HL
	LD	DE,(S9_SIZE)
	OR	A
	SBC	HL,DE
	JR	C,.RECV_NEXT
	JR	NZ,.BAD_DATA
.RECV_DONE
	LD	HL,MSG_CHANNEL
	CALL	@CONSOLE.STRING
	LD	A,(S11_CHANNEL)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BYTES
	CALL	@CONSOLE.STRING
	LD	HL,(S9_SIZE)
	CALL	@CONSOLE.DEC16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	XOR	A
	RET
.BAD_DATA
	LD	A,NETDRV_ERR_PROTOCOL
	SCF
	RET

VERIFY_PATTERN
	LD	HL,S11_APP_BUFFER
	LD	DE,(S9_SEQUENCE)
	LD	A,(S11_CHANNEL)
	OR	A
	LD	A,0x31
	JR	Z,.MASK_READY
	LD	A,0xA7
.MASK_READY
	LD	(S9_FLAGS),A
.VERIFY
	LD	A,B
	OR	C
	JR	Z,.OK
	LD	A,E
	PUSH	DE
	LD	D,A
	LD	A,(S9_FLAGS)
	XOR	D
	POP	DE
	CP	(HL)
	JR	NZ,.BAD
	INC	HL
	INC	DE
	DEC	BC
	JR	.VERIFY
.OK
	XOR	A
	RET
.BAD
	SCF
	RET

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(S9_EXIT_CODE),A
	XOR	A
	CALL	@S9APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	(NETDRV_FAIL_CODE),A
	CALL	PRINT_NETWORK_ERROR
	LD	A,(NETDRV_FAIL_CODE)
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(S9_EXIT_CODE),A
	LD	A,C
	CALL	@S9APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(S9_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

PRINT_NETWORK_ERROR
	LD	HL,MSG_NETWORK
	CALL	@CONSOLE.STRING
	LD	A,(S11_DIAG_STAGE)
	CALL	@CONSOLE.DEC8
	LD	A,(S11_DIAG_STAGE)
	OR	A
	JR	NZ,.MILLISECONDS
	LD	HL,MSG_TICKS
	CALL	@CONSOLE.STRING
	LD	HL,(EL3_LAST_TICKS)
	CALL	@CONSOLE.HEX16
	JR	.DEVICE
.MILLISECONDS
	LD	HL,MSG_ELAPSED
	CALL	@CONSOLE.STRING
	LD	HL,(NETTIME_ELAPSED_MS)
	CALL	@CONSOLE.DEC16
.DEVICE
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_TARGET
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	LD	B,4
.IP
	LD	A,(HL)
	INC	HL
	CALL	@CONSOLE.DEC8
	DJNZ	.IP_SEPARATOR
	JR	.PORT
.IP_SEPARATOR
	LD	A,'.'
	CALL	@CONSOLE.CHAR
	JR	.IP
.PORT
	LD	A,':'
	CALL	@CONSOLE.CHAR
	LD	HL,(S9_REMOTE_PORT)
	CALL	@CONSOLE.DEC16
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

MSG_BANNER	DB "3C509B TCPTEST v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: TCPTEST [-n count] [-l 0..4096] [-w ms] IPv4 port",0
MSG_CHANNEL	DB "[E1] channel=",0
MSG_BYTES	DB " bytes=",0
MSG_NETWORK	DB "[E2] NETWORK stage=",0
MSG_TICKS	DB " elapsed_ticks=#",0
MSG_ELAPSED	DB " elapsed_ms=",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=",0
MSG_TARGET	DB " target=",0
MSG_OK		DB "RESULT OK",0
MSG_FAIL	DB "RESULT FAIL code=",0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "tcp.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "stage9_cli.asm"
	INCLUDE "tcp_transport.asm"
	INCLUDE "stage11_app.asm"

	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP
