; TFTP.EXE - polling-only RFC 1350/RFC 2348 GET and PUT client.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE9_TFTP
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE10_DNS
	DEFINE STAGE10_TFTP

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"
	INCLUDE "dns_ntp.inc"

	MODULE MAIN

TFTP_TIMEOUT_MS	EQU 5000
TFTP_STATE_SENDS EQU 6
TFTP_LOCAL_PORT EQU 0x9000

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	@S10APP.SAVE_COMMAND
	CALL	@S10APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	CALL	@S9CLI.PARSE_TFTP
	JR	NC,.ARGS_OK
	CP	EL3_CLI_HELP
	JP	NZ,USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
.ARGS_OK
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JP	C,NETWORK_FAIL
	XOR	A
	LD	(DNS_EXPLICIT_FLAG),A
	LD	HL,S9_TFTP_HOST
	CALL	@DNSX.RESOLVE_OR_LITERAL
	JR	NC,.TARGET_OK
	JP	NETWORK_FAIL
.TARGET_OK
	LD	HL,1
	LD	(S9_IP_ID),HL
	LD	BC,(S9_TFTP_REQUEST_PORT)
	LD	DE,TFTP_LOCAL_PORT
	LD	HL,NET_TARGET_IP
	CALL	@UDPX.OPEN
	JR	NC,.ROUTE_OK
	JP	NETWORK_FAIL
.ROUTE_OK
	CALL	OPEN_LOCAL_FILE
	JR	NC,.FILE_OK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	FILE_FAIL
.FILE_OK
	LD	HL,0
	LD	(S9_TFTP_SERVER_PORT),HL
	LD	(S9_EXPECT_REMOTE_PORT),HL	; receive any TID, reject in TFTP layer
	LD	HL,TFTP_DEFAULT_BLOCK
	LD	(S9_TFTP_BLOCK_SIZE),HL
	LD	HL,0
	LD	(S9_TFTP_BUFFER_USED),HL
	LD	A,(S9_TFTP_MODE)
	OR	A
	JR	NZ,.PUT
	CALL	RUN_GET
	JR	.RESULT
.PUT
	CALL	RUN_PUT
.RESULT
	JP	NC,SUCCESS
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	NETDRV_ERR_FILE_IO
	JP	Z,FILE_FAIL
	CP	NETDRV_ERR_PROTOCOL
	JP	Z,REMOTE_FAIL
	CP	NETDRV_ERR_UNREACHABLE
	JP	Z,REMOTE_FAIL
	JP	NETWORK_FAIL

OPEN_LOCAL_FILE
	LD	A,(S9_TFTP_MODE)
	OR	A
	JR	NZ,.INPUT
	LD	HL,S9_TFTP_LOCAL_NAME
	LD	A,(S9_TFTP_FORCE)
	CALL	@FILE.OPEN_OUTPUT
	JR	.STORE
.INPUT
	LD	HL,S9_TFTP_LOCAL_NAME
	CALL	@FILE.OPEN_INPUT
.STORE
	RET	C
	LD	(S9_TFTP_FILE_HANDLE),A
	LD	A,1
	LD	(S9_TFTP_FILE_OPEN),A
	XOR	A
	RET

; ---------------- GET ----------------
RUN_GET
	CALL	REQUEST_GET
	RET	C
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_OACK
	JR	Z,.AFTER_OACK
	; Fallback DATA block 1 was returned directly from RRQ.
	CALL	PROCESS_GET_DATA
	RET	C
	JR	.CHECK_FINAL
.AFTER_OACK
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK_SIZE)
	LD	(S9_TFTP_BLOCK_SIZE),HL
	LD	HL,1
	LD	(S9_TFTP_BLOCK),HL
.GET_NEXT
	CALL	GET_DATA_STATE
	RET	C
	CALL	PROCESS_GET_DATA
	RET	C
.CHECK_FINAL
	LD	A,(S9_TFTP_FINAL)
	OR	A
	JR	Z,.GET_NEXT
	CALL	FLUSH_FILE_BUFFER
	RET	C
	JP	DALLY_FINAL

REQUEST_GET
	LD	A,TFTP_STATE_SENDS
	LD	(S9_TFTP_RETRIES),A
.TRY
	CALL	SEND_REQUEST
	RET	C
	LD	BC,TFTP_TIMEOUT_MS
	CALL	@UDPX.WAIT
.RECEIVE
	JR	C,.WAIT_ERROR
	CALL	PARSE_PACKET
	JR	C,.MALFORMED
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_ERROR
	JR	Z,.LATCH_ERROR
	CP	TFTP_OPCODE_OACK
	JR	Z,.LATCH_OACK
	CP	TFTP_OPCODE_DATA
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK)
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_DATA_LENGTH)
	LD	DE,TFTP_DEFAULT_BLOCK+1
	OR	A
	SBC	HL,DE
	JR	NC,.CONTINUE
	CALL	LATCH_TID
	JR	C,.CONTINUE
	LD	HL,TFTP_DEFAULT_BLOCK
	LD	(S9_TFTP_BLOCK_SIZE),HL
	LD	HL,1
	LD	(S9_TFTP_BLOCK),HL
	XOR	A
	RET
.LATCH_OACK
	CALL	LATCH_TID
	JR	C,.CONTINUE
	XOR	A
	RET
.LATCH_ERROR
	CALL	LATCH_TID
	JR	C,.CONTINUE
	JP	REPORT_SERVER_ERROR
.MALFORMED
	CALL	IS_BAD_OACK
	JR	NZ,.CONTINUE
	CALL	SEND_OPTION_ERROR
	LD	A,NETDRV_ERR_PROTOCOL
	SCF
	RET
.CONTINUE
	CALL	@UDPX.WAIT_CONTINUE
	JR	.RECEIVE
.WAIT_ERROR
	CP	NETDRV_ERR_UNREACHABLE
	JR	Z,.RETURN_ERROR
	CP	NETDRV_ERR_CANCELLED
	JR	Z,.RETURN_ERROR
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.RETURN_ERROR
	LD	A,(S9_TFTP_RETRIES)
	DEC	A
	LD	(S9_TFTP_RETRIES),A
	JR	NZ,.TRY
	LD	A,EL3_ERR_RX_TIMEOUT
.RETURN_ERROR
	SCF
	RET

GET_DATA_STATE
	LD	A,TFTP_STATE_SENDS
	LD	(S9_TFTP_RETRIES),A
.TRY
	LD	HL,(S9_TFTP_BLOCK)
	DEC	HL
	CALL	SEND_ACK
	RET	C
	LD	BC,TFTP_TIMEOUT_MS
	CALL	@UDPX.WAIT
.RECEIVE
	JR	C,.WAIT_ERROR
	CALL	CHECK_TID
	JR	NC,.TID_OK
	CALL	SEND_UNKNOWN_TID
	JR	.CONTINUE
.TID_OK
	CALL	PARSE_PACKET
	JR	C,.CONTINUE
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_ERROR
	JP	Z,REPORT_SERVER_ERROR
	CP	TFTP_OPCODE_DATA
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK)
	LD	DE,(S9_TFTP_BLOCK)
	OR	A
	SBC	HL,DE
	JR	Z,.EXPECTED
	INC	HL			; previous duplicate -> ACK it again
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_BLOCK)
	DEC	HL
	CALL	SEND_ACK
	RET	C
	JR	.CONTINUE
.EXPECTED
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_DATA_LENGTH)
	LD	DE,(S9_TFTP_BLOCK_SIZE)
	OR	A
	SBC	HL,DE
	JR	C,.OK
	JR	NZ,.CONTINUE
.OK
	XOR	A
	RET
.CONTINUE
	CALL	@UDPX.WAIT_CONTINUE
	JR	.RECEIVE
.WAIT_ERROR
	CP	NETDRV_ERR_UNREACHABLE
	JR	Z,.ERROR
	CP	NETDRV_ERR_CANCELLED
	JR	Z,.ERROR
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.ERROR
	LD	A,(S9_TFTP_RETRIES)
	DEC	A
	LD	(S9_TFTP_RETRIES),A
	JR	NZ,.TRY
	LD	A,EL3_ERR_RX_TIMEOUT
.ERROR
	SCF
	RET

PROCESS_GET_DATA
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_DATA)
	LD	BC,(S9_TFTP_PACKET_DESC+TFTPP_DATA_LENGTH)
	CALL	APPEND_FILE_DATA
	RET	C
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_DATA_LENGTH)
	LD	DE,(S9_TFTP_BLOCK_SIZE)
	OR	A
	SBC	HL,DE
	LD	A,0
	JR	Z,.NOT_FINAL
	INC	A
.NOT_FINAL
	LD	(S9_TFTP_FINAL),A
	OR	A
	JR	Z,.ACK_DONE
	LD	HL,(S9_TFTP_BLOCK)
	CALL	SEND_ACK
	RET	C
.ACK_DONE
	LD	HL,(S9_TFTP_BLOCK)
	INC	HL			; modulo 65536
	LD	(S9_TFTP_BLOCK),HL
	XOR	A
	RET

APPEND_FILE_DATA
	LD	(S9_RX_PAYLOAD),HL
	LD	(S9_RX_PAYLOAD_LENGTH),BC
	LD	HL,(S9_TFTP_BUFFER_USED)
	ADD	HL,BC
	JR	C,.APPEND_BAD
	LD	DE,STAGE9_FILE_CAPACITY+1
	OR	A
	SBC	HL,DE
	JR	C,.COPY
	CALL	FLUSH_FILE_BUFFER
	RET	C
.COPY
	LD	HL,(S9_RX_PAYLOAD)
	LD	DE,STAGE9_FILE_BUFFER
	PUSH	HL
	LD	HL,(S9_TFTP_BUFFER_USED)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	LD	BC,(S9_RX_PAYLOAD_LENGTH)
	LD	A,B
	OR	C
	JR	Z,.AFTER_COPY
	LDIR
.AFTER_COPY
	LD	HL,(S9_TFTP_BUFFER_USED)
	LD	BC,(S9_RX_PAYLOAD_LENGTH)
	ADD	HL,BC
	LD	(S9_TFTP_BUFFER_USED),HL
	XOR	A
	RET
.APPEND_BAD
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

FLUSH_FILE_BUFFER
	LD	DE,(S9_TFTP_BUFFER_USED)
	LD	A,D
	OR	E
	RET	Z
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	HL,STAGE9_FILE_BUFFER
	LD	C,DSS_WRITE
	RST	DSS
	JR	C,.WRITE_BAD
	LD	HL,0
	LD	(S9_TFTP_BUFFER_USED),HL
	XOR	A
	RET
.WRITE_BAD
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

DALLY_FINAL
	LD	BC,1000
	CALL	@UDPX.WAIT
.RECEIVE
	JR	C,.DONE
	CALL	CHECK_TID
	JR	NC,.TID_OK
	CALL	SEND_UNKNOWN_TID
	JR	.CONTINUE
.TID_OK
	CALL	PARSE_PACKET
	JR	C,.CONTINUE
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_DATA
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_BLOCK)
	DEC	HL
	LD	DE,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK)
	OR	A
	SBC	HL,DE
	JR	NZ,.CONTINUE
	EX	DE,HL
	CALL	SEND_ACK
.CONTINUE
	CALL	@UDPX.WAIT_CONTINUE
	JR	.RECEIVE
.DONE
	XOR	A
	RET

; ---------------- PUT ----------------
RUN_PUT
	CALL	REQUEST_PUT
	RET	C
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_OACK
	JR	NZ,.FALLBACK
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK_SIZE)
	LD	(S9_TFTP_BLOCK_SIZE),HL
	JR	.START
.FALLBACK
	LD	HL,TFTP_DEFAULT_BLOCK
	LD	(S9_TFTP_BLOCK_SIZE),HL
.START
	LD	HL,1
	LD	(S9_TFTP_BLOCK),HL
.NEXT
	CALL	READ_PUT_BLOCK
	RET	C
	CALL	PUT_DATA_STATE
	RET	C
	LD	A,(S9_TFTP_FINAL)
	OR	A
	JR	NZ,.DONE
	LD	HL,(S9_TFTP_BLOCK)
	INC	HL
	LD	(S9_TFTP_BLOCK),HL
	JR	.NEXT
.DONE
	RET

REQUEST_PUT
	LD	A,TFTP_STATE_SENDS
	LD	(S9_TFTP_RETRIES),A
.TRY
	CALL	SEND_REQUEST
	RET	C
	LD	BC,TFTP_TIMEOUT_MS
	CALL	@UDPX.WAIT
.RECEIVE
	JR	C,.WAIT_ERROR
	CALL	PARSE_PACKET
	JR	C,.MALFORMED
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_ERROR
	JR	Z,.LATCH_ERROR
	CP	TFTP_OPCODE_OACK
	JR	Z,.LATCH_OK
	CP	TFTP_OPCODE_ACK
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK)
	LD	A,H
	OR	L
	JR	NZ,.CONTINUE
.LATCH_OK
	CALL	LATCH_TID
	JR	C,.CONTINUE
	XOR	A
	RET
.LATCH_ERROR
	CALL	LATCH_TID
	JR	C,.CONTINUE
	JP	REPORT_SERVER_ERROR
.MALFORMED
	CALL	IS_BAD_OACK
	JR	NZ,.CONTINUE
	CALL	SEND_OPTION_ERROR
	LD	A,NETDRV_ERR_PROTOCOL
	SCF
	RET
.CONTINUE
	CALL	@UDPX.WAIT_CONTINUE
	JR	.RECEIVE
.WAIT_ERROR
	CP	NETDRV_ERR_UNREACHABLE
	JR	Z,.ERROR
	CP	NETDRV_ERR_CANCELLED
	JR	Z,.ERROR
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.ERROR
	LD	A,(S9_TFTP_RETRIES)
	DEC	A
	LD	(S9_TFTP_RETRIES),A
	JR	NZ,.TRY
	LD	A,EL3_ERR_RX_TIMEOUT
.ERROR
	SCF
	RET

READ_PUT_BLOCK
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	HL,STAGE9_TX_BUFFER+46
	LD	DE,(S9_TFTP_BLOCK_SIZE)
	LD	C,DSS_READ_FILE
	RST	DSS
	JR	C,.READ_BAD
	LD	(S9_SIZE),DE
	LD	HL,(S9_TFTP_BLOCK_SIZE)
	OR	A
	SBC	HL,DE
	LD	A,0
	JR	Z,.FULL
	INC	A
.FULL
	LD	(S9_TFTP_FINAL),A
	RET
.READ_BAD
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

PUT_DATA_STATE
	LD	A,TFTP_STATE_SENDS
	LD	(S9_TFTP_RETRIES),A
.TRY
	CALL	SEND_DATA
	RET	C
	LD	BC,TFTP_TIMEOUT_MS
	CALL	@UDPX.WAIT
.RECEIVE
	JR	C,.WAIT_ERROR
	CALL	CHECK_TID
	JR	NC,.TID_OK
	CALL	SEND_UNKNOWN_TID
	JR	.CONTINUE
.TID_OK
	CALL	PARSE_PACKET
	JR	C,.CONTINUE
	LD	A,(S9_TFTP_PACKET_DESC+TFTPP_OPCODE)
	CP	TFTP_OPCODE_ERROR
	JP	Z,REPORT_SERVER_ERROR
	CP	TFTP_OPCODE_ACK
	JR	NZ,.CONTINUE
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_BLOCK)
	LD	DE,(S9_TFTP_BLOCK)
	OR	A
	SBC	HL,DE
	JR	Z,.OK
	JR	.CONTINUE
.OK
	XOR	A
	RET
.CONTINUE
	CALL	@UDPX.WAIT_CONTINUE
	JR	.RECEIVE
.WAIT_ERROR
	CP	NETDRV_ERR_UNREACHABLE
	JR	Z,.ERROR
	CP	NETDRV_ERR_CANCELLED
	JR	Z,.ERROR
	CP	EL3_ERR_RX_TIMEOUT
	JR	NZ,.ERROR
	LD	A,(S9_TFTP_RETRIES)
	DEC	A
	LD	(S9_TFTP_RETRIES),A
	JR	NZ,.TRY
	LD	A,EL3_ERR_RX_TIMEOUT
.ERROR
	SCF
	RET

; ---------------- packet helpers ----------------
SEND_REQUEST
	LD	HL,S9_TFTP_REMOTE_NAME
	CALL	STRING_LENGTH
	LD	(S9_TFTP_BUILD_DESC+TFTPR_NAME_LENGTH),BC
	LD	HL,STAGE9_TX_BUFFER+42
	LD	(S9_TFTP_BUILD_DESC+TFTPR_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-42
	LD	(S9_TFTP_BUILD_DESC+TFTPR_CAPACITY),HL
	LD	HL,S9_TFTP_REMOTE_NAME
	LD	(S9_TFTP_BUILD_DESC+TFTPR_NAME),HL
	LD	HL,TFTP_OPCODE_RRQ
	LD	A,(S9_TFTP_MODE)
	OR	A
	JR	Z,.OP_READY
	LD	HL,TFTP_OPCODE_WRQ
.OP_READY
	LD	(S9_TFTP_BUILD_DESC+TFTPR_OPCODE),HL
	LD	HL,TFTP_REQUEST_BLOCK
	LD	(S9_TFTP_BUILD_DESC+TFTPR_BLOCK_SIZE),HL
	LD	HL,S9_TFTP_BUILD_DESC
	CALL	@TFTP.BUILD_REQUEST
	RET	C
	JP	@UDPX.SEND

SEND_ACK
	LD	(S9_TFTP_ACK_DESC+TFTPA_BLOCK),HL
	LD	HL,STAGE9_TX_BUFFER+42
	LD	(S9_TFTP_ACK_DESC+TFTPA_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-42
	LD	(S9_TFTP_ACK_DESC+TFTPA_CAPACITY),HL
	LD	HL,S9_TFTP_ACK_DESC
	CALL	@TFTP.BUILD_ACK
	RET	C
	JP	@UDPX.SEND

SEND_DATA
	LD	HL,STAGE9_TX_BUFFER+42
	LD	(S9_TFTP_DATA_DESC+TFTPD_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-42
	LD	(S9_TFTP_DATA_DESC+TFTPD_CAPACITY),HL
	LD	HL,(S9_SIZE)
	LD	(S9_TFTP_DATA_DESC+TFTPD_DATA_LENGTH),HL
	LD	HL,(S9_TFTP_BLOCK)
	LD	(S9_TFTP_DATA_DESC+TFTPD_BLOCK),HL
	LD	HL,S9_TFTP_DATA_DESC
	CALL	@TFTP.BUILD_DATA
	RET	C
	JP	@UDPX.SEND

PARSE_PACKET
	LD	(S9_TFTP_PACKET_DESC+TFTPP_BUFFER),HL
	LD	(S9_TFTP_PACKET_DESC+TFTPP_LENGTH),BC
	LD	HL,S9_TFTP_PACKET_DESC
	JP	@TFTP.PARSE

LATCH_TID
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	(S9_TFTP_SERVER_PORT),HL
	JP	@UDPX.SET_REMOTE_PORT

CHECK_TID
	PUSH	HL
	LD	HL,(S9_RX_SOURCE_PORT)
	LD	DE,(S9_TFTP_SERVER_PORT)
	OR	A
	SBC	HL,DE
	POP	HL
	RET	Z
	SCF
	RET

SEND_UNKNOWN_TID
	LD	HL,TFTP_ERROR_UNKNOWN_TID
	LD	DE,(S9_RX_SOURCE_PORT)
	LD	BC,MSG_UNKNOWN_LEN
	LD	IX,MSG_UNKNOWN
	JP	SEND_ERROR

SEND_OPTION_ERROR
	LD	HL,TFTP_ERROR_OPTION
	LD	DE,(S9_RX_SOURCE_PORT)
	LD	BC,MSG_OPTION_LEN
	LD	IX,MSG_OPTION
	JP	SEND_ERROR

; HL=code, DE=destination TID, BC=message length, IX=message.
SEND_ERROR
	LD	(S9_TFTP_ERROR_DESC+TFTPE_CODE),HL
	PUSH	IX
	POP	HL
	LD	(S9_TFTP_ERROR_DESC+TFTPE_MESSAGE),HL
	LD	(S9_TFTP_ERROR_DESC+TFTPE_MESSAGE_LENGTH),BC
	LD	HL,(S9_REMOTE_PORT)
	LD	(S9_RX_PAYLOAD),HL
	EX	DE,HL
	CALL	@UDPX.SET_REMOTE_PORT
	RET	C
	LD	HL,STAGE9_TX_BUFFER+42
	LD	(S9_TFTP_ERROR_DESC+TFTPE_BUFFER),HL
	LD	HL,STAGE9_TX_CAPACITY-42
	LD	(S9_TFTP_ERROR_DESC+TFTPE_CAPACITY),HL
	LD	HL,S9_TFTP_ERROR_DESC
	CALL	@TFTP.BUILD_ERROR
	JR	C,.RESTORE
	CALL	@UDPX.SEND
.RESTORE
	PUSH	AF
	LD	HL,(S9_RX_PAYLOAD)
	CALL	@UDPX.SET_REMOTE_PORT
	POP	AF
	RET

IS_BAD_OACK
	LD	HL,(S9_RX_PAYLOAD_LENGTH)
	LD	A,H
	OR	A
	JR	NZ,.CHECK
	LD	A,L
	CP	2
	RET	C
.CHECK
	LD	HL,(S9_RX_PAYLOAD)
	LD	A,(HL)
	OR	A
	RET	NZ
	INC	HL
	LD	A,(HL)
	CP	TFTP_OPCODE_OACK
	RET

REPORT_SERVER_ERROR
	LD	HL,MSG_SERVER_ERROR
	CALL	@CONSOLE.STRING
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_ERROR_CODE)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_SERVER_SEP
	CALL	@CONSOLE.STRING
	LD	HL,(S9_TFTP_PACKET_DESC+TFTPP_DATA)
	LD	BC,(S9_TFTP_PACKET_DESC+TFTPP_DATA_LENGTH)
	LD	A,B
	OR	A
	JR	Z,.BOUND
	LD	BC,79
.BOUND
	LD	A,C
	CP	80
	JR	C,.PRINT
	LD	C,79
.PRINT
	LD	A,B
	OR	C
	JR	Z,.LINE
	LD	A,(HL)
	CALL	@CONSOLE.CHAR
	INC	HL
	DEC	BC
	JR	.PRINT
.LINE
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,NETDRV_ERR_PROTOCOL
	SCF
	RET

STRING_LENGTH
	LD	BC,0
.LEN
	LD	A,(HL)
	OR	A
	RET	Z
	INC	HL
	INC	BC
	JR	.LEN

; ---------------- exits ----------------
SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(S9_EXIT_CODE),A
	XOR	A
	CALL	@S9APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	CP	NETDRV_ERR_CANCELLED
	JR	Z,CANCEL_FAIL
	CALL	PRINT_NETWORK_ERROR
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
FILE_FAIL
	LD	B,DSS_EXIT_LOCAL
	JR	FAIL
REMOTE_FAIL
	LD	B,DSS_EXIT_REMOTE
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(S9_EXIT_CODE),A
	LD	A,C
	CALL	@S9APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(S9_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

; A=status. Used only after a failed bounded network operation.
PRINT_NETWORK_ERROR
	PUSH	AF
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_NETWORK
	CALL	@CONSOLE.STRING
	LD	HL,(NETTIME_ELAPSED_MS)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_TARGET
	CALL	@CONSOLE.STRING
	LD	HL,S9_TFTP_HOST
	CALL	@CONSOLE.STRING
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	POP	AF
	RET

MSG_BANNER	DB "3C509B TFTP v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: TFTP host[:port] GET remote [-o local] [-y|-f] | PUT local [-o remote]",0
MSG_SERVER_ERROR DB "[E5] TFTP ERROR code=",0
MSG_SERVER_SEP	DB " message=",0
MSG_UNKNOWN	DB "Unknown transfer ID"
MSG_UNKNOWN_LEN EQU $-MSG_UNKNOWN
MSG_OPTION	DB "Invalid blksize"
MSG_OPTION_LEN EQU $-MSG_OPTION
MSG_NETWORK	DB "[E2] NETWORK stage=TFTP elapsed_ms=",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=",0
MSG_TARGET	DB " target=",0
MSG_OK		DB "RESULT OK",0
MSG_FAIL	DB "RESULT FAIL code=",0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "icmp.asm"
	INCLUDE "udp.asm"
	INCLUDE "dns.asm"
	INCLUDE "../lib/tftp.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "file.asm"
	INCLUDE "stage9_cli.asm"
	INCLUDE "udp_transport.asm"
	INCLUDE "stage10_app.asm"

	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP
