; UDPTEST.EXE - bounded UDP echo/generator diagnostic.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
	DEFINE RUNTIME_BASE 0x7000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE10_DNS

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"
	INCLUDE "dns_ntp.inc"

	MODULE MAIN

	ORG 0x8080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	DW START,START,STACK_TOP
	DS 106,0

	ORG 0x8100
START
	LD	SP,STACK_TOP
	CALL	@S10APP.SAVE_COMMAND
	CALL	@S10APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	CALL	@ARP.CLEAR_CACHE
	CALL	@S9CLI.PARSE_UDP
	JR	NC,.ARGS_OK
	CP	EL3_CLI_HELP
	JP	NZ,USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	JP	SUCCESS
.ARGS_OK
	LD	HL,(S9_REMOTE_PORT)
	LD	(S10_APP_PORT),HL
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	LD	BC,10000
	CALL	@NETDRV.WAIT_LINK_UP
	JP	C,NETWORK_FAIL
	XOR	A
	LD	(DNS_EXPLICIT_FLAG),A
	LD	HL,S9_TARGET_TEXT
	CALL	@DNSX.RESOLVE_OR_LITERAL
	JR	NC,.TARGET_OK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.TARGET_OK
	LD	HL,1
	LD	(S9_IP_ID),HL
	LD	HL,0
	LD	(S9_SEQUENCE),HL
	CALL	OPEN_DATAGRAM
	JR	NC,.OPEN_OK
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	JP	NETWORK_FAIL
.OPEN_OK
	CALL	RUN
	JP	NC,SUCCESS
	CP	NETDRV_ERR_CANCELLED
	JP	Z,CANCEL_FAIL
	CP	NETDRV_ERR_UNREACHABLE
	JP	Z,REMOTE_FAIL
	JP	NETWORK_FAIL

OPEN_DATAGRAM
	LD	HL,NET_TARGET_IP
	LD	BC,(S10_APP_PORT)
	LD	DE,0x8000
	JP	@UDPX.OPEN

RUN
.NEXT
	LD	HL,(S9_SEQUENCE)
	INC	HL			; one distinct nonzero local port per datagram
	LD	(S9_LOCAL_PORT),HL
	LD	A,3
	LD	(S9_ATTEMPTS),A
.TRY
	CALL	FILL_PAYLOAD
	LD	BC,(S9_SIZE)
	CALL	@UDPX.SEND
	RET	C
	LD	BC,(S9_TIMEOUT_MS)
	CALL	@UDPX.WAIT
	JR	.WAIT_RESULT
.WAIT_MORE
	CALL	@UDPX.WAIT_CONTINUE
.WAIT_RESULT
	JR	NC,.REPLY
	CP	EL3_ERR_RX_TIMEOUT
	JR	Z,.RETRY_TIMEOUT
	SCF
	RET
.RETRY_TIMEOUT
	LD	A,(S9_ATTEMPTS)
	DEC	A
	LD	(S9_ATTEMPTS),A
	JR	NZ,.TRY
	CALL	PRINT_TIMEOUT
	LD	A,EL3_ERR_RX_TIMEOUT
	SCF
	RET
.REPLY
	CALL	VERIFY_REPLY
	JR	C,.WAIT_MORE
	CALL	PRINT_REPLY
	LD	HL,(S9_SEQUENCE)
	INC	HL
	LD	(S9_SEQUENCE),HL
	LD	DE,(S9_COUNT)
	OR	A
	SBC	HL,DE
	JR	C,.NEXT
	XOR	A
	RET

FILL_PAYLOAD
	LD	HL,STAGE9_TX_BUFFER+42
	LD	BC,(S9_SIZE)
	LD	DE,(S9_SEQUENCE)
	LD	A,E
	XOR	D
	LD	D,A
	LD	E,0
.FILL
	LD	A,B
	OR	C
	RET	Z
	LD	A,E
	XOR	D
	LD	(HL),A
	INC	HL
	INC	E
	DEC	BC
	JR	.FILL

VERIFY_REPLY
	LD	DE,(S9_SIZE)
	LD	A,B
	CP	D
	JR	NZ,.BAD
	LD	A,C
	CP	E
	JR	NZ,.BAD
	LD	DE,(S9_SEQUENCE)
	LD	A,E
	XOR	D
	LD	D,A
	LD	E,0
.VERIFY
	LD	A,B
	OR	C
	JR	Z,.OK
	LD	A,E
	XOR	D
	CP	(HL)
	JR	NZ,.BAD
	INC	HL
	INC	E
	DEC	BC
	JR	.VERIFY
.OK
	XOR	A
	RET
.BAD
	SCF
	RET

PRINT_REPLY
	LD	HL,MSG_REPLY
	CALL	@CONSOLE.STRING
	LD	HL,(S9_SEQUENCE)
	INC	HL
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_BYTES
	CALL	@CONSOLE.STRING
	LD	HL,(S9_SIZE)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_TIME
	CALL	@CONSOLE.STRING
	LD	HL,(NETTIME_ELAPSED_MS)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_MS
	JP	@CONSOLE.LINE

PRINT_TIMEOUT
	LD	HL,MSG_TIMEOUT
	CALL	@CONSOLE.STRING
	LD	HL,(NETTIME_ELAPSED_MS)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_SLOT
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	A,EL3_ERR_RX_TIMEOUT
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_TARGET
	CALL	@CONSOLE.STRING
	LD	HL,S9_TARGET_TEXT
	CALL	@CONSOLE.STRING
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

SUCCESS
	LD	A,DSS_EXIT_LOCAL
	LD	(S9_EXIT_CODE),A
	XOR	A
	CALL	@S9APP.CLEANUP
	JR	C,LOCAL_FAIL_DIRECT
	LD	HL,MSG_OK
	CALL	@CONSOLE.LINE
	DSS_RETURN DSS_EXIT_OK
USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.LINE
	LD	A,NETDRV_ERR_PARAMETER
	LD	B,DSS_EXIT_ARGUMENT
	JR	FAIL
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JR	FAIL
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JR	FAIL
NETWORK_FAIL
	LD	B,DSS_EXIT_NETWORK
	JR	FAIL
REMOTE_FAIL
	LD	B,DSS_EXIT_REMOTE
	JR	FAIL
CANCEL_FAIL
	LD	B,DSS_EXIT_CANCELLED
	JR	FAIL
LOCAL_FAIL
	LD	B,DSS_EXIT_LOCAL
FAIL
	LD	C,A
	LD	A,B
	LD	(S9_EXIT_CODE),A
	LD	A,C
	CALL	@S9APP.CLEANUP
LOCAL_FAIL_DIRECT
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	A,(S9_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

BOOT_FAIL
	LD	(NETDRV_FAIL_CODE),A
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_FAIL_CODE)
	CALL	@CONSOLE.DEC8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	DSS_RETURN DSS_EXIT_LOCAL

MSG_BANNER	DB "3C509B UDPTEST v",PACKAGE_VERSION,0
MSG_HELP	DB "Usage: UDPTEST [-n count] [-l size] [-w ms] target port",0
MSG_REPLY	DB "Reply datagram=",0
MSG_BYTES	DB " bytes=",0
MSG_TIME	DB " time~=",0
MSG_MS		DB "ms",0
MSG_TIMEOUT	DB "[E2] TIMEOUT stage=UDP elapsed_ms=",0
MSG_SLOT	DB " slot=",0
MSG_BASE	DB " base=#",0
MSG_STATUS	DB " status=",0
MSG_TARGET	DB " target=",0
MSG_OK		DB "RESULT OK",0
MSG_FAIL	DB "RESULT FAIL code=",0

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "icmp.asm"
	INCLUDE "udp.asm"
	INCLUDE "dns.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "stage9_cli.asm"
	INCLUDE "udp_transport.asm"
	INCLUDE "stage10_app.asm"

	ASSERT $ + S10_BOOTSTRAP_STACK_RESERVE <= S10_STACK_TOP
