; WGET.EXE - polling-only HTTP/1.0 downloader over the 3C509B backend.
; SPDX-License-Identifier: BSD-3-Clause

EXE_VERSION	EQU 1
; WGET's image fills a whole 16 KiB window, so unlike every other utility here
; it loads into WIN1 and claims WIN2 for its page -- the sibling RTL8019A kit's
; arrangement for its large utilities. Runtime state therefore sits in
; 8000h..BFFFh, and the stack ends up at the top of the claimed page.
	DEFINE RUNTIME_BASE 0xB000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEFINE STAGE10_DNS
	DEFINE STAGE11_LAYOUT
	DEFINE STAGE12_LAYOUT
	; Image headroom to spare, so take the unrolled FIFO burst (el3_io.asm).
	DEFINE FAST_DATAPATH
	; Round-2 throughput: driver primitives must never be called from inside
	; PROCESS_FRAME/HANDLE_SEGMENT's own call chain (tcp_transport.asm), so
	; the ACK a segment earns is deferred to .WAIT_LOOP instead of sent
	; in-line. FTP does not define this and keeps the byte-identical old
	; behavior -- its image has no room to spare for this yet.
	DEFINE TCPX_DIRECT_RX

	DEVICE NOSLOT64K
	INCLUDE "version.inc"
	INCLUDE "dss.inc"
	INCLUDE "macro.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"
	INCLUDE "dns_ntp.inc"
	INCLUDE "tcp.inc"

	MODULE MAIN

HTTP_IDLE_MS	EQU 15000
MAX_REDIRECTS	EQU 5
WGET_HEADER_SIZE EQU 256

	ORG 0x4080
	DB "EXE",EXE_VERSION
	DW 0x0080,0,0,0,0,0
	; DSS installs this stack before the entry point runs and spends it on the
	; loader and on interrupt frames, so it has to be clear of the image on its
	; own. BFF0h is the top of WIN2, which the standard layout hands to the
	; program along with WIN1, so it is clear of the image by 16 KiB.
	DW START,START,S10_BOOTSTRAP_STACK
	DS 106,0

	ORG 0x4100
START
	; Restates the header stack. It is already at the top of WIN2, so the WIN1
	; hazard that used to gag this path is gone: BIOS WIN_MOVE maps the video
	; page over WIN1 on a scrolled line and restores SLOT1 from a POP taken
	; while that page is mapped, which only ever threatened a WIN1 stack.
	LD	SP,S10_BOOTSTRAP_STACK
	CALL	@S11APP.SAVE_COMMAND
	CALL	@S11APP.ALLOCATE_FRESH
	JP	C,BOOT_FAIL
	LD	SP,S10_RUNTIME_STACK_TOP
	LD	(CMDLINE_SOURCE),IX
	LD	HL,MSG_BANNER
	CALL	@CONSOLE.LINE
	CALL	CLEAR_WGET_STATE
	CALL	@ARP.CLEAR_CACHE
	CALL	@S9CLI.PARSE_WGET
	JR	NC,.ARGS_OK
	CP	EL3_CLI_HELP
	JP	NZ,USAGE_FAIL
	LD	HL,MSG_HELP
	CALL	@CONSOLE.STRING
	JP	SUCCESS_NO_FILE
.ARGS_OK
	LD	HL,W12_URL
	CALL	PARSE_URL
	JP	C,USAGE_FAIL
	LD	A,(W12_FLAGS)
	AND	0x08
	JR	Z,.DERIVE_OUTPUT
	LD	HL,W12_OUTPUT
	LD	(W12_OUTPUT_PTR),HL
	JR	.OUTPUT_READY
.DERIVE_OUTPUT
	CALL	DERIVE_OUTPUT
.OUTPUT_READY
	CALL	@S9APP.LOAD_ACTIVE_CONFIG
	JP	C,CONFIG_FAIL
	CALL	@S9APP.INIT_DRIVER
	JP	C,HARDWARE_FAIL
	CALL	OPEN_LOCAL_FILE
	JR	NC,.FILE_READY
	CP	NETDRV_ERR_CANCELLED
	JP	Z,PROMPT_CANCEL
	JP	FILE_FAIL
.FILE_READY
	; Redirects rewrite W12_PATH. Preserve the successfully opened name so an
	; HTTP failure always deletes that file, never a later redirect basename.
	LD	HL,(W12_OUTPUT_PTR)
	LD	DE,W12_OUTPUT_SNAPSHOT
	LD	B,95
	CALL	COPY_BOUNDED_Z
	LD	HL,W12_OUTPUT_SNAPSHOT
	LD	(W12_OUTPUT_PTR),HL
	CALL	TIME_START
	XOR	A
	LD	(W12_REDIRECTS),A

HOP_LOOP
	LD	HL,W12_HOST
	CALL	@DNSX.RESOLVE_OR_LITERAL
	JP	C,RESOLVE_FAIL
	LD	HL,MSG_RESOLVED
	CALL	@CONSOLE.STRING
	LD	HL,W12_HOST
	CALL	@CONSOLE.STRING
	LD	HL,MSG_TO
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IPV4
	LD	HL,MSG_PORT
	CALL	@CONSOLE.STRING
	LD	HL,(W12_PORT)
	CALL	@CONSOLE.DEC16
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_CONNECTING
	CALL	@CONSOLE.STRING
	LD	HL,NET_TARGET_IP
	CALL	PRINT_IPV4
	LD	HL,MSG_PORT
	CALL	@CONSOLE.STRING
	LD	HL,(W12_PORT)
	CALL	@CONSOLE.DEC16
	LD	HL,MSG_DOTS
	CALL	@CONSOLE.STRING
	CALL	@TCPX.RESET
	XOR	A
	LD	HL,NET_TARGET_IP
	LD	BC,(W12_PORT)
	CALL	@TCPX.OPEN
	JP	C,TCP_OPEN_FAIL
	LD	HL,MSG_CONNECTED
	CALL	@CONSOLE.LINE
	CALL	BUILD_GET
	XOR	A
	LD	HL,S11_APP_BUFFER
	LD	BC,(W12_REQUEST_LENGTH)
	CALL	@TCPX.SEND
	JP	C,TCP_SEND_FAIL
	CALL	RESET_HOP_STATE

.RX_LOOP
	XOR	A
	LD	HL,S11_APP_BUFFER
	LD	BC,TCP_MSS
	LD	DE,HTTP_IDLE_MS
	CALL	@TCPX.RECV
	JR	C,.RX_END_OR_FAIL
	LD	HL,S11_APP_BUFFER
	CALL	PROCESS_CHUNK
	JP	C,FILE_FAIL
	LD	A,(W12_HOP_DONE)
	CP	2
	JP	Z,HTTP_FAIL
	CALL	BODY_COMPLETE
	JR	C,.RX_LOOP
	; The declared Content-Length has arrived, so the response is over by
	; its own framing. Waiting for a FIN here instead would stall for
	; HTTP_IDLE_MS and then report a receive timeout on a download that in
	; fact completed byte-exact -- "Connection: close" is only a request,
	; and an HTTP/1.1 server is entitled to keep the socket open.
	XOR	A
	CALL	@TCPX.CLOSE
	JR	.RESPONSE_DONE
.RX_END_OR_FAIL
	CP	TCP_ERR_CLOSED
	JR	Z,.PEER_CLOSED
	CP	NETDRV_ERR_CANCELLED
	JP	Z,USER_ABORT
	JP	TCP_RECV_FAIL
.PEER_CLOSED
	XOR	A
	CALL	@TCPX.CLOSE
.RESPONSE_DONE
	; A complete response always has a parsed status line and CRLFCRLF.
	LD	A,(W12_STATUS_SEEN)
	OR	A
	JP	Z,TCP_RECV_FAIL_PROTOCOL
	LD	A,(W12_HTTP_STATE)
	CP	4
	JP	NZ,TCP_RECV_FAIL_PROTOCOL
	LD	A,(W12_HOP_DONE)
	CP	2
	JP	Z,HTTP_FAIL
	CP	1
	JR	Z,.REDIRECT
	CALL	CHECK_CONTENT_COMPLETE
	JP	C,TCP_RECV_FAIL_PROTOCOL
	JP	DOWNLOAD_DONE
.REDIRECT
	LD	A,(W12_LOCATION_SEEN)
	OR	A
	JP	Z,REDIRECT_NO_LOCATION
	LD	A,(W12_REDIRECTS)
	CP	MAX_REDIRECTS
	JP	NC,REDIRECT_TOO_MANY
	INC	A
	LD	(W12_REDIRECTS),A
	LD	HL,W12_URL
	CALL	APPLY_REDIRECT
	JP	C,REDIRECT_BAD
	JP	HOP_LOOP

OPEN_LOCAL_FILE
	LD	A,(W12_FLAGS)
	BIT	1,A
	LD	A,2
	JR	NZ,.MODE
	LD	A,(W12_FLAGS)
	AND	1
.MODE
	LD	HL,(W12_OUTPUT_PTR)
	CALL	@FILE.OPEN_OUTPUT_ORC
	RET	C
	LD	(W12_FILE_HANDLE),A
	LD	(S9_TFTP_FILE_HANDLE),A
	LD	A,1
	LD	(W12_FILE_OPEN),A
	LD	(S9_TFTP_FILE_OPEN),A
	XOR	A
	RET

CLEAR_WGET_STATE
	LD	HL,W12_STATE_BASE
	LD	B,0x40
	XOR	A
.CLEAR
	LD	(HL),A
	INC	HL
	DJNZ	.CLEAR
	LD	A,0xFF
	LD	(W12_FILE_HANDLE),A
	RET

RESET_HOP_STATE
	XOR	A
	LD	HL,W12_HTTP_STATE
	LD	B,6
.CLEAR_HTTP
	LD	(HL),A
	INC	HL
	DJNZ	.CLEAR_HTTP
	LD	HL,W12_BUFFER_USED
	LD	B,10
.CLEAR_COUNTS
	LD	(HL),A
	INC	HL
	DJNZ	.CLEAR_COUNTS
	LD	(W12_LOCATION_SEEN),A
	LD	(W12_STATUS_SEEN),A
	LD	(W12_HOP_DONE),A
	RET

; Assemble GET, Host, optional Range, and Connection headers in the 544-byte
; application work area. TCPX restores this caller-owned payload on retries.
BUILD_GET
	LD	DE,S11_APP_BUFFER
	LD	HL,LIT_GET
	CALL	COPY_Z_EXCEPT_NUL
	LD	HL,W12_PATH
	CALL	COPY_Z_EXCEPT_NUL
	LD	HL,LIT_HTTP_HOST
	CALL	COPY_Z_EXCEPT_NUL
	LD	HL,W12_HOST
	CALL	COPY_Z_EXCEPT_NUL
	LD	HL,(W12_RESUME_OFFSET)
	LD	A,H
	OR	L
	LD	HL,(W12_RESUME_OFFSET+2)
	OR	H
	OR	L
	JR	Z,.NO_RANGE
	LD	HL,LIT_RANGE
	CALL	COPY_Z_EXCEPT_NUL
	PUSH	DE
	POP	IX
	LD	HL,(W12_RESUME_OFFSET)
	LD	DE,(W12_RESUME_OFFSET+2)
	CALL	FORMAT_DEC32
	PUSH	IX
	POP	DE
	LD	A,'-'
	LD	(DE),A
	INC	DE
.NO_RANGE
	LD	HL,LIT_REST
	CALL	COPY_Z_EXCEPT_NUL
	LD	HL,S11_APP_BUFFER
	EX	DE,HL
	OR	A
	SBC	HL,DE
	LD	(W12_REQUEST_LENGTH),HL
	RET

COPY_Z_EXCEPT_NUL
	LD	A,(HL)
	OR	A
	RET	Z
	LD	(DE),A
	INC	HL
	INC	DE
	JR	COPY_Z_EXCEPT_NUL

; Feed arbitrary TCP segmentation through a line capture and CRLFCRLF state
; machine. Body bytes are suppressed for redirects and non-2xx replies.
PROCESS_CHUNK
	LD	A,B
	OR	C
	RET	Z
	LD	A,(W12_HTTP_STATE)
	CP	4
	JR	Z,.BODY
.HEADER_LOOP
	LD	A,(HL)
	PUSH	HL,BC
	CALL	CAPTURE_HEADER_BYTE
	POP	BC,HL
	LD	A,(HL)
	CALL	HEADER_TRANSITION
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	RET	Z
	LD	A,(W12_HTTP_STATE)
	CP	4
	JR	NZ,.HEADER_LOOP
.BODY
	LD	A,(W12_HOP_DONE)
	OR	A
	JP	Z,APPEND_BODY
	; A redirect or error hop's body is thrown away rather than written,
	; but it still has to be COUNTED: that is what lets BODY_COMPLETE end
	; the hop on its declared Content-Length instead of waiting for a FIN
	; the server need never send. The counter is reset per hop
	; (RESET_HOP_STATE), so this cannot leak into the real download's total.
	PUSH	BC
	POP	DE
	LD	HL,W12_BODY_RECEIVED
	JP	ADD16_TO_32

; BODY_COMPLETE: CF=1 "keep receiving", CF=0 "this response is complete".
; Complete means the headers are over (state 4), the response declared a
; Content-Length, and at least that many body bytes have been counted.
; Without a declared length the body runs to the peer's close, which is the
; only end-of-body marker HTTP/1.0 gives such a response, so this answers
; "keep receiving" and .PEER_CLOSED does the deciding. Trashes A, DE, HL.
BODY_COMPLETE
	LD	A,(W12_HTTP_STATE)
	CP	4
	JR	NZ,.MORE
	LD	A,(W12_CONTENT_KNOWN)
	OR	A
	JR	Z,.MORE
	LD	HL,(W12_BODY_RECEIVED)
	LD	DE,(W12_CONTENT_LENGTH)
	OR	A
	SBC	HL,DE
	LD	HL,(W12_BODY_RECEIVED+2)
	LD	DE,(W12_CONTENT_LENGTH+2)
	SBC	HL,DE
	RET
.MORE
	SCF
	RET

CAPTURE_HEADER_BYTE
	LD	(W12_LAST_ERROR),A
	CP	10
	RET	Z
	CP	13
	JR	Z,.EOL
	LD	A,(W12_HEADER_LENGTH)
	CP	WGET_HEADER_SIZE-1
	JR	NC,.OVERFLOW
	LD	E,A
	LD	D,0
	LD	HL,W12_HEADER_LINE
	ADD	HL,DE
	LD	A,(W12_LAST_ERROR)
	LD	(HL),A
	LD	HL,W12_HEADER_LENGTH
	INC	(HL)
	RET
.OVERFLOW
	RET
.EOL
	LD	A,(W12_HEADER_LENGTH)
	LD	E,A
	LD	D,0
	LD	HL,W12_HEADER_LINE
	ADD	HL,DE
	LD	(HL),0
	LD	A,(W12_STATUS_SEEN)
	OR	A
	JR	NZ,.HEADER
	CALL	PARSE_STATUS_LINE
	LD	A,1
	LD	(W12_STATUS_SEEN),A
	JR	.RESET
.HEADER
	CALL	CHECK_LOCATION
	CALL	CHECK_CONTENT_LENGTH
.RESET
	XOR	A
	LD	(W12_HEADER_LENGTH),A
	RET
HEADER_TRANSITION
	LD	(W12_LAST_ERROR),A
	LD	A,(W12_HTTP_STATE)
	OR	A
	JR	Z,.S0
	CP	1
	JR	Z,.S1
	CP	2
	JR	Z,.S2
	CP	3
	JR	Z,.S3
	RET
.S0
	LD	A,(W12_LAST_ERROR)
	CP	13
	RET	NZ
	LD	A,1
	JR	.STORE
.S1
	LD	A,(W12_LAST_ERROR)
	CP	10
	LD	A,2
	JR	Z,.STORE
	LD	A,(W12_LAST_ERROR)
	CP	13
	LD	A,1
	JR	Z,.STORE
	XOR	A
	JR	.STORE
.S2
	LD	A,(W12_LAST_ERROR)
	CP	13
	LD	A,3
	JR	Z,.STORE
	XOR	A
	JR	.STORE
.S3
	LD	A,(W12_LAST_ERROR)
	CP	10
	LD	A,4
	JR	Z,.STORE
	LD	A,(W12_LAST_ERROR)
	CP	13
	LD	A,1
	JR	Z,.STORE
	XOR	A
.STORE
	LD	(W12_HTTP_STATE),A
	RET

PARSE_STATUS_LINE
	LD	HL,W12_HEADER_LINE
.SPACE
	LD	A,(HL)
	OR	A
	JP	Z,.BAD
	CP	' '
	JR	Z,.DIGIT_START
	INC	HL
	JR	.SPACE
.DIGIT_START
	INC	HL
	LD	DE,0
	LD	B,0
.DIGIT
	LD	A,(HL)
	SUB	'0'
	JR	C,.END
	CP	10
	JR	NC,.END
	INC	B
	LD	C,A
	PUSH	HL
	LD	H,D
	LD	L,E
	ADD	HL,HL
	LD	D,H
	LD	E,L
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	LD	D,0
	LD	E,C
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	INC	HL
	JR	.DIGIT
.END
	LD	A,B
	OR	A
	JP	Z,.BAD
	LD	(W12_STATUS),DE
	LD	A,D
	OR	A
	JR	Z,.CLASS_LOW
	CP	1
	JR	NZ,.NON_2XX
	LD	A,E
	CP	44
	JR	C,.SUCCESS		; 256..299
	CP	144
	JR	NC,.NON_2XX
	JR	.REDIRECT
.CLASS_LOW
	LD	A,E
	CP	200
	JR	C,.NON_2XX
	JR	.SUCCESS		; 200..255
.REDIRECT
	LD	A,1
	LD	(W12_HOP_DONE),A
	LD	HL,MSG_REDIRECT
	CALL	@CONSOLE.STRING
	LD	HL,W12_HEADER_LINE
	CALL	@CONSOLE.LINE
	RET
.SUCCESS
	LD	HL,(W12_RESUME_OFFSET)
	LD	A,H
	OR	L
	LD	HL,(W12_RESUME_OFFSET+2)
	OR	H
	OR	L
	RET	Z
	LD	HL,(W12_STATUS)
	LD	DE,206
	OR	A
	SBC	HL,DE
	RET	Z
	LD	HL,MSG_RANGE
	CALL	@CONSOLE.LINE
	LD	A,2
	LD	(W12_HOP_DONE),A
	RET
.BAD
.NON_2XX
	LD	HL,MSG_HTTP_ERROR
	CALL	@CONSOLE.STRING
	LD	HL,W12_HEADER_LINE
	CALL	@CONSOLE.LINE
	LD	A,2
	LD	(W12_HOP_DONE),A
	RET

CHECK_LOCATION
	LD	HL,W12_HEADER_LINE
	LD	DE,LIT_LOCATION
	CALL	PREFIX_CI
	RET	NZ
	CALL	SKIP_WHITE
	LD	DE,W12_URL
	LD	B,255
	CALL	COPY_BOUNDED_Z
	LD	A,1
	LD	(W12_LOCATION_SEEN),A
	RET

CHECK_CONTENT_LENGTH
	LD	HL,W12_HEADER_LINE
	LD	DE,LIT_CONTENT_LENGTH
	CALL	PREFIX_CI
	RET	NZ
	CALL	SKIP_WHITE
	CALL	PARSE_DEC32
	RET	C
	LD	(W12_CONTENT_LENGTH),HL
	LD	(W12_CONTENT_LENGTH+2),DE
	LD	A,1
	LD	(W12_CONTENT_KNOWN),A
	RET

PREFIX_CI
	LD	A,(DE)
	OR	A
	RET	Z
	LD	C,A
	LD	A,(HL)
	CALL	TOLOWER
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	JR	PREFIX_CI

SKIP_WHITE
	LD	A,(HL)
	CP	' '
	JR	Z,.NEXT
	CP	9
	RET	NZ
.NEXT
	INC	HL
	JR	SKIP_WHITE

COPY_BOUNDED_Z
	LD	A,B
	OR	A
	JR	Z,.TERM
	LD	A,(HL)
	OR	A
	JR	Z,.TERM
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	JR	COPY_BOUNDED_Z
.TERM
	XOR	A
	LD	(DE),A
	RET

; Append a chunk while preserving a truly continuous 8192-byte disk buffer.
APPEND_BODY
	LD	(W12_HEADER_BYTES),HL
	LD	(W12_REQUEST_LENGTH),BC
.LOOP
	LD	HL,(W12_REQUEST_LENGTH)
	LD	A,H
	OR	L
	RET	Z
	LD	DE,STAGE9_FILE_CAPACITY
	LD	HL,(W12_BUFFER_USED)
	EX	DE,HL
	OR	A
	SBC	HL,DE			; HL = free bytes
	LD	DE,(W12_REQUEST_LENGTH)
	OR	A
	SBC	HL,DE
	JR	C,.USE_FREE
	LD	BC,(W12_REQUEST_LENGTH)
	JR	.COPY
.USE_FREE
	ADD	HL,DE
	LD	B,H
	LD	C,L
.COPY
	PUSH	BC
	LD	HL,STAGE9_FILE_BUFFER
	LD	DE,(W12_BUFFER_USED)
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(W12_HEADER_BYTES)
	LDIR
	LD	(W12_HEADER_BYTES),HL
	POP	DE
	LD	HL,(W12_REQUEST_LENGTH)
	OR	A
	SBC	HL,DE
	LD	(W12_REQUEST_LENGTH),HL
	LD	HL,(W12_BUFFER_USED)
	ADD	HL,DE
	LD	(W12_BUFFER_USED),HL
	LD	HL,W12_BODY_RECEIVED
	CALL	ADD16_TO_32
	LD	HL,(W12_BUFFER_USED)
	LD	DE,STAGE9_FILE_CAPACITY
	OR	A
	SBC	HL,DE
	JR	NZ,.LOOP
	CALL	FLUSH_BUFFER
	RET	C
	JR	.LOOP

ADD16_TO_32
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	DEC	HL
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	RET	NC
	INC	HL
	INC	(HL)
	RET	NZ
	INC	HL
	INC	(HL)
	RET

FLUSH_BUFFER
	LD	HL,(W12_BUFFER_USED)
	LD	A,H
	OR	L
	RET	Z
	CALL	PROGRESS_TICK
	LD	HL,STAGE9_FILE_BUFFER
	LD	DE,(W12_BUFFER_USED)
	LD	A,(W12_FILE_HANDLE)
	LD	C,DSS_WRITE
	RST	DSS
	JR	C,.BAD
	LD	HL,0
	LD	(W12_BUFFER_USED),HL
	XOR	A
	RET
.BAD
	LD	A,NETDRV_ERR_FILE_IO
	SCF
	RET

; Error cleanup preserves the pending partial body without adding a late
; progress repaint after the already-printed diagnostic.
FLUSH_BUFFER_QUIET
	LD	DE,(W12_BUFFER_USED)
	LD	A,D
	OR	E
	RET	Z
	LD	HL,STAGE9_FILE_BUFFER
	LD	A,(W12_FILE_HANDLE)
	LD	C,DSS_WRITE
	RST	DSS
	RET	C
	LD	HL,0
	LD	(W12_BUFFER_USED),HL
	RET

CHECK_CONTENT_COMPLETE
	LD	A,(W12_CONTENT_KNOWN)
	OR	A
	RET	Z
	LD	HL,W12_CONTENT_LENGTH
	LD	DE,W12_BODY_RECEIVED
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.BAD
	INC	HL
	INC	DE
	DJNZ	.CMP
	OR	A
	RET
.BAD
	LD	A,NETDRV_ERR_PROTOCOL
	SCF
	RET

DOWNLOAD_DONE
	CALL	FLUSH_BUFFER
	JP	C,FILE_FAIL
	CALL	PRINT_PROGRESS
	CALL	CLOSE_OUTPUT
	JP	C,FILE_FAIL
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_DONE
	CALL	@CONSOLE.STRING
	LD	HL,(W12_BODY_RECEIVED)
	LD	DE,(W12_BODY_RECEIVED+2)
	CALL	PRINT_DEC32
	LD	HL,MSG_BYTES
	CALL	@CONSOLE.LINE
	CALL	TIME_REPORT
	JP	SUCCESS_NO_FILE

CLOSE_OUTPUT
	LD	A,(W12_FILE_OPEN)
	OR	A
	RET	Z
	LD	A,(W12_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	RET	C
	XOR	A
	LD	(W12_FILE_OPEN),A
	LD	(S9_TFTP_FILE_OPEN),A
	RET

; URL parser and redirect handling intentionally mirror sibling truncation and
; accepted forms: absolute http:// or a path beginning with '/'.
PARSE_URL
	LD	DE,URL_PREFIX
	LD	B,7
.PREFIX
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	OR	A
	JP	Z,.BAD
	CALL	TOLOWER
	CP	C
	JP	NZ,.BAD
	INC	HL
	INC	DE
	DJNZ	.PREFIX
	LD	DE,W12_HOST
	LD	B,63
.HOST
	LD	A,(HL)
	OR	A
	JR	Z,.HOST_END
	CP	':'
	JR	Z,.HOST_END
	CP	'/'
	JR	Z,.HOST_END
	LD	C,A
	LD	A,B
	OR	A
	JR	Z,.HOST_SKIP
	LD	A,C
	LD	(DE),A
	INC	DE
	DEC	B
.HOST_SKIP
	INC	HL
	JR	.HOST
.HOST_END
	XOR	A
	LD	(DE),A
	LD	DE,80
	LD	(W12_PORT),DE
	LD	A,(HL)
	OR	A
	JR	Z,.DEFAULT_PATH
	CP	'/'
	JR	Z,.COPY_PATH
	CP	':'
	JR	NZ,.BAD
	INC	HL
	LD	DE,0
	LD	B,0
.PORT
	LD	A,(HL)
	SUB	'0'
	JR	C,.PORT_END
	CP	10
	JR	NC,.PORT_END
	INC	B
	LD	C,A
	PUSH	HL
	EX	DE,HL
	ADD	HL,HL
	JR	C,.PORT_OVERFLOW
	LD	D,H
	LD	E,L
	ADD	HL,HL
	JR	C,.PORT_OVERFLOW
	ADD	HL,HL
	JR	C,.PORT_OVERFLOW
	ADD	HL,DE
	JR	C,.PORT_OVERFLOW
	LD	D,0
	LD	E,C
	ADD	HL,DE
	JR	C,.PORT_OVERFLOW
	EX	DE,HL
	POP	HL
	INC	HL
	JR	.PORT
.PORT_OVERFLOW
	POP	HL
	JR	.BAD
.PORT_END
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	(W12_PORT),DE
	LD	A,D
	OR	E
	JR	Z,.BAD
	LD	A,(HL)
	OR	A
	JR	Z,.DEFAULT_PATH
	CP	'/'
	JR	NZ,.BAD
.COPY_PATH
	LD	DE,W12_PATH
	LD	B,255
	CALL	COPY_BOUNDED_Z
	OR	A
	RET
.DEFAULT_PATH
	LD	HL,DEFAULT_PATH
	LD	DE,W12_PATH
	LD	BC,2
	LDIR
	OR	A
	RET
.BAD
	SCF
	RET

APPLY_REDIRECT
	PUSH	HL
	CALL	PARSE_URL
	POP	HL
	RET	NC
	PUSH	HL
	LD	DE,HTTPS_PREFIX
	CALL	PREFIX_CI
	POP	HL
	JR	NZ,.PATH
	LD	HL,MSG_HTTPS
	CALL	@CONSOLE.LINE
	LD	A,1
	SCF
	RET
.PATH
	LD	A,(HL)
	CP	'/'
	JR	NZ,.BAD
	LD	DE,W12_PATH
	LD	B,255
	CALL	COPY_BOUNDED_Z
	OR	A
	RET
.BAD
	SCF
	RET

DERIVE_OUTPUT
	LD	HL,W12_PATH
	CALL	@FILE.BASENAME
	LD	A,(HL)
	OR	A
	JR	NZ,.READY
	LD	HL,DEFAULT_OUTPUT
.READY
	LD	(W12_OUTPUT_PTR),HL
	RET

TOLOWER
	CP	'A'
	RET	C
	CP	'Z'+1
	RET	NC
	ADD	A,'a'-'A'
	RET

PRINT_IPV4
	LD	B,4
.IP
	LD	A,(HL)
	CALL	@CONSOLE.DEC8
	INC	HL
	DEC	B
	RET	Z
	LD	A,'.'
	CALL	@CONSOLE.CHAR
	JR	.IP

; 32-bit decimal helpers use only W12_WORK32 and the Z80 stack.
PRINT_DEC32
	LD	IX,W12_NUMBER_BUFFER
	CALL	FORMAT_DEC32
	LD	(IX+0),0
	LD	HL,W12_NUMBER_BUFFER
	JP	@CONSOLE.STRING

FORMAT_DEC32
	LD	(W12_WORK32),HL
	LD	(W12_WORK32+2),DE
	LD	A,H
	OR	L
	OR	D
	OR	E
	JR	NZ,.NONZERO
	LD	(IX+0),'0'
	INC	IX
	RET
.NONZERO
	LD	B,0
.DIVIDE
	PUSH	BC
	CALL	DIV32_10
	POP	BC
	ADD	A,'0'
	PUSH	AF
	INC	B
	LD	HL,(W12_WORK32)
	LD	A,H
	OR	L
	LD	HL,(W12_WORK32+2)
	OR	H
	OR	L
	JR	NZ,.DIVIDE
.WRITE
	POP	AF
	LD	(IX+0),A
	INC	IX
	DJNZ	.WRITE
	RET

DIV32_10
	LD	HL,0
	LD	B,32
.BIT
	PUSH	HL
	LD	HL,W12_WORK32
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	POP	HL
	ADC	HL,HL
	LD	A,L
	CP	10
	JR	C,.NEXT
	SUB	10
	LD	L,A
	PUSH	HL
	LD	HL,W12_WORK32
	SET	0,(HL)
	POP	HL
.NEXT
	DJNZ	.BIT
	LD	A,L
	RET

PARSE_DEC32
	CALL	SKIP_WHITE
	LD	DE,0
	LD	(W12_WORK32),DE
	LD	(W12_WORK32+2),DE
	LD	B,0
.NEXT
	LD	A,(HL)
	SUB	'0'
	JR	C,.DONE
	CP	10
	JR	NC,.DONE
	INC	B
	LD	C,A
	PUSH	HL
	CALL	MUL_WORK32_10
	LD	A,(W12_WORK32)
	ADD	A,C
	LD	(W12_WORK32),A
	JR	NC,.NO_CARRY
	LD	HL,W12_WORK32+1
	INC	(HL)
	JR	NZ,.NO_CARRY
	INC	HL
	INC	(HL)
	JR	NZ,.NO_CARRY
	INC	HL
	INC	(HL)
.NO_CARRY
	POP	HL
	INC	HL
	JR	.NEXT
.DONE
	LD	A,B
	OR	A
	JR	Z,.BAD
	LD	HL,(W12_WORK32)
	LD	DE,(W12_WORK32+2)
	OR	A
	RET
.BAD
	SCF
	RET

MUL_WORK32_10
	CALL	SHIFT_WORK32		; 2x, retained as the addend
	LD	HL,(W12_WORK32)
	LD	DE,(W12_WORK32+2)
	LD	(W12_CONTENT_LENGTH),HL
	LD	(W12_CONTENT_LENGTH+2),DE
	CALL	SHIFT_WORK32		; 4x
	CALL	SHIFT_WORK32		; 8x
	LD	HL,(W12_WORK32)
	LD	DE,(W12_CONTENT_LENGTH)
	ADD	HL,DE
	LD	(W12_WORK32),HL
	LD	HL,(W12_WORK32+2)
	LD	DE,(W12_CONTENT_LENGTH+2)
	ADC	HL,DE
	LD	(W12_WORK32+2),HL
	RET

SHIFT_WORK32
	LD	HL,W12_WORK32
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	RET

; PROGRESS_TICK is called once per disk-buffer flush, so the counter it keeps is
; a count of flushes. Repainting on every one puts an update on screen each
; buffer -- a few KiB -- which is what makes a download look like it is
; progressing. Printing every fourth flush instead meant one repaint per four
; buffers, so a transfer showed two or three figures for its whole length and
; read as a stall between them; the repaint itself is a carriage return and one
; short line, nothing against the disk write that precedes it.
PROGRESS_TICK
	LD	A,(W12_FLAGS)
	BIT	2,A
	JR	NZ,.DOT
	CALL	PRINT_PROGRESS
	LD	HL,W12_PROGRESS_COUNT
	INC	(HL)
	RET
.DOT
	LD	A,'.'
	JP	@CONSOLE.CHAR

PRINT_PROGRESS
	LD	A,(W12_FLAGS)
	BIT	2,A
	RET	NZ
	LD	A,13
	CALL	@CONSOLE.CHAR
	LD	HL,(W12_BODY_RECEIVED)
	LD	DE,(W12_RESUME_OFFSET)
	ADD	HL,DE
	LD	(W12_TOTAL_WRITTEN),HL
	LD	HL,(W12_BODY_RECEIVED+2)
	LD	DE,(W12_RESUME_OFFSET+2)
	ADC	HL,DE
	LD	(W12_TOTAL_WRITTEN+2),HL
	LD	HL,W12_TOTAL_WRITTEN
	CALL	PRINT_KB
	LD	HL,MSG_PROGRESS_MID
	CALL	@CONSOLE.STRING
	LD	A,(W12_CONTENT_KNOWN)
	OR	A
	JR	Z,.UNKNOWN
	LD	HL,(W12_CONTENT_LENGTH)
	LD	DE,(W12_CONTENT_LENGTH+2)
	LD	A,H
	OR	L
	OR	D
	OR	E
	JR	Z,.UNKNOWN		; sibling represents Content-Length: 0 as '?'
	LD	DE,(W12_RESUME_OFFSET)
	ADD	HL,DE
	LD	(W12_TOTAL_WRITTEN),HL
	LD	HL,(W12_CONTENT_LENGTH+2)
	LD	DE,(W12_RESUME_OFFSET+2)
	ADC	HL,DE
	LD	(W12_TOTAL_WRITTEN+2),HL
	LD	HL,W12_TOTAL_WRITTEN
	CALL	PRINT_KB
	JR	.TAIL
.UNKNOWN
	LD	A,'?'
	CALL	@CONSOLE.CHAR
.TAIL
	LD	HL,MSG_PROGRESS_KB
	JP	@CONSOLE.STRING

PRINT_KB
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,(HL)
	EX	DE,HL
	LD	E,A
	SRL	E
	RR	H
	RR	L
	SRL	E
	RR	H
	RR	L
	LD	D,0
	JP	PRINT_DEC32

TIME_START
	CALL	TIME_NOW
	LD	(W12_START_TIME),HL
	LD	A,B
	LD	(W12_START_TIME+2),A
	RET

TIME_NOW
	PUSH	IX
	LD	C,DSS_SYSTIME
	RST	DSS
	PUSH	BC,HL
	LD	HL,0
	LD	(W12_WORK32),HL
	LD	(W12_WORK32+2),HL
	POP	DE
	PUSH	DE
	LD	A,D
	OR	A
	JR	Z,.MINUTES
	LD	B,A
.HOUR_LOOP
	LD	HL,(W12_WORK32)
	LD	DE,3600
	ADD	HL,DE
	LD	(W12_WORK32),HL
	JR	NC,.HOUR_NEXT
	LD	HL,W12_WORK32+2
	INC	(HL)
.HOUR_NEXT
	DJNZ	.HOUR_LOOP
.MINUTES
	POP	DE
	LD	A,E
	OR	A
	JR	Z,.SECONDS
	LD	B,A
.MIN_LOOP
	LD	HL,(W12_WORK32)
	LD	DE,60
	ADD	HL,DE
	LD	(W12_WORK32),HL
	JR	NC,.MIN_NEXT
	LD	HL,W12_WORK32+2
	INC	(HL)
.MIN_NEXT
	DJNZ	.MIN_LOOP
.SECONDS
	POP	BC
	LD	HL,(W12_WORK32)
	LD	D,0
	LD	E,B
	ADD	HL,DE
	LD	A,(W12_WORK32+2)
	LD	B,A
	JR	NC,.NOW_DONE
	INC	B
.NOW_DONE
	POP	IX
	RET

TIME_REPORT
	CALL	TIME_NOW
	LD	DE,(W12_START_TIME)
	OR	A
	SBC	HL,DE
	LD	A,(W12_START_TIME+2)
	LD	E,A
	LD	A,B
	SBC	A,E
	LD	B,A
	JR	NC,.NO_WRAP
	LD	DE,0x5180
	ADD	HL,DE
	LD	A,B
	ADC	A,1
	LD	B,A
.NO_WRAP
	LD	(W12_ELAPSED),HL
	LD	A,B
	LD	(W12_ELAPSED+2),A
	LD	HL,MSG_SUMMARY_PREFIX
	CALL	@CONSOLE.STRING
	LD	HL,(W12_BODY_RECEIVED)
	LD	DE,(W12_BODY_RECEIVED+2)
	CALL	PRINT_DEC32
	LD	HL,MSG_SUMMARY_BYTES
	CALL	@CONSOLE.STRING
	LD	HL,(W12_ELAPSED)
	LD	A,(W12_ELAPSED+2)
	LD	E,A
	LD	D,0
	CALL	PRINT_DEC32
	LD	HL,MSG_SUMMARY_SEC
	CALL	@CONSOLE.STRING
	LD	A,(W12_ELAPSED+2)
	OR	A
	JR	NZ,.NEWLINE
	LD	DE,(W12_ELAPSED)
	LD	A,D
	OR	E
	JR	Z,.NEWLINE
	LD	HL,(W12_BODY_RECEIVED)
	LD	(W12_WORK32),HL
	LD	HL,(W12_BODY_RECEIVED+2)
	LD	(W12_WORK32+2),HL
	CALL	DIV32_BY_DE
	LD	HL,MSG_COMMA
	CALL	@CONSOLE.STRING
	LD	HL,(W12_WORK32+2)
	LD	A,H
	OR	L
	JR	NZ,.KB_RATE
	LD	HL,(W12_WORK32)
	LD	A,H
	CP	4
	JR	NC,.KB_RATE
	LD	DE,(W12_WORK32+2)
	CALL	PRINT_DEC32
	LD	HL,MSG_BPS
	JR	.RATE_SUFFIX
.KB_RATE
	LD	HL,W12_WORK32
	CALL	SHIFT_RIGHT_10
	CALL	PRINT_DEC32
	LD	HL,MSG_KBPS
.RATE_SUFFIX
	CALL	@CONSOLE.STRING
.NEWLINE
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

DIV32_BY_DE
	LD	HL,0
	LD	B,32
.DIV_LOOP
	PUSH	HL
	LD	HL,W12_WORK32
	SLA	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	INC	HL
	RL	(HL)
	POP	HL
	ADC	HL,HL
	JR	C,.SUB_FORCE
	OR	A
	SBC	HL,DE
	JR	C,.RESTORE
	JR	.SET
.SUB_FORCE
	OR	A
	SBC	HL,DE
.SET
	PUSH	HL
	LD	HL,W12_WORK32
	SET	0,(HL)
	POP	HL
	JR	.NEXT
.RESTORE
	ADD	HL,DE
.NEXT
	DJNZ	.DIV_LOOP
	RET

SHIFT_RIGHT_10
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,(HL)
	EX	DE,HL
	LD	E,A
	SRL	E
	RR	H
	RR	L
	SRL	E
	RR	H
	RR	L
	LD	D,0
	RET

DELETE_FRESH_OUTPUT
	LD	A,(W12_RESUME_SELECTED)
	OR	A
	RET	NZ
	LD	HL,(W12_OUTPUT_PTR)
	LD	C,DSS_DELETE
	RST	DSS
	RET

HTTP_FAIL
	LD	HL,0
	LD	(W12_BUFFER_USED),HL
	CALL	CLOSE_OUTPUT
	CALL	DELETE_FRESH_OUTPUT
	XOR	A
	CALL	@TCPX.ABORT
	LD	B,DSS_EXIT_REMOTE
	JP	FAIL_EXIT

REDIRECT_NO_LOCATION
	LD	HL,MSG_NO_LOCATION
	CALL	@CONSOLE.LINE
	JP	HTTP_FAIL
REDIRECT_BAD
	CP	1
	JP	Z,HTTP_FAIL
	LD	HL,MSG_BAD_LOCATION
	CALL	@CONSOLE.LINE
	JP	HTTP_FAIL
REDIRECT_TOO_MANY
	LD	HL,MSG_TOO_MANY
	CALL	@CONSOLE.LINE
	JP	HTTP_FAIL

TCP_OPEN_FAIL
	CP	NETDRV_ERR_CANCELLED
	JP	Z,USER_ABORT
	LD	(W12_LAST_ERROR),A
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_TCP_OPEN
	JR	TCP_COMMON_FAIL
TCP_SEND_FAIL
	CP	NETDRV_ERR_CANCELLED
	JP	Z,USER_ABORT
	LD	(W12_LAST_ERROR),A
	LD	HL,MSG_TCP_SEND
	JR	TCP_COMMON_FAIL
TCP_RECV_FAIL_PROTOCOL
	LD	A,NETDRV_ERR_PROTOCOL
TCP_RECV_FAIL
	LD	(W12_LAST_ERROR),A
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_TCP_RECV
TCP_COMMON_FAIL
	CALL	@CONSOLE.STRING
	LD	A,(W12_LAST_ERROR)
	CALL	@CONSOLE.HEX8
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	CALL	PRINT_REGS
	JP	NETWORK_PRESERVE

RESOLVE_FAIL
	CP	NETDRV_ERR_CANCELLED
	JP	Z,USER_ABORT
	LD	HL,MSG_RESOLVE
	CALL	@CONSOLE.LINE
	JP	NETWORK_PRESERVE
NETWORK_PRESERVE
	CALL	FLUSH_BUFFER_QUIET
	CALL	CLOSE_OUTPUT
	LD	B,DSS_EXIT_NETWORK
	JP	FAIL_EXIT

USER_ABORT
	CALL	FLUSH_BUFFER
	CALL	PRINT_PROGRESS
	CALL	CLOSE_OUTPUT
	XOR	A
	CALL	@TCPX.ABORT
	LD	HL,@CONSOLE.CRLF
	CALL	@CONSOLE.STRING
	LD	HL,MSG_ABORT_TRANSFER
	CALL	@CONSOLE.LINE
	LD	B,DSS_EXIT_CANCELLED
	JP	FAIL_EXIT

PRINT_REGS
	LD	HL,MSG_REGS
	CALL	@CONSOLE.STRING
	LD	A,(NETDRV_SELECTED_SLOT)
	CALL	@CONSOLE.DEC8
	LD	HL,MSG_BASE
	CALL	@CONSOLE.STRING
	LD	HL,(NETDRV_SELECTED_BASE)
	CALL	@CONSOLE.HEX16
	LD	HL,MSG_STATUS
	CALL	@CONSOLE.STRING
	LD	A,(W12_LAST_ERROR)
	CALL	@CONSOLE.HEX8
	LD	HL,@CONSOLE.CRLF
	JP	@CONSOLE.STRING

FILE_FAIL
	CALL	CLOSE_OUTPUT
	LD	HL,MSG_FILE
	CALL	@CONSOLE.LINE
	LD	B,DSS_EXIT_LOCAL
	JP	FAIL_EXIT
CONFIG_FAIL
	LD	B,DSS_EXIT_CONFIG
	JP	FAIL_EXIT
HARDWARE_FAIL
	LD	B,DSS_EXIT_HARDWARE
	JP	FAIL_EXIT
PROMPT_CANCEL
	LD	B,DSS_EXIT_CANCELLED
	JP	EXIT_NO_RESULT
USAGE_FAIL
	LD	HL,MSG_USAGE_ERROR
	CALL	@CONSOLE.LINE
	LD	HL,MSG_HELP
	CALL	@CONSOLE.STRING
	LD	B,DSS_EXIT_ARGUMENT
	JP	FAIL_EXIT

SUCCESS_NO_FILE
	LD	HL,MSG_OK
	CALL	@CONSOLE.STRING
	LD	B,DSS_EXIT_OK
	JR	EXIT_NO_RESULT
FAIL_EXIT
	PUSH	BC
	LD	HL,MSG_FAIL
	CALL	@CONSOLE.STRING
	POP	BC
EXIT_NO_RESULT
	LD	A,B
	LD	(SAVED_EXIT_CODE),A
	LD	A,(S9_TFTP_FILE_OPEN)
	OR	A
	JR	Z,.DRIVER
	LD	A,(S9_TFTP_FILE_HANDLE)
	LD	C,DSS_CLOSE_FILE
	RST	DSS
.DRIVER
	CALL	@NETDRV.DONE
	IFNDEF STAGE12_LAYOUT
	; The runtime stack is inside the block about to be released, so go back to
	; the entry stack first. Nothing prints from here on, which is what makes a
	; WIN1 stack safe again.
	LD	A,(NETDRV_MEMORY_BLOCK)
	LD	SP,S10_BOOTSTRAP_STACK
	LD	C,DSS_FREEMEM
	RST	DSS
	ENDIF
	LD	A,(SAVED_EXIT_CODE)
	LD	B,A
	LD	C,DSS_EXIT
	RST	DSS

; Deliberately silent: reached only when the page claim failed, so the stack is
; still in WIN1 and a console line that scrolls would take BIOS WIN_MOVE through
; a POP off the video page. The exit status is the whole report.
BOOT_FAIL
	DSS_RETURN DSS_EXIT_LOCAL

LIT_GET	DB "GET ",0
LIT_HTTP_HOST	DB " HTTP/1.0",13,10,"Host: ",0
LIT_RANGE	DB 13,10,"Range: bytes=",0
LIT_REST	DB 13,10,"Connection: close",13,10,13,10,0
LIT_LOCATION	DB "location:",0
LIT_CONTENT_LENGTH DB "content-length:",0
URL_PREFIX	DB "http://"
HTTPS_PREFIX	DB "https://",0
DEFAULT_PATH	DB "/",0
DEFAULT_OUTPUT	DB "OUTPUT.BIN",0

MSG_BANNER	DB "3C509B WGET v",PACKAGE_VERSION,0
MSG_RESOLVED	DB "Resolved ",0
MSG_TO		DB " -> ",0
MSG_PORT	DB " port ",0
MSG_CONNECTING	DB "Connecting to ",0
MSG_DOTS	DB "...",0
MSG_CONNECTED	DB "ESTABLISHED.",0
MSG_REDIRECT	DB "Redirect: ",0
MSG_HTTP_ERROR	DB "[E] ",0
MSG_RANGE	DB "[E] server ignored Range (no resume). Rerun without -r.",0
MSG_NO_LOCATION DB "[E] redirect with no Location header",0
MSG_BAD_LOCATION DB "[E] cannot parse redirect Location",0
MSG_TOO_MANY	DB "[E] too many redirects (cap = 5)",0
MSG_HTTPS	DB "[E] redirect to https:// is not supported (no TLS).",0
MSG_RESOLVE	DB "[E] could not resolve host.",0
MSG_FILE	DB "[E] file create/write failed.",0
MSG_TCP_OPEN	DB "TCP connect failed, code 0x",0
MSG_TCP_SEND	DB "TCP send failed, code 0x",0
MSG_TCP_RECV	DB "TCP recv failed, code 0x",0
MSG_ABORT_TRANSFER DB "Aborted by user (Esc/Ctrl+C).",0
MSG_DONE	DB "Done. ",0
MSG_BYTES	DB " bytes received.",0
MSG_PROGRESS_MID DB "KB / ",0
MSG_PROGRESS_KB DB "KB",0
MSG_SUMMARY_PREFIX DB "  ",0
MSG_SUMMARY_BYTES DB " bytes in ",0
MSG_SUMMARY_SEC DB " sec",0
MSG_COMMA	DB ", ",0
MSG_KBPS	DB " KB/s",0
MSG_BPS	DB " B/s",0
MSG_REGS	DB "REGS slot=",0
MSG_BASE	DB " base=",0
MSG_STATUS	DB " status=",0
MSG_USAGE_ERROR DB "[E] usage: missing or invalid URL",0
MSG_HELP
	DB "Usage:",13,10
	DB "  WGET url [-o output] [-y|-f] [-r] [-d]",13,10
	DB "  WGET /?",13,10,13,10
	DB "  url     http://host[:port][/path]",13,10
	DB "  -o file write body to <file> (default: derived from URL).",13,10
	DB "  -y, -f  overwrite local file without prompt.",13,10
	DB "  -r      resume: append to <file>, request Range from server.",13,10
	DB "  -d      dot progress instead of the KB counter (less",13,10
	DB "          console work, use it to compare throughput).",13,10,0
MSG_OK		DB "RESULT OK",13,10,0
MSG_FAIL	DB "RESULT FAIL",13,10,0

; Bottom of the command staging area, long dead by exit time: the command itself
; is copied into the runtime area by ALLOCATE_FRESH. It sits below the load
; address in WIN1, so it is the one cell that survives whatever the exit path
; does to the windows -- which is why the exit code is kept here and not in the
; runtime data area.
SAVED_EXIT_CODE EQU S10_COMMAND_BUFFER

	ENDMODULE

	INCLUDE "el3_algorithms.asm"
	INCLUDE "console.asm"
	INCLUDE "isa.asm"
	INCLUDE "el3_io.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
	INCLUDE "el3.asm"
	INCLUDE "netdrv.asm"
	INCLUDE "ethernet.asm"
	INCLUDE "../lib/arp.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "tcp.asm"
	INCLUDE "stage9_app.asm"
	INCLUDE "nettime.asm"
	INCLUDE "file.asm"
	INCLUDE "stage9_cli.asm"
	INCLUDE "tcp_transport.asm"
	INCLUDE "stage11_app.asm"
	INCLUDE "stage12_dns.asm"



	; The image is code and rodata only. What bounds it is the runtime data
	; area, which starts at PAGE_BASE -- not the entry stack, which now sits a
	; whole window above at the top of WIN2.
	ASSERT $ <= PAGE_BASE
	; ... and the command record and exit code below the load address are not
	; code either.
	ASSERT S10_COMMAND_BUFFER + 0x0100 <= 0x4100
