; Deterministic vectors for the shared DLSPEED/DLDIRECT HTTP parser.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "http_stream.inc"

HTTP_STATE_VAR		EQU 0x8000
HTTP_STATUS_VAR		EQU 0x8001
HTTP_HEADER_LENGTH_VAR	EQU 0x8003
HTTP_CONTENT_KNOWN_VAR	EQU 0x8004
HTTP_CONTENT_LENGTH_VAR	EQU 0x8005
HTTP_BODY_RECEIVED_VAR	EQU 0x8009
HTTP_WORK32_VAR		EQU 0x800D
HTTP_ERROR_VAR		EQU 0x8011
HTTP_STATUS_SEEN_VAR	EQU 0x8012
HTTP_HEADER_LINE_VAR	EQU 0x8020

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001
STACK_TOP	EQU 0xBFF0

	MACRO CASE value
	LD A,value
	LD (TEST_RESULT),A
	ENDM
	MACRO FEED source,count
	LD HL,source
	LD BC,count
	CALL @HTTPSTREAM.PROCESS
	ENDM

	ORG 0x4000
TEST_START
	LD	SP,STACK_TOP
	XOR	A
	LD	(TEST_COMPLETE),A

	; Header boundaries are deliberately split across field text and every
	; CR/LF transition. Count exactly Content-Length and ignore pipelined tail.
	CASE 1
	CALL	@HTTPSTREAM.RESET
	FEED	R1A,R1A_LEN
	FEED	R1B,R1B_LEN
	FEED	R1C,R1C_LEN
	FEED	R1D,R1D_LEN
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	JP	NZ,FAIL
	CALL	@HTTPSTREAM.BODY_COMPLETE
	JP	C,FAIL
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	LD	DE,5
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL

	; Decimal overflow must be rejected, not wrapped to a small body length.
	CASE 8
	CALL	@HTTPSTREAM.RESET
	FEED	R8,R8_LEN
	LD	A,(HTTP_ERROR_VAR)
	CP	HTTP_ERR_HEADER
	JP	NZ,FAIL

	; A 2xx-looking token on a non-HTTP status line is not a valid response.
	CASE 9
	CALL	@HTTPSTREAM.RESET
	FEED	R9,R9_LEN
	LD	A,(HTTP_ERROR_VAR)
	CP	HTTP_ERR_STATUS
	JP	NZ,FAIL

	; An explicitly present but empty encoding field is malformed framing.
	CASE 10
	CALL	@HTTPSTREAM.RESET
	FEED	R10,R10_LEN
	LD	A,(HTTP_ERROR_VAR)
	CP	HTTP_ERR_UNSUPPORTED
	JP	NZ,FAIL

	; Close-delimited is valid but never complete until the caller observes FIN.
	CASE 2
	CALL	@HTTPSTREAM.RESET
	FEED	R2,R2_LEN
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	JP	NZ,FAIL
	CALL	@HTTPSTREAM.BODY_COMPLETE
	JP	NC,FAIL
	LD	A,(HTTP_CONTENT_KNOWN_VAR)
	OR	A
	JP	NZ,FAIL
	LD	HL,(HTTP_BODY_RECEIVED_VAR)
	LD	DE,4
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL

	; Declared ten, received four: caller must classify peer close as truncation.
	CASE 3
	CALL	@HTTPSTREAM.RESET
	FEED	R3,R3_LEN
	CALL	@HTTPSTREAM.BODY_COMPLETE
	JP	NC,FAIL

	CASE 4
	CALL	@HTTPSTREAM.RESET
	FEED	R4,R4_LEN
	LD	A,(HTTP_ERROR_VAR)
	CP	HTTP_ERR_STATUS
	JP	NZ,FAIL

	CASE 5
	CALL	@HTTPSTREAM.RESET
	FEED	R5,R5_LEN
	LD	A,(HTTP_ERROR_VAR)
	CP	HTTP_ERR_UNSUPPORTED
	JP	NZ,FAIL

	CASE 6
	CALL	@HTTPSTREAM.RESET
	FEED	R6,R6_LEN
	LD	A,(HTTP_ERROR_VAR)
	CP	HTTP_ERR_UNSUPPORTED
	JP	NZ,FAIL

	CASE 7
	CALL	@HTTPSTREAM.RESET
	FEED	R7,R7_LEN
	LD	A,(HTTP_ERROR_VAR)
	OR	A
	JP	NZ,FAIL
	CALL	@HTTPSTREAM.BODY_COMPLETE
	JP	C,FAIL
	LD	HL,(HTTP_STATUS_VAR)
	LD	DE,299
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL

PASS
	XOR	A
	LD	(TEST_RESULT),A
FAIL
	LD	A,0xA5
	LD	(TEST_COMPLETE),A
TEST_DONE
	HALT

R1A	DB "HTTP/1.0 200 OK",13
R1A_LEN EQU $-R1A
R1B	DB 10,"CONTENT-LEN"
R1B_LEN EQU $-R1B
R1C	DB "GTH:",9,"5",13,10,13
R1C_LEN EQU $-R1C
R1D	DB 10,"helloEXTRA"
R1D_LEN EQU $-R1D
R2	DB "HTTP/1.0 204 No Content",13,10,13,10,"body"
R2_LEN EQU $-R2
R3	DB "HTTP/1.0 200 OK",13,10,"Content-Length: 10",13,10,13,10,"four"
R3_LEN EQU $-R3
R4	DB "HTTP/1.0 404 Not Found",13,10,"Content-Length: 0",13,10,13,10
R4_LEN EQU $-R4
R5	DB "HTTP/1.1 200 OK",13,10,"Transfer-Encoding: chunked",13,10,13,10,"0",13,10,13,10
R5_LEN EQU $-R5
R6	DB "HTTP/1.0 200 OK",13,10,"Content-Encoding: gzip",13,10,"Content-Length: 4",13,10,13,10,"gzip"
R6_LEN EQU $-R6
R7	DB "HTTP/1.1 299 Fine",13,10,"Content-Encoding: identity",13,10,"Content-Length: 0",13,10,13,10
R7_LEN EQU $-R7
R8	DB "HTTP/1.1 200 OK",13,10,"Content-Length: 4294967296",13,10,13,10
R8_LEN EQU $-R8
R9	DB "NOTHTTP 200 OK",13,10,"Content-Length: 0",13,10,13,10
R9_LEN EQU $-R9
R10	DB "HTTP/1.1 200 OK",13,10,"Transfer-Encoding:",13,10,13,10
R10_LEN EQU $-R10

	INCLUDE "http_stream.asm"
	END TEST_START
