; Executable NETDRV ABI and caller-buffer boundary vectors.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "el3.inc"
	INCLUDE "memory.inc"
	INCLUDE "netdrv.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001

	ORG 0x4000
TEST_START
	LD	SP,STACK_TOP
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	; Ordinary low memory is valid unless occupied by a WIN1 DLL.
	LD	HL,0x4000
	LD	BC,0x0800
	CALL	@NETDRV.VALIDATE_BUFFER
	IF NETDRV_DLL_WINDOW = NETDRV_DLL_WIN1
		JP	NC,FAIL_1
		CP	NETDRV_ERR_PARAMETER
		JP	NZ,FAIL_1
	ELSE
		JP	C,FAIL_1
	ENDIF

	; WIN2 is rejected only when that is the future DLL load window.
	LD	HL,0x8000
	LD	BC,0x0100
	CALL	@NETDRV.VALIDATE_BUFFER
	IF NETDRV_DLL_WINDOW = NETDRV_DLL_WIN2
		JP	NC,FAIL_2
		CP	NETDRV_ERR_PARAMETER
		JP	NZ,FAIL_2
	ELSE
		JP	C,FAIL_2
	ENDIF

	; CALL has already pushed its return address: BEEE is exactly SP-256.
	IF NETDRV_DLL_WINDOW < NETDRV_DLL_WIN2
		LD	HL,0xBEED
		LD	BC,1
		CALL	@NETDRV.VALIDATE_BUFFER
		JP	C,FAIL_3
		LD	HL,0xBEEE
		LD	BC,1
		CALL	EXPECT_PARAMETER
		JP	C,FAIL_3
	ENDIF

	LD	HL,0xC000
	LD	BC,1
	CALL	EXPECT_PARAMETER
	JP	C,FAIL_4
	LD	HL,0xFFF0
	LD	BC,0x20
	CALL	EXPECT_PARAMETER
	JP	C,FAIL_4
	LD	HL,0x4000
	LD	BC,0
	CALL	EXPECT_PARAMETER
	JP	C,FAIL_4

	; Every public wrapper preserves both index registers.
	IF NETDRV_DLL_WINDOW = NETDRV_DLL_WIN1
		LD	HL,0x8000
	ELSE
		LD	HL,0x4000
	ENDIF
	LD	BC,60
	LD	IX,0xA55A
	LD	IY,0x5AA5
	CALL	@NETDRV.SEND_FRAME
	JP	C,FAIL_5
	PUSH	IX
	POP	HL
	LD	DE,0xA55A
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5
	PUSH	IY
	POP	HL
	LD	DE,0x5AA5
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5

	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

; Converts the expected NETDRV parameter failure into CF=0.
EXPECT_PARAMETER
	CALL	@NETDRV.VALIDATE_BUFFER
	RET	NC
	CP	NETDRV_ERR_PARAMETER
	JR	NZ,.BAD
	OR	A
	RET
.BAD
	SCF
	RET

FAIL_1:	LD A,1
	JR FAIL
FAIL_2:	LD A,2
	JR FAIL
FAIL_3:	LD A,3
	JR FAIL
FAIL_4:	LD A,4
	JR FAIL
FAIL_5:	LD A,5
FAIL:	LD (TEST_RESULT),A
TEST_DONE
	NOP

	MODULE EL3
CONFIGURE:	XOR A
	RET
DISCOVER:	XOR A
	RET
ACTIVATE:	XOR A
	RET
INIT:		XOR A
	RET
DONE:		XOR A
	RET
SEND_FRAME:	LD IX,0x1111
	LD IY,0x2222
	XOR A
	RET
RX_PENDING:	XOR A
	RET
READ_FRAME:	XOR A
	RET
DISCARD_FRAME:	XOR A
	RET
SNAPSHOT:	XOR A
	RET
LINK_STATE:	XOR A
	RET
WAIT_LINK_UP:	XOR A
	RET
	ENDMODULE

	INCLUDE "../src/lib/netdrv.asm"
