; Executable IPv4/ICMP codec vectors for z88dk-ticks.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001
WORK		EQU 0x8000
DESC4B		EQU 0x8F00
DESC4P		EQU 0x8F20
DESCIB		EQU 0x8F40
DESCIR		EQU 0x8F60
UNREACH		EQU 0x8800

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	; Payload 0, network byte order and IX/IY preservation.
	LD	HL,0
	CALL	BUILD_ICMP_REQUEST
	JP	C,FAIL_1
	LD	A,B
	OR	A
	JP	NZ,FAIL_1
	LD	A,C
	CP	8
	JP	NZ,FAIL_1
	LD	A,(WORK+0)
	CP	8
	JP	NZ,FAIL_1
	LD	A,(WORK+4)
	CP	0x50
	JP	NZ,FAIL_1
	LD	A,(WORK+5)
	CP	0x9B
	JP	NZ,FAIL_1
	LD	A,(WORK+6)
	CP	0xFF
	JP	NZ,FAIL_1
	LD	A,(WORK+7)
	CP	0xFF
	JP	NZ,FAIL_1
	LD	HL,WORK
	LD	BC,8
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,FAIL_1

	; Odd payload and deterministic pattern.
	LD	HL,1
	CALL	BUILD_ICMP_REQUEST
	JP	C,FAIL_2
	LD	A,(WORK+8)
	OR	A
	JP	NZ,FAIL_2
	LD	HL,WORK
	LD	BC,9
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,FAIL_2

	LD	HL,32
	CALL	BUILD_ICMP_REQUEST
	JP	C,FAIL_3
	LD	A,(WORK+39)
	CP	31
	JP	NZ,FAIL_3

	; Maximum Echo fits exactly in the 1500-byte IPv4 datagram.
	LD	HL,1472
	CALL	BUILD_ICMP_REQUEST
	JP	C,FAIL_4
	LD	HL,1480
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_4
	LD	A,(WORK+8+1471)
	CP	0xBF
	JP	NZ,FAIL_4

	; Build an IPv4 header with TTL=1, total length 1500 and DF only.
	LD	HL,1472
	CALL	BUILD_ICMP_REQUEST
	JP	C,FAIL_5
	LD	HL,WORK-20
	LD	(DESC4B+IP4B_BUFFER),HL
	LD	HL,1500
	LD	(DESC4B+IP4B_CAPACITY),HL
	LD	HL,SOURCE_IP
	LD	(DESC4B+IP4B_SOURCE),HL
	LD	HL,TARGET_IP
	LD	(DESC4B+IP4B_DESTINATION),HL
	LD	HL,1480
	LD	(DESC4B+IP4B_DATA_LENGTH),HL
	LD	HL,0x1234
	LD	(DESC4B+IP4B_IDENTIFIER),HL
	LD	A,1
	LD	(DESC4B+IP4B_TTL),A
	LD	A,IPV4_PROTOCOL_ICMP
	LD	(DESC4B+IP4B_PROTOCOL),A
	LD	IX,0x2468
	LD	IY,0x1357
	LD	HL,DESC4B
	CALL	@IPV4.BUILD
	JP	C,FAIL_5
	PUSH	IX
	POP	HL
	LD	DE,0x2468
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5
	PUSH	IY
	POP	HL
	LD	DE,0x1357
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5
	LD	A,(WORK-18)
	CP	0x05
	JP	NZ,FAIL_5
	LD	A,(WORK-17)
	CP	0xDC
	JP	NZ,FAIL_5
	LD	A,(WORK-14)
	CP	0x40
	JP	NZ,FAIL_5
	LD	A,(WORK-12)
	CP	1
	JP	NZ,FAIL_5
	LD	HL,WORK-20
	LD	BC,20
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,FAIL_5

	; Strict parse returns the caller-owned payload and exact fields.
	LD	HL,WORK-20
	LD	(DESC4P+IP4P_BUFFER),HL
	LD	HL,1500
	LD	(DESC4P+IP4P_LENGTH),HL
	LD	HL,SOURCE_IP
	LD	(DESC4P+IP4P_EXPECT_SOURCE),HL
	LD	HL,TARGET_IP
	LD	(DESC4P+IP4P_EXPECT_DESTINATION),HL
	LD	A,IPV4_PROTOCOL_ICMP
	LD	(DESC4P+IP4P_EXPECT_PROTOCOL),A
	LD	HL,DESC4P
	CALL	@IPV4.PARSE
	JP	C,FAIL_6
	LD	HL,(DESC4P+IP4P_DATA)
	LD	DE,WORK
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_6
	LD	HL,(DESC4P+IP4P_DATA_LENGTH)
	LD	DE,1480
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_6
	LD	HL,(DESC4P+IP4P_IDENTIFIER)
	LD	DE,0x1234
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_6

	; Reply matching is strict for size, id, sequence, checksum and payload.
	LD	HL,32
	CALL	BUILD_ICMP_REPLY
	JP	C,FAIL_7
	LD	HL,0x509B
	LD	(DESCIR+ICMPR_IDENTIFIER),HL
	LD	HL,0xFFFF
	LD	(DESCIR+ICMPR_SEQUENCE),HL
	LD	HL,32
	LD	(DESCIR+ICMPR_PAYLOAD_LENGTH),HL
	LD	HL,SOURCE_IP
	LD	(DESCIR+ICMPR_EXPECT_SOURCE),HL
	LD	HL,TARGET_IP
	LD	(DESCIR+ICMPR_EXPECT_DESTINATION),HL
	LD	HL,WORK
	LD	BC,40
	LD	DE,DESCIR
	CALL	@ICMP.PARSE_ECHO_REPLY
	JP	C,FAIL_7
	LD	A,(WORK+20)
	XOR	1
	LD	(WORK+20),A
	LD	HL,WORK
	LD	BC,40
	LD	DE,DESCIR
	CALL	@ICMP.PARSE_ECHO_REPLY
	JP	NC,FAIL_7

	; Rebuild a short request and quote it in a valid Destination Unreachable.
	LD	HL,32
	CALL	BUILD_ICMP_REQUEST
	JP	C,FAIL_8
	LD	HL,WORK-20
	LD	(DESC4B+IP4B_BUFFER),HL
	LD	HL,1500
	LD	(DESC4B+IP4B_CAPACITY),HL
	LD	HL,SOURCE_IP
	LD	(DESC4B+IP4B_SOURCE),HL
	LD	HL,TARGET_IP
	LD	(DESC4B+IP4B_DESTINATION),HL
	LD	HL,40
	LD	(DESC4B+IP4B_DATA_LENGTH),HL
	LD	HL,0x2222
	LD	(DESC4B+IP4B_IDENTIFIER),HL
	LD	A,255
	LD	(DESC4B+IP4B_TTL),A
	LD	HL,DESC4B
	CALL	@IPV4.BUILD
	JP	C,FAIL_8
	LD	HL,UNREACH
	LD	(HL),3
	INC	HL
	LD	(HL),1
	INC	HL
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	EX	DE,HL
	LD	HL,WORK-20
	LD	BC,28
	LDIR
	LD	HL,UNREACH
	LD	BC,36
	CALL	@ETHERNET.CHECKSUM
	LD	A,H
	LD	(UNREACH+2),A
	LD	A,L
	LD	(UNREACH+3),A
	LD	HL,UNREACH
	LD	BC,36
	LD	DE,DESCIR
	CALL	@ICMP.PARSE_UNREACHABLE
	JP	C,FAIL_8
	; A checksum-valid quote with a foreign sequence must not match.
	LD	A,(UNREACH+35)
	XOR	1
	LD	(UNREACH+35),A
	CALL	RECHECK_UNREACH
	LD	HL,UNREACH
	LD	BC,36
	LD	DE,DESCIR
	CALL	@ICMP.PARSE_UNREACHABLE
	JP	NC,FAIL_8
	LD	A,(UNREACH+35)
	XOR	1
	LD	(UNREACH+35),A
	; The reserved IPv4 flag is invalid in the quoted header as well.
	LD	A,0xC0
	LD	(UNREACH+14),A
	XOR	A
	LD	(UNREACH+18),A
	LD	(UNREACH+19),A
	LD	HL,UNREACH+8
	LD	BC,20
	CALL	@ETHERNET.CHECKSUM
	LD	A,H
	LD	(UNREACH+18),A
	LD	A,L
	LD	(UNREACH+19),A
	CALL	RECHECK_UNREACH
	LD	HL,UNREACH
	LD	BC,36
	LD	DE,DESCIR
	CALL	@ICMP.PARSE_UNREACHABLE
	JP	NC,FAIL_8

	; Options, fragmentation, reserved flags, oversize total and bad header
	; checksums are all rejected.
	LD	A,0x46
	LD	(WORK-20),A
	LD	HL,DESC4P
	CALL	@IPV4.PARSE
	JP	NC,FAIL_9
	LD	A,0x45
	LD	(WORK-20),A
	LD	A,0x60
	LD	(WORK-14),A
	CALL	RECHECK_IPV4_HEADER
	LD	HL,DESC4P
	CALL	@IPV4.PARSE
	JP	NC,FAIL_9
	LD	A,0xC0
	LD	(WORK-14),A
	CALL	RECHECK_IPV4_HEADER
	LD	HL,DESC4P
	CALL	@IPV4.PARSE
	JP	NC,FAIL_9
	LD	A,0x40
	LD	(WORK-14),A
	CALL	RECHECK_IPV4_HEADER
	LD	A,0x05
	LD	(WORK-18),A
	LD	A,0xDD
	LD	(WORK-17),A
	LD	HL,1501
	LD	(DESC4P+IP4P_LENGTH),HL
	CALL	RECHECK_IPV4_HEADER
	LD	HL,DESC4P
	CALL	@IPV4.PARSE
	JP	NC,FAIL_9
	LD	A,0xDC
	LD	(WORK-17),A
	LD	HL,1500
	LD	(DESC4P+IP4P_LENGTH),HL
	CALL	RECHECK_IPV4_HEADER
	LD	A,(WORK-10)
	XOR	1
	LD	(WORK-10),A
	LD	HL,DESC4P
	CALL	@IPV4.PARSE
	JP	NC,FAIL_9

	; Non-wrapping end checks and modulo-65536 sequence arithmetic.
	LD	HL,0xBFFC
	LD	(DESCIB+ICMPB_BUFFER),HL
	LD	HL,8
	LD	(DESCIB+ICMPB_CAPACITY),HL
	LD	HL,0
	LD	(DESCIB+ICMPB_PAYLOAD_LENGTH),HL
	LD	HL,DESCIB
	CALL	@ICMP.BUILD_ECHO
	JP	NC,FAIL_10
	LD	HL,0xFFF0
	LD	BC,32
	CALL	@IPV4.VALIDATE_REGION
	JP	NC,FAIL_10
	LD	HL,0xFFFF
	INC	HL
	LD	A,H
	OR	L
	JP	NZ,FAIL_10

	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JP	TEST_DONE

BUILD_ICMP_REQUEST
	LD	A,8
	JR	BUILD_ICMP
BUILD_ICMP_REPLY
	XOR	A
BUILD_ICMP
	LD	(DESCIB+ICMPB_TYPE),A
	LD	(DESCIB+ICMPB_PAYLOAD_LENGTH),HL
	LD	HL,WORK
	LD	(DESCIB+ICMPB_BUFFER),HL
	LD	HL,1480
	LD	(DESCIB+ICMPB_CAPACITY),HL
	LD	HL,0x509B
	LD	(DESCIB+ICMPB_IDENTIFIER),HL
	LD	HL,0xFFFF
	LD	(DESCIB+ICMPB_SEQUENCE),HL
	LD	HL,DESCIB
	JP	@ICMP.BUILD_ECHO

RECHECK_IPV4_HEADER
	XOR	A
	LD	(WORK-10),A
	LD	(WORK-9),A
	LD	HL,WORK-20
	LD	BC,20
	CALL	@ETHERNET.CHECKSUM
	LD	A,H
	LD	(WORK-10),A
	LD	A,L
	LD	(WORK-9),A
	RET

RECHECK_UNREACH
	XOR	A
	LD	(UNREACH+2),A
	LD	(UNREACH+3),A
	LD	HL,UNREACH
	LD	BC,36
	CALL	@ETHERNET.CHECKSUM
	LD	A,H
	LD	(UNREACH+2),A
	LD	A,L
	LD	(UNREACH+3),A
	RET

FAIL_1:	LD A,1
	JR FAIL
FAIL_2:	LD A,2
	JR FAIL
FAIL_3:	LD A,3
	JR FAIL
FAIL_4:	LD A,4
	JR FAIL
FAIL_5:	LD A,5
	JR FAIL
FAIL_6:	LD A,6
	JR FAIL
FAIL_7:	LD A,7
	JR FAIL
FAIL_8:	LD A,8
	JR FAIL
FAIL_9:	LD A,9
	JR FAIL
FAIL_10: LD A,10
FAIL:	LD (TEST_RESULT),A
TEST_DONE
	NOP

SOURCE_IP	DB 192,168,7,20
TARGET_IP	DB 203,0,113,10

	INCLUDE "ethernet.asm"
	INCLUDE "../src/lib/ipv4.asm"
	INCLUDE "../src/lib/icmp.asm"
