; Executable Stage 4 register-core regressions for z88dk-ticks.
; Result byte at C000: zero on success, otherwise failing case number.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001

	MACRO ASSERT_WORD address,value,target
	LD	HL,(address)
	LD	DE,value
	OR	A
	SBC	HL,DE
	JP	NZ,target
	ENDM

	MACRO ASSERT_BYTE address,value,target
	LD	A,(address)
	CP	value
	JP	NZ,target
	ENDM

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A
	CALL	RESET_MOCK

; Public command encoding and all valid/invalid window bounds.
	LD	HL,0x6869
	CALL	@EL3.CMD
	JP	C,FAIL_1
	LD	HL,(MOCK_LAST_COMMAND)
	LD	DE,0x6869
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1
	XOR	A
.WINDOW_LOOP
	PUSH	AF
	CALL	@EL3.SELECT_WINDOW
	JP	C,FAIL_2_POP
	POP	AF
	LD	B,A
	LD	A,(MOCK_WINDOW)
	CP	B
	JP	NZ,FAIL_2
	LD	A,B
	INC	A
	CP	7
	JR	NZ,.WINDOW_LOOP
	LD	A,7
	CALL	@EL3.SELECT_WINDOW
	JP	NC,FAIL_3
	CP	EL3_ERR_BAD_WINDOW
	JP	NZ,FAIL_3
	CALL	@EL3.RESET_GLOBAL
	JP	C,FAIL_3
	LD	HL,(MOCK_LAST_COMMAND)
	LD	A,H
	OR	L
	JP	NZ,FAIL_3

; Provider records low immediately before high for both word directions.
	XOR	A
	LD	(IO_TRACE_LENGTH),A
	LD	A,4
	LD	(MOCK_WINDOW),A
	LD	HL,0xA55A
	LD	E,EL3_W4_MEDIA_STATUS
	CALL	@EL3.WRITE16
	JP	C,FAIL_4
	LD	E,EL3_W4_MEDIA_STATUS
	CALL	@EL3.READ16
	JP	C,FAIL_4
	LD	DE,0xA55A
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_4
	LD	HL,IO_TRACE
	LD	A,(HL)
	CP	0x20 + EL3_W4_MEDIA_STATUS
	JP	NZ,FAIL_4
	INC	HL
	LD	A,(HL)
	CP	0x21 + EL3_W4_MEDIA_STATUS
	JP	NZ,FAIL_4
	INC	HL
	LD	A,(HL)
	CP	0x10 + EL3_W4_MEDIA_STATUS
	JP	NZ,FAIL_4
	INC	HL
	LD	A,(HL)
	CP	0x11 + EL3_W4_MEDIA_STATUS
	JP	NZ,FAIL_4

; CIP clears immediately, after three quanta, and never before timeout.
	XOR	A
	LD	(MOCK_CIP_REMAIN),A
	CALL	@EL3.WAIT_CIP
	JP	C,FAIL_5
	LD	HL,(EL3_LAST_TICKS)
	LD	A,H
	OR	L
	JP	NZ,FAIL_5
	LD	A,3
	LD	(MOCK_CIP_REMAIN),A
	CALL	@EL3.WAIT_CIP
	JP	C,FAIL_6
	LD	HL,(EL3_LAST_TICKS)
	LD	DE,3
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_6
	LD	A,0xFF
	LD	(MOCK_CIP_REMAIN),A
	CALL	@EL3.WAIT_CIP
	JP	NC,FAIL_7
	CP	EL3_ERR_CMD_TIMEOUT
	JP	NZ,FAIL_7
	LD	HL,(EL3_LAST_TICKS)
	LD	DE,100
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_7
	XOR	A
	LD	(MOCK_CIP_REMAIN),A
	CALL	@EL3.WAIT_CIP
	JP	C,FAIL_7
	ASSERT_WORD EL3_COUNT_TIMEOUT,1,FAIL_7

; Exact INIT trace, station byte order, media, filter, masks and thresholds.
	CALL	RESET_MOCK
	CALL	@EL3.INIT
	JP	C,FAIL_8
	LD	A,(COMMAND_COUNT)
	CP	22
	JP	NZ,FAIL_8
	LD	HL,COMMAND_TRACE
	LD	DE,INIT_COMMANDS
	LD	B,22
.COMMAND_COMPARE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_8
	INC	DE
	INC	HL
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_8
	INC	DE
	INC	HL
	DJNZ	.COMMAND_COMPARE
	LD	HL,MOCK_REGISTERS + 2*16
	LD	DE,EL3_MAC
	LD	B,6
.MAC_COMPARE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_9
	INC	DE
	INC	HL
	DJNZ	.MAC_COMPARE
	LD	HL,(MOCK_REGISTERS + 4*16 + EL3_W4_MEDIA_STATUS)
	LD	DE,0x00C3
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_RX_FILTER)
	LD	DE,EL3_RX_FILTER_POLLING
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_INTR_MASK)
	LD	A,H
	OR	L
	JP	NZ,FAIL_10
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_READ_ZERO_MASK)
	LD	DE,EL3_MASK_READ_ZERO
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_RX_EARLY)
	LD	DE,EL3_THRESHOLD_READBACK
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_TX_AVAILABLE)
	LD	DE,EL3_THRESHOLD_READBACK
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_TX_START)
	LD	DE,EL3_TX_START_VALUE
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10
	LD	A,(MOCK_WINDOW)
	CP	1
	JP	NZ,FAIL_10
	LD	HL,MOCK_REGISTERS + 6*16
	LD	B,14
.STATS_CLEARED
	LD	A,(HL)
	OR	A
	JP	NZ,FAIL_10
	INC	HL
	DJNZ	.STATS_CLEARED

; Snapshot v1 exact layout/counters/guards, followed by idempotent DONE.
	LD	HL,0x1234
	LD	(MOCK_REGISTERS + 1*16 + EL3_W1_RX_STATUS),HL
	LD	A,0x56
	LD	(MOCK_REGISTERS + 1*16 + EL3_W1_TX_STATUS),A
	LD	HL,0x1357
	LD	(MOCK_REGISTERS + 4*16 + EL3_W4_FIFO_DIAG),HL
	LD	HL,0x2468
	LD	(MOCK_REGISTERS + 4*16 + EL3_W4_NET_DIAG),HL
	LD	HL,3
	LD	(EL3_COUNT_TIMEOUT),HL
	LD	HL,4
	LD	(EL3_COUNT_RX),HL
	LD	HL,5
	LD	(EL3_COUNT_TX),HL
	LD	HL,6
	LD	(EL3_COUNT_DROP),HL
	LD	HL,7
	LD	(EL3_COUNT_FRAME),HL
	LD	HL,SNAP_TEST
	CALL	@EL3.SNAPSHOT
	JP	C,FAIL_11
	ASSERT_BYTE SNAP_GUARD_HEAD,0xA5,FAIL_11
	ASSERT_BYTE SNAP_GUARD_TAIL,0x5A,FAIL_11
	ASSERT_BYTE SNAP_TEST + EL3_SNAP_VERSION,EL3_SNAPSHOT_VERSION,FAIL_11
	ASSERT_BYTE SNAP_TEST + EL3_SNAP_LENGTH,EL3_SNAPSHOT_LENGTH,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_FLAGS,1,FAIL_11
	ASSERT_BYTE SNAP_TEST + EL3_SNAP_SLOT,1,FAIL_11
	ASSERT_BYTE SNAP_TEST + EL3_SNAP_WINDOW,1,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_IDPORT,0x0110,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_BASE,0x0300,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_PRODUCT,EL3_PRODUCT_3C509B_TPO,FAIL_11
	LD	HL,SNAP_TEST + EL3_SNAP_MAC
	LD	DE,MAC_GOLDEN
	LD	B,6
.SNAP_MAC_COMPARE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_11
	INC	DE
	INC	HL
	DJNZ	.SNAP_MAC_COMPARE
	ASSERT_WORD SNAP_TEST + EL3_SNAP_LAST_COMMAND,0x0801,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_LAST_STATUS,0x2000,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RX_STATUS,0x1234,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_TX_STATUS,0x0056,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_FIFO_DIAG,0x1357,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_NET_DIAG,0x2468,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_MEDIA_STATUS,0x00C3,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RX_FILTER,EL3_RX_FILTER_POLLING,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_INTR_MASK,0,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_READ_ZERO,EL3_MASK_READ_ZERO,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RX_EARLY,EL3_THRESHOLD_READBACK,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_TX_AVAILABLE,EL3_THRESHOLD_READBACK,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_TX_START,EL3_TX_START_VALUE,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_RESET,2,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_TIMEOUT,3,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_RX,4,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_TX,5,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_DROP,6,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_FRAME,7,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RESERVED,0,FAIL_11
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RESERVED+2,0,FAIL_11

; A failure before window capture must not reuse the prior saved window.
	LD	A,3
	LD	(MOCK_WINDOW),A
	LD	A,1
	LD	(MOCK_IO_ERROR),A
	XOR	A
	LD	(COMMAND_COUNT),A
	LD	HL,SNAP_TEST
	CALL	@EL3.SNAPSHOT
	JP	NC,FAIL_11
	CP	EL3_ERR_ISA_STATE
	JP	NZ,FAIL_11
	ASSERT_BYTE COMMAND_COUNT,0,FAIL_11
	ASSERT_BYTE MOCK_WINDOW,3,FAIL_11
	XOR	A
	LD	(MOCK_IO_ERROR),A
	XOR	A
	LD	(COMMAND_COUNT),A
	CALL	@EL3.DONE
	JP	C,FAIL_12
	LD	A,(COMMAND_COUNT)
	CP	7
	JP	NZ,FAIL_12
	LD	HL,COMMAND_TRACE
	LD	DE,DONE_COMMANDS
	LD	B,7
.DONE_COMPARE
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_12
	INC	DE
	INC	HL
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_12
	INC	DE
	INC	HL
	DJNZ	.DONE_COMPARE
	LD	A,(MOCK_WINDOW)
	OR	A
	JP	NZ,FAIL_12
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_INTR_MASK)
	LD	A,H
	OR	L
	JP	NZ,FAIL_12
	LD	HL,(MOCK_REGISTERS + 5*16 + EL3_W5_READ_ZERO_MASK)
	LD	A,H
	OR	L
	JP	NZ,FAIL_12

; One hundred complete INIT/SNAPSHOT/DONE cycles without rediscovery.
	CALL	RESET_MOCK
	LD	A,1
	LD	(TRACE_DISABLED),A
	LD	B,100
.HUNDRED
	PUSH	BC
	CALL	@EL3.INIT
	JP	C,FAIL_13_POP
	LD	HL,EL3_SNAPSHOT_BUFFER
	CALL	@EL3.SNAPSHOT
	JP	C,FAIL_13_POP
	CALL	@EL3.DONE
	JP	C,FAIL_13_POP
	POP	BC
	DJNZ	.HUNDRED
	LD	HL,(EL3_COUNT_RESET)
	LD	DE,200
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_13

; EL3REG decimal -n boundaries: 0/101 reject, 1/100 accept.
	LD	HL,CMD_N0
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_REG
	JP	NC,FAIL_14
	LD	HL,CMD_N1
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_REG
	JP	C,FAIL_14
	LD	HL,(CLI_COUNT)
	LD	DE,1
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_14
	LD	HL,CMD_N100
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_REG
	JP	C,FAIL_14
	LD	HL,(CLI_COUNT)
	LD	DE,100
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_14
	LD	HL,CMD_N101
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_REG
	JP	NC,FAIL_14

; Every public register-core routine preserves IX and IY.
	CALL	RESET_MOCK
	LD	IX,0x1234
	LD	IY,0x5678
	LD	E,0
	CALL	@EL3.READ8
	JP	C,FAIL_15
	LD	A,0xA5
	LD	E,4
	CALL	@EL3.WRITE8
	JP	C,FAIL_15
	LD	E,2
	CALL	@EL3.READ16
	JP	C,FAIL_15
	LD	HL,0x5AA5
	LD	E,4
	CALL	@EL3.WRITE16
	JP	C,FAIL_15
	LD	HL,EL3_CMD_ACK_INTR | EL3_ACK_POLLING
	CALL	@EL3.CMD
	JP	C,FAIL_15
	CALL	@EL3.WAIT_CIP
	JP	C,FAIL_15
	LD	A,3
	CALL	@EL3.SELECT_WINDOW
	JP	C,FAIL_15
	CALL	@EL3.RESET_GLOBAL
	JP	C,FAIL_15
	CALL	@EL3.RESET_RX
	JP	C,FAIL_15
	CALL	@EL3.RESET_TX
	JP	C,FAIL_15
	CALL	@EL3.INIT
	JP	C,FAIL_15
	LD	HL,SNAP_TEST
	CALL	@EL3.SNAPSHOT
	JP	C,FAIL_15
	CALL	@EL3.DONE
	JP	C,FAIL_15
	PUSH	IX
	POP	HL
	LD	DE,0x1234
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_15
	PUSH	IY
	POP	HL
	LD	DE,0x5678
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_15

; Exact INIT_VERIFY failure remains visible and is recoverable without EEPROM.
	CALL	RESET_MOCK
	LD	A,1
	LD	(MOCK_READ_ZERO_MISMATCH),A
	CALL	@EL3.INIT
	JP	NC,FAIL_16
	CP	EL3_ERR_INIT_VERIFY
	JP	NZ,FAIL_16
	ASSERT_BYTE EL3_LAST_STAGE,EL3_STAGE_INIT,FAIL_16
	ASSERT_BYTE EL3_VERIFY_FIELD,EL3_VERIFY_READ_ZERO,FAIL_16
	ASSERT_WORD EL3_VERIFY_ACTUAL,0,FAIL_16
	ASSERT_WORD EL3_VERIFY_EXPECTED,EL3_MASK_READ_ZERO,FAIL_16
	XOR	A
	LD	(MOCK_READ_ZERO_MISMATCH),A
	CALL	@EL3.DONE
	JP	C,FAIL_16
	CALL	@EL3.INIT
	JP	C,FAIL_16
	CALL	@EL3.DONE
	JP	C,FAIL_16
	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

FAIL_2_POP
	POP	AF
FAIL_2:  LD A,2
	JR FAIL
FAIL_13_POP
	POP	BC
FAIL_13: LD A,13
	JR FAIL
FAIL_1:  LD A,1
	JR FAIL
FAIL_3:  LD A,3
	JR FAIL
FAIL_4:  LD A,4
	JR FAIL
FAIL_5:  LD A,5
	JR FAIL
FAIL_6:  LD A,6
	JR FAIL
FAIL_7:  LD A,7
	JR FAIL
FAIL_8:  LD A,8
	JR FAIL
FAIL_9:  LD A,9
	JR FAIL
FAIL_10: LD A,10
	JR FAIL
FAIL_11: LD A,11
	JR FAIL
FAIL_12: LD A,12
	JR FAIL
FAIL_14: LD A,14
	JR FAIL
FAIL_15: LD A,15
	JR FAIL
FAIL_16: LD A,16
FAIL
	LD	(TEST_RESULT),A
TEST_DONE
	NOP

RESET_MOCK
	XOR	A
	LD	(MOCK_WINDOW),A
	LD	(MOCK_CIP_REMAIN),A
	LD	(COMMAND_COUNT),A
	LD	(IO_TRACE_LENGTH),A
	LD	(TRACE_DISABLED),A
	LD	(MOCK_IO_ERROR),A
	LD	(MOCK_READ_ZERO_MISMATCH),A
	LD	HL,MOCK_REGISTERS
	LD	DE,MOCK_REGISTERS+1
	LD	BC,7*16-1
	LD	(HL),A
	LDIR
	LD	HL,0
	LD	(EL3_COUNT_RESET),HL
	LD	(EL3_COUNT_TIMEOUT),HL
	LD	(EL3_COUNT_RX),HL
	LD	(EL3_COUNT_TX),HL
	LD	(EL3_COUNT_DROP),HL
	LD	(EL3_COUNT_FRAME),HL
	LD	(EL3_VERIFY_EXPECTED),HL
	LD	(EL3_VERIFY_ACTUAL),HL
	XOR	A
	LD	(EL3_VERIFY_FIELD),A
	LD	HL,0x0110
	LD	(EL3_IDPORT),HL
	LD	HL,0x0300
	LD	(EL3_BASE),HL
	LD	HL,EL3_PRODUCT_3C509B_TPO
	LD	(MOCK_REGISTERS + EL3_REG_PRODUCT_ID),HL
	LD	HL,0x0003
	LD	(MOCK_REGISTERS + 4*16 + EL3_W4_MEDIA_STATUS),HL
	LD	HL,MOCK_REGISTERS + 6*16
	LD	B,14
	LD	A,0xFF
.FILL_STATS
	LD	(HL),A
	INC	HL
	DJNZ	.FILL_STATS
	LD	HL,MAC_GOLDEN
	LD	DE,EL3_MAC
	LD	BC,6
	LDIR
	RET

INIT_COMMANDS
	DW 0x7000,0x7896,0x1800,0x5000,0x2800,0x5800
	DW 0x0802,0x0804,0xB000,0x0806,0x8005,0x8FFF
	DW 0x97FF,0x9E00,0xA800,0x2000,0x4800,0x6869
	DW 0x0802,0x0804,0x0805,0x0801
DONE_COMMANDS
	DW 0x1800,0x5000,0xB000,0x7000,0x7800,0x6869,0x0800
MAC_GOLDEN	DB 0x02,0x60,0x8C,0x12,0x34,0x56
SNAP_GUARD_HEAD DB 0xA5
SNAP_TEST	DS EL3_SNAPSHOT_LENGTH,0xCC
SNAP_GUARD_TAIL DB 0x5A

	MACRO CMD name,text
name
	DB .END-.TEXT
.TEXT	DB text
.END
	ENDM
	CMD CMD_N0,"-n 0"
	CMD CMD_N1,"-n 1"
	CMD CMD_N100,"-n 100"
	CMD CMD_N101,"-n 101"

; Mock provider. It records byte ordering and models command-visible registers.
	MODULE EL3IO
READ8
	PUSH	BC,DE,HL,IX,IY
	LD	A,E
	ADD	A,0x10
	CALL	TRACE_IO
	CALL	REGISTER_ADDRESS
	LD	A,(HL)
	LD	(READ_BYTE),A
	LD	A,(@MOCK_WINDOW)
	CP	6
	JR	NZ,.NO_ZERO
	XOR	A
	LD	(HL),A
.NO_ZERO
	LD	A,(READ_BYTE)
	OR	A
	POP	IY,IX,HL,DE,BC
	RET

WRITE8
	PUSH	BC,DE,HL,IX,IY
	LD	(WRITE_BYTE),A
	LD	A,E
	ADD	A,0x20
	CALL	TRACE_IO
	CALL	REGISTER_ADDRESS
	LD	A,(WRITE_BYTE)
	LD	(HL),A
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

READ16
	PUSH	BC,DE,IX,IY
	LD	A,(@MOCK_IO_ERROR)
	OR	A
	JR	Z,.READ16_START
	LD	A,EL3_ERR_ISA_STATE
	SCF
	POP	IY,IX,DE,BC
	RET
.READ16_START
	LD	A,E
	ADD	A,0x10
	CALL	TRACE_IO
	LD	A,E
	ADD	A,0x11
	CALL	TRACE_IO
	LD	A,E
	CP	EL3_REG_COMMAND
	JR	Z,.STATUS
	CALL	REGISTER_ADDRESS
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	XOR	A
	POP	IY,IX,DE,BC
	RET
.STATUS
	LD	A,(@MOCK_WINDOW)
	RLCA
	RLCA
	RLCA
	RLCA
	RLCA
	LD	H,A
	LD	L,0
	LD	A,(@MOCK_CIP_REMAIN)
	OR	A
	JR	Z,.STATUS_READY
	SET	4,H
	CP	0xFF
	JR	Z,.STATUS_READY
	DEC	A
	LD	(@MOCK_CIP_REMAIN),A
.STATUS_READY
	XOR	A
	POP	IY,IX,DE,BC
	RET

WRITE16
	PUSH	BC,DE,HL,IX,IY
	LD	(WRITE_WORD),HL
	LD	A,E
	ADD	A,0x20
	CALL	TRACE_IO
	LD	A,E
	ADD	A,0x21
	CALL	TRACE_IO
	LD	A,E
	CP	EL3_REG_COMMAND
	JR	Z,.COMMAND
	CALL	REGISTER_ADDRESS
	LD	DE,(WRITE_WORD)
	LD	(HL),E
	INC	HL
	LD	(HL),D
	JR	.OK
.COMMAND
	LD	HL,(WRITE_WORD)
	LD	(@MOCK_LAST_COMMAND),HL
	CALL	TRACE_COMMAND
	LD	A,H
	AND	0xF8
	CP	0x08
	JR	Z,.SELECT
	CP	0x70
	JR	Z,.INTR_MASK
	CP	0x78
	JR	Z,.READ_ZERO
	CP	0x80
	JR	Z,.RX_FILTER
	CP	0x88
	JR	Z,.RX_EARLY
	CP	0x90
	JR	Z,.TX_AVAILABLE
	CP	0x98
	JR	Z,.TX_START
	JR	.OK
.SELECT
	LD	A,L
	AND	7
	LD	(@MOCK_WINDOW),A
	JR	.OK
.INTR_MASK
	LD	DE,5*16 + EL3_W5_INTR_MASK
	JR	.STORE_PARAMETER
.READ_ZERO
	LD	DE,5*16 + EL3_W5_READ_ZERO_MASK
	LD	A,(@MOCK_READ_ZERO_MISMATCH)
	OR	A
	JR	Z,.STORE_PARAMETER
	LD	HL,0
	JR	.STORE_VALUE
	JR	.STORE_PARAMETER
.RX_FILTER
	LD	DE,5*16 + EL3_W5_RX_FILTER
	JR	.STORE_PARAMETER
.RX_EARLY
	LD	DE,5*16 + EL3_W5_RX_EARLY
	JR	.STORE_THRESHOLD
.TX_AVAILABLE
	LD	DE,5*16 + EL3_W5_TX_AVAILABLE
	JR	.STORE_THRESHOLD
.TX_START
	LD	DE,5*16 + EL3_W5_TX_START
	JR	.STORE_THRESHOLD
.STORE_THRESHOLD
	LD	HL,(WRITE_WORD)
	LD	A,L
	AND	0xFC
	LD	L,A
	LD	A,H
	AND	7
	LD	H,A
	JR	.STORE_VALUE
.STORE_PARAMETER
	LD	HL,(WRITE_WORD)
	LD	A,H
	AND	7
	LD	H,A
.STORE_VALUE
	PUSH	HL
	LD	HL,@MOCK_REGISTERS
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	LD	A,L
	LD	(DE),A
	INC	DE
	LD	A,H
	LD	(DE),A
.OK
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

REGISTER_ADDRESS
	LD	A,(@MOCK_WINDOW)
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0x70
	ADD	A,E
	LD	L,A
	LD	H,0
	LD	BC,@MOCK_REGISTERS
	ADD	HL,BC
	RET

TRACE_IO
	PUSH	AF,BC,DE,HL
	LD	B,A
	LD	A,(@IO_TRACE_LENGTH)
	CP	64
	JR	NC,.IO_DONE
	LD	L,A
	LD	H,0
	LD	DE,@IO_TRACE
	ADD	HL,DE
	LD	(HL),B
	LD	A,(@IO_TRACE_LENGTH)
	INC	A
	LD	(@IO_TRACE_LENGTH),A
.IO_DONE
	POP	HL,DE,BC,AF
	RET

TRACE_COMMAND
	LD	A,(@TRACE_DISABLED)
	OR	A
	RET	NZ
	LD	A,(@COMMAND_COUNT)
	CP	80
	RET	NC
	LD	E,A
	LD	D,0
	SLA	E
	RL	D
	PUSH	HL
	LD	HL,@COMMAND_TRACE
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	LD	A,L
	LD	(DE),A
	INC	DE
	LD	A,H
	LD	(DE),A
	LD	A,(@COMMAND_COUNT)
	INC	A
	LD	(@COMMAND_COUNT),A
	RET

READ_BYTE	DB 0
WRITE_BYTE	DB 0
WRITE_WORD	DW 0
	ENDMODULE

	MODULE EL3
SLOT	DB 1
; Stage 4 isolates the register core. Stage 5 vectors exercise the real
; loopback RMW used by INIT and DONE.
LOOPBACK_DISABLE
	XOR	A
	RET
	ENDMODULE

MOCK_WINDOW	DB 0
MOCK_CIP_REMAIN DB 0
MOCK_LAST_COMMAND DW 0
TRACE_DISABLED	DB 0
MOCK_IO_ERROR	DB 0
MOCK_READ_ZERO_MISMATCH DB 0
COMMAND_COUNT	DB 0
IO_TRACE_LENGTH DB 0
COMMAND_TRACE	DS 160,0xCC
IO_TRACE	DS 64,0xCC
MOCK_REGISTERS	DS 7*16,0xCC

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli.asm"
	INCLUDE "el3_regs.asm"
