; Executable DHCP renewal, DNS, NTP and TZ vectors for z88dk-ticks.
; SPDX-License-Identifier: BSD-3-Clause

	DEFINE RUNTIME_BASE 0xB000
	DEFINE STAGE9_LAYOUT
	DEFINE STAGE10_PAGE_LAYOUT
	DEVICE NOSLOT64K
	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "dns_ntp.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001
WORK		EQU 0x8000
DNS_BUILD	EQU 0x9000
DNS_PARSE	EQU 0x9020
NTP_BUILD	EQU 0x9040
NTP_PARSE	EQU 0x9060

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	; Shared TZ grammar, signed-minute output and ABI preservation.
	LD	IX,0x2468
	LD	IY,0x1357
	LD	HL,TZ_VALID
	LD	DE,TZ_EXPECTED
	LD	B,10
.TZ_OK_LOOP
	PUSH	BC
	PUSH	HL
	PUSH	DE
	CALL	@NETPARSE.PARSE_TZ
	JP	C,FAIL_1
	EX	DE,HL
	POP	DE
	LD	A,(DE)
	LD	C,A
	INC	DE
	LD	A,(DE)
	LD	B,A
	INC	DE
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_1
	POP	HL
.TZ_NEXT_TEXT
	LD	A,(HL)
	INC	HL
	OR	A
	JR	NZ,.TZ_NEXT_TEXT
	POP	BC
	DJNZ	.TZ_OK_LOOP
	PUSH	IX
	POP	HL
	LD	DE,0x2468
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1
	PUSH	IY
	POP	HL
	LD	DE,0x1357
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1
	LD	HL,TZ_INVALID
	LD	B,9
.TZ_BAD_LOOP
	PUSH	BC,HL
	CALL	@NETPARSE.PARSE_TZ
	JP	NC,FAIL_2
	POP	HL
.TZ_BAD_NEXT
	LD	A,(HL)
	INC	HL
	OR	A
	JR	NZ,.TZ_BAD_NEXT
	POP	BC
	DJNZ	.TZ_BAD_LOOP
	LD	HL,0xBFFC
	LD	(HL),'+'
	INC	HL
	LD	(HL),'1'
	INC	HL
	LD	(HL),'2'
	INC	HL
	LD	(HL),':'
	LD	HL,0xBFFC
	CALL	@NETPARSE.PARSE_TZ
	JP	NC,FAIL_2

	; A/IN RD query, trailing dot, label/name limits and caller-owned buffer.
	LD	HL,WORK
	LD	(DNS_BUILD+DNSQB_BUFFER),HL
	LD	HL,512
	LD	(DNS_BUILD+DNSQB_CAPACITY),HL
	LD	HL,NAME_TRAILING
	LD	(DNS_BUILD+DNSQB_NAME),HL
	LD	HL,0x1234
	LD	(DNS_BUILD+DNSQB_XID),HL
	LD	HL,DNS_BUILD
	CALL	@DNS.BUILD_QUERY
	JP	C,FAIL_3
	LD	HL,28
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_3
	LD	A,(WORK+0)
	CP	0x12
	JP	NZ,FAIL_3
	LD	A,(WORK+1)
	CP	0x34
	JP	NZ,FAIL_3
	LD	A,(WORK+2)
	CP	1
	JP	NZ,FAIL_3
	LD	A,(WORK+12)
	CP	4
	JP	NZ,FAIL_3
	LD	HL,NAME_LABEL_64
	CALL	@DNS.VALIDATE_NAME
	JP	NC,FAIL_3
	LD	HL,NAME_EMPTY_LABEL
	CALL	@DNS.VALIDATE_NAME
	JP	NC,FAIL_3

	; Strict response parser follows a CNAME/compression chain and selects A.
	LD	HL,DNS_GOOD
	LD	(DNS_PARSE+DNSP_BUFFER),HL
	LD	HL,DNS_GOOD_END-DNS_GOOD
	LD	(DNS_PARSE+DNSP_LENGTH),HL
	LD	HL,0x1234
	LD	(DNS_PARSE+DNSP_XID),HL
	LD	HL,WORK+0x300
	LD	(DNS_PARSE+DNSP_RESULT),HL
	LD	HL,DNS_PARSE
	CALL	@DNS.PARSE_REPLY
	JP	C,FAIL_4
	LD	HL,WORK+0x300
	LD	DE,ANSWER_IP
	CALL	ASSERT4
	JP	NZ,FAIL_4
	LD	HL,DNS_NXDOMAIN
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_4
	CP	NETDRV_ERR_DNS_NXDOMAIN
	JP	NZ,FAIL_4
	LD	HL,DNS_NO_A
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_4
	CP	NETDRV_ERR_DNS_NO_ANSWER
	JP	NZ,FAIL_4

	; Pointer loop/OOB, truncation, stale XID and QTYPE mismatch are rejected.
	LD	HL,DNS_LOOP
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_5
	LD	HL,DNS_POINTER_OOB
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_5
	LD	HL,DNS_TRUNCATED
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_5
	LD	HL,DNS_STALE
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_5
	CP	NETDRV_ERR_PARAMETER
	JP	NZ,FAIL_5
	LD	HL,DNS_BAD_QTYPE
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_5
	LD	HL,DNS_NAME_OVERFLOW
	CALL	PARSE_DNS_PACKET
	JP	NC,FAIL_5
	LD	HL,0xBFF8
	LD	(DNS_PARSE+DNSP_BUFFER),HL
	LD	HL,16
	LD	(DNS_PARSE+DNSP_LENGTH),HL
	LD	HL,DNS_PARSE
	CALL	@DNS.PARSE_REPLY
	JP	NC,FAIL_5
	LD	HL,DNS_GOOD
	LD	(DNS_PARSE+DNSP_BUFFER),HL
	LD	HL,DNS_GOOD_END-DNS_GOOD
	LD	(DNS_PARSE+DNSP_LENGTH),HL
	LD	HL,0xBFFE
	LD	(DNS_PARSE+DNSP_RESULT),HL
	LD	HL,DNS_PARSE
	CALL	@DNS.PARSE_REPLY
	JP	NC,FAIL_5
	LD	HL,WORK+0x300
	LD	(DNS_PARSE+DNSP_RESULT),HL

	; NTPv4 request, originate cookie and transmit timestamp validation.
	LD	HL,WORK+0x400
	LD	(NTP_BUILD+NTPB_BUFFER),HL
	LD	HL,48
	LD	(NTP_BUILD+NTPB_CAPACITY),HL
	LD	HL,NTP_TEST_COOKIE
	LD	(NTP_BUILD+NTPB_COOKIE),HL
	LD	HL,NTP_BUILD
	CALL	@NTP.BUILD_REQUEST
	JP	C,FAIL_6
	LD	A,B
	OR	A
	JP	NZ,FAIL_6
	LD	A,C
	CP	48
	JP	NZ,FAIL_6
	LD	A,(WORK+0x400)
	CP	0x23
	JP	NZ,FAIL_6
	LD	HL,WORK+0x428
	LD	DE,NTP_TEST_COOKIE
	LD	B,8
	CALL	ASSERT_BYTES
	JP	NZ,FAIL_6
	LD	HL,NTP_GOOD
	CALL	PARSE_NTP_PACKET
	JP	C,FAIL_6
	LD	HL,NTP_SECONDS
	LD	DE,NTP_EXPECT_SECONDS
	CALL	ASSERT4
	JP	NZ,FAIL_6
	LD	HL,NTP_BAD_COOKIE
	CALL	PARSE_NTP_PACKET
	JP	NC,FAIL_6
	CP	NETDRV_ERR_PARAMETER
	JP	NZ,FAIL_6
	LD	HL,NTP_BAD_MODE
	CALL	PARSE_NTP_PACKET
	JP	NC,FAIL_6
	LD	HL,NTP_ZERO_TX
	CALL	PARSE_NTP_PACKET
	JP	NC,FAIL_6
	LD	HL,0xBFFC
	LD	(NTP_BUILD+NTPB_COOKIE),HL
	LD	HL,NTP_BUILD
	CALL	@NTP.BUILD_REQUEST
	JP	NC,FAIL_6
	LD	HL,NTP_TEST_COOKIE
	LD	(NTP_BUILD+NTPB_COOKIE),HL
	LD	HL,NTP_GOOD
	LD	(NTP_PARSE+NTPP_BUFFER),HL
	LD	HL,48
	LD	(NTP_PARSE+NTPP_LENGTH),HL
	LD	HL,NTP_TEST_COOKIE
	LD	(NTP_PARSE+NTPP_COOKIE),HL
	LD	HL,0xBFFE
	LD	(NTP_PARSE+NTPP_SECONDS),HL
	LD	HL,NTP_PARSE
	CALL	@NTP.PARSE_REPLY
	JP	NC,FAIL_6

	; Epoch/leap-day conversion plus positive/negative date rollover.
	LD	HL,NTP_LEAP_SECONDS
	LD	DE,NTP_SECONDS
	LD	BC,4
	LDIR
	CALL	@NTP.TO_CALENDAR
	LD	HL,345
	LD	(NTP_TZ_MINUTES),HL
	CALL	@NTP.APPLY_TZ
	LD	HL,(NTP_YEAR)
	LD	DE,2024
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_7
	LD	A,(NTP_MONTH)
	CP	3
	JP	NZ,FAIL_7
	LD	A,(NTP_DAY)
	CP	1
	JP	NZ,FAIL_7
	LD	A,(NTP_HOUR)
	CP	5
	JP	NZ,FAIL_7
	LD	A,(NTP_MINUTE)
	CP	15
	JP	NZ,FAIL_7
	LD	HL,NTP_YEAR_SECONDS
	LD	DE,NTP_SECONDS
	LD	BC,4
	LDIR
	CALL	@NTP.TO_CALENDAR
	LD	HL,-210
	LD	(NTP_TZ_MINUTES),HL
	CALL	@NTP.APPLY_TZ
	LD	HL,(NTP_YEAR)
	LD	DE,2024
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_7
	LD	A,(NTP_MONTH)
	CP	12
	JP	NZ,FAIL_7
	LD	A,(NTP_DAY)
	CP	31
	JP	NZ,FAIL_7
	LD	A,(NTP_HOUR)
	CP	20
	JP	NZ,FAIL_7
	LD	A,(NTP_MINUTE)
	CP	30
	JP	NZ,FAIL_7

	; Renewal and RELEASE are unicast, carry ciaddr/source IP and valid sums.
	LD	HL,TEST_MAC
	LD	DE,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	HL,SERVER_MAC
	LD	DE,NET_RESULT_MAC
	LD	BC,6
	LDIR
	LD	HL,CLIENT_IP
	LD	DE,DHCP_OFFERED_IP
	LD	BC,4
	LDIR
	LD	HL,SERVER_IP
	LD	DE,DHCP_SERVER_ID
	LD	BC,4
	LDIR
	LD	HL,XID
	LD	DE,DHCP_XID
	LD	BC,4
	LDIR
	LD	DE,WORK
	LD	HL,TEST_MAC
	CALL	@DHCP.BUILD_RENEW
	JP	C,FAIL_8
	LD	HL,WORK
	LD	DE,SERVER_MAC
	LD	B,6
	CALL	ASSERT_BYTES
	JP	NZ,FAIL_8
	LD	HL,WORK+26
	LD	DE,CLIENT_IP
	CALL	ASSERT4
	JP	NZ,FAIL_8
	LD	HL,WORK+30
	LD	DE,SERVER_IP
	CALL	ASSERT4
	JP	NZ,FAIL_8
	LD	HL,WORK+54
	LD	DE,CLIENT_IP
	CALL	ASSERT4
	JP	NZ,FAIL_8
	LD	A,(WORK+52)
	OR	A
	JP	NZ,FAIL_8
	LD	A,(WORK+284)
	CP	DHCP_REQUEST
	JP	NZ,FAIL_8
	LD	HL,WORK+14
	LD	BC,20
	CALL	@ETHERNET.VERIFY_CHECKSUM
	JP	C,FAIL_8
	LD	DE,WORK
	LD	HL,TEST_MAC
	CALL	@DHCP.BUILD_RELEASE
	JP	C,FAIL_8
	LD	A,(WORK+284)
	CP	DHCP_RELEASE
	JP	NZ,FAIL_8
	LD	HL,WORK+285
	LD	DE,RELEASE_OPTIONS
	LD	B,7
	CALL	ASSERT_BYTES
	JP	NZ,FAIL_8
	LD	DE,0xBFF0
	LD	HL,TEST_MAC
	CALL	@DHCP.BUILD_RENEW
	JP	NC,FAIL_8
	LD	HL,0xBFF0
	LD	BC,32
	CALL	@DHCP.PARSE_RENEW_REPLY
	JP	NC,FAIL_8

	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

PARSE_DNS_PACKET
	LD	(DNS_PARSE+DNSP_BUFFER),HL
	PUSH	HL
.PDP_SCAN
	LD	A,(HL)
	INC	HL
	CP	0xEE
	JR	NZ,.PDP_SCAN
	POP	DE
	OR	A
	SBC	HL,DE
	DEC	HL
	LD	(DNS_PARSE+DNSP_LENGTH),HL
	LD	HL,0x1234
	LD	(DNS_PARSE+DNSP_XID),HL
	LD	HL,DNS_PARSE
	JP	@DNS.PARSE_REPLY

PARSE_NTP_PACKET
	LD	(NTP_PARSE+NTPP_BUFFER),HL
	LD	DE,48
	LD	(NTP_PARSE+NTPP_LENGTH),DE
	LD	DE,NTP_TEST_COOKIE
	LD	(NTP_PARSE+NTPP_COOKIE),DE
	LD	DE,NTP_SECONDS
	LD	(NTP_PARSE+NTPP_SECONDS),DE
	LD	HL,NTP_PARSE
	JP	@NTP.PARSE_REPLY

ASSERT4
	LD	B,4
ASSERT_BYTES
.AB_NEXT
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.AB_NEXT
	RET

FAIL_1:	LD A,1
	JR FAIL
FAIL_2:	LD A,2
	JR FAIL
FAIL_3:	LD A,3
	JR FAIL
FAIL_4:	LD A,4
	JR FAIL
FAIL_5:	LD A,5
	JR FAIL
FAIL_6:	LD A,6
	JR FAIL
FAIL_7:	LD A,7
	JR FAIL
FAIL_8:	LD A,8
FAIL:	LD (TEST_RESULT),A
TEST_DONE
	NOP

TZ_VALID
	DB 0,"0",0,"+4",0,"+5:30",0,"+5:45",0,"+9:30",0,"+12:45",0
	DB "-3:30",0,"-12:00",0,"+14:00",0
TZ_EXPECTED
	DW 0,0,240,330,345,570,765,-210,-720,840
TZ_INVALID
	DB "+5:10",0,"+5:60",0,"+14:15",0,"-12:15",0,"+5:3",0
	DB "+5:",0,"++5",0,"5x",0,"999999",0
NAME_TRAILING	DB "test.local.",0
NAME_EMPTY_LABEL DB "test..local",0
NAME_LABEL_64	DB "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.test",0
ANSWER_IP	DB 192,168,7,44

DNS_QUESTION	MACRO
	DB 4,"test",5,"local",0,0,1,0,1
	ENDM
DNS_HEADER	MACRO rcode,answers
	DB 0x12,0x34,0x81,0x80+rcode,0,1,0,answers,0,0,0,0
	ENDM
DNS_GOOD
	DNS_HEADER 0,2
	DNS_QUESTION
	DB 0xC0,0x0C,0,5,0,1,0,0,0,60,0,2,0xC0,0x0C
	DB 0xC0,0x0C,0,1,0,1,0,0,0,60,0,4,192,168,7,44
DNS_GOOD_END
DNS_NXDOMAIN
	DNS_HEADER 3,0
	DNS_QUESTION
	DB 0xEE
DNS_NO_A
	DNS_HEADER 0,1
	DNS_QUESTION
	DB 0xC0,0x0C,0,5,0,1,0,0,0,60,0,2,0xC0,0x0C,0xEE
DNS_LOOP
	DNS_HEADER 0,1
	DNS_QUESTION
	DB 0xC0,0x1C,0,1,0,1,0,0,0,60,0,4,1,2,3,4,0xEE
DNS_POINTER_OOB
	DNS_HEADER 0,1
	DNS_QUESTION
	DB 0xFF,0xFF,0,1,0,1,0,0,0,60,0,4,1,2,3,4,0xEE
DNS_TRUNCATED
	DNS_HEADER 0,1
	DNS_QUESTION
	DB 0xC0,0x0C,0,1,0,1,0,0,0,60,0,4,1,0xEE
DNS_STALE
	DB 0x12,0x35,0x81,0x80,0,1,0,0,0,0,0,0
	DNS_QUESTION
	DB 0xEE
DNS_BAD_QTYPE
	DNS_HEADER 0,0
	DB 4,"test",5,"local",0,0,28,0,1,0xEE
DNS_NAME_OVERFLOW
	DNS_HEADER 0,1
	DNS_QUESTION
	DB 63
	DS 63,'a'
	DB 63
	DS 63,'b'
	DB 63
	DS 63,'c'
	DB 62
	DS 62,'d'
	DB 0,0,1,0,1,0,0,0,60,0,4,1,2,3,4,0xEE

NTP_TEST_COOKIE	DB 1,2,3,4,5,6,7,8
NTP_EXPECT_SECONDS DB 0x00,0x04,0x1F,0xEB
NTP_GOOD
	DB 0x24,2,6,0xEC
	DS 20,0
	DB 1,2,3,4,5,6,7,8
	DS 8,0
	DB 0xEB,0x1F,0x04,0x00,0x80,0,0,0
NTP_BAD_COOKIE
	DB 0x24,2,6,0xEC
	DS 20,0
	DB 1,2,3,4,5,6,7,9
	DS 8,0
	DB 0xEB,0x1F,0x04,0x00,0x80,0,0,0
NTP_BAD_MODE
	DB 0x23,2,6,0xEC
	DS 20,0
	DB 1,2,3,4,5,6,7,8
	DS 8,0
	DB 0xEB,0x1F,0x04,0x00,0x80,0,0,0
NTP_ZERO_TX
	DB 0x24,2,6,0xEC
	DS 20,0
	DB 1,2,3,4,5,6,7,8
	DS 16,0
NTP_LEAP_SECONDS DB 0x07,0x92,0x8B,0xE9
NTP_YEAR_SECONDS DB 0x00,0x04,0x1F,0xEB
TEST_MAC	DB 2,0x60,0x8C,0x12,0x34,0x56
SERVER_MAC	DB 2,0,0,0,0,1
CLIENT_IP	DB 192,168,7,100
SERVER_IP	DB 192,168,7,1
XID		DB 0x12,0x34,0x56,0x78
RELEASE_OPTIONS DB 54,4,192,168,7,1,255

	INCLUDE "ethernet.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "dhcp.asm"
	INCLUDE "dns.asm"
	INCLUDE "ntp.asm"
	INCLUDE "netparse.asm"
	INCLUDE "el3_algorithms.asm"
