; Executable Stage 6 parser and CRC32 vectors for z88dk-ticks.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "memory.inc"
	INCLUDE "dss.inc"
	INCLUDE "el3.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001

	MACRO ASSERT_WORD address,value,target
	LD	HL,(address)
	LD	DE,value
	OR	A
	SBC	HL,DE
	JP	NZ,target
	ENDM

	MACRO ASSERT_BYTE address,value,target
	LD	A,(address)
	CP	value
	JP	NZ,target
	ENDM

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	LD	HL,CRC_TEXT
	LD	BC,9
	CALL	@CRC32.COMPUTE
	ASSERT_BYTE CRC32_VALUE+0,0x26,FAIL_1
	ASSERT_BYTE CRC32_VALUE+1,0x39,FAIL_1
	ASSERT_BYTE CRC32_VALUE+2,0xF4,FAIL_1
	ASSERT_BYTE CRC32_VALUE+3,0xCB,FAIL_1

	XOR	A
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	A,B
	CP	DSS_EXIT_OK
	JP	NZ,FAIL_6
	LD	A,EL3_ERR_PARAMETER
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	A,B
	CP	DSS_EXIT_ARGUMENT
	JP	NZ,FAIL_6
	LD	A,EL3_ERR_NOT_FOUND
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	A,B
	CP	DSS_EXIT_HARDWARE
	JP	NZ,FAIL_6
	LD	A,EL3_ERR_LINK_TIMEOUT
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	A,B
	CP	DSS_EXIT_NETWORK
	JP	NZ,FAIL_6
	LD	A,EL3_ERR_NO_MEMORY
	CALL	@EL3ALG.TO_DSS_EXIT
	LD	A,B
	CP	DSS_EXIT_LOCAL
	JP	NZ,FAIL_6

	LD	HL,CMD_TX_MIN
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI6.PARSE_TX
	JP	C,FAIL_2
	ASSERT_BYTE CLI_SLOT,0,FAIL_2
	ASSERT_WORD CLI_IDPORT,0x0100,FAIL_2
	ASSERT_WORD CLI_BASE,0x0200,FAIL_2
	ASSERT_WORD CLI_ETHERTYPE,0x0600,FAIL_2
	ASSERT_WORD CLI_LENGTH,14,FAIL_2
	ASSERT_WORD CLI_COUNT,1,FAIL_2
	ASSERT_WORD CLI_WAIT,1,FAIL_2
	ASSERT_BYTE CLI_PATTERN,0,FAIL_2

	LD	HL,CMD_TX_MAX
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI6.PARSE_TX
	JP	C,FAIL_3
	ASSERT_BYTE CLI_SLOT,1,FAIL_3
	ASSERT_WORD CLI_IDPORT,0x01F0,FAIL_3
	ASSERT_WORD CLI_BASE,0x03E0,FAIL_3
	ASSERT_WORD CLI_ETHERTYPE,0xFFFF,FAIL_3
	ASSERT_WORD CLI_LENGTH,1514,FAIL_3
	ASSERT_WORD CLI_COUNT,100,FAIL_3
	ASSERT_WORD CLI_WAIT,10000,FAIL_3
	ASSERT_BYTE CLI_PATTERN,4,FAIL_3

	LD	HL,CMD_RX_MAX
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI6.PARSE_RX
	JP	C,FAIL_4
	ASSERT_BYTE CLI_HEXDUMP,1,FAIL_4
	ASSERT_WORD CLI_COUNT,100,FAIL_4
	ASSERT_WORD CLI_WAIT,10000,FAIL_4

	LD	HL,CMD_TX_NO_DEST
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI6.PARSE_TX
	JP	NC,FAIL_5
	CP	EL3_ERR_PARAMETER
	JP	NZ,FAIL_5
	LD	HL,CMD_TX_BAD_LENGTH
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI6.PARSE_TX
	JP	NC,FAIL_5
	LD	HL,CMD_RX_BAD_WAIT
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI6.PARSE_RX
	JP	NC,FAIL_5

	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

FAIL_1:	LD A,1
	JR FAIL
FAIL_2:	LD A,2
	JR FAIL
FAIL_3:	LD A,3
	JR FAIL
FAIL_4:	LD A,4
	JR FAIL
FAIL_5:	LD A,5
	JR FAIL
FAIL_6:	LD A,6
FAIL:	LD (TEST_RESULT),A
TEST_DONE
	NOP

CRC_TEXT	DB "123456789"

	MACRO CMD name,text
name
	DB .END-.TEXT
.TEXT	DB text
.END
	ENDM

	CMD CMD_TX_MIN,"-s 0 -p #100 -b #200 -d 02:00:00:00:00:01 -t #0600 -l 14 -f 00 -n 1 -w 1"
	CMD CMD_TX_MAX,"-s 1 -p #1F0 -b #3E0 -d FF:FF:FF:FF:FF:FF -t #FFFF -l 1514 -f INC -n 100 -w 10000"
	CMD CMD_RX_MAX,"-x -s 1 -p #1F0 -b #3E0 -n 100 -w 10000"
	CMD CMD_TX_NO_DEST,"-n 1"
	CMD CMD_TX_BAD_LENGTH,"-d 02:00:00:00:00:01 -l 1515"
	CMD CMD_RX_BAD_WAIT,"-w 10001"

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli_stage6.asm"
	INCLUDE "crc32.asm"
