; Executable Stage 5 FIFO/datapath regressions for z88dk-ticks.
; Result byte at C000: zero on success, otherwise failing case number.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001

	MACRO ASSERT_WORD address,value,target
	LD	HL,(address)
	LD	DE,value
	OR	A
	SBC	HL,DE
	JP	NZ,target
	ENDM

	MACRO ASSERT_BYTE address,value,target
	LD	A,(address)
	CP	value
	JP	NZ,target
	ENDM

	MACRO TX_VECTOR length,required,target
	CALL	RESET_TX_MOCK
	LD	HL,TX_SOURCE_DATA
	LD	BC,length
	CALL	@EL3.SEND_FRAME
	JP	C,target
	LD	HL,required
	LD	(EXPECT_REQUIRED),HL
	LD	HL,length
	LD	(EXPECT_INPUT),HL
	CALL	CHECK_TX_CAPTURE
	JP	C,target
	ENDM

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A
	CALL	RESET_MOCK

; Required bytes, exact preamble/data/software pad/DWORD pad.
	TX_VECTOR 14,64,FAIL_1
	TX_VECTOR 42,64,FAIL_1
	TX_VECTOR 59,64,FAIL_1
	TX_VECTOR 60,64,FAIL_1
	TX_VECTOR 61,68,FAIL_1
	TX_VECTOR 62,68,FAIL_1
	TX_VECTOR 63,68,FAIL_1
	TX_VECTOR 1514,1520,FAIL_1
	LD	HL,TX_SOURCE_DATA
	LD	BC,13
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_1
	CP	EL3_ERR_FRAME_SIZE
	JP	NZ,FAIL_1
	LD	HL,TX_SOURCE_DATA
	LD	BC,1515
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_1

; TX Free and completion: immediate, delayed, then both 1000-waitq limits.
	CALL	RESET_TX_MOCK
	LD	A,3
	LD	(MOCK_FREE_DELAY),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_2
	ASSERT_WORD MOCK_FREE_READS,4,FAIL_2
	CALL	RESET_TX_MOCK
	LD	A,3
	LD	(MOCK_STATUS_DELAY),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_2
	ASSERT_WORD MOCK_TX_READS,4,FAIL_2
	CALL	RESET_TX_MOCK
	LD	HL,0
	LD	(MOCK_TX_FREE),HL
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_3
	CP	EL3_ERR_TX_TIMEOUT
	JP	NZ,FAIL_3
	ASSERT_WORD EL3_LAST_TICKS,1000,FAIL_3
	ASSERT_BYTE MOCK_TX_RESETS,1,FAIL_3
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,0,FAIL_3
	CALL	RESET_TX_MOCK
	XOR	A
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_3
	CP	EL3_ERR_TX_TIMEOUT
	JP	NZ,FAIL_3
	ASSERT_WORD EL3_LAST_TICKS,1000,FAIL_3
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,1,FAIL_3

; Read-peek/write-pop, stale entry, and bounded recovery.
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY
	LD	(MOCK_TX_STATUS),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_4
	ASSERT_BYTE MOCK_TX_POPS,2,FAIL_4
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_JABBER
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY
	LD	(MOCK_STATUS_SEQUENCE+1),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_5
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,2,FAIL_5
	ASSERT_BYTE MOCK_TX_RESETS,1,FAIL_5
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_UNDERRUN
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY
	LD	(MOCK_STATUS_SEQUENCE+1),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_5
	ASSERT_BYTE MOCK_TX_RESETS,1,FAIL_5
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_MAX_COLLISION
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY
	LD	(MOCK_STATUS_SEQUENCE+1),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_5
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,2,FAIL_5
	ASSERT_BYTE MOCK_TX_RESETS,0,FAIL_5
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_OVERFLOW
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_6
	CP	EL3_ERR_TX_ERROR
	JP	NZ,FAIL_6
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,1,FAIL_6
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_JABBER
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	(MOCK_STATUS_SEQUENCE+1),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_6
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,2,FAIL_6

; A failed reset/enable recovery must never retransmit the frame.
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_JABBER
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,1
	LD	(MOCK_FAIL_TX_RESET),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_16
	CP	EL3_ERR_CMD_TIMEOUT
	JP	NZ,FAIL_16
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,1,FAIL_16
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_MAX_COLLISION
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,1
	LD	(MOCK_FAIL_TX_ENABLE),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_16
	CP	EL3_ERR_CMD_TIMEOUT
	JP	NZ,FAIL_16
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,1,FAIL_16
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_OVERFLOW
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,1
	LD	(MOCK_FAIL_TX_ENABLE),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_16
	CP	EL3_ERR_CMD_TIMEOUT
	JP	NZ,FAIL_16
	ASSERT_BYTE MOCK_PACKET_ATTEMPTS,1,FAIL_16
	CALL	RESET_TX_MOCK

; RX empty, complete error, invalid size, small buffer, data and pad consume.
	CALL	RESET_RX_MOCK
	CALL	@EL3.RX_PENDING
	JP	C,FAIL_7
	OR	A
	JP	NZ,FAIL_7
	CALL	@EL3.DISCARD_FRAME
	JP	NC,FAIL_7
	CP	EL3_ERR_NO_FRAME
	JP	NZ,FAIL_7
	CALL	RESET_RX_MOCK
	LD	HL,EL3_RX_ERROR | 60
	LD	(MOCK_RX_STATUS_QUEUE),HL
	LD	A,1
	LD	(MOCK_RX_COUNT),A
	CALL	@EL3.RX_PENDING
	JP	C,FAIL_8
	CP	1
	JP	NZ,FAIL_8
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	JP	NC,FAIL_8
	CP	EL3_ERR_RX_ERROR
	JP	NZ,FAIL_8
	ASSERT_BYTE MOCK_RX_DISCARDS,1,FAIL_8
	CALL	RESET_RX_MOCK
	LD	HL,59
	LD	(MOCK_RX_STATUS_QUEUE),HL
	LD	A,1
	LD	(MOCK_RX_COUNT),A
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	JP	NC,FAIL_8
	CP	EL3_ERR_RX_ERROR
	JP	NZ,FAIL_8
	CALL	RESET_RX_MOCK
	LD	HL,61
	LD	(MOCK_RX_STATUS_QUEUE),HL
	LD	A,1
	LD	(MOCK_RX_COUNT),A
	LD	HL,RX_DEST_DATA
	LD	BC,60
	CALL	@EL3.READ_FRAME
	JP	NC,FAIL_9
	CP	EL3_ERR_FRAME_SIZE
	JP	NZ,FAIL_9
	LD	A,B
	OR	A
	JP	NZ,FAIL_9
	LD	A,C
	CP	61
	JP	NZ,FAIL_9
	ASSERT_WORD EL3_RX_REQUIRED,61,FAIL_9
	ASSERT_BYTE MOCK_RX_DISCARDS,1,FAIL_9
	CALL	PREPARE_RX_61
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	JP	C,FAIL_10
	LD	A,C
	CP	61
	JP	NZ,FAIL_10
	ASSERT_WORD MOCK_RX_CONSUMED,64,FAIL_10
	ASSERT_BYTE MOCK_RX_DISCARDS,1,FAIL_10
	LD	HL,RX_DEST_DATA
	LD	B,61
.RX_COMPARE
	LD	A,(HL)
	CP	0xA5
	JP	NZ,FAIL_10
	INC	HL
	DJNZ	.RX_COMPARE

; Two and ten queued packets remain independent.
	LD	B,2
	CALL	TEST_RX_QUEUE
	JP	C,FAIL_11
	LD	B,10
	CALL	TEST_RX_QUEUE
	JP	C,FAIL_11

; Controller-loopback RMW preserves other bits and verifies bit 13.
	CALL	RESET_MOCK
	LD	HL,0x0155
	LD	(MOCK_NET_DIAG),HL
	CALL	@EL3.LOOPBACK_ENABLE
	JP	C,FAIL_12
	ASSERT_WORD MOCK_NET_DIAG,0x2155,FAIL_12
	CALL	@EL3.LOOPBACK_DISABLE
	JP	C,FAIL_12
	ASSERT_WORD MOCK_NET_DIAG,0x0155,FAIL_12
	LD	A,1
	LD	(MOCK_DROP_NET_DIAG_WRITE),A
	CALL	@EL3.LOOPBACK_ENABLE
	JP	NC,FAIL_12
	CP	EL3_ERR_LOOPBACK_VERIFY
	JP	NZ,FAIL_12
	ASSERT_BYTE MOCK_WINDOW,1,FAIL_12
	ASSERT_WORD MOCK_NET_DIAG,0x0155,FAIL_12

; Counter semantics and snapshot v1/60, including zero reserved bytes.
	CALL	RESET_MOCK
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_13
	CALL	PREPARE_RX_61
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	JP	C,FAIL_13
	CALL	RESET_RX_MOCK
	LD	HL,EL3_RX_ERROR | 60
	LD	(MOCK_RX_STATUS_QUEUE),HL
	LD	A,1
	LD	(MOCK_RX_COUNT),A
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	JP	NC,FAIL_13
	CALL	RESET_TX_MOCK
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY | EL3_TX_JABBER
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY
	LD	(MOCK_STATUS_SEQUENCE+1),A
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_13
	CALL	RESET_TX_MOCK
	LD	HL,0
	LD	(MOCK_TX_FREE),HL
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	NC,FAIL_13
	LD	HL,SNAP_TEST
	CALL	@EL3.SNAPSHOT
	JP	C,FAIL_13
	ASSERT_BYTE SNAP_TEST + EL3_SNAP_VERSION,1,FAIL_13
	ASSERT_BYTE SNAP_TEST + EL3_SNAP_LENGTH,60,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_RESET,2,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_TIMEOUT,1,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_RX,1,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_TX,1,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_DROP,1,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_COUNT_FRAME,3,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RESERVED,0,FAIL_13
	ASSERT_WORD SNAP_TEST + EL3_SNAP_RESERVED+2,0,FAIL_13

; CLI bounds and IX/IY preservation.
	LD	HL,CMD_N0
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_LB
	JP	NC,FAIL_14
	LD	HL,CMD_N1
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_LB
	JP	C,FAIL_14
	ASSERT_WORD CLI_COUNT,1,FAIL_14
	LD	HL,CMD_N100
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_LB
	JP	C,FAIL_14
	ASSERT_WORD CLI_COUNT,100,FAIL_14
	LD	HL,CMD_N101
	LD	(CMDLINE_SOURCE),HL
	CALL	@CLI.PARSE_LB
	JP	NC,FAIL_14
	LD	A,EL3_SNAPSHOT_VERSION
	CP	1
	JP	NZ,FAIL_14
	LD	A,EL3_SNAPSHOT_LENGTH
	CP	60
	JP	NZ,FAIL_14
	CALL	RESET_TX_MOCK
	LD	IX,0x1234
	LD	IY,0x5678
	LD	HL,TX_SOURCE_DATA
	LD	BC,60
	CALL	@EL3.SEND_FRAME
	JP	C,FAIL_15
	CALL	PREPARE_RX_61
	CALL	@EL3.RX_PENDING
	JP	C,FAIL_15
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	JP	C,FAIL_15
	CALL	@EL3.DISCARD_FRAME
	CP	EL3_ERR_NO_FRAME
	JP	NZ,FAIL_15
	CALL	@EL3.LOOPBACK_ENABLE
	JP	C,FAIL_15
	CALL	@EL3.LOOPBACK_DISABLE
	JP	C,FAIL_15
	PUSH	IX
	POP	HL
	LD	DE,0x1234
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_15
	PUSH	IY
	POP	HL
	LD	DE,0x5678
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_15

	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

FAIL_1:  LD A,1
	JR FAIL
FAIL_2:  LD A,2
	JR FAIL
FAIL_3:  LD A,3
	JR FAIL
FAIL_4:  LD A,4
	JR FAIL
FAIL_5:  LD A,5
	JR FAIL
FAIL_6:  LD A,6
	JR FAIL
FAIL_7:  LD A,7
	JR FAIL
FAIL_8:  LD A,8
	JR FAIL
FAIL_9:  LD A,9
	JR FAIL
FAIL_10: LD A,10
	JR FAIL
FAIL_11: LD A,11
	JR FAIL
FAIL_12: LD A,12
	JR FAIL
FAIL_13: LD A,13
	JR FAIL
FAIL_14: LD A,14
	JR FAIL
FAIL_15: LD A,15
	JR FAIL
FAIL_16: LD A,16
FAIL
	LD	(TEST_RESULT),A
TEST_DONE
	NOP

CHECK_TX_CAPTURE
	LD	HL,(MOCK_FIFO_COUNT)
	LD	DE,(EXPECT_REQUIRED)
	OR	A
	SBC	HL,DE
	JR	NZ,.TX_CHECK_BAD
	LD	HL,(EXPECT_INPUT)
	LD	DE,60
	OR	A
	SBC	HL,DE
	JR	NC,.TX_CHECK_INPUT
	LD	HL,60
	JR	.TX_CHECK_EFFECTIVE
.TX_CHECK_INPUT
	LD	HL,(EXPECT_INPUT)
.TX_CHECK_EFFECTIVE
	LD	A,(MOCK_TX_CAPTURE)
	CP	L
	JR	NZ,.TX_CHECK_BAD
	LD	A,(MOCK_TX_CAPTURE+1)
	AND	0x7F
	CP	H
	JR	NZ,.TX_CHECK_BAD
	LD	A,(MOCK_TX_CAPTURE+1)
	AND	0x80
	JR	Z,.TX_CHECK_BAD
	LD	A,(MOCK_TX_CAPTURE+2)
	OR	A
	JR	NZ,.TX_CHECK_BAD
	LD	A,(MOCK_TX_CAPTURE+3)
	OR	A
	JR	NZ,.TX_CHECK_BAD
	LD	HL,MOCK_TX_CAPTURE+4
	LD	BC,(EXPECT_INPUT)
.TX_CHECK_DATA
	LD	A,B
	OR	C
	JR	Z,.TX_CHECK_ZERO
	LD	A,(HL)
	CP	0x5A
	JR	NZ,.TX_CHECK_BAD
	INC	HL
	DEC	BC
	JR	.TX_CHECK_DATA
.TX_CHECK_ZERO
	LD	DE,MOCK_TX_CAPTURE
	LD	BC,(EXPECT_REQUIRED)
	ADD	DE,BC
.TX_CHECK_ZERO_LOOP
	OR	A
	SBC	HL,DE
	JR	Z,.TX_CHECK_OK
	ADD	HL,DE
	LD	A,(HL)
	OR	A
	JR	NZ,.TX_CHECK_BAD
	INC	HL
	JR	.TX_CHECK_ZERO_LOOP
.TX_CHECK_OK
	OR	A
	RET
.TX_CHECK_BAD
	SCF
	RET

PREPARE_RX_61
	CALL	RESET_RX_MOCK
	LD	HL,61
	LD	(MOCK_RX_STATUS_QUEUE),HL
	LD	A,1
	LD	(MOCK_RX_COUNT),A
	LD	HL,MOCK_RX_DATA
	LD	BC,61
	LD	A,0xA5
.PREP_FILL
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	LD	A,0xA5
	JR	NZ,.PREP_FILL
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	RET

TEST_RX_QUEUE
	PUSH	BC
	CALL	RESET_RX_MOCK
	POP	BC
	LD	A,B
	LD	(MOCK_RX_COUNT),A
	LD	HL,MOCK_RX_STATUS_QUEUE
	LD	D,B
.QUEUE_STATUS
	LD	(HL),60
	INC	HL
	LD	(HL),0
	INC	HL
	DEC	D
	JR	NZ,.QUEUE_STATUS
	LD	HL,MOCK_RX_DATA
	LD	D,B
	LD	E,1
.QUEUE_PACKET
	LD	B,64
.QUEUE_DATA
	LD	(HL),E
	INC	HL
	DJNZ	.QUEUE_DATA
	INC	E
	DEC	D
	JR	NZ,.QUEUE_PACKET
	LD	A,(MOCK_RX_COUNT)
	LD	(QUEUE_REMAIN),A
	LD	A,1
	LD	(QUEUE_EXPECT),A
.QUEUE_READ
	LD	HL,RX_DEST_DATA
	LD	BC,1514
	CALL	@EL3.READ_FRAME
	RET	C
	LD	A,C
	CP	60
	JR	NZ,.QUEUE_BAD
	LD	A,(QUEUE_EXPECT)
	LD	D,A
	LD	A,(RX_DEST_DATA)
	CP	D
	JR	NZ,.QUEUE_BAD
	LD	A,(QUEUE_EXPECT)
	INC	A
	LD	(QUEUE_EXPECT),A
	LD	A,(QUEUE_REMAIN)
	DEC	A
	LD	(QUEUE_REMAIN),A
	JR	NZ,.QUEUE_READ
	CALL	@EL3.RX_PENDING
	RET	C
	OR	A
	JR	NZ,.QUEUE_BAD
	XOR	A
	RET
.QUEUE_BAD
	SCF
	RET

RESET_MOCK
	XOR	A
	LD	(MOCK_WINDOW),A
	LD	(MOCK_CIP_REMAIN),A
	LD	(MOCK_DROP_NET_DIAG_WRITE),A
	LD	(MOCK_TX_RESETS),A
	LD	(MOCK_TX_ENABLES),A
	LD	HL,0
	LD	(EL3_COUNT_RESET),HL
	LD	(EL3_COUNT_TIMEOUT),HL
	LD	(EL3_COUNT_RX),HL
	LD	(EL3_COUNT_TX),HL
	LD	(EL3_COUNT_DROP),HL
	LD	(EL3_COUNT_FRAME),HL
	CALL	RESET_TX_MOCK
	CALL	RESET_RX_MOCK
	RET

RESET_TX_MOCK
	XOR	A
	LD	(MOCK_CIP_REMAIN),A
	LD	(MOCK_TX_STATUS),A
	LD	(MOCK_FREE_DELAY),A
	LD	(MOCK_STATUS_DELAY),A
	LD	(MOCK_TX_POPS),A
	LD	(MOCK_PACKET_ATTEMPTS),A
	LD	(MOCK_TX_RESETS),A
	LD	(MOCK_TX_ENABLES),A
	LD	(MOCK_FAIL_TX_RESET),A
	LD	(MOCK_FAIL_TX_ENABLE),A
	LD	H,A
	LD	L,A
	LD	(MOCK_FIFO_COUNT),HL
	LD	(MOCK_TX_READS),HL
	LD	(MOCK_FREE_READS),HL
	LD	HL,0xFFFF
	LD	(MOCK_TX_FREE),HL
	LD	A,EL3_TX_COMPLETE | EL3_TX_NOTIFY
	LD	(MOCK_STATUS_SEQUENCE),A
	LD	(MOCK_STATUS_SEQUENCE+1),A
	LD	HL,MOCK_TX_CAPTURE
	LD	DE,MOCK_TX_CAPTURE+1
	LD	BC,1519
	XOR	A
	LD	(HL),A
	LDIR
	RET

RESET_RX_MOCK
	XOR	A
	LD	(MOCK_RX_COUNT),A
	LD	(MOCK_RX_INDEX),A
	LD	(MOCK_RX_DISCARDS),A
	LD	H,A
	LD	L,A
	LD	(MOCK_RX_OFFSET),HL
	LD	(MOCK_RX_CONSUMED),HL
	RET

	MACRO CMD name,text
name
	DB .END-.TEXT
.TEXT	DB text
.END
	ENDM
	CMD CMD_N0,"-n 0"
	CMD CMD_N1,"-n 1"
	CMD CMD_N100,"-n 100"
	CMD CMD_N101,"-n 101"

; Register and FIFO mock provider.
	MODULE EL3IO
READ8
	PUSH	BC,DE,HL,IX,IY
	LD	A,E
	CP	EL3_W1_TX_STATUS
	JR	NZ,.READ8_ZERO
	LD	HL,(@MOCK_TX_READS)
	INC	HL
	LD	(@MOCK_TX_READS),HL
	LD	A,(@MOCK_STATUS_DELAY)
	OR	A
	JR	Z,.READ8_STATUS
	DEC	A
	LD	(@MOCK_STATUS_DELAY),A
	XOR	A
	JR	.READ8_DONE
.READ8_STATUS
	LD	A,(@MOCK_TX_STATUS)
	JR	.READ8_DONE
.READ8_ZERO
	XOR	A
.READ8_DONE
	OR	A
	POP	IY,IX,HL,DE,BC
	RET

WRITE8
	PUSH	BC,DE,HL,IX,IY
	LD	A,E
	CP	EL3_W1_TX_STATUS
	JR	NZ,.WRITE8_DONE
	LD	A,(@MOCK_TX_POPS)
	INC	A
	LD	(@MOCK_TX_POPS),A
	XOR	A
	LD	(@MOCK_TX_STATUS),A
.WRITE8_DONE
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

READ16
	PUSH	BC,DE,IX,IY
	LD	A,E
	CP	EL3_REG_COMMAND
	JR	Z,.READ16_COMMAND
	LD	A,(@MOCK_WINDOW)
	CP	1
	JR	NZ,.READ16_WINDOW4
	LD	A,E
	CP	EL3_W1_TX_FREE
	JR	Z,.READ16_FREE
	CP	EL3_W1_RX_STATUS
	JR	Z,.READ16_RX
.READ16_WINDOW4
	LD	A,(@MOCK_WINDOW)
	CP	4
	JR	NZ,.READ16_ZERO
	LD	A,E
	CP	EL3_W4_NET_DIAG
	JR	NZ,.READ16_ZERO
	LD	HL,(@MOCK_NET_DIAG)
	JR	.READ16_DONE
.READ16_FREE
	LD	HL,(@MOCK_FREE_READS)
	INC	HL
	LD	(@MOCK_FREE_READS),HL
	LD	A,(@MOCK_FREE_DELAY)
	OR	A
	JR	Z,.READ16_FREE_READY
	DEC	A
	LD	(@MOCK_FREE_DELAY),A
	LD	HL,0
	JR	.READ16_DONE
.READ16_FREE_READY
	LD	HL,(@MOCK_TX_FREE)
	JR	.READ16_DONE
.READ16_RX
	LD	A,(@MOCK_RX_INDEX)
	LD	B,A
	LD	A,(@MOCK_RX_COUNT)
	CP	B
	JR	Z,.READ16_ZERO
	LD	A,B
	ADD	A,A
	LD	L,A
	LD	H,0
	LD	BC,@MOCK_RX_STATUS_QUEUE
	ADD	HL,BC
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	JR	.READ16_DONE
.READ16_COMMAND
	LD	A,(@MOCK_WINDOW)
	RLCA
	RLCA
	RLCA
	RLCA
	RLCA
	LD	H,A
	LD	L,0
	LD	A,(@MOCK_CIP_REMAIN)
	OR	A
	JR	Z,.READ16_DONE
	SET	4,H
	CP	0xFF
	JR	Z,.READ16_DONE
	DEC	A
	LD	(@MOCK_CIP_REMAIN),A
	JR	.READ16_DONE
.READ16_ZERO
	LD	HL,0
.READ16_DONE
	XOR	A
	POP	IY,IX,DE,BC
	RET

WRITE16
	PUSH	BC,DE,HL,IX,IY
	LD	A,E
	CP	EL3_REG_COMMAND
	JR	Z,.WRITE16_COMMAND
	LD	A,(@MOCK_WINDOW)
	CP	4
	JR	NZ,.WRITE16_DONE
	LD	A,E
	CP	EL3_W4_NET_DIAG
	JR	NZ,.WRITE16_DONE
	LD	A,(@MOCK_DROP_NET_DIAG_WRITE)
	OR	A
	JR	NZ,.WRITE16_DONE
	LD	(@MOCK_NET_DIAG),HL
	JR	.WRITE16_DONE
.WRITE16_COMMAND
	LD	A,H
	AND	0xF8
	CP	0x08
	JR	Z,.WRITE16_SELECT
	CP	0x40
	JR	Z,.WRITE16_DISCARD
	CP	0x58
	JR	Z,.WRITE16_TX_RESET
	CP	0x48
	JR	Z,.WRITE16_TX_ENABLE
	JR	.WRITE16_DONE
.WRITE16_SELECT
	LD	A,L
	AND	7
	LD	(@MOCK_WINDOW),A
	JR	.WRITE16_DONE
.WRITE16_DISCARD
	LD	A,(@MOCK_RX_DISCARDS)
	INC	A
	LD	(@MOCK_RX_DISCARDS),A
	LD	A,(@MOCK_RX_INDEX)
	INC	A
	LD	(@MOCK_RX_INDEX),A
	XOR	A
	LD	H,A
	LD	L,A
	LD	(@MOCK_RX_OFFSET),HL
	JR	.WRITE16_DONE
.WRITE16_TX_RESET
	LD	A,(@MOCK_TX_RESETS)
	INC	A
	LD	(@MOCK_TX_RESETS),A
	LD	A,(@MOCK_FAIL_TX_RESET)
	OR	A
	JR	Z,.WRITE16_DONE
	LD	A,0xFF
	LD	(@MOCK_CIP_REMAIN),A
	JR	.WRITE16_DONE
.WRITE16_TX_ENABLE
	LD	A,(@MOCK_TX_ENABLES)
	INC	A
	LD	(@MOCK_TX_ENABLES),A
	LD	A,(@MOCK_FAIL_TX_ENABLE)
	OR	A
	JR	Z,.WRITE16_DONE
	LD	A,0xFF
	LD	(@MOCK_CIP_REMAIN),A
.WRITE16_DONE
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

FIFO_WRITE
	PUSH	BC,DE,HL,IX,IY
	LD	(FIFO_LENGTH),BC
	LD	A,B
	OR	A
	JR	NZ,.FIFO_WRITE_COPY
	LD	A,C
	CP	4
	JR	NZ,.FIFO_WRITE_COPY
	LD	A,(@MOCK_PACKET_ATTEMPTS)
	INC	A
	LD	(@MOCK_PACKET_ATTEMPTS),A
	DEC	A
	LD	E,A
	LD	D,0
	PUSH	HL
	LD	HL,@MOCK_STATUS_SEQUENCE
	ADD	HL,DE
	LD	A,(HL)
	LD	(@MOCK_TX_STATUS),A
	POP	HL
.FIFO_WRITE_COPY
	PUSH	HL
	LD	HL,@MOCK_TX_CAPTURE
	LD	DE,(@MOCK_FIFO_COUNT)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	LD	BC,(FIFO_LENGTH)
	LDIR
	LD	HL,(@MOCK_FIFO_COUNT)
	LD	BC,(FIFO_LENGTH)
	ADD	HL,BC
	LD	(@MOCK_FIFO_COUNT),HL
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

FIFO_ZERO
	PUSH	BC,DE,HL,IX,IY
	LD	(FIFO_LENGTH),BC
	LD	HL,(@MOCK_FIFO_COUNT)
	LD	DE,@MOCK_TX_CAPTURE
	ADD	HL,DE
	XOR	A
.FIFO_ZERO_LOOP
	LD	D,A
	LD	A,B
	OR	C
	LD	A,D
	JR	Z,.FIFO_ZERO_DONE
	LD	(HL),A
	INC	HL
	DEC	BC
	JR	.FIFO_ZERO_LOOP
.FIFO_ZERO_DONE
	LD	HL,(@MOCK_FIFO_COUNT)
	LD	BC,(FIFO_LENGTH)
	ADD	HL,BC
	LD	(@MOCK_FIFO_COUNT),HL
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

FIFO_READ
	PUSH	BC,DE,HL,IX,IY
	LD	(FIFO_LENGTH),BC
	EX	DE,HL
	PUSH	DE
	LD	A,(@MOCK_RX_INDEX)
	LD	L,A
	LD	H,0
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	DE,(@MOCK_RX_OFFSET)
	ADD	HL,DE
	LD	DE,@MOCK_RX_DATA
	ADD	HL,DE
	POP	DE
	LDIR
	LD	HL,(@MOCK_RX_OFFSET)
	LD	BC,(FIFO_LENGTH)
	ADD	HL,BC
	LD	(@MOCK_RX_OFFSET),HL
	LD	HL,(@MOCK_RX_CONSUMED)
	ADD	HL,BC
	LD	(@MOCK_RX_CONSUMED),HL
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

FIFO_SKIP
	PUSH	BC,DE,HL,IX,IY
	LD	HL,(@MOCK_RX_OFFSET)
	ADD	HL,BC
	LD	(@MOCK_RX_OFFSET),HL
	LD	HL,(@MOCK_RX_CONSUMED)
	ADD	HL,BC
	LD	(@MOCK_RX_CONSUMED),HL
	XOR	A
	POP	IY,IX,HL,DE,BC
	RET

FIFO_LENGTH	DW 0
	ENDMODULE

	MODULE EL3
SLOT	DB 1
	ENDMODULE

EXPECT_REQUIRED	DW 0
EXPECT_INPUT	DW 0
QUEUE_REMAIN	DB 0
QUEUE_EXPECT	DB 0
MOCK_WINDOW	DB 1
MOCK_CIP_REMAIN DB 0
MOCK_TX_STATUS	DB 0
MOCK_TX_FREE	DW 0xFFFF
MOCK_FREE_DELAY DB 0
MOCK_STATUS_DELAY DB 0
MOCK_TX_POPS	DB 0
MOCK_PACKET_ATTEMPTS DB 0
MOCK_TX_RESETS DB 0
MOCK_TX_ENABLES DB 0
MOCK_FAIL_TX_RESET DB 0
MOCK_FAIL_TX_ENABLE DB 0
MOCK_TX_READS	DW 0
MOCK_FREE_READS DW 0
MOCK_FIFO_COUNT DW 0
MOCK_STATUS_SEQUENCE DS 2,0xC0
MOCK_NET_DIAG	DW 0
MOCK_DROP_NET_DIAG_WRITE DB 0
MOCK_RX_COUNT	DB 0
MOCK_RX_INDEX	DB 0
MOCK_RX_DISCARDS DB 0
MOCK_RX_OFFSET	DW 0
MOCK_RX_CONSUMED DW 0
MOCK_RX_STATUS_QUEUE DS 20,0
MOCK_RX_DATA	DS 640,0
MOCK_TX_CAPTURE DS 1520,0
TX_SOURCE_DATA	DS 1514,0x5A
RX_DEST_DATA	DS 1514,0
SNAP_TEST	DS EL3_SNAPSHOT_LENGTH,0xCC

	INCLUDE "el3_algorithms.asm"
	INCLUDE "cli.asm"
	INCLUDE "el3_fifo.asm"
	INCLUDE "el3_regs.asm"
