; Executable UDP/TFTP codec vectors for z88dk-ticks.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "udp_tftp.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001
WORK		EQU 0x8000
UDPB		EQU 0x9000
UDPP		EQU 0x9020
TREQ		EQU 0x9040
TPARSE		EQU 0x9060
TDATA		EQU 0x9080
TERROR		EQU 0x90A0

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	; UDP zero payload, byte order, checksum and ABI preservation.
	LD	HL,0
	CALL	BUILD_UDP
	JP	C,FAIL_1
	LD	A,B
	OR	A
	JP	NZ,FAIL_1
	LD	A,C
	CP	8
	JP	NZ,FAIL_1
	LD	A,(WORK+0)
	CP	0xC4
	JP	NZ,FAIL_1
	LD	A,(WORK+1)
	CP	0x00
	JP	NZ,FAIL_1
	LD	A,(WORK+2)
	CP	0x1E
	JP	NZ,FAIL_1
	LD	A,(WORK+3)
	CP	0x61
	JP	NZ,FAIL_1
	LD	A,(WORK+4)
	OR	A
	JP	NZ,FAIL_1
	LD	A,(WORK+5)
	CP	8
	JP	NZ,FAIL_1
	LD	A,(WORK+6)
	LD	B,A
	LD	A,(WORK+7)
	OR	B
	JP	Z,FAIL_1
	LD	IX,0x2468
	LD	IY,0x1357
	LD	HL,UDPB
	CALL	@UDP.BUILD
	JP	C,FAIL_1
	PUSH	IX
	POP	HL
	LD	DE,0x2468
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1
	PUSH	IY
	POP	HL
	LD	DE,0x1357
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1

	; Odd/even data and strict parse return caller-owned payload.
	LD	HL,1
	CALL	BUILD_UDP
	JP	C,FAIL_2
	LD	A,0xA5
	LD	(WORK+8),A
	CALL	REBUILD_UDP
	JP	C,FAIL_2
	CALL	PARSE_UDP
	JP	C,FAIL_2
	LD	HL,(UDPP+UDPP_PAYLOAD)
	LD	DE,WORK+8
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_2
	LD	HL,(UDPP+UDPP_PAYLOAD_LENGTH)
	LD	DE,1
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_2

	LD	HL,1472
	CALL	BUILD_UDP
	JP	C,FAIL_3
	LD	HL,1480
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_3
	CALL	PARSE_UDP
	JP	C,FAIL_3
	LD	A,(WORK+6)
	LD	B,A
	XOR	A
	LD	(WORK+6),A
	LD	(WORK+7),A		; UDP checksum 0000 is legal for IPv4
	CALL	PARSE_UDP
	JP	C,FAIL_3
	LD	A,B
	LD	(WORK+6),A

	; A checksum whose one's-complement result is zero is sent as FFFF.
	LD	HL,2
	CALL	BUILD_UDP
	JP	C,FAIL_3
	LD	A,0x8D
	LD	(WORK+8),A
	LD	A,0xE7
	LD	(WORK+9),A
	CALL	REBUILD_UDP
	JP	C,FAIL_3
	LD	A,(WORK+6)
	CP	0xFF
	JP	NZ,FAIL_3
	LD	A,(WORK+7)
	CP	0xFF
	JP	NZ,FAIL_3

	; Bad lengths, ports, checksum, overflow and C000 boundary are rejected.
	LD	HL,1473
	CALL	BUILD_UDP
	JP	NC,FAIL_4
	LD	HL,1
	CALL	BUILD_UDP
	JP	C,FAIL_4
	LD	HL,8
	LD	(UDPP+UDPP_LENGTH),HL
	LD	HL,UDPP
	CALL	@UDP.PARSE
	JP	NC,FAIL_4
	LD	HL,9
	LD	(UDPP+UDPP_LENGTH),HL
	LD	A,(WORK+8)
	XOR	1
	LD	(WORK+8),A
	LD	HL,UDPP
	CALL	@UDP.PARSE
	JP	NC,FAIL_4
	LD	HL,0xBFF9
	LD	(UDPB+UDPB_BUFFER),HL
	LD	HL,8
	LD	(UDPB+UDPB_CAPACITY),HL
	LD	HL,UDPB
	CALL	@UDP.BUILD
	JP	NC,FAIL_4
	LD	HL,0xFFF8
	LD	(UDPB+UDPB_BUFFER),HL
	LD	HL,UDPB
	CALL	@UDP.BUILD
	JP	NC,FAIL_4
	LD	HL,0xBFF9
	LD	(UDPP+UDPP_BUFFER),HL
	LD	HL,8
	LD	(UDPP+UDPP_LENGTH),HL
	LD	HL,UDPP
	CALL	@UDP.PARSE
	JP	NC,FAIL_4

	; RRQ framing: octet + blksize=1428; parse a valid OACK.
	CALL	PREP_RRQ
	LD	HL,TREQ
	CALL	@TFTP.BUILD_REQUEST
	JP	C,FAIL_5
	LD	HL,26
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_5
	LD	HL,WORK
	LD	DE,RRQ_GOLDEN
	LD	B,26
	CALL	COMPARE
	JP	NZ,FAIL_5
	LD	HL,TFTP_OPCODE_WRQ
	LD	(TREQ+TFTPR_OPCODE),HL
	LD	HL,TREQ
	CALL	@TFTP.BUILD_REQUEST
	JP	C,FAIL_5
	LD	A,(WORK+1)
	CP	TFTP_OPCODE_WRQ
	JP	NZ,FAIL_5
	LD	HL,OACK_1428
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	HL,OACK_1428_END-OACK_1428
	LD	(TPARSE+TFTPP_LENGTH),HL
	LD	HL,TPARSE
	CALL	@TFTP.PARSE
	JP	C,FAIL_5
	LD	HL,(TPARSE+TFTPP_BLOCK_SIZE)
	LD	DE,1428
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5
	LD	HL,OACK_8
	CALL	PARSE_TFTP
	JP	C,FAIL_5
	LD	HL,(TPARSE+TFTPP_BLOCK_SIZE)
	LD	DE,8
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5
	LD	HL,OACK_512
	CALL	PARSE_TFTP
	JP	C,FAIL_5
	LD	HL,(TPARSE+TFTPP_BLOCK_SIZE)
	LD	DE,512
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_5
	LD	HL,OACK_UPPER
	CALL	PARSE_TFTP
	JP	C,FAIL_5

	; DATA/ACK, block wrap and exact-multiple zero final DATA.
	LD	HL,WORK
	LD	(TDATA+TFTPD_BUFFER),HL
	LD	HL,1500
	LD	(TDATA+TFTPD_CAPACITY),HL
	LD	HL,0
	LD	(TDATA+TFTPD_DATA_LENGTH),HL
	LD	HL,0xFFFF
	LD	(TDATA+TFTPD_BLOCK),HL
	LD	HL,TDATA
	CALL	@TFTP.BUILD_DATA
	JP	C,FAIL_6
	LD	A,(WORK+2)
	CP	0xFF
	JP	NZ,FAIL_6
	LD	A,(WORK+3)
	CP	0xFF
	JP	NZ,FAIL_6
	LD	HL,WORK
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	HL,4
	LD	(TPARSE+TFTPP_LENGTH),HL
	LD	HL,TPARSE
	CALL	@TFTP.PARSE
	JP	C,FAIL_6
	LD	HL,(TPARSE+TFTPP_BLOCK)
	INC	HL
	LD	DE,0
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_6
	LD	HL,(TPARSE+TFTPP_DATA_LENGTH)
	LD	A,H
	OR	L
	JP	NZ,FAIL_6
	LD	HL,WORK
	LD	(TDATA+TFTPA_BUFFER),HL
	LD	HL,4
	LD	(TDATA+TFTPA_CAPACITY),HL
	LD	HL,0xFFFF
	LD	(TDATA+TFTPA_BLOCK),HL
	LD	HL,TDATA
	CALL	@TFTP.BUILD_ACK
	JP	C,FAIL_6
	LD	A,(WORK+1)
	CP	TFTP_OPCODE_ACK
	JP	NZ,FAIL_6
	LD	HL,WORK
	CALL	PARSE_TFTP_LENGTH_4
	JP	C,FAIL_6
	LD	A,(TPARSE+TFTPP_OPCODE)
	CP	TFTP_OPCODE_ACK
	JP	NZ,FAIL_6

	; ERROR framing and bounded, terminated message parsing.
	LD	HL,WORK
	LD	(TERROR+TFTPE_BUFFER),HL
	LD	HL,64
	LD	(TERROR+TFTPE_CAPACITY),HL
	LD	HL,5
	LD	(TERROR+TFTPE_CODE),HL
	LD	HL,ERR_TEXT
	LD	(TERROR+TFTPE_MESSAGE),HL
	LD	HL,3
	LD	(TERROR+TFTPE_MESSAGE_LENGTH),HL
	LD	HL,TERROR
	CALL	@TFTP.BUILD_ERROR
	JP	C,FAIL_6
	LD	HL,WORK
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	(TPARSE+TFTPP_LENGTH),BC
	LD	HL,TPARSE
	CALL	@TFTP.PARSE
	JP	C,FAIL_6
	LD	HL,(TPARSE+TFTPP_ERROR_CODE)
	LD	DE,5
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_6

	; Malformed/oversized OACK and unterminated ERROR are rejected.
	LD	HL,OACK_TOO_BIG
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	HL,OACK_TOO_BIG_END-OACK_TOO_BIG
	LD	(TPARSE+TFTPP_LENGTH),HL
	LD	HL,TPARSE
	CALL	@TFTP.PARSE
	JP	NC,FAIL_7
	LD	HL,BAD_ERROR
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	HL,BAD_ERROR_END-BAD_ERROR
	LD	(TPARSE+TFTPP_LENGTH),HL
	LD	HL,TPARSE
	CALL	@TFTP.PARSE
	JP	NC,FAIL_7
	LD	HL,OACK_EXTRA
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	HL,OACK_EXTRA_END-OACK_EXTRA
	LD	(TPARSE+TFTPP_LENGTH),HL
	LD	HL,TPARSE
	CALL	@TFTP.PARSE
	JP	NC,FAIL_7
	LD	HL,OACK_BAD_NAME
	CALL	PARSE_TFTP
	JP	NC,FAIL_7
	LD	HL,OACK_EMPTY
	CALL	PARSE_TFTP
	JP	NC,FAIL_7

	XOR	A
	LD	(TEST_RESULT),A
	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	JP	TEST_DONE

BUILD_UDP
	LD	(UDPB+UDPB_PAYLOAD_LENGTH),HL
	LD	DE,8
	ADD	HL,DE
	LD	(UDPB+UDPB_CAPACITY),HL
REBUILD_UDP
	LD	HL,WORK
	LD	(UDPB+UDPB_BUFFER),HL
	LD	HL,SOURCE_IP
	LD	(UDPB+UDPB_SOURCE_IP),HL
	LD	HL,TARGET_IP
	LD	(UDPB+UDPB_DESTINATION_IP),HL
	LD	HL,0xC400
	LD	(UDPB+UDPB_SOURCE_PORT),HL
	LD	HL,7777
	LD	(UDPB+UDPB_DESTINATION_PORT),HL
	LD	HL,UDPB
	JP	@UDP.BUILD

PARSE_UDP
	LD	HL,WORK
	LD	(UDPP+UDPP_BUFFER),HL
	LD	BC,(UDPB+UDPB_PAYLOAD_LENGTH)
	LD	HL,8
	ADD	HL,BC
	LD	(UDPP+UDPP_LENGTH),HL
	LD	HL,SOURCE_IP
	LD	(UDPP+UDPP_SOURCE_IP),HL
	LD	HL,TARGET_IP
	LD	(UDPP+UDPP_DESTINATION_IP),HL
	LD	HL,0xC400
	LD	(UDPP+UDPP_EXPECT_SOURCE_PORT),HL
	LD	HL,7777
	LD	(UDPP+UDPP_EXPECT_DEST_PORT),HL
	LD	HL,UDPP
	JP	@UDP.PARSE

; All fixed OACK vectors terminate immediately before the next label.
PARSE_TFTP
	LD	(TPARSE+TFTPP_BUFFER),HL
	INC	HL
	INC	HL
	LD	BC,2
.LENGTH
	LD	A,(HL)
	INC	HL
	INC	BC
	OR	A
	JR	NZ,.LENGTH
.SECOND
	LD	A,(HL)
	INC	HL
	INC	BC
	OR	A
	JR	NZ,.SECOND
	LD	(TPARSE+TFTPP_LENGTH),BC
	LD	HL,TPARSE
	JP	@TFTP.PARSE

PARSE_TFTP_LENGTH_4
	LD	(TPARSE+TFTPP_BUFFER),HL
	LD	HL,4
	LD	(TPARSE+TFTPP_LENGTH),HL
	LD	HL,TPARSE
	JP	@TFTP.PARSE

PREP_RRQ
	LD	HL,WORK
	LD	(TREQ+TFTPR_BUFFER),HL
	LD	HL,128
	LD	(TREQ+TFTPR_CAPACITY),HL
	LD	HL,TEST_NAME
	LD	(TREQ+TFTPR_NAME),HL
	LD	HL,4
	LD	(TREQ+TFTPR_NAME_LENGTH),HL
	LD	HL,TFTP_OPCODE_RRQ
	LD	(TREQ+TFTPR_OPCODE),HL
	LD	HL,1428
	LD	(TREQ+TFTPR_BLOCK_SIZE),HL
	RET

COMPARE
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	COMPARE
	RET

FAIL_1	LD A,1 : JR FAIL
FAIL_2	LD A,2 : JR FAIL
FAIL_3	LD A,3 : JR FAIL
FAIL_4	LD A,4 : JR FAIL
FAIL_5	LD A,5 : JR FAIL
FAIL_6	LD A,6 : JR FAIL
FAIL_7	LD A,7
FAIL
	LD	(TEST_RESULT),A
	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	JP	TEST_DONE

TEST_DONE
	NOP

SOURCE_IP	DB 192,168,7,20
TARGET_IP	DB 192,168,7,44
TEST_NAME	DB "TEST"
RRQ_GOLDEN	DB 0,1,"TEST",0,"octet",0,"blksize",0,"1428",0
OACK_1428	DB 0,6,"blksize",0,"1428",0
OACK_1428_END
OACK_8		DB 0,6,"blksize",0,"8",0
OACK_512	DB 0,6,"blksize",0,"512",0
OACK_UPPER	DB 0,6,"BLKSIZE",0,"512",0
OACK_TOO_BIG	DB 0,6,"blksize",0,"1429",0
OACK_TOO_BIG_END
OACK_EXTRA	DB 0,6,"blksize",0,"512",0,"timeout",0,"1",0
OACK_EXTRA_END
OACK_BAD_NAME	DB 0,6,"timeout",0,"512",0
OACK_EMPTY	DB 0,6,"blksize",0,0
BAD_ERROR	DB 0,5,0,1,"missing"
BAD_ERROR_END
ERR_TEXT	DB "bad"

	INCLUDE "ethernet.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "udp.asm"
	INCLUDE "tftp.asm"
