; Executable TCP header/checksum/MSS vectors for z88dk-ticks.
; SPDX-License-Identifier: BSD-3-Clause

	DEFINE RUNTIME_BASE 0xB000
	DEVICE NOSLOT64K
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "ip_icmp.inc"
	INCLUDE "tcp.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001
WORK		EQU 0x8000
BUILD_DESC	EQU 0x9000
PARSE_DESC	EQU 0x9040
PARSED_SEQ	EQU 0x9080
PARSED_ACK	EQU 0x9084

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	LD	HL,WORK
	LD	(BUILD_DESC+TCPB_BUFFER),HL
	LD	HL,600
	LD	(BUILD_DESC+TCPB_CAPACITY),HL
	LD	HL,SOURCE_IP
	LD	(BUILD_DESC+TCPB_SOURCE_IP),HL
	LD	HL,DEST_IP
	LD	(BUILD_DESC+TCPB_DESTINATION_IP),HL
	LD	HL,49152
	LD	(BUILD_DESC+TCPB_SOURCE_PORT),HL
	LD	HL,8080
	LD	(BUILD_DESC+TCPB_DESTINATION_PORT),HL
	LD	HL,SEQ
	LD	(BUILD_DESC+TCPB_SEQUENCE),HL
	LD	HL,ACK
	LD	(BUILD_DESC+TCPB_ACKNOWLEDGEMENT),HL
	LD	HL,0
	LD	(BUILD_DESC+TCPB_PAYLOAD_LENGTH),HL
	LD	A,TCP_FLAG_SYN
	LD	(BUILD_DESC+TCPB_FLAGS),A
	LD	HL,TCP_MSS
	LD	(BUILD_DESC+TCPB_WINDOW),HL
	LD	(BUILD_DESC+TCPB_MSS),HL
	LD	HL,BUILD_DESC
	CALL	@TCP.BUILD
	JP	C,FAIL_1
	LD	HL,TCP_SYN_HEADER_LENGTH
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_1
	LD	A,(WORK+12)
	CP	0x60
	JP	NZ,FAIL_1
	LD	A,(WORK+20)
	CP	2
	JP	NZ,FAIL_1
	LD	A,(WORK+22)
	CP	2
	JP	NZ,FAIL_1
	LD	A,(WORK+23)
	CP	0x18
	JP	NZ,FAIL_1

	CALL	SET_PARSE
	LD	HL,PARSE_DESC
	CALL	@TCP.PARSE
	JP	C,FAIL_2
	LD	A,(PARSE_DESC+TCPP_FLAGS)
	CP	TCP_FLAG_SYN
	JP	NZ,FAIL_2
	LD	HL,(PARSE_DESC+TCPP_MSS)
	LD	DE,TCP_MSS
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_2
	LD	HL,PARSED_SEQ
	LD	DE,SEQ
	CALL	ASSERT4
	JP	NZ,FAIL_2

	; Data header with odd payload exercises pseudo-header checksum folding.
	LD	HL,0
	LD	(BUILD_DESC+TCPB_MSS),HL
	LD	HL,3
	LD	(BUILD_DESC+TCPB_PAYLOAD_LENGTH),HL
	LD	A,TCP_FLAG_PSH|TCP_FLAG_ACK
	LD	(BUILD_DESC+TCPB_FLAGS),A
	LD	HL,WORK+TCP_HEADER_LENGTH
	LD	(HL),0x11
	INC	HL
	LD	(HL),0x22
	INC	HL
	LD	(HL),0x33
	LD	HL,BUILD_DESC
	CALL	@TCP.BUILD
	JP	C,FAIL_3
	LD	HL,TCP_HEADER_LENGTH+3
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_3
	CALL	SET_PARSE
	LD	HL,TCP_HEADER_LENGTH+3
	LD	(PARSE_DESC+TCPP_LENGTH),HL
	LD	HL,PARSE_DESC
	CALL	@TCP.PARSE
	JP	C,FAIL_3
	LD	HL,(PARSE_DESC+TCPP_PAYLOAD_LENGTH)
	LD	DE,3
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_3
	LD	HL,(PARSE_DESC+TCPP_PAYLOAD)
	LD	A,(HL)
	CP	0x11
	JP	NZ,FAIL_3

	; Corruption and malformed data offset must be rejected.
	LD	A,(WORK+TCP_HEADER_LENGTH)
	XOR	0x80
	LD	(WORK+TCP_HEADER_LENGTH),A
	LD	HL,PARSE_DESC
	CALL	@TCP.PARSE
	JP	NC,FAIL_4
	LD	A,(WORK+TCP_HEADER_LENGTH)
	XOR	0x80
	LD	(WORK+TCP_HEADER_LENGTH),A
	LD	A,(WORK+12)
	LD	(SAVED_OFFSET),A
	LD	A,0x40
	LD	(WORK+12),A
	LD	HL,PARSE_DESC
	CALL	@TCP.PARSE
	JP	NC,FAIL_4
	LD	A,(SAVED_OFFSET)
	LD	(WORK+12),A

	; Buffer wrap/window and zero ports are rejected before writes.
	LD	HL,0xBFF8
	LD	(BUILD_DESC+TCPB_BUFFER),HL
	LD	HL,64
	LD	(BUILD_DESC+TCPB_CAPACITY),HL
	LD	HL,BUILD_DESC
	CALL	@TCP.BUILD
	JP	NC,FAIL_5
	LD	HL,WORK
	LD	(BUILD_DESC+TCPB_BUFFER),HL
	LD	HL,600
	LD	(BUILD_DESC+TCPB_CAPACITY),HL
	LD	HL,0
	LD	(BUILD_DESC+TCPB_SOURCE_PORT),HL
	LD	HL,BUILD_DESC
	CALL	@TCP.BUILD
	JP	NC,FAIL_5

	XOR	A
	LD	(TEST_RESULT),A
	LD	A,0xA5
	LD	(TEST_COMPLETE),A
TEST_DONE
	HALT
	JR	TEST_DONE

SET_PARSE
	LD	HL,WORK
	LD	(PARSE_DESC+TCPP_BUFFER),HL
	LD	HL,TCP_SYN_HEADER_LENGTH
	LD	(PARSE_DESC+TCPP_LENGTH),HL
	LD	HL,SOURCE_IP
	LD	(PARSE_DESC+TCPP_SOURCE_IP),HL
	LD	HL,DEST_IP
	LD	(PARSE_DESC+TCPP_DESTINATION_IP),HL
	LD	HL,49152
	LD	(PARSE_DESC+TCPP_EXPECT_SOURCE_PORT),HL
	LD	HL,8080
	LD	(PARSE_DESC+TCPP_EXPECT_DEST_PORT),HL
	LD	HL,PARSED_SEQ
	LD	(PARSE_DESC+TCPP_SEQUENCE),HL
	LD	HL,PARSED_ACK
	LD	(PARSE_DESC+TCPP_ACKNOWLEDGEMENT),HL
	RET

ASSERT4
	LD	B,4
.LOOP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.LOOP
	RET

FAIL_1
	LD	A,1
	JR	FAIL
FAIL_2
	LD	A,2
	JR	FAIL
FAIL_3
	LD	A,3
	JR	FAIL
FAIL_4
	LD	A,4
	JR	FAIL
FAIL_5
	LD	A,5
FAIL
	LD	(TEST_RESULT),A
	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	JR	TEST_DONE

SOURCE_IP	DB 192,0,2,10
DEST_IP	DB 192,0,2,1
SEQ		DB 0x12,0x34,0x56,0x78
ACK		DB 0x9A,0xBC,0xDE,0xF0
SAVED_OFFSET	DB 0

	INCLUDE "ethernet.asm"
	INCLUDE "ipv4.asm"
	INCLUDE "tcp.asm"
