; Executable protocol/config/cache vectors for z88dk-ticks.
; SPDX-License-Identifier: BSD-3-Clause

	DEVICE NOSLOT64K
	INCLUDE "dss.inc"
	INCLUDE "memory.inc"
	INCLUDE "el3.inc"
	INCLUDE "netdrv.inc"
	INCLUDE "netcfg.inc"

TEST_RESULT	EQU 0xC000
TEST_COMPLETE	EQU 0xC001
WORK		EQU 0x8000

	MACRO FAIL_IF_C target
	JP C,target
	ENDM

	ORG 0x4000
TEST_START
	LD	A,0xFF
	LD	(TEST_RESULT),A
	XOR	A
	LD	(TEST_COMPLETE),A

	; RFC 1071 odd-length checksum: ASCII "123456789" -> F62A.
	LD	HL,CHECKSUM_TEXT
	LD	BC,9
	CALL	@ETHERNET.CHECKSUM
	LD	DE,0xF62A
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_1

	; Even length whose carry must wrap end-around: FF FF 00 02 sums to
	; 0002h, so the complement is FFFDh.
	LD	HL,CARRY_BYTES
	LD	BC,4
	CALL	@ETHERNET.CHECKSUM
	LD	DE,0xFFFD
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_7

	; Saturation: FFFFh + FFFFh must fold to a zero checksum, not FFFFh.
	LD	HL,ONES_BYTES
	LD	BC,4
	CALL	@ETHERNET.CHECKSUM
	LD	A,H
	OR	L
	JP	NZ,FAIL_8

	; 600 bytes of 01h is 300 words of 0101h = 12D2Ch, folding to 2D2Dh and
	; complementing to D2D2h. Past 256 words this is the only case that
	; reaches ACCUMULATE's outer pass.
	LD	HL,WORK
	LD	DE,WORK+1
	LD	BC,600
	LD	(HL),1
	LDIR
	LD	HL,WORK
	LD	BC,600
	CALL	@ETHERNET.CHECKSUM
	LD	DE,0xD2D2
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_9

	; The same buffer at an odd length pads the trailing byte as a high
	; half: 2D2Dh + 0100h = 2E2Dh, complement D1D2h.
	LD	HL,WORK
	LD	BC,601
	CALL	@ETHERNET.CHECKSUM
	LD	DE,0xD1D2
	OR	A
	SBC	HL,DE
	JP	NZ,FAIL_10

	LD	HL,LOCAL_IP
	LD	DE,NET_LOCAL_IP
	LD	BC,4
	LDIR
	LD	HL,MASK
	LD	DE,NET_NETMASK
	LD	BC,4
	LDIR
	LD	HL,GATEWAY
	LD	DE,NET_GATEWAY
	LD	BC,4
	LDIR
	LD	HL,SAME_TARGET
	CALL	@ARP.SELECT_NEXT_HOP
	FAIL_IF_C FAIL_2
	OR	A
	JP	NZ,FAIL_2
	LD	HL,NET_NEXT_HOP_IP
	LD	DE,SAME_TARGET
	CALL	ASSERT4
	JP	NZ,FAIL_2
	LD	HL,OFF_TARGET
	CALL	@ARP.SELECT_NEXT_HOP
	FAIL_IF_C FAIL_2
	LD	HL,NET_NEXT_HOP_IP
	LD	DE,GATEWAY
	CALL	ASSERT4
	JP	NZ,FAIL_2
	LD	HL,SUBNET_BCAST
	CALL	@ARP.SELECT_NEXT_HOP
	FAIL_IF_C FAIL_2
	CP	1
	JP	NZ,FAIL_2
	LD	HL,NET_RESULT_MAC
	LD	B,6
	LD	A,0xFF
.BCAST_MAC
	CP	(HL)
	JP	NZ,FAIL_2
	INC	HL
	DJNZ	.BCAST_MAC

	; Request framing and network byte order.
	LD	HL,TEST_MAC
	LD	DE,NETDRV_STATION_MAC
	LD	BC,6
	LDIR
	LD	DE,WORK
	LD	HL,SAME_TARGET
	CALL	@ARP.BUILD_REQUEST
	LD	A,B
	OR	A
	JP	NZ,FAIL_3
	LD	A,C
	CP	60
	JP	NZ,FAIL_3
	LD	A,(WORK+12)
	CP	0x08
	JP	NZ,FAIL_3
	LD	A,(WORK+13)
	CP	0x06
	JP	NZ,FAIL_3
	LD	A,(WORK+21)
	CP	1
	JP	NZ,FAIL_3
	; A /32 has no host bits and therefore no subnet-broadcast address.
	LD	HL,MASK32
	LD	DE,NET_NETMASK
	LD	BC,4
	LDIR
	LD	HL,LOCAL_IP
	CALL	@ARP.SELECT_NEXT_HOP
	FAIL_IF_C FAIL_3
	OR	A
	JP	NZ,FAIL_3
	LD	HL,MASK
	LD	DE,NET_NETMASK
	LD	BC,4
	LDIR

	; Four-entry cache hit, expiry and oldest-entry eviction.
	CALL	@ARP.CLEAR_CACHE
	LD	HL,CACHE_IP1
	LD	DE,CACHE_MAC1
	LD	BC,10
	CALL	@ARP.CACHE_INSERT
	LD	HL,CACHE_IP1
	LD	BC,60
	CALL	@ARP.CACHE_LOOKUP
	FAIL_IF_C FAIL_4
	LD	HL,CACHE_IP1
	LD	BC,71
	CALL	@ARP.CACHE_LOOKUP
	JP	NC,FAIL_4
	; Reinserting the same IP updates in place instead of leaving a stale hit.
	CALL	@ARP.CLEAR_CACHE
	LD	HL,CACHE_IP1
	LD	DE,CACHE_MAC1
	LD	BC,10
	CALL	@ARP.CACHE_INSERT
	LD	HL,CACHE_IP1
	LD	DE,CACHE_MAC5
	LD	BC,20
	CALL	@ARP.CACHE_INSERT
	LD	HL,CACHE_IP1
	LD	BC,20
	CALL	@ARP.CACHE_LOOKUP
	FAIL_IF_C FAIL_4
	LD	HL,NET_RESULT_MAC
	LD	DE,CACHE_MAC5
	LD	B,6
.UPDATED_MAC
	LD	A,(DE)
	CP	(HL)
	JP	NZ,FAIL_4
	INC	DE
	INC	HL
	DJNZ	.UPDATED_MAC
	CALL	@ARP.CLEAR_CACHE
	LD	IX,CACHE_IP1
	LD	IY,CACHE_MAC1
	LD	C,1
	LD	B,4
.FILL_CACHE
	PUSH	BC,IX,IY
	PUSH	IX
	POP	HL
	PUSH	IY
	POP	DE
	LD	B,0
	CALL	@ARP.CACHE_INSERT
	POP	IY,IX,BC
	LD	DE,4
	ADD	IX,DE
	LD	DE,6
	ADD	IY,DE
	INC	C
	DJNZ	.FILL_CACHE
	LD	HL,CACHE_IP5
	LD	DE,CACHE_MAC5
	LD	BC,20
	CALL	@ARP.CACHE_INSERT
	LD	HL,CACHE_IP1
	LD	BC,20
	CALL	@ARP.CACHE_LOOKUP
	JP	NC,FAIL_4
	LD	HL,CACHE_IP5
	LD	BC,20
	CALL	@ARP.CACHE_LOOKUP
	FAIL_IF_C FAIL_4

	; DHCPDISCOVER exact fixed fields, IPv4 and nonzero UDP checksum.
	LD	HL,XID_VALUE
	LD	DE,DHCP_XID
	LD	BC,4
	LDIR
	LD	DE,WORK
	LD	HL,TEST_MAC
	CALL	@DHCP.BUILD_DISCOVER
	LD	HL,292
	OR	A
	SBC	HL,BC
	JP	NZ,FAIL_5
	LD	A,(WORK+12)
	CP	0x08
	JP	NZ,FAIL_5
	LD	A,(WORK+13)
	OR	A
	JP	NZ,FAIL_5
	LD	A,(WORK+34)
	OR	A
	JP	NZ,FAIL_5
	LD	A,(WORK+35)
	CP	68
	JP	NZ,FAIL_5
	LD	A,(WORK+37)
	CP	67
	JP	NZ,FAIL_5
	LD	HL,WORK+14
	LD	BC,20
	CALL	@ETHERNET.VERIFY_CHECKSUM
	FAIL_IF_C FAIL_5
	LD	HL,WORK+14
	LD	A,(WORK+38)
	LD	B,A
	LD	A,(WORK+39)
	LD	C,A
	CALL	@ETHERNET.UDP_IPV4_CHECKSUM
	LD	A,H
	OR	L
	JP	NZ,FAIL_5
	LD	A,(WORK+282)
	CP	53
	JP	NZ,FAIL_5
	LD	A,(WORK+284)
	CP	DHCP_DISCOVER
	JP	NZ,FAIL_5

	; Config parser: LF/comments/unknown/duplicate; last IP wins.
	LD	HL,CONFIG_TEXT
	LD	BC,CONFIG_END-CONFIG_TEXT
	CALL	@NETPARSE.PARSE
	FAIL_IF_C FAIL_6
	LD	A,(NETCFG_WARNINGS)
	CP	2
	JP	NZ,FAIL_6
	LD	A,(NETDRV_CONFIG+NETDRV_CFG_MODE)
	CP	NETDRV_MODE_AUTO
	JP	NZ,FAIL_6
	LD	HL,NCV_IP_SRC
	LD	DE,DHCP_TEXT
	CALL	@NETPARSE.STR_EQ_CI
	JP	NZ,FAIL_6

	LD	A,0xA5
	LD	(TEST_COMPLETE),A
	XOR	A
	LD	(TEST_RESULT),A
	JR	TEST_DONE

ASSERT4
	LD	B,4
.LOOP
	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	.LOOP
	RET

FAIL_1:	LD A,1
	JR FAIL
FAIL_2:	LD A,2
	JR FAIL
FAIL_3:	LD A,3
	JR FAIL
FAIL_4:	LD A,4
	JR FAIL
FAIL_5:	LD A,5
	JR FAIL
FAIL_6:	LD A,6
	JR FAIL
FAIL_7:	LD A,7
	JR FAIL
FAIL_8:	LD A,8
	JR FAIL
FAIL_9:	LD A,9
	JR FAIL
FAIL_10: LD A,10
FAIL:	LD (TEST_RESULT),A
TEST_DONE
	NOP

CHECKSUM_TEXT	DB "123456789"
CARRY_BYTES	DB 0xFF,0xFF,0x00,0x02
ONES_BYTES	DB 0xFF,0xFF,0xFF,0xFF
LOCAL_IP	DB 192,168,7,2
MASK		DB 255,255,255,0
MASK32		DB 255,255,255,255
GATEWAY		DB 192,168,7,1
SAME_TARGET	DB 192,168,7,44
OFF_TARGET	DB 8,8,8,8
SUBNET_BCAST	DB 192,168,7,255
TEST_MAC	DB 2,0x60,0x8C,0x12,0x34,0x56
XID_VALUE	DB 0x12,0x34,0x56,0x78
CACHE_IP1	DB 10,0,0,1, 10,0,0,2, 10,0,0,3, 10,0,0,4
CACHE_IP5	DB 10,0,0,5
CACHE_MAC1	DB 2,0,0,0,0,1, 2,0,0,0,0,2, 2,0,0,0,0,3, 2,0,0,0,0,4
CACHE_MAC5	DB 2,0,0,0,0,5
DHCP_TEXT	DB "DHCP",0
CONFIG_TEXT
	DB "# test",10
	DB "NET=509B",10,"HW=AUTO",10,"IDPORT=#110",10
	DB "IP=10.0.0.1",10,"UNKNOWN=x",10,"IP=DHCP",10
CONFIG_END

	INCLUDE "ethernet.asm"
	INCLUDE "../src/lib/arp.asm"
	INCLUDE "dhcp.asm"
	INCLUDE "netparse.asm"
	INCLUDE "netparse_file.asm"
	INCLUDE "el3_algorithms.asm"
